### ISSUE TITLE
EXPECT_CALL(...) in combination with EXPECT_DEATH(...) will result in a incorrect function call count 

### ISSUE THREAD

**Issue by nyxus** [google/googletest#1004]
Consider the following function:

```
std::shared_pointer<...> Mice::Bar()
{...}

void Cat::Foo()
{
    if (Mice.Bar() != nullptr)
    {
      ...
    }
    else
    {
      assert(false);
    }
}
```

Has the following unit test:
```
TEST_F(CatTest, TestCatDeath)
{
  EXPECT_CALL(MiceMock, Bar()).WillOnce(Return(std::shared_pointer<...>()));
  EXPECT_DEATH(Cat->foo(), ...);
}
```

I would expect that this unit test passes the test.
But instead, the test fails on the function call count:
```
Actual function call count doesn't match EXPECT_CALL(MiceMock, Bar())...
         Expected: to be called once
         Actual: never called - unsatisfied and active
```

With `ASSERT_DEATH` and `(ASSERT|EXPECT)_DEATH_IF_SUPPORTED` I noticed the same incorrect behaviour.  
Therefore, I guess this is a bug?

Note: I'm using Gtest v1.8 build with GCC (Ubuntu 4.8.5-2ubuntu1~14.04.1) 4.8.5

A (temporary) workaround is to use `ON_CALL(MiceMock, Bar()).WillByDefault(Return(...))`. But this does not do the check if `Mice.Bar()` is actually called.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by xman1979** [comment]
the solution is to put EXPECT_CALL in a closure, eg:

auto op = [this] {
   EXPECT_CALL();
  ...
};

EXPECT_DEATH(op(), ...)

**Comment by slymas** [comment]
Thank you @xman1979 for posting this! :) 
I haven't thought about using a lambda but it makes total sense.

I also needed to use `::testing::Mock::AllowLeak(myMockObject);` before the EXPECT_DEATH to be able to delete the mock in the original thread and let its expectations be verified.

**Comment by jackgo73** [comment]
> the solution is to put EXPECT_CALL in a closure, eg:
> 
> auto op = [this] {
> EXPECT_CALL();
> ...
> };
> 
> EXPECT_DEATH(op(), ...)

thanks!
