### ISSUE TITLE
Question re. status of project

### ISSUE THREAD

**Issue by PerMalmberg** [google/googletest#1010]
Hi,

As gtest integrates with CLion we're considering using it, but I see that this project hasn't built successfully  the last three months (https://ci.appveyor.com/project/BillyDonahue/googletest/history). As such, it makes me a bit hesitant to use it.

Could someone please shed some light on the current status? Is there an ongoing effort to make it build?

**Comment by ilya-kolpakov** [comment]
I am wondering the same thing.

**Comment by KindDragon** [comment]
You can build it if you apply PR #996 and #811. But no one want merge them :)

**Comment by PerMalmberg** [comment]
Yeah, I saw those. Considering the age of #811 it makes you wonder as to the commitment from Google's side. Although CLion integration is nice, I'd rather go with something that I don't have to fix first.

**Comment by dankegel** [comment]
https://github.com/google/googletest/pull/996 was merged 4 days ago.  So I think the project is live, it just needs really simple, focused MR's, and tincture of time.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
