### ISSUE TITLE
gtest.a vs gtest_main.a inconsistency

### ISSUE THREAD

**Issue by travisdowns** [google/googletest#1015]
The `make/Makefile` build and the `CMake` build generate `gtest_main.a` very differently: the `make` build includes all of `gtest.a` in `gtest_main.a` so you _only_ need to link to `gtest_main.a`, while in the `CMake` build the `gtest_main.a` is very small and only includes the `main()` function itself, so you need to link to both `gtest.a` and `gtest_main.a`.

Since `CMake` is the primary build system (from what I understand), one could assume the latter approach is the correct one, but the documentation seems to contradict this - directly in the `CMakeLists.txt` file we have
```
# Defines the gtest & gtest_main libraries.  User tests should link
# with one of them.
```

Some more details in [this SO answer](http://stackoverflow.com/a/42191014/149138) which also shows some of the confusion this has sowed.

**Comment by absassi** [comment]
For the sake of completeness, I'd like to add that the `gmock_main` library does include `gmock` and `gtest` when built by `CMake` or by `make/Makefile`. When using Autotools, the `gtest_main` built by `Makefile.am` includes `gtest` (like `make/Makefile`) and the `gmock_main` includes `gmock` but not `gtest` (unlike any other).

To summarize, the contents of each library are:

Build method | `gtest` | `gtest_main` | `gmock` | `gmock_main`
------------ | - | - | - | -
CMake | `gtest` | `gtest_main` | `gtest`, `gmock` | `gtest`, `gmock`, `gmock_main`
Makefile | `gtest` | `gtest`, `gtest_main` | `gtest`, `gmock` | `gtest`, `gmock`, `gmock_main`
Autotools | `gtest` | `gtest`, `gtest_main` | `gmock` | `gmock`, `gmock_main`
