### ISSUE TITLE
XML output should support JUnit compatible schema as well

### ISSUE THREAD

**Issue by gayanpathirage** [google/googletest#1017]
Currently generated XML does not comply with [JUnit-Schema](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd) and this is critically required for integrations with SonarQube, Jenkins and Bamboo like tools. 

Preferred option: --gtest_output=**junit_xml**:output.xml

NOTE: There are other ways to do this via [XLTs and manual scripts](http://stackoverflow.com/questions/6329215/how-to-get-ctest-results-in-hudson-jenkins)

**Comment by ButchDean** [comment]
Are there any updates on this? It would be very helpful!

**Comment by FlashSheridan** [comment]
According to 
https://stackoverflow.com/a/42245874/28312, there’s a workaround, which I haven’t tried yet:
https://stackoverflow.com/questions/6329215/how-to-get-ctest-results-in-hudson-jenkins

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by domino14** [comment]
plz fix
