### ISSUE TITLE
EXPECT_EQ argument handling not getting correct argument count

### ISSUE THREAD

**Issue by limitedAtonement** [google/googletest#1022]
std::vector<int> a {1,2};
    EXPECT_EQ(a, std::vector<int>{1,3, 4});

fails to compile (in gcc 6.3.1) with the following error:

> error: macro "EXPECT_EQ" passed 3 arguments, but takes just 2

    std::vector<int> a {1,2};
    EXPECT_EQ(a, (std::vector<int>{1,3, 4}));

compiles as expected. I'm guessing the expansion of this and many other macros could benefit from the typical `()` treatment.

**Comment by sbenzaquen** [comment]
On Mon, Feb 20, 2017 at 1:31 PM, limitedAtonement <notifications@github.com>
wrote:

> std::vector<int> a {1,2};
> EXPECT_EQ(a, std::vector<int>{1,3, 4});
>
> fails to compile (in gcc 6.3.1) with the following error:
>
> error: macro "EXPECT_EQ" passed 3 arguments, but takes just 2
>
> std::vector<int> a {1,2};
> EXPECT_EQ(a, (std::vector<int>{1,3, 4}));
>
> compiles as expected. I'm guessing the expansion of this and many other
> macros could benefit from the typical () treatment.
>

This can't be fixed in the definition of the macro.
The macro takes two arguments and you were passing more than that. It fails
before the macro is even invoked.
The preprocessor does not understand C++. Curly braces are not taken into
account for argument grouping, only parens.

**Comment by limitedAtonement** [comment]
Thanks!

**Comment by teusbenschop** [comment]
What works in my case is this bit of code:

```
vector <int> data {2, 3, 4];
EXPECT_EQ ((vector <int>{2, 3, 4}), chapters);
```

**Comment by limitedAtonement** [comment]
@teusbenschop Thank you for chiming in. I noted that in my original question.

**Comment by teusbenschop** [comment]
> @teusbenschop Thank you for chiming in. I noted that in my original question.

You are right, I had overlooked that bit :)

**Comment by csisy** [comment]
I just came across the same problem. Isn't it fixable on the macro itself? I mean as the OP stated, a very common solution is to enclose the arguments of a macro in `()` so it doesn't need to be done by the caller.
