### ISSUE TITLE
Google Test framework over TI compiler 

### ISSUE THREAD

**Issue by mabnfeo** [google/googletest#1024]
I am currently trying to compile google test framework over Code Composer studio using compiler "TI v5.1.8" whereas I am able to compile the framework using the same software but with compiler "GNU v4.7.4".

By using compiler "TI v5.1.8" I get errors like "sys/types.h" is missing and even if I bypass it (making an empty header file with the same name) than I get "regex.h" is missing.

As anyone tried compiling google test framework with compiler "TI v5.1.8" using Code composer studio? I shall be very thankful for the help.

**Comment by neemashakya** [comment]
Hi @mabnfeo , did you find any answers? I am trying to compile google test framework with TI v16.9.1 compiler but so far no luck!

**Comment by mabnfeo** [comment]
Hi @neemashakya , Nop... I switched to CUnit as Ti compiler does not have the required files to make Google test framework compile. I tried it with GNU v4.7 and that worked. By the way good luck to you.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
