### ISSUE TITLE
Links in googlemock/README.md broken

### ISSUE THREAD

**Issue by BeckmaR** [google/googletest#1025]
Hello,

it looks like the following links in [said file](/google/googletest/blob/master/googlemock/README.md) under "Getting Started" are broken: "basics", "Google Mock for Dummies", "CheatSheet" and "CookBook" return a 404.

Regards,
René

**Comment by IainHaslam** [comment]
@BeckmaR - this was resolved by ba638689e40fc60c2e5194fc777bf30541deeff8 - are you able to close it?
