### ISSUE TITLE
comparison of integers of different signs

### ISSUE THREAD

**Issue by lczech** [google/googletest#1026]
Using googltest 1.8 and Clang 3.9.1 on Ubuntu 14.04, I get

```
googletest/include/gtest/gtest.h:1392:11: warning: comparison of integers of
      different signs: 'const int' and 'const unsigned long' [-Wsign-compare]
  if (lhs == rhs) {
      ~~~ ^  ~~~
```

It's probably not a big issue, but still a little smelly ;-)

**Comment by henryiii** [comment]
This shows up even with something like:
```cpp
EXPECT_EQ(1, output.size());
```

(Where 1 is just an integral constant and should not have a sign)

**Comment by p-groarke** [comment]
Same here on clang++. Would you like a PR?

**Comment by arjangupta** [comment]
Does anyone know a fix for this yet? I was able to fix the issue by using suffixes. For example, I was getting the warning for the following line:
`ASSERT_EQ(output.size(), 0);`
And I fixed it by doing this:
`ASSERT_EQ(empty_orig.size(), 0u);`

**Comment by xpahos** [comment]
@arjangupta comment 135 line of CMakeLists.txt with add_cxx_compiler_flag(-Werror RELEASE)

**Comment by arjangupta** [comment]
@xpahos thank you!

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
