### ISSUE TITLE
Some test executables crash on exit even if no tests run when building gtest as shared library on VS2015

### ISSUE THREAD

**Issue by dankegel** [google/googletest#1035]
I may be abusing the bug tracking system as documentation here, but it at first looked like a bug,
so maybe that's appropriate.

I'm maintaining a largish set of C/C++ libraries and executables on mac, linux, and windows.
It has quite a few test programs, mostly using google test.
It has in the past been run through valgrind and coverity routinely, and is fairly clean.
Everything is built suitable for producing shared libraries, even when building static libraries,
because some of our users are in turn shared libraries.
All was well... until I ported to Visual Studio 2015, when two of the google test programs
started crashing on exit, even if GTEST_FILTER was set so that no actual test cases ran.

This happens both with the old gtest I'd been using, and with the tip of master
(plus one commit to fix some vs2015 incompatibilities, see #1033).
(Updating to the tip of master revealed that I had long ago switched gtest
to use cxx_shared_library instead of cxx_library; I did that again with the fresh
stuff to avoid linker errors from clashing c runtime library settings.  Hold that thought.)

A debug build crashes even sooner, when the tests are being registered.  Here's a stack trace using the source from #1033, fused and built as shared libraries:
```
gtest.dll!free_dbg_nolock(void * const block, const int block_use) Line 980	C++
gtest.dll!_free_dbg(void * block, int block_use) Line 1011	C++
[External Code]	
gtest.dll!testing::internal::MakeAndRegisterTestInfo(const char * test_case_name, const char * name, const char * type_param, const char * value_param, testing::internal::CodeLocation code_location, const void * fixture_class_id, void(*)() set_up_tc, void(*)() tear_down_tc, testing::internal::TestFactoryBase * factory) Line 4005	C++
RefCountedTest.exe!`dynamic initializer for '`anonymous namespace'::RefCountedTest_SingleObject_Test::test_info_''() Line 30	C++
```
I fear I'm being bitten by the ol' demon "mixing magical static constructors with shared libraries does surprising things".  (Hence my frequent 'static constructors considered harmful' rant.)

Next I tried a more kosher fix for my c runtime library mismatch problem, i.e.
I reverted my googletest/CMakeLists.txt hack, returning to using cxx_library(gtest),
and added set(gtest_force_shared_crt TRUE)  in my outer CMakeLists.txt
before add_subdirectory(googletest).
That didn't work because I had forgotten that gtest_force_shared_crt is a cmake cache variable, and
those have to be set specially (cue complaints about complex but free tools you can't live without),
so I tried
set(gtest_force_shared_crt TRUE CACHE BOOL "let's use /MD, ok?")
and that linked properly.  Whew, back on the straight and narrow.  And, bonus, it solved the crashes.

So I guess this is a documentation bug, but since
https://github.com/google/googletest/blob/master/googletest/README.md
already shows how to use gtest_force_shared_crt properly, just filing this bug
and marking it FIXED is probably enough; people who run into this situation
and google the error messages have a good chance of running into this bug
report and getting a clue.  At most, that readme could sprout a TROUBLESHOOTING
section with an entry
```
Q. I tried building gtest as a shared library, and on some platforms I get strange crashes on exit, 
even if GTEST_FILTER was set to avoid running any tests.
A. gtest's CMakeLists.txt builds gtest as a static library for good reason;
gtest uses static constructors and destructors, and if you build gtest as a shared
library, the order they execute in is somewhat undefined, which can lead to crashes.
On Windows, you may need to set gtest_force_shared_crt to avoid linking problems, see above.
```

**Comment by gennadiycivil** [comment]
@dankegel thank you for this and sorry for the very long wait. I recommend submitting a PR with the documentation fix, having this in an issue is not optimal.
Thanks
