### ISSUE TITLE
gtest.h generates error on visual studio 2017

### ISSUE THREAD

**Issue by bmanga** [google/googletest#1036]
gtest.h produces error when using visual studio 2017 with the latest standard compiler switch (/std:c++latest). This is because the switch removes the tr1 namespace (while the __cplusplus macro value is still 199711L). Hence gtest fails looking for std::tr1::tuple and friends.
This can be worked around by defining  GTEST_HAS_TR1_TUPLE to 0 and GTEST_HAS_STD_TUPLE to 1, although it would be nice if gtest could figure it out itself.

**Comment by KindDragon** [comment]
Can you try with PR #811?

**Comment by bmanga** [comment]
That works, thanks! Any reasons why that's not been merged yet?

**Comment by KindDragon** [comment]
IDK, no one responding :)

**Comment by KindDragon** [comment]
Can be closed. PR #1218 fixed this

**Comment by tobiaskohlbau** [comment]
Looks like it's not fixed by #1218. With VS 15.5 Preview 5 I still get the warning.

```googletest\googletest\include\gtest/gtest-printers.h(617): warning C4996: 'std::tr1': warning STL4002: The non-Standard std::tr1 namespace and TR1-only machinery are deprecated and will be REMOVED. You can define _SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING to acknowledge that you have received this warning.```

**Comment by giladreich** [comment]
Definitely not fixed yet.

**Comment by janissimsons** [comment]
Still not fixed.

**Comment by gennadiycivil** [comment]
TR1 is gone now, closing
