### ISSUE TITLE
Error when building a project for BDS X5

### ISSUE THREAD

**Issue by JMorrison911** [google/googletest#1037]
1) gtest.lib. Unit
a) ------------------------gtest.lib. Unit -----------------------
[bcc32 Warning] W8123 Path 'c:\program files (x86)\embarcadero\rad studio\12.0\include\vcl' not found - path ignored in option '-I'
[bcc32 Warning] W8123 Path 'C:\Program Files (x86)\FastReports\LibD19' not found - path ignored in option '-I'
[bcc32 Warning] W8123 Path 'c:\program files (x86)\embarcadero\rad studio\12.0\include\vcl' not found - path ignored in option '-I'
[bcc32 Warning] W8123 Path 'C:\Program Files (x86)\FastReports\LibD19' not found - path ignored in option '-I'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'TestPartResult'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'Message'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'TestPartResult'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'TestPartResult'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] utility(15): E2247 'testing::internal::scoped_ptr<string>::scoped_ptr(const testing::internal::scoped_ptr<string> &)' is not accessible
[bcc32 Error] utility(17): E2247 'operator testing::internal::scoped_ptr<string>::=(const testing::internal::scoped_ptr<string> &)' is not accessible
[bcc32 Error] utility(18): E2247 'operator testing::internal::scoped_ptr<string>::=(const testing::internal::scoped_ptr<string> &)' is not accessible
[bcc32 Error] utility(15): E2247 'testing::internal::scoped_ptr<string>::scoped_ptr(const testing::internal::scoped_ptr<string> &)' is not accessible
[bcc32 Error] utility(17): E2247 'operator testing::internal::scoped_ptr<string>::=(const testing::internal::scoped_ptr<string> &)' is not accessible
[bcc32 Error] utility(18): E2247 'operator testing::internal::scoped_ptr<string>::=(const testing::internal::scoped_ptr<string> &)' is not accessible
[bcc32 Error] gtest-internal.h(885): E2396 Template argument must be a constant expression
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'Message'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'Message'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest.cc(2109): E2285 Could not find a match for 'internal::Strings::vector(const char * const *,const char * const *)'
[bcc32 Error] gtest.cc(2109): E2285 Could not find a match for 'internal::Strings::vector(const char * const *,const char * const *)'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::_Smanip<int>'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest-message.h(131): E2094 'operator<<' not implemented in type 'std::stringstream' for arguments of type 'std::string'
[bcc32 Error] gtest.cc(3568): E2268 Call to undefined function 'localtime_r'
[bcc32 Error] gtest.cc(3568): E2228 Too many error or warning messages
b) ----------------------------------- utility ------------------------------------
[bcc32 Warning] W8123 Path 'c:\program files (x86)\embarcadero\rad studio\12.0\include\vcl' not found - path ignored in option '-I'
[bcc32 Warning] W8123 Path 'C:\Program Files (x86)\FastReports\LibD19' not found - path ignored in option '-I'
[bcc32 Warning] W8123 Path 'c:\program files (x86)\embarcadero\rad studio\12.0\include\vcl' not found - path ignored in option '-I'
[bcc32 Warning] W8123 Path 'C:\Program Files (x86)\FastReports\LibD19' not found - path ignored in option '-I'
[bcc32 Error] utility(15): E2247 'testing::internal::scoped_ptr<string>::scoped_ptr(const testing::internal::scoped_ptr<string> &)' is not accessible
[bcc32 Error] utility(17): E2247 'operator testing::internal::scoped_ptr<string>::=(const testing::internal::scoped_ptr<string> &)' is not accessible
[bcc32 Error] utility(18): E2247 'operator testing::internal::scoped_ptr<string>::=(const testing::internal::scoped_ptr<string> &)' is not accessible
[bcc32 Error] utility(15): E2247 'testing::internal::scoped_ptr<string>::scoped_ptr(const testing::internal::scoped_ptr<string> &)' is not accessible
[bcc32 Error] utility(17): E2247 'operator testing::internal::scoped_ptr<string>::=(const testing::internal::scoped_ptr<string> &)' is not accessible
[bcc32 Error] utility(18): E2247 'operator testing::internal::scoped_ptr<string>::=(const testing::internal::scoped_ptr<string> &)' is not accessible
[bcc32 Error] gtest-internal.h(885): E2396 Template argument must be a constant expression
[bcc32 Error] gtest.cc(2109): E2285 Could not find a match for 'internal::Strings::vector(const char * const *,const char * const *)'
[bcc32 Error] gtest.cc(2109): E2285 Could not find a match for 'internal::Strings::vector(const char * const *,const char * const *)'
[bcc32 Error] gtest.cc(3568): E2268 Call to undefined function 'localtime_r'
[bcc32 Error] gtest.cc(3613): E2268 Call to undefined function 'GetReservedAttributesForElement'
[bcc32 Error] gtest-test-part.cc(53): E2354 Two operands must evaluate to the same type
[bcc32 Error] gtest-test-part.cc(53): E2285 Could not find a match for 'std::string::basic_string(std::string&)'
[bcc32 Warning] gtest-test-part.cc(102): W8058 Cannot create pre-compiled header: code in header

2) gtest_unittest.exe
[bcc32 Error] gtest-internal.h(885): E2396 Template argument must be a constant expression
[bcc32 Error] gtest_unittest.cc(456): E2268 Call to undefined function 'setenv'
[bcc32 Error] gtest_unittest.cc(458): E2268 Call to undefined function 'unsetenv'
[bcc32 Error] gtest_unittest.cc(1305): E2268 Call to undefined function 'AddFailureInOtherThread'
[bcc32 Error] gtest_unittest.cc(1305): E2451 Undefined symbol 'FATAL_FAILURE'
[bcc32 Error] gtest_unittest.cc(1305): E2451 Undefined symbol 'FATAL_FAILURE'
[bcc32 Error] gtest-printers.h(856): E2299 Cannot generate template specialization from 'UniversalPrinter<T>'
[bcc32 Error] gtest-printers.h(856): E2379 Statement missing ;
[bcc32 Error] gtest.h(1522): E2285 Could not find a match for 'CmpHelperOpFailure<T1,T2>(const char *,const char *,const T1,const T1,const char *)'
[bcc32 Error] gtest.h(1522): E2285 Could not find a match for 'CmpHelperOpFailure<T1,T2>(const char *,const char *,const T1,const T1,const char *)'
[bcc32 Error] gtest.h(1526): E2285 Could not find a match for 'CmpHelperOpFailure<T1,T2>(const char *,const char *,const T1,const T1,const char *)'
[bcc32 Error] gtest.h(1526): E2285 Could not find a match for 'CmpHelperOpFailure<T1,T2>(const char *,const char *,const T1,const T1,const char *)'
[bcc32 Error] gtest.h(1524): E2285 Could not find a match for 'CmpHelperOpFailure<T1,T2>(const char *,const char *,const T1,const T1,const char *)'
[bcc32 Error] gtest.h(1524): E2285 Could not find a match for 'CmpHelperOpFailure<T1,T2>(const char *,const char *,const T1,const T1,const char *)'
[bcc32 Error] gtest.h(1530): E2285 Could not find a match for 'CmpHelperOpFailure<T1,T2>(const char *,const char *,const T1,const T1,const char *)'
[bcc32 Error] gtest.h(1530): E2285 Could not find a match for 'CmpHelperOpFailure<T1,T2>(const char *,const char *,const T1,const T1,const char *)'
[bcc32 Error] gtest.h(1528): E2285 Could not find a match for 'CmpHelperOpFailure<T1,T2>(const char *,const char *,const T1,const T1,const char *)'
[bcc32 Error] gtest.h(1528): E2285 Could not find a match for 'CmpHelperOpFailure<T1,T2>(const char *,const char *,const T1,const T1,const char *)'
[bcc32 Error] gtest-internal.h(885): E2396 Template argument must be a constant expression
[bcc32 Error] gtest-internal.h(885): E2396 Template argument must be a constant expression
[bcc32 Error] gtest-internal.h(885): E2396 Template argument must be a constant expression
[bcc32 Error] gtest.h(277): E2034 Cannot convert 'const ConvertibleToAssertionResult &' to 'bool'
[bcc32 Error] gtest-internal.h(885): E2396 Template argument must be a constant expression
[bcc32 Error] gtest_unittest.cc(5368): E2102 Cannot use template 'CodeLocationForTYPEDTEST<T>' without specifying specialization parameters
[bcc32 Error] gtest_unittest.cc(5368): E2293 ) expected
[bcc32 Error] gtest_unittest.cc(5370): E2102 Cannot use template 'CodeLocationForTYPEDTEST<T>' without specifying specialization parameters
[bcc32 Error] gtest_unittest.cc(5370): E2293 ) expected
[bcc32 Warning] gtest_unittest.cc(5378): W8054 Style of function definition is now obsolete
[bcc32 Error] gtest_unittest.cc(5378): E2275 { expected
[bcc32 Warning] gtest_unittest.cc(5380): W8054 Style of function definition is now obsolete
[bcc32 Error] gtest_unittest.cc(5381): E2468 Value of type void is not allowed
[bcc32 Warning] gtest_unittest.cc(5382): W8070 Function should return a value
[bcc32 Warning] gtest_unittest.cc(5384): W8054 Style of function definition is now obsolete
[bcc32 Error] gtest_unittest.cc(5384): E2275 { expected
[bcc32 Warning] gtest_unittest.cc(5386): W8054 Style of function definition is now obsolete
[bcc32 Error] gtest_unittest.cc(5386): E2293 ) expected

**Comment by JMorrison911** [comment]
sha of bruch - aa148eb2b7f70ede0eb10de34b6254826bfb34f4

**Comment by nevot** [comment]
Is this going to be sloved?
I'm using tokyo version and it is still happening

**Comment by tanzislam** [comment]
Please try my patch in #1217 with the [Clang-enhanced compiler](http://docwiki.embarcadero.com/RADStudio/Tokyo/en/Clang-enhanced_C%2B%2B_Compilers). (You'll need to disable the "Use 'classic' Borland compiler" option in Project Options.)

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
