### ISSUE TITLE
Compiler-specific implementations of __LINE__ are not handled correctly

### ISSUE THREAD

**Issue by sxlijin** [google/googletest#1044]
Surprisingly I couldn't find any bug that references this. The tl;dr: is that gtest seems to assume (and I may be wrong on this count) that `__LINE__` uniquely corresponds to the input source line, which causes problems if you try to nest any tests whose macros include a `goto` in their expansion, since gtest uses `__LINE__` to make those labels unique.

Before delving into the nature of the issue, here's an example of a file which `g++` will not compile:

```
$ cat -n main.cpp
     1  #include <gtest/gtest.h>
     2
     3  class BrokenTest : public ::testing::Test {};
     4
     5  TEST_F(BrokenTest, Bad)
     6  {
     7      EXPECT_NO_THROW({
     8          EXPECT_THROW({ throw std::exception(); }, std::exception);
     9          EXPECT_THROW({ throw std::exception(); }, std::exception); // error
    10      });
    11  }
    12
    13  int main(int argc, char** argv)
    14  {
    15      ::testing::InitGoogleTest(&argc, argv);
    16      return RUN_ALL_TESTS();
    17  }
```

And here's the snippet from `g++`'s error dump that we care about:
```
[...]/broken-gtest-example/lib/googletest/include/gtest/internal/gtest-internal.h:1147:25: error: duplicate label ‘gtest_label_testthrow_10’
     GTEST_CONCAT_TOKEN_(gtest_label_testthrow_, __LINE__): \
[snip]
[...]/broken-gtest-example/main.cpp:9:9: note: in expansion of macro ‘EXPECT_THROW’
         EXPECT_THROW({ throw std::exception(); }, std::exception); // error
```

It turns out that this happens because of the nested macro in the source file, which means that [compilers have some liberty in deciding how to expand `__LINE__`](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80071) (since the C++ standard is deliberately ambiguous about its definition).

After spending an hour or two digging through and hacking at the guts of gtest, I have no idea if there's a way to fix this (since there are tests like `EXPECT_THROW(ThrowAnInteger(), int) << "unexpected failure";`). I've had a couple of ideas for fixing this (using `__COUNTER__` to make the labels unique, using anonymous functions a la GNU C to refactor out the `goto`s) but I wanted to throw this out there before doing any more work on it.

**Comment by gennadiycivil** [comment]
@sxlijin Thank you for the report. Unfortunately there appears to be no actionable information here

**Comment by golvok** [comment]
This seems to affect the more general case of having any two `ASSERT_THROW`s that happen to get the same `__LINE__`, such as when they're inside a helper macro. Since this is the only relevant thing that came up when I was searching for this, I'll tell about a solution I found.

Since labels are scoped to functions, using an immediately-invoked lambdas works-around this fairly neatly (note that `ASSERT_NO_FATAL_FAILURE` doesn't work here for similar reasons).

```c++
#define ASSERT_THROWS_STUFF(obj_expr, k_expr) \
  do { \
    auto&& obj_ = obj_expr; \
    auto&& k_ = k_expr; \
    bool failed_ = true;
    [&] { ASSERT_THROW(obj_.func1(k_)); failed = false; }(); \
    if (failed) GTEST_FAIL(); \
    ASSERT_THROW(obj_.func2(k_)); \
  } while (false)
```

Also, I will have to agree with @sxlijin that the use of `goto` seems mandatory,  unless a compiler extension like `__COUNTER__` is used to either make the labels unique, or to make variables with unique names.
