### ISSUE TITLE
Value-Parametrized testing with non-optimized SetUp calls

### ISSUE THREAD

**Issue by pdroalves** [google/googletest#1057]
I'm playing with Value-Parametrized tests for a fixture that has a very expensive setup.

Using googletest's INSTANTIATE_TEST_CASE_P approach I noticed that it instantiates the fixture class before each test case for each parameter, ignoring a much more smart possibility that is instantiate the fixture class for some parameter, run all tests for that parameter and then switch to the next one.

Am I missing something here? This behavior increases a lot testing time.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.
