### ISSUE TITLE
c++11 apps that require -Wsuggest-override cannot use google test without editing it

### ISSUE THREAD

**Issue by dankegel** [google/googletest#1063]
This is similar to but smaller and simpler than #533.

We recently made the leap to requiring -Wsuggest-override in our apps.
We include googletest with -isystem to suppress warnings, but even so, our tests failed to build, saying
```
error: ‘virtual void foo_bar::TestBody()’ can be marked override [-Werror=suggest-override]  TEST_F(...)
```
etc.  A small change to the fused gtest.h sufficed to get that app up, but it'd be nice to get a fix upstream.

In light of the difficulty getting similar changes in for Google Mock (see #533), let's make this
issue solely about the minimal set of changes needed to get gtest (not gmock) ready for
use by apps that require the override qualifier when overriding virtuals.

**Comment by jwakely** [comment]
There's a non-intrusive solution that doesn't require editing `gtest.h`:

````
#if __GNUC__ >= 5
// Disable GCC 5's -Wsuggest-override warnings in gtest
# pragma GCC diagnostic push
# pragma GCC diagnostic ignored "-Wsuggest-override"
#endif
#include <gtest/gtest.h>
#if __GNUC__ >= 5
# pragma GCC diagnostic pop
#endif
````

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by mhubii** [comment]
still get a similar error trying to compile the below code 

```cpp
#include <array>
#include <gtest/gtest.h>


template <typename IntConst>
class FooTest : public testing::Test
{
public:
    static constexpr std::size_t dim = IntConst::value;
    FooTest() = default;
    std::array<double, dim> array;
};


using Implementations = testing::Types<std::integral_constant<std::size_t, 1>,
                                       std::integral_constant<std::size_t, 2> >;

TYPED_TEST_CASE(FooTest, Implementations);

TYPED_TEST(FooTest, test1) {};
```

error reads 

```shell
error: ‘void FooTest_test1_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = std::integral_constant<long unsigned int, 1>]’ can be marked override [-Werror=suggest-override]
 TYPED_TEST(FooTest, test1) {};
```

surely could be implemented differently, just wanted to share
