### ISSUE TITLE
EXPECT_CALL(...).Times(X); does not detect if call happens in EXPECT_EXIT(...)

### ISSUE THREAD

**Issue by kdawgwilk** [google/googletest#1067]
I have the following code:
```c++
ON_CALL(scanner, GetNextToken()).WillByDefault(Return(TokenClass(VOID_TOKEN, "void")));
EXPECT_CALL(scanner, GetNextToken()).Times(1);
EXPECT_EXIT(parser.Match(INT_TOKEN), ExitedWithCode(1), "Expected token type INT, but got type VOID");
```

The call to `parser.Match(...)` calls the `GetNextToken` method before it exits but the call is never detected because it runs in an `EXPECT_EXIT`

So I get the following message when running the test:
```
ParserTests.cpp:148: Failure
Actual function call count doesn't match EXPECT_CALL(scanner, GetNextToken())...
         Expected: to be called once
           Actual: never called - unsatisfied and active
```

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
