### ISSUE TITLE
When compile with libc++, the code throw std::bad_cast exception before running into main

### ISSUE THREAD

**Issue by tolak** [google/googletest#1068]
Hi, when i use gtest with libc++(not std libc++), the code threw exception "std::bad_cast " before running into main. And we figured out that it's std::use_facet within libc++ which actually threw the exception, but we can't find why and where gtest triggered the failed invokation of std::use_facet. It seems we got a incorrect "locale", Anyone can help me? Thanks.
Here is the backtrace dumped in gdb command line:
==================================
(gdb) catch throw
Catchpoint 1 (throw)
(gdb) run
Starting program: /path/to/clean-gtest-libcxx 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Catchpoint 1 (exception thrown), __cxa_throw (thrown_object=0x74088, 
    tinfo=0x73c60 <typeinfo for std::bad_cast>, 
    dest=0xbdd8 <std::bad_cast::~bad_cast()>)
    at /path/to/release/libcxxabi/src/cxa_exception.cpp:223
223     /path/to/release/libcxxabi/src/cxa_exception.cpp: No such file or directory.
(gdb) backtrace
#0  __cxa_throw (thrown_object=0x74088, 
    tinfo=0x73c60 <typeinfo for std::bad_cast>, 
    dest=0xbdd8 <std::bad_cast::~bad_cast()>)
    at /path/to/release/libcxxabi/src/cxa_exception.cpp:223
#1  0xb6f7801c in std::__1::locale::use_facet(std::__1::locale::id&) const ()
   from /usr/lib/libc++.so.1
#2  0xb6f6d498 in std::__1::__stdinbuf<char>::__stdinbuf(_IO_FILE*, __mbstate_t*) () from /usr/lib/libc++.so.1
#3  0xb6f6ccb8 in std::__1::ios_base::Init::Init() ()
   from /usr/lib/libc++.so.1
#4  0xb6f505c8 in _GLOBAL__sub_I_iostream.cpp () from /usr/lib/libc++.so.1
#5  0xb6fe6a04 in call_init () from /lib/ld-linux.so.3
#6  0xb6fe6ae0 in _dl_init_internal () from /lib/ld-linux.so.3
#7  0xb6fd7d64 in _dl_start_user () from /lib/ld-linux.so.3
#8  0xb6fd7d64 in _dl_start_user () from /lib/ld-linux.so.3
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
