### ISSUE TITLE
googletest built-in test failure.

### ISSUE THREAD

**Issue by AmeyaVS** [google/googletest#1070]
I have cloned the googletest repository and build the library, as per the documentation on _**Ubuntu 16.04**_ with _**g++ 5.4.0, cmake 3.5.1**_:

```sh
cmake -Dgtest_build_samples=ON -Dgtest_build_tests=ON -Dgmock_build_tests=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$HOME/apps/gtest ..
```

After building the library, examples and running make check, I am seeing these failure:

```text
The following tests FAILED:  
         48 - gtest_break_on_failure_unittest (Failed)
	 49 - gtest_catch_exceptions_test (Failed)
	 50 - gtest_color_test (Failed)
	 51 - gtest_env_var_test (Failed)
	 52 - gtest_filter_unittest (Failed)
	 53 - gtest_help_test (Failed)
	 54 - gtest_list_tests_unittest (Failed)
	 55 - gtest_output_test (Failed)
	 56 - gtest_shuffle_test (Failed)
	 57 - gtest_throw_on_failure_test (Failed)
	 58 - gtest_uninitialized_test (Failed)
	 59 - gtest_xml_outfiles_test (Failed)
	 60 - gtest_xml_output_unittest (Failed)
Errors while running CTest
```

I have verified the gtest_break_on_failure where the test is intentionally added to fail.
While the gtest_color_test is verifying the internal feature set of the framework.

My concern is about the other test which are currently failing, should I be bothered about them or should I just ignore them for now?

I am currently evaluating the framework for utilizing it my project.

-Ameya

**Comment by hethi** [comment]
This issue is duplicated in issue #1175, a fix is available in pull request #1235.

**Comment by hethi** [comment]
@AmeyaVS - to answer your question: Until the pull request is merged, you may just remove the `-DCMAKE_BUILD_TYPE=Debug`. If you do not specify the build type, the tests will pass (it's a problem of the search path to test binaries on UNIXoid systems).

**Comment by hethi** [comment]
This issue can be closed now IMHO.

**Comment by AmeyaVS** [comment]
Sorry for the late response.
Closing the issue.
