### ISSUE TITLE
clang-tidy 4.0 modernize-use-equals-delete warning

### ISSUE THREAD

**Issue by martin-ejdestig** [google/googletest#1072]
Clang Tidy 4.0 added a check for preferring "= delete" instead of making special member functions private and leaving them unimplemented. See http://clang.llvm.org/extra/clang-tidy/checks/modernize-use-equals-delete.html . Should at least add a NOLINT if "= delete" can not be used.

Example output of running clang-tidy with modernize-use-equals-delete on code that uses Google Test:

foo.cpp:52:2: warning: use '= delete' to prohibit calling of a special member function [modernize-use-equals-delete]
        TEST_F(ColorTest, Variant)
        ^
/usr/include/gtest/gtest.h:2217:3: note: expanded from macro 'TEST_F'
  GTEST_TEST_(test_fixture, test_name, test_fixture, \
  ^
/usr/include/gtest/internal/gtest-internal.h:1222:7: note: expanded from macro 'GTEST_TEST_'
      GTEST_TEST_CLASS_NAME_(test_case_name, test_name));\
      ^
/usr/include/gtest/internal/gtest-internal.h:1211:3: note: expanded from macro 'GTEST_TEST_CLASS_NAME_'
  test_case_name##_##test_name##_Test
  ^
note: expanded from here

**Comment by gennadiycivil** [comment]
There is no actionable information here.

**Comment by martin-ejdestig** [comment]
I just updated to latest master to check and modernize-use-equals-delete no longer issues a warning, so this has been fixed.

No idea in what commit or in what release it will be available though. Would be... nice to know...

**Comment by dnnr** [comment]
Thanks for checking! I wasn't even aware that there has been a release recently.

Did you mean to imply that it is *not yet* fixed in 1.8.1?

**Comment by martin-ejdestig** [comment]
> Did you mean to imply that it is not yet fixed in 1.8.1?

I did not check. @gennadiycivil ought to know though.

**Comment by gennadiycivil** [comment]
@martin-ejdestig @dnnr 
From the front page of googletest:
1.8.x Release - the 1.8.x is the last release that works with pre-C++11 compilers. The 1.8.x will not accept any requests for any new features and any bugfix requests will only be accepted if proven "critical"

If you think that this clang-tidy warning is critical please feel free to make your case and submit a PR.

Thank you

**Comment by dnnr** [comment]
Fair enough. Even if this still persists in 1.8.1, I certainly wouldn't classify it as critical.

I'm glad to see that there's progress, and looking forward to 1.9.x! :+1:

**Comment by jasjuang** [comment]
I just ran into this problem and I am on the lastest master of googletest. How did you guys eventually get rid of the clang-tidy warnings?

**Comment by jasjuang** [comment]
NOLINT and NOLINTNEXTLINE don't even work because the code that causes the problem is in a large `#define` block...

**Comment by jasjuang** [comment]
I figured it out. The answer manually change it into what clang-tidy wants ourselves. Change [this line](https://github.com/google/googletest/blob/master/googletest/include/gtest/internal/gtest-internal.h#L1406) to 

```
 GTEST_TEST_CLASS_NAME_(test_suite_name, test_name)() = default;                   \
```
