### ISSUE TITLE
g_argvs is a static object causing exit time failures

### ISSUE THREAD

**Issue by blackgnezdo** [google/googletest#1075]
I build gtest-1.8.0 on OpenBSD 6.1-amd64. When I run protobuf-3.2.0 test suite relying on gtest, I get exit time failures complaining about double-freeing memory.  The object implicated is g_argvs. Quick code inspection reveals a typical pattern outlawed in [google style guide](https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables):

Objects with static storage duration, including global variables, static variables, static class member variables, and function static variables, must be Plain Old Data (POD): only ints, chars, floats, or pointers, or arrays/structs of POD.

The following patch makes this symptom disappear (though the next bug is still causing trouble and will require more work). Admittedly, this is c++11-only code and may require changes to work for the full set of supported compilers.

```patch
$OpenBSD$
--- googletest/src/gtest.cc.orig
+++ googletest/src/gtest.cc
@@ -384,13 +384,17 @@ void AssertHelper::operator=(const Message& message) c
 GTEST_API_ GTEST_DEFINE_STATIC_MUTEX_(g_linked_ptr_mutex);
 
 // A copy of all command line arguments.  Set by InitGoogleTest().
-::std::vector<testing::internal::string> g_argvs;
+::std::vector<testing::internal::string>& g_argvs() {
+  static ::std::vector<testing::internal::string>* const gargvs =
+      new ::std::vector<testing::internal::string>();
+  return *gargvs;
+}
 
 const ::std::vector<testing::internal::string>& GetArgvs() {
 #if defined(GTEST_CUSTOM_GET_ARGVS_)
   return GTEST_CUSTOM_GET_ARGVS_();
 #else  // defined(GTEST_CUSTOM_GET_ARGVS_)
-  return g_argvs;
+  return g_argvs();
 #endif  // defined(GTEST_CUSTOM_GET_ARGVS_)
 }
 
@@ -5347,9 +5351,9 @@ void InitGoogleTestImpl(int* argc, CharType** argv) {
 
   if (*argc <= 0) return;
 
-  g_argvs.clear();
+  g_argvs().clear();
   for (int i = 0; i != *argc; i++) {
-    g_argvs.push_back(StreamableToString(argv[i]));
+    g_argvs().push_back(StreamableToString(argv[i]));
   }
 
   ParseGoogleTestFlagsOnly(argc, argv);

```

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by gennadiycivil** [comment]
@blackgnezdo I ll re-open this issue. To be upfront, this is not anywhere close to top priority so if this presents an issue for you - you may want to consider creating a  proper PR. 
Thanks

**Comment by gennadiycivil** [comment]
ping. I am about to close this again unless there is some activity on it. please let me know

**Comment by blackgnezdo** [comment]
The internal CL died on the vine, so let's abandon this. I suspect things may have even changed on OpenBSD since then due to them switching to clang/llvm/ldb.
