### ISSUE TITLE
How to use MOCK_METHOD for overloaded operators

### ISSUE THREAD

**Issue by RuoxiQin** [google/googletest#1080]
Hi,

I am new to googlemock (and Github). I got a problem when using `MOCK_METHODn` in googlemock. I have an abstract class `Foo` with `virtual operator[]`
```
class Foo{
public:
      virtual ~Foo(){};
      virtual int operator [] (int index) = 0;
}
```

and I want to use googlemock to get a `MockFoo`
```
class MockFoo: public Foo{
public:
      MOCK_METHOD1(operator[], int(int index));
}
```

However, I got the building errors like this
```
error: pasting "]" and "_" does not give a valid preprocessing token
  MOCK_METHOD1(operator[], GeneInterface&(int index));
```

So could anyone tell me how to mock operator by using `MOCK_METHODn`? Besides, I have read the docs in googlemock and found nothing related to my problem. Maybe someone could add this topic in there?

Thanks!

**Comment by leoasterix** [comment]
The way I had used it is:
class MockFoo: public Foo{
public:
      MOCK_METHOD1(at, int(int index));
      int operator [] (int index) override
      {
          at(index);
      }
}

**Comment by RuoxiQin** [comment]
That works. Thank you!
