### ISSUE TITLE
Error with cmake 3.7.1

### ISSUE THREAD

**Issue by mojovski** [google/googletest#1086]
When I try to configure gtest with cmake 3.7.1 (master branch of today),
I receive this error:
```
CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:219 (message):
  No REQUIRED_VARS specified for FIND_PACKAGE_HANDLE_STANDARD_ARGS()
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindPythonInterp.cmake:151 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  external/googletest/googletest/cmake/internal_utils.cmake:211 (find_package)
  external/googletest/googletest/CMakeLists.txt:60 (include)
```
The problem is the FindPythonInterp.cmake file provided by cmake.
It requires the searched package to be found:
```
#FindPythonInterp.cmake:151
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PythonInterp REQUIRED_VARS PYTHON_EXECUTABLE VERSION_VAR PYTHON_VERSION_STRING)
```
I had to change line 
googletest/googletest/cmake/internal_utils.cmake:211
to
```
#find_package(PythonInterp)
```
to make it work (I dont need python for now).

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
