### ISSUE TITLE
AdvancedGuide: invalid function names: TestCaseSetUp()/TestCaseTearDown()

### ISSUE THREAD

**Issue by Macintron** [google/googletest#1087]
In the advanced guideline, Getting the Current Test's Name (https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#getting-the-current-tests-name):

Use correct function names
TestCaseSetUp() -> SetUpTestCase()
TestCaseTearDown() -> TearDownTestCase()

**Comment by hethi** [comment]
@Macintron Thanks for reporting this. As I'm just exercising anyway, I picked this up and created a pull request. Hopefully it will be merged by the maintainers soon :-).

**Comment by hethi** [comment]
As it's merged now, you may close this issue?
