### ISSUE TITLE
Different behaviour under gcc and clang (segfault on clang)

### ISSUE THREAD

**Issue by stefan-imp** [google/googletest#1088]
Using Googlemock 1.7, I have the following test code:

```
typedef std::vector<int> Foos;

class Mockable
{
public:
    Mockable() {}
    virtual ~Mockable() {}

    virtual bool start(const Foos& foos) = 0;
};

class MockMockable: public Mockable
{
public:
    MOCK_METHOD1(start, bool(const Foos&));
};

void testQuick()
{
        MockMockable x;
        Foos targetFoos;
        Foos foos;

        EXPECT_CALL(x, start(_))
            .WillOnce(SaveArg<0>(&targetFoos));
            // .WillOnce(DoAll(SaveArg<0>(&targetFoos), Return(true))); // This version works with both compilers
        Mockable *target = &x;
        target->start(foos);
}
```

I can compile the above example with both gcc (6.3) and clang (3.5).  It compiles without warning in both cases.

Running the test on gcc passes.  On clang it segfaults.

The problem seems to be something to do with not providing a return value.  The commented out alternative action compiles and runs without problems on both compilers.

It is unclear which compiler's behaviour is as expected...i.e. should the SaveArg action return a default value, or is the return action mandatory?

**Comment by stefan-imp** [comment]
One more comment.  If the typedef is changed from `std::vector<int>` to a simple type like <int>, the difference goes away again.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
