### ISSUE TITLE
Protocol buffer messages are not being pretty printed

### ISSUE THREAD

**Issue by rohitsaboo** [google/googletest#1102]
I'm unable to get protocol buffer messages to be pretty printed in my gtest failure messages.

My guess is that
https://github.com/google/googletest/blob/7cc548dcbf266d48c9b3fe8ec30c2f2ba8acb1d9/googletest/include/gtest/internal/gtest-internal.h#L907 checks if the type is convertible to proto2::Message in order to pretty print protocol buffer messages, whereas in the open source implementation of protobufs, the type seems to be google::protobuf::Message.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by inazarenko** [comment]
Open source protobuf messages derive from `google::protobuf::MessageLite`.

GTest enables ProtbufPrinter based on:

```
template <typename T>
struct IsAProtocolMessage
   : public std::is_convertible<const T*, const ::proto2::MessageLite*> {};
```

So open-source protobufs are printed as bytes.

This was previously closed as "inactive": https://github.com/google/googletest/issues/1102

The issue still occurs at current master.
