### ISSUE TITLE
Proposal for integration of CPack to build RPM

### ISSUE THREAD

**Issue by ecky-l** [google/googletest#1103]
I have created a patch with some build files for building an RPM from googletest. This makes it easy to package the distribution into an RPM for the current platform, by just typing "make package".

Since I don't have access to the repository for creating pull requests, the patch is attached (git format-patch ...).

[0001-Integration-of-CPack-for-building-RPM.zip](https://github.com/google/googletest/files/1028947/0001-Integration-of-CPack-for-building-RPM.zip)

**Comment by gennadiycivil** [comment]
Looks stale
