### ISSUE TITLE
Miscellaneous issues in Google Mock Cookbook

### ISSUE THREAD

**Issue by johngmyers** [google/googletest#1105]
There is a dead link "Google C++ style guide".

Yob's comma: "use `ConcretePacketStream` in production code, and use `MockPacketStream` in tests."

A code sample in the "Validating a Member of an Object" section does not render properly with the GitHub website viewer.

Verb number error: "The code won't compile if any of these conditions isn't met". "any" is not elliptical for "any one" in this context, so takes a plural verb.

Tables in the "Writing New Actions Quickly" and "Using the ACTION Object's Type" sections do not render properly with the GitHub website viewer.

**Comment by hethi** [comment]
The dead link was fixed in #1165 :-)

**Comment by hethi** [comment]
Hmm, what's the problem with the tables not rendered properly? I can't see a problem there?

**Comment by hethi** [comment]
Same for the code sample - what's the problem you see?

**Comment by johngmyers** [comment]
Those tables and that code sample appear to have been subsequently fixed.

**Comment by hethi** [comment]
Ah, that's cool. Then probably you can close this issue?
