### ISSUE TITLE
How to parallelise Google Test Cases?

### ISSUE THREAD

**Issue by guptaarpit21** [google/googletest#1106]
I'm having trouble in parallelising of google test cases in order to reduce execution time.
can anyone help me with the code and process to do so ?

**Comment by cferris1000** [comment]
I wrote something for Android that does this. The code is available here:

https://android-review.googlesource.com/c/390582/

I haven't submitted it yet, but it does speed up execution when running on
a single machine.

Christopher Ferris

**Comment by guptaarpit21** [comment]
I've implemented using google sharding but what about the xml file generation as multiple shards run in parallel and thus no proper xml output file. is there any way to do so?
