### ISSUE TITLE
Death test child under MinGW should not invoke Windows Error Reporting

### ISSUE THREAD

**Issue by tanzislam** [google/googletest#1116]
I noticed that a death test (e.g. `EXPECT_DEATH(...)`) on Windows 7 triggers Windows Error Reporting when the child process crashes, if the code is built with MinGW-w64. In the parent process, the test hangs until the user cancels or otherwise satisfies the Windows Error Reporting popup.

This simple code reproduces the problem:

```cpp
#include <gtest/gtest.h>
#include <cassert>

TEST(DeathTestTest, AssertionCrashesProgram)
{
    EXPECT_DEATH(assert(false), "");
}
```

I am using:

 - Windows 7 SP1
 - GCC v7.1.0 (part of mingw-w64)
 - Latest "master" branch of Google Test (commit 42bc671f47b)

**Comment by BillyDonahue** [comment]
ok, I see how this is annoying but I don't see how to keep it from happening.

**Comment by tanzislam** [comment]
I believe the issue is with [this section of code](https://github.com/google/googletest/blob/master/googletest/src/gtest.cc#L4217-L4254) being guarded by the `GTEST_HAS_SEH` macro, which [never gets set on MinGW](https://github.com/google/googletest/blob/master/googletest/include/gtest/internal/gtest-port.h#L929-L948).

That section of code doesn't seem to do anything that requires SEH support. I intend to raise a pull request to remove the `GTEST_HAS_SEH` guard from around it; getting permission from my employer first ...
