### ISSUE TITLE
GTEST_AMBIGUOUS_ELSE_BLOCKER_ does not block the warning for gcc-7.1.

### ISSUE THREAD

**Issue by gkistanova** [google/googletest#1119]
Starting from gcc 7.1 the GTEST_ASSERT_ and all the dependencies produce the following warning,
when used with if statement without surrounding braces.

It seems GTEST_AMBIGUOUS_ELSE_BLOCKER_ does not do the trick any more.

To reproduce, compile the following code
```
// gtest-ambiguous-else-warning.cpp
#include "gtest/gtest.h"

void foo(int i) {
  if (i > 0)
    GTEST_ASSERT_(::testing::AssertionFailure(), GTEST_NONFATAL_FAILURE_);
}
```
with
```
gcc-7.1 -Wall -c ./gtest-ambiguous-else-warning.cpp
```
The printout would be
```
./gtest-ambiguous-else-warning.cpp: In function 'void foo(int)':
./gtest-ambiguous-else-warning:4:6: warning: suggest explicit braces to avoid ambiguous 'else' [-Wdangling-else]
   if (i > 0)
      ^
```

We observe the issue with Google Test 1.8.0, but as far as I can tell, it is the same in the current trunk.

**Comment by Bu11etmagnet** [comment]
I ran into this too (with gtest 1.7.0). This may be a bug in GCC.

```
int main(int argc, char const *argv[])
{
  if (argc > 0) switch(0) case 0: default:
    if (argc > 1)
      return 2;
    else
      return 1;

  return 0;
}
```
and it seems pretty clear to me that the else cannot belong to the outside if. clang correctly suppresses the warning.

**Comment by Bu11etmagnet** [comment]
https://stackoverflow.com/questions/44797011/google-tests-ambiguous-else-blocker-defeated-by-gcc-7-1

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by rnk** [comment]
Can we reopen this? This is still affecting users. See all the commits referencing this. Another user ran into this issue in LLVM:
https://reviews.llvm.org/D61046#inline-541366

**Comment by ecatmur** [comment]
Note googletest has disabled this warning internally: https://github.com/google/googletest/pull/1426

**Comment by sasha2048** [comment]
Sorry for a stupid question, but why not just replace

    GTEST_AMBIGUOUS_ELSE_BLOCKER_
    if (foo)
      bar;
    else
      baz

with

    do {
      if (foo)
        bar;
      else
        baz;
    } while (false)
