### ISSUE TITLE
How to use mock class as template parameter

### ISSUE THREAD

**Issue by pranavladkat** [google/googletest#1125]
I have implemented a class using policy design pattern and I need to test it using googletest/googlemock. E.g. in below code, I want to test class Foo and would like to use a mock class for class Bar. Is it possible to test it using google test framework?

```
template <typename T>
class Foo : private T {
public:
  void foo() {
    T::bar();
  }
};

class Bar {
public:
  void bar() {
    std::cout << "Hey there!" << std::endl;
  }
};

int main() {
  Foo<Bar> f;
  f.foo();
}
```

**Comment by Fazer2** [comment]
Why don't you use Foo<BarMock> and see what happens?

**Comment by lhcopetti** [comment]
I was able to actually come up with something after I found out that, surprisingly, you can cast derived classes to base classes even though the inheritance is private.

Below is a piece of working code based on your example that mocks the behavior of the template parameter.

```
template <typename T>
class Foo : private T {
public:
  void foo() {
    T::bar();
  }
};

class Bar {
public:
  void bar() {
    std::cout << "Hey there!" << std::endl;
  }
};

class PolicyMock {
public:
	MOCK_METHOD0(bar, void());
};

TEST(TemplateTestFixture, MockPolicyDesignClass)
{
	Foo<PolicyMock> foo;
	PolicyMock& mock = reinterpret_cast<PolicyMock&>(foo);
	EXPECT_CALL(mock, bar());
	foo.foo();
}
```

Hope it works out for you!

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
