### ISSUE TITLE
Repeating the same test code for multiple fixtures?

### ISSUE THREAD

**Issue by karlnapf** [google/googletest#1131]
Imagine I have a couple of fixtures `F1, F2`, and I want to run the same test code on them. And that I want to test multiple implementations of the same interface.

```
TEST(F1, name) { ... test code ... }
TEST(F2, name) { ... same test code again ... }
```

Is there a nice way to do this *without*
 * using value parameterized tests (passing parameters that make a single fixture behave like `F1` or `F2`
 * templating the tests and passing `F1` and `F2` as template parameter?
 * putting the test code into a function

I imagine something like
```
TEST_DEFINE_WITHOUT_FIXTURE(name) { ... test code ... }
INSTANTIATE_TEST(F1, name)
INSTANTIATE_TEST(F2, name)
```

Thanks for this great tool!

**Comment by karlnapf** [comment]
@lisitsyn @vigsterkr

**Comment by hethi** [comment]
In case you find some different solution, you may add it to this question in the [FAQ](../blob/master/googletest/docs/FAQ.md#i-have-an-interface-that-has-several-implementations-can-i-write-a-set-of-tests-once-and-repeat-them-over-all-the-implementations)?

**Comment by karlnapf** [comment]
I worked around it for now, but this leads to duplicate code, un-intuitive structure etc. Would be a nice feature

**Comment by noahdesu** [comment]
@karlnapf do you have a reference to your technique?

**Comment by karlnapf** [comment]
I define an enum with the different test contexts, e.g.
```
enum class ETestType
{
	E_CASE_A,
	E_CASE_B,
};
```

My fixture class uses the `GetParam()`  to switch setting up the test context in the `SetUp` method:
```
class MyFixture: public ::testing::TestWithParam<ETestType>
{
public:
	void SetUp()
	{
		auto test_type = GetParam();
		switch (test_type)
		{
			case ETestType::E_CASE_A:
			{
				// set up test environment a
				break;
			}
			case ETestType::E_CASE_B:
			{
				// set up test environment b
				break;
			}
			...
		}
	}
};
```

Then I define my parametrised tests:
```
TEST_P(MyFixture, test_for_multiple_contexts)
{
    // test code that I want to execute for all different contexts
}
```

And then finally instantiating the tests
```
INSTANTIATE_TEST_CASE_P(Bla, MyFixture, ::testing::Values(ETestType::E_CASE_A, ETestType::E_CASE_B)
);
```

You see, this is rather laborious. I would prefer to use googletest's macro magic.

**Comment by noahdesu** [comment]
@karlnapf  Thanks. This is very similar to what I came up with as well. I can easily see how having more than a few cases could become quite fragile.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by karlnapf** [comment]
It is a pitty this wasn't addressed since it would be a very nice feature to have

**Comment by andioz** [comment]
I don't understand the reason why this is closed. Is it because somebody actively decided this will not be pursued, or just because nobody commented? Would be nice to know if the reason is a technical one, otherwise it should go to a wishlist.
