### ISSUE TITLE
Compilation errors with Clang with Microsoft CodeGen VS2015

### ISSUE THREAD

**Issue by limdor** [google/googletest#1132]
When compiling with CMake for VS 2015 and toolchain v140_clang_c2 they appear the following errors:

>   C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Clang.targets(210,5): error : Element <DebugInformationFormat> has an invalid value of "ProgramDatabase". [E:\googletest-master\build\googlemock\gmock.vcxproj]
>   C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Clang.targets(210,5): error : Element <ExceptionHandling> has an invalid value of "Sync". [E:\googletest-master\build\googlemock\gmock.vcxproj]
>   C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Clang.targets(210,5): error : Element <WarningLevel> has an invalid value of "Level4". [E:\googletest-master\build\googlemock\gmock.vcxproj]

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
