### ISSUE TITLE
Unable to generate a stack trace for C++ exceptions

### ISSUE THREAD

**Issue by emmenlau** [google/googletest#1140]
Can someone give me a hint how to generate stack traces for googletest (without googlemock)?
There was a suggestion on Stackoverflow that I tried:
https://stackoverflow.com/questions/26581066/how-to-get-backtrace-information-from-exception-in-googletest/26583406#26583406

I added my own implemention of EmptyTestEventListener and print the backtrace in OnTestPartResult()
but the backtrace there has nothing to do with the exception any more. I also tried adding a backtrace
unwind into googletest/src/gtest.cc OsStackTraceGetter::CurrentStackTrace() but I can not see this
stack trace printed. How would I access it?

I think google test is great, but without automatic stack trace its really limited. If tests fail in continous
integration, it would really help to see why/where the issue occured.

**Comment by ArekPiekarz** [comment]
It may not be a perfect solution in this case, but have you checked [Boost Stacktrace](https://github.com/boostorg/stacktrace)? It just got accepted into Boost, so it's not yet in a tagged release, but it should provide you the backtrace in cases of failures.

**Comment by emmenlau** [comment]
Thanks @ArekPiekarz! Your answer has actually pointed me in a very good direction. I will try to work with your suggestion, thanks!
