### ISSUE TITLE
Install target does not contain all needed files

### ISSUE THREAD

**Issue by krytarowski** [google/googletest#1148]
The install target does not install all needed files.

In particular gtest-all.cc & co. are required for LLVM compiler-rt.
There are MSAN tests that need to rebuild googletest libraries with sugar for sanitizers.

The current work around is to use full LLVM sources, which breaks standalone build and execution of tests of compiler-rt.

These files are already installed by Debian packages, but they are absent in pristine sources.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by krytarowski** [comment]
Please reopen, still valid in 1.8.1

**Comment by gennadiycivil** [comment]
@krytarowski The best way to approach this would be to create a proper PR and submit it for consideration. 
I am re-opening by your request but please note that if it remains stale it will just get closed again

**Comment by krytarowski** [comment]
Closing issue tickets does not make the problems to disappear. Pinging it every once in a while does not make it less stale.. it just discourages involvement that reported problems are treated as unwanted.

**Comment by gennadiycivil** [comment]
@krytarowski Let me explain. 
This issue has been open for over a year and did not generate sufficient interests from anyone in the community to act on it. 
Logically this means that this issue is not important to anyone in the community.
Logically this means that when we re-open it it will once again just sit here without anyone acting on it.

I hope I provided sufficient explanation.
Thank you

**Comment by krytarowski** [comment]
I don't see value in pinging some tickets 'this is broken for me too'. Such person would be rather warned for spamming.

As mentioned in the original report, I've mentioned a workaround in Debian and for them it was important.

https://packages.debian.org/stretch/amd64/googletest/filelist

I have faced the same trouble on NetBSD with pkgsrc and was kind to report it.

**Comment by gennadiycivil** [comment]
As previously discussed, this is once again stale. Note that any and all CMake support is community-based, we are not using CMake internally.

I am closing it.
