### ISSUE TITLE
std::variant printer

### ISSUE THREAD

**Issue by alex-weej** [google/googletest#1151]
Any thoughts on how we will approach this? In the general case we need to dump the `index` in addition to the value itself, in order for things to be unambiguous.

Sadly there's zero(?) hope for including the type name as spelled, although the demangled form can be used if and only if the type appears exactly once in the list of types.

How about this, for bikeshedding sake?

```
variant<int, string>{"this is a string"}
  -> { [1] "this is a string" }
```

**Comment by BillyDonahue** [comment]
Something like that example should be fine.
Looks ok to me.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
