### ISSUE TITLE
Could i do fork in single test case?

### ISSUE THREAD

**Issue by fenehuang** [google/googletest#1153]
Hi, guys

I meet a problem. If  make a fork in one test case, the result will print more than once.
So should i do fork in one test case???

code like as:

int test_nice_process(void)
{
    int pid;
    int rtn;
    int nice;

    pid = fork();
    if (!pid) {
        nice = getpriority(PRIO_PROCESS, getpid());
        ATLOGI("Pid-%d 1.nice %d\n", getpid(), nice);
        if (nice == -1) 
            exit(-1);

        if (setpriority(PRIO_PROCESS, getpid(), -20 ) == -1) {
            perror("setpriority");
            exit(-1);
        }   

        nice = getpriority(PRIO_PROCESS, getpid());
        ATLOGI("Pid-%d 2.nice %d\n", getpid(), nice);
        if (nice == -1) 
            exit(-1);
    } else if (pid > 0) {
        waitpid(pid, &rtn, 0); 
        if (WIFEXITED(rtn) && WEXITSTATUS(rtn) != 0) {
            ATLOGE("Pid-%d exit code:%d\n", pid, rtn);
            return -1; 
        }   
    } else {
        ATLOGE("Pid-%d can't fork", getpid());
        return -1; 
    }   

    return 0;
}

TEST_F(MockTest, processPermTest) 
{
test_nice_process()
 ....
}

-------
And then, the result print like as:

[       OK ] MockTest.checkPermTest (2732 ms)
[ RUN      ] MockTest.processPermTest
hell
child exit code:0
child exit code:139
hell
child exit code:0
child exit code:139
[       OK ] MockTest.processPermTest (31 ms)
[----------] 5 tests from MockTest (2791 ms total)

[----------] Global test environment tear-down
[==========] 5 tests from 1 test case ran. (2791 ms total)
[  PASSED  ] 4 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] MockTest.checkProcessLabel

----
print more than once processPermTest result.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by DanielGoldfarb** [comment]
Forking can be a good way to test something that **runs only once** in an executable, but that may correctly give _different_ results depending on conditions.  By setting the conditions and running in a fork, the test can be repeated for other conditions without the need to run a separate executable for each set of conditions (the fork effectively re-initializes everything)

Here is some basic code for doing this.  _The key to avoiding repeated output is to **always** call exit() from the fork, for both success and failure.  It is also important to pass the return value of testing::Test::HasFailure() into exit, so that success or failure gets properly recognized by the test_ : 

    #include <gtest/gtest.h>
    #include <unistd.h>      // fork()
    #include <sys/wait.h>    // WIFEXITED, etc.
    
    class MyTest : public ::testing::Test
    {
      public:
       int  wait_for_child_fork(int pid);
    };
    
    int  MyTest::wait_for_child_fork(int pid)
    {
       int status;
       if ( 0 > waitpid( pid, &status, 0 ) ) {
          std::cerr << "[----------]  Waitpid error!" << std::endl;
          return (-1);
       }
       if ( WIFEXITED(status) ) {
          const int exit_status = WEXITSTATUS(status);
          if ( exit_status != 0 ) {
             std::cerr << "[----------]  Non-zero exit status " << exit_status << " from test!" << std::endl;
          }
          return exit_status;
       } else {
          std::cerr << "[----------]  Non-normal exit from child!" << std::endl;
          return (-2);
       }
    }
    
    //  ===========================================================================
    //  NOTE WELL:  It is VERY IMPORTANT that the child-fork in each test call
    //              exit() (or abort), OTHERWISE it is possible for some tests
    //              to run multiple times.   SEE TEST "BOILER_PLATE" FOR HOW EACH
    //              TEST SHOULD BE STRUCTURED AND HOW exit(..) SHOULD BE CALLED
    //  ===========================================================================
    
    //  ---------------------------------------------------------------------
    //  These first 3 tests ( WAITPID_ERROR, FORKABORT, and NONZERO_FORKEXIT)
    //  just make sure the whole forking and wait_for_child_fork() thing is
    //  working.  See test BOILER_PLATE for how to structure your tests AND
    //  FOR HOW TO CALL EXIT TO ENSURE THAT (a) tests do not run more than once,
    //  and (b) THE SUCCESS OR FAILURE OF THE TEST GETS PROPERLY REPORTED
    //  BY PASSING "testing::Test::HasFailure()" into the exit() call.
    //  ---------------------------------------------------------------------
    
    TEST_F( MyTest, WAITPID_ERROR )  
    {  // Make sure we can catch a non-zero exit from the fork.
       int pid = fork();
       if ( 0 == pid ) {  // I am the child
          exit(0);
       } else {  // I am the parent
          ASSERT_NE( 0, wait_for_child_fork(-99) );  // wait for invalid pid
       }
    }
    
    TEST_F( MyTest, FORKABORT )
    {  // Make sure we can catch an abort from the fork.
       int pid = fork();
       if ( 0 == pid ) {  // I am the child
          abort();
       } else {  // I am the parent
          ASSERT_EQ( -2, wait_for_child_fork(pid) );  // abnormal exit, expect -2
       }
    }
    
    TEST_F( MyTest, NONZERO_FORKEXIT )  
    {  // Make sure we can catch a non-zero exit from the fork.
       int pid = fork();
       if ( 0 == pid ) {  // I am the child
          exit(99);
       } else {  // I am the parent
          ASSERT_EQ( 99, wait_for_child_fork(pid) );  // non-zero exit
       }
    }
    
    TEST_F( MyTest, BOILER_PLATE )
    {
       int pid = fork();
       if ( 0 == pid ) {  // I am the child
    
          // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
          //
          // Insert EXPECT_ and ASSERT_ tests here.
          //
          // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    
          // This exit is very important, otherwise the fork
          // keeps running and may duplicate other tests.
          exit(testing::Test::HasFailure());  
    
       } else {  // I am the parent
          ASSERT_EQ( 0, wait_for_child_fork(pid) );
       }
    }
    
    TEST_F( MyTest, ANOTHER_TEST )
    {
       int pid = fork();
       if ( 0 == pid ) {  // I am the child
    
          // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
          //
          // Insert EXPECT_ and ASSERT_ tests here.
          //
          // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    
          // This exit is very important, otherwise the fork
          // keeps running and may duplicate other tests.
          exit(testing::Test::HasFailure());  
    
       } else {  // I am the parent
          ASSERT_EQ( 0, wait_for_child_fork(pid) );
       }
    }

**Comment by gennadiycivil** [comment]
Thank you very much for this report. Unfortunately there appears to be no actionable information. I am not sure what this is suggesting

**Comment by gennadiycivil** [comment]
The best way to approach this would be to create a proper PR and submit it for consideration so it is clear what this is adding

**Comment by DanielGoldfarb** [comment]
What I have provided above is a "work-around" for the fact that calling fork during a Google Test can cause the test to run more than once.  The work-around is to always call `exit(testing::Test::HasFailure())` _from the child fork._  In terms of actionable information I figure there are two choices here: (1) simply instruct people that this aspect of Google Test is WAD and they can use the above suggested work-around, or (2) someone could write some Google Test macro[s] to effectively build the work-around into Google Test to make it easier to use, and follow up with a pull request.

**Comment by gennadiycivil** [comment]
@DanielGoldfarb Thank you for this. However your work will be just lost in this issue. I suggest opening a PR against proper place in googletest documentation that would make this recipe available for others.

**Comment by DanielGoldfarb** [comment]
OK.  Sounds good.  Thanks.

**Comment by DanielGoldfarb** [comment]
@gennadiycivil  Btw, to save me some time finding the right spot, assuming you are more familiar with the documentation than I am, could you possibly suggest an appropriate place to include this recipe in the documentation?

**Comment by gennadiycivil** [comment]
Hard to say, maybe in the Advanced guide
