### ISSUE TITLE
undefined behaviour shifting 1 into sign bit, in gtest-port.h

### ISSUE THREAD

**Issue by seanm** [google/googletest#1154]
clang's -Wshift-sign-overflow warns:

```
googletest/include/gtest/internal/gtest-port.h:2440:34: warning: signed shift result (0x8000000000000000) sets the sign bit of the shift expression's type ('BiggestInt' (aka 'long long')) and becomes negative [-Wshift-sign-overflow]
    ~(static_cast<BiggestInt>(1) << (8*sizeof(BiggestInt) - 1));
      ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

test-port.h has this:

```C++
// The maximum number a BiggestInt can represent.  This definition
// works no matter BiggestInt is represented in one's complement or
// two's complement.
//
// We cannot rely on numeric_limits in STL, as __int64 and long long
// are not part of standard C++ and numeric_limits doesn't need to be
// defined for them.
const BiggestInt kMaxBiggestInt =
    ~(static_cast<BiggestInt>(1) << (8*sizeof(BiggestInt) - 1));
```

1) indeed it is undefined behaviour in C++ to shift a 1 into the sign bit of a signed variable.
2) the comment is wrong. 'long long' as been standard since C++11.
3) perhaps numeric_limits could be used conditionally #if C+11?

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
