### ISSUE TITLE
testing::Property doesn't work with std::shared_ptr<> objects

### ISSUE THREAD

**Issue by barreyra** [google/googletest#1156]
Given a `std::shared_ptr<Foobar> foo`, I'm required to write:

```
    EXPECT_THAT(foo, Pointee(Property(&Foobar::barfoo, "Hello")));
```

instead of simply:

```
    EXPECT_THAT(foo, Property(&Foobar::barfoo, "Hello"));
```

**Comment by sbenzaquen** [comment]
On Tue, Jul 25, 2017 at 9:39 AM, barreyra <notifications@github.com> wrote:

> Given a std::shared_ptr<Foobar> foo, I'm required to write:
>
>     EXPECT_THAT(foo, Pointee(Property(&Foobar::barfoo, "Hello")));
>
> instead of simply:
>
>     EXPECT_THAT(foo, Property(&Foobar::barfoo, "Hello"));
>
> I'm not sure why you would expect this to work. That is not a property of
std::shared_ptr (there is no special code for shared_ptr in gMock).
Pointee(xxx) is exactly what you want.

**Comment by barreyra** [comment]
You're right. If gMock were to support this, you wouldn't be able to call the std::shared_ptr<> methods.  It makes a little awkward, but I guess I can write my own matcher, something like PtrProperty if I really want a shortcut.
