### ISSUE TITLE
Library install location is wrong

### ISSUE THREAD

**Issue by mwoehlke-kitware** [google/googletest#1161]
There are two issues with the library install location:

- It doesn't install to the correct arch-dependent location.
- `.dll`s are not installed to `bin` (Windows-only issue).

#1160 fixes the first. For the second, just using `DESTINATION` is insufficient. The correct invocation is e.g.:

```
install(TARGETS gtest gtest_main
  RUNTIME DESTINATION bin
  LIBRARY DESTINATION lib${LIB_SUFFIX}
  ARCHIVE DESTINATION lib${LIB_SUFFIX}
)
```

**Comment by mwoehlke-kitware** [comment]
I updated #1160 to fix both issues...

**Comment by gennadiycivil** [comment]
Could you please provide evidence of testing, for example - how you run the install before the fix and how you run the install after the proposed fix.  We need to make sure that this fix does not introduce regression problems. 
What platforms did you test this on? Thank you

**Comment by mwoehlke-kitware** [comment]
Um... `ninja install`? Tested on Fedora 26, with `BUILD_SHARED_LIBS=ON`. I compared output of `find` on the install trees: as expected, the only change is that libraries installed to `lib64` (correct on Fedora) instead of `lib` (wrong on Fedora).

**Comment by gennadiycivil** [comment]
Thank you for the prompt response. Since this fix is also relevant on Windows we need to make sure that Windows testing has been included.

**Comment by mwoehlke-kitware** [comment]
I tried on Windows...

Without #1160:

    -- Installing: .../build/googletest/install/lib/gtest.lib
    -- Installing: .../build/googletest/install/lib/gtest.dll
    -- Installing: .../build/googletest/install/lib/gtest_main.lib
    -- Installing: .../build/googletest/install/lib/gtest_main.dll

This is wrong; the `.dll`s should be in `bin`.

With #1160:

    -- Installing: .../build/googletest/install/lib/gtest.lib
    -- Installing: .../build/googletest/install/bin/gtest.dll
    -- Installing: .../build/googletest/install/lib/gtest_main.lib
    -- Installing: .../build/googletest/install/bin/gtest_main.dll

This is correct; the `.lib`s are in `lib`, the `.dll`s are in `bin`.

**Comment by mwoehlke-kitware** [comment]
@SylvainCorlay, #1160 *does* do that...

**Comment by Cylix** [comment]
FYI, as reported in #1198 , this change break the installation of gtest by not installing the headers anymore.

**Comment by gennadiycivil** [comment]
@mwoehlke-kitware could you please take a look, @Cylix reported
