### ISSUE TITLE
TypeWithoutFormatter doesn't work with empty structs

### ISSUE THREAD

**Issue by jeremysalwen** [google/googletest#1163]
When using a an empty struct as a gtest parameter, e.g.

```
struct EmptyType {};
INSTANTIATE_TEST_CASE_P(Foo, FooTests,
                        ::testing::Values(EmptyType{}));
```

gtest will then print out uninitialized memory due to an implementation bug in TypeWithoutFormatter.  sizeof(EmptyStruct{}) == 1, rather than 0, so PrintBytesInObjectTo() will be called with a size of 1, printing out a single byte of uninitialized memory when listing the tests.  Valgrind will notice this error and report the use of uninitialized memory.  An easy fix would be to add a special case for zero-member structs/classes to TypeWithoutFormatter.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
