### ISSUE TITLE
gtest-filepath_test (RootOfWrongDriveDoesNotExists) fails with some removable media types

### ISSUE THREAD

**Issue by nephatrine** [google/googletest#1166]
If the Z:\ drive letter is mapped to certain removable media types like an SD card reader (or probably even a CD-ROM drive or floppy drive), then this test will fail unless media is inserted into the drive. Because the physical hardware is always attached to the computer, the drive "exists" as far as DirectoryExists sees, but _chdrive will still fail when trying to switch over to it since no media is inserted and so the EXPECT_FALSE fails.

What is the expected result of FilePath::DirectoryExists() in the case of a disk/CD/SD drive that has no media inserted?

**Comment by Nephatrine** [comment]
Ended up adding another check in ``TEST(DirectoryTest, RootOfWrongDriveDoesNotExists)`` like this around the EXPECT_FALSE and break:

```CXX
if( GetDriveType(non_drive) != DRIVE_REMOVABLE )
{
  EXPECT_FALSE(FilePath(non_drive).DirectoryExists());
  break;
}
```

It might make sense to also check the type against DRIVE_CDROM and DRIVE_REMOTE as those seem like they could be extant, but not accessible as well. If you want I can submit a PR for this.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
