### ISSUE TITLE
Tizen Studio Unit Test Issue

### ISSUE THREAD

**Issue by MehediAlamgir** [google/googletest#1182]
Hello

I am a Tizen developer. I want to write UnitTest (Google Test) for my C++ tizen project in Tizen Studio using Google Test. But i am facing difficulties to write unit test in tizen studio. 

My problems are 

1. When i create a unittest project and build it without writing anything here, it shows some error.
 
2. When i create a unit test project for my tizen project, It automatically creates a hidden source file in unit test project which is duplicate of one of my source file. For example my project structure is

TextSVC/src/ 

there are several folders under "TextSVC/src"  named Database,Factory etc and a source file named  "TextSvc.cpp". In my created unittest project it creates a hidden folder named ".TextSvc.cpp" in the location of "TextSVCTest/src".

The error is, unittest project did not find a header file of that hidden ".TextSvc.cpp" file. If i delete that header file from hidden ".TextSvc.cpp" and build the unittest project again, it automatically return that header file again. on ther otherhand, If i click on that missing header file, that header file opens
in ide which means that header file exists.

3. The project for which i create a unittest project, it shows "multiple declaration of variableName" error where "variableName" is all declared variables of my project class

4. If my project use a custom written library, the unittest project did not find the some of the code of that custom library.

Can you please provide me the solutions of my above facing errors in Tizen unittest project ?

**Comment by hethi** [comment]
Hi Mehedi, this seems to be a Tizen Studio related build problem, not a Google Test one. Without source code available (e.g. on GitHub), probably nobody can help you.
