### ISSUE TITLE
Feature request: Custom typeinfo

### ISSUE THREAD

**Issue by nohajc** [google/googletest#1184]
Sometimes it would be useful to do typed tests on incomplete types.

While that can be achieved by turning RTTI off (typeid does not work with incomplete types), type information is then obviously missing in the report (you only get "\<type\>" for any test case).

There are other ways of obtaining type information (even at compile time - e.g. boost typeindex) but I completely understand you probably don't want to add unnecessary dependencies.

However, a mechanism could be added for the user to provide his own typeinfo function.

```cpp
template <typename T>
std::string GetTypeName() {
# if GTEST_HAS_CUSTOM_TI
  const char* const name = GTEST_CUSTOM_GETTYPENAME(T);
# elif GTEST_HAS_RTTI
  const char* const name = typeid(T).name();
  ...
# else
  return "<type>";
# endif
}
```

Something like this perhaps? I think this could be useful to anyone who cannot use RTTI for some reason but still wants some type information.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by spectras** [comment]
Actually, this feature would be nice to have. I happen to have RTTI disabled on some project with type-parameterized tests, and `where TypeParam = <type>` in gtest output really isn't helpful.

I resort to adding a specialization to internal namespace, which feels brittle:
```cpp
namespace testing::internal {   // dirty hack to have type names despite -fno-rtti
    template <> std::string GetTypeName<feature::plain>() { return "plain"; }
    template <> std::string GetTypeName<feature::sse2>() { return "sse2"; }
    template <> std::string GetTypeName<feature::avx2>() { return "avx2"; }
}
```
Having some similar mechanism not buried in an `internal` namespace would be great.
Should I open a new issue or is re-opening this one ok?

**Comment by EricWF** [comment]
There are two distinct issues here:

1. Tolerating incomplete types in typed tests. This was forcing OP to turn RTTI off.
2. When RTTI is off, use *anything* better than "\<type\>" in diagnostics.

Fully customizable typeinfo is a solution to both. There are other solution of differing quality and difficulty as well. For example, we may be able to parse meaningful type names from the `__PRETTY_FUNCTION__` variable.

**Comment by nohajc** [comment]
> For example, we may be able to parse meaningful type names from the `__PRETTY_FUNCTION__` variable.

This is exactly what boost typeindex does when RTTI is turned off.

Anyway, nice to hear that someone else beside myself finds this useful. :D

**Comment by ian-h-chamberlain** [comment]
Looks like this was previously requested as well: #415 

This is a pretty old issue, but it seems like some way of custom-naming types has been a desirable feature for at least some users for quite a while... it's been a while, but maybe this issue is still worth re-opening?
