### ISSUE TITLE
Parametrized test parameter should be constexpr

### ISSUE THREAD

**Issue by h-2** [google/googletest#1188]
I was really surprised this isn't the case. What's the reason? It not being constexpr prevents many useful tests that have to be created via typed_test + std::integral_constant instead (which is not so nice obviously).

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
