### ISSUE TITLE
Slowdown in google test initalization because of parameterized test

### ISSUE THREAD

**Issue by bosscar** [google/googletest#1195]
We noticed a lot of slowdown in google test initialization because of parameterized test registration.
Is there any options to speed up this?  Or is there any workarounds?

`// This method expands all parameterized tests registered with macros TEST_P
// and INSTANTIATE_TEST_CASE_P into regular tests and registers those.
// This will be done just once during the program runtime.
void UnitTestImpl::RegisterParameterizedTests() {
#if GTEST_HAS_PARAM_TEST
  if (!parameterized_tests_registered_) {
    parameterized_test_registry_.RegisterTests();
    parameterized_tests_registered_ = true;
  }
#endif`

**Comment by gennadiycivil** [comment]
Need concrete proof , repeatable tests, etc

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
