### ISSUE TITLE
Conditional Compilation Flag GTEST_HAS_TR1_TUPLE=0 does not turn off tuple features?

### ISSUE THREAD

**Issue by nyavramov** [google/googletest#1196]
Hi there, 

I'm trying to build Google Mock on Embarcadero's Rad Studio C++ Builder 10.2:

![image](https://user-images.githubusercontent.com/6327118/29246143-4af56fce-7fbe-11e7-9da9-8767f1be4bee.png)

**gmock.lib** and **gmock_main.lib** both successfully compile. My problem is that I cannot compile **gmock_test.exe** due to issues with tr1/tuple.

I want to turn off all tuple-related features in GMock per the instructions provided in **gtest-port.h (line 632)**:

![image](https://user-images.githubusercontent.com/6327118/29246132-cf9d356e-7fbd-11e7-969d-f2b34b46f2fd.png)

I provide Rad Studio with the conditional compiler flag:
`GTEST_HAS_TR1_TUPLE=0`

Rad Studio prepends all flags provided with -D so that I am really providing this flag:
`-DGTEST_HAS_TR1_TUPLE=0`
(I tried adding `-D` to my original flag but was given an identifier error, so I know that I'm not supposed to include the `-D`)

This produces the following series of errors:

![image](https://user-images.githubusercontent.com/6327118/29246169-448240da-7fbf-11e7-9cbd-e2552fdf5431.png)

A breakdown of the first error on the list above:
![image](https://user-images.githubusercontent.com/6327118/29246259-db25a9d0-7fc1-11e7-845c-f5495c567325.png)

It appears that Google Mock is still trying to use the tuple features despite the flag I provided. Is there something I'm misunderstanding? Perhaps I am providing the wrong flags?

Other things I've tried:

- I tried tinkering with **gtest-port.h** directly by changing `#define GTEST_HAS_TR1_TUPLE 1` to `#define GTEST_HAS_TR1_TUPLE 0` everywhere I saw that macro.
- In **gtest-port.h**, I also tried changing `GTEST_HAS_STD_TUPLE_ 1` to `GTEST_HAS_STD_TUPLE_ 0` which created thousands of other errors, so that didn't work either. 
- I tried forcing Google Mock to use its own implementation of tr1/tuple, but that also produces a slew of errors. Visual Studio also cannot use Google Mock's own implementation of tuple, so I suspect it's the same case for Rad Studio. 

I'm pretty new to Google Mock / Google Test so any help would be appreciated. 

Thanks a bunch.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
