### ISSUE TITLE
CMake install dir is broken

### ISSUE THREAD

**Issue by Cylix** [google/googletest#1198]
Hey,

I used to have the following in my CMakeList:

```
  ExternalProject_Add("googletest"
                      GIT_REPOSITORY "https://github.com/google/googletest.git"
                      CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX=${PROJECT_SOURCE_DIR}/deps")
```

It worked great until recently.
Now, it appears that the gtest headers are not installed (only the gmock headers are), which leads to break my builds.

If I specify a specific previous commit (5 days ago), it works fine again:

```
  ExternalProject_Add("googletest"
                      GIT_REPOSITORY "https://github.com/google/googletest.git"
                      GIT_TAG "461713fec4603806d2049835c0790bf94d2db631"
                      CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX=${PROJECT_SOURCE_DIR}/deps")
```

So, seems like there is a recent change in your cmake configuration that breaks the headers installation.

Best

**Comment by Cylix** [comment]
Btw, I also tried the recommanded CMake config from your doc, but the result is the same: only gmocks headers are installed.


```
-- Install configuration: ""
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/lib/libgmock.a
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/lib/libgmock_main.a
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/gmock-actions.h
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/gmock-cardinalities.h
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/gmock-generated-actions.h
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/gmock-generated-actions.h.pump
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/gmock-generated-function-mockers.h
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/gmock-generated-function-mockers.h.pump
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/gmock-generated-matchers.h
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/gmock-generated-matchers.h.pump
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/gmock-generated-nice-strict.h
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/gmock-generated-nice-strict.h.pump
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/gmock-matchers.h
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/gmock-more-actions.h
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/gmock-more-matchers.h
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/gmock-spec-builders.h
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/gmock.h
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/internal
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/internal/custom
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/internal/custom/gmock-generated-actions.h
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/internal/custom/gmock-generated-actions.h.pump
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/internal/custom/gmock-matchers.h
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/internal/custom/gmock-port.h
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/internal/gmock-generated-internal-utils.h
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/internal/gmock-generated-internal-utils.h.pump
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/internal/gmock-internal-utils.h
-- Installing: /Users/cylix/personal_projects/cpp_redis/deps/include/gmock/internal/gmock-port.h
```

**Comment by CHChang810716** [comment]
I have exactly same problem.

**Comment by gennadiycivil** [comment]
... If I specify a specific previous commit (5 days ago), it works fine again:
Could you please provide details? Which commit works and which commit stops working

**Comment by Cylix** [comment]
Hey,

So I spent a bit time and it is pretty weird.

I fixed it by putting the following commit: 461713fec4603806d2049835c0790bf94d2db631
Then afterwhile it got broken (not sure which commit though).
Seems it was fixed at: a4121dd54b58e88107166d8c8ed9eca58ce96629 (but I dont understand why since it only changes the README?)
And got broken again at 08b1a1f73cec48481ec3e477e8c247e7aa534df5
Right now, the current master branch is broken.

**Comment by Cylix** [comment]
Got it: the original commit that break the install is the following one: 0e8e0e07d6c4bc8c9cd6df5407452c12752ab45c

My guess is that [this line](https://github.com/google/googletest/commit/0e8e0e07d6c4bc8c9cd6df5407452c12752ab45c#diff-af3b638bc2a3e6c650974192a53c7291R18) changed the default behavior

**Comment by gennadiycivil** [comment]
Thank you for the investigation. Please check the documentation, is this actually a *bug* or a * feature*? 
If this is a *bug* then the logical next step is to prepare a PR fixing the issue. If you decide to go that route please prepare a PR and demonstrate a test case before and after

**Comment by Cylix** [comment]
This is for sure a regression as my Travis is based on this behavior for the past 6 months and the documentation does not mention anything in particular concerning any mandatory option to set in order to install the includes.
I'll try to provide a fix if I find the time :)

**Comment by mwoehlke-kitware** [comment]
Interesting; that line says that the `INSTALL_GTEST` option should be shown if `BUILD_GTEST OR BUILD_GMOCK`... but it seems it is only being shown if `BUILD_GTEST` (which is OFF by default), and thus `INSTALL_GTEST` is OFF.

It is possibly fixable like:

    -option(BUILD_GTEST "..." OFF)
    +cmake_dependent_option(BUILD_GTEST "..." ON "NOT BUILD_GMOCK" ON)

...because gtest is necessarily built if gmock is built. However, I'm not sure if hiding that option would be more or less confusing.

Meanwhile, I'm investigating why `cmake_dependent_option` seems to be acting screwy...

**Comment by mwoehlke-kitware** [comment]
D'oh... ordering issue... PR coming up...
