### ISSUE TITLE
gtest crashes with libc++ (+ patch to fix the issue)

### ISSUE THREAD

**Issue by m-gupta** [google/googletest#1207]
Some packages in ChromeOS crash in gtest when built using libc++. 
gtest/internal/gtest-port.h:1394:: Condition typeid(*base) == typeid(Derived) failed.

After some debugging, I believe that the issue is in gtest where it was using typeid but the visibility of class was not marked as default. 

There is an explanation about typeinfo and visibility here:
https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/CppRuntimeEnv/Articles/SymbolVisibility.html

Excerpt from the article:
If your symbol uses runtime type identification (RTTI) information, exceptions, or dynamic casts for an object that is defined in another library, your symbol must be visible if it expects to handle requests initiated by the other library. For example, if you define a catch handler for a type in the C++ standard library, and you want to catch exceptions of that type thrown by the C++ standard library, you must make sure that your typeinfo object is visible.

The follwoing patch fixes the crash in my testing by making ThreadLocal class visibility as default.

diff -Nuar old/googletest/include/gtest/internal/gtest-port.h new/googletest/include/gtest/internal/gtest-port.h
--- old/googletest/include/gtest/internal/gtest-port.h
+++ new/googletest/include/gtest/internal/gtest-port.h
@@ -2027,7 +2027,7 @@
 
 // Implements thread-local storage on pthreads-based systems.
 template <typename T>
-class ThreadLocal {
+class GTEST_API_ ThreadLocal {
  public:
   ThreadLocal()

**Comment by gennadiycivil** [comment]
Thank you for the contribution. In order for this to be considered please make a proper Pull Request, and include clearly reproducible test cases

**Comment by m-gupta** [comment]
Sent https://github.com/google/googletest/pull/1296
