### ISSUE TITLE
Regular expressions from C++ 11?

### ISSUE THREAD

**Issue by lbartnik** [google/googletest#1208]
Hi, I did a preliminary check and it doesn't seem that Google Test uses C++'s regex library. Would you be interested in adding it? Or are there reasons why this is not a good idea?

If it is something worthwhile, I'd like to take a closer look and propose a pull request.

**Comment by jwakely** [comment]
The README lists the base requirement for using googletest as "A C++98-standard-compliant compiler" which would have to change to use `std::regex`. In particular, it would mean versions of GCC older than 4.9.0 would be unsupported, since older releases don't support `std::regex`.

**Comment by ThomasTacquet** [comment]
Without speaking about the base requirement, for curiosity purposes, would std::regex be faster than other regex engines ?

**Comment by KindDragon** [comment]
It probably doesn't support all required Regex features

**Comment by jwakely** [comment]
I doubt that. What features are required? I see POSIX EREs which are certainly supported by `std::regex` (along with BREs, Ecmascript, awk, grep and egrep formats).

**Comment by KindDragon** [comment]
Check this https://github.com/google/googletest/blob/96f3745e73d5541419617006e9571b572a098f91/googlemock/test/gmock-spec-builders_test.cc#L1149-L1169

GTest use some advanced fetures

**Comment by jwakely** [comment]
Challenge accepted:
https://wandbox.org/permlink/PFHMeBC8B4cPGNu5

**Comment by lbartnik** [comment]
Actually, the reason I asked was that Google Test in Windows has a limited support for regex because it uses an in-house implementation of the regex engine. In Linux it uses the POSIX library, AFAIR.

Now, would it be an option to enable regex in C++11 compatible compilers? Because that would bring regex to the same level on both platforms, and thus do away with platform-specific test cases.

**Comment by jwakely** [comment]
The minimum requirement on Windows is Microsoft Visual C++ 2010 or newer, so it should be possible to use `std::regex` when the compiler is MSVC, and stick to pcre or posix otherwise.

**Comment by lbartnik** [comment]
Right... So, @jwakely, are you in position to advise how to approach this? Should I simply work on a pull request? Or maybe get an initial OK from the future approver? I ask because I would be sad to spend time on this only to get my PR declined.

**Comment by Bu11etmagnet** [comment]
You'd need something like https://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions/41186162#41186162 to decide whether `std::regex` is usable or not.

**Comment by jwakely** [comment]
@Bu11etmagnet   that's for testing if libstdc++ supports `std::regex`, but that's not the problem: on GNU/Linux the POSIX `regcomp` function works fine, so `std::regex` isn't needed. It's needed on Windows, so that test is useless.

**Comment by jwakely** [comment]
Something like this maybe:
https://github.com/google/googletest/compare/master...jwakely:std-regex

**Comment by thomthom** [comment]
Seeiing how GoogleTest 1.9 will require C++11, having `std::regex` would be very nice. Is this something that is open for a PR?

**Comment by jwakely** [comment]
If it's going to require C++11, then it should just require a compiler that supports C++11 properly. And then surely there's no problem using `std::regex`?

**Comment by thomthom** [comment]
The README says:

> 1.8.x Release - the 1.8.x is the last release that works with pre-C++11 compilers.

There is also this announcement in another issue created by the team: https://github.com/abseil/googletest/issues/1366

> An update from googletest team: it's decided starting from version 1.9.0 googletest will require C++11 to compile.

So I'm curious, would a PR with `std:regex` be accepted?

**Comment by thomthom** [comment]
FYI, I added my own custom matches like this:

```cpp
#pragma warning( push )
#pragma warning( disable : 4100 ) 
MATCHER_P(MatchesStdRegex, pattern, "MatchesRegex using std::regex") {
  std::regex regex(pattern);
  return std::regex_match(arg, regex);
}

MATCHER_P(ContainsStdRegex, pattern, "ContainsRegex using std::regex") {
  std::regex regex(pattern);
  return std::regex_search(arg, regex);
}
#pragma warning( pop )
```

However, I still think it would benefit the framework to support `std::regex` out of the box with existing ASSERTs going forward with C++11. The current version with platform dependant regex support got klunky very fast.

**Comment by gennadiycivil** [comment]
Just a note:
master already requires C++ 11 and has been for some time.

Regarding regular expressions:

Yes, we would consider a PR , however please take a look  (
http://go/gh/abseil/googletest/blob/b49266606875a8fa6cac79a05002d490a9a2af07/googletest/include/gtest/internal/gtest-port.h),
the  GTEST_USES_PCRE has to stay.
Completely removing GTEST_USES_SIMPLE_RE would be very welcome, however I
am not sure how std::regex would compare , will it have exact same
functionality so not to break exising users?

Thanks
G

**Comment by gennadiycivil** [comment]
@thomthom , answering your question
1. Yes, I had internal link ( wrong copy/paste ) sorry about that

2. GTEST_USES_PCRE - internally googletest will use RE2. the macro is set using customization point. 

3. How to add std::regex support - the best end-state scenario would be if googletest drops its own simple RE implementation and replace it with std::regex. This would be the right direction. So it would work "the same" on POSIX systems as well as internally but drops this simple RE ( not very capable anyway ) 
Of course the huge caveat here is that we need to make sure this is a non-breaking change .

What do you think?

Thanks
G

**Comment by gennadiycivil** [comment]
Ping

**Comment by thomthom** [comment]
My gut feeling is that it won't be existing syntax in either variant can be compatible with `std::regex`. As mentioned, the simple variant, on Windows, is a subset of `std::regex`'s default `ECMAScript` syntax. But, what didn't had to be escaped in Simple might need escaping in `ECMAScript`.

And then I think we'll have the same scenario with `GTEST_USES_POSIX_RE`. Maybe if `std::regex` used its `posix` variant. But `GTEST_USES_SIMPLE_RE` is not a subset of `GTEST_USES_POSIX_RE`. So it breaks either way.

Question is, since introducing C++11 requirement with GoogleTest 1.9 - would that be an opportunity to introduce `std::regex` with `ECMAScript` syntax as default? With macros to switch back to legacy behaviour as quick-fix for those running into issues migrating from older versions?

**Comment by gennadiycivil** [comment]
I am tempted to conclude that "this is not happening" and close this issue. I just don't see real practical benefit for making a breaking change.

**Comment by thomthom** [comment]
The benefit is cross platform consistently, which I think is valuable. But, maybe it's not worth breaking changes of default behaviour.

Perhaps include `std::regex` matchers as an easy opt-in? Or as a minimum include something like my example above (https://github.com/google/googletest/issues/1208#issuecomment-442224080) in the documentation?

```
#pragma once

#include <regex>
#include "gmock/gmock.h"

#pragma warning( push )
#pragma warning( disable : 4100 ) // Mute unused result_listener arg.
MATCHER_P(MatchesRegex, pattern, "MatchesRegex using std::regex") {
  std::regex regex(pattern);
  return std::regex_match(arg, regex);
}

MATCHER_P(ContainsRegex, pattern, "ContainsRegex using std::regex") {
  std::regex regex(pattern);
  return std::regex_search(arg, regex);
}
#pragma warning( pop )
```

That might be enough to easily get started with cross platform regex in GoogleMock. There's much more that could be done with all the options and flavors that `std::regex` offer, but the above is bare minimum to get started.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by wrowe** [comment]
See https://github.com/google/googletest/pull/2422 for further followup/proposal
