### ISSUE TITLE
GoogleTest: Small test parameter class causes Valgrind Error

### ISSUE THREAD

**Issue by JimCarroll64** [google/googletest#1213]
I've been writing a number of parameterized tests in GoogleTest that take a class as their parameter so I can pass a few different values to it. A couple of these classes are rather small, like in the following:

    class MyParams
    {
        public:
    
        bool _thing1;
        bool _thing2;
        bool _thing3;
    
        MyParams(bool thing1, bool thing2, bool thing3) :
            _thing1(thing1), _thing2(thing2), _thing3(thing3)
        {}  
    };
    
    class MyTestFixture : public ::testing::TestWithParam<MyParams>
    {
    };
    
    TEST_P(MyTestFixture, MyParamTest)
    {
    }
    
    INSTANTIATE_TEST_CASE_P(MyTests, MyTestFixture, ::testing::Values(MyParams(false, false, false)));
    
    int main(int argc, char **argv)
    {
        ::testing::InitGoogleTest(&argc, argv);
        return RUN_ALL_TESTS();
    }

When I run the test with Valgrind, it reports an error when GoogleTest initializes the test cases:

    ==12555== Invalid read of size 8
    ==12555==    at 0x408DE7: testing::internal::ParameterizedTestCaseInfo<MyTestFixture>::RegisterTests() (gtest-param-util.h:516)
    ==12555==    by 0x4221E9: testing::internal::ParameterizedTestCaseRegistry::RegisterTests() (gtest-param-util.h:602)
    ==12555==    by 0x40FB9F: testing::internal::UnitTestImpl::RegisterParameterizedTests() (gtest.cc:2290)
    ==12555==    by 0x416624: testing::internal::UnitTestImpl::PostFlagParsingInit() (gtest.cc:4125)
    ==12555==    by 0x42A149: void testing::internal::InitGoogleTestImpl<char>(int*, char**) (gtest.cc:4991)
    ==12555==    by 0x418259: testing::InitGoogleTest(int*, char**) (gtest.cc:5006)
    ==12555==    by 0x404829: main (MyParamTests.C:28)
    ==12555==  Address 0x5e432c0 is 0 bytes inside a block of size 3 alloc'd
    ==12555==    at 0x4C2A105: operator new(unsigned long) (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
    ==12555==    by 0x409B6F: testing::internal::ValuesInIteratorRangeGenerator<MyParams>::Iterator::Current() const (gtest-param-util.h:311)
    ==12555==    by 0x4094CE: testing::internal::ParamIterator<MyParams>::operator*() const (gtest-param-util.h:113)
    ==12555==    by 0x408DE6: testing::internal::ParameterizedTestCaseInfo<MyTestFixture>::RegisterTests() (gtest-param-util.h:516)
    ==12555==    by 0x4221E9: testing::internal::ParameterizedTestCaseRegistry::RegisterTests() (gtest-param-util.h:602)
    ==12555==    by 0x40FB9F: testing::internal::UnitTestImpl::RegisterParameterizedTests() (gtest.cc:2290)
    ==12555==    by 0x416624: testing::internal::UnitTestImpl::PostFlagParsingInit() (gtest.cc:4125)
    ==12555==    by 0x42A149: void testing::internal::InitGoogleTestImpl<char>(int*, char**) (gtest.cc:4991)
    ==12555==    by 0x418259: testing::InitGoogleTest(int*, char**) (gtest.cc:5006)
    ==12555==    by 0x404829: main (MyParamTests.C:28)

The memory reported is an instance of the parameter class. It appears to only occur for small sizes of the class (1-3 or 5-7. Any different size does not trigger the valgrind error). Accordingly, padding the class above makes the error go away.

The tests work great regardless, but wondering if I'm not doing something right.

GoogleTest version is 1.7.0. GCC version is 4.8.5.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
