### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Beshkent** [google/googletest#1244]
Hi,
While checking our project for dynamic memory leak using Intel Inspector I found an issue in using GetThreadLocalsMapLocked(). Intel inspector says, that memo is not deallocated in that function and points static ThreadIdToThreadLocals* map = new ThreadIdToThreadLocals;

WBR,
Dilshod

**Comment by jwakely** [comment]
It's a global that persists for the lifetime of the program, why does it need to be deallocated?

**Comment by ShadowIce** [comment]
The problem with this is that it's printed as part of the memory leak report (when using the boost testing framework with gmock for example) which makes it harder to find more serious memory leaks.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
