### ISSUE TITLE
gtest_prod_test-md can't debug in x64 /md                          error LNK2019 CrtDbgReportW

### ISSUE THREAD

**Issue by zhenyi100056** [google/googletest#1258]
buildgtest_prod_test-md with  x64 /Md,
error LNK2019 CrtDbgReportW
error LNK1120

so my project build with x64 Md can't depend on gtestd.lib build under x64 md
error LNK2038 
error LNK2019   CrtDbgReportW

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
