### ISSUE TITLE
REGISTER_TYPED_TEST_CASE_P: Limit of 50

### ISSUE THREAD

**Issue by smessmer** [google/googletest#1267]
The REGISTER_TYPED_TEST_CASE_P macro has a limit of 50 parameters. We're using it quite extensively in one of our test suites and now encountered the limit. Is there an easy way we can fix this in our code base? If not, can it be fixed in googletest?

**Comment by pwnall** [comment]
Seems easy to tweak if you're willing to regenerate the headers.
https://github.com/google/googletest/blob/master/googletest/include/gtest/internal/gtest-type-util.h.pump#L2

FWIW, I just ran into this as well. I'm going to work around it by breaking up my test.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
