### ISSUE TITLE
gmock_gen.py parameter generation ignores pointer

### ISSUE THREAD

**Issue by TypeKazt** [google/googletest#1278]
I've experienced missed asterisk's when using the gmock_gen.py script to generate a mocked class.

Here is an example of a method it failed to mock properly: 
`virtual bool doStuff(double x, const ClassA& a, ClassB* b = 0) = 0;`

`MOCK_METHOD3(doStuff,
      bool(double, ClassA, IMHSObserver));`

**Comment by gennadiycivil** [comment]
Thank you very much for this report. Unfortunately there appears to be no actionable information.
