### ISSUE TITLE
Can not get properties on the original order from xml

### ISSUE THREAD

**Issue by avk2** [google/googletest#1280]
I have encountered the problem where I would want to use `RecordProperty()` and then parsing the output xml file and showing that extra information (on html) is not in the same order as I expected.

```
            for z in range(len(node.attributes.items())):
                k = node.attributes.item(z).name
                v = node.attributes.item(z).value
```

The issue is that DOM doesn't return attributes in any order (see https://stackoverflow.com/a/3728241/2968729). 

A dirty workaround would be to set my key attributes with a code so then I can sort them. 

Apart of changing to another xml processor, what would you suggest?

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
