### ISSUE TITLE
Small Documentation bug: incorrect macro used on Cheat Sheet for specifying calling convention

### ISSUE THREAD

**Issue by btpnlsl** [google/googletest#1282]
The documentation for specifying the calling convention of a mock method uses an incorrect macro.

Here is a link to the section: [https://github.com/google/googletest/blob/master/googlemock/docs/CheatSheet.md#specifying-calling-conventions-for-mock-functions](https://github.com/google/googletest/blob/master/googlemock/docs/CheatSheet.md#specifying-calling-conventions-for-mock-functions)

Here is the incorrect text:
`MOCK_METHOD_1_WITH_CALLTYPE(STDMETHODCALLTYPE, Foo, bool(int n));`

The text should read:
`MOCK_METHOD1_WITH_CALLTYPE(STDMETHODCALLTYPE, Foo, bool(int n));`

Thank you.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
