### ISSUE TITLE
MinGW-w64 - MinGW-Builds shared library support 

### ISSUE THREAD

**Issue by FlorianWolters** [google/googletest#1287]
It does not seem to be possible to compile a shared library version of Google Test v1.8.0 with [MinGW-w64 - MinGW-Builds](http://mingw-w64.org/doku.php/download) (v7.1.0, x86_64, POSIX threads) using a Windows 10.0.14393 x86_64 operating system and the build tools [CMake](https://cmake.org) v.3.9.4 x86_64 and [Ninja](https://ninja-build.org) v1.8.2 x86.

The batch script used for the build (you have to modify the file paths to match with your environment):

    @ECHO OFF

    SET ARCHITECTURE=x64
    SET PROJECT=gtest
    SET VERSION=1.8.0

    SET PATH=D:\dev\native\cmake\cmake-3.9.4-%ARCHITECTURE%\bin;^
    D:\dev\native\ninja\ninja-1.8.2-x86;^
    D:\dev\native\mingw-builds\mingw-builds-7.1.0-%ARCHITECTURE%\bin

    cmake -HD:/dev/_builds/%PROJECT%-%VERSION%^
     -BD:/dev/_builds/build-%PROJECT%-%VERSION%/%ARCHITECTURE%/mgw71/shared/Release^
     -GNinja^
     -DCMAKE_BUILD_TYPE=Release^
     -DCMAKE_C_COMPILER=gcc^
     -DCMAKE_CXX_COMPILER=gcc^
     -DBUILD_SHARED_LIBS=ON^
     -Dgtest_disable_pthreads=ON^
     > configure.log 2>&1
    cmake --build D:/dev/_builds/build-%PROJECT%-%VERSION%/%ARCHITECTURE%/mgw71/shared/Release^
     --config Release^
     > build.log 2>&1

The build step fails when trying to link the shared library `libgtest.dll` (see below for the full output):

    [8/11] Linking CXX shared library googlemock\gtest\libgtest.dll
    FAILED: googlemock/gtest/libgtest.dll googlemock/gtest/libgtest.dll.a 
    cmd.exe /C "cd . && D:\dev\native\mingw-builds\mingw-builds-7.1.0-x64\bin\gcc.exe  -O3 -DNDEBUG   -shared -o googlemock\gtest\libgtest.dll -Wl,--out-implib,googlemock\gtest\libgtest.dll.a -Wl,--major-image-version,0,--minor-image-version,0 googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj -LD:/dev/_builds/build-gtest-1.8.0/x64/mgw71/shared/Release/googlemock/gtest/src -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x89e): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long long&, unsigned long long)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x8f1): undefined reference to `std::__throw_logic_error(char const*)'

How-to fix this? Is it required to enforce a certain C++ standard (e.g. C++11) and/or to set one or more preprocessor constants? Is Protobuf meant to be used with MinGW-w64 - MinGW-Builds at all? It is possible to compile and link a static library version though.

----

The full output of the configure step:

    -- The C compiler identification is GNU 7.1.0
    -- The CXX compiler identification is GNU 7.1.0
    -- Check for working C compiler: D:/dev/native/mingw-builds/mingw-builds-7.1.0-x64/bin/gcc.exe
    -- Check for working C compiler: D:/dev/native/mingw-builds/mingw-builds-7.1.0-x64/bin/gcc.exe -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: D:/dev/native/mingw-builds/mingw-builds-7.1.0-x64/bin/gcc.exe
    -- Check for working CXX compiler: D:/dev/native/mingw-builds/mingw-builds-7.1.0-x64/bin/gcc.exe -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) 
    -- Configuring done
    -- Generating done
    -- Build files have been written to: D:/dev/_builds/build-gtest-1.8.0/x64/mgw71/shared/Release

The shortened output of the build step:

    [1/11] Building CXX object googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.obj
    [2/11] Building CXX object googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.obj
    [3/11] Building CXX object googlemock/CMakeFiles/gmock_main.dir/src/gmock-all.cc.obj
    [4/11] Building CXX object googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.obj
    [5/11] Building CXX object googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj
    [6/11] Building CXX object googlemock/CMakeFiles/gmock_main.dir/__/googletest/src/gtest-all.cc.obj
    [7/11] Building CXX object googlemock/CMakeFiles/gmock.dir/__/googletest/src/gtest-all.cc.obj
    [8/11] Linking CXX shared library googlemock\gtest\libgtest.dll
    FAILED: googlemock/gtest/libgtest.dll googlemock/gtest/libgtest.dll.a 
    cmd.exe /C "cd . && D:\dev\native\mingw-builds\mingw-builds-7.1.0-x64\bin\gcc.exe  -O3 -DNDEBUG   -shared -o googlemock\gtest\libgtest.dll -Wl,--out-implib,googlemock\gtest\libgtest.dll.a -Wl,--major-image-version,0,--minor-image-version,0 googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj -LD:/dev/_builds/build-gtest-1.8.0/x64/mgw71/shared/Release/googlemock/gtest/src -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x89e): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long long&, unsigned long long)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x8f1): undefined reference to `std::__throw_logic_error(char const*)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x95e): undefined reference to `operator delete(void*)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x96b): undefined reference to `operator delete(void*, unsigned long long)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x9e2): undefined reference to `std::ostream::put(char)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x9f7): undefined reference to `std::ctype<char>::_M_widen_init() const'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0xa1e): undefined reference to `std::__throw_bad_cast()'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0xa75): undefined reference to `operator delete(void*)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0xb12): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long long)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0xb21): undefined reference to `operator delete(void*)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0xb34): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long long) const'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0xb5d): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long long)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0xba7): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long long)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0xbba): undefined reference to `operator delete(void*)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0xbda): undefined reference to `std::__throw_length_error(char const*)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0xbea): undefined reference to `operator delete(void*)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0xc15): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0xc2e): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0xc44): undefined reference to `operator delete(void*)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0xe0e): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0xf1b): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0xfd7): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x100d): undefined reference to `operator delete(void*)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x1076): undefined reference to `operator new(unsigned long long)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x10d2): undefined reference to `operator delete(void*, unsigned long long)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x1101): undefined reference to `operator delete(void*)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x13e5): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x14f0): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x164f): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x18eb): undefined reference to `operator new(unsigned long long)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x199f): undefined reference to `operator new(unsigned long long)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x19af): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x19da): undefined reference to `operator delete(void*, unsigned long long)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x1a0e): undefined reference to `operator new(unsigned long long)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x1a5a): undefined reference to `operator delete(void*, unsigned long long)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x1bb0): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x1be6): undefined reference to `std::ostream::operator<<(int)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x1bf2): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x1bfa): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x1c34): undefined reference to `std::ctype<char>::_M_widen_init() const'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x1c60): undefined reference to `std::__throw_bad_cast()'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x1c6b): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x1c9d): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)'
    googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj:gtest-all.cc:(.text+0x1cc2): undefined reference to `std::ostream::operator<<(int)'

**Comment by eintw1ck** [comment]
You set your CXX compiler to gcc try setting it to g++

**Comment by FlorianWolters** [comment]
@eintw1ck I am stupid. Thanks for the hint. I am using MSVC now anyways.
