### ISSUE TITLE
Option to print always the Actual and Expected values 

### ISSUE THREAD

**Issue by avk2** [google/googletest#1291]
It would be nice if it was possible to print the Actual and Expected result always and not only when the test fails. 

At my work, the client asks for a detailed output with the actual and expected values (https://github.com/avk2/gtest_report). So I'm using `RecordProperty()` as workaround. Which results on:

- A lot of repetitive work
- Dirty tests functions with RecordProperty messages everywhere
- RecordProperty isn't suitable for verbose because DOM processor doesn't retrieve the key attributes in any order

Example:
```
TEST(FooTest, testing_foo) {
    EXPECT_TRUE(foo());
    EXPECT_FALSE(fooo();

    RecordProperty("n01_ACTUAL","");
    RecordProperty("n02_foo", foo());
    RecordProperty("n03_fooo, fooo());
   

    RecordProperty("n04_EXPECTED","");
    RecordProperty("n05_foo", true);
    RecordProperty("n06_fooo, false);
}
```

I add the prefix 'nXX' so I can sort them.

As you can imaging, having to do this for considerable number of tests is insane and not maintainable.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
