### ISSUE TITLE
Separate gtest-printers.h into a standalone library?

### ISSUE THREAD

**Issue by alex-weej** [google/googletest#1301]
I've found great utility in `::testing::internal::UniversalTersePrint` in contexts other than writing test suites. I've trivially implemented something akin to `std::quoted`, but which works for anything that's printable by gtest:

```c++
// "quoted" only works for strings:
std::cout << "The string is: " << std::quoted(the_string) << "\n";

// "dumped" works for anything that gtest supports, or that authors have added support for: 
std::cout << "The thing is: " << dumped(the_thing) << "\n";
```

It seems it would be useful for the wider C++ community if there was at least some effort to standardise a protocol, e.g. `PrintTo`, for this. But gtest-printers being part of gtest itself is a little funny for people to swallow -- perhaps people prefer Catch or Boost.Test, I don't know.

Thoughts? Maybe this is only viable as an actual ISO C++ standards proposal... Maybe one already exists?

Thanks

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by alex-weej** [comment]
@gennadiycivil Would you be OK with reopening this one? This has become a little more pertinent to our organization recently. Thanks

**Comment by alex-weej** [comment]
Possibly Abseil is a good home for this given that Google Test now has a hard dependency on Abseil...
