### ISSUE TITLE
All test fixture passed but final result failed

### ISSUE THREAD

**Issue by z63zheng** [google/googletest#1306]
Something strange happened when I was using google test. In this test I have three fixtures. When I ran the test, all of them are passed but the final result is failed. And there are no error messages. The result in visual studio indicate segfault but no error messages are shown in the output. I tried to debug it but I cannot do it without some error messages.

Here is the output. I change the names of the test because I am not allowed to show them.
Output:
----------------------------------------------------------
Running main() from gtest_main.cc
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from MyTest
[ RUN      ] MyTest.Test1
[       OK ] MyTest.Test1 (63 ms)
[ RUN      ] MyTest.Test2
[       OK ] MyTest.Test2 (31 ms)
[ RUN      ] MyTest.Test3
[       OK ] MyTest.Test3 (62 ms)
[----------] 3 tests from MyTest (156 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test case ran. (156 ms total)
[  PASSED  ] 3 tests.
<end of output>
Test time =   0.80 sec
----------------------------------------------------------
Test Failed.
"MyTest_gtestRun" end time: Oct 23 12:24 Pacific Daylight Time
"MyTest_gtestRun" time elapsed: 00:00:00
----------------------------------------------------------

Any possible reasons causing this problem? Are there anything I can do to show more error message about the problem?

**Comment by gennadiycivil** [comment]
Thank you very much for this report. Unfortunately there appears to be no actionable information.
