### ISSUE TITLE
Add full implementation of IncrementCounter to example

### ISSUE THREAD

**Issue by JoostvanPinxten** [google/googletest#1307]
Took me some time to figure out how the Google Mock code wants the Factory to be formatted; in the end I missed the inline function that wraps the action, and tried too soon to implement my own logic on top of it (which got messy fast).

The following snippet, in combination with the cookbook.md suggestions, made it work as reported in the cookbook.

```c++
struct IncrementCounterAction {
    explicit IncrementCounterAction(int init) : init(init) {

    }

    template <typename F>
    operator ::testing::Action<F>() const {
      return ::testing::Action<F>(new Impl<F>(init));
    }

    int init;
    private:

     template <typename F>
     class Impl : public testing::ActionInterface<F> {
      public:
       typedef typename testing::internal::Function<F>::Result Result;
       typedef typename testing::internal::Function<F>::ArgumentTuple ArgumentTuple;

       explicit Impl(int init) : init(init) {}  // NOLINT

       virtual Result Perform(const ArgumentTuple&) {
         return ++init;
       }

      private:
       int init;

       GTEST_DISALLOW_ASSIGN_(Impl);
     };

     GTEST_DISALLOW_ASSIGN_(IncrementCounterAction);
};

// Creates an action that returns an incremented integer value, starting from x+1
inline IncrementCounterAction IncrementCounter(int x) {  // NOLINT
  return IncrementCounterAction(x);
}
```

**Comment by JoostvanPinxten** [comment]
Also, I'd like my code to be independent of the `::testing::internal` but that doesn't seem to be possible?

In addition, why can lambdas with captures and std::functions not be converted into FactoryFunction's (I'm using G++4.9)?

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
