### ISSUE TITLE
Mildly confusing documentation for googlemock CheatSheet - Mocking a Class Template

### ISSUE THREAD

**Issue by Quincunx271** [google/googletest#1309]
The [documentation on mocking class templates][1] can be improved. If you simply copy-n-paste the code, removing the ellipses, you will get a linker error, as `~StackInterface()` isn't defined. This is at the very least mildly confusing, especially to people unfamiliar with linker errors.

I'm proposing changing this:

```c++
template <typename Elem>
class StackInterface {
 public:
  ...
  virtual ~StackInterface();
  virtual int GetSize() const = 0;
  virtual void Push(const Elem& x) = 0;
};
```

To this (or some other variation that defines the destructor):

```c++
template <typename Elem>
class StackInterface {
 public:
  ...
  virtual ~StackInterface() = default;
  virtual int GetSize() const = 0;
  virtual void Push(const Elem& x) = 0;
};
```

  [1]: https://github.com/google/googletest/blob/master/googlemock/docs/CheatSheet.md#mocking-a-class-template

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.
