### ISSUE TITLE
Mock leak when expecting call with shared_ptr to mock itself as argument

### ISSUE THREAD

**Issue by estan** [google/googletest#1310]
Example:

```cpp
#include <memory>

#include <gtest/gtest.h>
#include <gmock/gmock.h>

using ::testing::Property;

class A { public: virtual void f(std::shared_ptr<A>) {} };

class MockA : public A { public: MOCK_METHOD1(f, void(std::shared_ptr<A>)); };

TEST(MyTest, test) {
    auto mock = new MockA;
    auto mockShared = std::shared_ptr<A>(mock);

    // Expect f to be called on mock, with a shared_ptr to
    // mock itself as argument.
    EXPECT_CALL(*mock, f(mockShared));

    // Alternative, but less desirable, way to do the expectation
    // which avoids the leak below, using a Property matcher:
    //
    //EXPECT_CALL(*mock, f(Property(&decltype(mockShared)::get, mock)));

    // Call f on mock with a shared_ptr to mock itself as argument.
    mock->f(mockShared);

    // Result:
    //
    // /home/estan/tc/Test.cpp:18: ERROR: this mock object (used
    // in test MyTest.test) should be deleted but never is. Its
    // address is @0xab6790.
}
```

My guess is that this somehow results in a circle of `::testing::internal::linked_ptr` to the mock inside Google Mock, preventing its deletion when the expectations are destroyed.

***Some background:*** I'd really like to be able to do this without getting a leak. In my real code, I have a `PluginManager`, holding `Plugins`, and in some tests I'd like to verify that the manager calls `resolve` on one of the plugins (a mock) with a list of `shared_ptr` to all the plugins (which includes the plugin itself) as argument.

**Comment by gennadiycivil** [comment]
linked_ptr is ( and has been for some time ) gone from googletest

I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by estan** [comment]
@gennadiycivil The problem is still present. This is the test case with googletest/mock `master`:

```
[estan@newton ~]$ ./test
Running main() from gmock_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from MyTest
[ RUN      ] MyTest.test
[       OK ] MyTest.test (0 ms)
[----------] 1 test from MyTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (1 ms total)
[  PASSED  ] 1 test.

test.cpp:18: ERROR: this mock object (used in test MyTest.test) should be deleted but never is. Its address is @0x55b74c8b9990.
ERROR: 1 leaked mock object found at program exit. Expectations on a mock object is verified when the object is destructed. Leaking a mock means that its expectations aren't verified, which is usually a test bug. If you really intend to leak a mock, you can suppress this error using testing::Mock::AllowLeak(mock_object), or you may use a fake or stub instead of a mock.
[estan@newton ~]$
```

**Comment by sbenzaquen** [comment]
The code is making a reference cycle in that the mock object is holding a reference to itself through the `EXPECT_CALL` argument.
You need to break that dependency explicitly to allow for the `shared_ptr` to be collected.
You could, for example, call `testing::Mock::VerifyAndClearExpectations(mock);` at the end of the test to break that reference cycle.

**Comment by estan** [comment]
@sbenzaquen Indeed, thanks for that tip. I realize now that it's not much that googlemock could do about this cycle. Verified your suggestion and it worked.
