### ISSUE TITLE
release-1.8.0 cannot build in Windows+codeblock+MinGW

### ISSUE THREAD

**Issue by Yensan** [google/googletest#1314]
I have tried many methods but always see this error.  It makes me depressed ... If you can, tell me how to build it. Thank you
this is the last methods I used:
1.   open  ..cmake-3.10.0-rc3-win32-x86\bin\cmake-gui.exe 
      source code path: F:/Downloads/googletest-release-1.8.0
       where to build bin: F:/Downloads/tools/gbuild
      choose   MinGW Makefiles
      then, click configure button
2.  choose values in bellow:
      build GMOCK
      build GTEST
      build SHARED LIBS
      GTEST disable pthreads
3.   click configure, then click generate
4.   open  cmd.exe,  cd  to makefile dir   _F:/Downloads/tools/gbuild_   ,  then run    _mingw32-make_

**then, error occurred.**

> F:\Downloads\tools\gbuild>mingw32-make
> Scanning dependencies of target gmock_main
> [  9%] Building CXX object googlemock/CMakeFiles/gmock_main.dir/__/googletest/sr
> c/gtest-all.cc.obj
> In file included from F:\Downloads\googletest-release-1.8.0\googletest\src\gtest
> -all.cc:45:0:
> F:/Downloads/googletest-release-1.8.0/googletest/src/gtest-port.cc: In construct
> or 'testing::internal::Mutex::Mutex()':
> F:/Downloads/googletest-release-1.8.0/googletest/src/gtest-port.cc:242:45: error
> : cannot convert 'CRITICAL_SECTION* {aka _CRITICAL_SECTION*}' to '_RTL_CRITICAL_
> SECTION*' in initialization
>        critical_section_(new CRITICAL_SECTION) {
>                                              ^
> F:/Downloads/googletest-release-1.8.0/googletest/src/gtest-port.cc:243:48: error
> : cannot convert '_RTL_CRITICAL_SECTION*' to 'LPCRITICAL_SECTION {aka _CRITICAL_
> SECTION*}' for argument '1' to 'void InitializeCriticalSection(LPCRITICAL_SECTIO
> N)'
>    ::InitializeCriticalSection(critical_section_);
>                                                 ^
> F:/Downloads/googletest-release-1.8.0/googletest/src/gtest-port.cc: In destructo
> r 'testing::internal::Mutex::~Mutex()':
> F:/Downloads/googletest-release-1.8.0/googletest/src/gtest-port.cc:253:46: error
> : cannot convert '_RTL_CRITICAL_SECTION*' to 'PCRITICAL_SECTION {aka _CRITICAL_S
> ECTION*}' for argument '1' to 'void DeleteCriticalSection(PCRITICAL_SECTION)'
>      ::DeleteCriticalSection(critical_section_);
>                                               ^
> F:/Downloads/googletest-release-1.8.0/googletest/src/gtest-port.cc: In member fu
> nction 'void testing::internal::Mutex::Lock()':
> F:/Downloads/googletest-release-1.8.0/googletest/src/gtest-port.cc:261:43: error
> : cannot convert '_RTL_CRITICAL_SECTION*' to 'LPCRITICAL_SECTION {aka _CRITICAL_
> SECTION*}' for argument '1' to 'void EnterCriticalSection(LPCRITICAL_SECTION)'
>    ::EnterCriticalSection(critical_section_);
>                                            ^
> F:/Downloads/googletest-release-1.8.0/googletest/src/gtest-port.cc: In member fu
> nction 'void testing::internal::Mutex::Unlock()':
> F:/Downloads/googletest-release-1.8.0/googletest/src/gtest-port.cc:271:43: error
> : cannot convert '_RTL_CRITICAL_SECTION*' to 'LPCRITICAL_SECTION {aka _CRITICAL_
> SECTION*}' for argument '1' to 'void LeaveCriticalSection(LPCRITICAL_SECTION)'
>    ::LeaveCriticalSection(critical_section_);
>                                            ^
> F:/Downloads/googletest-release-1.8.0/googletest/src/gtest-port.cc: In member fu
> nction 'void testing::internal::Mutex::ThreadSafeLazyInit()':
> F:/Downloads/googletest-release-1.8.0/googletest/src/gtest-port.cc:292:27: error
> : cannot convert 'CRITICAL_SECTION* {aka _CRITICAL_SECTION*}' to '_RTL_CRITICAL_
> SECTION*' in assignment
>          critical_section_ = new CRITICAL_SECTION;
>                            ^
> F:/Downloads/googletest-release-1.8.0/googletest/src/gtest-port.cc:293:54: error
> : cannot convert '_RTL_CRITICAL_SECTION*' to 'LPCRITICAL_SECTION {aka _CRITICAL_
> SECTION*}' for argument '1' to 'void InitializeCriticalSection(LPCRITICAL_SECTIO
> N)'
>          ::InitializeCriticalSection(critical_section_);
>                                                       ^
> F:/Downloads/googletest-release-1.8.0/googletest/src/gtest-port.cc: In static me
> mber function 'static void testing::internal::ThreadLocalRegistryImpl::StartWatc
> herThreadFor(DWORD)':
> F:/Downloads/googletest-release-1.8.0/googletest/src/gtest-port.cc:495:21: error
> : '::OpenThread' has not been declared
>      HANDLE thread = ::OpenThread(SYNCHRONIZE | THREAD_QUERY_INFORMATION,
>                      ^
> googlemock\CMakeFiles\gmock_main.dir\build.make:62: recipe for target 'googlemoc
> k/CMakeFiles/gmock_main.dir/__/googletest/src/gtest-all.cc.obj' failed
> mingw32-make[2]: *** [googlemock/CMakeFiles/gmock_main.dir/__/googletest/src/gte
> st-all.cc.obj] Error 1
> CMakeFiles\Makefile2:88: recipe for target 'googlemock/CMakeFiles/gmock_main.dir
> /all' failed
> mingw32-make[1]: *** [googlemock/CMakeFiles/gmock_main.dir/all] Error 2
> Makefile:139: recipe for target 'all' failed
> mingw32-make: *** [all] Error 2
> 
> F:\Downloads\tools\gbuild>mingw32-make

**Comment by KindDragon** [comment]
Can you try with the latest commit from `master`?

**Comment by Yensan** [comment]
release-1.7.0 can build in Windows+codeblock+MinGW  in my way. And now I am walk around in gtest as a primer user  with `Win+MinGW+VScode`
but release-1.8.0 cannot,  latest commit from master cannot.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
