### ISSUE TITLE
Visual Studio 2017 don't run tests properly 

### ISSUE THREAD

**Issue by NukeBird** [google/googletest#1317]
Here is a my project: https://github.com/NukeBird/SP3D/tree/feature.gtest

Visual Studio's project generated by this command:
`cmake . -Bbuild -G"Visual Studio 15 2017 Win64" 
`

When I do Test -> Run -> All tests (Ctrl+R, A):

> [30.10.2017 22:23:39 Informational] ------ Load Playlist started ------
> [30.10.2017 22:23:39 Informational] ========== Load Playlist finished (0:00:00,0070172) ==========
> [30.10.2017 22:23:39 Informational] ------ Discover test started ------
> [30.10.2017 22:23:39 Warning] Test run will use DLL(s) built for framework Framework45 and platform X86. Following DLL(s) will not be part of run: 
> SP3Dd.lib, run_unit_tests.exe are built for Framework None and Platform X64.
>  Go to http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409 for more details on managing these settings.
> [30.10.2017 22:23:40 Informational] ========== Discover test finished: 0 found (0:00:01,0891675) ==========
> [30.10.2017 22:23:40 Informational] ------ Discover test started ------
> [30.10.2017 22:23:40 Warning] Test run will use DLL(s) built for framework Framework45 and platform X86. Following DLL(s) will not be part of run: 
> SP3Dd.lib, run_unit_tests.exe are built for Framework None and Platform X64.
>  Go to http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409 for more details on managing these settings.
> [30.10.2017 22:23:40 Informational] ========== Discover test finished: 0 found (0:00:00,0718118) ==========
> [30.10.2017 22:28:10 Informational] ------ Load Playlist started ------
> [30.10.2017 22:28:10 Informational] ========== Load Playlist finished (0:00:00) ==========
> [30.10.2017 22:28:11 Informational] ------ Discover test started ------
> [30.10.2017 22:28:11 Warning] Test run will use DLL(s) built for framework Framework45 and platform X86. Following DLL(s) will not be part of run: 
> SP3Dd.lib, run_unit_tests.exe are built for Framework None and Platform X64.
>  Go to http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409 for more details on managing these settings.
> [30.10.2017 22:28:11 Informational] ========== Discover test finished: 0 found (0:00:00,0713323) ==========
> [30.10.2017 22:29:01 Informational] ------ Discover test started ------
> [30.10.2017 22:29:01 Warning] Test run will use DLL(s) built for framework Framework45 and platform X86. Following DLL(s) will not be part of run: 
> run_unit_tests.exe is built for Framework None and Platform X64.
>  Go to http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409 for more details on managing these settings.
> [30.10.2017 22:29:01 Informational] ========== Discover test finished: 0 found (0:00:00,0798204) ==========

Visual Studio testing seems broken. What is going wrong? 

(program run_unit_tests by itself works fine. But I wanna integrate tests to Visual Studio)

**Comment by KindDragon** [comment]
You need to report this problem to Visual Studio https://developercommunity.visualstudio.com/spaces/8/index.html

**Comment by NukeBird** [comment]
I install https://marketplace.visualstudio.com/items?itemName=ChristianSoltenborn.GoogleTestAdapter

And everything now is OK! ^^
