### ISSUE TITLE
Building in Windows within folder path with spaces and VS2017 preview is broken

### ISSUE THREAD

**Issue by bryanzim** [google/googletest#1318]
Currently Windows builds will fail if they contain spaces and VS2017 will emit errors from the deprecation of tr1::tuple.  

Fixes for both these issues have been created and are in a pending pull request.  Can that request please be looked at?

**Comment by KindDragon** [comment]
> VS2017 will emit errors from the deprecation of tr1::tuple.

This is fixed in master

**Comment by bryanzim** [comment]
No it is not.  I should have been more explicit.  VS2017 will compile fine even though it is using tr1::tuple and not std::tuple and not emit an error. VS2017 Preview which is version 19.12.25816.0 will emit the following:

warning C4996: 'std::tr1': warning STL4002: The non-Standard std::tr1 namespace and TR1-only machinery are deprecated and will be REMOVED. You can define _SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING to acknowledge that you have received this warning. 

and fail to compile.  Also the path issues are not addressed either.

**Comment by bryanzim** [comment]
+1 to see if anyone will pick this up and review small pending pull request.

**Comment by bryanzim** [comment]
Posting again into this black hole forum to see if anything escapes.

**Comment by j-o** [comment]
+1 as a new update for VS2017 has been released two days ago that includes the the tr1::tuple deprecation, i.e., googletest doesn't compile with the current Visual Studio.
