### ISSUE TITLE
possible strncmp NULL dereference in SkipPrefix

### ISSUE THREAD

**Issue by hazelnusse** [google/googletest#1319]
Scan build is reporting a potential null pointer dereference here:
https://github.com/google/googletest/blob/master/googletest/src/gtest.cc#L5027

This might be a false positive, but given that the path length is 18, it isn't obvious to me.

[strncmp_null_dereference.tar.gz](https://github.com/google/googletest/files/1432345/strncmp_null_dereference.tar.gz)

**Comment by hazelnusse** [comment]
Hello?

**Comment by MichaelVincentHubbard** [comment]
Hi, I might try to look at the files in cygwin.

I'll look at it in the morning ummm, forgeting exactly ummm seems super
interesting or code for not code.

How are you?  I don't work for Google or anything.

Michael

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.
