### ISSUE TITLE
Using Times(n) With EXPECT_CALL Registers As Success When It Fails

### ISSUE THREAD

**Issue by nko12** [google/googletest#1325]
I have the following pieces of code.

IWindowSystem.h (in a library)
```
class DX2D_API IWindowSystem
{
public:
	virtual ~IWindowSystem() {}

	virtual void* CreateWindow(const DX2DHelper::Core::WindowOptions& winOptions) = 0;
	virtual bool ShowWindow() = 0;
	virtual bool ResizeWindow(const Primitives::Size<unsigned int>& newSize) = 0;
	virtual bool MinimizeWindow() = 0;
	virtual bool CloseWindow() = 0;
	virtual void DestroyWindow(void* winData) = 0;
};
```

GameWindowTests.cpp (in the testing executable)
```
class MockWindowSystem : public DX2DHelper::Detail::Core::IWindowSystem
{
public:
	MOCK_METHOD1(CreateWindow, void*(const DX2DHelper::Core::WindowOptions&));
	MOCK_METHOD0(ShowWindow, bool());
	MOCK_METHOD1(ResizeWindow, bool(const DX2DHelper::Primitives::Size<unsigned int>&));
	MOCK_METHOD0(MinimizeWindow, bool());
	MOCK_METHOD0(CloseWindow, bool());
	MOCK_METHOD1(DestroyWindow, void(void*));
};

...

TEST(GameWindowTests, WhenGameWindowInitializesItShouldPassSameWindowCreationPropertiesToWindowSystem)
{
	WindowOptions options;
	options.winWidth = 1080;
	options.winHeight = 720;
	options.winTitle = "DX2DHelper Test";

	MockWindowSystem winSystem;

	// The GameWindow should pass an option object with all the same properties to the window system.
	// It should only call CreateWindow a single time.
	EXPECT_CALL(winSystem, CreateWindow(options))
		.Times(1);

	GameWindow window(&winSystem);
	EXPECT_TRUE(window.InitializeWindow(options).IsSuccess());
}
```
GameWindow's InitializeWindow method does not call winSystem->CreateWindow() at all. When this test completes, it correctly prints the following error:
```
error: Actual function call count doesn't match EXPECT_CALL(winSystem, CreateWindow(options))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
```

however _it shows up as a success_.

```
[ RUN      ] GameWindowTests.WhenGameWindowInitializesItShouldPassSameWindowCreationPropertiesToWindowSystem
D:\DX2DHelper\DX2DHelperTests\Platform\Shared\GameWindowTests.cpp(61): error: Actual function call count doesn't match EXPECT_CALL(winSystem, CreateWindow(options))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
[       OK ] GameWindowTests.WhenGameWindowInitializesItShouldPassSameWindowCreationPropertiesToWindowSystem (1 ms)
```

From [this ](https://groups.google.com/forum/#!topic/googlemock/pa9nxuq0TZg)link, someone pointed out this can happen if you are using the mock instance as a static instance, or it's not being destructed by the time the test is destroyed. However, in my example, the mock instance is created and destroyed in the test, and I temporarily added a destructor to it to make sure it was being called when the test method finished executing.

Any ideas why this is happening? Extra info if applicable:

- Visual Studio 2017
- Windows 10 Fall Creators Update
- GoogleTest/GoogleMock Master Branch From 11/10/2017

**Comment by ArekPiekarz** [comment]
Try using a StrictMock.

**Comment by nko12** [comment]
I changed the following line of code to a StrictMock:
```cpp
StrictMock<MockWindowSystem> winSystem;
```
This yielded the expected behavior. The test properly failed.
```
[ RUN      ] GameWindowTests.GameWindowInitializationShouldFailIfWindowSystemFailsToCreateWindow
D:\DX2DHelper\DX2DHelperTests\Tests\Core\GameWindowTests.cpp(82): error: Value of: window.InitializeWindow(options).IsSuccess()
  Actual: true
Expected: false
D:\DX2DHelper\DX2DHelperTests\Tests\Core\GameWindowTests.cpp(77): error: Actual function call count doesn't match EXPECT_CALL(winSystem, CreateAppWindow(options))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
[  FAILED  ] GameWindowTests.GameWindowInitializationShouldFailIfWindowSystemFailsToCreateWindow (0 ms)
```

The strange thing is, I changed it back, and the test (correctly) continues to fail.  Nothing surrounding that code has really changed, so I don't know why I can't reproduce this issue anymore. I'll just try to keep an eye on it.

**Comment by nko12** [comment]
@ArekPiekarz The issue appears to have sprung up again.

The following failing test (I also added a strict mock to it this time)
```cpp
TEST(GraphicsContextTests, InitializeShouldCallGraphicsSystemInitializeMethod)
{
	StrictMock<MockGraphicsSystem> system;

	// Initializing the graphics context should call the initialize method of the graphics system
	// one time.
	EXPECT_CALL(system, InitializeGraphics(_))
		.Times(1);

	GraphicsContext context(&system);
	context.InitializeGraphicsBackend(GraphicsInitOptions());
}
```
yields the following Google Test output.
```
[----------] 1 test from GraphicsContextTests
[ RUN      ] GraphicsContextTests.InitializeShouldCallGraphicsSystemInitializeMethod
D:\DX2DHelper\DX2DHelperTests\src\Core\GraphicsContextTests.cpp(22): error: Actual function call count doesn't match EXPECT_CALL(system, InitializeGraphics(_))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
[       OK ] GraphicsContextTests.InitializeShouldCallGraphicsSystemInitializeMethod (1 ms)
[----------] 1 test from GraphicsContextTests (2 ms total)
```

Any ideas?

**Comment by ArekPiekarz** [comment]
@nko12 Sorry, I didn't notice your comment until now. Is it still a problem? If yes,  it would help if you provided a minimal compilable example, so that people could test it on their systems.

**Comment by nko12** [comment]
I haven't noticed the problem again, but I'll let you know if it ever appears to show up again.

**Comment by Aleksandrius** [comment]
I had the same problem. It was solved by specifying another GTest library for linking. I use CMake for compilation, and if I link the test application to `libgtest` or `GTest::GTest`, then a failed EXCEPT_CALL will not mark the test as failed. Linking to `gtest_main` will work as expected.

I used a library from msys -> mingw-w64-x86_64-gtest 1.8.0-1. Compiler is mingw64.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by ysxiao** [comment]
This happened to us on and off but never really figured out until now. The root cause: make sure you don't link to both gmock.lib and gtest.lib! gmock.lib has all the gtest bits built in, so you really only need to link to gmock.lib. No idea why the linker didn't complain about duplicate symbols when I linked to both, and then more bizarrely,  ::testing::InitGoogleMock somehow mysteriously became a no-op! I only figured that one out when I saw the warning "you didn't call ::testing::InitGoogleTest before call RUN_ALL_TESTS blah blah", but I did call  ::testing::InitGoogleMock, which should in turn call  ::testing::InitGoogleTest, right?!

**Comment by ZhenyaKh** [comment]
> This happened to us on and off but never really figured out until now. The root cause: make sure you don't link to both gmock.lib and gtest.lib! gmock.lib has all the gtest bits built in, so you really only need to link to gmock.lib. No idea why the linker didn't complain about duplicate symbols when I linked to both, and then more bizarrely, ::testing::InitGoogleMock somehow mysteriously became a no-op! I only figured that one out when I saw the warning "you didn't call ::testing::InitGoogleTest before call RUN_ALL_TESTS blah blah", but I did call ::testing::InitGoogleMock, which should in turn call ::testing::InitGoogleTest, right?!

Thank you so much!
