### ISSUE TITLE
Some question in using gtest on Unreal All Platform

### ISSUE THREAD

**Issue by kaichd** [google/googletest#1328]
hello,
i want to use the gtest on Unreal Engine (4.18)
in PC/MacOS, it works fine ,but in Android, it is not work.

## use-method
1. gtest build as dynamic library, the build macro(GTEST_CREATE_SHARED_LIBRARY=1,GTEST_HAS_POSIX_RE=0) pass to ndk-build
2. unreal build macro is GTEST_HAS_POSIX_RE=0, and link the gtest dynamic library(.so)
3. the call func is 
```c++
int foo(int a, int b)
{
    UE_LOG(LogGCloud, Log, TEXT("GTEST a = %d"), a);
    UE_LOG(LogGCloud, Log, TEXT("GTEST b = %d"), b);
    return a+b;
}

TEST(footest, footest1)
{
    EXPECT_EQ(10, foo(2,8));
    EXPECT_EQ(10, foo(3,6));
}
void *pthread_func(void* args)
{
    int argc = 3;
    char argv1[] = "test.exe";
#if PLATFORM_WINDOWS
    char argv2[] = "--gtest_output=xml:d:/zzztestMSDK.xml";
#elif PLATFORM_MAC
    char argv2[] = "--gtest_output=xml:/Users/Downloads/zzztestMSDK.xml";
#elif PLATFORM_IOS
    char argv2[] = "--gtest_output=xml";
#elif PLATFORM_ANDROID
    char argv2[] = "--gtest_output=xml:/sdcard/zzztestMSDK.xml";
#endif
    char argv3[] = "--gtest_filter=*.*";
    UE_LOG(LogTemp, Log, TEXT("gtest - 2"));
    char *argv[] = {argv1, argv2, argv3};
    UE_LOG(LogTemp, Log, TEXT("gtest  - 3"));
    testing::InitGoogleTest(&argc, argv);
    UE_LOG(LogTemp, Log, TEXT("gtest  - 4"));
    int ret = RUN_ALL_TESTS();
    UE_LOG(LogTemp, Log, TEXT("gtest  end : ret = %d"), ret);
    return ((void *)0);
}
void UMyUserWidget::OnClicked()
{
	UE_LOG(LogTemp, Log, TEXT("gtest - 0"));
        int err;
        err = pthread_create(&main_tid, NULL, pthread_func, NULL); //创建线程
        UE_LOG(LogTemp, Log, TEXT("gtest - 1"));
```

## questions
the question is like that, when the EXPECT_EQ failed, the gtest is not work, the log print "0,1,2,3,4", but not print the "end".

i try to make the testcase EXPECT_EQ ALL pass, the gtest is work fine, print the "end" at all, and the xml output is fine.

pls help me, thx

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
