### ISSUE TITLE
GoogleTest is modifying my CMake based environment

### ISSUE THREAD

**Issue by Zingam** [google/googletest#1334]
Why does adding Google Test modify my environment.

For example after I added it to my CMake project I get:
warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc

CMAKE_DEBUG_POSTFIX  is also set to "d"

**Comment by dneto0** [comment]
Seems similar to #1268

**Comment by dneto0** [comment]
Hey @Zingam, MR #1481 avoids modifying CMAKE_DEBUG_POSTFIX.   Is that enough to fix your problem?
