### ISSUE TITLE
When will there be a new release?

### ISSUE THREAD

**Issue by dapirian** [google/googletest#1342]
The last release (1.8) is 1.5yrs old, is a new one coming soon? We could use it, there are some bug fixes we'd like to be using :) Plus the last release is old enough to not even include the bazel build files

**Comment by ninjaCoder** [comment]
+1 for that !!!

**Comment by bjornfor** [comment]
Duplicate: https://github.com/google/googletest/issues/1079

**Comment by gennadiycivil** [comment]
https://github.com/google/googletest/releases/tag/release-1.8.1
