### ISSUE TITLE
Test organization and static linking 

### ISSUE THREAD

**Issue by lordofinsomnia** [google/googletest#1344]
I have main project foo and it's dependent subproject bar. I am using Google tests for testing. Both of them have their own tests. TestFoo  executable and TestBar executible.
When I execute tests for foo(TestFoo) I want to test and it's dependent subproject bar(via TestBar).

I tried to create TestFoo.lib (static library) and TestFoo executable links it.  I did same thing for TestBar.

But there is a catch. When I execute TestFoo or TestBar. Google test does not find any tests. 

There is a [important note for Visual c users][1], but this problem also affects gcc and clang. I have tried a workaround suggested in link, but it does not work in either msvc, gcc or clang.

Is there any good practice or some workarounds? 

Thanks. 

  [1]: https://github.com/google/googletest/blob/master/googletest/docs/Primer.md#important-note-for-visual-c-users

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by detly** [comment]
Is this limitation documented anywhere?
