### ISSUE TITLE
CHECK_NEAR accepts meaninglessly small epsilon values

### ISSUE THREAD

**Issue by randomascii** [google/googletest#1350]
Chromium bug crbug.com/786046 was a logic bug in a test. This logic bug sat unnoticed for two years until subtle timing changes turned it into an occasionally flaky test. The problem is that EXPECT_NEAR was being passed an epsilon value of 1.0 when the doubles that were passed in were so huge that adjacent doubles were 512.0 apart. Thus, the epsilon value was pointless and EXPECT_NEAR was silently converted to EXPECT_EQUAL.

It is straightforward for EXPECT_NEAR (actually DoubleNearPredFormat) to detect the smallest practical epsilon value given the input values and then fail if abs_error is smaller than that. With this change the flaky test mentioned in crbug.com/786046 becomes this 100% reliable failure:

../../base/time/time_win_unittest.cc(292): error: The epsilon used to compare expected_microseconds_since_origin and converted_microseconds_since_origin is less than the minimum epsilon in this range, which is 512, where
expected_microseconds_since_origin evaluates to 3.640989196237484e+18,
converted_microseconds_since_origin evaluates to 3.640989196237484e+18, and
1.0 evaluates to 1.
ticks=9223372036854775807, to be converted via logic path: SAFE

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by randomascii** [comment]
Note that this issue was ultimately fixed - using a slightly different technique than originally planned - with this recent commit:

https://github.com/google/googletest/commit/b5687db554a295e697f5d459cf6d3f343d2ca179
