### ISSUE TITLE
Travis CI broken

### ISSUE THREAD

**Issue by stefanosoffia** [google/googletest#1351]
I suspect there is some issue with the googletest Travis CI setup, as of 2017/12/8.
I observe that on pull request #1338 the two OSX+GCC builds fail with:
```
${CXX} --version
ccache: error: Could not find compiler "g++-4.9" in PATH
The command "${CXX} --version" failed and exited with 1 during .
```
There are other pull requests, e.g. #1103, which seem to suffer from the same issue.

**Comment by gennadiycivil** [comment]
This should be fixed by https://github.com/google/googletest/pull/1345

**Comment by stefanosoffia** [comment]
Confirmed.
