### ISSUE TITLE
Combine no longer available in Visual Studio 2017

### ISSUE THREAD

**Issue by BigSeb** [google/googletest#1352]
By removing the C4996 mentionned in the pull request #1348 which solved the tr1::tuple deprecated warning, Combine is no longer available. This is due to the following line in gtest-port.h:
```c++
// Determines whether to support Combine(). This only makes sense when
// value-parameterized tests are enabled.  The implementation doesn't
// work on Sun Studio since it doesn't understand templated conversion
// operators.
#if GTEST_HAS_PARAM_TEST && GTEST_HAS_TR1_TUPLE && !defined(__SUNPRO_CC)
# define GTEST_HAS_COMBINE 1
#endif
```
Because GTEST_HAS_TR1_TUPLE is not activated, GTEST_HAS_COMBINE is not set, disabling testing::Combine even though is was working fine in Visual Studio 2017 before.

**Comment by reid-p** [comment]
gtest-port.h should probably have this:

```
#if GTEST_HAS_PARAM_TEST && (GTEST_HAS_STD_TUPLE_ || GTEST_HAS_TR1_TUPLE) && !defined(__SUNPRO_CC)
# define GTEST_HAS_COMBINE 1
#endif
```

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by tlemo** [comment]
This bug is affecting cross-platform code (it seems that people still need to workaround this).

The fix should be simple (as suggested by reid-p@), so why not just fix it?

**Comment by sbenzaquen** [comment]
On Thu, Dec 27, 2018 at 6:30 PM Leonard Mosescu <notifications@github.com>
wrote:

> This bug is affecting cross-platform code (it seems that people still need
> to workaround this).
>
> The fix should be simple (as suggested by reid-p@), so why not just fix
> it?
>
Is this still a problem?
GET_HAS_COMBINE is no longer a thing as it is unconditionally supported now
with C++11.

**Comment by tlemo** [comment]
Nevermind, I was looking at an older snapshot. I can confirm that it's not longer an issue, thanks!
