### ISSUE TITLE
gmock_verbose and other command line options help

### ISSUE THREAD

**Issue by uecasm** [google/googletest#1356]
The FAQ and Cookbook for GMock suggest using the `--gmock_verbose=info` command line option at times.

First: this option is not included in the `--help` output (nor are any other options, if such exist).  It would be nice if this were added, and perhaps also a `--gmock_help` option for some more general information if there are several options.

Second: this option is silently ignored if the user links `gtest_main` instead of `gmock_main`.  It would be nice if this could be detected and reported somehow; perhaps raise an error if someone tries to use mocks without having called `InitGoogleMock` (which is presumably the reason why the parameter is not checked).

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.
