### ISSUE TITLE
C++11 

### ISSUE THREAD

**Issue by gennadiycivil** [google/googletest#1366]
An update from googletest team: it's decided starting from version 1.9.0 googletest will require C++11 to compile. A 1.8.1 branch will be created for pre-C++11 compilers but only critical bug fixes will be accepted in the branch.

In addition starting with 1.9.0 version googletest will be following Abseil compatibility  policies outlined [HERE](https://abseil.io/about/compatibility).

Thank you

**Comment by ninjaCoder** [comment]
Great news, when 1.9.0 except to be released ?
