### ISSUE TITLE
Add a possibility to parametrize test by type and value at the same time

### ISSUE THREAD

**Issue by akrzemi1** [google/googletest#1380]
Let me first present my problem, and then the feature request. I have a function template `inspect`:
```c++
template <typename T>
bool inspect(T const& v);
```
I want to test if it returns `true` for the following values:

* `1` (type `int`)
* `10` (type `int`)
* `1.0` (type `double`)
* `"Y"` (type `const char *`)

Basically, different values of different types, but sometimes different values have the same type. I would like to write one test or "test template" with the following contents:

```c++
EXPECT_TRUE(inspect(GetParam()));
```

And then somehow "instantiate" it with `{1, 10, 1.0, "Y"}`.

Is there a way to do it in the current framework?

I know I can emulate it:

```c++
struct int_1 {
  static int GetParam() { return 1; }
};
struct int_10 {
  static int GetParam() { return 10; }
};
struct double_1 {
  static double GetParam() { return 1.0; }
};
struct cstr_Y {
  static const char * GetParam() { return "Y"; }
};

using AKTypes = ::testing::Types<int_1, int_10, double_1, cstr_Y>;

template <typename T> struct AKTestCase : ::testing::Test {};
TYPED_TEST_CASE (AKTestCase, AKTypes);

TYPED_TEST (AKTestCase, test_1)
{
  EXPECT_TRUE (inspect(TypeParam::GetParam()));
}
```

Also, it is possible to infer the list of types from a heterogenous collection of values:

```c++
template <typename... T>
::testing::Types<T...> Values(T&&... values);

using AKTypes = decltype(Values(1, 10, 1.0, "Y"));
```

So, it seems such addition should be implementable?

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by puetzk** [comment]
Just hit a case where I vaguely wanted this, so I'll leave a thought (even though it's a closed issue). Seems like parameterize over a std::tuple would be a fairly natural way to express this; it would just expand over the parameter pack as with std::index_sequence_for, std::get, and std::tuple_element.

That does seem like a tidy way to unify the expansion of a template test (ala TYPED_TEST) supplying `TypeParam` and a value-parameterized one supplying `GetParam()` into a `TYPED_TEST_P`/`INSTANTIATE_TYPED_TEST_SUITE_P` that unpacked a tuple and supplied both a type and avalue to each instantiation.

I don't have enough need to actually implement it, though.
