### ISSUE TITLE
Override printing when gtest catch user exceptions

### ISSUE THREAD

**Issue by maingoh** [google/googletest#1381]
Hi ! I would like to display some information when gtest catch my own exceptions (not just `e.what()`).

By looking at the code this is handled in `HandleExceptionsInMethodIfSupported()` but i don't know how to override this function to catch and print what I need.

What would be the best way to do this ?
Thank you,

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
