### ISSUE TITLE
<gtest/gtest.h> and <complex.h> incompatible

### ISSUE THREAD

**Issue by enh** [google/googletest#1391]
`<complex.h>` defines the macro `I`, which then causes trouble for code in <gtest/gtest-printers.h> like
```
  template <size_t I>
  struct tuple_element : ::std::tuple_element<I, Tuple> {};
```
We hit this in some Android libc tests: https://android-review.googlesource.com/#/c/platform/bionic/+/581376/2/tests/complex_test.cpp

**Comment by gennadiycivil** [comment]
I am no sure what we can do in googletest to protect against this. I think this would be a clent's code responsiblity

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
