### ISSUE TITLE
Compilation error when iterator of a map is used as function argument

### ISSUE THREAD

**Issue by RaveenReddy** [google/googletest#1392]
Hello,

When any function has an iterator of a map as an argument i am seeing compilation error "::iterator' has no member named 'begin" and "::iterator' has no member named 'end'"

Below example code is not compiling
typedef std::map<int, int> SAMPLE_MAP;
    virtual void func(SAMPLE_MAP::iterator &it) const = 0;
  MOCK_CONST_METHOD1(func,
      void(SAMPLE_MAP::iterator &it));

I am using GCC compiler 4.3.3 for VxWorks on Intel platform.

Workaround was use const_iterator instead of iterator.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
