### ISSUE TITLE
Non-pointer conversion error with Intel ICC 18.0

### ISSUE THREAD

**Issue by dwtowner** [google/googletest#1406]
With Intel Compiler 18.0 patch 0, I get the following issues.

[snip]googletest\googletest\src/gtest.cc(2904): error #2259: non-pointer conversion from "int" to "const WORD={unsigned short}" may lose significant bits
    const WORD existing_bg = old_color_attrs & background_mask;
                             ^
[snip]googletest\googletest\src/gtest.cc(2906): error #2259: non-pointer conversion from "int" to "WORD={unsigned short}" may lose significant bits
    WORD new_color = GetColorAttribute(color) | existing_bg | FOREGROUND_INTENSITY;
                     ^

[snip]googletest\googlemock\include\gmock/gmock-matchers.h(3273): error #2259: non-pointer conversion from "int" to "char" may lose significant bits
      matched_[SpaceIndex(ilhs, irhs)] = b ? 1 : 0;

Explicitly casting the LHS before assignment can work around this.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. Unfortunately there appears to be no actionable information.
