### ISSUE TITLE
TYPED_TEST incorrectly fetching test name

### ISSUE THREAD

**Issue by ghost** [google/googletest#1408]
![image](https://user-images.githubusercontent.com/19455261/35068439-e83fd8ac-fb8b-11e7-91ac-1d1c3a2f9e6c.png)

When using a `#define` in the `CaseName` parameter, the literal macro name is used instead of expanding it.  This does not occur with TEST_F.

**NOTE:**
TEST_F uses `::testing::internal::GetTypeId<test_fixture>()`, which I suppose is what is expanding the macro.

**EDIT**: Picture isn't working, uploaded here: https://imgur.com/a/K4OWJ

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
