### ISSUE TITLE
dnl @license GPLWithACException

### ISSUE THREAD

**Issue by luisapace** [google/googletest#1414]
Hi, in the module _**https://github.com/google/googletest/blob/master/googletest/m4/acx_pthread.m4**_ I see written in the code:

**_dnl @license GPLWithACException_**

What does it mean? what code is under GPL ? and what does it mean GPLWithACException?

Thanks.

**Comment by offa** [comment]
It means **GPLv3 with Autoconf Exception**:

- [GPLv3 with Autoconf exception](https://spdx.org/licenses/GPL-3.0-with-autoconf-exception.html)
- [GPLv2 with Autoconf exception](https://spdx.org/licenses/GPL-2.0-with-autoconf-exception.html)

**Comment by luisapace** [comment]
Does it mean that acx_pthread.m4 is under GPLv3 with Autoconf exception?

Thanks.

**Comment by offa** [comment]
I think so. However, I'm neither a lawyer nor a license expert.

**Comment by luisapace** [comment]
Me neither... but "dnl @license GPLWithACException" is a comment in the code... so knowing its meaning should be a technical question, isn't it? Thanks anyway for your answer and your time.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
