### ISSUE TITLE
Name macros variables (expected,actual) instead of (val1,val2)

### ISSUE THREAD

**Issue by arteniioleg** [google/googletest#1416]
At the moment you can't differentiate them

https://github.com/google/googletest/blob/83fa0cb17dad47a1d905526dcdddb5b96ed189d2/googletest/include/gtest/gtest.h#L1957

This is actually useful in error messages.

We have this code `ASSERT_EQ(reply, nullptr);` and it generates this error message:

```
Failure
Value of: nullptr
  Actual: 8-byte object <00-00 00-00 00-00 00-00>
Expected: reply
Which is: 8-byte object <C0-08 00-24 9D-7F 00-00>
```

As you can see it's confusing: `nullptr` is expected to be `reply`.
Correct is `ASSERT_EQ(nullptr, reply);`: `reply` is expected to be `nullptr`.

```
Failure
Value of: reply
  Actual: 8-byte object <C0-08 00-24 9D-7F 00-00>
Expected: nullptr
Which is: 8-byte object <00-00 00-00 00-00 00-00>
```

So the macros should be

```cpp
#define ASSERT_EQ(expected, actual)
```

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.
