### ISSUE TITLE
prefer clock_gettime and CLOCK_MONOTONIC to gettimeofday

### ISSUE THREAD

**Issue by skotchandsoda** [google/googletest#1424]
I saw #1199 but std::chrono is inapplicable for C++98.

A more broadly available improvement would be to use clock_gettime() with the CLOCK_MONOTONIC clock on platforms where it is available. This ensures that an elapsed time cannot be negative, which seems to be the primary issue with using gettimeofday() for interval measurement.

**Comment by bryanzim** [comment]
There is a pull request #1370 with these desired features but there seems to be no interest in merging it in.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
