### ISSUE TITLE
To try samples immediately, it would be better to add description in the top README.md

### ISSUE THREAD

**Issue by tomoyuki-nakabayashi** [google/googletest#1431]
When a user starts googletest, he/she will try samples (googletest/googletest/samples) at first to understand it.
The top README has the following sentence, but doesn't refer how to try samples.
 
> More detailed documentation for googletest (including build instructions) are in its interior googletest/README.md file.

I finally found googletest/README.md includes how to build and try samples.
I feel it's kind if the information is written in the top README.md.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
