### ISSUE TITLE
gmock how implement" CStringArray & " as  returned argument 

### ISSUE THREAD

**Issue by windsorzj** [google/googletest#1436]
void fuction(CStringArray &astrDemo) as the func protype.
how using gmock return such parameter ?
```

CStringArray strArray;
i use SetArgReferee<0>(strArray)  hoping to return this para.
but the error was ""error C2248: 'CObject::CObject' : cannot access private member declared in class 'CObject' [duplicate]"
```
so  some help appreciated.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. Unfortunately there appears to be no actionable information.
