### ISSUE TITLE
Variable 'prefix' not defined in gtest.pc

### ISSUE THREAD

**Issue by Begasus** [google/googletest#1438]
Trying to update the build for Haiku platform, but checking the pkgconfig files fail because of missing prefix variable
adding: prefix=@CMAKE_INSTALL_FULL_BINDIR@ seems to work, but I'm not sure if it's the correct way to do it? any suggestions?

**Comment by gennadiycivil** [comment]
looks like it is addressed

**Comment by Begasus** [comment]
Thanks for taking the time to look into it :+1:
