### ISSUE TITLE
sonarcloud reports bugs on unnamed namespaces

### ISSUE THREAD

**Issue by uglyoldbob** [google/googletest#1447]
I included googletest on a repository of mine and noticed that sonarcloud flagged some googletest code as having bugs.

![image](https://user-images.githubusercontent.com/921714/36029512-76647e8e-0d71-11e8-86ad-f868f9011069.png)

I initially thought it was invalid because the unnamed namespaces are not in header files.
However, it was brought to my attention that the source files are being introduced with "#include" causing them to be treated like headers.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
