### ISSUE TITLE
GCC 7 with Wconversion enabled adds warnings about MatcherList to projects using GMock

### ISSUE THREAD

**Issue by stevecotton** [google/googletest#1465]
When using GMock in a project that uses -Wconversion, and building with GCC 7.3.0, several instances of this warning are reported:

    gtest/googlemock/include/gmock/gmock-matchers.h:1622:29: warning: conversion to ‘int’ from ‘long unsigned int’ may alter its value [-Wconversion]
       typedef MatcherList<sizeof...(Args), Args...> MatcherListType;

This can be reproduced when building GTest itself, by adding `-DCMAKE_CXX_FLAGS=-Wconversion` to the build options. The cause seems to be MatcherList's template using `int kSize`, instead of `std::size_t kSize`. I think it's a one-line fix, but I'm not intending to open a PR for fixing it myself, because I think the effort of carefully understanding the CLAs would be disproportionate to the size of the patch.

$ git rev-parse HEAD

    3f0cf6b62ad1eb50d8736538363d3580dd640c3e

$ gcc --version

    gcc (Debian 7.3.0-3) 7.3.0
    Copyright (C) 2017 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ cmake -Dgtest_build_tests=ON -DCMAKE_CXX_FLAGS=-Wconversion ${GTEST_DIR}

    -- The C compiler identification is GNU 7.3.0
    -- The CXX compiler identification is GNU 7.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /usr/bin/python (found version "2.7.14") 
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Check if compiler accepts -pthread
    -- Check if compiler accepts -pthread - yes
    -- Found Threads: TRUE  
    -- Configuring done
    -- Generating done
    -- Build files have been written to: mybuild

mybuild$ make -k

    Scanning dependencies of target gtest
    [  1%] Building CXX object googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
    [  2%] Linking CXX static library libgtest.a
    [  2%] Built target gtest
    Scanning dependencies of target gmock
    [  2%] Building CXX object googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
    In file included from googletest/googlemock/include/gmock/gmock-spec-builders.h:70:0,
                     from googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:43,
                     from googletest/googlemock/include/gmock/gmock.h:61,
                     from googletest/googlemock/src/gmock-all.cc:40:
    googletest/googlemock/include/gmock/gmock-matchers.h:1622:29: error: conversion to ‘int’ from ‘long unsigned int’ may alter its value [-Werror=conversion]
       typedef MatcherList<sizeof...(Args), Args...> MatcherListType;
                                 ^~~
    cc1plus: all warnings being treated as errors

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
