### ISSUE TITLE
Build fails if Clone(2) not available

### ISSUE THREAD

**Issue by Riounis** [google/googletest#1468]
If Clone(2) is not available, such as when using Cygwin, the functions StackLowerThanAddress and StackGrowsDown in gtest-death-test.cc are unused, and cause compilation errors because the flag to turn warnings into errors is turned on.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
