### ISSUE TITLE
Slow compilation time

### ISSUE THREAD

**Issue by jpan127** [google/googletest#1478]
Hi, I have been doing a trial run with googletest and have liked it a lot, but I noticed my compile times are very very slow.  This is coming from a C project with C unit testing, so I was guessing there would be some slower compilation but the difference is drastic.

For example compiling just one test file gives me `~6+ seconds` for a test fixture, a mock class, and 3 short tests with 8 expect_calls.

I have seen around that putting the classes into their own headers can speed things up, but I poked around some more and commented everything out except `#include <gtest/gtest.h>`.

This took a `little under 3 seconds` to compile.  Am I doing something wrong, or is there anything I can do to speed this up?  Compiling ~100 tests, most likely much longer than the current test, can net ~1000 seconds.

For reference, I am running googletest v1.7.0, g++ 4.8.5, Ubuntu 4.8.5, on a work desktop with double Intel Xeon E5-2660 v3, 64GB ram, and Samsung 850 EVO SSD.

Thanks!

**Comment by gennadiycivil** [comment]
Thank you very much for this report. Unfortunately there appears to be no actionable information.

**Comment by pnstickne** [comment]
Isn’t the action “profile and fix performance”?

**Comment by sopgenorth** [comment]
Will the many reports of slow compilation time ever get any attention?

**Comment by pparkerspam** [comment]
I agree with all of the above comments about this being ignored.  My particular issue is that because I'm debugging some CMake problems, I have to build googletest from clean every iteration, resulting in a **23 second compile time** on an i9.  Neither parallel make nor ccache help a bit.

**Comment by are-scenic** [comment]
> I agree with all of the above comments about this being ignored. My particular issue is that because I'm debugging some CMake problems, I have to build googletest from clean every iteration, resulting in a 19 second compile time on a 64GB RAM i7. Parallel make didn't make a bit of difference; watching top it appears there are 2 or 3 large files that take on the order of 10 seconds each to compile.
> 
> I did find the following, although sadly it doesn't really apply to me: https://github.com/google/googletest/blob/main/docs/gmock_cook_book.md#making-the-compilation-faster
> 
> I eventually fixed my particular problem by using ccache. It took a little while to get it working, but once it was working clean builds went down to 1 second from 19.

@pparkerspam, thank you for your comment about the gmock-cook-book. It's a pity it didn't help you. However, you mentioning this here helped my and I believe many other developers who found themselves struggling with the same problem and who came across this ticket. I think you deserve to know that your knowledge sharing helped other people in the community.
Thank you.
