### ISSUE TITLE
Implement an antonym to EXPECT_DEATH (i.e. EXPECT_NO_DEATH)

### ISSUE THREAD

**Issue by DigitalInBlue** [google/googletest#1484]
There are some tests which may `abort` or `assert` if something goes wrong.  Inline with `EXPECT_NO_THROW`, I would like an `EXPECT_NO_DEATH`.  I have implemented a quick and dirty version [here.](https://gist.github.com/DigitalInBlue/e9f143a8d1f6a6670995ff9fcaef9721)  

The code I posted does not emit good messages, but should serve to show that it is fairly trivial to implement with little impact on the underlying framework.

I have been using this in my tests and it is a very helpful addition to Google Test.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
