### ISSUE TITLE
API for listing test names

### ISSUE THREAD

**Issue by paleozogt** [google/googletest#1494]
Presently there isn't a way to programmatically get the test names.  Everything has to be done via the CLI argv interface.

Ideally gtest would have an API on `::testing::UnitTest`, for example:
```
std::vector<std::string> getTestNames() const;
```

**Comment by djwaffle2005** [comment]
ok man

**Comment by Bu11etmagnet** [comment]
Why just the names? 
Perhaps it would be better to get a list of tests, which can be queried for their names.

**Comment by paleozogt** [comment]
I asked for just the test names because I figured that would be easier to implement.

Getting a list of the actual test objects would be great.  In fact, that would let us run the tests directly (instead of having to go through `RUN_ALL_TESTS`).

**Comment by gennadiycivil** [comment]
@paleozogt  Would https://github.com/google/googletest/pull/1658 be helpful?

**Comment by paleozogt** [comment]
I don't think so-- tho thanks for asking.

What I'm after is a C++ API to call to get the test list, while #1658 seems to be another CLI argument.  (Tho its pretty neat in what its trying to solve.)

**Comment by asoffer** [comment]
This isn't particularly difficult to implement provided you access them after main() begins, but... could you explain what you're trying to do here? What do you want the test names for?

**Comment by paleozogt** [comment]
I have a C++ library and suite of GTests for it.  I want to package the library and tests into `.so`'s that can be loaded by an Android/iOS app.  The app would show the list of tests names, and then the user could tap on the test they want to run.  Or they could type in wildcards for running multiple tests.  Its sort of like an app version of the cli runner.

The ability to do this is *almost* there in GTest, but the code is highly coupled to the idea that its running from a command-line tool.

**Comment by CJ-Johnson** [comment]
Hello  @paleozogt ! Unfortunately this is not something we are able to prioritize. That said, we would consider looking at a PR. Is that something you are able to create?
