### ISSUE TITLE
Installing Google Test For Linux (Minor)

### ISSUE THREAD

**Issue by pcsnow** [google/googletest#1511]
github does not use tar. 
CLONE button only provides .zip format

s/gtest-1.5.0.tar.gz/googletest-master.zip

s/gtest-version/googltest-master/

s/goolge/google/
s/reach de/reach the/
s/nedd/need/
s/ho/go/

# I em TER-bil spellzer tooo! Cheers

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
