### ISSUE TITLE
In googlemock, WillSeveral(?) suggestion.

### ISSUE THREAD

**Issue by taeguk** [google/googletest#1514]
In current, there are only ```WillOnce()``` and ```WillRepeatedly()```. There is no feature about registering same expectations for several times.
How about adding the feature which is tentatively named "```WillSeveral()```"?

**Comment by taeguk** [comment]
@rburny 
With the way you suggest, I can't register several different expectations.
In current, the only way is
```c++
auto expectation = EXPECT_CALL(...);
for (int i = 0; i < TheCountOfA; ++i)
    expectation = expectation.WillOnce(A);
for (int i = 0; i < TheCountOfB; ++i)
    expectation = expectation.WillOnce(B);
...
```

**Comment by rburny** [comment]
Ah, I see. Then using `RetiresOnSaturation()` might help; it will cause the whole expectation to be removed after it matches the specified number of calls (admittedly, it's fairly confusing).

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
