### ISSUE TITLE
Support use case with manual unloading of DLLs on Windows

### ISSUE THREAD

**Issue by andreybokhanko** [google/googletest#1516]
Hi All,

There was a question on this back in 2010 (https://groups.google.com/forum/#!topic/googletestframework/A9UXUrbKMD8) and an answer (from Vlad Losev) that this use case is not supported.

Basically, the use case is manual unloading of DLLs on Windows before program exit, like this (an example is from the mail thread linked above):

```
  int main(int argc, char* argv[]) 
  { 
    HMODULE hDLL = ::LoadLibrary("MyDLL.dll"); 

    ::testing::InitGoogleTest(&argc, argv); 
    int nResult = RUN_ALL_TESTS(); 
    ::FreeLibrary(hDLL); 

    return nResult; 
  } 

```
Here is what Vlad replied:

> gtest doesn't support this use case. The tests themselves some objects during their initialization, and those objects are cleaned up by gtest during the program shutdown. If the code that performs the clean-up is already unloaded from memory by that time, the program will crash. Unless you want to modify Google Test's code to suppress that clean-up, your only option is to keep those DLLs loaded until the program terminates.

We faced with a similar issue, as we unload DLLs manually, and I believe this is quite a common use case on Windows. The solution we employed is adding the following to gtest.h:

```
inline void CLEAN_TESTS() {
  ::testing::UnitTest::GetInstance()->Clean();
}

```
and the following to gtest.cc:

```
void UnitTest::Clean() {
  delete impl_;
  impl_ = new internal::UnitTestImpl(this);
}

```
I wonder if the community considers this code to be acceptable for inclusion into Google Test? I can open a pull request with an actual patch, but first want to make sure that this approach is considered to be reasonable.

Yours,
Andrey
===
Architect,
Align Technology

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
