### ISSUE TITLE
gtest report to show  source files(.c) and function names in report

### ISSUE THREAD

**Issue by srinivas-github** [google/googletest#1530]
We are working on a customized report generation, where we need to get the source files and functions that are mapped to testcases/testsuite.
Is there any way to generate report (XML) file which includes  source file names( .c) and function names in report?
Any help will be highly appreciated.

thanks,
Srini

**Comment by gennadiycivil** [comment]
I think https://github.com/google/googletest/pull/1658 comes very close to this
