### ISSUE TITLE
Segfault on libcurl simple test

### ISSUE THREAD

**Issue by maym86** [google/googletest#1535]
I get a segfault in gtest that I don't get when I just run the code normally in main. I would appreciate some feedback if I am doing something wrong with gtest? It is a very basic example for curl so I would expect it to work.

The test:

```
TEST(HTTPTest, Passes) {
    const std::string url= "https://www.google.com/";
    std::string kml_result = loadURL(url);
    EXPECT_FALSE(kml_result.empty());
}

```
The code:

```
#include "http.h"
#include <curl/curl.h>
#include <glog/logging.h>

size_t writeFunction(void *ptr, size_t size, size_t nmemb, std::string *data) {
    data->append(reinterpret_cast< char* >(ptr), size * nmemb);
    return size * nmemb;
}

std::string loadURL(const std::string &url) {
    auto curl = curl_easy_init();
    std::string response_str;

    if (curl) {
        curl_easy_setopt(curl, CURLOPT_URL, url.c_str());

        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, writeFunction);
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response_str);
        curl_easy_setopt(curl, CURLOPT_VERBOSE, 1);

        auto res = curl_easy_perform(curl);

        if (res != CURLE_OK) {
            LOG(ERROR) << curl_easy_strerror(res);
        }

        curl_easy_cleanup(curl);
    }

    return response_str;
}

```

I get a segfault on the following line but only when running with gtest.       
` auto res = curl_easy_perform(curl);`

Signal: SIGSEGV (Segmentation fault)

Any idea why I would see this with gtest and not in main?

Versions:
gtest: 1.8.0
libcurl: 7.47.0
Ubuntu 16.04

**Comment by gennadiycivil** [comment]
Thank you very much for this report. Unfortunately there appears to be no actionable information.

**Comment by maym86** [comment]
"no actionable information" care to elaborate on what information you need to make it actionable?
