### ISSUE TITLE
We miss an Accepted Error concept in Google Test

### ISSUE THREAD

**Issue by strattist** [google/googletest#1536]
I believe we miss an **Accepted Error** concept in the *Google Test framework*. I am implementing a C / C++ library and I think other languages might not have the same problematic than me but it would be great to have an **Accepted Error** related macro that could saved in the output file for the test what was the **Accepted Error**. 

Something that will just describe the accepted approximations (sometimes 1e-4 if a mathematical function is approximated, sometimes 1 due to rounding differences, sometimes maybe more).

I am using `TestWithParam` for that at the moment but it seems a bit overkill and it's not exactly the same concept to me. 

Could it be considered as an addition for the future?

**Comment by gennadiycivil** [comment]
Apologies for the long wait. Could you please provide more information, not clear what this feature would do. Probably best would be to provide a pseudo-unit test to illustrate

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
