### ISSUE TITLE
Linking to the latest release

### ISSUE THREAD

**Issue by Blonder** [google/googletest#1553]
Hello is it possible to add a link to the latest release, see https://help.github.com/articles/linking-to-releases/ as in https://github.com/zeux/pugixml/releases

**Comment by stefan-muc** [comment]
I guess that would require some text to be written for a release, e.g. the still missing release notes - see  #855 

I guess this will become better with upcoming 1.8.1 and 1.9.0 release

**Comment by andreasluca** [comment]
When is a release scheduled for? Or which is the latest release (after 1.8, which is quite old...)?

**Comment by gennadiycivil** [comment]
See https://github.com/google/googletest/issues/1531

**Comment by gennadiycivil** [comment]
https://github.com/google/googletest/releases/tag/release-1.8.1
