### ISSUE TITLE
Build of unit tests fails in clang with c++11

### ISSUE THREAD

**Issue by s-kenji** [google/googletest#1565]
Hi,
I cannot run unit tests using gtest in clang with c++11.
The following error has occurred.
```
In file included from /Users/s-kenji/workspace/my_project/test/jsonparser.cc:5:
In file included from /Users/s-kenji/workspace/my_project/build/googletest-src/googlemock/include/gmock/gmock.h:58:
/Users/ksugimur/workspace/my_project/build/googletest-src/googlemock/include/gmock/gmock-actions.h:388:18: error: use of overloaded operator '==' is ambiguous (with operand types 'const internal::linked_ptr<ActionInterface<void
      (const basic_json<std::map, std::vector, basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer> &, bool *, int *)> >' and 'nullptr_t')
    return impl_ == nullptr && fun_ == nullptr;
           ~~~~~ ^  ~~~~~~~
```
The cause of this error is that overloaded operator '==' is not defined for comparison of linked_ptr and nullptr, So I would like to contribute a patch to define the comparison of linked_ptr and nullptr.

Version: 
Clang: Apple LLVM version 9.1.0 (clang-902.0.39.1)
OS: macOS HighSierra 10.13.2
commit: 531e29485c3bd21a5f2fa846dfc62f9c38756033

**Comment by gennadiycivil** [comment]
Looking through comments looks like it is no longer an issue. Please let me know otherwize
