### ISSUE TITLE
is the release version history maintained?

### ISSUE THREAD

**Issue by kalyanaramansanthanam** [google/googletest#1583]
looks like the github > releases  pages was last update in `Aug 22, 2016`
is there an alternative release history page maintained?

**Comment by xkszltl** [comment]
If you take a look at the previous versions, they all have several years in-between

**Comment by gennadiycivil** [comment]
See https://github.com/google/googletest/issues/1531

**Comment by kalyanaramansanthanam** [comment]
sorry, i don't follow. why is #1531 relevant for this ticket?

**Comment by gennadiycivil** [comment]
Sorry, wrong paste, the next release is "coming soon" see https://github.com/google/googletest/issues/1467

**Comment by kalyanaramansanthanam** [comment]
thanks
