### ISSUE TITLE
In addition to PASS & FAIL, also add test result class SKIPPED (or similar)?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#160]
```
We are using GTEST for very many tests, however all test in our test case 
definition are linked together and executed. Unfortunately, some tests can 
only be executed if the environment is correctly set up (must be done 
manually). Therefore these tests are always failing, but in fact they could 
not be executed.

Would it be possible to the test case result "SKIPPED" as a new class to a 
test case (maybe colored yellow ;-) to abort a test if it determines it 
cannot be executed in this environment?
```

Original issue reported on code.google.com by `constant...@gmail.com` on 2 Jul 2009 at 5:30

**Comment by CryPtiC128** [comment]
Is there any update on this request or any need in the community to require such an update?

In my opinion, a third state ("inconclusive" / "skipped" / ...) in testing is very important: Every test above unit test level (or at least most of them)
- answers a question and
- has some kind of preconditions (= the arrange part).
If the test environment cannot be brought to match the preconditions, the question cannot be answered. Thus the test did not fail.

In many cases, the arrange part of a test does not even concern the aspect under test. If there was an error in such an arrange part, we would not have a problem in our aspect under test, but no information.

**Comment by LazyWolfLin** [comment]
I am looking for this too.

I use gtest in my work, and it rely on the remote server. So I want some test is skipped if the remote server is break.
