### ISSUE TITLE
Accessing deleted function due to purported user-defined move constructor

### ISSUE THREAD

**Issue by pauluap** [google/googletest#1600]
I have a working GoogleTest/GoogleMock project on Linux building with the GCC toolchain.

I'm running into problems on Windows with Microsoft Visual Studio 2017 version 19.14.26428.1 for x64

I'm getting this type of error for several files:

```
D:\uet\repostories\eBMS\tests\Mock/bank/MockUpstreamInterface.hpp(21): error C2280: 'testing::internal::MockSpec<bool (nsapi_error_t)>::MockSpec(const testing::internal::MockSpec<bool (nsapi_error_t)> &)': attempting to reference a deleted function
D:\uet\repostories\eBMS\tests\GMock\master\googlemock\include\gmock/gmock-spec-builders.h(1302): note: compiler has generated 'testing::internal::MockSpec<bool (nsapi_error_t)>::MockSpec' here
D:\uet\repostories\eBMS\tests\GMock\master\googlemock\include\gmock/gmock-spec-builders.h(1302): note: 'testing::internal::MockSpec<bool (nsapi_error_t)>::MockSpec(const testing::internal::MockSpec<bool (nsapi_error_t)> &)': function was implicitly deleted because a data member invokes a deleted or inaccessible function 'std::tuple<testing::Matcher<A1>>::tuple(const std::tuple<testing::Matcher<A1>> &)'
        with
        [
            A1=nsapi_error_t
        ]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\tuple(457): note: 'std::tuple<testing::Matcher<A1>>::tuple(const std::tuple<testing::Matcher<A1>> &)': function was implicitly deleted because 'std::tuple<testing::Matcher<A1>>' has a user-defined move assignment operator
        with
        [
            A1=nsapi_error_t
        ]
```

Line 21 is the first mock function in this struct declaration 

```
class RawUpstreamInterface
{
public:
    MOCK_METHOD1(mock_UpdateError,   bool(nsapi_error_t));
    MOCK_METHOD1(mock_UpdateAddress, bool(char const *));
};
```

And `nsapi_error_t` is `enum nsapi_error_t { ... };`

Since neither `bool` or `nsapi_error_t` are types that could conceivably have user-defined move assignment operator, and that the project has been building with GCC, that suggests to me that the issue could be with the library implementation of `std::tuple`  but there are dragony things there and I'm not sure what the workaround would be.

I was using version 1.7.0, but after running into this issue, I tried out master, but that did not change anything.

Is there anything that I can do to resolve this at least locally?

**Comment by gennadiycivil** [comment]
There has been a lot of code movement lately. Is this still an issue?

**Comment by pauluap** [comment]
It appears to have been an issue with Visual Studio 2017.  A newer version of compiler was able to compile the code without any changes to Google Mock.  So it appears to be out of scope for this project.  Thanks for advancing Google Test/Mock, I use it heavily.
