### ISSUE TITLE
CC-BY-2.5 License for DevGuide.md ?

### ISSUE THREAD

**Issue by anirudh2290** [google/googletest#1604]
Apache MXnet uses googletest as one of the submodules and it has a CC-BY-2.5 license for [DevGuide.md](https://github.com/google/googletest/blob/ec44c6c1675c25b9827aacd08c02433cccde7780/googlemock/docs/DevGuide.md). This falls under [category b](https://www.apache.org/legal/resolved.html#category-b) which makes it a problem for us since MXNet is under Apache License 2.0. Was the doc DevGuide.md intended to be a different license from the license for source ? Can this be relicensed to be the same license as source?

**Comment by gennadiycivil** [comment]
This is no longer relevant I believe
