### ISSUE TITLE
Access violation exception.

### ISSUE THREAD

**Issue by p-groarke** [google/googletest#1618]
All of a sudden, gtest has started throwing exceptions when trying to start tests. Using gtest 1.8.0 from bincrafters conan repo. MSVC 15.7 x64.

It seems adding a new test caused this problem to start. Removing tests 1 by 1 is inconclusive.

```
proj.exe!std::_Uninitialized_move_al_unchecked<int *,int *,class std::allocator<int> >(int *,int *,int *,struct std::_Wrap_alloc<class std::allocator<int> > &)	Unknown
proj.exe!std::_Uninitialized_move<int *,int *,class std::allocator<int> >(int *,int *,int *,struct std::_Wrap_alloc<class std::allocator<int> > &)	Unknown
proj.exe!std::vector<int,class std::allocator<int> >::_Umove<int *>(int *,int *,int *)	Unknown
proj.exe!std::vector<int,class std::allocator<int> >::_Reallocate(unsigned __int64)	Unknown
proj.exe!std::vector<int,class std::allocator<int> >::_Reserve(unsigned __int64)	Unknown
proj.exe!std::vector<int,class std::allocator<int> >::push_back(int &&)	Unknown
proj.exe!testing::internal::UnitTestImpl::GetTestCase(char const *,char const *,void (*)(void),void (*)(void))	Unknown
proj.exe!testing::internal::UnitTestImpl::AddTestInfo(void (*)(void),void (*)(void),class testing::TestInfo *)	Unknown
proj.exe!testing::internal::MakeAndRegisterTestInfo(char const *,char const *,char const *,char const *,struct testing::internal::CodeLocation,void const *,void (*)(void),void (*)(void),class testing::internal::TestFactoryBase *)	Unknown
proj.exe!`dynamic initializer for '`anonymous namespace'::tree_constructors_Test::test_info_''() Line 36	C++
```

**Comment by p-groarke** [comment]
Works in release, probably UB somewhere.

**Comment by wkaluza** [comment]
FYI, Visual Studio in the 15.7 update introduced several compiler bugs which manifest as access violations in previously working code. One of many examples:

https://developercommunity.visualstudio.com/content/problem/251254/reading-access-violation-in-vectorpush-back.html

I'd have a look at what's already been reported to Microsoft, and if your issue seems novel, open a bug so they can investigate. MS seem reasonably responsive and eager to handle the situation.

**Comment by p-groarke** [comment]
Duplicate of MSVC bug https://developercommunity.visualstudio.com/content/problem/251254/reading-access-violation-in-vectorpush-back.html
