### ISSUE TITLE
Usage of _MSC_VER should check for defined() first

### ISSUE THREAD

**Issue by emrainey** [google/googletest#1634]
https://github.com/google/googletest/blob/ba96d0b1161f540656efdaed035b3c062b60e006/googletest/include/gtest/internal/gtest-port.h#L316

https://github.com/google/googletest/blob/ba96d0b1161f540656efdaed035b3c062b60e006/googletest/include/gtest/internal/gtest-port.h#L2552

There's multiple uses of `_MSC_VER` which are guarded with `defined(_MSC_VER)` checks and a few which are not guarded, which causes users to have to add flags to their compilers to accommodate this uneven usage. 

Good usage:
https://github.com/google/googletest/blob/ba96d0b1161f540656efdaed035b3c062b60e006/googletest/include/gtest/internal/gtest-internal.h#L790

**Comment by gennadiycivil** [comment]
@emrainey Please feel free to create a PR

**Comment by johnmcfarlane** [comment]
@gennadiycivil this issue still affects users who wish to compile their code error-free and who might not be in a position to ignore googletest warnings (say, with `-isystem`). Should it not be kept open as *help needed*?
