### ISSUE TITLE
Unable to use gtest with C++98 project

### ISSUE THREAD

**Issue by avanti21** [google/googletest#1635]
Hello,

We are trying to consume gtest framework in our existing code base which has been written using C++98 and we still do not support C++ 11 features. While compiling our code, we are getting errors for std::tuple. Is there any way to consume header of C++ 98 or is it available somewhere?

**Comment by tanzislam** [comment]
Looking at the [portability code](https://github.com/google/googletest/blob/master/googletest/include/gtest/internal/gtest-port.h#L88-L102), it looks like you need to set the preprocessor symbols `GTEST_HAS_TR1_TUPLE=0`, `GTEST_USE_OWN_TR1_TUPLE=1` and `GTEST_LANG_CXX11=0`.
