### ISSUE TITLE
Raspberry PI 3 DMX OLA tests  (www.nomis52.net doesn't exist anymore?)

### ISSUE THREAD

**Issue by philarnaud** [google/googletest#1636]
Good morning,
I am trying to run OLA on a Raspberry pi. I found some explainations on  https://opendmx.net/index.php/LLA,_OpenDMX_USB_and_Q_Light_Controller_Tutorial

I have some issues on this phase
Build_and_install_the_usb_kernel_module but I can't load this phase:
There are debian packages available at the time of writing. 
Add the packages to your sources file:
sudo gedit /etc/apt/sources.list
Add the following line at the end:
deb http://www.nomis52.net/data/debian ./

Install the packages:
sudo apt-get update  -> errors
sudo apt-get install liblla0 llad llad-console lla-examples

www.nomis52.net doesn't exist anymore.
Is someone able to help me?

Best regards.
Philippe

**Comment by Bu11etmagnet** [comment]
Perhaps you should ask the OLA project.

**Comment by gennadiycivil** [comment]
Not relevant for googletest, sorry
