### ISSUE TITLE
Change CMAKE_BINARY_DIR to CMAKE_CURRENT_BINARY_DIR in README

### ISSUE THREAD

**Issue by shunjilin** [google/googletest#1639]
In https://github.com/google/googletest/tree/master/googletest/README.md
Under 'Using CMake - Incorporating Into An Existing CMake Project', 
might want to change instances of CMAKE_BINARY_DIR to CMAKE_CURRENT_BINARY_DIR, 
otherwise users who organize test related files into subdirectories will not be able to configure.

This has been mentioned https://github.com/google/googletest/pull/1285 but the pull request seems to be stuck in the CLA verification stage

**Comment by jeffvandyke** [comment]
Just did this for a project of mine, could this just quick be changed in the documentation?

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.
