### ISSUE TITLE
Tests crash on AIX7.1 when using static libgcc / libstdc++ and exception is thrown

### ISSUE THREAD

**Issue by SteveHallNNT** [google/googletest#1640]
Hi all
I'm having a problem using Google Test on AIX7.1.   I have a very simple program like so:

```
#include <gtest/gtest.h>
 
void ThrowFunc()
{
  try
  {
    throw "error";
  }
  catch(...)
  {
    printf("Gotcha!\n");
  }
}
 
TEST(MyTests, MyTest)
{
  ThrowFunc();
  EXPECT_TRUE(true);
}
 
int main(int argc, char ** argv)
{
  printf("Normal\n");
  ThrowFunc();
  printf("GTest\n"); 
  ::testing::InitGoogleTest(&argc, argv);
  int retcode = RUN_ALL_TESTS();
 
  return 0;
}
```

Which I compile with :

`$ g++ -o testgtest -static-libgcc -static-libstdc++ -I <path to gtest include> -L <path to gtest .a libs>   -lpthread -lgtest testgtest.cpp`

When run it crashes when the exception is thrown inside a test (but is fine outside the test) :

```
$ ./testgtest 
Normal
Gotcha!
GTest
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from MyTests
[ RUN      ] MyTests.MyTest
IOT/Abort trap (core dumped)
```

Compiling without the static libgcc / libstdc++ works fine.

Does anyone have any ideas?

Thanks
Steve H

**Comment by gennadiycivil** [comment]
googletest can be compiled with exceptions and without exceptions. 
Perhaps yours is compiled without?

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
