### ISSUE TITLE
Distinguish between multiple expectations created on the same line

### ISSUE THREAD

**Issue by Bu11etmagnet** [google/googletest#1641]
https://stackoverflow.com/q/50986645
I have some test code which sets up expectations like this:

    InSequence seq;
    for (auto const& p : scenario) {
      ON_CALL(mock_object, query(p.input))
        .WillByDefault(Return(p.result));
    }

Unfortunately, this makes it difficult to identify failed expectations, because they are all reported on the same line.

Is there a way to attach some description to the expectation, that appears in the output in case of failure?

**Comment by asoffer** [comment]
Apologies for the lengthy delay. The `SCOPED_TRACE` macro is what you're looking for.

**Comment by Bu11etmagnet** [comment]
I don't believe `SCOPED_TRACE` is what I'm looking for.
Putting a `SCOPED_TRACE` inside the loop before the `ON_CALL` has no effect.
