### ISSUE TITLE
Access Violation when integrating with Visual Studio test framework

### ISSUE THREAD

**Issue by ericlemes** [google/googletest#1643]
Hi there,

I'm trying to use Google Mock with Visual Studio test framework, following the guidelines of the documentation. 

I created a sample where the issue can be reproduced in a single file, if you create a new native unit test project and add google test and google mock root and include directories. In this sample, I removed the listener, initialization code, etc, just to keep it simple, but the result is the same if you have the init code and a listener.

I didn't set any specific GTEST_* pre processor directive. I've just included the gtest-all and gmock-all src files to keep it simple and eliminate more variables.

I've used VS 15.6.* and latest google test code. I appreciate if anyone has thoughts about this issue.

The runners behave differently if compiled in 64 or 32 bits. In 32 bits it executes with success (but you see the exception in debug) and in 64 bits it aborts the test run, not reporting any result.

Here's the code:

`

#include "stdafx.h"
#include "CppUnitTest.h"
#include "gmock/gmock.h"

#include "src/gmock-all.cc"
#include "src/gtest-all.cc"

using namespace Microsoft::VisualStudio::CppUnitTestFramework;

namespace GMockVSTest
{		
	class ITest {
	public:
		virtual ~ITest() {};
		virtual void DoSomething() = 0;
	};

	class MockITest : public ITest {
	public:
		MOCK_METHOD0(DoSomething,
			void());
	};

	TEST_CLASS(UnitTest1)
	{
	public:
		
		TEST_METHOD(TestMethod1)
		{
			MockITest mockITest;
			EXPECT_CALL(mockITest, DoSomething());

			mockITest.DoSomething();
		}

	};
}

`

**Comment by gennadiycivil** [comment]
There is no actionable information here

**Comment by SpaceTestMonkey** [comment]
Why was this issue closed? 

Actually I just ran into it and can replicate it, exactly as original poster described, just in 1.10.0

- GoogleTest + x86 -> works
- GoogleTest + x64 -> works
- MsTest (aka CppUnit) + x86 -> works
- MsTest (aka CppUnit) + x64 -> throws access violation outside of stack frame after test run

As GMocks is advertised to work with other test runners, I consider this to be a real problem :(

I have attached a visual studio 2017 solution, that reproduces the problem.

[GTestStaticLib-1.10.0.zip](https://github.com/google/googletest/files/5702597/GTestStaticLib-1.10.0.zip)

**Comment by ericlemes** [comment]
@SpaceTestMonkey I tried for a long time to make it work on MsTest and eventually gave up. It seems like no one is actually interested in making this work on VSTest. I really recommend to use GTEST as a test runner and don't waste your time.

I think is something related to the way VSTest/MSTest handles exception and the way GoogleMock handles it.

**Comment by SpaceTestMonkey** [comment]
@ericlemes 
> I think is something related to the way VSTest/MSTest handles exception and the way GoogleMock handles it.

Thank you for the Heads Up. I suppose I ll try with GTest Runner too, hope it integrates in our environment

**Comment by rajeshdaggumati99** [comment]
Hi ,
I am preparing a document on gtest for c++ code unit tetsing.
As part of that document, I need some information regarding data integrity and security of gtest and how it interacts with any software and any access violations or data stealing ?

please let me know  .
