### ISSUE TITLE
Unable to build using clang-cl

### ISSUE THREAD

**Issue by thekitchensink** [google/googletest#1649]
Hi, 

At the moment googletest is unable to build on windows using clang-cl. This is because currently clang-cl doesn't seem to support the __pragma(warning(disable:xxxx)) syntax that msvc does. This causes the build to fail due to deprecated function usage.

It looked like PR #1337 was opened to fix it, but it never got merged due to not passing CI.

**Comment by gennadiycivil** [comment]
closing, should be good now
