### ISSUE TITLE
fuse_gtest_files.py should leave gtest_prod.h separate

### ISSUE THREAD

**Issue by abigailbunyan** [google/googletest#1650]
[`googletest/scripts/fuse_gtest_files.py`](https://github.com/google/googletest/blob/master/googletest/scripts/fuse_gtest_files.py) fuses the entire googletest tree into two files, `gtest-all.cc` and `gtest.h`.

googletest also contains [`gtest_prod.h`](https://github.com/google/googletest/blob/master/googletest/include/gtest/gtest_prod.h), which contains definitions that are useful in production code. The fuse script currently fuses this into `gtest.h`. It would be nice if it could (either always or optionally) leave `gtest_prod.h` separate, so that production code doesn't have to include a 21000-line `gtest.h` just to use the one short macro that `gtest_prod.h` defines.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. Unfortunately there appears to be no actionable information. 
Could you please explain in greater details your use case.

Regarding fusing - this is not how we use googletest internally and these scripts are most likely to be removed * some time soon *

**Comment by abigailbunyan** [comment]
Our use case is as follows:

* Our test code does `#include <gtest/gtest.h>` to use googletest functionality
* Our production code does `#include <gtest/gtest_prod.h>` to access the `FRIEND_TEST` macro
* We use googletest by bundling it into a third-party dependency directory in our repository.

Fusing googletest files is attractive to us as it allows us to compile a single compilation unit for all of googletest, and means less files to bundle to use googletest as a dependency. However, it means that the fairly common pattern above (using `<gtest/gtest.h>` in test code, and `<gtest/gtest_prod.h>` in production code) is no longer possible.

I suggest that the fusing script should instead produce three files: `gtest-all.cc`, `gtest.h` and `gtest_prod.h`. This would make fusing more useful in scenarios like this. If the fusing scripts are due to be removed then this issue can be closed.

**Comment by gennadiycivil** [comment]
if fusing is important for you - the best way to approach this would be to create a proper PR and submit it for consideration

**Comment by gennadiycivil** [comment]
Ping

**Comment by abigailbunyan** [comment]
I'll see if I can find time to write a PR.

**Comment by gennadiycivil** [comment]
Related https://github.com/google/googletest/pull/2268.
I am closing this as inactive
