### ISSUE TITLE
[Feature Request] Support for Arduino / PlatformIO

### ISSUE THREAD

**Issue by ciband** [google/googletest#1659]
It would be nice if GTest was supported in the PlatformIO framework for Arduino.

One of my projects runs on both desktop OSes and IoT (ESP32 and ESP8266).  I use GTest for Windows/Mac/Linux and Aunit with an adapter to use the GTest interface.

Native support would be nice if possible.  Thanks.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
We can close this now, the PR has been merged
