### ISSUE TITLE
Horrible Documentation

### ISSUE THREAD

**Issue by Joebeazelman** [google/googletest#1660]
It's really a sad state of affairs when a multibillion dollar company can't write straightforward documentation to support their software.  I've looked high and low for how to configure Google Test using the XCode IDE and I have only run into a series of dead ends.  I would expect something as simple as running brew or npm. Instead, I have to build the entire test library and include it in my source tree because the developers couldn't be bothered to put in a bit more work into automation, or to put in the resources to write adequate documentation.  Very pathetic!

**Comment by tesch1** [comment]
Their software that you're getting for [absolute free](https://www.reddit.com/r/ChoosingBeggars/)?  Stop complaining, take a break from your whiny entitlement, and contribute some code and/or documentation!

**Comment by gennadiycivil** [comment]
There appears to be no actionable information.

**Comment by Joebeazelman** [comment]
Absolutely free?  Get a clue! 

First, there’s no such thing as free. Google isn’t running a charity here.  Their making money indirectly from open source. It saves them millions in licensing fees and plays into their fake “do no evil” propaganda. It also makes them a darling among  the gullible technorati. Of course, Google isn’t stupid enough to open source their search engine.

Second, I am entitled and have a right to complain. Open source has decimated an entire industry of small software companies and solo developers who created quality software because they can’t compete with free. Ironically, big business, who are not threatened by open source, are the real winners. Unlike yourself, I will speak up when faced with no alternatives to dog food.

Ironically, most open source advocates have no issue paying for $2500 MacBook Pros, but throw a hissy fit at paying less than a cup of coffee for software. Under their logic, since software is ethereal, it has no percieved value, despite the enormous human effort involved in writing it. Open source advocates, such as yourself, are painfully unaware of how anti-intellectual and anti-competitive open source is.

**Comment by Bu11etmagnet** [comment]
>  There's a great tool you can use to find that out, you might have heard it it, it's called "google", just google that.

Don't do it! https://www.youtube.com/watch?v=OqxLmLUT-qc
