### ISSUE TITLE
Absolutely a Waste of Time

### ISSUE THREAD

**Issue by markfrazzetto** [google/googletest#1666]
Stay away from this tool set.  I tried installing to a local directory, the poor design of the headers produced countless compile errors.  I tried installing from my linux distro repo and the libraries were not included in the install.  I tried doing a sudo make install and used pkg-config to supply the compile and link parameters, and got countless link errors.  I am no newb, I have written and compiled so many programs under Linux and Unix, and googlemock\googletest have wasted my time more than any other library I have tried to use.
You basically have to be a CMake guru to use these tools.  Stay away unless you have considerable devop  experience.

**Comment by tanzislam** [comment]
Have you tried `git clone`-ing from this GitHub repo? The distro repo may have problems of its own.

I haven't had any problems building `googletest` (using the makefile in `googletest/make/Makefile`) with:

 - GCC (under MinGW-w64/MSYS2 on Windows 7, WSL on Windows 10, and Ubuntu 16.04 and above)
 - Clang (running as `g++` inside macOS 10.2 and 10.3)

I had slight problems building on the following platforms, but eventually overcame them. You can see how in [the Wiki pages of my project](https://github.com/tanzislam/cryptopals/wiki):

 - Visual Studio Community 2015 and 2017
 - Embarcadero C++Builder Starter 10.1 (Berlin) and 10.2 (Tokyo)

**Comment by tesch1** [comment]
Note to self: don't invite Mark to the next party.

**Comment by gennadiycivil** [comment]
There appears to be no actionable information.
