### ISSUE TITLE
Primer points to google internal page

### ISSUE THREAD

**Issue by froody** [google/googletest#1681]
At https://github.com/google/googletest/blob/master/googletest/docs/primer.md in the table for 

Meaning | googletest Term | ISTQB Term

There's a link for TestCase which links to https://g3doc.corp.google.com/third_party/googletest/googletest/g3doc/primer.md#basic-concepts

My guess is it should link to
https://github.com/google/googletest/blob/master/googletest/docs/primer.md#basic-concepts

**Comment by vkotovv** [comment]
Looks like it was fixed: https://github.com/google/googletest/blob/master/googletest/docs/primer.md#beware-of-the-nomenclature
