### ISSUE TITLE
Is there any suggested "coding to interface" book?

### ISSUE THREAD

**Issue by amaruk** [google/googletest#1683]
Dear the Gtest team,

We started with CppUnit and now we've migrated to the Gtest/Gmock framework for awhile.
The framework works pretty well.
Now that we are trying to use Gmock to make testing life easier, we can't help noticing that our product code is not that testing friendly. Yes, we didn't code to interface. Luckily, we still have enough to refactor our product code.
We tried to be coding to interface, but still met quite some design problems, such as private member function mock, interface and singleton conflict, etc.
We also googled some coding to interface related posts, but they are more or less simple suggestions for special cases.
So we wonder if there is any suggested books, other than the Gmock cookbook, which describe general skills or best practices of c++ coding to interface?

Thanks a lot!

Sincerely Yours,
Amaruk

**Comment by siralexmu** [comment]
Hi @amaruk ,
Have you tried "Modern C++ programming with test-driven development" by Jeff Langr?

**Comment by hendrics** [comment]
“Modern C++ programming with TDD” is great but I would also recommend https://www.goodreads.com/book/show/58128.Head_First_Design_Patterns
It is from 2004 and java based but I’ve only discovered it recently and can whole hartedly recommend. It address coding to the interface and other concept from
Get go and explains the pitfalls and compromises.

**Comment by amaruk** [comment]
@siralexmu
@hendrics
I got the "Head First Design Patterns" last week. It's a book that can make people remember things easily.
The "Modern C++ programming with TDD" sounds like exactly the book I need. I'm going to order it, now.
Thank you so much for your recommendations!
