### ISSUE TITLE
Setting -D_GLIBCXX_USE_CXX11_ABI=0 has no effect?

### ISSUE THREAD

**Issue by ButchDean** [google/googletest#1687]
Hi,

Trying to set the environment to link against the pre-C++11 abi with GCC8.1 on Linux has no effect, unless I am missing something. I have tried editing the _internal_utils.cmake_ file at the point:

`target_link_libraries(${name} ${CMAKE_THREAD_LIBS_INIT})`

like this:

`target_link_libraries(${name} ${CMAKE_THREAD_LIBS_INIT} -D_GLIBCXX_USE_CXX11_ABI=0)`

but all that does is:

$ strings libgtest.so | grep GLIBCXX
GLIBCXX_3.4.21
GLIBCXX_3.4.20
GLIBCXX_3.4.14
GLIBCXX_3.4.5
GLIBCXX_3.4.15
GLIBCXX_3.4

to

$ strings libgtest.so | grep GLIBCXX
GLIBCXX_3.4.20
GLIBCXX_3.4.15
GLIBCXX_3.4.21
GLIBCXX_3.4

so it literally just removes the number of versions supported instead of only going up to GLIBCXX_3.4.13 for instance. What am I doing wrong?

Thank you.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. Unfortunately there appears to be no actionable information, not really clear what you are trying to do here and why

**Comment by ButchDean** [comment]
And thank you for your reply. Unfortunately I cannot remember the specifics any longer as I believe I worked around it. If anything comes to light again I will update.
