### ISSUE TITLE
New Project and New Item not showing up in Visual Studio for other languages than English

### ISSUE THREAD

**Issue by BlackStarX42** [google/googletest#1694]
Neither the project nor the item template of Google Test are shown in the New Project or the Add New Item dialog in Visual Studio if the language of Visual Studio is set to anything else than English. I have confirmed that at least German, French, Spanish and Italian are affected.
In the following 2 screenshots are captured with English language setting.
![newprojecten](https://user-images.githubusercontent.com/41993823/43517349-eddf70c0-9577-11e8-82cc-5676724b023f.png)
![addnewitemen](https://user-images.githubusercontent.com/41993823/43517356-f1f501e8-9577-11e8-8d69-f5b4e29eb48f.png)
The next 2 screenshots are captured with German language setting. You can see that, compared with the English language setting, the Google Test project and item respectively is missing.
![newprojectde](https://user-images.githubusercontent.com/41993823/43517361-f4bc5b6a-9577-11e8-8e06-4e3a150d9e52.png)
![addnewitemde](https://user-images.githubusercontent.com/41993823/43517364-f64c65e2-9577-11e8-9bfa-c18990bebdaa.png)

**Comment by wkaluza** [comment]
This smells like a problem with Visual Studio, not with Google Test. You can report it to Microsoft here: https://developercommunity.visualstudio.com

**Comment by BlackStarX42** [comment]
As chance would have it, I already did: https://developercommunity.visualstudio.com/content/problem/240774/visual-studio-templates-for-google-test-not-showin.html
As you can see, the bug report was closed as not their product.

**Comment by wkaluza** [comment]
My bad, thank you for clarifying.
