### ISSUE TITLE
How can I used some args of main？

### ISSUE THREAD

**Issue by big91987** [google/googletest#1701]
I'm new to gtest, here's a problem that I encounter
Sometimes I want to use some param that passed form argv/argc of the MAIN function 
(not like --gtest_xxx),  to do some action in my test while using the shell , BUT I don't know how to do that  Is there anyone come across the the same issue ？ 

like that: 
int main(int argc, char** argv) {
     char a = argv[2];
     ....
}

TEST_F(xxxx) {
  if (a=="234") {
        EXPECT_EQ(1, xxxx);
  } else {
  }
}

cmd：
./gts  xxx 234

**Comment by Bu11etmagnet** [comment]
The code behind the TEST_F(fixture, testname) macro creates a class which is derived from the test fixture class. An instance of this class is created for each test (by some magic means). You need to communicate information from main to the test fixture class. The easiest way to achieve this is via global variables (set in main(), read in the test fixture constructor or the test body).

**Comment by BrukerJWD** [comment]
```
std::string a; // global variable
int main(int argc, char** argv) {
    a = argv[2]; // don't forget argc check here
}
TEST_F(xxxx) {
    if (a=="234") {
        EXPECT_EQ(1, xxxx);
    }
}
```

If you want to check certain parameters, you may want to use [parameterized tests](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#value-parameterized-tests).
