### ISSUE TITLE
How can I change the name of testSuite during the test?

### ISSUE THREAD

**Issue by big91987** [google/googletest#1702]
Hello, everyone, recently, my company has a new requirement which need to modify the name attribute of the testSuit  during the TEST so that the XML report contains this msg, for example, if there is a error during the test, I hope to append the branch name of the test object (a string) to the "name" , purely it's for jenkins to generate a report.

Do you have the same needs? How do you handle them?

**Comment by gennadiycivil** [comment]
This does not seem a general requirement but rather a corner case. If this is an important feature for your please feel free to submit a PR for consideration
