### ISSUE TITLE
Adding installation guide to the README

### ISSUE THREAD

**Issue by Spandan-Madan** [google/googletest#1729]
For any code base, isn't it brutally obvious to add an installation guide?

For others struggling, just use this if you're on a mac:- https://gist.github.com/butuzov/e7df782c31171f9563057871d0ae444a

**Comment by tanzislam** [comment]
The README file does say:

>More detailed documentation for googletest (including build instructions) are in its interior googletest/README.md file.

That should get you going locally, without installing it at a system level. (To install it on the system it's probably better to use your system's package manager, although you won't get the latest version that way.)

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
