### ISSUE TITLE
Faulty condition in checking parametrized-test suffix names for underscores

### ISSUE THREAD

**Issue by Hodobox** [google/googletest#1747]
https://github.com/google/googletest/blob/3306848f697568aacf4bcca330f6bdd5ce671899/googletest/include/gtest/internal/gtest-param-util.h#L642

if (!isalnum(name[index]) && name[index] != '_')
        return false;

when name[index] == '_', this evaluates to ( true && false), so it doesn't return false - it lets suffixes containing underscores pass (I was able to put undescores in my suffixes, but no other non-alphanumeric chars).

if the documentation in 'Specifying Names for Value-Parameterized Test Parameters' is to be believed:
'In particular, they should not contain underscores.',

this should be
if (!isalnum(name[index]) || name[index] == '_')
        return false;
instead.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
