### ISSUE TITLE
Build fails: error: mutex 'mutex_' is still held at the end of function

### ISSUE THREAD

**Issue by yurivict** [google/googletest#1751]
Build of google/benchmark fails due to googletest: https://github.com/google/benchmark/issues/655

**Comment by yurivict** [comment]
```googletest-1.8.0.712``` on FreeBSD 11.2, ```clang-6```.

**Comment by jbeich** [comment]
FreeBSD [annotated](https://github.com/freebsd/freebsd/commit/72b4dec586dbec62ce27c16a908955fb89c58235#diff-77ebab68662ffb25be0c4998868f8340) `<pthread.h>`, so consumers has to do the same. If you don't like the warning pass `-isystem/path/to/prefix` for compiler to [ignore warnings](https://gcc.gnu.org/onlinedocs/cpp/System-Headers.html) en masse (e.g., via `USES=localbase`), don't use `-Wthread-safety`/`-Werror` (use `-Werror=whatever` instead) or silence it via `__attribute__((no_thread_safety_analysis))` or `#pragma GCC diagnostic ignored "-Wthread-safety"`.

Simplified:
```c
typedef void * pthread_mutex_t __attribute((capability("mutex")));

int pthread_mutex_lock(pthread_mutex_t *lock) __attribute__((exclusive_lock_function(* lock)));

pthread_mutex_t *lock;
void Lock() { // Not annotated yet
  pthread_mutex_lock(lock);
}
```

```
$ cc -c test.c -Wthread-safety
test.c:8:1: warning: mutex 'lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
test.c:7:3: note: mutex acquired here
  pthread_mutex_lock(lock);
  ^
1 warning generated.
```

**Comment by gennadiycivil** [comment]
Looks stale, googletest code changed a lot, I assume this is no longer an issue and closing
