### ISSUE TITLE
Invalid use of void expression error

### ISSUE THREAD

**Issue by lornarmac** [google/googletest#1763]
With gcc 5.2.0 (or 5.4.0) and the -std=c++11 compiler option I get lots of these "invalid use of void expression" errors in, for example, the expansion of GTEST_ASSERT. Output in attached file.

[TestPackage Build errors.txt](https://github.com/google/googletest/files/2307131/TestPackage.Build.errors.txt)

Is there some PP define I need perhaps? Should I be able to compile googletest with this compiler option & compiler combination?

It's google test v 1.8.x

Thanks

**Comment by 2power10** [comment]
could you share how those function looks like: `audioSmartXMgr->stopAVBCall()`, `audioSmartXMgr->stopECNRCall()`.
