### ISSUE TITLE
Feature Request: EXPECT_NULL or EXPECT_NULLPTR

### ISSUE THREAD

**Issue by rohan-varma** [google/googletest#1766]
I find myself using EXPECT_EQ(object, nullptr) a lot in my tests. In my opinion, it might look cleaner if we could do something like EXPECT_NULL(object), which makes the statement and what we are testing a little more clear. I saw that gmock supports an IsNull() method, so I was wondering if we could do something similar in gtest. I'd be happy to implement this feature if we decide to move forward with it!

**Comment by wkaluza** [comment]
I wouldn't count on it - as seen e.g. in #1661 the maintainers don't want to add to the arsenal of macros that gtest already exposes. You might just have to create this macro yourself as a test helper.
