### ISSUE TITLE
Unfriendly for mocking global functions/non-virtual methods

### ISSUE THREAD

**Issue by V0idk** [google/googletest#1782]
I have found two project with a friendly approach, based on gmock, but why gmock not provide such approach?
Check: 
https://github.com/gzc9047/CppFreeMock
https://github.com/mazong1123/injectorpp

```cpp
//CppFreeMock
string func() {
    return "Non mocked.";
}

TEST(HelloWorld, First) {
    EXPECT_CALL(*MOCKER(func), MOCK_FUNCTION()).Times(Exactly(1))
        .WillOnce(Return("Hello world."));
    EXPECT_EQ("Hello world.", func());
}
```

**Comment by gennadiycivil** [comment]
Thank you very much for this report. Unfortunately there appears to be no actionable information.
