### ISSUE TITLE
CMake WRITE_BASIC_CONFIG_VERSION_FILE for CMake Versions < 3.0

### ISSUE THREAD

**Issue by athrun22** [google/googletest#1786]
Using CMake 2.8.9, building GoogleTest fails because the PROJECT_VERSION variable is required by the write_basic_config_version_file command on [line 96](https://github.com/google/googletest/blob/58f3f1005cffce8a9d005d0361d3471cd9947501/googletest/CMakeLists.txt#L96), but it is not set for CMake versions < 3.0 on [line 44 of the CMakeLists.txt](https://github.com/google/googletest/blob/58f3f1005cffce8a9d005d0361d3471cd9947501/googletest/CMakeLists.txt#L44). Because the version cannot be set in the project command for versions of CMake less than 3, it is possible to fix this by supplying the version explicitly to the write_basic_config_version_file command. This is shown in the following line, which allowed my project to build successfully.
```cmake
  write_basic_package_version_file(${version_file} VERSION ${GOOGLETEST_VERSION} COMPATIBILITY AnyNewerVersion)
```

**Comment by gennadiycivil** [comment]
Ping

**Comment by fidergo-stephane-gourichon** [comment]
> Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

The fix by @athrun22  works here and allows CMake to complete.
Preparing a PR.
