### ISSUE TITLE
target_link_libraries CMake versions < 3.3 do not support PUBLIC keyword

### ISSUE THREAD

**Issue by athrun22** [google/googletest#1787]
This [commit](https://github.com/google/googletest/commit/6de39826aa190a07179a8104c00ad11ea20d8679#diff-98eb25640483d40b7d2663b41473906aR111) introduced the PUBLIC keyword for target_link_libraries in multiple CMake files. The PUBLIC keyword is not supported until CMake version 3.3, but cmake_minimum_required does not reflect this. Older versions of CMake will try to link with a library called "PUBLIC".

The effected files are the CMakeLists in both [googletest](https://github.com/google/googletest/blob/58f3f1005cffce8a9d005d0361d3471cd9947501/googletest/CMakeLists.txt#L146) and [googlemock](https://github.com/google/googletest/blob/58f3f1005cffce8a9d005d0361d3471cd9947501/googlemock/CMakeLists.txt#L111) and the [internal_utils.cmake](https://github.com/google/googletest/blob/58f3f1005cffce8a9d005d0361d3471cd9947501/googletest/cmake/internal_utils.cmake#L185).

**Comment by sergiud** [comment]
This is not true. The `PUBLIC|PRIVATE|INTERFACE` keywords are available since CMake 3.0: https://cmake.org/cmake/help/v3.0/command/target_link_libraries.html.

**Comment by athrun22** [comment]
Sorry, you're right @sergiud, the interface keywords have been available since 3.0. But, has the cmake_minimum_required been updated to reflect CMake 3.0?

**Comment by sergiud** [comment]
Yes, this needs to be updated.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
