### ISSUE TITLE
std::to_string fails compare

### ISSUE THREAD

**Issue by BeErikk** [google/googletest#1793]
I have the following expression
> std::wstring ft(L"42");
> EXPECT_STREQ(std::to_wstring(42), ft);

I get :
> error C2512: 'testing::AssertionResult': no appropriate default constructor available

What is wrong? The expression pass doctest and MS test

Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26726 for x64 (VS2017 15.8.1)
Compiler options: _-std:c++latest -Zc:strictStrings_

edit:
This works though
> EXPECT_STREQ(std::to_wstring(42).c_str(), ft.c_str());

**Comment by Bu11etmagnet** [comment]
You are using the wrong tool for the job. EXPECT_STREQ is for comparing C strings (const char* or const wchar_t*). If you have std::string-s or std::wstring-s, use EXPECT_EQ.

Note that writing `std::to_wstring(.....).c_str()`is dangerous. `std::to_wstring` returns a temporary object. Using `c_str()` might result in a dangling pointer (probably not in this case).

**Comment by BeErikk** [comment]
OK, thanks, I suspected something like this.
I'm checking up wchar_t support in a library which is using another test suite with uncertain support of wide stings, so it's a translating test suite method issue actually. There's a lot of testing against c-strings involved so the _.c_str()_ member is needed, even though not in this case.
