### ISSUE TITLE
Trying to build GTest on MSVC 12

### ISSUE THREAD

**Issue by uilianries** [google/googletest#1810]
Hi!

I'm trying to build google test using MSVC 12, but I get an error during the execution:

> C:\Users\appveyor.conan\data\gtest\1.8.1\bincrafters\testing\package\f84b2d17334e7b23564f7244508491e451d80357\include\gtest/gtest-printers.h(1036): error C2770: invalid explicit template argument(s) for 'AddReference<const ::std::tr1::tuple_element<I,std::tuple<bool,int>>::type>::type testing::internal::TuplePolicy::get(const std::tuple<bool,int> &)' [C:\projects\conan-gtest\test_package\build\ffafa1fe0219c44dbe68adf8ffbfd78683edb626\test_package.vcxproj]

I tried using some custom settings, like GTEST_HAS_TR1_TUPLE and GTEST_USE_OWN_TR1_TUPLE, but they did not work.

I'm forgetting something?

**Comment by gennadiycivil** [comment]
This  (MSVC++ 12.0  _MSC_VER == 1800 (Visual Studio 2013 version 12.0)) is an old compiler. We wont 'support' it, you are on your own using it, sorry

**Comment by uilianries** [comment]
No problem, thanks for your answer.

Regards.
