### ISSUE TITLE
Windows DLL: macro memory leak and memory allocation/deallocation boundary issues

### ISSUE THREAD

**Issue by szetheli** [google/googletest#1813]
I've compiled googletest as a DLL using cmake and MSVC 2010, then linked it to a project that has overridden the memory management (MemAlloc, operator new, MemFree, operator delete).  The memory manager tracks allocations and raises an exception if the application exits without freeing all the allocated memory.  Memory leaks within the gtestd.dll aren't tracked because it's using the standard memory allocator internally, but memory leaks in the application or test compiled artifacts are reported.

In the process of debugging issues with the custom memory manager, I found two problems:
* TEST/GTEST_TEST/GTEST_TEST_ macros leak objects created in the memory manager of the test implementor.
gtest-internal.h line 1326-1327:
`        new ::testing::internal::TestFactoryImpl<\
            GTEST_TEST_CLASS_NAME_(test_case_name, test_name)>`
The test factory is never deleted and since its a template, it gets created in the test implementor's compile, using the implementors memory manager.
**Solution:** Change the macro to declare the TestFactoryImpl as a global variable, named GTEST_TEST_CLASS_NAME_(test_case_name, test_name)_factory and pass a reference to it instead of using new.  This keeps the factory in scope for the life of the test exe and nothing in gtestd.dll tries to delete it.

* new and delete of memory using different memory manager scopes: 
gtest-internal.h line 1322:
`        ::testing::internal::CodeLocation(__FILE__, __LINE__), \ `
CodeLocation (struct) creates std::string instances that are created in the implementor's memory manager, but then copied without reallocating as the CodeLocation is pass by value into MakeAndRegisterTestInfo.  This results in a case I don't completely understand but the result is that the string::operator new occurs in the test memory manager and the string::delete gets called when the gtestd.dll deletes the TestInfo gets deleted.
**Solution:** Changing MakeAndRegisterTestInfo to pass by reference the CodeLocation declared in the test scope, so that a new copy is created as it is copied into the TestInfo.  The instances created in the test scope are then deleted when the function scope ends using the test memory manager and the strings allocated in the MakeAndRegisterTestInfo are deleted by gtestd.dll in TestInfo::~TestInfo
Note: The use of std::string for CodeLocation is overkill since its only ever going to be passed __FILE__ symbols.  Using LPCTSTR instead would prevent any memory allocation/deallocation problems, but that was a deeper change than I was attempting, and pass by reference is better for the method anyway.  There are other uses of CodeLocation that would benefit from pass by reference but I didn't dive into them.

If these solutions are acceptable, I can have a PR ready in a few days (have to go through my companies internal review process first).

**Comment by gennadiycivil** [comment]
@szetheli Thank you for this report. It is hard to evaluate without actual PR to look at. 
Side note - mcvs2010 is not really a supported complier.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
