### ISSUE TITLE
Tagged 1.8.1 has GOOGLETEST_VERSION 1.9.0

### ISSUE THREAD

**Issue by bdangit** [google/googletest#1816]
First thank you for releasing a long awaited update!

As I am building googletest, I noticed that in the CMake, this package is showing up as `1.9.0` which is definitely not `1.8.1` ref: 
https://github.com/google/googletest/blob/release-1.8.1/CMakeLists.txt#L8. 

This seems to have been set this way in this commit: https://github.com/google/googletest/commit/759ef7c4e9662321548d1c30528c78ecdba2a05d

Should the tag have been 1.9.0 instead of 1.8.1?

**Comment by gennadiycivil** [comment]
You can see in the very same commit that 1.9.0 was previously used , scroll down

**Comment by bdangit** [comment]
@gennadiycivil good catch! and tracing that cookie trail leads to a commit that was done a year ago:

https://github.com/google/googletest/commit/8604c4adac40573f806cfadae44e22f8dfaf212a

**Comment by KindDragon** [comment]
@gennadiycivil Please fix tag or version

**Comment by gennadiycivil** [comment]
@bdangit @KindDragon This is an unfortunate mistake however this makes no practical difference internally (we don't use CMake ). The fact that only now after a year there is a request to fix this also leads me to believe that this not important. 
Can you provide a practical non-theoretical reason to fix this?

**Comment by bdangit** [comment]
As a user who downloads by specific tag, I would have expected the version to be as advertised.  While it is a bit confusing, I can’t think of any technical reason how the version this time could break any test code.  That is unless of the user specified that they must have 1.8.1 via this CMake `find_package(GTest 1.8.1 CONFIG REQUIRED)`, then they would be in for some confusing times. 

Perhaps a recommendation to move forward is to ya e this release really be 1.9.0?

**Comment by KindDragon** [comment]
Or you can release 1.8.2 hotfix with the correct version

**Comment by gennadiycivil** [comment]
@KindDragon @bdangit  There is on-going work in the master , and this is where I may want to do the catch up - when we cut the next release we might want to bump both the GitHub tag and the CMake package to 1.9.1. 
The documentation note about this is welcomeed - please open a PR - but I still don't see practical reason to make the change .

**Comment by bdangit** [comment]
@gennadiycivil sounds reasonable.  I'll review the current README.md and make a PR to place it in there.

**Comment by SoapGentoo** [comment]
@gennadiycivil Added PR for this. Having the correct version is also important for pkg-config, as requiring `1.9` which isn't in distros/generally available yet makes it hard for people to depend on and have pkg-config check their dependencies.

**Comment by bdangit** [comment]
thanks @SoapGentoo / @gennadiycivil!
