### ISSUE TITLE
Support "noexcept" function specifiers

### ISSUE THREAD

**Issue by pepe82sh** [google/googletest#1821]
I've been waiting for this feature for quite a while now, but the original issue #667 has been closed recently due to inactivity. Given the fact that googletest will drop support for c++98 soon, I'd expect that a language feature like `noexcept` should be supported.
#667 was referencing PR #681, which was then dropped in favour of PR #794 and PR #1168. PR #1168 has been dropped in favour of solutions discussed in issue #948, which lead to PR #1532. Unfortunately PR #1532 is close to be merged, but does not include support for noexcept anymore.

**Comment by Hedanito** [comment]
Also in need of this, especially now that noexcept is part of the type system and compilers are starting to flag noexcept mismatches as errors.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
@ugoren ping

**Comment by xyxjin** [comment]
"noexcept" is supported in the latest gmock, or not?

**Comment by kuzkry** [comment]
I don't know since when, but it works now. Syntax is described [here](https://github.com/google/googletest/blob/9311242db422dd6f24c8e764847fe5d70d0d4859/googlemock/docs/cheat_sheet.md#mocking-a-normal-class-mockclass) and all you need to do is to change
```c++
MOCK_METHOD(int, GetSize, (), (const, override)); // override is optional
```
to
```c++
MOCK_METHOD(int, GetSize, (), (const, override, noexcept)); // override is optional
```
Please, close this issue.
