### ISSUE TITLE
CMake 2.8.12's write_basic_package_version_file's VERSION argument isn't optional

### ISSUE THREAD

**Issue by steven-joruk** [google/googletest#1826]
I'm building googletest on CentOS 7, which uses CMake 2.8.12. I'm not sure if it was always required up until this point, or when it became optional.

A simple fix is to pass in "VERSION ${GOOGLETEST_VERSION}" to write_basic_package_version_file.

https://cmake.org/cmake/help/v2.8.12/cmake.html

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
