### ISSUE TITLE
Suggestion for MOCK_METHOD macro, supporting various attributes

### ISSUE THREAD

**Issue by ugoren** [google/googletest#1840]
Here's my suggestion for implementing `MOCK_METHOD`, in a way that:

1. Does not require providing the argument count (covering issue #948, based on PR #1532 ).
2. Supports the existing `_CONST`, `_T` and `_WITH_CALLTYPE` variations, in a single macro.
3. Supports various attributes such as `override` and `noexcept` (covering issue #533 and issue #1821).

The basic usage is `MOCK_METHOD(retval, name, (arg, arg...), attr, attr...)`

Usage:
```
// Replacing existing 8 macro families (special treatment for each attribute):
MOCK_METHOD(int, foo, (int x));                 // MOCK_METHOD1
MOCK_METHOD(int, foo, (int x), const);          // MOCK_CONST_METHOD1
MOCK_METHOD(int, foo, (int x), typename);       // MOCK_METHOD1_T
MOCK_METHOD(int, foo, (int x), Calltype(sth));  // MOCK_METHOD1_WITH_CALLTYPE(sth, ...)
MOCK_METHOD(int, foo, (int x), Calltype(sth), const, typename);  // MOCK_CONST_METHOD1_T_WITH_CALLTYPE(sth, ...)

// Adding various attributes (generic - attributes just passed as-is)
MOCK_METHOD(int, foo, (int a), override);
MOCK_METHOD(int, foo, (int a), noexcept);
MOCK_METHOD(int, foo, (int a), override, noexcept);
```

Comments:
1. The 3 special attributes (`const`, `typename` and `Calltype`) are used identically, but get special treatment by the macro.
2. Any other attribute is placed just before the function body, which is suitable for `override` and `noexcept` (and `final`, though it seems to me pointless).
  a. We can easily implement a white list and fail unknown attributes.
3. The implementation is based on PR #1532.
  a. Adding a `...` parameter for attributes.
  b. Separation between special and generic attributes demonstrated [in my fork](https://github.com/ugoren/googletest/blob/attributes/googlemock/include/gmock/internal/attr_test.c).
  c. Generic attributes handled like [`MOCK_METHOD_ATTRS` in my fork](https://github.com/ugoren/googletest/blob/1d85a390ef75b1102e62e7918aac018a41266f43/googlemock/include/gmock/gmock-generated-function-mockers.h.pump#L279)
4. Any number of attributes (or none) is allowed, up to some limit (pump-generated).
5. The only technical challenge seems to me MSVC's buggy preprocessor. I successfully implemented most of this with MSVC support, and I'm quite sure it's feasible.

**Comment by pepe82sh** [comment]
Looks great and would totally cover #1821 for me. If I get this right your fork is ready to use, so I'll give it a try on Monday 👍 (At least checking this for MinGW on a Windows 10 machine)

**Comment by pepe82sh** [comment]
Okay, then I misunderstood. If you need me to test something I'll be happy to do so. I'd help implementing as well, but my preprocessor magic skills are way below googletest level.

**Comment by ugoren** [comment]
@pepe82sh, [My attributes branch](https://github.com/ugoren/googletest/tree/attributes) now contains a working implementation.
No Windows support yet.

**Comment by gennadiycivil** [comment]
This should be long fixed now, closing
