### ISSUE TITLE
pragma disable warning 5046 on MSVC 2010 causes compile errors

### ISSUE THREAD

**Issue by kachanovskiy** [google/googletest#1848]
https://github.com/google/googletest/blob/258def01a68e3a4d080fee6d4502035218e61e38/googlemock/include/gmock/gmock-matchers.h#L60

1><path>\googletest-master\googlemock\include\gmock/gmock-matchers.h(62): error C2220: warning treated as error - no 'object' file generated
1><path>\googletest-master\googlemock\include\gmock/gmock-matchers.h(62): warning C4616: #pragma warning : warning number '5046' not a valid compiler warning

the warning itself does not exist in this version, and only causes a C4616 warning. however, thanks to explicitly configured -WX (see internal_utils.cmake around line 70), it unfortunately causes build break.

Not sure which MSVC version is the first one to have it, but - could you please at least surround it with 
#if _MSC_VER > 1600, so that MSVC10 could still use googletest master?

Thanks for understanding.

**Comment by gennadiycivil** [comment]
Sorry this version of the compiler is way to old to be supportable .

**Comment by beutlich** [comment]
> Not sure which MSVC version is the first one to have it

This warning is new in Visual Studio 2017 version 15.8 (_MSC_VER == 1915).

Issue should be fixed then if older compilers than VS 2017 15.8 are supported.
