### ISSUE TITLE
googletest build error:use_UnorderedPointwise_with_hash_tables

### ISSUE THREAD

**Issue by yangyiwu** [google/googletest#1849]
Scanning dependencies of target gtest
[ 25%] Building CXX object gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
Linking CXX static library libgtest.a
[ 25%] Built target gtest
Scanning dependencies of target gmock
[ 50%] Building CXX object CMakeFiles/gmock.dir/src/gmock-all.cc.o
cc1plus: warnings being treated as errors
In file included from /data/home/uchannel/walleyang/googletest-1.8.x/googlemock/include/gmock/gmock-spec-builders.h:71,
                 from /data/home/uchannel/walleyang/googletest-1.8.x/googlemock/include/gmock/gmock-generated-function-mockers.h:44,
                 from /data/home/uchannel/walleyang/googletest-1.8.x/googlemock/include/gmock/gmock.h:62,
                 from /data/home/uchannel/walleyang/googletest-1.8.x/googlemock/src/gmock-all.cc:39:
/data/home/uchannel/walleyang/googletest-1.8.x/googlemock/include/gmock/gmock-matchers.h: In member function ‘testing::internal::PointwiseMatcher<TupleMatcher, RhsContainer>::operator testing::Matcher<T>() const’:
/data/home/uchannel/walleyang/googletest-1.8.x/googlemock/include/gmock/gmock-matchers.h:3034: error：‘use_UnorderedPointwise_with_hash_tables’的声明隐藏了‘this’的一个成员
make[2]: *** [CMakeFiles/gmock.dir/src/gmock-all.cc.o] 错误 1
make[1]: *** [CMakeFiles/gmock.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by yangyiwu** [comment]
is any one got the same error?

**Comment by gennadiycivil** [comment]
Thank you very much for this report. Unfortunately there appears to be no actionable information.
