### ISSUE TITLE
On RHEL6 with GCC-4.4.7 googletest-1.8.0 header has trailing comma issue flagged by -pedantic

### ISSUE THREAD

**Issue by marlowa** [google/googletest#1866]
Projects that use googletest 1.8.0 on RHEL with GCC-4.4.7 (the default gcc compiler) cannot use the -pedantic flag with -Werror because it gives a warning in gtest-internal.h at line 1073. The warning is: comma at end of enumerator list.

The enum declaration looks like this:
``
  enum {
    kCheckTypeIsNotConstOrAReference = StaticAssertTypeEqHelper<
        Element, GTEST_REMOVE_REFERENCE_AND_CONST_(Element)>::value,
  };

I think it is simply a case of removing the trailing comma.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
