### ISSUE TITLE
file input option

### ISSUE THREAD

**Issue by prchary** [google/googletest#1873]
Google test has a file input processing logic, but never exposed this option.
it is a working feature which i think should be exposed in help message.

option
--gtest_flagfile = <file path>

Each line in the file should start with a flag or command option which google test can process.

ex.
--gtest_filter=TestClass1.test1:TestClass1.test2
--gtest_filter=TestClass2.test1:TestClass2.test2

Thanks,
Panduranga Pamulaparthy

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
