### ISSUE TITLE
Allow writing a test mixin class

### ISSUE THREAD

**Issue by pitrou** [google/googletest#1879]
One testing style that doesn't seem currently supposed is the test mixin style that is common in e.g. Python.
Abstractly, I would like to:
- define a base class containing various test methods (such as with TEST_F)
- define one (or usually several) derived fixture classes which would be the actual test classes

An example of how it may look like:
```c++

class TestMixin {
 protected:
  int some_value_;
};

TEST_F(TestMixin, SomeTest) {
  ASSERT_EQ(some_value_ % 42, 0);
};

class Test42 : public TestMixin, public ::testing::Test {
 protected:
  void SetUp() override {
    some_value_ = 42;
  }
};

class Test84 : public TestMixin, public ::testing::Test {
 protected:
  void SetUp() override {
    some_value_ = 84:
  }
};

// This test is specific to the Test84 fixture
TEST_F(Test84, OtherTest) {
  ASSERT_EQ(some_value_ / 42, 2);
};

```

The test framework would instantiate `Test42::SomeTest`, `Test84::SomeTest` and `Test84::OtherTest`.

**Comment by gennadiycivil** [comment]
@pitrou It appears that it is already possible to do just that
Please see https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#value-parameterized-tests
and
https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#type-parameterized-tests

**Comment by pitrou** [comment]
@gennadiycivil Not really. It works if all parameterized instances use the exact same tests. But for example I might want to define some tests for a type (or value) and not the others.

**Comment by gennadiycivil** [comment]
Feel free to propose a PR and we can take look.
Thank you
