### ISSUE TITLE
qnx compiling issue

### ISSUE THREAD

**Issue by salugoju** [google/googletest#1884]
struct inheritance inherit = {0};
The above line in gtest-death-test.cc file, line number 1047, in version 1.8.0 and above throws below compiling errors
error: missing initializer for member 'inheritance::pgroup'
error: missing initializer for member 'inheritance::sigmask'
error: missing initializer for member 'inheritance::sigdefault'
error: missing initializer for member 'inheritance::sigignore'
error: missing initializer for member 'inheritance::stack_max'
error: missing initializer for member 'inheritance::policy'
error: missing initializer for member 'inheritance::nd'
error: missing initializer for member 'inheritance::runmask'
error: missing initializer for member 'inheritance::param'

These errors go away with below change
struct inheritance inherit;//  = {0};
memset(&inherit,0,sizeof(inheritance));

**Comment by gennadiycivil** [comment]
Thank you very much for this report. Unfortunately there appears to be no actionable information.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.
