### ISSUE TITLE
Leakable mock object isn't really leaked

### ISSUE THREAD

**Issue by chrisstjohn** [google/googletest#1885]
Leaving aside the dubious use of Mock::AllowLeak(), if it IS used then ~MockObjectRegistry() avoids complaining about the object being left in the registry but it doesn't empty the StateMap before returning.

This means that if the leaked object (which in my case isn't really being leaked - it's just destroyed after MockObjectRegistry) tries to Mock::UnregisterLocked() itself, the object is 'found' in the registry and an attempt is made to remove an item from the partially destroyed std::map. At this point things get a little weird.

I suggest that ~MockObjectRegistry() should call states_.clear() before returning to ensure that any leaked objects really are orphaned - unless I have misunderstood the use case of Mock::AllowLeak() ?

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.
