### ISSUE TITLE
Merge added os specific flag -std=c++11

### ISSUE THREAD

**Issue by whiterabbit963** [google/googletest#1891]
The merge added the line add_definitions(-std=c++11) to the CMakeLists.txt file in a31d6f9.  This causes a warning to get thrown on Windows when compiling (D9002: ignoring unknown option '-std=c++11').

The add_definitions() flag should probably never be used with options like set_target_properties(name PROPERTIES CXX_STANDARD 11) or set(CMAKE_CXX_STANDARD 11).

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
