### ISSUE TITLE
CMakeLists.txt using $<IF:...> syntax when not supported by that version of CMake

### ISSUE THREAD

**Issue by dneto0** [google/googletest#1892]
Example of a broken build when using CMake 3.7:

https://source.cloud.google.com/results/invocations/c18bbd62-5117-4837-8aaa-5665b8e1b3ee/log 

Excerpt:

```
-- Google Mock found - building tests
-- Configuring done
CMake Error:
  Error evaluating generator expression:
    $<IF:$<CONFIG:Debug>,gmockd,gmock>
  Expression did not evaluate to a known generator expression
CMake Error:
  Error evaluating generator expression:
    $<IF:$<CONFIG:Debug>,gmock_maind,gmock_main>
  Expression did not evaluate to a known generator expression

```

The $<IF:...> syntax was introduced in CMake 3.8.
Insteda of $<IF:expr,A,B> we can use $<expr:A>$<$<NOT:expr>:B> construction instead.

**Comment by dneto0** [comment]
The offending commit in Googletest is https://github.com/google/googletest/commit/f5260ae757a681566d8f7d0558b8dc0551036506

**Comment by dneto0** [comment]
cc: @antiagainst

**Comment by gennadiycivil** [comment]
Fixed now I think
