### ISSUE TITLE
Please add a way to identify the executable as a google-test

### ISSUE THREAD

**Issue by janwilmans** [google/googletest#1895]
I propose to standardise a command-line option to identify the executable as a certain kind of test:
it has been adopted by Phil Nash in Catch, and I have proposed this to boost.test (without any response)

see https://github.com/janwilmans/LibIdentify

**Comment by gennadiycivil** [comment]
Unfortunately there does not appear to be enough value to justify the work

**Comment by janwilmans** [comment]
I'm disheartened by this because the work is negligible, however, I see no other option then to stop supporting google test. Thank you for your time and interest.
