### ISSUE TITLE
Feature request: add a way to wait for a debugger to attach to the process

### ISSUE THREAD

**Issue by janwilmans** [google/googletest#1896]
see 
https://github.com/janwilmans/LibIdentify#additional-proposed-extention-for-all-test-frameworks

**Comment by gennadiycivil** [comment]
Not enough value for the work

**Comment by janwilmans** [comment]
I'm disheartened by this because the work is negligible, however, I see no other option then to stop supporting google test. Thank you for your time and interest.

**Comment by Spirit30** [comment]
@gennadiycivil So how do you mean to debug with breakpoints using Visual Studio then?

**Comment by Spirit30** [comment]
I'm using debugging in Visual Studio -> Test Explorer.
