### ISSUE TITLE
1.8.1 said to support pre-C++11 but using C++11 extension "long long"?

### ISSUE THREAD

**Issue by hartwork** [google/googletest#1901]
I'm getting compile errors for 1.8.1 building with Clang 7 and `-Werror -std=c++98`:
```
clang++-7 [..] -pedantic -Werror -std=c++98 [..]
In file included from test/FourSuite.cpp:22:
In file included from /home/travis/.local/include/gtest/gtest.h:59:
In file included from /home/travis/.local/include/gtest/internal/gtest-internal.h:40:
/home/travis/.local/include/gtest/internal/gtest-port.h:2388:9: error: 
      'long long' is a C++11 extension [-Werror,-Wc++11-long-long]
typedef long long BiggestInt;  // NOLINT
        ^
```
Is that a bug?

**Comment by gennadiycivil** [comment]
@hartwork  1.8.1 represents a state of the code that supported pre-C++11 compilers.. This issue never came up in all the compilers that are defined in the testing matrix.  
Note that this is not the same as compiling with new clang and specifically telling this compiler to downgrade to c++98.

**Comment by hartwork** [comment]
Hi! I'm not sure I'm following. If pre-C++11 compilers are said to be supported, I'd expect a compiler that implements nothing C++11 to be able to compile the code. I'd make the CI compile with `-std=c++03 -pedantic -Werror` (which also has a problem with some C99 features used in gtest 1.8.1). What's the benefit of using C++03 with some C++11 features added that pass the current compiler matrix? I get the C99 bits more than the C++11 ones. What do you think?

**Comment by hartwork** [comment]
I realize now that `long long` is a C99 feature as well (not just C++11). So I guess gtest is doing C++03 with some C99 added. My assumption was that pre-C++11 would imply sound C++03 but I see that it's not being said anywhere. So I guess the bug is with me then. Unless you want to add a note on what is expected from those pre-C++11 compilers, this ticket can be closed maybe. What do you think?

**Comment by gennadiycivil** [comment]
@hartwork Thank you for looking into this more. I think it is most pragmatic just to close this issue.

**Comment by Bu11etmagnet** [comment]
The easiest solution is to compile with `-Wno-long-long` or `-Wno-c++11-long-long`
