### ISSUE TITLE
Make error on Linux "error regex_t does not name a type"

### ISSUE THREAD

**Issue by zeFresk** [google/googletest#1909]
Hello,
I'm unable to compile gtest on my desktop :(

I'm downloading it using CMake and building it alongside with my project.
I'm using Ubuntu 18.04 LTS from WSL, the configuration with CMake seems to be working fine, the error occurs when building.

Here are the logs : 
> from [...]/gtest-internal.h:40:0, 
>      from [...]/include/gtest/gtest.h:59
> [...]/google-test/googletest-src/googletest/include/gtest/internal/gtest-port.h:1128:3: error: 'regex_t' does not name a type; did you mean 'regex_h'?
>  regex_t full_regex_;    // For FullMatch()
> [...]/google-test/googletest-src/googletest/include/gtest/internal/gtest-port.h:1128:3: error: 'regex_t' does not name a type; did you mean 'regex_h'?
>  regex_t partial_regex_;    // For PartialMatch()

I tried with clang and gcc, without success, but when I tried on Windows (VS 2017 15.8.5) it worked.
Do you think it comes from my setup or from googletest itself ?

Thank you for your help :)

**Comment by gennadiycivil** [comment]
Looking at [the code ](https://github.com/google/googletest/blob/b3b19a796cbb3222fb3a49daf3f0a9378e8505ad/googletest/include/gtest/internal/gtest-port.h#L1128) is seems that you are building with GTEST_USES_POSIX_RE . I am guessing that <regex.h> is somehow not available on you system or your build does now know how to find it. 
On Windows as you can see in the same code just below, googletest is using simple regex implementation .

**Comment by zeFresk** [comment]
Ok, here I am again.

Yes I already saw that, and today I tested on a real Ubuntu at work (not WSL) using gcc 5.x and still no luck.
Besides I'm sure that <regex> exists and is correctly located because I use it in my main project.

I tried using CC=clang (v6.0.0) or CC=gcc (7.3.0) with no success :(
I checked minutes ago and my CMakeLists and CMakeLists.in are exactly the same as the one used in the README...

For the moment I disabled tests for Linux users but it's still frustrating :(

I don't know if I can post repositories here but you can easily find my project on my profile at "CASM" if you want to test on your configuration.

Thank you for you help, I will try some more things !

**Comment by Bu11etmagnet** [comment]
Since the error is "regex_t does not name a type" and not "fatal: regex.h not found", the problem is not a missing regex.h
@zeFresk , try compiling with `-save-temps` and look at the preprocessor output (.ii file). You can also add the -H switch so the compiler dumps the names of all include files.
My guess is that despite GTEST_USES_POSIX_RE, <regex.h> was not included.

**Comment by zeFresk** [comment]
Well... I'm dumb...
I had a file named regex.h in my own project, renaming it solved the problem.

Thanks to both of you for helping me !
