### ISSUE TITLE
Cannot find Documentation.md

### ISSUE THREAD

**Issue by acebrianjuan** [google/googletest#1920]
Hi,

I am trying to find the _Documentation.md_ file for googletest.
I was expecting to find it under [/googletest/docs/](https://github.com/google/googletest/tree/master/googletest/docs), but it's not there.
It used to be there however. [Here](https://github.com/google/googletest/blob/efd49c2d456bf102d2c179f2c506d81573bde339/googletest/docs/Documentation.md) is the file on commit efd49c2 (Jan 26 2018).

What happened to the file? Where can I find it?

Thank you.

PS: googlemock has its own [_Documentation.md_](https://github.com/google/googletest/blob/master/googlemock/docs/Documentation.md) file under [/googlemock/docs/](https://github.com/google/googletest/blob/master/googlemock/docs/)

**Comment by gennadiycivil** [comment]
@acebrianjuan 
Thank your for this report. The only thing that file did was listing all documentation markdown files for Google Test. It was removed because it was not adding much value and was a burden to maintain.
You are welcome to submit a PR that would restore it if it is important for you
