### ISSUE TITLE
Running cmake --build yields many errors.

### ISSUE THREAD

**Issue by allidoisace** [google/googletest#1922]
I am trying to compile with cmake and when the cmake --build . runs, there are a bunch of errors. Is there something im missing?

**Comment by Bu11etmagnet** [comment]
https://www.chiark.greenend.org.uk/~sgtatham/bugs.html#respect
Unless you tell us what steps did you do, and what errors did you get, there's little chance anyone can tell you what you missed.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. Unfortunately there appears to be no actionable information.
