### ISSUE TITLE
CMake: migrate to target_include_directories and target_link_directories

### ISSUE THREAD

**Issue by jwuttke** [google/googletest#1926]
gtest-1.8.0/CMakeLists.txt still contains the CMake commands include_directories and link_directories that set undesirable global properties, and are therefore deprecated. Please migrate to target_include_directories and target_link_directories.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
