### ISSUE TITLE
GTest porting question

### ISSUE THREAD

**Issue by dmb07** [google/googletest#1928]
We are porting GTest to our project, and we are not using any OS neither POSIX RE support. We are currently commenting the line #428 on the file gtest-port.h to avoid GTEst to look for POSIX RE when WINDOWS OS is not used.

![image](https://user-images.githubusercontent.com/44413815/47384999-7804fd00-d6ce-11e8-8b80-9eb4b241b3b1.jpg)

We want to know if there is a flag or something else that we can configure to avoid commenting this line and modify the code of the GTest, please let us know your comments, thanks!

**Comment by gennadiycivil** [comment]
@dmb07 Could you please explain exactly what your goal is. Is your goal to use googletest without any RE whatsoever?
Thanks

**Comment by dmb07** [comment]
Hi @gennadiycivil,
No, we do want to use RE support, but the GTest internal one, not the POSIX RE support. We already find a way to avoid commenting that line, we just have to set that flag from the build command, thanks for your help!

**Comment by gennadiycivil** [comment]
Good to hear. I am closing this issue.
Thanks!
G
