### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by gmusjha** [google/googletest#1933]
I am trying to compile. My environment is something like this:

OS :CentOS Linux release 7.5.1804 (Core) 
gcc:gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)

I am trying to use cmake by creating build directory and invoking cmake from it. It creates make file. But on make I get following:
I think I am missing some step

In file included from /home/gmusjha/Documents/software/googletest/googletest/include/gtest/internal/gtest-internal.h:40:0,
                 from /home/sjha/Documents/software/googletest/googletest/include/gtest/gtest.h:59,
                 from /home/sjha/Documents/software/googletest/googletest/src/gtest-all.cc:38:
/home/gmusjha/Documents/software/googletest/googletest/include/gtest/internal/gtest-port.h:1200:3: error: identifier ‘nullptr’ is a keyword in C++11 [-Werror=c++0x-compat]
   explicit scoped_ptr(T* p = nullptr) : ptr_(p) {}
   ^
In file included from /home/gmusjha/Documents/software/googletest/googletest/include/gtest/gtest.h:59:0,
                 from /home/sjha/Documents/software/googletest/googletest/src/gtest-all.cc:38:
/home/gmusjha/Documents/software/googletest/googletest/include/gtest/internal/gtest-internal.h:946:11: error: identifier ‘decltype’ is a keyword in C++11 [-Werror=c++0x-compat]
           class Iterator = decltype(::std::declval<const C&>().begin()),
           ^
In file included from /home/gmusjha/Documents/software/googletest/googletest/include/gtest/internal/gtest-internal.h:40:0,
                 from /home/sjha/Documents/software/googletest/googletest/include/gtest/gtest.h:59,
                 from /home/sjha/Documents/software/googletest/googletest/src/gtest-all.cc:38:
/home/gmusjha/Documents/software/googletest/googletest/include/gtest/internal/gtest-port.h:1200:30: error: ‘nullptr’ was not declared in this scope
   explicit scoped_ptr(T* p = nullptr) : ptr_(p) {}
                              ^
/home/gmusjha/Documents/software/googletest/googletest/include/gtest/internal/gtest-port.h:1213:21: error: ‘nullptr’ was not declared in this scope
   void reset(T* p = nullptr) {
                     ^
/home/gmusjha/Documents/software/googletest/googletest/include/gtest/internal/gtest-port.h: In member function ‘T* testing::internal::scoped_ptr<T>::release()’:
/home/sjha/Documents/software/googletest/googletest/include/gtest/internal/gtest-port.h:1209:12: error: ‘nullptr’ was not declared in this scope
     ptr_ = nullptr;
            ^
/home/gmusjha/Documents/software/googletest/googletest/include/gtest/internal/gtest-port.h: In function ‘void testing::internal::FlushInfoLog()’:
/home/gmusjha/Documents/software/googletest/googletest/include/gtest/internal/gtest-port.h:1363:37: error: ‘nullptr’ was not declared in this scope
 inline void FlushInfoLog() { fflush(nullptr); }

**Comment by gennadiycivil** [comment]
Looks like your compilation does not include setting c++11 which may be required by your toolchain. googletest requires C++ 11

**Comment by yuanwentian** [comment]
> Looks like your compilation does not include setting c++11 which may be required by your toolchain. googletest requires C++ 11

I get the same problem. My environment is something like this:

Linux 16.04
g++ 7.3.0
cmake_minimum_required(VERSION 3.8)
set(CMAKE_CXX_STANDARD 17)

I am trying to use cmake by creating build directory and invoking cmake from it. It creates make file. But on **make** command, I get following:

taharabun@ubuntu:~/Projects/RieMO/buildTest$ make
Scanning dependencies of target gtest
[  6%] Building CXX object googletest-build/googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 12%] Linking CXX static library ../../../lib/libgtest.a
[ 12%] Built target gtest
Scanning dependencies of target gtest_main
[ 18%] Building CXX object googletest-build/googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 25%] Linking CXX static library ../../../lib/libgtest_main.a
[ 25%] Built target gtest_main
Scanning dependencies of target constraintTest
[ 31%] Building CXX object test/CMakeFiles/constraintTest.dir/src/constraintTest.cpp.o
In file included from /usr/local/include/gmock/gmock.h:58:0,
                 from /home/taharabun/Projects/RieMO/test/src/constraintTest.cpp:2:
/usr/local/include/gmock/gmock-actions.h: In constructor ‘testing::internal::ByMoveWrapper<T>::ByMoveWrapper(T)’:
/usr/local/include/gmock/gmock-actions.h:505:55: error: ‘move’ is not a member of ‘testing::internal’
   explicit ByMoveWrapper(T value) : payload(internal::move(value)) {}
                                                       ^~~~
/usr/local/include/gmock/gmock-actions.h:505:55: note: suggested alternative: ‘None’
   explicit ByMoveWrapper(T value) : payload(internal::move(value)) {}
                                                       ^~~~
                                                       None
/usr/local/include/gmock/gmock-actions.h: In constructor ‘testing::internal::ReturnAction<R>::ReturnAction(R)’:
/usr/local/include/gmock/gmock-actions.h:539:59: error: ‘move’ is not a member of ‘testing::internal’
   explicit ReturnAction(R value) : value_(new R(internal::move(value))) {}
                                                           ^~~~
/usr/local/include/gmock/gmock-actions.h:539:59: note: suggested alternative: ‘None’
   explicit ReturnAction(R value) : value_(new R(internal::move(value))) {}
                                                           ^~~~
                                                           None
/usr/local/include/gmock/gmock-actions.h: In member function ‘virtual testing::internal::ReturnAction<R>::Impl<testing::internal::ByMoveWrapper<R_>, F>::Result testing::internal::ReturnAction<R>::Impl<testing::internal::ByMoveWrapper<R_>, F>::Perform(const ArgumentTuple&)’:
/usr/local/include/gmock/gmock-actions.h:607:24: error: ‘move’ is not a member of ‘testing::internal’
       return internal::move(wrapper_->payload);
                        ^~~~
/usr/local/include/gmock/gmock-actions.h:607:24: note: suggested alternative: ‘None’
       return internal::move(wrapper_->payload);
                        ^~~~
                        None
/usr/local/include/gmock/gmock-actions.h: In function ‘testing::internal::ReturnAction<R> testing::Return(R)’:
/usr/local/include/gmock/gmock-actions.h:1062:46: error: ‘move’ is not a member of ‘testing::internal’
   return internal::ReturnAction<R>(internal::move(value));
                                              ^~~~
/usr/local/include/gmock/gmock-actions.h:1062:46: note: suggested alternative: ‘None’
   return internal::ReturnAction<R>(internal::move(value));
                                              ^~~~
                                              None
/usr/local/include/gmock/gmock-actions.h: In function ‘testing::internal::ByMoveWrapper<R> testing::ByMove(R)’:
/usr/local/include/gmock/gmock-actions.h:1095:47: error: ‘move’ is not a member of ‘testing::internal’
   return internal::ByMoveWrapper<R>(internal::move(x));
                                               ^~~~
/usr/local/include/gmock/gmock-actions.h:1095:47: note: suggested alternative: ‘None’
   return internal::ByMoveWrapper<R>(internal::move(x));
                                               ^~~~
                                               None
In file included from /usr/local/include/gmock/gmock-spec-builders.h:75:0,
                 from /usr/local/include/gmock/gmock-generated-function-mockers.h:43,
                 from /usr/local/include/gmock/gmock.h:61,
                 from /home/taharabun/Projects/RieMO/test/src/constraintTest.cpp:2:
/usr/local/include/gmock/gmock-matchers.h: In constructor ‘testing::internal::PredicateFormatterFromMatcher<M>::PredicateFormatterFromMatcher(M)’:
/usr/local/include/gmock/gmock-matchers.h:1836:68: error: ‘move’ is not a member of ‘testing::internal’
   explicit PredicateFormatterFromMatcher(M m) : matcher_(internal::move(m)) {}
                                                                    ^~~~
/usr/local/include/gmock/gmock-matchers.h:1836:68: note: suggested alternative: ‘None’
   explicit PredicateFormatterFromMatcher(M m) : matcher_(internal::move(m)) {}
                                                                    ^~~~
                                                                    None
/usr/local/include/gmock/gmock-matchers.h: In function ‘testing::internal::PredicateFormatterFromMatcher<M> testing::internal::MakePredicateFormatterFromMatcher(M)’:
/usr/local/include/gmock/gmock-matchers.h:1880:53: error: ‘move’ is not a member of ‘testing::internal’
   return PredicateFormatterFromMatcher<M>(internal::move(matcher));
                                                     ^~~~
/usr/local/include/gmock/gmock-matchers.h:1880:53: note: suggested alternative: ‘None’
   return PredicateFormatterFromMatcher<M>(internal::move(matcher));
                                                     ^~~~
                                                     None
In file included from /usr/local/include/gmock/gmock-generated-function-mockers.h:43:0,
                 from /usr/local/include/gmock/gmock.h:61,
                 from /home/taharabun/Projects/RieMO/test/src/constraintTest.cpp:2:
/usr/local/include/gmock/gmock-spec-builders.h: In constructor ‘testing::internal::ReferenceOrValueWrapper<T>::ReferenceOrValueWrapper(T)’:
/usr/local/include/gmock/gmock-spec-builders.h:1306:37: error: ‘move’ is not a member of ‘testing::internal’
       : value_(::testing::internal::move(value)) {
                                     ^~~~
/usr/local/include/gmock/gmock-spec-builders.h:1306:37: note: suggested alternative: ‘None’
       : value_(::testing::internal::move(value)) {
                                     ^~~~
                                     None
/usr/local/include/gmock/gmock-spec-builders.h: In member function ‘T testing::internal::ReferenceOrValueWrapper<T>::Unwrap()’:
/usr/local/include/gmock/gmock-spec-builders.h:1312:44: error: ‘move’ is not a member of ‘testing::internal’
   T Unwrap() { return ::testing::internal::move(value_); }
                                            ^~~~
/usr/local/include/gmock/gmock-spec-builders.h:1312:44: note: suggested alternative: ‘None’
   T Unwrap() { return ::testing::internal::move(value_); }
                                            ^~~~
                                            None
/usr/local/include/gmock/gmock-spec-builders.h: In constructor ‘testing::internal::ActionResultHolder<T>::ActionResultHolder(testing::internal::ActionResultHolder<T>::Wrapper)’:
/usr/local/include/gmock/gmock-spec-builders.h:1410:38: error: ‘move’ is not a member of ‘testing::internal’
       : result_(::testing::internal::move(result)) {
                                      ^~~~
/usr/local/include/gmock/gmock-spec-builders.h:1410:38: note: suggested alternative: ‘None’
       : result_(::testing::internal::move(result)) {
                                      ^~~~
                                      None
/usr/local/include/gmock/gmock-spec-builders.h: In member function ‘testing::internal::FunctionMockerBase<F>::Result testing::internal::FunctionMockerBase<F>::InvokeWith(const ArgumentTuple&)’:
/usr/local/include/gmock/gmock-spec-builders.h:1584:5: error: ‘scoped_ptr’ was not declared in this scope
     scoped_ptr<ResultHolder> holder(
     ^~~~~~~~~~
/usr/local/include/gmock/gmock-spec-builders.h:1584:5: note: suggested alternative: ‘linked_ptr’
     scoped_ptr<ResultHolder> holder(
     ^~~~~~~~~~
     linked_ptr
/usr/local/include/gmock/gmock-spec-builders.h:1584:28: error: expected primary-expression before ‘>’ token
     scoped_ptr<ResultHolder> holder(
                            ^
/usr/local/include/gmock/gmock-spec-builders.h:1586:12: error: ‘holder’ was not declared in this scope
     return holder->Unwrap();
            ^~~~~~
/usr/local/include/gmock/gmock-spec-builders.h:1586:12: note: suggested alternative: ‘tolower’
     return holder->Unwrap();
            ^~~~~~
            tolower
test/CMakeFiles/constraintTest.dir/build.make:62: recipe for target 'test/CMakeFiles/constraintTest.dir/src/constraintTest.cpp.o' failed
make[2]: *** [test/CMakeFiles/constraintTest.dir/src/constraintTest.cpp.o] Error 1
CMakeFiles/Makefile2:103: recipe for target 'test/CMakeFiles/constraintTest.dir/all' failed
make[1]: *** [test/CMakeFiles/constraintTest.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gmusjha** [comment]
Please add    set (CMAKE_CXX_STANDARD 11) in

CMakeLists.txt .

After this step I created a build directory and used cmake ../ and make which successfully ran.

________________________________

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by Stolaine** [comment]
I am having this issue in my linux environment 

I have set(CMAKE_CXX_STANDARD 11) in my CMakeLists.txt

But no help.

**Comment by 5ingwings** [comment]
make be you are in the wrong path
cmake ${GTEST_DIR}  GTEST_DIR is the lib's root path

**Comment by Remi-Coulom** [comment]
That change fixes the problem for me:
https://github.com/Remi-Coulom/googletest/commit/2a2b0586ff3a0923322ad415a0a3c04ea47a96e3

**Comment by nmoinvaz** [comment]
I experienced the issue on Windows when including `googletest` as a subdirectory in CMake. I was able to resolve the issue with `-Dgtest_disable_pthreads=ON`. It was attempting to use pthreads which I had installed via `vcpkg` for another project.
