### ISSUE TITLE
clang-7 abi issue?

### ISSUE THREAD

**Issue by jjpepper** [google/googletest#1942]
After upgrading to clang-7 in Debian Stretch, and building a google test executable, we're getting the following errors:

```
/home/mi/source/repos/mi-geometry-framework/miUtilsTest/FileSystemUtilsTest.cpp:17: undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
/home/mi/source/repos/mi-geometry-framework/miUtilsTest/FileSystemUtilsTest.cpp:17: undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()'
/home/mi/source/repos/mi-geometry-framework/miUtilsTest/FileSystemUtilsTest.cpp:17: undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()'

```

The version of gtest I have installed is 1.8.0-6.
Has anyone else tried this?  Is it an abi compatibility issue?

**Comment by sbenzaquen** [comment]
On Mon, Oct 29, 2018 at 6:16 AM Jesse Pepper <notifications@github.com>
wrote:

> After upgrading to clang-7 in Debian Stretch, and building a google test
> executable, we're getting the following errors:
>
> /home/mi/source/repos/mi-geometry-framework/miUtilsTest/FileSystemUtilsTest.cpp:17: undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
> /home/mi/source/repos/mi-geometry-framework/miUtilsTest/FileSystemUtilsTest.cpp:17: undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()'
> /home/mi/source/repos/mi-geometry-framework/miUtilsTest/FileSystemUtilsTest.cpp:17: undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()'
>
>
> The version of gtest I have installed is 1.8.0-6.
> Has anyone else tried this? Is it an abi compatibility issue?
>

This seems like you are building your project using libc++ (clang's STL),
but the googletest prebuilt library you are trying to use was built using
libstdc++ (GCC's STL).
One solution is to build googletest from scratch with your project. Or use
the system library to build your project.

**Comment by jjpepper** [comment]
Oh indeed! Good spot. Yes we want the <filesystem> out of experimental
mode. The gcc one doesn’t have that yet does it?

**Comment by sbenzaquen** [comment]
On Mon, Oct 29, 2018 at 1:55 PM Jesse Pepper <notifications@github.com>
wrote:

> Oh indeed! Good spot. Yes we want the <filesystem> out of experimental
> mode. The gcc one doesn’t have that yet does it?
>

libstdc++ seems to support it already, but you might not have that version
installed.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html

**Comment by gennadiycivil** [comment]
Ping, can we close this
