### ISSUE TITLE
Minor style issue: googlemock README.md

### ISSUE THREAD

**Issue by larvacea** [google/googletest#1947]
"Lets an user extend it by defining new matchers and actions."

should be "Lets a user..."

See, for instance, Chicago Manual of Style section 5.72. Orthography is hard.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by jerryturcios08** [comment]
This issue has been addressed in the [latest commit](https://github.com/google/googletest/commit/879ac092fde0a19e1b3a61b2546b2a422b1528bc).

**Comment by jerryturcios08** [comment]
@gennadiycivil You can close this issue now.
