### ISSUE TITLE
Unable to skip tests in test fixture SetUp()

### ISSUE THREAD

**Issue by sethraymond** [google/googletest#1953]
It appears that using `GTEST_SKIP()` (introduced in #1544, which is a phenomenal feature!) inside of a test fixture does not work, or at the very least is inconsistent. Example:

```c++
class FooTest : public ::testing:Test {
protected:
    void SetUp()
    {
        GTEST_SKIP();
    }
};

TEST_F(FooTest, Foo)
{
    ASSERT_EQ(1, 0);
}
```

Running the unit test will sometimes cause the `Foo` test to skip, and others it will simply fail due to the equality assertion failing.

**Comment by gennadiycivil** [comment]
@sethraymond I tried to duplicate this report but could not do it. Note that your test code is practically identical to the gtest_skip_test.cc. 
Could you please provide a reliable repeatable test for this

**Comment by sethraymond** [comment]
@gennadiycivil When I ran the code in my IDE, I asked it to run the tests 10-50 times each. I found inconsistencies between failure and skips. I'm not sure how to reproduce that loop in code (call `RUN_ALL_TESTS()` in a loop?) I unfortunately cannot get you the actual code as I am out of the office. However, I can try to get it to you in the future.

I looked at `gtest_skip_test.cc` - could the reason be that I am missing the `override` in the `SetUp()` function?

**Comment by aprelev** [comment]
@sethraymond, as I pointed out in [my PR](https://github.com/google/googletest/pull/1544#issue-179454412), skipping does not work in `SetUp()` nor in `TearDown()`; according to @gennadiycivil, this would have been [an unnecessary compication](https://github.com/google/googletest/pull/1544#issuecomment-379763952).

**Comment by aprelev** [comment]
However, after I did some digging, I found [this commit](https://github.com/google/googletest/commit/59f90a338bce2376b540ee239cf4e269bf6d68ad), which promises to honour GTEST_SKIP() in SetUp(). This seems to have been added a couple of weeks after my PR was closed.

**Comment by snarkmaster** [comment]
I think this was likely fixed by https://github.com/google/googletest/commit/59f90a338bce2376b540ee239cf4e269bf6d68ad

So, @sethraymond probably had a version of `googletest` that was a couple of weeks behind trunk.

**Comment by asoffer** [comment]
It seems this was fixed.
