### ISSUE TITLE
QNX Momentics: GoogleMock - Return has value, in function returning void error

### ISSUE THREAD

**Issue by westsiderz** [google/googletest#1978]
Hello All,

I have some issues with GoogleMock when I import it in QNX Momentics IDE. I have already asked this question in StackOverflow, but nobody was able to answer it. In order to spare some copy-paste operations, I will directly give you the link to SO:
[Link:](https://stackoverflow.com/questions/52896055/qnx-momentics-googlemock-return-has-value-in-function-returning-void-error?noredirect=1#comment93336790_52896055)
Hope this is OK.

GoogleMock works fine. My problem is that the IDE shows some errors or warnings (I am not sure exactly what kind are they) and if I commit the project this way, the other developers will be bothered by those errors. 

So maybe if somebody has seen such a behavior I will be glad to hear the possible solution.

Best Regards,
Ahmed

**Comment by gennadiycivil** [comment]
Thank you very much for this report. Unfortunately there appears to be no actionable information.
