### ISSUE TITLE
when EXPECT_NO_THROW fails the test run stop

### ISSUE THREAD

**Issue by meijin007** [google/googletest#1981]
code example:
```
TEST(Tests, 1) {
  EXPECT_TRUE(true)
}

TEST(Tests, 2) {
EXPECT_NO_THROW(throw std::exception)
}

TEST(Tests, 3) {
EXPECT_TRUE(true)
}
```
 - Expected: All tests run, second test fail.
 - Actual: First test run fine, second test run, fail, but never finished, 3rd test never run.

**Comment by gennadiycivil** [comment]
Thank your for this contribution. Could you please elaborate and provide more information  - please check if you compile googletest with exceptions support, please provide information on the system , compiler, etc
As of right now there is not enough information to help you
