### ISSUE TITLE
undefined reference to `Factorial(int)' when compiling sample1_unittest

### ISSUE THREAD

**Issue by huhkru** [google/googletest#1986]
Performed make all on sample1_unittest:

ERROR: sample1_unittest.cc:12: undefined reference to `Factorial(int)'
collect2: error: ld returned 1 exit status
make: *** [sample1_unittest] Error 1

Please help to resolve the issue

**Comment by gennadiycivil** [comment]
Could you please elaborate and provide more information , as it is there is not enough to try to help you

**Comment by gennadiycivil** [comment]
Looks stale
