### ISSUE TITLE
GTestConfig.cmake not getting read by find_package(...)

### ISSUE THREAD

**Issue by jipe4153** [google/googletest#1990]
It seems the *Config.cmake file is not getting read when using ex:
`find_package(GTest REQUIRED)`

This means that on an ubuntu system whenever you install to somewhere other than default location (ex: /usr/local/include) the build will fail, not finding  "gtest/gtest.h". 

You may reproduce by doing:

`cd googletest/`
`cmake -DCMAKE_INSTALL_PREFIX=<SOME_LOCAL_DIR>  .  `
`sudo make install`
`cd other_project/  `
`cmake -DCMAKE_PREFIX_PATH=<SOME_LOCAL_DIR> .  `
`make`

**Comment by jipe4153** [comment]
I've written my own packaging fix that works in my forked repo, let me know if this could be needed as a reference.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.
