### ISSUE TITLE
Files created when building not gitignored

### ISSUE THREAD

**Issue by nrbrook** [google/googletest#1998]
I'm using googletest as a submodule in a cmake project inside CLion. After building the files `googletest-distribution.cbp` and `googlemock/gmock.cbp` are created, and are not gitignored so appear as untracked files in the working copy for the submodule.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
