### ISSUE TITLE
Install with Cmake Documentation

### ISSUE THREAD

**Issue by isidore** [google/googletest#2005]
There needs to be a how to add this to your project documentation.
We've been trying for a while with little success and I'm surprised you don't have this documented. It's step 1 to using your product.

The best I've seen so for online is : https://crascit.com/2015/07/25/cmake-gtest/

Which has a few problem, the main one being it doesn't work.
The ideal install should:

* Not force me to checkin a duplication of the googletest code.
* Work with cmake.
* Be as few lines as possible. ideally 1 line.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by isidore** [comment]
Right, let's point out a few issues with your response.

1) I'm not sure we have a good way of installing, much less a generic one.
2) there does not appear to be a standard place for documentation, much less a installation section 

Here are some clues from the original report that might help for the future
>> We've been trying for a while with little success 
This is an indicator that we don't have a solution to share
>> The best I've seen so for online is : https://crascit.com/2015/07/25/cmake-gtest/
Notice the start of the url isn't part of the official googletest result url, either github or other.

Perhaps you are missing the advantage of beginner mind. My suggestion. Take a c++ who hasn't use google test and watch them install google test into their existing project.: 1 rule, you can't say anything. this can be hard, so you might want to have them video tape themself and then watch it later.

This general process is called "usability testing"
If you'd like a good comparison, have them then do the same with catch2.

**Comment by gennadiycivil** [comment]
Looks stale
