### ISSUE TITLE
Done moving?

### ISSUE THREAD

**Issue by AndrewGaspar** [google/googletest#2012]
Hey, don't mean to be a nag, but it seems like this repo is a bit of a hot potato right now (google -> abseil -> google). It's not a major deal since it redirects, but we have a [spack package](https://github.com/spack/spack/pull/10079) that recently broke due to the hashes for the release tarballs changing (I don't blame you for this, I'm sure you don't view them as a contract). At the same time I updated the canonical URL to the abseil path, but I'm now seeing that I should probably switch it back.

Do you intend to keep it in the google namespace now?

**Comment by gennadiycivil** [comment]
All done moving :-) will stay in google org.
Thank you!
G

**Comment by AndrewGaspar** [comment]
Thanks!
