### ISSUE TITLE
Linker error undefined symbol on MacOS

### ISSUE THREAD

**Issue by sllvm** [google/googletest#2021]
For the below test case in google mock tests directory fails on MacOS Mojave with default Apple clang compiler. Note, this test case passes on Ubuntu Linux default gcc compiler.

TEST(ElementsAreTest, MatchesThreeElementVector) {
        using ::testing::ElementsAre;
        using ::testing::StrEq;
        using ::testing::_;
  vector<std::string> test_vector;
  test_vector.push_back("one");
  test_vector.push_back("two");
  test_vector.push_back("three");

  EXPECT_THAT(test_vector, ElementsAre("one", StrEq("two"), _));
}

Getting below linker error, 
Undefined symbols for architecture x86_64:
  "testing::Matcher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::Matcher(char const*)", referenced from:
      testing::Matcher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&> testing::internal::MatcherCastImpl<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*>::CastImpl<true>(char const* const&, testing::internal::BooleanConstant<true>, testing::internal::BooleanConstant<true>) in insertion_sort.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by sgraham** [comment]
I am also experiencing this problem on trying to update Fuchsia's copy of googletest. 

In particular code like this:

```
std::vector<std::string> contents;
// ...
EXPECT_THAT(contents, ::testing::UnorderedElementsAre(".", "foo", "bar", "baz"));
```

results in 

```
ld.lld: error: undefined symbol: testing::Matcher<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> > const&>::Matcher(char const*)
>>> referenced by gmock-matchers.h:149 (../../third_party/googletest/googlemock/include/gmock/gmock-matchers.h:149)
>>>               host_x64/obj/garnet/public/lib/fxl/files/fxl_unittests.directory_unittest.o:(testing::Matcher<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> > const&> testing::internal::MatcherCastImpl<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> > const&, char const*>::CastImpl<true>(char const* const&, testing::internal::BooleanConstant<true>, testing::internal::BooleanConstant<true>))
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
```

It seems to be related to Matcher thinking it can implicitly convert from const char* to std::string? But it's a bit difficult to bisect to where it broke because of other API changes (TestCase to TestSuite or something)

**Comment by sgraham** [comment]
I found the change in behaviour was introduced at 8e86f67261649621baf39e8c4368ae224c2193f6.
