### ISSUE TITLE
Compiler error C2440 by MOCK_METHODx

### ISSUE THREAD

**Issue by zlogz** [google/googletest#2028]
gmock v1.8.1 will cause compiler error C2440: `gmock\gmock-spec-builders.h(1350): error C2440: 'initializing': cannot convert from 'BSTR *' to 'T *'`

When compile below code with VS2017 on Windows 10:

```cpp
class MockDemo
{
    MOCK_METHOD0(foo, CComBSTR&());
};
```

The reason would be the ATL class `CComBSTR` has a & operator overloading, and cannot adapt with `ReferenceOrValueWrapper`  in file `gmock-spec-builders.h`.

Could you please take a look and fix it on gmock? Actually, gmock v1.7.0 works to above code.

**Comment by gennadiycivil** [comment]
From the front page:
1.8.x Release - the 1.8.x is the last release that works with pre-C++11 compilers. The 1.8.x will not accept any requests for any new features and any bugfix requests will only be accepted if proven "critical"

With that if this is critical for you we would consider a PR

Thanks
G

**Comment by zlogz** [comment]
Many thanks for your kind reply @gennadiycivil .
We'll make a workaround to this issue and looking forward to the new release of 1.9.x
