### ISSUE TITLE
Matchers do not work with noncopyable types

### ISSUE THREAD

**Issue by ADDubovik** [google/googletest#2029]
`#include "gtest/gtest.h"
#include "gmock/gmock.h"

using namespace testing;

class Movable_But_Noncopyable_Type1
{
	public:
		Movable_But_Noncopyable_Type1() = default;
		~Movable_But_Noncopyable_Type1() = default;

		Movable_But_Noncopyable_Type1(const Movable_But_Noncopyable_Type1 &) = delete;
		Movable_But_Noncopyable_Type1(Movable_But_Noncopyable_Type1 &&) = default;

		Movable_But_Noncopyable_Type1& operator=(const Movable_But_Noncopyable_Type1 &) = delete;
		Movable_But_Noncopyable_Type1& operator=(Movable_But_Noncopyable_Type1 &&) = default;
};

class Movable_But_Noncopyable_Type2
{
	public:
		Movable_But_Noncopyable_Type2() = default;
		~Movable_But_Noncopyable_Type2() = default;

		Movable_But_Noncopyable_Type2(const Movable_But_Noncopyable_Type2 &) = delete;
		Movable_But_Noncopyable_Type2(Movable_But_Noncopyable_Type2 &&) = default;

		Movable_But_Noncopyable_Type2& operator=(const Movable_But_Noncopyable_Type2 &) = delete;
		Movable_But_Noncopyable_Type2& operator=(Movable_But_Noncopyable_Type2 &&) = default;
};

class Foo_interface
{
	public:
		virtual void process(Movable_But_Noncopyable_Type1 &&);
		virtual void process(Movable_But_Noncopyable_Type2 &&);
};

class MockFoo : Foo_interface
{
	public:
		MOCK_METHOD1(process, void(Movable_But_Noncopyable_Type1 &&));
		MOCK_METHOD1(process, void(Movable_But_Noncopyable_Type2 &&));
};

TEST(OBK_MessageParserTest, Test01)
{
	MockFoo mockFoo;

	Movable_But_Noncopyable_Type1 something_1;
	EXPECT_CALL(mockFoo, process(testing::TypedEq<Movable_But_Noncopyable_Type1&&>(std::move(something_1))));
	/* error C2280: 'Movable_But_Noncopyable_Type1::Movable_But_Noncopyable_Type1
					(const Movable_But_Noncopyable_Type1 &)': attempting to reference a deleted function */
}

#include "../main.h"`

**Comment by gennadiycivil** [comment]
From the documentation
https://github.com/google/googletest/blob/0614a539f011adfeca365f8c3f6447671bba0e04/googlemock/docs/CookBook.md#mocking-methods-that-use-move-only-types

A few actions (e.g. DoAll) copy their arguments internally, so they can never work with non-copyable objects; you'll have to use functors instead.

**Comment by rburny** [comment]
Matchers must be copyable, so you cannot create them from non-copyable objects. Instead, you need to use `std::cref` as follows:

`EXPECT_CALL(mockFoo, process(std::cref(something_1)));`

There is another related problem, though - currently, the Eq() matcher copies its argument when matching. I have a pending change to fix it; once it is committed, it will be possible to match non-copyable types.
