### ISSUE TITLE
Exception thrown in Gtest .exe after run.

### ISSUE THREAD

**Issue by sajana1994** [google/googletest#2043]
"Exception thrown at 0x00007FF61795F346 in Gtest_Sample.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF." error is coming when we run any test with Singleton pattern. (Gtest_Sample.exe is my sample Gtest application)

We have created one class and get the instance of the class in Setup() later after performing the test in TearDown() we are deleting that instance. 

Result: Test will pass but later we will get a crash with above mentioned error in gtest.internal-inl.h

OS: Windows 10
Compiler:  VC++
Please refer the attached Screenshot and sample project.

[Gtest_Sample.zip](https://github.com/google/googletest/files/2726729/Gtest_Sample.zip)
![error](https://user-images.githubusercontent.com/46372693/50685318-bc9e0480-103e-11e9-9042-4a50b9c0cea5.jpg)

**Comment by gennadiycivil** [comment]
Thank you very much for this report. Unfortunately there appears to be no actionable information. Please explain exactly the code, the environment, what version of Visual Studio, how the googletest has been compiled ( exceptions/no exceptions etc)
