### ISSUE TITLE
Exception thrown in Gtest .exe in gtest-internal-inl.h

### ISSUE THREAD

**Issue by sajana1994** [google/googletest#2056]
VS version: Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
OS: Windows 10
Compiler: VC++

**Problem description:**
We have a global SetUp() and TearDown() derived from testing::Environment from gtest/gtest.h.
In TearDown() we are deleting our singleton instance, after that a crash is happening in gtest-internal-inl.h in **// A function for deleting an object.  Handy for being used as a
// functor.
template <typename T>
static void Delete(T* x) {
  delete x;**

During compilation we aren't getting any error (Compiled using VC++ compiler).Crash happens at the runtime.

Please refer the attached Screenshot and sample project.

![gtesterror](https://user-images.githubusercontent.com/46372693/50811681-86f66580-1335-11e9-9143-20810e386026.png)
[Gtest_Sample.zip](https://github.com/google/googletest/files/2735302/Gtest_Sample.zip)

**Comment by gennadiycivil** [comment]
No community activity , closing. 
The maintainers are not in position to help, we don't use Visual Studio
