### ISSUE TITLE
TYPED_TEST_SUITE: warning about variadic macro

### ISSUE THREAD

**Issue by sergeyext** [google/googletest#2069]
I'm using typed tests as suggested in [documentation](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#typed-tests) and get the following warning:
```
warning: ISO C++11 requires at least one argument for the "..." in a variadic macro
```
Compiler is GCC 7.4.0, -Wall and -Wextra are enabled
Sources are fused with googletest/scripts/fuse_gtest_files.py

Macro definitions (defined for all sources via build system command line):
```
GTEST_HAS_RTTI=0
GTEST_HAS_PTHREAD=0
GTEST_HAS_EXCEPTIONS=0
GTEST_LANG_CXX11=1
```

Repro code:
```
#include <gtest/gtest.h>

template<typename T>
class SomeTest : public ::testing::Test
{
public:
	using InterpolatorType = T;
	using ContainerType = typename InterpolatorType::Container;
};

using TestTypes = ::testing::Types<int>;
TYPED_TEST_SUITE(SomeTest, TestTypes);
```

**Comment by gennadiycivil** [comment]
Anyway, this should be fixed now
