### ISSUE TITLE
What python version is supported/required for scripts?

### ISSUE THREAD

**Issue by LebedevRI** [google/googletest#2075]
The *.py scripts all seem to say `#!/usr/bin/env python`.
This doesn't work so well on e.g. redhat:
```
[  200s] + /usr/lib/rpm/redhat/brp-mangle-shebangs
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/xcode/Scripts/versiongenerate.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/test/googletest-uninitialized-test.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/test/googletest-catch-exceptions-test.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** WARNING: ./usr/share/googletest-source/googletest/test/gtest_xml_test_utils.py is executable but has empty or no shebang, removing executable bit
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/test/gtest_xml_output_unittest.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/test/googletest-throw-on-failure-test.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** WARNING: ./usr/share/googletest-source/googletest/test/gtest_test_utils.py is executable but has empty or no shebang, removing executable bit
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/test/googletest-color-test.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/test/googletest-break-on-failure-unittest.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/test/googletest-output-test.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/test/gtest_testbridge_test.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/test/gtest_xml_outfiles_test.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/test/googletest-list-tests-unittest.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/test/gtest_help_test.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/test/googletest-shuffle-test.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/test/googletest-filter-unittest.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/test/googletest-env-var-test.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/scripts/pump.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/scripts/gen_gtest_pred_impl.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/scripts/release_docs.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] mangling shebang in /usr/share/googletest-source/googletest/scripts/gtest-config.in from /bin/sh to #!/usr/bin/sh
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/scripts/upload_gtest.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/scripts/upload.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googletest/scripts/fuse_gtest_files.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googlemock/test/gmock_leak_test.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** WARNING: ./usr/share/googletest-source/googlemock/test/gmock_test_utils.py is executable but has empty or no shebang, removing executable bit
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googlemock/test/gmock_output_test.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] mangling shebang in /usr/share/googletest-source/googlemock/scripts/gmock-config.in from /bin/sh to #!/usr/bin/sh
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googlemock/scripts/generator/cpp/gmock_class_test.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googlemock/scripts/generator/cpp/tokenize.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googlemock/scripts/generator/cpp/gmock_class.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googlemock/scripts/generator/cpp/ast.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googlemock/scripts/generator/cpp/utils.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googlemock/scripts/generator/cpp/keywords.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googlemock/scripts/generator/gmock_gen.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googlemock/scripts/fuse_gmock_files.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googlemock/scripts/upload_gmock.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googlemock/scripts/upload.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
[  200s] *** ERROR: ambiguous python shebang in /usr/share/googletest-source/googlemock/scripts/gmock_doctor.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
```
So, are these scripts python2 or python3 already? Can the version be hardcoded?
I can submit a patch to mass-replace, but i'm not sure of the direction,
and i don't think all that has test coverage.

**Comment by LebedevRI** [comment]
> This seems to be a problem in your particular environment.

Eh, no.
That is a diagnostic output of `/usr/lib/rpm/redhat/brp-mangle-shebangs`,
which is run when producing an RPM with the googletest *sources*.

> As a side note the scripts are mostly python2 .

Great. Can that version be hardcoded in them?

**Comment by gennadiycivil** [comment]
It would help if you explained what the task is. Sounds like you are
packaging googletest for redhat?

**Comment by LebedevRI** [comment]
> It would help if you explained what the task is.

Sure.

> Sounds like you are packaging googletest for redhat?

Kind of.
I'm using googletest in [my project as testing framework](https://github.com/darktable-org/rawspeed/tree/develop/test).
I'm following "build with the same flags as the actual code",
and following the [Incorporating Into An Existing CMake Project](https://github.com/google/googletest/blob/master/googletest/README.md#incorporating-into-an-existing-cmake-project) path.

Naturally, for that i need the source codes of the google test.
Since the project is being built on OBS "as a CI" on https://build.opensuse.org/package/show/graphics:darktable:master/rawspeed,
the sources are packaged on https://build.opensuse.org/package/show/graphics:darktable:master/googletest-source

And if i try to enable building of that src package for Fedora_Rawhide,
i get that error i showed in the initial post. That error is self-explanatory.
It simply says that the python scripts don't specify the python version they are using.
Simply hardcoding the python version will fix the issue.

Does that make sense?

**Comment by gennadiycivil** [comment]
Hard-coding python version may fix the issue for this particular environment and will break countless other environments unfortunately. googletest is popular and used on a variety of platforms.

Personally I would not bother trying to package an RPM, just build from source

**Comment by LebedevRI** [comment]
> Hard-coding python version may fix the issue for this particular environment and will break countless other environments unfortunately.

And it is as likely to be broken on some other platforms already.

I think i'm failing to convey the main problem here.
These scripts do not specify the python version they expect.
Do they all support both the python2 and python3?
If not, do you understand that they only work because the python symlink
just happens to point to the python version expected by the scripts?
As in, if they expect python2, and one bright day this python symlink
starts pointing to python3, all these scripts will just silently break?

> googletest is popular and used on a variety of platforms.
> 
> Personally I would not bother trying to package an RPM, just build from source - if you are just working on your personal project.

I am building it from source, that is kinda the root "problem" here.
That is the only sane way to get these sources there, that's the thing.

**Comment by LebedevRI** [comment]
I'm saying that "potatoes grow in soil", and you are saying "no way, moon orbits earth".
The point i was trying to make, about not specifying python version, was missed completely.
Ok great, not my project.

**Comment by eli-schwartz** [comment]
@LebedevRI I would argue you've sort of missed the point why /usr/bin/python might or might not be bad. There are better arguments to make, but honestly, I would not be convinced by your argument either.

**Comment by eli-schwartz** [comment]
@gennadiycivil,

This is not about what Fedora might do, and I have equally no idea what rpm might do.

On the other hand, your shebangs are unarguably a problem -- because the Python Software Foundation says they are a problem and says you should not do that.

Please read PEP 394: https://www.python.org/dev/peps/pep-0394/
Then make this repository compliant with the PEP.

The program /usr/bin/python2 is required to exist on all recent distributions of python2, and the program /usr/bin/python3 is required to exist on all past and present versions of python3. This is for the purpose of portability. The program /usr/bin/python is intended to be a vendor choice, and may point to either python2 or python3, and must not be relied on.

**Comment by eli-schwartz** [comment]
> Hard-coding python version may fix the issue for this particular environment and will break countless other environments unfortunately. googletest is popular and used on a variety of platforms.

Can you clarify, what supported platforms for googletest you believe do not have the python2 command? Those platforms surely predate PEP 394, are you referring to for example end-of-life versions of Debian? I don't think that you should support end-of-life versions of Debian!

**Comment by CentUser** [comment]
Found the same error in cmake, while packaging using cpack generating rpm packages, the shabang is actually /usr/libexec/platform-python, perhaps this is the way the developers found to diminish the difference between python2 and python3, yet,  seems little problem.
I have not find the way to work this out.
