### ISSUE TITLE
redefinition of function Ignored Value

### ISSUE THREAD

**Issue by Stolaine** [google/googletest#2076]
While running "make" command to build wav2letter i ran this error.

[cat.txt](https://github.com/google/googletest/files/2791419/cat.txt)

the error is saying that it is a redefinition of error
one in /usr/local/include/gtest/internal/gtest-internal.h:111:7
other in /usr/include/gmock/internal/gmock-generated-internal-utils.h:55:7

please help

**Comment by EricWF** [comment]
It looks like you have two distinct versions of googletest/googlemock installed.

Is there a `/usr/include/gtest` directory?
Is there a `/usr/local/include/gmock` directory?

I would try removing your installations for both libraries, and then reinstalling googletest.

**Comment by Stolaine** [comment]
thanks the issue is resolved
