### ISSUE TITLE
No hierarchy

### ISSUE THREAD

**Issue by alf-p-steinbach** [google/googletest#2080]
The primer says

> Tests should be well organized and reflect the structure of the tested code. googletest groups related tests into test cases that can share data and subroutines.

Essentially, what that says is "SHOULD be well organized, but no support for that, sorry".

My code is usually structured hierarchically. There are libraries and hierarchies of folders within libraries. It's sort of insane to not be able to likewise structure the set of tests.

I would also like to be able to group tests via more free-form tags.

The above is sort of ABSOLUTE NEED functionality that I was very disappointed to realize isn't there in Google Test. More esoteric just nice-to-have functionality request: In a science-fiction like scenario a test explorer would support checking if all common ways to test something, in a set S, had been all applied to every test case in a group G. The underlying test framework would have to be support the data in some way. Maybe it can be done just via tags.

**Comment by aparks5** [comment]
Can you give an example? I think I've hit the same issue with derived fixtures but I'm not sure it's not a PEBCAK error.

**Comment by gennadiycivil** [comment]
Thank you for this report. I would advise to take a look at how googletest's own unit tests are organized. As it stands there is no actionable information in this issue.

**Comment by gennadiycivil** [comment]
Looks stale
