### ISSUE TITLE
Should report the source file location of the TEST that throws an exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#209]
```
When a test is run with --gtest_catch_exceptions and it throws an exception, 
Google Test currently provides no information about its location. It should 
report the location of the TEST that threw the exception in the TestInfo 
class and print it in the failure message.
```

Original issue reported on code.google.com by `vladlosev` on 21 Oct 2009 at 10:51

**Comment by nioncode** [comment]
Are there any plans to implement this? Apparently, a patch for this was in #16, but was declined.

**Comment by gennadiycivil** [comment]
@nioncode please feel free to submit a PR to be considered

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
