### ISSUE TITLE
Feature request: ASSERT_EQ for helper functions with AssertionResult

### ISSUE THREAD

**Issue by AlexanderLanin** [google/googletest#2095]
Hi,

I'll not even take my current problem, but simply the one from [documentation](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#using-a-function-that-returns-an-assertionresult)

The problem is that this code doesn't give sufficient information on what happened.
```
bool IsEven(int n) {
  return (n % 2) == 0;
}
```

So the current approach is to write:
```
::testing::AssertionResult IsEven(int n) {
  if ((n % 2) == 0)
     return ::testing::AssertionSuccess();
  else
     return ::testing::AssertionFailure() << n << " is odd";
}
```

Here is my suggestion - naming to be improved ;-)
```
::testing::AssertionResult IsEven(int n) {
   ASSERTRESULT_EQ(n % 2, 0);
   return ::testing::AssertionSuccess();
}
```

I know the difference in this small example is marginal. But it really makes sense for more complex examples. The problem I'm having is that you need to manually write all the output code, here is some "example":
```
  if (lhs != rhs)
     return ::testing::AssertionFailure() << ::testing::PrintToString(lhs) << " is not equal to " << ::testing::PrintToString(rhs);
```
which is even more annoying if lhs and rhs are functions... you need temporary variables... it gets messy.

I'm currently achieving the above proposal in my code via:
```
::testing::AssertionResult assertionFailureFromStr(const char* errMsg) {
  return ::testing::AssertionFailure() << errMsg;
}

#define ASSERTRESULT_EQ(lhs, rhs) \
  GTEST_PRED_FORMAT2_(::testing::internal::EqHelper<GTEST_IS_NULL_LITERAL_(lhs)>::Compare, \
    lhs, rhs, return assertionFailureFromStr)
```

P.S. EXPECT instead of ASSERT would also be interesing, but I'm not sure it's possible.

**Comment by dribeas** [comment]
While "expect" semantics can be implemented it may not be simple enough, it would depend on having a known `AssertionResult` variable that is set to be failure if the check fails for the first time and keeps adding the "error reports", at the end of the function if that has been set you return it, otherwise return `AssertionSuccess()`.

**Comment by asoffer** [comment]
Apologies for the delay. The bar for new macro APIs is quite high. Given that this can mostly be achieved with a function, and that adding would open the door to NE, LT, etc versions, I am going to close this as something we do not want to implement as part of GoogleTest. If you feel strongly, we may be able to have a conversation as part of a pull request.
