### ISSUE TITLE
misspelling may happen when using “SetUpTestCase” or “TearDownTestCase”

### ISSUE THREAD

**Issue by rezaebrh** [google/googletest#2122]
If we misspell for example `SetUpTestcase `instead of `SetUpTestCase`, no error/warning will be shown.
But this mistake may happen frequently. Although for `SetUp `and `TearDown `(Because they are virtual) we can use `override `keyword and any misspell will cause error but for `SetUpTestCase `and `TearDownTestCase `there is no similar solution.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
Closing

**Comment by rezaebrh** [comment]
@gennadiycivil Thanks
