### ISSUE TITLE
CMake variable GOOGLETEST_VERSION is fixed, not computed from non-CMake-specific information

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [google/googletest#2124]
Opening issue as approved by maintainer on #2089 .

# Current state

CMake variable GOOGLETEST_VERSION is fixed, not computed from non-CMake-specific information, see line below:

https://github.com/google/googletest/blob/ea43be9d1a781b73dbd573954ee4a371c233a583/CMakeLists.txt#L4

# Consequence

As a consequence, whenever googletest version number changes, this file has to be changed, too.

This would be a non-issue if that line was the ["single, unambiguous, authoritative representation"](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

The reality is googletest maintainers do not use CMake at all. CMake is completely community supported for googletest. bazel is main release mechanism.

If we do nothing about this, people building using CMake will get wrong version information as soon as version changes, until someone fixes that each time.

# Solution

It is possible in CMake to automatically compute the value of the variable, based on `git describe`.
For example, this answer: https://stackoverflow.com/a/38836941

Best solutions are those that keep maximum portability (avoid making unnecessary assumptions about CMake-time platform).

As a side note, it would be best to add some comments on top of the CMakeLists.txt to make clear that bazel is primary build system and CMake is community supported.

I may do this some time in the future, but don't hold your breath. Anyone can offer a PR, too.

**Comment by xilaraux** [comment]
Can I help with that?

**Comment by ngie-eign** [comment]
This is true and gets more annoying when dealing with autotools-based builds as well.

It would be nice if these things were consistent.

**Comment by gennadiycivil** [comment]
https://github.com/google/googletest/commit/703bd9caab50b139428cea1aaff9974ebee5742e
