### ISSUE TITLE
Googlemock moveable function arguments are broken

### ISSUE THREAD

**Issue by baylesj** [google/googletest#2130]
After following the [CookBook](https://github.com/google/googletest/blob/master/googlemock/docs/CookBook.md#mocking-methods-that-use-move-only-types) guide for using move-only arguments in googlemock, I am still unable to get moveable function arguments working.

I created a test.cc file that has the exact code from the CookBook file, and on both g++ and clang I ge the following error:

```
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:2476:3: note: copy constructor is implicitly deleted because 'unique_ptr<Buzz, std::__1::default_delete<Buzz> >' has a user-declared move constructor
  unique_ptr(unique_ptr&& __u) noexcept
```

This is broken on tags 1.8.0, 1.8.1, and HEAD.

I have attached both my test.cc file and the full compiler output:
 
[Repro.zip](https://github.com/google/googletest/files/2871493/Repro.zip)

**Comment by cmumford** [comment]
Hi @baylesj: I think that maybe the code where you got this from in the [cookbook](https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md#mocking-methods-that-use-move-only-types) has an error. I believe that:

```c++
EXPECT_TRUE(mock_buzzer_.ShareBuzz(MakeUnique<Buzz>(AccessLevel::kInternal)), 0);
```

should really be:

```c++
EXPECT_TRUE(mock_buzzer_.ShareBuzz(MakeUnique<Buzz>(AccessLevel::kInternal, 0));
```

I'll submit a PR for that.

Also, in test.cc you seem to have two lines of code that seem to be leftover from a prior experiment. This should be removed:

```c++
  virtual void Foo(std::unique_ptr<int> movable_argument) = 0;
};
```

So, after making these two changes your test app seems to work. Can you confirm?

**Comment by baylesj** [comment]
confirmed, thanks!
