### ISSUE TITLE
The primer indexes arrays out of their range

### ISSUE THREAD

**Issue by dspinellis** [google/googletest#2140]
In the following example provided in the provided [primer](https://github.com/google/googletest/blob/master/googletest/docs/primer.md), if the size of `x` is larger than the size of `y`, the indexing of `y` will fail.

```c++
 ASSERT_EQ(x.size(), y.size()) << "Vectors x and y are of unequal length";

for (int i = 0; i < x.size(); ++i) {
   EXPECT_EQ(x[i], y[i]) << "Vectors x and y differ at index " << i;
 }
```

**Comment by gennadiycivil** [comment]
Done

**Comment by projedi** [comment]
Sorry for intruding, I'm not sure that 

> if the size of `x` is larger than the size of `y`, the indexing of `y` will fail

will happen. The example given uses `ASSERT_EQ(x.size(), y.size())` before indexing into the arrays. `ASSERT*`  family of macro emit `return;` when the condition fails. So, the `for` loop won't even execute if `x` and `y` sizes are different.

Could the example benefit from a comment instead?
```cpp
ASSERT_EQ(x.size(), y.size()) << "Vectors x and y are of unequal length";

// Note, that x and y sizes are the same here (ASSERT from above would've interrupted
// the test immediately, if that was not the case), so we can safely index y here.
for (int i = 0; i < x.size(); ++i) {
  EXPECT_EQ(x[i], y[i]) << "Vectors x and y differ at index " << i;
}
```

Or am I missing something?

**Comment by dspinellis** [comment]
You're right, if  the two code parts are used together and the `ASSERT_EQ`  stops the test, the `for` loop will not be executed.  However, this is a subtle side-effect, and people can miss it; see e.g. [this case](https://github.com/rowungiles/heckel_diff/blob/master/tests/algorithm_tests.cpp#L19) where the `ASSERT_EQ` has been turned into an `EXPECT_EQ`.
