### ISSUE TITLE
Fix `-Wsign-conversion` issues with clang

### ISSUE THREAD

**Issue by ngie-eign** [google/googletest#2146]
Some downstream consumers of googletest compile with clang and use `-Wsign-conversion` (or in the case of https://github.com/jcarpent/pinocchio-ceres/issues/1, `-Wconversion`, which is a superset of `-W*conversion` warnings).

In order to unbreak their CI pipelines, `-Wsign-conversion` was explicitly ignored in #2137. It's in the project's best interest to not ignore these issues, however, so they should be fixed.

**Comment by ngie-eign** [comment]
@gennadiycivil: I'll work on this.

CC: @FlashSheridan, @jcarpent

**Comment by gennadiycivil** [comment]
@ngie-eign Thank you for your help with this. The -Wsign-conversion is a compiler warning that we should support.

I suggest the following:
1) Create a branch with CI configuration that includes this warning
2) Do a small change that just addresses a few cases, send this for review so we can look internally and make sure we are on the right path 
3) Once this small change has been reviewed, approved , do more changes. 

Let me know if this is OK
Thanks again
G
