### ISSUE TITLE
How do I integrate googletest into my configure script?

### ISSUE THREAD

**Issue by nikolas** [google/googletest#2149]
I have `GTEST_DIR = /usr/src/googletest/googletest` in my test directory's Makefile, but this path shouldn't be hardcoded. This is just where Debian puts its googletest package.

Googletest isn't designed to be used as a pre-compiled library, so I don't know how to use `pkg-config` to find its installed path.

How do I find out where a user has installed googletest, in the most portable way?

**Comment by Chukak** [comment]
Hi!
On most systems, **`GTEST_DIR`** will be **`/usr/src/googletest/`**.
You can verify that this path exists.
If the specified path doesn't exist, you can run the command: 
**`dpkg -L googletest | grep -Po '^.*/googletest/' | head -1`**
This will give you a path to the googletest directory, if googletest was installed in system.

You can also try other commands:
* **`locate -i '*googletest/googletest'`**
* **`find / -maxdepth 5 -regex ".*/googletest/googletest" 2>&1 | grep -v "Permission denied"`** 
 `-maxdepth` may be less for better performance.

**Comment by nikolas** [comment]
It looks like integrating with CMake is actually the recommended way of using Googletest now, so I'm closing this. https://github.com/google/googletest/tree/master/googletest#legacy-build-scripts
