### ISSUE TITLE
googletest/test/gtest_unittest.cc: CharsToIndices(..) implementation seems sketchy

### ISSUE THREAD

**Issue by ngie-eign** [google/googletest#2171]
Looking at this code when trying to resolve #2146, I am a bit puzzled by what the purpose is for this method and/or whether or not it can be redone in a simpler manner:
```
3475 std::vector<size_t> CharsToIndices(const std::string& str) {
3476   std::vector<size_t> out;
3477   for (size_t i = 0; i < str.size(); ++i) {
3478     out.push_back(str[i]);
3479   }
3480   return out;
3481 }
```

I feel like there's a bit of a misunderstanding in terms of how char arrays, std::strings, and std::vectors work. I know how to make it simpler in C, but I need to look into what the intent of the writer was, since the purpose is obfuscated.

**Comment by ngie-eign** [comment]
```
$ git log b54098a9a^..b54098a9a
commit b54098a9abade957ab3c4e94ae5e5225ef0015a4
Author: kosak <kosak@google.com>
Date:   Mon Jul 28 21:54:50 2014 +0000

    Expand equality failure messages with a by-line diff.
```
Hmm...

**Comment by ngie-eign** [comment]
Hmm.. so the purpose is the vectorize a string as individual characters. I think the choice of type for the vector is a bit... interesting; it seems incorrect using a 64-bit long for a 8~32-bit character.

**Comment by asoffer** [comment]
It's true, `size_t` is wider than is necessary, but it's also is not a particularly important. Using a smaller type is not necessarily faster (it is necessarily smaller) though I do not believe performance is particularly important here, espeically given the lack of `out.reserve(str.size())`.
