### ISSUE TITLE
Warning: private field 'old_crtdbg_flag_' is not used

### ISSUE THREAD

**Issue by twam** [google/googletest#2179]
When building gtest under Windows with clang 7.0.01 and target x86_64-pc-windows-gnu it fails with

> In file included from .../googletest/googletest/src/gtest-all.cc:45:
> .../googletest/googletest\src/gtest-port.cc:411:7: warning: private field 'old_crtdbg_flag_' is not used [-Wunused-private-field]
>   int old_crtdbg_flag_;
>       ^

**Comment by ngie-eign** [comment]
This issue can be closed, since the PR was merged.

**Comment by oshan1998** [comment]
Make it as public variable if this you encounter this problem " field 'old_crtdbg_flag_' is not used [-Werror,-Wunused-private-field]"
