### ISSUE TITLE
Fatal failures in SetUpTestSuite

### ISSUE THREAD

**Issue by NikolausDemmel** [google/googletest#2187]
I tried to look for an answer, but couldn't find anything.

Is there a canonical way to indicate fatal failure in `SetUpTestSuite` such that all tests of the suite are not run and marked as failed? In my example, I load some data from disk in `SetUpTestSuite` and want to make sure the tests don't run, but are failed, when there is a issue with IO or parsing the data.

It's not hard to implement this manually (see below), but I feel like there should be an inbuilt mechanism (first thing I tried was `ASSERT_TRUE(...)` inside `SetUpTestSuite` instead of my `check_setup`, but that doesn't have the desired effect).

```cpp
class FooTest : public ::testing::Test {
 protected:
  static void check_setup(bool condition) {
    if (!condition) {
      setup_ok_ = false;
      throw std::runtime_error("FooTest::SetUpTestSuite failed");
    }
  }

  static void SetUpTestSuite() {
    // load data
    check_setup(data_.load());

    // execute the following only if the data loaded ok
    check_setup(data_.prepare());
  }

  void SetUp() override { ASSERT_TRUE(setup_ok_); }

  static bool setup_ok_;
  static FooData data_;
};

bool FooTest::setup_ok_ = true;
FooData FooTest::data_ {};

TEST_F(FooTest, Bar) {
  // test succeeds only if data loaded ok; otherwise, it doesn't run and is marked as failed 
  SUCCEED();
}
```

**Comment by AbelHu** [comment]
@NikolausDemmel Are you sure that your SetUpTestSuite works? I am a newbie to gtest and found that only SetUpTestCase works.

**Comment by NikolausDemmel** [comment]
> Are you sure that your SetUpTestSuite works? I am a newbie to gtest and found that only SetUpTestCase works.

Yes it works, at least with the gtest version I'm using (recent master). A quick search reveals that these names were recently changed, so you might have to use `SetUpTestCase` if you are using an older gtest. 

See https://stackoverflow.com/questions/54468799/google-test-using-setuptestsuite-doesnt-seem-to-work#comment95773772_54483163

**Comment by AbelHu** [comment]
Thanks for the information, @NikolausDemmel . I am using the latest release v1.8.1. It seems like that the change has not been released.

**Comment by gennadiycivil** [comment]
@NikolausDemmel Thank you for this question. There isn't a strictly canonical way because there is such a variety of ways that the TestSuite could be set up.

**Comment by NikolausDemmel** [comment]
@gennadiycivil, thanks for your reply. Then I guess this could be a feature request :-). Being able to use the `ASSERT` macros in the SetUpTestSuite and have them abort and fail the corresponding tests would be convenient. But as noted, it can be worked around, so maybe its low priority.

Feel free to close the issue if you feel like tracking the "feature request" isn't useful.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by MatthieuHernandez** [comment]
I have almost the same problem and I did this :
```cpp
class Cifar10Test : public testing::Test {
protected :
    static void SetUpTestCase() {
        Cifar10 dataset;
        data = move(dataset.data);
    }

    void SetUp() override {
        ASSERT_TRUE(data) << "Don't forget to download dataset";
    }

    static unique_ptr<Data> data;
};

unique_ptr<Data> Cifar10Test::data = nullptr;

TEST_F(Cifar10Test, loadData) {
    // Test 1
}

TEST_F(Cifar10Test, trainNeuralNetwork) {
    // Test 2
}
```

**Comment by DavidPerretSN** [comment]
I'm quite confused about the fix that closed this issue.

It's a good thing that it skips the test, preventing it to crash or create other issues, but the console output seems to display the "failure" correctly: 

[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from IssueRepro

[  PASSED  ] 0 tests.
[  SKIPPED ] 1 test, listed below:
[  SKIPPED ] IssueRepro.ReturnIsCorrect
[  FAILED  ] 0 tests, listed below:
 0 FAILED TESTS
[  FAILED  ] IssueRepro: SetUpTestSuite or TearDownTestSuite
 **1 FAILED TEST SUITE**

But I can find no mention of this failed test suite in the xml output... there is indeed the skipped = 1 indication, but I have no way to get back from my xml that the test suite failed.

<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="1" **failures="0"** disabled="0" **errors="0"** time="0.003" timestamp="2021-10-06T16:50:51.997" name="AllTests">
  <testsuite name="IssueRepro" tests="1" **failures="0"** disabled="0" skipped="1" **errors="0"** time="0" timestamp="2021-10-06T16:50:51.999">
    <testcase name="ReturnIsCorrect" status="run" result="skipped" time="0" timestamp="1970-01-01T00:00:00.000" classname="IssueRepro">
      <skipped message="xxx\myTests.cpp:33&#x0A;"><![CDATA[xxx\myTests.cpp:33
]]></skipped>
    </testcase>
  </testsuite>
</testsuites>


Shouldn't the XML report some errors when we had an assert that was triggered in the SetUpTestSuite...

**Comment by DavidPerretSN** [comment]
@dinord Any opinion on this ? Is it done this way by design ?
