### ISSUE TITLE
gtest mistakenly reports tests passed while they should not.

### ISSUE THREAD

**Issue by honghaoli** [google/googletest#2197]
I spent some time to figure out [this problem](https://stackoverflow.com/questions/55330525/googletest-never-fails-where-it-should-with-bazel-test-but-works-with-cmake), where gtest mistakenly reports all the tests passed while apparently some of them should not, but gtest_main gives the correct result.
*(I use **bazel** to build the project)*

I have to change
```
"//bazel_build/googletest:gtest",
```
in the ```BUILD``` file into
```
"//bazel_build/googletest:gtest_main",
```
to make things work.

**BUT**
I'm still confused! 
If the ```gtest``` does not work there, it should at least fail the build or throw error/warnings. It should never say:
```
Executed 1 out of 1 test: 1 test passes.
```
as the output.

I consider it as a bug.

**Comment by sbenzaquen** [comment]
If your binary built with `:gtest` it means you already had a `main()`. This means that linking against `:gtest_main` now has 2 `main()` functions which is an ODR violation and has undefined behavior.

Now, as to why it "passed" without `:gtest_main", are you sure the tests were actually run?
Did you check the console output to be sure that the tests ran?

If you write your own `main`, you have to:
 - Initialize the library by calling `testing::InitGoogleTest(...)`
 - Run the tests by calling `RUN_ALL_TESTS()`
See https://github.com/google/googletest/blob/master/googletest/docs/primer.md#writing-the-main-function

**Comment by honghaoli** [comment]
Thanks for the comment!

> If your binary built with `:gtest` it means you already had a `main()`. This means that linking against `:gtest_main` now has 2 `main()` functions which is an ODR violation and has undefined behavior.
> 
I do not have my own main function and use the :gtest.

> Now, as to why it "passed" without `:gtest_main", are you sure the tests were actually run?
> Did you check the console output to be sure that the tests ran?
> 
So I guess my tests did not run. My concern is: why should the output says the "test passed" if there is no main function defined. It should fail the build or give warnings. I thought this could be improved since people may mistakenly use :gtest without their main function and thought the test passed.
The reason I am picky about this is, I did use some internal version of those packages in somewhere, and the build will fail for my case there.

> If you write your own `main`, you have to:
> 
> * Initialize the library by calling `testing::InitGoogleTest(...)`
> * Run the tests by calling `RUN_ALL_TESTS()`
>   See https://github.com/google/googletest/blob/master/googletest/docs/primer.md#writing-the-main-function

**Comment by sbenzaquen** [comment]
A binary will not link if you are missing `main`. `:gtest` does not include a `main` function. If your binary was building and running it is because you had some `main` function.

I don't know where the "test passed" message is coming from. Is that the output of your test? or the output of some build system?
Note that a binary that exit with an exit code of `0` is considered to be a passing test, and `0` is the default exit code for `main`. This means that running nothing in your main will be considered a passing test.

**Comment by honghaoli** [comment]
This should be a bazel bug other than a googletest bug.
