### ISSUE TITLE
How to mock out params

### ISSUE THREAD

**Issue by Mrzhuzy** [google/googletest#2200]
Suppose there is a function int GetResume(char & p_chStatus, char * p_szMsg,int & p_iCount, Const p_iLength), the first three are out params, the latter one is input param, how to mock the first three out params?

**Comment by akonradi** [comment]
Not sure what the question is. You can use MOCK_METHOD4 to define the mock method and then use WillOnce to write into the out params.

```c++
TEST(MyTest, GetResume) {
  MyObj obj;
  EXPECT_CALL(obj, GetResume).WillOnce([] (char & p_chStatus, char * p_szMsg,int & p_iCount, Const p_iLength) {
    p_chStatus = 'a';
    p_szMsg = nullptr;
    p_iCount = 42;
  });

  // Do stuff that calls GetResume
}
```

**Comment by asoffer** [comment]
Closing as akonradi's response is correct, though nowadays, we prefer to use the bare MOCK_METHOD (without a number) macro.

I might also suggest ON_CALL instead of EXPECT_CALL, but roughly speaking akonradi is correct.
