### ISSUE TITLE
Hexadecimal Printing in Test Fail messages

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#222]
```
What steps will reproduce the problem?
1. Compare two numerical values using ASSERT_EQ function; 
2. The output shows expected and actual values in base 10 format
3. There is no way to print these expected and default values in
hexadecimal/octal format

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
unix

Please provide any additional information below, such as a code snippet.


```

Original issue reported on code.google.com by `giris...@gmail.com` on 12 Nov 2009 at 5:07

**Comment by nmz787** [comment]
linkrot:
http://code.google.com/p/googletest/wiki/GoogleTestAdvancedGuide#Using_a_Predicate-Formatter

 where is the new link?

**Comment by jbzdarkid** [comment]
https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#using-a-predicate-formatter

**Comment by thpica** [comment]
https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#using-a-predicate-formatter

**Comment by RPiAwesomeness** [comment]
https://github.com/google/googletest/blob/main/docs/advanced.md#using-a-predicate-formatter
