### ISSUE TITLE
1.8.1 is said to support pre-c++11.. but compilation is failed in GCC 4.1.2 (Redhat machine with c++98 compiler)

### ISSUE THREAD

**Issue by dispongateway** [google/googletest#2220]
1.8.1 is said to support pre-c++11.. but compilation is failed in GCC 4.1.2 (Redhat machine with c++98 compiler).

The compilation error says that template handling error. 
Meanwhile 1.8.0 works fine.

**Comment by gennadiycivil** [comment]
There is a wide variety of compilers with their respective assosiated
issues. The compiler in question is almost 12 years old.
Is there a particular reason you can't use a newer compiler?

**Comment by dispongateway** [comment]
Yes, Our customers still use the old linux machines. Hence We could not force them to use the newer compilers.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by dispongateway** [comment]
> Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

How can I do this?

**Comment by tituswinters** [comment]
We don't have access to all old compilers, and generally aren't willing to
contort much to support things outside the ~5 year support horizon. If you
can make a minimal PR that re-enables support for your old compiler, we can
evaluate whether the support burden / mess it makes is acceptable - but we
won't be able to test or promise that future releases don't break that
support.

(Fundamentally: if you're stuck with an old compiler, you probably need a
similarly old set of libraries. Trying to mix-and-match arbitrarily has an
intrinsic quadratic scaling problem that we're unwilling to commit to.)

**Comment by Bu11etmagnet** [comment]
If your customers need to use 12-year-old compilers and operating systems (GCC 4.1 is the default compiler for RHEL 5, released March 15, 2007), they should stick to gtest 1.8.0

**Comment by ngie-eign** [comment]
FWIW, I’d be concerned about security flaws with the 12 year old OSes...
