### ISSUE TITLE
Possibility to debug tests launched via death test define using Visual Studio

### ISSUE THREAD

**Issue by tapika** [google/googletest#2223]
This is more or less Google Test Adapter issue, raised issue here:

https://github.com/csoltenborn/GoogleTestAdapter/issues/277

But this will require changing googletest code as well, to await for debugger attaching.

Now I'm talking about Windows platform / Visual Studio, interested how this is handled for other platforms ?

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
