### ISSUE TITLE
Making scripts compatible with python 3

### ISSUE THREAD

**Issue by dibya001** [google/googletest#2233]
As python 2 will be EOL on Jan 1, 2020, so when the python scripts in the projects will be compatible with python 3? Or if some scripts don't support python 3 but also are unused, is there any plan to remove those unnecessary scripts?

**Comment by gennadiycivil** [comment]
Yes we will be making scripts Python 3 compatible, and yes older scripts are getting removed, see https://github.com/google/googletest/commit/9f4f27b2a5081830aa977c4fbf303751118a68e4

**Comment by gennadiycivil** [comment]
As to "when" - I can not give you an answer. 
Is there particular reason and particular script that is of an interest?

**Comment by dibya001** [comment]
We are trying to migrate all our codebase to Python3  including the Thirdparty dependencies like Google Test.

**Comment by gennadiycivil** [comment]
@dibya001 , Did this answer your question?
