### ISSUE TITLE
Microsoft Visual Studio 2013 c++11 issues

### ISSUE THREAD

**Issue by zichaelpath** [google/googletest#2235]
Hello, I am interested in using googlemock and googletest as my testing and mocking suite for some projects that I am currently a team member of.  I am using Visual Studio 2013 and developing for Windows Embedded 2013.  I have downloaded and attempted to implement your code into our unit tests, however I am met with a sea of errors in Visual Studio.  Upon inspection of the code, I have not noticed any errors in the compiler and everything seems to be in working order.  Is there any reason why it is not working for me?

**Comment by gennadiycivil** [comment]
Visual Studio 2013 is a very old compiler. We do not run any CI checks on it.
If for any reason you can not use a newer one you may want to try one of the older googletest releases.

**Comment by zichaelpath** [comment]
do you support Windows Embedded Compact 2013?

**Comment by tituswinters** [comment]
Honestly, I'm not entirely sure where the compatibility level stands for
googletest at this point. But if you need C++11, you may need to update to
MSVC 2015r3 or better. The C++11 support previous to that release was
lacking in most Windows compilers, especially for things like thread-safe
initialization of function-scope statics (which is fairly common in a lot
of C++11 code, at least in my experience).
