### ISSUE TITLE
"make check" fails on googlemock

### ISSUE THREAD

**Issue by nathanpt1** [google/googletest#2236]
Out of the box autotools are utilized in the compilation.  Does an environment variable or LIB path need to be set?  I do not see anything in the documentation.  Or is this an error in the framework?

RHEL Workstation 7.6
HP z440 Xeon 8-core 16 GB RAM
local GCC 4.8.5
local python 2.7.5
local autotool suite

googletest 1.8.1 - tar.gz

At top level
autoreconf -fiv
./configure --prefix=/install-path
make
make check

Making check in googletest
PASS: 12

Making check in googlemock
./test/production.cc: In function 'void _Z41__static_initialization_and_destruction_0ii.constprop.702()':
./test/production.cc:35:37: note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without
...
 PrivateCode::PrivateCode() : x_(0) {}
t/gmock_test.cc:39:41: fatal error: gtest/internal/custom/gtest.h: No such file or directory
 #include "gtest/internal/custom/gtest.h"
compilation terminated.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. Unfortunately there appears to be no actionable information.
