### ISSUE TITLE
Documents and samples related to TYPED_TEST_CASE needs to be updated

### ISSUE THREAD

**Issue by EhsanMosadeq** [google/googletest#2237]
TYPED_TEST_SUIT is not available anymore and replaced  by TYPED_TEST_CASE. So [advanced doc](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md) and [sample](https://github.com/google/googletest/blob/master/googletest/samples/sample6_unittest.cc) related to it should be updated.

**Comment by gennadiycivil** [comment]
TYPED_TEST_SUIT is the new API and is available.

**Comment by EhsanMosadeq** [comment]
Yes it seems that my local version is not updated. Thanks.
