### ISSUE TITLE
INSTANTIATE_TEST_CASE_P called before GTest global test-environments setup

### ISSUE THREAD

**Issue by czuzu** [google/googletest#2240]
Instantiation of parameterized tests is done before setting up the Google-Test test environments (::testing::AddGlobalTestEnvironment).
This forces populating containers for ValuesIn usage statically, outside of Google-Test context.
In my opinion, this is bad design and should be changed.

**Comment by czuzu** [comment]
A workaround would be creating static methods that populate the containers (lazy usage) and destroying those containers on global-environment teardown.
But that is not so elegant compared to postponing tests discovery after global test-environments setup :)

**Comment by gennadiycivil** [comment]
@czuzu thank you for this report. It would be helpful if you could elaborate on "bad design". Thank you

**Comment by czuzu** [comment]
@gennadiycivil Hi, I thought I already explained what I meant by that :) I mean that instantiating parameterized test cases after global test-environments are set up is a better usage design than the current one because of the following.

Currently, containers and data needed by parameterized test-cases **cannot depend on any global test-environments**, because **these environments** are **set up only after INSTANTIATE_TEST_CASE_P is called**. This means 2 things:

1. Prerequisites of those test-cases must be prepared in a different manner than using global test-environments, but shouldn't the purpose of global test-environments be just that?

2. If you **already had some initialization logic** that was **done using global test-environments** and now you **want to use a parameterized test-case** which **uses data that depends on that initialization logic**, now you are **forced to take that logic outside the global test-environments and redesign your code** - this actually happened in my case

**Comment by sbenzaquen** [comment]
On Sun, Apr 28, 2019 at 9:40 AM czuzu <notifications@github.com> wrote:

> @gennadiycivil <https://github.com/gennadiycivil> Hi, I thought I already
> explained what I meant by that :) I mean that instantiating parameterized
> test cases after global test-environments are set up is a better usage
> design than the current one because of the following.
>
> Currently, containers and data needed by parameterized test-cases *cannot
> depend on any global test-environments*, because *these environments* are *set
> up only after INSTANTIATE_TEST_CASE_P is called*. This means 2 things:
>
>    1.
>
>    Prerequisites of those test-cases must be prepared in a different
>    manner than using global test-environments, but shouldn't the purpose of
>    global test-environments be just that?
>    2.
>
>    If you *already had some initialization logic* that was *done using
>    global test-environments* and now you *want to use a parameterized
>    test-case* which *uses data that depends on that initialization logic*,
>    now you are *forced to take that logic outside the global
>    test-environments and redesign your code* - this actually happened in
>    my case
>
>
You can have a dynamically generated list of values passed as the list of
values to `INSTANTIATE_TEST_CASE_P`.
It still has to run at dynamic initialization time, though.

Alternatively, you can use `testing::RegisterTest` to register tests
manually without the macros. This function gives you much more freedom on
how you define and name your tests, but it is only recommended for those
specific cases where the macros do not do what you need.

**Comment by czuzu** [comment]
Hi @sbenzaquen. By dynamically-generated I'm guessing you mean lazy initialization, returning the container by calling a function. This is what I'm doing actually, but yes, it still has to run before global test-environments are set up, so it doesn't solve the issue :).

Is `testing::RegisterTest` documented? I don't see it. Is it not internal? I'm using an older version of gtest, I don't even know what it is, I must use one that is provided by a 3rd party (btw isn't the version of gtest documented in the sources? I couldn't find that either). The version I'm using does not seem to have `testing::RegisterTest` defined (only `testing::internal::ParameterizedTestCase*::RegisterTests`). Also, this would still be a workaround, not elegant IMO since it makes the user manually do what gtest "should" be doing.

The intention of this post is either to get an elegant solution to the problem which I don't know of and/or suggest that the behaviour is changed such that global test-environments are setup before parameterized test-cases are instantiated. I'm still of the opinion that it would make more sense for it to behave this way :)

**Comment by gennadiycivil** [comment]
@czuzu testing::RegisterTest is in the current master, it is somewhat recent.
You can see the definitions and usage examples 
https://github.com/google/googletest/search?q=testing%3A%3ARegisterTest&unscoped_q=testing%3A%3ARegisterTest

**Comment by czuzu** [comment]
Ok thanks, that's good to know, although unfortunately I'm stuck with an older version of gtest.

That aside, that's still a somewhat cumbersome alternative to something that could be working differently (better) by default, so I'm still of the opinion that INSTANTIATE_TEST_CASE_P behavior (call time specifically) should be changed instead.

Thank for you the provided information.

**Comment by gennadiycivil** [comment]
Closing, looks like the conversation reached its limit. 
Let me know otherwise
Thanks

**Comment by stilllman** [comment]
@gennadiycivil I think this feature request deserves to be considered, I feel like it was closed because of the tone of the conversation and not because it was deemed a bad idea.

I just stumble upon the exact same issue as @czuzu: I'm trying to instantiate a test case with a dynamic list of parameters, using `ValuesIn`, but I'm failing because the generation of the parameters is done outside of the test environment, where my application code doesn't work.

Considering test environments are "advertised" as "global set-up and tear-down at the program level", I think we might not be the only ones being surprised by this behavior. Note that the doc describes the behavior precisely and very well explains that the set-up will be performed only when `RUN_ALL_TESTS` is called, but one doesn't necessarily know if test cases are instantiated during `InitGoogleTest` or `RUN_ALL_TESTS` 🤷 

If you think that test initializations is a separate process from tests run and they should be done in a separate environment, it is definitely an acceptable decision IMHO, but I just want to make sure that you actually considered the alternative (doing the initialisation within the test env).

As a side question, would the following be a correct change to solve our issue?

`int main(int argc, char** argv)
{
	::testing::AddGlobalTestEnvironment(new MyEnvironment);
	::testing::InitGoogleTest(&argc, argv);
	return RUN_ALL_TESTS();
}`
=>
`int main(int argc, char** argv)
{
	MyEnvironment env;
	env.Setup();
	::testing::InitGoogleTest(&argc, argv);
	const auto exitCode = RUN_ALL_TESTS();
	env.TearDown();
}`
?

**Comment by atracsys-jlu** [comment]
I've just stumbled across the same issue, and @stilllman's suggestion just made my day.
