### ISSUE TITLE
Test case objects

### ISSUE THREAD

**Issue by AmeenOliver** [google/googletest#2243]
I’m an embedded system test engineer, using Google Test framework,  and I would like to ask you,
If there is a way to return the test cases objects as a table that contain input value either the output.

Actually I tried and reached to extract the expected and the actual value that represent argument of Macros (like : EXPECT_EQ(expected, actual)) by modifying the code source,
But still not possible for me to extract DataCurr[],ConfigCurr[] informations.

this exemple show the test case to extract its content.
TEST_F(TRANSMISSION, SUTC_TR_004) {
                Tr.transmissionInit(); // 
                EXPECT_EQ(0xFF,Tr.getVariant());
                DataCurr[0] = 1; 
                DataCurr[1] = 1;
                DataCurr[2] = 7;
                DataCurr[3] = 1;
                DataCurr[4] = 1;
                DataCurr[5] = 1;
                DataCurr[6] = 1;
                DataCurr[7] = 1;
                ConfigCurr[0] = 1;
                ConfigCurr[1] = 1;
                ConfigCurr[2] = 7;
                ConfigCurr[3] = 1;
                ConfigCurr[4] = 1;
                Tr.transmissionProc(DataCurr, ConfigCurr);
                EXPECT_EQ(255,Tr.getVariant());
}

AMINE EL YOUBI
Embedded System Engineer
Department Auto & Aero ALTEN MAROC

**Comment by asoffer** [comment]
Closing, as I believe this is a question about the API under test rather than GoogleTest itself. Please reopen if I am incorrect.
