### ISSUE TITLE
Two Macros for Numerical Analysis

### ISSUE THREAD

**Issue by NAThompson** [google/googletest#2247]
No unit testing framework provides test macros which provide the information I require when writing numerical unit tests. I have [two macros](https://raw.githubusercontent.com/boostorg/math/a36a7f4ef4c80b37a8582c66ad46cb7ddd4f6a0b/test/math_unit_test.hpp) which I use routinely, but they tend to frustrate people since they are not provided in any common unit testing package. So I was hoping to get a discussion going about whether googletest would like these macros, and conditional on y'alls thumbs up, I'll go throw the effort to learn how to integrate them into your system.

- The first macro is CHECK_ULP_CLOSE. I got the idea to create this macro from [Cleve Moler](https://blogs.mathworks.com/cleve/2017/01/23/ulps-plots-reveal-math-function-accurary/), and it is the most severe test of a numerical algorithm's accuracy, requiring that the number of representables between an accepted value and a computed value is below some value. In addition to indicating a failure, both the decimal and hexadecimal representation is printed. For me it is not obvious when a failure occurs whether or not that failure is meaningful. The hexadecimal representation is quite helpful in that regard, since is shows what fraction of your bits are being wasted. Example output is:
<img width="806" alt="math_unit_test" src="https://user-images.githubusercontent.com/5459618/57180196-57271c80-6e54-11e9-877d-81271446eace.png">

- The next macro is called `CHECK_MOLLIFIED_CLOSE`. This is from an idea of Walter Gautchi, who recommended interpolating between absolute error and relative error via considering the quantity |expected - computed|/max(|expected|, 1). This is especially useful when implementing a special function, because CHECK_CLOSE_FRACTION always fails at the zeros, and CHECK_CLOSE always fails as the values get large. So for instance, if you are testing every 32 bit representable, you are sure to get frustrated. One criticism of CHECK_MOLLIFIED_CLOSE is that 1 needs to be a relevant scale for it to be meaningful, but if people non-dimensionalize their problems then it should be meaningful. Again, the hexadecimal rep, the decimal rep, and the ULP distance are also presented on failure.

What do you think?

**Comment by pleroy** [comment]
In the context of googlemock this should be done using matchers, not macros, as it would combine much better with other matchers and the rest of the testing infrastructure.

This being said I have had needed similar tools myself for numerical analysis purposes (see [here](https://github.com/mockingbirdnest/Principia/blob/master/testing_utilities/almost_equals.hpp) and [here](https://github.com/mockingbirdnest/Principia/blob/master/testing_utilities/vanishes_before.hpp) for example) so I for one would welcome inclusion of matchers addressing these needs in googlemock.

(As a side note I don't think that the "mollified" version should hard-wire 1, it should take the scale as a parameter somehow, again for convenience when composing matchers.)

**Comment by gennadiycivil** [comment]
@EricWF @sbenzaquen

**Comment by gennadiycivil** [comment]
We would welcome a PR with appropriate matchers

**Comment by asoffer** [comment]
I'm closing this issue as discussion has stagnated here. We welcome a PR along these lines... I believe that is the best place to continue a discussion, with a concrete implementation to reference.
