### ISSUE TITLE
BDD style with gtest

### ISSUE THREAD

**Issue by devans80** [google/googletest#2250]
Would it be possible to incorporate BDD style with gtest using something like https://github.com/Resurr3ction/cppbdd/blob/master/include/cppbdd/gtestbdd.h ? I am in the process of submitting a PR to extend it to also work with parameterized tests.

**Comment by gennadiycivil** [comment]
@devans80 Thank you for this idea. We are always open to improvements. With that, there would need to be a clear and compelling argument why the "new thing" is "better" and what it would allow is to do that is not currently possible.
Thanks agian

**Comment by devans80** [comment]
https://dannorth.net/whats-in-a-story/
Strictly speaking there isn't a straight technical win to this, however BDD style tests are a way to facilitate some ways of structuring tests that map more naturally onto an agile workflow.

- In an agile workflow, writing tests in a BDD style puts the focus of the test at all times on the features being delivered.
- Having a natural language description for the Scenario in a Given-When-Then-And format means that non-technical product owners can be part of writing tests
- Having a natural language description up to the point where a test has failed, gives the reader a richer context for what the test was for, and a natural language description of why it failed.

**Comment by gennadiycivil** [comment]
Let me clarify, I am not asking to justify the BDD tests in general, the
benefits are well known. Rather I am looking for more information how the
BDD testing would be used with googletest ( which is after all a C++ unit
testing framework ) and what benefits it would provide for googletest users
in particular.
Thank you
G

**Comment by devans80** [comment]
> Let me clarify, I am not asking to justify the BDD tests in general, the benefits are well known. Rather I am looking for more information how the BDD testing would be used with googletest ( which is after all a C++ unit testing framework ) and what benefits it would provide for googletest users in particular. Thank you G

Sure, makes sense. 
Okay so based on an extended version of [cppbdd](https://github.com/Resurr3ction/cppbdd) we have been using (although it's currently implemented with macros, which we can agree is sub-optimal) an example, albeit convoluted, use case might look something like this:

```cpp
FEATURE("A User can contact their client") {
  SCENARIO_F("[compose][email] Some scenario", MyFixture) {
    GIVEN("a valid initial state")
    const int i=5;
    
    WHEN("Applying an event.")
    ..

    THEN("Expect a thing to have happened")
    EXPECT_EQ(.., ..);

    AND("Expect something else")
    EXPECT_EQ(.., ..);
  }
}
```

and the output looks approximately like this 

```bash
[==========] Running 8 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from MyFixture
[ RUN      ] MyFixture.[compose][email] Created email event projects correctly
       SCENARIO [compose][email] Created email event projects correctly
          GIVEN Empty (default constructed) initial state
           WHEN Applying an EmailCreated event.
           THEN Expect the projection to have correct receiver
            AND Expect the projection to have correct sender
[       OK ] MyFixture.[compose][email] EmailCreated event projects correctly (12 ms)
...
...
[----------] Global test environment tear-down
[==========] 8 tests from 2 test cases ran. (21 ms total)
[  PASSED  ] 8 tests.
```

so considering myself as a googletest user, the benefit comes from being able to structure the code in a BDD style, for all the reasons we already discussed, but also from the output printing being in a natural language style supported in a standardized framework that doesn't rely on me just printing that. The unification of the reading the code the same way as the output is beneficial. One way this can be used is with A non technical product owner, who can write a plain text document in the format of `GIVEN`, `WHEN`, `THEN` and the engineers can use those as the template around which to fill in the test code. But even without product owner involvement it's a useful to lay out tests this way.

**Comment by gennadiycivil** [comment]
This look intriguing but far from definitive. Let's see if we can switch to something concrete. The email example is very high level and could be argued to apply more to integration testing than unit testing. 
Putting this aside , would you be able to prove tangible benefits by applying BDD to googletest's own test suite?

**Comment by devans80** [comment]
@gennadiycivil that seems like a reasonable suggestion. It will have to be a slow burn project though, as I have a full time job and finding the extra time will be a challenge. Also the implementation we are already using to do this (in unit tests, with googletest) is macro based and would need to be converted to some other implementation before it could be acceptable.

**Comment by devans80** [comment]
> The email example is very high level and could be argued to apply more to integration testing than unit testing.

Actually it could be useful to calibrate our understanding of these terms before going any further.
Was the intention of the comment quoted above that googletest was intended only for unit testing and should simply not be used for integration testing? As a c++ test framework, i've seen it commonly used for both and there do not appear to be any major drawbacks using it for both.
Or was it more to do with it applying to only the integration test use case of googletest, but that use case is a valid one ? (i.e. only consider a concrete application to integration tests in this project, not unit tests)

For reference I would align my understanding of the terms 'unit' and 'integration' tests with something like the definition by Martin Fowler here : https://martinfowler.com/bliki/IntegrationTest.html
Would your definition be different to that ? And if so, how would the difference impact the use of googletest framework for both ?

**Comment by gennadiycivil** [comment]
@devans80 Thank you for the explanations. 
For the record, terms 'unit' and 'integration' tests as defined by Martin Fowler here : https://martinfowler.com/bliki/IntegrationTest.html are fine.

The primary purpose of googletest is "C++ unit testing framework" . I would not go as far as to say that it should never be used for intergration tests. If your use-case warrants this usage and the framework provides value for you - great!

**Comment by gennadiycivil** [comment]
Looks stale will close soon

**Comment by ecruzolivera** [comment]
Hi, any update on this topic?

BDD is useful when dealing with legacy code which it is know what needs to do but the internals are generally an undocumented mess. On those cases trying to uni tests the project is at best a waste of time if not a totally impossible task.

I think that the fact that GTest support another "unit test related" workflow can only add value to its users, and example of this was the merge o GTest and GMock in to a single project.

I think that this issue's discussion sidetracked in to a semantic discussion about what is what and wasn't never discussed the possibility or not of include BDD in GTest.

**Comment by data-man** [comment]
@ecruzolivera 
Try [ut](https://github.com/boost-ext/ut) (C++17*/C++20)
>`* - Limitations may apply`

**Comment by ecruzolivera** [comment]
thanks @data-man for the suggestion, but switch UT library is not the idea.

**Comment by BartVandewoestyne** [comment]
Just FYI: Catch2 has [BDD-style testing](https://github.com/catchorg/Catch2/blob/devel/docs/test-cases-and-sections.md#bdd-style-test-cases).  In my opinion, having the possibility to define BDD-style tests with GoogleTest would be valuable.

**Comment by A-Sam** [comment]
Same here. It seems this proposal has gone stale but it's a really straightforward argument why to have BDD support "in any format" in gtest.

I have been looking for a way to link natural language to the test units of any type in gtest and it takes quite the work for raw handling of Gherkin steps tokens to be mapped by cmake and pre/post build scripts to link them in structured data like json.

It'd be so much easier to make a variation of the `TEST_*` macros with gherkin based steps as variadic args.

Multiple wrappers have already been implemented in Catch2 so I'm not really sure what is the value of not supporting it?

At least a promise to accept a PR for the implementation :)!


The argument is that it helps a lot in test decomposition and structuring. "natural language helps the system domain to cover core functionality requirements and expectations " this BDD listings allows TDD to be 1:1 mapping and quite straightforward to have near 100% code coverage without the SW developer covering function by function just because! 

This is a big problem in ASPICE test structuring in general and BDD helps to map SYS.X to SWE.X in clear mappings.


Just to reiterate, I'm a big fan of the raw gtest `TEST_*` units. But I think providing a way to map them to BDD Gherkin steps or tokens will facilitate time spent in test decomposition.
