### ISSUE TITLE
Google Test fails to compile When we build PDFium project with MSVC on windows

### ISSUE THREAD

**Issue by spacelg** [google/googletest#2251]
Hi All,

We tried to build PDFium project with MSVC on windows. It failed to build due to google Test compile errors c2065 c2275 c2440 and c2039. PDFiume use googletest‘s commit is [9997a83](https://github.com/google/googletest/commit/9997a830ee5589c2da79198bc3b60d1c47e50118).
And We tried to compile gtest-printers.cc or gmock.cc separately and these files will report these errors. Could you please help take a look at this? Thanks in advance!

[log_x86_build.log](https://github.com/google/googletest/files/3165609/log_x86_build.log)

Actual result:
D:\PDFium\pdfium\third_party\googletest\src\googletest\include\gtest/gtest-printers.h(523): error C2065: 'is_pointer': undeclared identifier
D:\PDFium\pdfium\third_party\googletest\src\googletest\include\gtest/gtest-printers.h(523): error C2275: 'T': illegal use of this type as an expression
D:\PDFium\pdfium\third_party\googletest\src\googletest\include\gtest/gtest-printers.h(523): error C2440: 'specialization': cannot convert from 'int' to 'testing::internal::DefaultPrinterType'
D:\PDFium\pdfium\third_party\googletest\src\googletest\include\gtest/gtest-printers.h(523): error C2039: 'value': is not a member of 'testing::internal::WrapPrinterType<testing::internal::kPrintContainer>'

**Comment by gennadiycivil** [comment]
Could you please provide more information,what version of MSVC in particular

Thanks



*From: *spacelg <notifications@github.com>
*Date: *Fri, May 10, 2019, 04:40
*To: *google/googletest
*Cc: *Subscribed

Hi All,

**Comment by spacelg** [comment]
Hi,

Thanks for your reply!
We use VS2017 and cl command as below:
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX64\x86/cl.exe" /nologo /showIncludes -DUSE_AURA=1 -DNO_TCMALLOC -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -D_HAS_EXCEPTIONS=0 -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -D_USING_V110_SDK71_ -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=NTDDI_WIN10_RS2 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DGTEST_API_= -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=1 -DGTEST_HAS_TR1_TUPLE=0 -I../../third_party/googletest/src/googletest -I../.. -Igen -I../../third_party/googletest/src/googletest/include /Gy /FS /bigobj /utf-8 /Zc:sizedDealloc- /wd4117 /D__DATE__= /D__TIME__= /D__TIMESTAMP__= /O1 /Ob2 /Oy- /Zc:inline /Gw /Oi /Zi /MT /W3 /wd4800 /wd4267 /wd4996 /WX /wd4091 /wd4127 /wd4251 /wd4275 /wd4312 /wd4324 /wd4351 /wd4355 /wd4503 /wd4589 /wd4611 /wd4100 /wd4121 /wd4244 /wd4505 /wd4510 /wd4512 /wd4610 /wd4838 /wd4995 /wd4996 /wd4456 /wd4457 /wd4458 /wd4459 /wd4200 /wd4201 /wd4204 /wd4221 /wd4245 /wd4267 /wd4305 /wd4389 /wd4702 /wd4701 /wd4703 /wd4661 /wd4706 /wd4715 /wd4267 /wd4702 /wd4800 /TP /GR- /wd4577 /c ../../third_party/googletest/src/googletest/src/gtest-printers.cc /Foobj/third_party/googletest/gtest/gtest-printers.obj /Fd"obj/third_party/googletest/gtest_cc.pdb"

Thanks,
Lin

**Comment by spacelg** [comment]
Hi, 

Is there anyone looking at this issue?

Thanks,
Lin

**Comment by gennadiycivil** [comment]
@spacelg the best suggestion I can provide is to use bazel or CMake on Windows. Since this configuration is a part of regular Continuous Integration it is working and tested on each Pull Request.

**Comment by gennadiycivil** [comment]
I am closing this issue , there appears to be no community activity on this. Please let me know otherwise
Thanks
