### ISSUE TITLE
Fix the project version of 1.8.1

### ISSUE THREAD

**Issue by chfast** [google/googletest#2256]
The `GOOGLETEST_VERSION` of the 1.8.1 release is 1.9.0 what is at least confusing.
https://github.com/google/googletest/blob/release-1.8.1/CMakeLists.txt#L8

This affects also the exported cmake package configs.

Probably the best way to handle that would be to release 1.8.2 with the version number fixed.

**Comment by gennadiycivil** [comment]
@chfast thank you for this request. As you can see in https://github.com/google/googletest/blob/f71fb4f9a912ec945401cc49a287a759b6131026/CMakeLists.txt#L1 CMake support is community-based.

Disconnect between the actual release and the version in CMake is an oversign that happened some time ago.

We are planning to fix it with the next release 1.9.x , dont have timing for that yet.

Thanks
