### ISSUE TITLE
SonarQube integration

### ISSUE THREAD

**Issue by Prasaddiwalkar** [google/googletest#2262]
My C++ project is hosted on GitLab I want to integrate GoogleTest results with SonarQube.

Can anyone guide me to achieve it.

**Comment by EricWF** [comment]
I'm afraid this isn't the right place to ask.

I found some links on the SonarQube side of things:

https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Test-runners
https://github.com/SonarOpenCommunity/sonar-cxx/issues/1097
https://community.sonarsource.com/t/gtest-output-and-sonar/3900

**Comment by albmiranda** [comment]
You can export the coverage using Generic Test Data format. (sonar.coverageReportPaths)

After .gcda and .gcno files created, run gcov and gcovr to create a xml report.
> gcov . 
> gcovr . --sonarqube test-coverage.xml

(y)
