### ISSUE TITLE
 googletest should release a new version

### ISSUE THREAD

**Issue by marehr** [google/googletest#2267]
We are >45 commits and a couple of features ahead of the last released version, a new release would be much appreciated.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The next version will be released when ready, can not promise any concrete time. What is the significance of the "new version" - which is basically a cut in some point of time- and why is important for your use case?

**Comment by Arfrever** [comment]
I guess that @marehr meant `1.8.2` release from `v1.8.x` branch...

Personally I would need `1.9.0` release from `master` branch.
[Protocol Buffers](https://github.com/protocolbuffers/protobuf) 3.8.0 released in last week requires at least `INSTANTIATE_TEST_SUITE_P` macro, which is not available in `v1.8.x` branch, but is available in `master` branch.
When can we expect `1.9.0` release?

**Comment by gennadiycivil** [comment]
@marehr There will NOT be a release from 1.8 branch
@Arfrever, please see  https://github.com/google/googletest/issues/2267#issuecomment-498802635 above

Thank you!

**Comment by tomalakgeretkal** [comment]
Why's it surprising that somebody would be keen on a new release? The last one was almost a year ago!

**Comment by gennadiycivil** [comment]
Thank you for commenting.
It is not "surprising" , sorry if my remark somehow came through as if this
is 'surprising'.
I recommend reading https://abseil.io/about/philosophy . Thank you

**Comment by ocroquette** [comment]
> What is the significance of the "new version" - which is basically a cut in some point of time- and why is important for your use case?

As far as I and my company are concerned, we are very interested in GTEST_SKIP, but it is not part of any official release yet, and we are concerned about using a random version from "master". I guess other users would have the same issue with other features added since 1.8.

Or are you recommending any "master" version for productive use?

**Comment by Arfrever** [comment]
Gentoo GNU/Linux now has a snapshot from master branch of gtest, since it is required by new protobuf:
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=e58c0ab35c35b4de684f86137e432efba6592080

**Comment by gennadiycivil** [comment]
https://github.com/google/googletest/releases/tag/v1.10.x
