### ISSUE TITLE
Add `MockFunction::AsLambda` method

### ISSUE THREAD

**Issue by adambadura** [google/googletest#2278]
`MockFunction` has `AsStdFunction` method returning an `std::function` of appropriate signature and calling the `Call` method.

Why not add also `AsLambda` which returns the lambda doing the same? It doesn't even add much since it can be reused by the `AsStdFunction`:
````diff
diff --git a/googlemock/include/gmock/gmock-spec-builders.h b/googlemock/include/gmock/gmock-spec-builders.h
index 1f261bd2..ec4a38cc 100644
--- a/googlemock/include/gmock/gmock-spec-builders.h
+++ b/googlemock/include/gmock/gmock-spec-builders.h
@@ -1846,12 +1846,16 @@ class MockFunction<R(Args...)> {
   MockFunction(const MockFunction&) = delete;
   MockFunction& operator=(const MockFunction&) = delete;
 
-  std::function<R(Args...)> AsStdFunction() {
+  auto AsLambda() {
     return [this](Args... args) -> R {
       return this->Call(std::forward<Args>(args)...);
     };
   }
 
+  std::function<R(Args...)> AsStdFunction() {
+    return AsLambda();
+  }
+
   // Implementation detail: the expansion of the MOCK_METHOD macro.
   R Call(Args... args) {
     mock_.SetOwnerAndName(this, "Call");
````

Use of a lambda instead of `std::function` when possible has some advantages, perhaps most importantly here shorter stack traces.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.
I will close this issue now and will be looking forward to a proper PR with full justification why this is advantageus

**Comment by adambadura** [comment]
This is not doable within C++11. I'm working in C++14 for so long, that I failed to notice that C++11 doesn't have the full return type deduction.
