### ISSUE TITLE
Different MakeAndRegisterTestInfo signatures

### ISSUE THREAD

**Issue by nrbrook** [google/googletest#2294]
I'm getting missing symbols when linking my test target with google test:
```
Undefined symbols for architecture x86_64:
  "testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)", referenced from:
      ___cxx_global_var_init in ATAppTests.cpp.o
```
It seems `gtest.h` has the wrong signature:
https://github.com/google/googletest/blob/1d721a7a9d58748b3f687b7ef56e9159881041df/googletest/include/gtest/gtest.h#L758-L763
Compared to `gtest-internal.h`:
https://github.com/google/googletest/blob/1d721a7a9d58748b3f687b7ef56e9159881041df/googletest/include/gtest/internal/gtest-internal.h#L558-L562

**Comment by nrbrook** [comment]
Sorry, the compiler was picking up an old gtest.h embedded in https://github.com/meekrosoft/fff

**Comment by pestophagous** [comment]
even though this was an erroneous bug, i'm glad it was here. it sped up my own diagnosis when i ran into basically the same situation. thanks, @nrbrook !

**Comment by Niklesh99** [comment]
@nrbrook Can you help how to verify which version of gtest header the compiler is using?

**Comment by nrbrook** [comment]
@Niklesh99  I can't remember but I probably just modified the header to put an `#error` in to see which file it was trying.

**Comment by Niklesh99** [comment]
Thanks for the comment. The issue got resolved now.
