### ISSUE TITLE
What happened to googletest/docs/XcodeGuide.md ?

### ISSUE THREAD

**Issue by Yrchgrchh** [google/googletest#2295]
Hi,

I see XCodeGuide.md was removed from documentation. What was the reason behind it and what is the current way to use gtest in xcode projects?

Thanks

**Comment by gennadiycivil** [comment]
Thank you for your question.

As you can see in the
https://github.com/google/googletest#requirements Googletest
officially supports bazel and (community-supported) Cmake.

>> What was the reason behind
The XCodeGuide.md was old, unmaintained and we had no way to know if it was
still correct.

>>>it and what is the current way to use gtest in xcode projects?
You can generate XCode with CMake
https://cmake.org/cmake/help/latest/generator/Xcode.html#

Hope this helps
G

**Comment by Yrchgrchh** [comment]
I see, thanks a lot for the quick reply
