### ISSUE TITLE
Debug Assertion Failed!  Expression: __acrt_first_block == header

### ISSUE THREAD

**Issue by LegalizeAdulthood** [google/googletest#2299]
Building google test 1.8.1 in a debug shared object and running tests results in debug assertions from the VC++ runtime.  The code in question was compiled with VS 2015 with all the latest updates applied.

![image](https://user-images.githubusercontent.com/4270863/59952258-c2df3c00-9438-11e9-962f-ec194710a811.png)

The call stack shows this to be in this function:

```
TestInfo* MakeAndRegisterTestInfo(
    const char* test_case_name,
    const char* name,
    const char* type_param,
    const char* value_param,
    CodeLocation code_location,
    TypeId fixture_class_id,
    SetUpTestCaseFunc set_up_tc,
    TearDownTestCaseFunc tear_down_tc,
    TestFactoryBase* factory) {
  TestInfo* const test_info =
      new TestInfo(test_case_name, name, type_param, value_param,
                   code_location, fixture_class_id, factory);
  GetUnitTestImpl()->AddTestInfo(set_up_tc, tear_down_tc, test_info);
  return test_info;
}
```

![image](https://user-images.githubusercontent.com/4270863/59952624-1e5df980-943a-11e9-86bf-e7bde407cd58.png)

We never got this assertion when using gtest v1.7.0

**Comment by LegalizeAdulthood** [comment]
Stepping through it in the debugger, the assert is thrown on the `return` statement, presumably when some temporary object is being destroyed and freeing memory.  I wasn't able to narrow it down more specifically.

**Comment by Peteck** [comment]
I started getting this error in debug when I switched from MDd to MTd runtime lib.

**Comment by asoffer** [comment]
From https://stackoverflow.com/questions/35310117/debug-assertion-failed-expression-acrt-first-block-header, it seems likely that some object is allocated on one side of a DLL boundary and destroyed in another. Because DLLs are community supported we are unable to look into this further. If you do find more we would gladly accept a PR to fix this issue.
