### ISSUE TITLE
Sign conversion warnings become errors with Emscripten

### ISSUE THREAD

**Issue by encelo** [google/googletest#2300]
Given the default compiler settings of `set(cxx_base_flags "-Wall -Wshadow -Werror -Wconversion")` I got a couple sign conversion warnings with Emscripten that become errors.
It happens for the following two lines:

- https://github.com/google/googletest/blob/834dff3b5279164c65f13cc712ed79dbb5c66950/googletest/src/gtest.cc#L1952

```
error: implicit conversion changes signedness: 'const wchar_t' to 'wint_t' (aka 'unsigned int') [-Werror,-Wsign-conversion]
    left = towlower(*lhs++);
           ~~~~~~~~ ^~~~~~
```

- https://github.com/google/googletest/blob/834dff3b5279164c65f13cc712ed79dbb5c66950/googletest/src/gtest.cc#L1953

```
error: implicit conversion changes signedness: 'const wchar_t' to 'wint_t' (aka 'unsigned int') [-Werror,-Wsign-conversion]
    right = towlower(*rhs++);
            ~~~~~~~~ ^~~~~~
```

**Comment by EricWF** [comment]
Oh wow. You can't call `towlower` with a wide character without this warning triggering. That's unfortunate.

I don't know if we can support `-Wconversion` as a policy, but I'll certainly fix this code. You have to love good API design.

**Comment by EricWF** [comment]
If you can confirm that the patch fixes the issue, it would be much appreciated.

**Comment by encelo** [comment]
Yes, I confirm it fixes the compilation warnings and errors with Emscripten. :+1:

**Comment by gennadiycivil** [comment]
I would prefer to add a CI configuration to guard against this condition. If at all possible, please add one.

**Comment by gennadiycivil** [comment]
should be done now
