### ISSUE TITLE
release-1.8.1 compile failed:  error: ‘AssertionResult’ does not name a type

### ISSUE THREAD

**Issue by rhettdyao** [google/googletest#2301]
I checkout gtest tag release-1.8.1, when I compile my test suit, it report this error.
but when I use tag release-1.8.0, no compile error.
otherwise, when I use the master, it report the error abort c++ 11. I use gcc 4.8.5

**Comment by EricWF** [comment]
This is not enough information to work from.
Can you provide a full reproducer including source, command line invocation, and output?

It's worth noting GCC 4.8 support is being phased out. Newer GCC versions will be required to use Googletest.

**Comment by gennadiycivil** [comment]
Closing, looks abandoned
