### ISSUE TITLE
GMock should not gives false warning when using mock object as smart pointer

### ISSUE THREAD

**Issue by daravi** [google/googletest#2305]
When I store a mock object on the heap using a shared_ptr, the expectations are satisfied and the pointer is destroyed, but GMock thinks the mock object is still alive (gives warning):

```
// Using a mock object
MockFoo foo;
EXPECT_CALL(foo, doSomething());
foo.doSomething();
// Test passes without warnings
...............................
// Using shared_ptr to a mock object
auto foo_sp = std::make_shared<MockFoo>();
EXPECT_CALL(*foo, doSomething());
mock->doSomething();
foo_sp = nullptr;
// Test passes WITH warnings that mock object is still alive
```

There should not be any warnings as the mock object is destroyed, and the expectation is satisfied.

**Comment by ant35rookie** [comment]
Hello,

I'm writing test with release-1.8.0 and there is no warning about releasing pointer
```
git clone -b 'release-1.8.0' --single-branch https://github.com/google/googletest.git
```
how about trying it with newer versions ?

**Comment by daravi** [comment]
Hi sorry for the noise I realized that the issue was elsewhere and wanted to delete this issue but it wasn’t showing up (I guess needs to be approved first?).

Cheers.
