### ISSUE TITLE
run" make install" fail

### ISSUE THREAD

**Issue by kelvin9628146** [google/googletest#2306]
when I run the "make install " section , I get a error message.
is it something wrong I do?
//-----------------
[ 36%] Built target gmock_main
[ 63%] Built target gmock
[ 81%] Built target gtest
[100%] Built target gtest_main
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/libgmock.a
CMake Error at googlemock/cmake_install.cmake:41 (file):
  file INSTALL cannot copy file
  "/path/googletest-release-1.8.0/googlemock/libgmock.a"
  to "/usr/local/lib/libgmock.a".
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)

Makefile:128: recipe for target 'install' failed
make: *** [install] Error 1
//---------------------------------------

**Comment by gennadiycivil** [comment]
looks like you dont have file permissions to copy the file.
