### ISSUE TITLE
Enhancement: comparison between containers

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#231]
```
The google test framework includes no easy way to compare between containers of 
numbers. I have 
a potential solution that would be improved by inclusion in the googletest 
framework (and more 
direct access to the macros and templated functions).

I posted my solution on SO:
http://stackoverflow.com/questions/1460703/comparison-of-arrays-in-google-
test/1681550#1681550

and I'm attaching my own copy of the source.
```

Original issue reported on code.google.com by `johnson.seth.r@gmail.com` on 2 Dec 2009 at 2:18

Attachments:
- [expectIterable.hpp](https://storage.googleapis.com/google-code-attachments/googletest/issue-231/comment-0/expectIterable.hpp)

**Comment by qcq** [comment]
I want to ask another question, do we have a way to compare two containers which contains same items but not in same order.

**Comment by Bu11etmagnet** [comment]
We can compare them, but the answer will be "not equal".

**Comment by marthinsen** [comment]
> I want to ask another question, do we have a way to compare two containers which contains same items but not in same order.

There is a section about container matchers in the docs of Google Mock: [https://github.com/google/googlemock/blob/master/googlemock/docs/v1_7/CheatSheet.md#container-matchers](Google Mock Cheat Sheet)
EXPECT_THAT(my_container, UnorderedElementsAreArray(expected_container)); might help.

**Comment by qcq** [comment]
great, Thanks, may be I am sucked in old doc of Gtest. Thanks again

On Oct 26, 2018, at 22:34, Eirik Marthinsen <notifications@github.com<mailto:notifications@github.com>> wrote:


I want to ask another question, do we have a way to compare two containers which contains same items but not in same order.

There is a section about container matchers in the docs of Google Mock: [https://github.com/google/googlemock/blob/master/googlemock/docs/v1_7/CheatSheet.md#container-matchers](Google Mock Cheat Sheet)
EXPECT_THAT(my_container, UnorderedElementsAreArray(expected_container)); might help.
