### ISSUE TITLE
NiceMocks always uses default constructor

### ISSUE THREAD

**Issue by 0ge** [google/googletest#2315]
I have a diamond inheritance structure. I have an interface class that is used in many other classes. I want to make only one mock for all subclasses. The specific mocks can then inherit the general mock and get the finished mock functions.

This works, except when I try to instantiate the finial mocks as NiceMock and the general mock does not have a default constructor. An example:

```
#include "gmock/gmock.h"
#include "gtest/gtest.h"

class A {
public:
  A() {}
};

class B : virtual public A {
public:
  B() {}
};

class MockA : virtual public A {
public:
  MockA(int a = 0) { printf("a = %d\n", a); }
};

class MockB : virtual public MockA, virtual public B {
public:
  MockB() : MockA(1), B() {}
};

class MockC : virtual public MockA, virtual public B {};

class MyFixture : public ::testing::Test {
protected:
  MockB myMockB;
  MockC myMockC;
  ::testing::NiceMock<MockB> myMockB1;
};

TEST_F(MyFixture, MyTest) { SUCCEED(); }

int main(int argc, char **argv) {
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
```

This will give the (to me) unexpected output when run:

```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from MyFixture
[ RUN      ] MyFixture.MyTest
a = 1
a = 0
a = 0
[       OK ] MyFixture.MyTest (0 ms)
[----------] 1 test from MyFixture (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 1 test.
```

If I remove the default value in MockA's constructor, the program won't compile:

> main.cpp:24:7: error: implicit default constructor for 'MockC' must explicitly initialize the base class 'MockA' which does not have a default constructor

This is expected if in fact the NiceMock always uses the default constructor (because its now missing).

What is the reason for this behaviour?

Thanks,

```
$ c++ --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by EricWF** [comment]
`MockC` always default constructs its `MockA` base class.

This isn't a Google test issue.
