### ISSUE TITLE
pump_manual.md is out of date

### ISSUE THREAD

**Issue by LegalizeAdulthood** [google/googletest#2321]
> Variadic templates and variadic macros can alleviate the problem. However, while both are being considered by the C++ committee, neither is in the standard yet or widely supported by compilers.

Not only have variadic macros and templates been added to the standard, support for them is widespread among compilers at this point.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by LegalizeAdulthood** [comment]
LOL.  It took you as much time to type that response as it would be to type up the fix.
