### ISSUE TITLE
Newline missing in output when assertion fails

### ISSUE THREAD

**Issue by nrbrook** [google/googletest#2327]
When running a single test, for some reason a newline is removed when an assertion fails. For example:
```
Testing started at 11:57 ...
"<path>/runTests" --gtest_filter=ATAnalogInputConfigTests.testGetDataMultipleTwoConfigs:ATAnalogInputConfigTests/*.testGetDataMultipleTwoConfigs:*/ATAnalogInputConfigTests.testGetDataMultipleTwoConfigs/*:*/ATAnalogInputConfigTests/*.testGetDataMultipleTwoConfigs --gtest_color=no
Running main() from <path>/googletest/src/gtest_main.cc
Running 1 test from 1 test suite.<path>/ATAnalogInputConfigTests.cpp:547: Failure
Expected equality of these values:
  memcmp(data->bytes, expected, sizeof(expected))
    Which is: 16
  0

1 test from 1 test suite ran. (0 ms total)
Process finished with exit code 1
```
The problem here is the missing newline after the period in `Running 1 test from 1 test suite.<path>/ATAnalogInputConfigTests.cpp:547: Failure`
There is a newline in the `printf` statement on line 3171 of gtest.cc, but for some reason it seems to be missing in the output:
```
printf("Running %s from %s.\n",
```

Testing on https://github.com/google/googletest/commit/ee3aa831172090fd5442820f215cb04ab6062756
Running the tests in Clion 2019.1

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by nrbrook** [comment]
I'm not sure why it is happening though. The newline which should be printed is being removed from the output. Perhaps an ANSI escape code is moving the cursor?

**Comment by derekmauro** [comment]
I don't think this is something we are able to prioritize. If you figure out what it going on, let us know.
