### ISSUE TITLE
SetupTestSuite/TearDownTestSuite errors are logged but ignored

### ISSUE THREAD

**Issue by martijnvans** [google/googletest#2330]
This test will log the assert failure but pass (exit code 0) anyway:

```
class SetupFailTest : public ::testing::Test {
 protected:
  static void SetUpTestSuite() {
    ASSERT_EQ("", "SET_UP_FAIL");
  }
};
TEST_F(SetupFailTest, NoopPassingTest) {}
```

**Comment by gennadiycivil** [comment]
This is a [known behaviour](https://github.com/google/googletest/blob/8756ef905878f727e8122ba25f483c887cbc3c17/googletest/include/gtest/gtest.h#L425) unfortunately.

**Comment by martijnvans** [comment]
I recently added that comment to the file, at the request of the library owners. I'm actively working on a cleanup to remove places within google that are depending on this behavior. So far 50% of the teams have responded with fixes. So I still consider this a bug and aim to fix it.

**Comment by gennadiycivil** [comment]
@martijnvans Thank you so much!

**Comment by gennadiycivil** [comment]
Note:
The fix for this is coming *very soon*

**Comment by derekmauro** [comment]
I believe this is fixed. Re-open if it is not.
