### ISSUE TITLE
pump.py doesn't run with Python 3

### ISSUE THREAD

**Issue by adambadura** [google/googletest#2365]
Running [`pump.py`](../blob/master/googletest/scripts/pump.py) with Python 3 (`3.7.4` to be precise) results in the following error:
```
  File "pump.py", line 249
    print 'ERROR: %s expected at %s.' % (token_type, pos)
                                    ^
SyntaxError: invalid syntax
```

Since [Python 2.7 will not be maintained past 2020](https://pythonclock.org/) perhaps it is worth to rewrite the script for Python 3. (And possibly other scripts judging on comments at #2075 and version declared in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md#requirements-for-contributors).)

Perhaps it would be fairly easy to make it compatible with both versions?

What are the plans here considering the end of Python 2.7 maintenance?

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by kuzkry** [comment]
@gennadiycivil you haven't read or/and answered @adambadura's questions. I think he shouldn't waste his time for a likely rejected PR and your for reviewing his stuff.
