### ISSUE TITLE
Ubuntu 18.04 clang-9 head failing - release 1.8.1 works ok

### ISSUE THREAD

**Issue by mjhurd** [google/googletest#2369]
Current head generates SIGSEGVs on all test runs.

Just an FYI and thank you for the tool. Release 1.8.1 works fine and git checkout on that version is fine.

![image](https://user-images.githubusercontent.com/33476121/62443918-7dd05880-b79f-11e9-8cfd-e33b6d4d2ea3.png)

**Comment by gennadiycivil** [comment]
Thank you very much for this report. I would recommend to try to replicate this behaviour with our Travis CI. As it stands there is no actionable information here.

**Comment by EricWF** [comment]
The line numbers in your stack trace don't match up with master or 1.8.1. 

What revision did you build with? How did you build it? Can you provide your tests that are failing?

**Comment by EricWF** [comment]
I'm closing this bug because there's no actionable information.
You can reopen when providing the additional information.
