### ISSUE TITLE
gtest throws error even before the tests are run when linking to nodejs

### ISSUE THREAD

**Issue by jbcolme** [google/googletest#2370]
I'm working on some unit tests using c++ which are linked to nodejs. I worked on the tests, while in parallel someone updated the node version to 10.14.1. The tests, which were running before, now break even before running. An exception is thrown even if I just use a single test that returns true.
The exception is in gtest-port.h:

```
  void reset(T* p = NULL) {
    if (p != ptr_) {
      if (IsTrue(sizeof(T) > 0)) {  // Makes sure T is a complete type.
        delete ptr_;                      <-- here: Access violation executing location 
      }
      ptr_ = p;
    }
  }

```
The exception only happens if I link to a library that uses node. I'm trying to figure out if its a bug in my code, wrong build configuration (the project is large and the building is complex), or a bug in node. I'm using node 10.14.1, visual studio 15.9.14. 

The back trace of the exception is:

```
00000000016c7516()  Unknown
node.exe!00007ff612c6b828() Unknown
node.exe!00007ff612063034() Unknown
node.exe!00007ff612c26da1() Unknown 
UT_Addon.exe!std::basic_stringstream<char,std::char_traits<char>,std::allocator<char> >::`scalar deleting destructor'(unsigned int) C++
[Inline Frame] UT_Addon.exe!testing::internal::scoped_ptr<std::basic_stringstream<char,std::char_traits<char>,std::allocator<char> > >::reset(std::basic_stringstream<char,std::char_traits<char>,std::allocator<char> > *) Line 1200   C++
[Inline Frame] UT_Addon.exe!testing::internal::scoped_ptr<std::basic_stringstream<char,std::char_traits<char>,std::allocator<char> > >::{dtor}() Line 1185  C++
UT_Addon.exe!testing::internal::FlagToEnvVar(const char * flag) Line 1132   C++
UT_Addon.exe!testing::internal::BoolFromGTestEnv(const char * flag, bool default_value) Line 1190   C++
UT_Addon.exe!testing::`dynamic initializer for 'FLAGS_gtest_also_run_disabled_tests''() Line 197    C++
[External Code] 
```

The first call of the stack is from gtest.cc:

```
GTEST_DEFINE_bool_(
    also_run_disabled_tests,
    internal::BoolFromGTestEnv("also_run_disabled_tests", false),
    "Run disabled tests too, in addition to the tests normally being run.");
```

If I add these macros to gtest-all.cc I get a little further, but the program crashes anyway

```
#define GTEST_GET_BOOL_FROM_ENV_(flag, default) default
#define GTEST_GET_STRING_FROM_ENV_(flag, default) default
#define GTEST_GET_INT32_FROM_ENV_(flag, default) default
#define GTEST_CUSTOM_INIT_GOOGLE_TEST_FUNCTION_(argc, argv) return
```

What can lead to this behaviour?

**Comment by jbcolme** [comment]
Hi, 
This came up again. I'm trying to figure out what is going on. Maybe there are issues between certain node and gtests versions? Any hint will be appreciated. We are using node 10.16.3, have no idea how to get the gtest version, and visual studio 15.9.14

**Comment by asoffer** [comment]
This feels like an issue with linking multiple C runtimes. Are either NodeJS or GTest being used as DLLs? An access violation can occur if one DLL allocates memory using one C runtime and freed with another (since the two runtimes use their own heaps).

Can you provide full reproduction instructions? A minimal build script and instructions on how you obtained the versions of NodeJS and GTest that you're using?

**Comment by jbcolme** [comment]
I forgot this was still open. You are probably right. This was part of a pretty big project in which I was using dinamic libraries to include gtest. For some reason that I don't remember right now once the project was compiled as a static library the error was gone. So my guess is that we were not doing things properly in the first place. I had forgotten to close this ticket sorry.
