### ISSUE TITLE
Redirect Windows CRT assertions to stderr

### ISSUE THREAD

**Issue by pitrou** [google/googletest#2371]
By default, assertions in the Windows CRT in debug mode will pop up a dialog box and wait for user input (*). This is undesirable in automated testing setups (such as cloud-based CI services) as it then appears to hang without any useful indication of why the tests stopped running.

Instead, gtest could redirect those messages by default to stderr. See e.g. https://stackoverflow.com/questions/13943665/how-can-i-disable-the-debug-assertion-dialog-on-windows/31611163#31611163

(*) These can happen e.g. when passing an invalid file descriptor to a CRT function, or other kinds of invalid input

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by pitrou** [comment]
Opened a PR at https://github.com/google/googletest/pull/2372
