### ISSUE TITLE
Function Pointers Called Through InvokeArgument Fail to Handle Exceptions

### ISSUE THREAD

**Issue by szegel** [google/googletest#2379]
Hello Google Team,

I was trying to test our teams implementation of callbacks and ran into an issue. I have done my best to create a simplified example below:

```
// SUT.cpp
ExampleClass::init() {
pthread_create(&callback_thread_, 0, ExampleClass:: foo, this)
}

// foo is a private method of ExampleClass
void ExampleClass::foo() {
    while (true) {
        some_mockable_function_call()
    }
}

//TestSUT.cpp
TEST() {
std::runtime_error exception("Get Me out of callback");
EXPECT_CALL(mock, some_mockable_function_call()).WillOnce(Throw(exception));
EXPECT_CALL(mock_pthread, pthread_create(_,_,_,_).WillOnce(DoAll(IgnoreResult(InvokeArgument<2>((void*) 0)),  Return(1)));
EXPECT_THROW(sut.init(), std::runtime_error);

// continue test....
```
The output of this test case is:
```
./example_test --gtest_catch_exceptions=1
terminate called after throwing an instance of 'char const*'
Aborted
```

When I call the function pointer directly, I am able to catch my exceptions and my test works correctly.
```
//TestSUT.cpp
TEST() {
std::runtime_error exception("Get Me out of callback");
// Save off a function pointer to the callback, and fail init
void* the_callback;
EXPECT_CALL(mock_pthread, pthread_create(_,_,_,_).WillOnce(DoAll(SaveArg<2>(& the_callback), IgnoreResult(InvokeArgument<2>((void*) 0)),  Return(1)));
EXPECT_EQ(sut.init(), SOME_ERROR_CODE);

EXPECT_CALL(mock, some_mockable_function_call()).WillOnce(Throw(exception));
try {
((void (*)()) the_callback)();
catch (std::runtime& e) {
std::cout << "exception: " << e.what() << std::endl;
}
// continue test....
```
Output:
```
exception: Get Me out of callback
```

This leads me to believe that when I use InvokeArgument() on a function pointer (which has an EXPECT_CALL that throws), it is doing something which is not letting me catch exceptions.

PS: I am mocking pthread by using the linker trick so it grabs my mock pthread instead of the actual pthread.  I have verified that my mock is getting called, and there is only 1 thread running.

**Comment by EricWF** [comment]
Are you trying to throw an exception across threads?

**Comment by szegel** [comment]
I updated the issue to make it more clear, and simplified examples.

**Comment by EricWF** [comment]
Can you produce a reproducer without phreads?

**Comment by szegel** [comment]
Hey Eric,  I think I made this bug too early.  I do not fully understand what is going on yet. Let me continue to test and I will make a new more accurate issue when I fully understand the problem.
