### ISSUE TITLE
using Invoke instead of InvokeWithoutArgs results in very wild issues

### ISSUE THREAD

**Issue by travnick** [google/googletest#2389]
Let's have simple mock:
```
struct ReferenceAnnihilator
{
    MOCK_CONST_METHOD0(DestroyTheReference, const bool* const&());
};
```
and mock the object of it with:
```
    using Ptr = const bool*;
    EXPECT_CALL(annihilator, DestroyTheReference())
        .WillRepeatedly(Invoke(
            [ptr = Ptr{nullptr}]() -> const Ptr& //
            {
                return ptr; //
            }));
```
Then use it
```
            const bool* const& preciousReference = annihilator.DestroyTheReference();
            std::cout << preciousReference << std::endl;
```
it prints `7874b251` ⚠️  instead of `00000000` 

The MSVC debugger shows an interesting information:
```
| Name | Value | Type
| preciousReference | 0x7874b251 {ucrtbased.dll!free_dbg_nolock(void * const block, const int block_use), Line 1001} {true (131)} | const bool * const &
```

When using `InvokeWithoutArgs` instead, then it behaves as expected.

If I'm doing something improper, then I was unable to find any word about it's prohibited to use `Invoke` with lambda that takes no argument.

It's also quite easy to forget to use ` -> const Ptr&` in lambda, since without it the temporary copy is made, which is further used to initialize a reference - which results in another disaster.

Faced with:
google test: 1.8.3
Visual Studio 2017, version 15.7.6

**Comment by EricWF** [comment]
You're returning a reference to an object stored inside the lambda. But the lambda goes out of scope at the end of the call to `Invoke`, so the value it returns is garbage.

This appears to be undefined behavior in the example. Please re-open if you disagree.

**Comment by travnick** [comment]
The lambda **has** to be somehow **stored** by `Invoke` in google test mock internals, so the lambda will be invoked on *every* call to the `DestroyTheReference` of mock - and only on call to `DestroyTheReference`.

So as far as I can see, no dangling reference is returned.

**Comment by sbenzaquen** [comment]
On Thu, Aug 29, 2019 at 8:39 AM Mikołaj Milej <notifications@github.com>
wrote:

> The lambda *has* to be somehow *stored* by Invoke in google test mock
> internals, so the lambda will be invoked on *every* call to the
> DestroyTheReference of mock - and only on call to DestroyTheReference.
>
> So as far as I can see, no dangling reference is returned.
>
It does, but the action might be invoked on a temporary copy. That
temporary copy will return what will be a dangling pointer.

**Comment by travnick** [comment]
can you precisely describe which temporary copy do you mean?

**Comment by sbenzaquen** [comment]
On Fri, Oct 18, 2019 at 2:23 AM Mikołaj Milej <notifications@github.com>
wrote:

> can you precisely describe which temporary copy do you mean?
>
Executing an action could delete the mock object itself.
To avoid a reentrancy problem, the code copies the action object before it
is executed. That way the object we invoke persists even if the mock is
deleted.
That copy is the "temporary" copy. We copy the object, invoke it and then
throw away the copy.

**Comment by travnick** [comment]
Ok, got the point. And why `InvokeWithoutArgs` is working? Or it simply by an accident?

If it works like that, then it would be nice to have this behavior documented, since it's not obvious and quite error-prone
