### ISSUE TITLE
gtest-port.h use of #if prevents compilation with -Wundef

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#240]
```
What steps will reproduce the problem?
1. Build gtest
2. Write a test
3. Compile with -Wundef passed to g++

What is the expected output? What do you see instead?
I would expect a clean compile with no warnings emitted.  But the use of
#if with a mixture of macros, some defined and some that are not generates
a large number of warnings.

What version of the product are you using? On what operating system?
Version: Revision 357
OS: Linux (Ubuntu 9.10)

Please provide any additional information below, such as a code snippet.
I have attached a patch to gtest-port.h that fixes this issue by adding
definitions for all of the GTEST_OS_* macros.  They default to 0 and are
redefined to 1 as needed.

```

Original issue reported on code.google.com by `robot...@chromium.org` on 28 Dec 2009 at 12:55

Attachments:
- [gtest-port.h.patch](https://storage.googleapis.com/google-code-attachments/googletest/issue-240/comment-0/gtest-port.h.patch)

**Comment by MohSam1** [comment]
Hi, How can I download this patch, i face the same problem with the GCC and would like to evaluate if the patch works for me ?

**Comment by strenkwalder** [comment]
@GoogleCodeExporter 
I have the same issue and it breaks my CMAKE build in Linux.
I have a workaround but that's no permanent solution.

**Comment by ericoporto** [comment]
Hey, what's the solution to this with GCC ?
