### ISSUE TITLE
Using EXCEPT_THROW results in "ignoring return value" in GCC 8.3.0

### ISSUE THREAD

**Issue by krawacik3** [google/googletest#2416]
While testing a method with `EXPECT_THROW` results with `warning: ignoring return value of 'bool MyClass::isMatching() const', declared with attribute nodiscard [-Wunused-result]`.
The method declaration looks like this 
`[[nodiscard]] bool isMatching() const;`

For now, I've omitted this with 

```
bool a;
EXPECT_THROW(a = myClass.isMatching(), MyException);
```
but is there any 'cleaner' solution?

**Comment by brandl-muc** [comment]
For one thing you can join declaration and assignment, thus not polluting your scope:
`EXPECT_THROW(auto const a = myClass.isMatching(), MyException);`

Less annoying for me is using cast to `void`:
`EXPECT_THROW((void) myClass.isMatching(), MyException);`

Actually I think the cast to `void` should be integrated into the `*_THROW`-Macros. I would try to create a pull request if this is desired.

**Comment by sbenzaquen** [comment]
On Tue, Dec 10, 2019 at 6:45 AM Matthäus Brandl <notifications@github.com>
wrote:

> For one thing you can join declaration and assignment, thus not polluting
> your scope:
> EXPECT_THROW(auto const a = myClass.isMatching(), MyException);
>
> Less annoying for me is using cast to void:
> EXPECT_THROW((void) myClass.isMatching(), MyException);
>
> Actually I think the cast to void should be integrated into the *_THROW-Macros.
> I would try to create a pull request if this is desired.
>
This has been proposed before, but sadly it doesn't work.
We can't add the cast to void by default, because EXPECT_THROW takes a
statement and not an expression.
Which is why your first example works in the first place.

**Comment by asoffer** [comment]
Unfortunately I don't think it's feasible to fix this. It requires detecting whether the first argument to EXPECT_THROW is a statement or an expression. I do not believe this is possible. Adding the `bool b =` inside the macro, or cast to void is the appropriate workaround.
