### ISSUE TITLE
fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by Mrzhuzy** [google/googletest#2423]
/home/ktgs/4.Trunk/ext/googletest/googletest/src/gtest_main.cc:33:20: fatal error: Python.h: No such file or directory
compilation terminated.
googlemock/gtest/CMakeFiles/gtest_main.dir/build.make:62: recipe for target 'googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o' failed
make[2]: *** [googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o] Error 1
CMakeFiles/Makefile2:220: recipe for target 'googlemock/gtest/CMakeFiles/gtest_main.dir/all' failed
make[1]: *** [googlemock/gtest/CMakeFiles/gtest_main.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by EricWF** [comment]
This bug report isn't actionable for a number of reasons.

First, although the full error text is appreciated, it doesn't inform why you think this is a bug, or what you expect to be happening. This is a clear symptom of the python development packages not being installed. Knowing that, what can Google Test do to help?

Second, `gtest_main.cc` has never included `Python.h`. So I have no idea how you ended up with this error, nor how I can help.

Please re-open this bug with additional information.
