### ISSUE TITLE
gmock_gen.py uses old MOCK_METHODN macros

### ISSUE THREAD

**Issue by Valloric** [google/googletest#2434]
Using the `gmock_gen.py` script to generate a mock class generates one that uses the deprecated `MOCK_METHODN` macros (where N is a number) instead of the newer `MOCK_METHOD` macro.

Location: https://github.com/google/googletest/blob/eb56ee5a28b41fcc244205cc18ff7847f7c6b7bc/googlemock/scripts/generator/cpp/gmock_class.py#L95

**Comment by gennadiycivil** [comment]
These scripts are[ not supported](https://github.com/google/googletest/blob/master/googlemock/scripts/README.md). Feel free to open a PR to fix if this creates an issue for you.
