### ISSUE TITLE
Unable to print derived class while operator<< for base class defined

### ISSUE THREAD

**Issue by alancprc** [google/googletest#2435]
I'm new to use google test and not sure it's a problem with google test or the
way I use it.

`class D` is derived from `class B`, and `operator<<` for `class B` is defined.
with this, `std::cout` is able to print B and D, as shown in test `PrintByCout`.
However, when two object of `class D` is compared using `EXPECT_EQ`, it just
print the byte data instead of using `operator<<` for `class B`.

Only when `operator<<` for `class D` is defined `class D` objects are properly
printed.

The code for testing is shown as follows, along with the execution result.
Tested on v1.8.0/v1.8.1/1.8.x/master, with the same result.

```
#include <iostream>
#include <string>

class B {
 public:
  B(std::string name = "class B") : name_(name) {}
  bool operator==(const B& rhs) const { return name_ == rhs.Name(); }
  std::string Name()const { return name_;}

 private:
  std::string name_;
};

class D : public B {
 public:
  D(std::string name = "class D") : B(name) {}
};

std::ostream& operator<<(std::ostream& os, const B& b) {
  os << b.Name();
  return os;
}

/* without this operator<< for D, EXPECT_EQ won't print D properly */
/*
std::ostream& operator<<(std::ostream& os, const D& b) {
  os << b.Name();
  return os;
}
*/

#include <gtest/gtest.h>

TEST(Print, PrintByCout) { std::cout << B() << std::endl << D() << std::endl; }

TEST(Print, PrintB) {
  B obj1("b1");
  B obj2("b2");
  EXPECT_EQ(obj1, obj2);
}

TEST(Print, PrintD) {
  D obj1("d1");
  D obj2("d2");
  EXPECT_EQ(obj1, obj2);
}
```
output :
```
Running main() from ./googletest/googletest/src/gtest_main.cc
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from Print
[ RUN      ] Print.PrintByCout
class B
class D
[       OK ] Print.PrintByCout (0 ms)
[ RUN      ] Print.PrintB
sample.cpp:39: Failure
Expected equality of these values:
  obj1
    Which is: b1
  obj2
    Which is: b2
[  FAILED  ] Print.PrintB (0 ms)
[ RUN      ] Print.PrintD
sample.cpp:45: Failure
Expected equality of these values:
  obj1
    Which is: 32-byte object <90-64 84-4C FF-7F 00-00 02-00 00-00 00-00 00-00 64-31 00-6E 39-56 00-00 E0-E1 75-6E 39-56 00-00>
  obj2
    Which is: 32-byte object <B0-64 84-4C FF-7F 00-00 02-00 00-00 00-00 00-00 64-32 00-4C FF-7F 00-00 40-7D D9-7F 87-7F 00-00>
[  FAILED  ] Print.PrintD (0 ms)
[----------] 3 tests from Print (0 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test case ran. (0 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] Print.PrintB
[  FAILED  ] Print.PrintD
```

**Comment by coder-shang** [comment]
hi, please look into 

gtest-printers.h
// Prints the given value to the given ostream.  If the value is a
// protocol message, its debug string is printed; if it's an enum or
// of a type implicitly convertible to BiggestInt, it's printed as an
// integer; otherwise the bytes in the value are printed.  This is
// what UniversalPrinter<T>::Print() does when it knows nothing about
// type T and T has neither << operator nor PrintTo().
//
// A user can override this behavior for a class type Foo by defining
// a << operator in the namespace where Foo is defined.

and gtest_printer.cc
void PrintBytesInObjectToImpl(const unsigned char* obj_bytes, size_t count, ostream* os)

I think what you issued is not a problem. It's just an author's own realization.

**Comment by kuzkry** [comment]
Hey @alancprc!
Unfortunately I doubt we could do something with it. Please analyse this simplified example:
```c++
#include <iostream>

struct B {};
struct D : B {};

template <typename T>
void foo(T) {
    // This is something that works under the hood of GTest.
    // I think we cannot change this as we don't know what types
    // users will try to print.
    std::cout << "Not what we wanted\n";
}

void foo(const B&) {
    // This is what we want.
    std::cout << "Good\n";
}

int main() {
    foo(D{}); // oops, a function template is a better match
}
```

What comes to my mind, in your example you could write:
```c++
/* template header */
std::ostream& operator<<(std::ostream& os, const T& b) {
  os << b.Name();
  return os;
}
```
where _template header_ can be either:
`template <typename T, typename = typename std::enable_if<std::is_base_of<B, T>::value>::type>` (C++11)
`template <typename T, typename = std::enable_if_t<std::is_base_of<B, T>::value>>` (C++14)
`template <typename T, typename = std::enable_if_t<std::is_base_of_v<B, T>>>` (C++17)

I know, it's not the nicest thing ever.

**Comment by alancprc** [comment]
@kuzkry Thanks for your clear explanation. Your workaround with a template `operator<<` is nice enough for me.
Thank you.

**Comment by sbenzaquen** [comment]
Actually, we can fix this problem. We just hadn't taken the time to do it yet.
The probing we use is not very good, but it was the best we could do before C++11.
Now we can do better since we require C++11.

We are trying to add an overload to the hope ours has the worse ranking. This will always trip on cases like this.
What we should be doing instead is decltype-sfinae to detect the operator and then dispatch based on it.

Eg:

```
template <typename T>
auto TryStreamOpImpl(std::ostream* os, const T& value, int) ->
  decltype(*os << value) {
  return *os << value;
}

template <typename T>
void TryStreamOpImpl(std::ostream* os, const T& value, char) {
  // Fallback for byte printing
}

template <typename T>
void TryStreamOp(std::ostream* os, const T& value) {
  TryStreamOpImpl(os, value, 0);
}
```

**Comment by kuzkry** [comment]
In my example I wanted to simplify the explanation why it didn't work for the author.
In reality it's more complicated than that because it works due to ADL. But if you have an idea, go ahead! ;)

**Comment by sbenzaquen** [comment]
I'm working on a fix for this.
It does change the way the printer dispatches, so it needs a few tries to make sure we don't break much.
Unfortunately, this will break some code. Enabling this will cause new `operator<<` overloads to be considered, which is the goal, but it can backfire in some bad cases.

**Comment by asoffer** [comment]
I believe this should be fixed now:
https://github.com/google/googletest/blob/6c58c11d5497b6ee1df3cb400ce30deb72fc28c0/googletest/test/googletest-printers-test.cc#L1253

Please reopen if this is still an issue.
