### ISSUE TITLE
GTest is unable to print C++17 types

### ISSUE THREAD

**Issue by kuzkry** [google/googletest#2437]
```c++
#include <optional>
#include <string>

#include <gmock/gmock.h>
#include <gtest/gtest.h>

using my_type = std::optional<std::string>;

class Mock {
public:
  MOCK_METHOD(my_type, foo, (), ());
};

TEST(Foo, Test)
{
  my_type const lol;
  Mock mock;

  ON_CALL(mock, foo()).WillByDefault(::testing::Return(lol));

  mock.foo();
}
```

When my_type is:
* `std::any`, `16-byte object <B2-AA 19-00 00-00 00-00 51-58 1F-00 00-00 00-00>` is printed and there are no Valgrind complains
* `std::optional<std::string>`, `40-byte object <D0-90 DA-05 00-00 00-00 13-00 00-00 00-00 00-00 13-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 01-00 00-00 00-00 00-00>` is printed and Valgrind reports problems
* `std::string_view`, `{ 'n' (110, 0x6E), 'o' (111, 0x6F), ' ' (32, 0x20), 'e' (101, 0x65), 'a' (97, 0x61), 's' (115, 0x73), 't' (116, 0x74), 'e' (101, 0x65), 'r' (114, 0x72), ' ' (32, 0x20), 'e' (101, 0x65), 'g' (103, 0x67), 'g' (103, 0x67), 's' (115, 0x73), ' ' (32, 0x20), 'h' (104, 0x68), 'e' (101, 0x65), 'r' (114, 0x72), 'e' (101, 0x65) }` is printed and there are no Valgrind complains
* `std::variant<std::string>`,  `40-byte object <D0-90 DA-05 00-00 00-00 13-00 00-00 00-00 00-00 13-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00>` is printed and Valgrind reports problems

These Valgrind complains for optional and variant are:
> Use of uninitialised value of size 8
> Conditional jump or move depends on uninitialised value(s)

**Comment by davidzchen** [comment]
I am also getting the same issue with `absl::string_view`

**Comment by asoffer** [comment]
I believe this should be fixed by #2436 .
https://godbolt.org/z/xsrd3P
Please reopen if this is still an issue.

**Comment by kuzkry** [comment]
Sorry, I forgot to close this one down :) No issues here.

**Comment by marehr** [comment]
`std::nullopt` is still not printable.
