### ISSUE TITLE
Feature request: Visual Studio test adapter for C++ Linux projects

### ISSUE THREAD

**Issue by aborisovich** [google/googletest#2441]
Dear sirs,
For some time now, Visual Studio 2017 and 2019 offers C++ workloads for Linux system.
It allows to create linux project in the IDE, compile its content on remote machine with GCC (copying sources and libs to remote device) and run/debug it on the remote device.
On the other hand, test adapters for GTest had been created by MS ("Test Adapter For Google Test") and external parties ("Google Test Adapter Extension") to integrate Google Test into VS IDE and Test Explorer window. I attempted to implement gtest adapter for the C++ linux project but failed with following results:
- executable on linux may be build successfully, that runs tests and outputs them to the stdout.
- this executable on linux is not discovered as test in Test Explorer (is not integrated into IDE).

Please provide a test adapter for linux projects in VS2017 and 2019.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by asoffer** [comment]
@aborisovich a minor but important nit-pick: We are not all "sirs." Our team has women and non-binary members as well.

Regarding the test adaptor, this is outside the scope of what GoogleTest intends to provide. This may be something that can be provided as a contributor extension if you are inclined to provide one.
