### ISSUE TITLE
Implies matcher

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [google/googletest#2445]
Found myself just now wanting to write
```C++
EXPECT_THAT(my_boolean, Implies(my_other_boolean));
```
rather than
```C++
EXPECT_TRUE(!my_boolean || my_other_boolean);
```
. I didn't see it on the cheat sheet - it's not around somewhere and I missed it, right?

**Comment by asoffer** [comment]
We do not have one of these. It could be built with a custom matcher. Alternatively,

```
if (my_boolean) {
  EXPECT_TRUE(my_other_boolean);
}
```

Given these options, I don't believe it makes sense for googletest to add support for a new matcher.
