### ISSUE TITLE
`gtest_environment_test.cc` invokes `RUN_ALL_TESTS()` multiple times

### ISSUE THREAD

**Issue by jrhemstad** [google/googletest#2447]
In [gtest_environment_test.cc](https://github.com/google/googletest/blob/9311242db422dd6f24c8e764847fe5d70d0d4859/googletest/test/gtest_environment_test.cc) global environments are being tested by repeatedly creating a new `testing::Environment` and then calling `RunAllTests()`, which invokes `RUN_ALL_TESTS()`. 

The pattern looks like this:
```
testing::AddGlobalTestEnvironment(new MyEnvironment);
RunAllTests();
testing::AddGlobalTestEnvironment(new OtherEnvironment);
RunAllTests();
```

However, the documentation expressly forbids calling `RUN_ALL_TESTS()` more than once:
> Also, you should call RUN_ALL_TESTS() only once. Calling it more than once conflicts with some advanced googletest features (e.g. thread-safe death tests) and thus is not supported.

**Therefore, is the pattern used in `gtest_environment_test.cc` safe?** 

I'd like to do something similar in my own tests if possible.

**Comment by derekmauro** [comment]
This works for us, but the gist of the issue is that we reserve the right to change the behavior. This is ok for us, because we can update our own tests if we need to. My advice is not to rely on this working forever.
