### ISSUE TITLE
Why not move to C++ attribute instead of MACRO

### ISSUE THREAD

**Issue by soroshsabz** [google/googletest#2449]
ITNOA

As I know in many testing framework in another language like Java and C# we use annotation or attribute to mark a function is for test or like xUnit framework we use annotation to declare `theory` and etc.

My question is why gtest not move to using C++ attribute for many case of MACRO using like `TEST` or `INSTANTIATE_TEST_CASE_P` and etc. for writing user defined C++17 attribute we can use [foonathan example](https://foonathan.net/meetingcpp2017.html)

thanks

**Comment by kuzkry** [comment]
Hi!

If I understood how [cppast](https://github.com/foonathan/cppast) works correctly, I see two major problems:
1) our users are required to have a C++11-standard-compliant compiler and this library relies on a C++17 new amendment to the standard which is:
> Any attribute-token that is not recognized by the implementation is ignored.
2) cppast uses clang which is an additional dependency for us. IMHO this would be an overkill for a test framework to rely on a specific compiler.

Btw. thank you for the issue, I haven't heard about this tool and I might wanna use it in my projects :)

**Comment by asoffer** [comment]
Hi Soroshsabz,

This is an interesting idea, but kuzkry has identified two really important reasons why it would be difficult to integrate into googletest. This would be a big breaking change and so the benefit would have to be enough to offset the pain this would cause for googletest users.

I strongly encourage you to explore this sort of things outside of googletest. It looks fascinating and I don't think we as a C++ community fully understand how powerful it will be yet!
