### ISSUE TITLE
Missing Matcher documentation

### ISSUE THREAD

**Issue by cfsteefel** [google/googletest#2463]
In both the gMock and gtest documentations, a set of Matchers is described, and links are provided that suggest they should go to a complete listing of the Matchers. However, both just link back to the gMock cookbook itself.
The gMock link is located in the first line under the heading here: https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md#using-predicates-as-matchers
The gtest link can be seen here, described as a list of all matchers:
https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#asserting-using-gmock-matchers
The bad link can be seen here: https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md#MatcherList

Would it be possible to update these links to either point to the correct location (if it exists), or delete them?

**Comment by CJ-Johnson** [comment]
Thank you for the issue! This has now been addressed internally and will be fixed in the next OSS push. (333288356)

**Comment by ybgunjal2000** [comment]
Please unsubscribe me from your mailing list
