### ISSUE TITLE
ASSERT_TRUE and ASSERT_FALSE on bools with undefined behavior

### ISSUE THREAD

**Issue by jpetrucciani** [google/googletest#2467]
This is a pretty odd issue that I've found, and it's probably not common to run into this (as it requires that you have a function with a return type, but without a return statement, and you will get a compiler warning for that), but I figured I'd file an issue so that you all are aware! I've looked through the docs quite a bit, and the other issues for any sort of explanation and I wasn't able to figure it out - although if this is just a case of me misunderstanding the use of some of the macros, feel free to close this issue!

## Steps to reproduce

0. Have a function with a pointer argument with a return type declared, but with an empty body (in my case, a function that returns bool)
1. Call this function, storing the return value into a variable (in my case, `bool result`)
2. Use `ASSERT_TRUE` or `ASSERT_FALSE` on this (undefined behavior) value `result`
3. Both `ASSERT_TRUE` and `ASSERT_FALSE` on this value `result` seem to pass assertion

## Code to reproduce
**CMakeLists.txt**
```cmake
project(FooTest)
cmake_minimum_required(VERSION 2.6)

# Locate GTest
find_package(GTest REQUIRED)
include_directories(${GTEST_INCLUDE_DIRS})

# Link runTests with what we want to test and the GTest and pthread library
add_executable(runTests tests.cpp)
target_link_libraries(runTests ${GTEST_LIBRARIES} pthread)
```
**tests.cpp**
```cpp
#include "gtest/gtest.h"
#include "gmock/gmock.h"

bool foo(char * x) {}

namespace {
  class FooTest: public::testing::Test {
    protected: FooTest() {}
    virtual~FooTest() {}
    virtual void SetUp() {}
    virtual void TearDown() {}
  };
  TEST(FooTest, tests_foo) {
    char x = 'x';
    bool result = foo(&x);
    printf("%d", result);
    ASSERT_TRUE(result);
    ASSERT_FALSE(result);
    ASSERT_EQ(result, true);
  }
}

int main(int argc, char ** argv) {
  ::testing::InitGoogleTest( & argc, argv);
  return RUN_ALL_TESTS();
}
```
**Output**
```
# cmake CMakeLists.txt
# make
# ./runTests
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from FooTest
[ RUN      ] FooTest.tests_foo
141
/tmp/tests.cpp:19: Failure
Value of: result
  Actual: false
Expected: true
[  FAILED  ] FooTest.tests_foo (0 ms)
[----------] 1 test from FooTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] FooTest.tests_foo

 1 FAILED TEST
```

## Current Behavior
Using `ASSERT_TRUE` and `ASSERT_FALSE` both seem to be passing when given this undefined value, even though this value is probably neither `true` nor `false` (C/C++ [will encounter undefined behavior](https://stackoverflow.com/questions/9936011/if-a-function-returns-no-value-with-a-valid-return-type-is-it-okay-to-for-the/9936090#9936090) if allowed to flow off the end of a value-returning function).

### Workaround
It seems that the `ASSERT_EQ` macro can be used as a workaround to get the test to actually fail - however, this creates a weird error message where both values claim to be `true`:
```
Expected equality of these values:
  result
    Which is: true
  true
```

## Expected Behavior
I'm not sure exactly what I'd expect in this case, and also this isn't going to be a common type of function being tested. I would probably expect either `ASSERT_TRUE` or `ASSERT_FALSE` to fail (or both potentially!) as this value being tested is most likely not either value (although perhaps I'm understanding these macros incorrectly! I'd figure you'd be able to pass a bool straight into them).

## Environment Details
```bash
Ubuntu 18.04.3 LTS Bionic
cmake version 3.15.3
GNU Make 4.1
g++ (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0

# uname -a
Linux $HOSTNAME 4.15.0-1048-aws #50-Ubuntu SMP Wed Sep 4 22:03:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

our pinned googletest commit hash: 33a0d4f6d76a0ed6061e612848532cba82d42870
also tried on latest googletest commit hash: f2fb48c3b3d79a75a88a99fba6576b25d42ec528
```

**Comment by sbenzaquen** [comment]
On Fri, Sep 20, 2019 at 12:11 PM Jacobi Petrucciani <
notifications@github.com> wrote:

> This is a pretty odd issue that I've found, and it's probably not common
> to run into this (as it requires that you have a function with a return
> type, but without a return statement, and you will get a compiler warning
> for that), but I figured I'd file an issue so that you all are aware! I've
> looked through the docs quite a bit, and the other issues for any sort of
> explanation and I wasn't able to figure it out - although if this is just a
> case of me misunderstanding the use of some of the macros, feel free to
> close this issue!
> Steps to reproduce
>
>    1. Have a function with a pointer argument with a return type
>    declared, but with an empty body (in my case, a function that returns bool)
>    2. Call this function, storing the return value into a variable (in my
>    case, bool result)
>    3. Use ASSERT_TRUE or ASSERT_FALSE on this (undefined behavior) value
>    result
>    4. Both ASSERT_TRUE and ASSERT_FALSE on this value result seem to pass
>    assertion
>
> Code to reproduce
>
> *CMakeLists.txt*
>
> project(FooTest)cmake_minimum_required(VERSION 2.6)
> # Locate GTestfind_package(GTest REQUIRED)include_directories(${GTEST_INCLUDE_DIRS})
> # Link runTests with what we want to test and the GTest and pthread libraryadd_executable(runTests tests.cpp)target_link_libraries(runTests ${GTEST_LIBRARIES} pthread)
>
> *tests.cpp*
>
> #include "gtest/gtest.h"
> #include "gmock/gmock.h"
> bool foo(char * x) {}
> namespace {
>   class FooTest: public::testing::Test {
>     protected: FooTest() {}
>     virtual~FooTest() {}
>     virtual void SetUp() {}
>     virtual void TearDown() {}
>   };
>   TEST(FooTest, tests_foo) {
>     char x = 'x';
>     bool result = foo(&x);
>     printf("%d", result);
>     ASSERT_TRUE(result);
>     ASSERT_FALSE(result);
>     ASSERT_EQ(result, true);
>   }
> }
> int main(int argc, char ** argv) {
>   ::testing::InitGoogleTest( & argc, argv);
>   return RUN_ALL_TESTS();
> }
>
> *Output*
>
> # cmake CMakeLists.txt
> # make
> # ./runTests
> [==========] Running 1 test from 1 test suite.
> [----------] Global test environment set-up.
> [----------] 1 test from FooTest
> [ RUN      ] FooTest.tests_foo
> 141
> /tmp/tests.cpp:19: Failure
> Value of: result
>   Actual: false
> Expected: true
> [  FAILED  ] FooTest.tests_foo (0 ms)
> [----------] 1 test from FooTest (0 ms total)
>
> [----------] Global test environment tear-down
> [==========] 1 test from 1 test suite ran. (0 ms total)
> [  PASSED  ] 0 tests.
> [  FAILED  ] 1 test, listed below:
> [  FAILED  ] FooTest.tests_foo
>
>  1 FAILED TEST
>
> Current Behavior
>
> Using ASSERT_TRUE and ASSERT_FALSE both seem to be passing when given
> this undefined value, even though this value is probably neither true nor
> false (C/C++ will encounter undefined behavior
> <https://stackoverflow.com/questions/9936011/if-a-function-returns-no-value-with-a-valid-return-type-is-it-okay-to-for-the/9936090#9936090>
> if allowed to flow off the end of a value-returning function).
> Workaround
>
> It seems that the ASSERT_EQ macro can be used as a workaround to get the
> test to actually fail - however, this creates a weird error message where
> both values claim to be true:
>
> Expected equality of these values:
>   result
>     Which is: true
>   true
>
> Expected Behavior
>
> I'm not sure exactly what I'd expect in this case, and also this isn't
> going to be a common type of function being tested. I would probably expect
> either ASSERT_TRUE or ASSERT_FALSE to fail (or both potentially!) as this
> value being tested is most likely not either value (although perhaps I'm
> understanding these macros incorrectly! I'd figure you'd be able to pass a
> bool straight into them).
>
This is completely out of the hands of GoogleTest.
You have undefined behavior in your program even before you get to the body
of the EXPECT_* macros. All bets are off.
I suggest running your tests with the different sanitizers to find these
issues.
Eg, https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html should find
this particular problem.

For this particular UB, an uninitialized bool could manifest as false,
true, both and none all at the same time.

**Comment by jpetrucciani** [comment]
Ah okay, thank you for your time!

We are using googletest for unit testing arbitrary student submissions, so we do end up with quite a bit of undefined behavior in submitted code. Sounds like we'll need to incorporate some other tools to make this a bit easier to deal with. Thank you for the included link!

**Comment by sbenzaquen** [comment]
No problem.
Thanks for the detailed report!
