### ISSUE TITLE
Rename v1.10.x tag to v1.10.0 or release-1.10.0

### ISSUE THREAD

**Issue by jbeich** [google/googletest#2488]
`v1.10.x` is currently both a tag name and a branch name:
https://github.com/google/googletest/tags
https://github.com/google/googletest/branches

**Comment by jbeich** [comment]
v1.10.x is currently both a tag name and a branch name.

**Comment by thomthom** [comment]
`release-1.10.0` would be consistent with existing tags.

**Comment by gennadiycivil** [comment]
Sure, thank you
