### ISSUE TITLE
-Wdangling-else error on GCC 6.5

### ISSUE THREAD

**Issue by gkarlos** [google/googletest#2492]
I recently downgraded GCC to 6.5 and i am getting the following error:
`cc1plus: error: -Werror=dangling-else: no option -Wdangling-else`
I guess `-Wdangling-else` is a GCC 7 feature. Is there any way around it?

**Comment by gkarlos** [comment]
Nevermind. It was the leftover build folder, which i guess had makefiles for gcc 7 with that flag.

**Comment by jamesthesken** [comment]
@gkarlos how did you resolve this error? Thank you
