### ISSUE TITLE
Release 1.10 did not fix the '-Wsuggest-override' warnings!

### ISSUE THREAD

**Issue by roblub** [google/googletest#2493]
I know similar bugs were reported in the past, but they all appear to be closed... However it looks like the bug is still there even in gtest 1.10: while compiling application that use gtest+gmock and '-Wsuggest-override' warning flag, the compiler still complains that the override keyword is missing on lines that contain macros like MOCK_METHOD. MOCK_CONST_METHOD/TYPED_TEST, etc. ...

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by roblub** [comment]
I've carefully read your comment from https://github.com/google/googletest/issues/2489#issuecomment-538759628 about the "new powerful MOCK_METHOD macro", and I've  checked that switching to it fixes the warning (moreover I've discovered the macro accepts "final" keyword, what is not documented) - thank you for this. I'm not sure what to do with the warnings in TYPED_TEST  yet - I'll look at it later.

**Comment by roblub** [comment]
>  The best way to approach this would be to create a proper PR and submit it for consideration.

Done. Please let me know, what do you think about it.

**Comment by gennadiycivil** [comment]
Need CLA, otherwise we can not consider the changes
