### ISSUE TITLE
Release 1.10 did not contain proper changelog...

### ISSUE THREAD

**Issue by roblub** [google/googletest#2494]
The https://github.com/google/googletest/releases/tag/v1.10.x contains shows something like this:

```
 v1.10.x

    703bd9c

v1.10.x: Googletest export

@invalid-email-address invalid-email-address tagged this 3 days ago · 1 commit to master since this tag

Release Googletest 1.10

PiperOrigin-RevId: 272658347


```
Which makes me wondering if it is an official release. It looks like somebody hacked into your system and made a release....

Not to mention that it is hard to get the list from changes from git, because majority of commits reads "Googletest export".

**Comment by gennadiycivil** [comment]
Duplicate, https://github.com/google/googletest/issues/2489
