### ISSUE TITLE
Switching from installed GoogleTest to CMake add_subdirectory approach breaks other dependecy

### ISSUE THREAD

**Issue by JanHett** [google/googletest#2501]
I have a project using GTest and OpenImageIO (OIIO). Up until now GTest was expected to be installed on the system and I was including it in my CMake config with `find_package(GTest REQUIRED)` and then linking to with `target_link_libraries(tests GTest::GTest)`.
I wanted to change this to include GTest from a subdirectory. Hence, I replaced `find_package` with `add_subdirectory(external/googletest external/googletest/build EXCLUDE_FROM_ALL)` and linked to it with `target_link_libraries(tests gtest)`.

On the GTest side, everything seems to work fine. The library compiles and the target `gtest` is available. However, somehow using the target from the subdirectory instead of the global install in the `target_link_libraries` command causes the error message `fatal error: 'OpenImageIO/imageio.h' file not found`.

I am not sure if this is an issue with GoogleTest or OpenImageIO. I decided to post this issue here since the change in the way GTest is linked was causing the issue (`GTest::GTest` works, `gtest` causes the above error to appear).

Is there a difference between the two "versions" of GTest that could explain this issue?

Additional information:
OS: macOS 10.14.6
Compiler: clang
C++ standard: 17
OIIO is linked with `target_link_libraries(tests OpenImageIO ${CMAKE_DL_LIBS})`

**Comment by asoffer** [comment]
Hi Jan, I expect the include paths are different and that when both GTest and OIIO were used, they found each other because they were both in the system path, but now the subdirectory gtest doesn't explore the same paths.
