### ISSUE TITLE
MOCK_METHOD chokes on function pointer return types

### ISSUE THREAD

**Issue by thejcannon** [google/googletest#2502]
I've tried both `MOCK_METHOD(int(*)(), foobar, ())` and `MOCK_METHOD((int(*)()), foobar, ())` but alas it is too much for `MOCK_METHOD`. You will eventually get "function cannot return function type" (or something similar).

Using typedefs or type aliases or `decltype(&my_func)` all work.

This is probably because when a function returns a function pointer, the form `Ret (Args...)` isn't valid anymore. It is of some ugly form like `FnPtrRetType (*(MyArgs...))(FnPtrArgs...)` so all the usages of `Ret (Args...)` aren't valid.

Not sure what can be done other than type aliasing the return type before you use it.

**Comment by asoffer** [comment]
Matt Calabrese proposed an elegant solution: The macro should use `identity_t<ReturnType>` as the return type, where 
```
template <typename T>
using identity_t = T;
```

This should be available in the next day or two.

**Comment by asoffer** [comment]
This should be fixed now.
