### ISSUE TITLE
Avoid test class name collisions.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#254]
```
When I define two test classes with the same name, but place them in
separate namespaces, gtest spits out an error that the two test suites
collided: 

namespace A {
class MyTest : public testing::Test {}
TEST_F( MyTest, TestBlah ) {}
}

namespace B {
class MyTest : public testing::Test {}
TEST_F( MyTest, TestBarf ) {}
}

I took a brief look at the implementation of TEST_F to see why. It looks
like down in the GTEST_TEST() (which is called by TEST_F()), we are
registering the auto-generated test class using the fixture name only.
Would it be possible to augment this with the namespace as well to avoid
collisions? Something like:

TEST_F( A, MyTest, TestBlah ) {}
TEST_F( B, MyTest, TestBarf ) {}



```

Original issue reported on code.google.com by `JCYo...@gmail.com` on 12 Feb 2010 at 10:58

**Comment by knutpett** [comment]
When having a large C++ code base and ditto large testing suite, arranging code in namespaces is a big advantage. It would be very good if GTEST could (optionally) support namespaces as suggested by the original poster. I don't consider prefixing fixtures and/or tests a very good solution. Could you please reconsider your decision and reopen the issue? And/or - whould you accept a patch?
