### ISSUE TITLE
How to share test cases between suites?

### ISSUE THREAD

**Issue by adambadura** [google/googletest#2559]
I have a use case, where it would be beneficial to share test cases between different suites. It came out in type-parametrized tests but perhaps could be generalized.

Let me illustrate it with sample code build around the [Type-Parameterized Tests](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#type-parameterized-tests) samples.
```c++
template <typename T>
class FooTest : public ::testing::Test {
  ...
};

TYPED_TEST_SUITE_P(FooTest);

TYPED_TEST_P(FooTest, HasPropertyA) { ... }
TYPED_TEST_P(FooTest, HasPropertyB) { ... }
TYPED_TEST_P(FooTest, HasPropertyC) { ... }
```
Now, some of my types (let's call them "primary") have all three properties. While other types (let's call them "secondary") have only first two properties. I would like to express it like this:
```c++
REGISTER_TYPED_TEST_SUITE_P(FooTestPrimary,
                            HasPropertyA, HasPropertyB, HasPropertyC);

REGISTER_TYPED_TEST_SUITE_P(FooTestSecondary,
                            HasPropertyA, HasPropertyB);
```
so that later I could do:
```c++
using MyPrimaryTypes = ::testing::Types<char, int, unsigned int>;
INSTANTIATE_TYPED_TEST_SUITE_P(MyPrimary, FooTestPrimary, MyPrimaryTypes);

using MySecondaryTypes = ::testing::Types<float, double>;
INSTANTIATE_TYPED_TEST_SUITE_P(MySecondary, FooTestSecondary, MySecondaryTypes );
```

---

The only way to achieve something close to it (without repeating tests) was to define sets differently. I would define a secondary test suite for properties A and B and primary test suite for property C. Then with secondary types, I would `INSTANTIATE_TYPED_TEST_SUITE_P` only the secondary test suite. While with primary types I would `INSTANTIATE_TYPED_TEST_SUITE_P` twice, to cover both suites.

However, this seems harder to maintain and less readable.

Another approach would be to move test cases definitions to fixture class methods. Then I would derive both suites from that class and have test cases repeated, but having minimal repetition possible. This results in clients using just one suite as desired but doesn't avoid some repetition.

---

An interesting feature of being able to share test cases between suites is a nice move towards contract testing. We could define a single test case which verifies some generic properties of a type or interface and then only append those tests to suites.

---

So, what means do we have (except those already listed) to achieve sharing test cases between suites?

If none, do we perhaps want to have such a feature? I could try to dive into the code and see if it is doable. But it seems (at first glance) possibly a complex task so I would rather prefer to know whether it has any chance to be accepted.

**Comment by asoffer** [comment]
Thanks for bringing this to our attention. The TL;DR is I expect the added complexity for having such a feature wouldn't pay off. Avoiding duplication is not something we typically aim for in tests.

As a workaround, could you make a base class for the secondary types and inherit off it for the primary types (with the extra added HasPropertyC?

Alternatively, you could separate out each property into it's own test suite and mention which ones you want in the INSTANTIATE macro?

**Comment by adambadura** [comment]
> The TL;DR is I expect the added complexity for having such a feature wouldn't pay off.

Why do you expect this will add significant complexity? Maybe it will turn out to be an alternative approach of similar complexity? Although, I do remind I haven't even tried to implement it.

> Avoiding duplication is not something we typically aim for in tests.

Fair enough! Although, I think there are limits to everything. :)

> As a workaround, could you make a base class for the secondary types and inherit off it for the primary types (with the extra added HasPropertyC?

Do you mean to change the "production code" types? How would that help with tests?

> Alternatively, you could separate out each property into it's own test suite and mention which ones you want in the INSTANTIATE macro?

That is doable as well, however not practical once both groups become large (unlike 2+1 test cases in the example) and there are many types for which those get instantiated. The repetition of instantiating code becomes an issue on its own then.

**Comment by asoffer** [comment]
Regarding "inherit off it for the primary types" I meant the test fixtures rather than the production code.

Yes, there are limits to everything and removing some duplication is good. I only mention this to point out that while we strongly prioritize this in production code, we don't see as much benefit in tests. This doesn't mean this is a bad idea, just that you'll need to work a bit harder to convince us.

We definitely welcome you to work on this and are happy to provide feedback along the way, though I can't make any promises that it'll be accepted. I definitely encourage you to pursue it, I just want to set expectations accordingly.

**Comment by adambadura** [comment]
@asoffer How deriving fixture classes would help? Could you show an example?

**Comment by adambadura** [comment]
@derekmauro, why have you closed this?
