### ISSUE TITLE
How to pass parameters to typed test?

### ISSUE THREAD

**Issue by leeQT** [google/googletest#2564]
I have a test with 2 types, TypeA and TypeB, and I want to run each of them with Param1, Param2 and Param3, how can I do that?
I found a walkaround solution: treat the parameter as one type too:
`typedef testing::Types<std::tuple<TypeA, Param1>, std::tuple<TypeA, Param2>,...> instance_types;`
and get the pamameter using `typename std::tuple_element<1, decltype(TypeParam())>::type`
However, I think there should be a simpler way. Any clue?

**Comment by kuzkry** [comment]
There's no way to pass parameters to a typed test. Gtest implements value-parametrized and typed tests but you cannot mix them together.

**Comment by sbenzaquen** [comment]
On Thu, Nov 14, 2019 at 4:24 AM LiQinTian <notifications@github.com> wrote:

> I have a test with 2 types, TypeA and TypeB, and I want to run each of
> them with Param1, Param2 and Param3, how can I do that?
> I found a walkaround solution: treat the parameter as one type too:
> typedef testing::Types<std::tuple<TypeA, Param1>, std::tuple<TypeA,
> Param2>,...> instance_types;
> and get the pamameter using typename std::tuple_element<1,
> decltype(TypeParam())>::type
> However, I think there should be a simpler way. Any clue?
>

Value and type parameterized tests are orthogonal.
Your solution works fine and it is not that hard to use with things like
std::integral_constant.
But if all of this fails, you can always skip the macros and make the tests
manually. That way you can make as many tests as you'd like and bind any
type/data to them.
See testing::RegisterTest in
https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#registering-tests-programmatically
Obviously, this API requires a lot more user setup, so it is not
recommended for cases where the macros would work.

**Comment by leeQT** [comment]
> On Thu, Nov 14, 2019 at 4:24 AM LiQinTian ***@***.***> wrote: I have a test with 2 types, TypeA and TypeB, and I want to run each of them with Param1, Param2 and Param3, how can I do that? I found a walkaround solution: treat the parameter as one type too: typedef testing::Types<std::tuple<TypeA, Param1>, std::tuple<TypeA, Param2>,...> instance_types; and get the pamameter using typename std::tuple_element<1, decltype(TypeParam())>::type However, I think there should be a simpler way. Any clue?
> Value and type parameterized tests are orthogonal. Your solution works fine and it is not that hard to use with things like std::integral_constant. But if all of this fails, you can always skip the macros and make the tests manually. That way you can make as many tests as you'd like and bind any type/data to them. See testing::RegisterTest in https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#registering-tests-programmatically Obviously, this API requires a lot more user setup, so it is not recommended for cases where the macros would work.

Thans a lot, closing this issue now.
