### ISSUE TITLE
Adding support for ps4 and other consoles

### ISSUE THREAD

**Issue by pippy360** [google/googletest#2565]
Hi googletest team,

Internally we maintain a fork of googletest for consoles (ps4/xboxone/Nintendo switch...).

Would you guys be willing to accept a pull request which added support for these platforms?

**Comment by asoffer** [comment]
pippy360,

Yes, with two caveats:
* The changes should be minimally intrusive in the sense that it should not significantly increase maintenance burden for other platforms. I don't actually foresee any problems here, but I want to spell that out explicitly.
* Support for these platforms will be "community support." That is, it will likely be you who is on the hook for handling issues related to these platforms. 

That being said, absolutely, yes, we welcome pull requests!
