### ISSUE TITLE
GTestTarget.cmake is missing but required from GTestConfig

### ISSUE THREAD

**Issue by BuBuMan** [google/googletest#2581]
Hey, 

After doing the following steps on Windows:

1- Clone googletest repo
2- Run cmake . in root directory
3- Open googletest-distrubution.sln and build

When I go to googletest/generated GTestTarget.cmake is not generated although GTestConfig tries to include it. 

I am using this directory for find_package in my build system and it is failing due to that. Am I missing something here?

**Comment by BuBuMan** [comment]
Seems like the export command is missing in the CMakeLists.txt file under google test. Is this a bug? After I added the following command where it generates the config file it works.

export(EXPORT GTestTargets FILE "${generated_dir}/GTestTargets.cmake")

**Comment by derekmauro** [comment]
We aren't familiar with this workflow. You may want to ask this question on a forum like stackoverflow.
