### ISSUE TITLE
LINK2001 Unresolved external symbol

### ISSUE THREAD

**Issue by lsdy** [google/googletest#2585]
`
class A{
public:
  A(){}
  ~A(){}
};
class TestAgreement:public testing::Test{
protected:
  static void SetUpTestCase(){
    _a=new A();
  }
  static void TearDownTestCase(){
    delete _a;
  }
  static A* _a;
}
`
Error:
LINK2001 Unresolved external symbol "protected:static class A* TestAgreement::_a"(?_a@TestAgreement@@1PAVA@@A).

I follow the example of others.Is it wrong with me?

**Comment by asoffer** [comment]
This is not an issue with googletest specifically, but you have only declared `_a` but never defined it. You need (outside the class)
`A* A::_a = nullptr;`
