### ISSUE TITLE
Fixed width integers are not guaranteed to exist

### ISSUE THREAD

**Issue by kuzkry** [google/googletest#2599]
Hello Googlers,
recent commit 717ce7fe has removed custom testing::internal::{Int,Uint}{32,64} types and replaced them by standard counterparts. Rationale stated in the commit message is:
> Remove testing::internal::{Int,Uint}{32,64} in favor of types guaranteed to be in <cstdint> since C++11..

This isn't true as aliases such as std::(u)int{8, 16, 32, 64}_t are _optional_ and _provided only if the implementation directly supports the type_. I agree that {unsigned / signed} long longs are guaranteed to have at least 64 bits and this is what we should be using but on the 32-bit platform, where {unsigned / signed} long longs are only emulated, std::(u)int64_t aren't going to be available.

**Comment by derekmauro** [comment]
Is this a theoretical or real concern? We believe all toolchains that we will reasonably support have this support.

**Comment by kuzkry** [comment]
Purely theoretical I think as no-one has even upvoted it since when it was posted. That's good news.
