### ISSUE TITLE
Compile error when using ON_CALL, WillByDefault(Invoke(...)) in constructor of Mock class

### ISSUE THREAD

**Issue by ephedria-l** [google/googletest#2612]
I get the following compile error when using 
ON_CALL(*this, WriteData(_,_)).WillByDefault(Invoke(this, &MockChannel::SendData)); in my MockClass' constructor:

d:\code\machinecontrol\iconfield1\iconfield\bin\debug\tmp-win32-msvc2015-x64\catch2testsicon\../../../../Components/LeicaTPSDevice/tests/catch2/MockChannel.h(29): error C2664: 'testing::internal::OnCallSpec<int (const unsigned char *,int)> &testing::internal::OnCallSpec<int (const unsigned char *,int)>::WillByDefault(const testing::Action<F> &)': cannot convert argument 1 from 'testing::internal::InvokeMethodAction<MockChannel,void (__cdecl MockChannel::* )(const unsigned char *,int)>' to 'const testing::Action<F> &'

This compiled in version 1.8.0.

I also tried using a lambda, but it also does not work:
ON_CALL(*this, WriteData(_,_)).WillByDefault(Invoke([this](const unsigned char* buffer, int size) { this->SendData(buffer, size); }));

**Comment by hyukmyeong** [comment]
How about check the types between WriteData(), and SendData() ?
Because I could find below log

int (const unsigned char *,int)
int (const unsigned char ,int)

**Comment by asoffer** [comment]
I believe @hyukmyeong is right. At least with the lambda example, buffer is not a pointer.
