### ISSUE TITLE
How do I make gmock treat all failures as errors?

### ISSUE THREAD

**Issue by bcgshyam** [google/googletest#2613]
I have some test code, which due to some code changes, is not executing completely (I know this, as I can see failure messages in the logs saying expected to execute once, but did not run for many functions). However, the compilation/execution is not failing, as it getting an exception that it is expecting (as the same exception is thrown in multiple places). So the test appears to pass, but it is not executing completely. How can I make gmock treat all warnings/failures as errors?

This is the kind of messages in the log - 

> Failure Actual function call count doesn't match EXPECT_CALL(*(function name))... 
> Expected: to be called once 
> Actual: never called - unsatisfied and active

**Comment by asoffer** [comment]
What sort of mock is 'function name'? 
Making it a `testing::StrictMock` should do this.

https://github.com/google/googletest/blob/master/googlemock/docs/cheat_sheet.md

**Comment by bcgshyam** [comment]
No StrictMock did not work. 
Using ::testing::GTEST_FLAG(throw_on_failure) = true helped resolve the issue.
