### ISSUE TITLE
MOCK_METHOD with an std::any argument doesn't compile with clang 9.0.0

### ISSUE THREAD

**Issue by daravi** [google/googletest#2616]
As the title says, the compiler returns:
```
.../llvm-9.0.0/bin/../include/c++/v1/type_traits:2843:14: error: base class has incomplete type
...
in instantiation of template class 'testing::internal::MockSpec<std::__1::basic_string<char> (const std::__1::any &)>' requested here
     MOCK_METHOD1(doSomething, std::string(const std::any& data));
     ^
```

Issue only occurred when I switched from GCC to Clang.

**Comment by asoffer** [comment]
Interesting, I don't think this is strictly a Googletest issue, as I've reproduced something that I would expect to work (in both clang and gcc)

https://godbolt.org/z/_g6txZ

**Comment by asoffer** [comment]
As it turns out, this is a known bug with the standard that occurs with type traits whenever you perfect-forward (done by std::tuple) to a type-erased interface (std::any). Internally we pass around the function arguments with a tuple. We could work around this in some instances by 1-argument tuples. I'm going to look into this, but it may be more complexity than we wish to maintain.

**Comment by asoffer** [comment]
Further reference to the issue
https://cplusplus.github.io/LWG/issue3121

**Comment by asoffer** [comment]
We've looked into this a bit. If the use of std::tuple were entirely internal, we could consider a number of solutions (storing dummy arguments to pad the tuple to >1 element, or using an alternate implementation without these issues).

However, the tuples are exposed in public interfaces (e.g., the MockSpec .With method). I think the sad reality is that, the collateral damage we would cause by fixing this is just too big. I'd suggest looking to use a type other than std::any as the argument.

Sorry we can't be more helpful on this.

**Comment by alireza-hosseini** [comment]
I have the same issue with GCC as well:
`error: invalid use of incomplete type ‘struct std::is_constructible<testing::Matcher<std::any>, const testing::Matcher<std::any>&>’`
