### ISSUE TITLE
googletest as external repository in bazel build throws compilation error

### ISSUE THREAD

**Issue by prav-sp** [google/googletest#2617]
(base) praveen-sp-m:gtest_bazel praveen$ bazel test //tests:tests
DEBUG: Rule 'googletest' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "703bd9caab50b139428cea1aaff9974ebee5742e", shallow_since = "1570114335 -0400" and dropping ["tag"]
DEBUG: Call stack for the definition of repository 'googletest' which is a git_repository (rule definition at /private/var/tmp/_bazel_praveen/27a4507d452afc25dce689156119c052/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /Users/praveen/Desktop/my_data/My_Project/gtest_bazel/WORKSPACE:3:1
INFO: Analyzed target //tests:tests (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
ERROR: /private/var/tmp/_bazel_praveen/27a4507d452afc25dce689156119c052/external/googletest/BUILD.bazel:57:1: C++ compilation of rule '@googletest//:gtest' failed (Exit 1) cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 33 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/googletest/googletest/src/gtest.cc:122:
external/googletest/googletest/src/gtest-internal-inl.h:126:40: error: unknown type name 'Int32'
    const char* str, const char* flag, Int32* value);
                                       ^
external/googletest/googletest/src/gtest-internal-inl.h:130:34: error: unknown type name 'Int32'
inline int GetRandomSeedFromFlag(Int32 random_seed_flag) {
                                 ^
external/googletest/googletest/src/gtest-internal-inl.h:216:13: error: no type named 'Int32' in namespace 'testing::internal'
  internal::Int32 random_seed_;
  ~~~~~~~~~~^
external/googletest/googletest/src/gtest-internal-inl.h:217:13: error: no type named 'Int32' in namespace 'testing::internal'
  internal::Int32 repeat_;
  ~~~~~~~~~~^
external/googletest/googletest/src/gtest-internal-inl.h:219:13: error: no type named 'Int32' in namespace 'testing::internal'
  internal::Int32 stack_trace_depth_;
  ~~~~~~~~~~^
external/googletest/googletest/src/gtest-internal-inl.h:230:40: error: unknown type name 'UInt32'
GTEST_API_ std::string CodePointToUtf8(UInt32 code_point);
                                       ^
external/googletest/googletest/src/gtest-internal-inl.h:266:12: error: unknown type name 'Int32'
GTEST_API_ Int32 Int32FromEnvOrDie(const char* env_var, Int32 default_val);
           ^
external/googletest/googletest/src/gtest-internal-inl.h:266:57: error: unknown type name 'Int32'
GTEST_API_ Int32 Int32FromEnvOrDie(const char* env_var, Int32 default_val);
                                                        ^
external/googletest/googletest/src/gtest-internal-inl.h:326:55: error: unknown type name 'UInt32'
        static_cast<int>(random->Generate(static_cast<UInt32>(range_width)));
                                                      ^
external/googletest/googletest/src/gtest.cc:333:1: error: unknown type name 'UInt32'
UInt32 Random::Generate(UInt32 range) {
^
external/googletest/googletest/src/gtest.cc:333:25: error: unknown type name 'UInt32'
UInt32 Random::Generate(UInt32 range) {
                        ^
external/googletest/googletest/src/gtest.cc:336:24: error: unknown type name 'UInt32'
  state_ = static_cast<UInt32>(1103515245ULL*state_ + 12345U) % kMaxRange;
                       ^
external/googletest/googletest/src/gtest.cc:1738:7: error: unknown type name 'UInt32'

**Comment by Eduardor123** [comment]
is this issue solved? I am having the same problem

**Comment by prav-sp** [comment]
no, i still have the same issue.

Alternatively, i have built the googletest locally and tried to associate local_repository to my workspace rather than git_repository and this seems to solve my issue temporarily

**Comment by asoffer** [comment]
@prav-sp apologies for the delay. Can you provide exact reproduction instructions? Perhaps a WORKSPACE file, operating system information, bazel version, and commands to run?

**Comment by derekmauro** [comment]
Closing due to lack of response.

**Comment by liuzubing** [comment]
I have the same problem, Is there any solution to this issue ?

**Comment by liuzubing** [comment]
> is this issue solved? I am having the same problem

Is it solved ?

**Comment by Thinginitself** [comment]
I have the same problem, wait for solution.

**Comment by Sigma711** [comment]
Just change the "gtest/gtest.h" to "gtest.h" in the third-party file "gtest-all.cc".
