### ISSUE TITLE
-Wmissing-declaration for intToCallReaction

### ISSUE THREAD

**Issue by Smattr** [google/googletest#2618]
When using `-Wmissing-declaration` with GCC 9.1.0 [`intToCallReaction`](https://github.com/google/googletest/blob/master/googlemock/src/gmock-spec-builders.cc#L554) triggers a warning because it has no preceding prototype. Not sure if you consider such things worth addressing. I only ran into this because an outer build system I was using injected both this and `-Werror`, causing a build failure.

**Comment by asoffer** [comment]
As addressed in https://github.com/google/googletest/issues/2661, we do not believe  that `-Wmissing-declaration` is worth turning on, as it seems to have a low signal-to-noise ratio, and typically only surfaces issues that would be caught in a linking phase anyway. We are open to PRs that mark such functions as static to silence the warnings in your build, but at this time we are not promising to turn on this warning in our own.
