### ISSUE TITLE
Can I make some cases exclusive to each other?

### ISSUE THREAD

**Issue by psionic12** [google/googletest#2621]
Let me explain:
I have a class which has some sort of thread registration work,and I have a test case which will create threads then initialize my class to test if the thread registration works well. If I run this single case, it has no problem.

But I have other tests on this class which targets on other purpose, if I run the whole test, which I think they will run parallel, other tests which initialize my class will has influence to the thread test case.

So is there any way I can make this thread test exclusive to to other test? That is, If I run the whole cases, all case will be tested, but when the thread case is running, no other cases will run.

**Comment by hyukmyeong** [comment]
Does your class to be tested has static data or static member function?
I wonder why they are influenced each other?

**Comment by psionic12** [comment]
Yes, the class has a static thread_local member which will effects on any threads it involve to, that's why I want to make the test cases isolated.

**Comment by hyukmyeong** [comment]
If I join or wait its child thread then it doesn't fail even though they are in different test cases
Is this same to your situation?

```
#include <iostream>
#include <thread>

#include "gtest/gtest.h"
#include "gmock/gmock.h"

using namespace std;
using namespace testing;

inline void DoSleep(int seconds, int milli_seconds) {
  const timespec time = {
    seconds,                        // seconds.
    milli_seconds * 1000L * 1000L,  // milli seconds.
  };
  nanosleep(&time, NULL);
}

class MyRunner {
public:
    MyRunner(const string& param) : name(move(param)) {
        main_thread = thread(&MyRunner::ThreadFunc, this);
    }

    ~MyRunner() {
        main_thread.join();
    }

    void ThreadFunc() {
        for(int i=0; i<3; ++i) {
            DoSleep(0, 10);
            if (name.compare("Test1") == 0)
                data = 1;

            if (name.compare("Test2") == 0)
                data = 2;
        }
    }

    thread main_thread;
    string name;
    static int data;
};

int MyRunner::data = 0;

TEST(AsyncTest, Test1) {
    MyRunner runner1("Test1");
}

TEST(AsyncTest, Test2) {
    MyRunner runner("Test2");
}

TEST(AsyncTest, Test3) {
    ASSERT_EQ(MyRunner::data, 2);
}
```

**Comment by psionic12** [comment]
@hyukmyeong sorry, not the same... 
The detail is complicated, and you can image this as that the test class sort of a black box, I cannot modify it to fit the tests, the easiest way is to make cases fully isolated, if possible.

**Comment by hyukmyeong** [comment]
I see, if then I recommend you using `ASSERT_EXIT`

because it fork a new process for the test
and so threads are not influenced if they are in different test cases

I hope this would help you

```
void foo() {
    MyRunner runner1("Test1");

    // doing something
    // if (result)
    //      cerr << "success" << endl;
    // else
    //      cerr << "failure" << endl;

    cerr << "success" << endl;
    exit(1);
}

TEST(AsyncTest, Test1) {
    ASSERT_EXIT(foo(), ::testing::ExitedWithCode(1), "success");
}

TEST(AsyncTest, Test2) {
    ASSERT_EXIT(foo(), ::testing::ExitedWithCode(1), "success");
}
```

**Comment by psionic12** [comment]
That's it, this seems what I want.
Really thanks, I'll try:)
