### ISSUE TITLE
Put use case in docs

### ISSUE THREAD

**Issue by jverce** [google/googletest#2623]
There's a super useful use case for when you need to make a mock return `std::unique_ptr` base on an already existing one:
https://github.com/google/googletest/blob/78fdd6c00b8fa5dd67066fbb796affc87ba0e075/googlemock/test/gmock-actions_test.cc#L1335

The [cookbook docs](https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md#mocking-methods-that-use-move-only-types) don't have such an example, which I think it'd be super valuable. Do you mind adding it?

Thanks!

PS: I'm leaving for vacation so I can't do it myself anytime soon.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by asoffer** [comment]
@jverce I believe, the cookbook covers both Return and ByMove, though maybe not combining the two in this way. This particular mechanism is a bit subtle; It probably shouldn't be used with ON_CALL as it's likely wrong to call this twice. Moreover, though it might be useful, it's a bit more specific than we're aiming for in the cookbook.
