### ISSUE TITLE
Mingw32 build error : gettimeofday() deprecated

### ISSUE THREAD

**Issue by LoopInt** [google/googletest#2625]
When building with cmake & mingw32 on W10, an error is raise due to gettimeofday() deprecated:

[ 25%] Building CXX object CMakeFiles/gtest.dir/src/gtest-all.cc.obj
In file included from E:\Documents\googletest-master\googletest\src\gtest-all.cc:41:
E:/Documents/googletest-master/googletest/src/gtest.cc: In function 'testing::internal::TimeInMillis testing::internal::GetTimeInMillis()':
E:/Documents/googletest-master/googletest/src/gtest.cc:865:29: error: 'int gettimeofday(timeval*, void*)' is deprecated [-Werror=deprecated-declarations]
   gettimeofday(&now, nullptr);
                             ^
In file included from E:/Documents/googletest-master/googletest/src/gtest.cc:100,
                 from E:\Documents\googletest-master\googletest\src\gtest-all.cc:41:
c:\mingw\include\sys\time.h:106:53: note: declared here
 int __cdecl __MINGW_NOTHROW __POSIX_2008_DEPRECATED gettimeofday
                                                     ^~~~~~~~~~~~
In file included from E:\Documents\googletest-master\googletest\src\gtest-all.cc:41:
E:/Documents/googletest-master/googletest/src/gtest.cc:865:29: error: 'int gettimeofday(timeval*, void*)' is deprecated [-Werror=deprecated-declarations]
   gettimeofday(&now, nullptr);
                             ^
In file included from E:/Documents/googletest-master/googletest/src/gtest.cc:100,
                 from E:\Documents\googletest-master\googletest\src\gtest-all.cc:41:
c:\mingw\include\sys\time.h:106:53: note: declared here
 int __cdecl __MINGW_NOTHROW __POSIX_2008_DEPRECATED gettimeofday
                                                     ^~~~~~~~~~~~
cc1plus.exe: all warnings being treated as errors
CMakeFiles\gtest.dir\build.make:62: recipe for target 'CMakeFiles/gtest.dir/src/gtest-all.cc.obj' failed
mingw32-make[2]: *** [CMakeFiles/gtest.dir/src/gtest-all.cc.obj] Error 1
CMakeFiles\Makefile2:79: recipe for target 'CMakeFiles/gtest.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/gtest.dir/all] Error 2
Makefile:84: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by Kravlalala** [comment]
The same issue for MinGW-64 bit version 8.2.0

**Comment by LoopInt** [comment]
Solved by adding `set(CMAKE_CXX_FLAGS "-Wno-deprecated-declarations")` in CMakeList.txt.
