### ISSUE TITLE
Feature Request: EXPECT_REGULAR, ASSERT_REGULAR macro's to test Regular type semantics

### ISSUE THREAD

**Issue by N-Dekker** [google/googletest#2636]
It is often good practice for a user-defined type to behave as a Regular type. As Titus Winters wrote in [Revisiting Regular Types](https://abseil.io/blog/20180531-regular-types) (2108): 
> After 20 years of experience, we're confident that the definition of a Regular type is a useful abstraction, and approximates the right "default semantics" for user-defined types.

However, it appears challenging for users to properly test that their types do indeed have the required semantics of a Regular type. I feel that it would be very useful for GoogleTest to provide some macro's to perform those tests.

At https://github.com/N-Dekker/gtest-regular/ I placed an example implementation of two macro's, `EXPECT_REGULAR` and `ASSERT_REGULAR`. Both macro's expect two arguments, allowing users to specify two different example values of the type they want to test. For example, when testing a user type:

    UserType example_value1(42);
    UserType example_value2{x, y, z};
    EXPECT_REGULAR(example_value1, example_value2);

Each macro call tests 12 different expectations, including:

- `a != b` equals `!(a == b)`
- `T() == T()`
- `T a(b)` implies `a == b`
- `a = b` implies `a == b`
- if `b != T()` then after `a = b; a = T();` still `b` remains unequal to `T()`
- if `a == b` then after self-assignment `a = a;` still `a` remains equal to `b`
- after `a = move(a)`, `a` should not be corrupted, so `a == a` remains true

The example implementation of these macro's is at https://github.com/N-Dekker/gtest-regular/blob/master/example_implementation/gtest-regular.h  It aims to produce a specific, informative message for each expectation failure. A test program is included at https://github.com/N-Dekker/gtest-regular (running at Azure Pipelines), displaying the output for various (intended) test failures.

Please consider adding such macro's to the GoogleTest framework!

**Comment by sbenzaquen** [comment]
On Sun, Dec 15, 2019 at 7:10 AM Niels Dekker <notifications@github.com>
wrote:

> It is often good practice for a user-defined type to behave as a Regular
> type. As Titus Winters wrote in Revisiting Regular Types
> <https://abseil.io/blog/20180531-regular-types> (2108):
>
> After 20 years of experience, we're confident that the definition of a
> Regular type is a useful abstraction, and approximates the right "default
> semantics" for user-defined types.
>
> However, it appears challenging for users to properly test that their
> Regular types do indeed have the correct semantics. I feel that it would be
> very useful for GoogleTest to provide some macro's to perform those tests.
>
> At https://github.com/N-Dekker/gtest-regular/ I placed an example
> implementation of two macro's, EXPECT_REGULAR and ASSERT_REGULAR. Both
> macro's expect two arguments, allowing users to specify two different
> example values of the type they want to test. For example, when testing a
> user type:
>
> UserType example_value1(42);
> UserType example_value2{x, y, z};
> EXPECT_REGULAR(example_value1, example_value2);
>
> Each macro call tests 12 different expectations, including:
>
>    - a != b equals !(a == b)
>    - T() == T()
>    - T a(b) implies a == b
>    - a = b implies a == b
>    - if b != T() then after a = b; a = T(); still b remains unequal to T()
>    - if a == b then after self-assignment a = a; still a remains equal to
>    b
>    - after a = move(a), a should not be corrupted, so a == a remains true
>
> The example implementations of these macro's is at
> https://github.com/N-Dekker/gtest-regular/blob/master/example_implementation/gtest-regular.h
> It aims to produce a specific, informative message for each expectation
> failure. A test program is included at
> https://github.com/N-Dekker/gtest-regular (running at Azure Pipelines),
> displaying the output for various (intended) test failures.
>

The bar for new macros is really high, and I don't think this reaches it.
This could be implemented without new macros.
An example of a similar API:
https://github.com/abseil/abseil-cpp/blob/master/absl/hash/hash_testing.h
Sample usage:

EXPECT_TRUE(absl::VerifyTypeImplementsAbslHashCorrectly({v1, v2, ..., vN}));

Note that this supports an arbitrary list of values, not just two. This
list should include all "interesting" values for the type, which is usually
way more than two.
This also leaves space in the API to pass extra options. eg whether it
should check for all 6 relationals or just eq/ne.

> Please consider adding such macro's to the GoogleTest framework!
>
Would you consider providing a PR for the new feature?

**Comment by N-Dekker** [comment]
@sbenzaquen Thank you for your feedback, Samuel! I think I understand your concerns. However, I still find the approach that I implemented at https://github.com/N-Dekker/gtest-regular very appealing.

The new macro's could get longer, more distinguishable names, for example `GTEST_ASSERT_REGULAR_TYPE` and `GTEST_EXCEPT_REGULAR_TYPE`, to avoid naming collisions. I hope that would take away possible objections against adding new macros. 

It might be nice to support an arbitrary number of example values, but in practice I think two example values are sufficient, to detect the most common bugs that might occur when users aims to support Regular requirements for their class types. Users who really want to try out more example values could also call the macro multiple times, with different example values of one and the same type. 

> Would you consider providing a PR for the new feature?

The implementation at https://github.com/N-Dekker/gtest-regular/blob/master/example_implementation/gtest-regular.h could easily be used as part of a pull request, after some small modifications. (The license text should be adjusted, and the internal helper class should be moved into the `testing::internal` namespace.) I intend to do so, as a next step.

Before adjusting the code according to your comments, I would like to be sure that there is no chance that my current approach (two new macro's, two example values) could be accepted for GoogleTest.

**Comment by asoffer** [comment]
I do not believe it is likely that we accept this as is (with macros). As Sam mentioned, the bar for new macros is very high. In particular, we essentially require for new macros that this cannot be done without macros.

We would welcome a PR without macros.
