### ISSUE TITLE
Gmock1.8x msvc gmock_test can't compile successfully

### ISSUE THREAD

**Issue by avalonsaber1** [google/googletest#2642]
use the googletest-1.8.x\googlemock\msvc\2015 gmock.sln, but the gmock_test project can't compile successfully.
Severity	Code	Description	Project	File	Line
Error	C2893	Failed to specialize function template 'unknown-type std::invoke(_Callable &&,_Types &&...)'	gmock-generated-actions_test	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits	1494

**Comment by derekmauro** [comment]
Does the latest release solve this problem?
