### ISSUE TITLE
static code analyzer warning regarding rule of 5

### ISSUE THREAD

**Issue by Zeppan** [google/googletest#2643]
I'm using google test to test my C library and it is working fine but I get some compiler warnings (the tests runs fine). All of my C code is in separate `.c` files. I include all my C specific headers in a `extern "C" {}`.

The warning I get (not the real name of my tests): 
```
class 'testSuite_testName_Test' defines a copy constructor and a copy assignment operator but does not define a destructor, a move constructor or a move assignment operator [cppcoreguidelines-special-member-functions]
TEST_F(storageTest, testName) {
^
```

I get these warning for all of my `TEST_F` tests, my class in the `.cc` file looks like this:

```
class testSuite : public testing::Test
{
public:
	virtual void SetUp()
	{
	}

	virtual void TearDown()
	{
	}
};
```

I also have the main function in the same file:

```
int main(int argc, char **argv)
{
	::testing::InitGoogleTest(&argc, argv);
	return RUN_ALL_TESTS();
}
```

A test I do might look like this:

```
TEST_F(testSuite, testName) {
    int ret = some_func();
    ASSERT_EQ(ret, 0);
}
```

**Comment by N-Dekker** [comment]
@Zeppan Is your issue possibly related to https://github.com/google/googletest/pull/2639 by @trzecieu?

**Comment by Zeppan** [comment]
Hi @N-Dekker ,
That seems to be the solution to my problem. I'll close this issue.
