### ISSUE TITLE
GTest fails to compile with Intel19 and VS2019

### ISSUE THREAD

**Issue by sah-git** [google/googletest#2644]
I'm trying to embed Google Test in my project. I am using:

Project Type:  Visual Studio 16 2019
Toolset:       Intel C++ Compiler 19.0
Architecture:  64 bits
CMake version: 3.16.1

I am following the instructions of [Google Test readme](https://github.com/google/googletest/blob/master/googletest/README.md#incorporating-into-an-existing-cmake-project)

I am using the master branch of Gtest repository.

Cmake runs ok, and Visual Studio solution is generated. But when building it, cmock and gtest projects fail to build with the following errors:

```
Error #2586: \'operator=\' : decorated name length exceeded, name was truncated

1>gtest-all.cc
1>Error #2586: \'operator=\' : decorated name length exceeded, name was truncated

1>gmock-all.cc
1>C:\Users\saa4\Downloads\googletest-master\googlemock\include\gmock/gmock-actions.h(816): message #411: class template "testing::internal::InvokeMethodAction<Class, MethodPtr>" defines no constructor to initialize the following:
1>            const member "testing::internal::InvokeMethodAction<Class, MethodPtr>::obj_ptr"
1>            const member "testing::internal::InvokeMethodAction<Class, MethodPtr>::method_ptr"
1>  struct InvokeMethodAction {
1>         ^
1>
1>C:\Users\saa4\Downloads\googletest-master\googlemock\include\gmock/gmock-actions.h(845): message #411: class template "testing::internal::InvokeMethodWithoutArgsAction<Class, MethodPtr>" defines no constructor to initialize the following:
1>            const member "testing::internal::InvokeMethodWithoutArgsAction<Class, MethodPtr>::obj_ptr"
1>            const member "testing::internal::InvokeMethodWithoutArgsAction<Class, MethodPtr>::method_ptr"
1>  struct InvokeMethodWithoutArgsAction {
1>         ^
```
When setting the compiler to Visual C++ it builds normally. Do I need te set any extra configuration parameter for Intel?

**Comment by AlessandroFasse** [comment]
Is there a solution for this?

**Comment by songyuncen** [comment]
add_compile_options(-wd2586)

**Comment by derekmauro** [comment]
The Intel compiler isn't supported, but does the solution in the previous comment work?
