### ISSUE TITLE
Feature Request: add option to stop repetitions at first failure.

### ISSUE THREAD

**Issue by unidual** [google/googletest#2645]
Rationale: to check whether a particular test is flaky, `--gtest_repeat` is useful, but may be wasteful.
Especially in continuous integration and when a handful of tests are run a lot of time each.
In most use cases, it would be enough to stop at first failure.

May we add a flag to have this behavior, e.g. `--stop_repeat_after_failure`?
It would skip to the next test.

**Comment by asoffer** [comment]
I believe `--gtest_break_on_failure` is what you're looking for.
https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#repeating-the-tests
