### ISSUE TITLE
'~MyTestSuite_MyTestCase' overrides a destructor but is not marked 'override'

### ISSUE THREAD

**Issue by hzahnlei** [google/googletest#2658]
Hello,
this is my first issue I am reporting. I hope I am doing it correctly. I have checked that this issue is no duplicate.

# Symptoms

I am using strict checking and I am treating warnings as errors. After upgrading to the latest version of Google Test my compiler gives me the following error message: `~MyTestSuite_MyTestCase' overrides a destructor but is not marked 'override'`

# Consequences

For now I can disable warnings. So my project compiles. However, I am trying hard to avoid any compiler warnings and I want all checks to be enabled. (Option for disabling the warning: `-Wno-inconsistent-missing-destructor-override`)

# Cause

- Google Test overrides a destructor in file `gtest/internal/gtest-internal.h`, line 1408. But the override is not marked `override`.

- According to Google's C++ Style Guide (https://google.github.io/styleguide/cppguide.html#Inheritance) overridden destructors should be marked with `override`.

- Therefore I ask you to annotate the destructor in line 1408 `override`.

# My set-up

- macOS 10.14.6 Mojave
- Xcode 11.3
- Apple Clang 11.0.0 (clang-1100.0.33.16)
- Google Test built from latest source today (2020-01-05), should be 1.10.0

Thank you for your help in advance,
Holger

**Comment by asoffer** [comment]
Thank you for reporting this. This looks reasonable and I'll get this in as soon as possible.
