### ISSUE TITLE
Add static/dynamic runtime support in the CMakeLists.txt

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#266]
```
Current version of the CMakeLists.txt generates project file with static 
runtime support. Attached patch extends this script to allow user choose 
either static or dynamic runtime. 

New option was added USE_STATIC_RT:
- ON: Generate projects with static runtime
- OFF: Generate projects with dynamic runtime
```

Original issue reported on code.google.com by `Dmitriy....@gmail.com` on 25 Mar 2010 at 6:59

Attachments:
- [google-test-cmake.patch](https://storage.googleapis.com/google-code-attachments/googletest/issue-266/comment-0/google-test-cmake.patch)

**Comment by MSK61** [comment]
A section should be added to the gtest [README file] (https://github.com/google/googletest/blob/master/googletest/README.md) to list the available options for selecting/enforcing C runtime libraries during building gtest.
