### ISSUE TITLE
Mock a Template Method

### ISSUE THREAD

**Issue by alfonsobrandao** [google/googletest#2660]
Hey everyone!

I'm having some trouble _mocking_ a method that is Template type.
It's something like that:

    class my_class
    {

    public:

         my_class();
         ~my_class();

         template<typename T>
         boost::optional<T> get_value(const std::string& id);
    }

I'm trying to:

    class mock_my_class : public my_class
    {

    public:    

         mock_my_class();
         ~mock_my_class();

         template <typename T>
         MOCK_METHOD(boost::optional<T>, get_value, (const std::string& id));
    }

It won't compile, returning this:
      
      error: expected unqualified-id before ‘static_assert’
      MOCK_METHOD(boost::optional<T>, get_value, (const std::string& id));
      ^~~~~~~~~~~

Thanks in advance,
AB.

**Comment by hyukmyeong** [comment]
Hello

I think there are template related member functions are like below

1. template class + normal method
2. normal class + template method
3. template class + template 
4. template global function

for the first one you can use macros in gMock
for the others you should add below things with gMock macros

1. type trait
2. template specialization
3. function overloading

e.g.) if I  use type trait 
```
class TestClass_1 {};
class TestClass_2 {};

class DOC {
public:
    template<typename T>
    string foo(T param) {
        return "I'm foo";
    }
};

class MockDOC {
public:
    MOCK_METHOD(string, foo_tc1, (int param));
    MOCK_METHOD(string, foo_tc2, (int param));

    template<typename T>
    string foo(T& param)
    {
        if (is_same<T, TestClass_1>::value)
        {
            return foo_tc1(1);
        }
        else if (is_same<T, TestClass_2>::value)
        {
            return foo_tc2(2);
        }
    }
};

```

**Comment by alfonsobrandao** [comment]
Thanks so much for your help, @hyukmyeong ! 👍 

I'll close this for future questions regarding this.

**Comment by carltonslowdown** [comment]
> Hello?
> 
> I think it can be divided into 4 or more cases
> 
> 1. template class + normal member function
> 2. normal class + template member function
> 3. template class + template member function
> 4. template global function
> 
> for the first one you can use gMock macro for the other cases you should use gMock macro with one of below options
> 
> 1. type traits
> 2. template specialization
> 3. function overloading
> 
> I think template methods can't be used as virtual functions so you don't need inheritance but you should make your SUT which uses my_class as a template class (or use macro replacement if you don't want to modify SUT)
> 
> e.g.) type traits
> 
> ```
> class TestClass_1 {};
> class TestClass_2 {};
> 
> class DOC {
> public:
>     template<typename T>
>     string foo(T param) {
>         return "I'm foo";
>     }
> };
> 
> template<typename T>
> class SUT {
> public:
>     SUT(T& param) : doc(param) {};
>     void foo() {
>         TestClass_1 ts1;
>         TestClass_2 ts2;
> 
>         cout << doc.foo(ts1) << endl;
>         cout << doc.foo(ts2) << endl;
>     }
> private:
>     T& doc;
> };  
>     
> class MockDOC {
> public:
>     MOCK_METHOD1(foo_tc1, string(int param));
>     MOCK_METHOD1(foo_tc2, string(int param));
> 
>     template<typename T>
>     string foo(T& param) {
>         if (is_same<T, TestClass_1>::value) {
>             return foo_tc1(1);
>         } else if (is_same<T, TestClass_2>::value) {
>             return foo_tc2(2);
>         }
>     }
> };
> 
> TEST(SutTest, UseMock) {
>     DOC doc;
>     SUT<DOC> sut(doc);
>     
>     MockDOC mock_doc;
>     SUT<MockDOC> mock_sut(mock_doc);
> 
>     EXPECT_CALL(mock_doc, foo_tc1(_))
>         .WillOnce(Return("I'm mocked foo (TestClass_1)"));
> 
>     EXPECT_CALL(mock_doc, foo_tc2(_))
>         .WillOnce(Return("I'm mocked foo (TestClass_2)"));
> 
>     sut.foo();
>     mock_sut.foo();
> }
> ```





https://stackdev.space/questions/utilize-the-gtest-googletest-template-for-testing
