### ISSUE TITLE
Return ByMove error in v1.8.1 - return using existing unique_ptr

### ISSUE THREAD

**Issue by IsabellaRey** [google/googletest#2662]
Hi, I'm using release 1.8.1 in Visual Studio 2017 with VS2015 compiler (v140).

I'm trying to get the `Return(ByMove(...))` to work, following the example in the cookbook at https://github.com/google/googletest/blob/release-1.8.1/googlemock/docs/CookBook.md (which is essentially the same as documented in master)

```
enum class AccessLevel { kInternal, kPublic };

class Buzz {
public:
	explicit Buzz(AccessLevel access) {  }
};

class Buzzer {
public:
	virtual ~Buzzer() {}
	virtual std::unique_ptr<Buzz> MakeBuzz() = 0;
};

class MockBuzzer : public Buzzer {
public:
	MOCK_METHOD0(MakeBuzz, std::unique_ptr<Buzz>());
};

// in the test:
MockBuzzer mock_buzzer_;
auto buzz = std::make_unique<Buzz>(AccessLevel::kInternal);
EXPECT_CALL(mock_buzzer_, MakeBuzz())
     .WillOnce(Return(ByMove(buzz)));
```

The Return ByMove is giving me a C2280 error:
```
'std::unique_ptr<Buzz,std::default_delete<_Ty>>::unique_ptr(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)': attempting to reference a deleted function
```

Am I using this wrong? I can't find an example where `ByMove` is passed an existing unique pointer. Your examples just use `MakeUnique` (which I don't seem to have).

I need `MockBuzzer` to return an existing unique pointer: in my real code the equivalent of `MockBuzzer` is in fact a `MockFactory` that must return pointer to another mock `std::unique_ptr<MockDataProvider>`; I need the `MockDataProvider` to already exist so I can set expectations on it

An example of how this should be used would be great please.

Just for clarity, my real code is along these lines:
```
class IDataProvider
	{
	public:
		virtual ~IDataProvider() = default;
		virtual DataCollection getData(const SearchFilter& filter) const = 0;
	};
class IDataProviderFactory
	{
	public:
		virtual ~IDataProviderFactory() = default;
		virtual std::unique_ptr<IDataProvider> createDataProvider() const = 0;
	};

class MockDataProvider : public IDataProvider
{
public:
	MOCK_CONST_METHOD1(getData, DataCollection(const SearchFilter& filter));
};
class MockDataProviderFactory : public IDataProviderFactory
{
public:
	MOCK_CONST_METHOD0(createDataProvider, std::unique_ptr<IDataProvider>());
};

// in tests:
auto mockDataProvider = std::make_unique<MockDataProvider>();
EXPECT_CALL(*mockDataProvider, getDataCollection(filter)).WillOnce(Return(DataCollection()));

auto mockFactory = std::make_unique<MockDataProviderFactory>();
EXPECT_CALL(*mockFactory, createDataProvider()).WillOnce(Return(ByMove(mockDataProvider)));
```

**Comment by IsabellaRey** [comment]
Answering my own questions, looks like the proper way of using this is:
```
Return(ByMove(std::move(myUniquePointer)))
```

Is it worth putting an explicit example like this in the cookbook?

**Comment by asoffer** [comment]
Isabella, apologies for the delay. We would welcome the addition of such documentation. To give some reasoning for this, because actions may be performed multiple times, we do not want to move lvalues passed in to the action. It's definitely a bit strange, and could use extra documentation!
