### ISSUE TITLE
Fatal assertion (ASSERT, FAIL) in function call is not fatal for the caller test

### ISSUE THREAD

**Issue by daravi** [google/googletest#2666]
Hi. I am not sure if I am doing something wrong since this seems pretty trivial and I think it used to behave correctly before.

However, when I put a fatal assertion in a function call it does not halt test execution. (as I think it should from the documentation, though I cannot find explicit clarification)

```cxx
void failFatalAssert()
{
    ASSERT_TRUE(false);
}

TEST(FailFatalAssert, Direct)
{
    ASSERT_TRUE(false);
    EXPECT_TRUE(false) << "This assertion correctly does not run";
}

TEST(FailFatalAssert, Indirect)
{
    failFatalAssert();
    EXPECT_TRUE(false) << "This assertion should not have been run";
}
```

Output:

```
(base) gtest/build_make > ./fatalAssertion 
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from FailFatalAssert
[ RUN      ] FailFatalAssert.Direct
.../test.cpp:30: Failure
Value of: false
  Actual: false
Expected: true
[  FAILED  ] FailFatalAssert.Direct (0 ms)
[ RUN      ] FailFatalAssert.Indirect
.../test.cpp:25: Failure
Value of: false
  Actual: false
Expected: true
.../test.cpp:37: Failure
Value of: false
  Actual: false
Expected: true
This assertion should not have been run
[  FAILED  ] FailFatalAssert.Indirect (0 ms)
[----------] 2 tests from FailFatalAssert (0 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (1 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] FailFatalAssert.Direct
[  FAILED  ] FailFatalAssert.Indirect
```

P.S. inline-ing the function does not change this behavior.

**Comment by hyukmyeong** [comment]
Hello?

I think that `ASSERT_*` only stops current function
so for failures in subroutines you should use `HasFatalFailure()` or similar functions in caller (test function)
please refer : https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#propagating-fatal-failures

**Comment by asoffer** [comment]
ASSERT only stops the current function. We consider it best practice to have EXPECTs and ASSERTs in the main test body, though this isn't always feasible. A reasonable that solves most cases is to, rather than assert inside a function, have the function return values and have the main test body assert on those values.
