### ISSUE TITLE
Microsecond/nanosecond precision print time

### ISSUE THREAD

**Issue by avasylev** [google/googletest#2667]
I'm looking to make test duration printed in microseconds/nanoseconds for benchmarking. 
Millisecond precision seems to be backed into GetTimeInMillis() for all measurements, so guessing there's no some easy flag to switch precision?

Would that be of any interest if I prep PR to update GetTimeInMillis() to GetTimeInNanos() or smth like that? Keeping default output in millis but config switchable to nanos?

**Comment by kuzkry** [comment]
Hello! You might wanna consider that normally unit tests aren't written with performance in mind and so is GoogleTest backend. Here we rather deal with polymorphism, exceptions and stuff that are hard to measure. Each test is actually started by calling its virtual function. So I'd rather use other libraries such as [Google Benchmark](https://github.com/google/benchmark).

**Comment by asoffer** [comment]
@kuzkry is absolutely correct. GoogleTest is not a great way to run benchmarks. The results will be noisy and unreliable. I'd look for a tool design from the start for benchmarking. It's possible when GoogleTest takes a hard dependency on Abseil, we gain the thing you're looking for, but I'd still not suggest this as a benchmarking facility.

**Comment by wskellenger-intrepid** [comment]
I also think this would be useful.  It is understood that GTest is not a benchmarking tool, yet GTest still reports the test runtime in ms, which is often in many of our tests "0 ms" which isn't that useful.
