### ISSUE TITLE
Wonder why the `main` in `gtest_main.a` doesn't conflict with my own `main`

### ISSUE THREAD

**Issue by left4taco** [google/googletest#2674]
Hi guys. I'm using gtest in my project now and find something very interesting. The final compiling command generated by CMake is like 
```shell
$ c++
/usr/bin/c++ \
  CMakeFiles/test_complex.dir/test/test_complex.cpp.o \
  CMakeFiles/test_complex.dir/test/test.cpp.o \ # has a main function
  gtest/libgtest_main.a \ # also has a main function
  gtest/libgtest.a \
  ... # a bunch of libraries
  -pthread \
  -o test_complex
```

So basically there are two `main` functions defined, one is my own `test.cpp.o` and the other one in `libgtest_main.a`. I'm curious how come the compiler doesn't complain about the double definition problem anymore?

It's really bugging me for a while😂 Hope someone could help me out. Thanks!🙏

**Comment by hyukmyeong** [comment]
Hello?

If you have global functions which have same signature in source files or object files
>> linker makes multiple definition error

If you have global functions which have same signature in libraries
>> linker takes earlier one

suppose you have four definitions of `void foo(int param)` in `main.cpp `, `foo1.o`, `libfoo2.a`, libfoo3.a`

`g++ main.cpp foo1.o` : error
`g++ main.cpp libfoo2.a libfoo3.a` use foo in main.cpp

I think gcc and clang's linkers works like this

**Comment by asoffer** [comment]
Unfortunately there's not much we can do here from a language perspective. Having multiple `main` functions is an ODR violation and therefore undefined behavior. Compilers are unable to diagnose it. Some linkers might diagnose it but it's not guaranteed and they're free to do whatever they want. In practice, they pick one, but there are really no guarantees in this space.
