### ISSUE TITLE
Need pthreads detection suppression in CMake build script

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#269]
```
Some OSes support POSIX threads but gtest's threading tests fail there. See 
http://groups.google.com/group/googletestframework/browse_thread/thread/66eacb6c
45df8470/
8fc028eeee080d29#8fc028eeee080d29 for an example.

autoconf build script has the --with_threads=no flag to suppress use of 
threads. We need a similar 
functionality in CMake build script to support such systems.
```

Original issue reported on code.google.com by `vladlosev` on 27 Mar 2010 at 10:32

**Comment by gldneagl** [comment]
At any rate... after years, this is still an issue on every version of Ubuntu from 14 through 18, and UBUNTU is NOT an obscure distro... so when y'all going to fix this? gtest is hardcoded into Cryptonote-based software in way that is is not simple to undo, besides tests are a good thing when their code don't make builds FAIL.
