### ISSUE TITLE
[Question] Is testing::InitGoogleMock() deprecated?

### ISSUE THREAD

**Issue by tt4g** [google/googletest#2694]
Thank you for the great library.

I found `testing::InitGoogleMock()` example code in https://github.com/google/googletest/blob/release-1.8.1/googlemock/docs/ForDummies.md#using-mocks-in-tests but remove that example in v1.10.

Is `testing::InitGoogleMock()` deprecated?

**Comment by kuzkry** [comment]
Hello! This isn't deprecated. You should still initialize it in your `main` function like that
```c++
  // custom code
  testing::InitGoogleMock(&argc, argv);
  return RUN_ALL_TESTS();
```
and link it with `gmock` and `gtest` libs. If your `main` doesn't do anything else, I'd recommend to link `gmock_main` lib that will provide [the default main](https://github.com/google/googletest/blob/23b2a3b1cf803999fb38175f6e9e038a4495c8a5/googlemock/src/gmock_main.cc) for you.

**Comment by tt4g** [comment]
@kuzkry Thank you for answering!

**Comment by gejotux** [comment]
Thanks
