### ISSUE TITLE
Why do we have both ASSERT_FLOAT_EQ and ASSERT_DOUBLE_EQ, but only one ASSERT_NEAR

### ISSUE THREAD

**Issue by mmatrosov** [google/googletest#2713]
I see an asymmetry here. As a possible fix, why can't we use `ASSERT_FLOAT_EQ` for both float and doubles?

**Comment by sbenzaquen** [comment]
The ASSERT_FLOAT_EQ/etc macros was the old way of doing things.
It doesn't scale well (needs more macros for each new predicate) and it
doesn't combine well.
The new way is ASSERT_THAT(x, Matchers(...)), which does not have these
problems.
We are not adding more macros for the old way, but we recommend using the
new way for all new code.

**Comment by mmatrosov** [comment]
Thanks for the clarification. Two observations.

First, old-style macros seem more concise and symmetric:
```
ASSERT_FLOAT_EQ(a, b);
ASSERT_THAT(x, FloatEq(b));
```
Thus, I actually like them more.

Second, we still have two matchers: `FloatEq` and `DoubleEq`. I see that we also have two matchers for absolute errors: `FloatNear` and `DoubleNear`. But still, why can't we have a single version handling both `float` and `double`?
