### ISSUE TITLE
GTEST_SKIP Message not in exported XML

### ISSUE THREAD

**Issue by mhs-insiders** [google/googletest#2728]
Hi,

in our test suite we are using GTEST_SKIP in some circumstances to skip specific tests.
We would like to add some information for the reason a test was skipped just like the
failure message for failed tests.
I noticed that the GTEST_MESSAGE_ makro can take ::testing::TestPartResult::kSkip as an argument, but the supplied message will not be shown either in the Visual Studio Test Explorer nor will it be included in the exported XML-File.

Is there an existing way to export a message with GTEST_SKIP or could you expose this functionality in a future version?

Best Regards
MHs

**Comment by derekmauro** [comment]
This appears to be fixed.
