### ISSUE TITLE
I have some questions about output print style；(

### ISSUE THREAD

**Issue by wu933** [google/googletest#2730]
![image](https://user-images.githubusercontent.com/16176283/75304486-50074a00-587e-11ea-8527-7b73a54d2839.png)

1. Some sentence have a period, but some do not.
2. The title of every sentence does not align to left or center or right

I hope to get some answers with these two questions, thank you

**Comment by asoffer** [comment]
1. We'd definitely encourage pull requests to fix this sort of thing.
2. I'm not sure I understand the concern for this one, but if you submit a PR that might be a good place to discuss it.
