### ISSUE TITLE
Build fails in case GTEST_USES_PCRE=1

### ISSUE THREAD

**Issue by bgaifullin** [google/googletest#2735]
There is no implementation of class testing::internal::RE for case when GTEST_USES_PCRE=1,
this causes fail build on class MatchesRegexMatcher, which uses RE definitely

**Comment by bgaifullin** [comment]
seems like may be resolved by PR #2422

**Comment by kuzkry** [comment]
Hi! Actually the way it works is that you are, as a user, supposed to supply your own `testing::internal::RE` implementation in [custom/gtest-port.h](https://github.com/google/googletest/blob/master/googletest/include/gtest/internal/custom/gtest-port.h) file. But how would you know if it isn't documented, right? :D
If only Google accepted #2422, we could forget about this macro yuckiness on all platforms.

**Comment by bgaifullin** [comment]
)

**Comment by derekmauro** [comment]
As @kuzkry mentioned, our internal custom/gtest-port.h file actually has an implementation that uses PCRE. This isn't supported in the open source world, and you shouldn't be trying to set this macro.
