### ISSUE TITLE
‘nullptr’ was not declared in this scope

### ISSUE THREAD

**Issue by codearun** [google/googletest#2740]
25%] Building CXX object googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
In file included from googletest-release-1.10.0/googletest/include/gtest/internal/gtest-internal.h:40,
                 from googletest-release-1.10.0/googletest/include/gtest/gtest.h:62,
                 from googletest-release-1.10.0/googletest/src/gtest-all.cc:38:
googletest-release-1.10.0/googletest/include/gtest/internal/gtest-port.h: In function ‘void testing::internal::FlushInfoLog()’:
googletest-release-1.10.0/googletest/include/gtest/internal/gtest-port.h:972: error: ‘nullptr’ was not declared in this scope
googletest-release-1.10.0/googletest/include/gtest/internal/gtest-port.h: In function ‘To testing::internal::DownCast_(From*)’:
googletest-release-1.10.0/googletest/include/gtest/internal/gtest-port.h:1082: error: ‘nullptr’ was not declared in this scope
googletest-release-1.10.0/googletest/include/gtest/internal/gtest-port.h:1088: error: ‘nullptr’ was not declared in this scope
googletest-release-1.10.0/googletest/include/gtest/internal/gtest-port.h: In function ‘void testing::internal::SleepMilliseconds(int)’:

compiled on 4.1.12 kernel with gcc 
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-23.0.1) (GCC) 

 g++ -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-23.0.1) (GCC) 

In the CMakeLists.txt,  I had to modify the  
#  add_definitions(-std=c++11)
  add_definitions(-std=c++0x)

**Comment by kuzkry** [comment]
23b2a3b1 removed default CMAKE_CXX_STANDARD to avoid mixed builds (i.e. mixing C++11 with C++17).

**Comment by asoffer** [comment]
Thanks @kuzkry. That looks to be the cause.

**Comment by SkyGra** [comment]
hi, @kuzkry 

i have try add "add_definitions(-std=c++11)" in CMakefilelist.txt，but it doesn't work.

i also try add "set(CMAKE_CXX_STANDARD 11)" in CMakefilelist.txt, it also doesn't work.

can you tell me how to solve it

**Comment by SkyGra** [comment]
my gcc is 4.4.7
cmake is 3.19.1

**Comment by kuzkry** [comment]
Hey @SkyGra. I think the problem here is your compiler version. Take a look at [GCC standard support webpage](
https://gcc.gnu.org/projects/cxx-status.html#cxx11) where you can read about "Null pointer constant" being supported since GCC 4.6. Actually, Googletest requires C++11, which implies GCC >= 4.8.1 as 
> GCC 4.8.1 was the first feature-complete implementation of the 2011 C++ standard

Hopefully that solves your problem.

**Comment by Kodwings22** [comment]
You can check this link too may be useful ( https://kodlogs.net/298/c-nullptr-was-not-declared-in-this-scope)
