### ISSUE TITLE
EXPECT_THROW can't differentiate between some exception class and some inherited class from it 

### ISSUE THREAD

**Issue by rezaebrh** [google/googletest#2741]
In our code, I've got a function which will throw some exceptions with different classes. In one case, it will throw ``std::logic_error`` and in one other case it will throw ``std::out_of_range`` which is inherited from ``std::logic_error``. The problem is whenever the program i supposed to throw ``std::out_of_range`` and we EXPECT ``std::logic_error``, the test will pass. Although type of these 2 exception classes are consider the same, won't it be possible to discriminate these 2 classes from each other?

P.S: Of course whenever you EXPECT ``std::out_of_range`` and the program throws ``std::logic_error``, the discrimination will work fine.

**Comment by asoffer** [comment]
This is the intended behavior.
If the test throws a derived exception and expects a base exception, the tests should pass because indeed, a base exception was thrown (the derived is a base). If you want to expect a derived exception, you should expect the derived exception type.
