### ISSUE TITLE
Link error when compile googletest with Visual Studio 2015

### ISSUE THREAD

**Issue by MarcusGi** [google/googletest#2743]
googletest-param-test-test.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall testing::internal::MarkAsIgnored::MarkAsIgnored(char const *)" (??0MarkAsIgnored@internal@testing@@QAE@PBD@Z)，该符号在函数 "void __cdecl works_here::`dynamic initializer for 'gtest_allow_ignore_NotInstantiatedTest''(void)" (??__Egtest_allow_ignore_NotInstantiatedTest@works_here@@YAXXZ) 中被引用

**Comment by asoffer** [comment]
We will not be able to debug this from the current information. Please reopen if you can provide full reproduction steps.

**Comment by xiaolongDGitHub** [comment]
hi ，I also had met this problem using Visual Studio, how do you solve it ?

**Comment by Suanmd** [comment]
> googletest-param-test-test.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall testing::internal::MarkAsIgnored::MarkAsIgnored(char const *)" (??0MarkAsIgnored@internal@testing@@QAE@PBD@Z)，该符号在函数 "void __cdecl works_here::`dynamic initializer for 'gtest_allow_ignore_NotInstantiatedTest''(void)" (??__Egtest_allow_ignore_NotInstantiatedTest@works_here@@YAXXZ) 中被引用

Same Question, help please!
同样的问题，求教！

**Comment by AndrewAndJenny** [comment]
同样的问题
