### ISSUE TITLE
cannot find -lgtest

### ISSUE THREAD

**Issue by zhxing001** [google/googletest#2748]
i build the shared lib libgtest.so, when i build the test project, the -lgtest can not be find.

**Comment by kuzkry** [comment]
Hi! Check out the content of `lib` directory within your build folder. Maybe libgtest.so isn't there but libgtest.a is.

**Comment by zhangxy988** [comment]
Sorry, but we won't be able to help you debugging without more concrete details and ways to reproduce the issue.
