### ISSUE TITLE
Questions about linking pthread

### ISSUE THREAD

**Issue by GOGOYAO** [google/googletest#2752]
I follow the step on [incorporating-into-an-existing-cmake-project](https://github.com/google/googletest/tree/master/googletest#incorporating-into-an-existing-cmake-project) and I can compile and link my test correctly.

But if I install gtest by myself and then I use the installed gtest, I failed the link my test code. I need to add `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")` into my `CMakeLists.txt` and it will work correctly. 

So why do I need add the params `-pthread` if I use the installed gtest lib but I don't need to if I follow the step of [incorporating-into-an-existing-cmake-project](https://github.com/google/googletest/tree/master/googletest#incorporating-into-an-existing-cmake-project)?

Anybody can help me?

# Here is my test code.

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.5.1)
project(Test C CXX)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread") # without -pthread, it will failed to link pthread_xxxx
include_directories("/usr/local/include")
link_directories("/usr/local/lib")
find_library(GTEST_LIB NAMES gtest)
add_executable(test gtest_demo.cpp)
message(status "gtest: ${GTEST_LIB}")
target_link_libraries(test ${GTEST_LIB})
```

gtest_demo.cpp
```
#include <gtest/gtest.h>
int add(int a, int b) {
    int c = a + b;
    return c;
}

TEST(AddCase, AddOK) {
    EXPECT_EQ(3, add(1,2));
}

using namespace std;
int main(int argc,char* argv[]) {
    testing::InitGoogleTest(&argc,argv); 
    RUN_ALL_TESTS(); 
    return 0;
}
```
# Here is how I install gtest
```
mkdir googletest/build \
    && cd googletest/build && cmake .. && make -j10 \
    && cp lib/* /usr/local/lib/ \
    && cp -r googletest/googlemock/include/gmock/ /usr/local/include \
    && cp -r googletest/googletest/include/gtest/ /usr/local/include \
```

**Comment by zhangxy988** [comment]
CMake file is community supported and we don't have much expertise regarding CMake.
Adding tag help-wanted to seek community volunteers. Thanks in advance!

**Comment by hyukmyeong** [comment]
Hello,  

I could find `ThreadLocal` class is implemented with pthread  
I think that it is one of essential classes to use googletest  
  
and it uses `pthread` if I'm not in Windows environment  
you can find relevant source code [here](https://github.com/google/googletest/blob/master/googletest/include/gtest/internal/gtest-port.h#L1745)  
  
```cpp
// file : gtest-port.h

1356 # elif GTEST_OS_WINDOWS && !GTEST_OS_WINDOWS_PHONE && !GTEST_OS_WINDOWS_RT
...
// Implements thread-local storage on Windows systems.
...
1555 template <typename T>
1556 class ThreadLocal : public ThreadLocalBase {
...
1631 # elif GTEST_HAS_PTHREAD
...
1743 // Implements thread-local storage on pthreads-based systems.
1744 template <typename T>
1745 class GTEST_API_ ThreadLocal {
...
1781 static pthread_key_t CreateKey() {
1782    pthread_key_t key;
1783    // When a thread exits, DeleteThreadLocalValue() will be called on
1784    // the object managed for that thread.
1785    GTEST_CHECK_POSIX_SUCCESS_(
1786        pthread_key_create(&key, &DeleteThreadLocalValue));
1787    return key;
1781  }
```
  
it means googletest uses pthread by default  
and so we need to add pthread library as well to use googletest  
  
I think packages are commonly used with cmake and so others couldn't find issue about it  
becuase I could find gtest.pc file in build result and it has -lpthread in my envrionment (ubuntu)  
  
```bash
// file : googletest/build/googletest/generated/gtest.pc
prefix=${pcfiledir}/../..
libdir=${prefix}/lib
includedir=${prefix}/include

Name: gtest
Description: GoogleTest (without main() function)
Version: 1.10.0
URL: https://github.com/google/googletest
Libs: -L${libdir} -lgtest -lpthread
Cflags: -I${includedir} -DGTEST_HAS_PTHREAD=1 -lpthread
```

**Comment by vslashg** [comment]
Does this information help?  We can close this issue if so.

**Comment by GOGOYAO** [comment]
Thank you. I am clear.
