### ISSUE TITLE
error MSB6006 when compiling google test with visual studio 2013

### ISSUE THREAD

**Issue by gtc1072** [google/googletest#2759]
An error "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: “cmd.exe” exited, error code -1073741819" occurred when I compile google test with visual studio 2013, but it works good while compiling any other c++ programm project. Did anyone face the same issue?

**Comment by zhangxy988** [comment]
Sorry, MSVC 2013 isn't within our supported platforms. We support MSVC 2015 update 3 onwards.
