### ISSUE TITLE
cannot copy  lib*.a /usr/local/lib

### ISSUE THREAD

**Issue by MohsenDehghanzadeh** [google/googletest#2771]
to install on fedora30
inside   : /googletest-release-1.10.0/googletest

mkdir mybuild     
cd mybuild
cmake -Dgtest_build_samples=ON 
i get : 

CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

CMake Error: The source directory "/home/nemo/Downloads/Compressed/googletest-release-1.10.0/googletest/mybuild" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
and nothing to do

**Comment by MohsenDehghanzadeh** [comment]
what should i do

**Comment by kuzkry** [comment]
It seems you've forgotten `..` and cmake looked in the directory you were in ;) Use `cmake -Dgtest_build_samples=ON ..`
