### ISSUE TITLE
Generated testsuites report internal name configuration 

### ISSUE THREAD

**Issue by lvjp** [google/googletest#2776]
I think that it can be useful to let user choose the name wrote inside the xml/json generated report instead of the hard coded `AllTests`.

The actual generated file :
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="1" failures="0" disabled="0" errors="0" time="0" timestamp="2020-03-29T14:18:26" name="AllTests">
   <snip/>
</testsuites>
```

We can imagine that the name can be grabbed from the `FILE_PATH` part of `--gtest_output` if it's not set to the default value.

This can permit easier aggregation of group of tests suites. For example when you split your main binary in 2 or 3 internal libraries which each output  and report.xml file.

**Comment by asoffer** [comment]
Thanks for the suggestion. While we don't foresee any immediate problems with this, currently, this is not something we have the time pursue. If you would like to send a PR, we'd be happy to discuss further there.
