### ISSUE TITLE
google mock delegate to fake must be copy constructable

### ISSUE THREAD

**Issue by natersoz** [google/googletest#2789]
Using google test and mocks it seems that I cannot delegate a call from a mock to a fake if the function returns a reference to a data object. The google test version I'm using is 1.10.0 from the released zip.

In the code below when I delegate from a mock to a fake I get an error indicating that the copy constructor is deleted. The copy constructor must be deleted for this code to work properly.

```
#include "gtest/gtest.h"
#include "gmock/gmock.h"

#include <cstdint>

using ::testing::Invoke;
using ::testing::Mock;
using ::testing::Return;
using ::testing::ReturnRef;
using ::testing::_;

class Accessor
{
public:
    virtual ~Accessor()                  = default;
    Accessor()                           = default;
    Accessor(Accessor const&)            = delete;
    Accessor(Accessor&&)                 = delete;
    Accessor& operator=(Accessor const&) = delete;
    Accessor& operator=(Accessor&&)      = delete;

    struct Foo
    {
        ~Foo()                     = default;
        Foo()                      = default;
        Foo(Foo const&)            = delete;
        Foo(Foo&&)                 = delete;
        Foo& operator=(Foo const&) = delete;
        Foo& operator=(Foo&&)      = delete;

        uint32_t thing_1 = 13u;
    };

    struct Bar
    {
        ~Bar()                     = default;
        Bar()                      = default;
        Bar(Bar const&)            = delete;
        Bar(Bar&&)                 = delete;
        Bar& operator=(Bar const&) = delete;
        Bar& operator=(Bar&&)      = delete;

        uint32_t thing_2 = 79u;
    };

    virtual Foo&       GetFoo()       = 0;
    virtual Bar const& GetBar() const = 0;
};

class AccessorImpl: public Accessor
{
public:
    ~AccessorImpl() override                       = default;
    AccessorImpl()                                 = default;
    AccessorImpl(AccessorImpl const& ) = delete;
    AccessorImpl(AccessorImpl&&)                   = delete;
    AccessorImpl& operator=(AccessorImpl const&)   = delete;
    AccessorImpl& operator=(AccessorImpl&&)        = delete;

    Foo&       GetFoo()       override { return this->foo_; };
    Bar const& GetBar() const override { return this->bar_; };

private:
    Foo foo_;
    Bar bar_;
};

class MockAccessor : public Accessor
{
public:
    MOCK_METHOD0(GetFoo, Foo&());
    MOCK_CONST_METHOD0(GetBar, Bar&());
};

class MockAccessorWithFake : public MockAccessor
{
public:
    MockAccessorWithFake() : MockAccessor(), fake_accessor_()
    {
        ON_CALL(*this, GetFoo).WillByDefault([this]() {
            return this->fake_accessor_.GetFoo();
        });

        ON_CALL(*this, GetBar).WillByDefault([this]() {
            return this->fake_accessor_.GetBar();
        });
    }

private:
    AccessorImpl fake_accessor_;
};

TEST(AccessorTest, test)
{
    MockAccessorWithFake accessor;
    EXPECT_EQ(accessor.GetFoo().thing_1, 13u);
    EXPECT_EQ(accessor.GetBar().thing_2, 79u);
}
```
Errors from clang compiler:

test_accessor.cc:83:20: error: call to deleted constructor of 'Accessor::Foo' return this->fake_accessor_.GetFoo(); ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

test_accessor.cc:26:9: note: 'Foo' has been explicitly marked deleted here Foo(Foo const&) = delete; ^

test_accessor.cc:82:46: error: no viable conversion from '(lambda at test_accessor.cc:82:46)' to 'const Action' ON_CALL(*this, GetFoo).WillByDefault(this { ^~~~~~~~~~

googletest-src/googlemock/include/gmock/gmock-actions.h:339:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from '(lambda at test_accessor.cc:82:46)' to 'const testing::Action &' for 1st argument class Action { ^

googletest-src/googlemock/include/gmock/gmock-actions.h:339:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from '(lambda at test_accessor.cc:82:46)' to 'testing::Action &&' for 1st argument

googletest-src/googlemock/include/gmock/gmock-actions.h:367:3: note: candidate template ignored: requirement '::std::is_constructible, (lambda at test_accessor.cc:82:46)>::value' was not satisfied [with G = (lambda at test_accessor.cc:82:46)] Action(G&& fun) : fun_(::std::forward(fun)) {} // NOLINT ^

googletest-src/googlemock/include/gmock/gmock-spec-builders.h:323:46: note: passing argument to parameter 'action' here OnCallSpec& WillByDefault(const Action& action) {

**Comment by asoffer** [comment]
The lambdas are not returning references. The returned type is decayed unless you specify the return type explicitly. This is not a googletest issue but a C++ issue.

**Comment by natersoz** [comment]
Thank you very much for the help!
