### ISSUE TITLE
UniversalPrint should make it easy to avoid ODF breaches getting in the way of PrintTo and unexpectedly difficult overloads

### ISSUE THREAD

**Issue by code5hot** [google/googletest#2798]
At the moment, if one translation unit in a program uses UniversalPrint then it is instantiated to find a PrintTo implementation based on what's in scope at that point.

We often need a specific PrintTo in another translation unit and it can be difficult or impossible to make that happen.

I think we need UniversalPrint to be in an unnamed namespace (maybe that's not adequate - but just mooting it to start the conversation) so that a different UniversalPrint is used in each translation unit and so it can use a translation-unit specific PrintTo.

For example, I wrote an overload of PrintTo for ostream& to avoid a pointless long sequence of hex values but the hex values were printed anyway. I think it was because another translation unit instantiated UniversalPrint for ostream and the default PrintTo was selected at that point. If I had triggered two different template instantiations within my translation unit then I would have had a useful diagnostic and could have worked something out.

A non-universalprint and PrintTo variant of each header should be provided which doesn't include a definition of universalprint - just a declaration - and a header to include after we've defined PrintTo overloads.

Also gtest's instantiations should be listed and releases rejected if there are any instantiations outside of a short defined list of gtest's own types and very well-understood builtin types.

**Comment by code5hot** [comment]
It's very easily possible, nay, probable that what I think is the problem is actually something else, but the existence of this matter makes it hard to figure out what it actually is.

**Comment by sbenzaquen** [comment]
On Sat, Apr 4, 2020 at 3:56 PM code5hot <notifications@github.com> wrote:

> At the moment, if one translation unit in a program uses UniversalPrint
> then it is instantiated to find a PrintTo implementation based on what's in
> scope at that point.
>
> We often need a specific PrintTo in another translation unit and it can be
> difficult or impossible to make that happen.
>
There is no simple way to do this without easily invoking ODR violations
and undefined behavior.
As an example, `testing::PrintToString<T>` must mean the exact same thing
for every caller in every translation unit.

> I think we need UniversalPrint to be in an unnamed namespace (maybe that's
> not adequate - but just mooting it to start the conversation) so that a
> different UniversalPrint is used in each translation unit and so it can use
> a translation-unit specific PrintTo.
>
Even if UniversalPrint was unique for each TU, the callers would have to
agree.
Eg, the code inside EXPECT_EQ which is not unique per-TU would have
undefined behavior if UniversalPrint doesn't mean the same everywhere.
You would have to move it and every transitive caller into an anonymous
namespace, and that is a problem because it is viral and would affect
existing correct user code libraries that happen to call PrintToString.

> For example, I wrote an overload of PrintTo for ostream& to avoid a
> pointless long sequence of hex values but the hex values were printed
> anyway. I think it was because another translation unit instantiated
> UniversalPrint for ostream and the default PrintTo was selected at that
> point. If I had triggered two different template instantiations within my
> translation unit then I would have had a useful diagnostic and could have
> worked something out.
>
Yep, you triggered an ODR violation with No Diagnostics Required, so it is
just UB.

We have discussed ideas on how to locally extend the printer, but none have
been good enough yet.

**Comment by code5hot** [comment]
On Tue, 21 Apr 2020, 23:57 Samuel Benzaquen, <notifications@github.com>
wrote:

>
>
> We have discussed ideas on how to locally extend the printer, but none have
> been good enough yet.
>
> extern template instance declarations are a reasonable way as long as
theres no a default within gtest. The default is usually the mistake,
leaving clients to de-fault the system is usually best IMO as long as you
make it easy for them.

Ie, all instances required by gtest would have extern template instance
declarations, and some standard implementation files can be included into
client code for the basic cases (equivalent to including backward
co.pativle header names) or client code can provide it's own instances for
everything. Some trivial backward compatibility can be provided with the
existing header names, but people can migrate client code by including a
different set of headers which don't have the backward compatibility and
adding a translation unit to provide template instances for producing names
and in their test case TUs add external template instance declarations for
anything they need to print themselves.

By including things with a parameter for a tag struct, TU-specific printing
can also be done because the instance will have to be provided by the TU
that provides the tag struct and again, backward compatibility can be
provided when the existing header names are used.

**Comment by asoffer** [comment]
The approach you described does not work well with Bazel, making it difficult to gain traction internally.

As mentioned in Sam's comment, we've considered extension mechansims but none have proven good enough yet. I am closing this issue, as we're unable to fix this problem. If you believe you have a solution, we would welcome a PR and we can discuss specific technical options there.
