### ISSUE TITLE
ValuesIn and other data generators should accept function and variadic args and catch exceptions

### ISSUE THREAD

**Issue by code5hot** [google/googletest#2799]
When using a generator we need to make sure we have a failure when running tests so that when we can't generate a set of values we don't run zero tests and pass. So we have to raise an exception while making the list.

This helpfully stops the process in a position for diagnostics but that prevents us finding the full set of such failures for all instantiations of parameterised tests.

We need a THROW_UNLESS(value, matcher) macro which throws a gtest specific exception type and also we need to be able to tag EXPECT_THAT calls so we can THROW_UNLESS(tag, Failed()) which will let us assert a collection of things that must be true for later code to make any sense and THROW_UNLESS to prevent nonsense code from running. Then we need generators to recognise that an exception is because of one of these and don't abort unless gtest arguments require abort but it would be good to break the debugger if it's attached.

If no failure is in the adhoc test part then the exception should still trigger an abort with diagnostic information (eg, by using a scope-guard to throw another exception while the current one is in-flight.

This is easy to implement, I've done it with an extra function but it should be part of the generator as standard.

I haven't implemented the EXPECT_THAT tagging before - it shouldn't really be lexically scoped because we should be able to EXPECT_THAT in a block statement and check the tag for throwing from outside the block statement. Perhaps a matcher that takes a reference to a local OptionalAssertionResult and wraps another matcher, saving the result of the match for later inspection. Is there a better way?

**Comment by code5hot** [comment]
Furthermore we need to be able to register predicates to test exceptions of other types to decide if we want to hide them in the same manner throughout a single translation unit. C++11 makes this quite easy.

**Comment by vslashg** [comment]
We have a very high bar for adding new macros to Google Test.  Because Google does not use exceptions internally, we would not implement this feature ourselves.  We would welcome a pull request, and would be happy to discuss this feature in detail there.
