### ISSUE TITLE
Had to set C++ 14 to work

### ISSUE THREAD

**Issue by marimeireles** [google/googletest#2801]
As it is the master branch is not working out of the box on MacOS Catalina.
I had to add a `set (CMAKE_CXX_STANDARD 14)` on the cmake.

**Comment by kuzkry** [comment]
Hi! Could you post your compilation logs from before you've made this change?

**Comment by OlivierLDff** [comment]
I did PR that fix it if you are using cmake v > 3.0 : https://github.com/google/googletest/pull/2808

**Comment by derekmauro** [comment]
This should be fixed at head.
