### ISSUE TITLE
'gmock' nuget package updates

### ISSUE THREAD

**Issue by Aralox** [google/googletest#2804]
Hi there, I've tried a few times to get through to 'stailgot', the owner of the most official-looking nuget package for google test (https://www.nuget.org/packages/gmock/), but to no avail. I also messaged here (https://github.com/google/googletest/issues/2094), which summarizes what I'm trying to do:

> Hi @gennadiycivil , I really do believe we should include the `.nuspec` and all related nuget files in this repo. I see it as sort of the same as including CMake files - it makes it much easier for people to get up and running with the project.
> 
> It looks like this is the most 'official' package: https://www.nuget.org/packages/gmock/ as it says it's by Google, the releases follow the releases here and the project page links to this repo. But from your comments on other issues, it looks like that package isn't actually 'official'? I tried contacting 'stailgot' through the nuget site to suggest a change to one of the files in the nuget package (`gmock.targets`), but have not received a response, and am wondering if my message was swallowed into the nuget.org email system somewhere. I have included the change I suggested below if you are interested.
> 
> Anyway, I really believe we should include all nuget-related files in this repo, and start publishing an official official package (or make it clear that the one I linked 'gmock' is the official one). They are very small and straightforward, as the package wouldn't include any built binaries but instead just have the source and target file to compile against. It would remove all ambiguity between this repo and the current various nuget packages for google test/mock, and would definitely encourage many people to start using google test (many people in my team and company too)!
> 
> Thanks,
> Pravin
> 
> ```
> diff --git a/DVM_DEVELOP/gmock.targets b/DVM_DEVELOP/gmock.targets
> index 04303f7e..2b163222 100644
> --- a/DVM_DEVELOP/gmock.targets
> +++ b/DVM_DEVELOP/gmock.targets
> @@ -11,12 +11,14 @@
>    <ItemGroup>
>      <ClCompile Include="$(MSBuildThisFileDirectory)..\..\lib\native\src\gtest\gtest-all.cc">
>        <PreprocessorDefinitions>;%(PreprocessorDefinitions)</PreprocessorDefinitions>
> +      <PrecompiledHeader>NotUsing</PrecompiledHeader>
>      </ClCompile>
>    </ItemGroup>
>  
>    <ItemGroup>
>      <ClCompile Include="$(MSBuildThisFileDirectory)..\..\lib\native\src\gmock\gmock-all.cc">
>        <PreprocessorDefinitions>;%(PreprocessorDefinitions)</PreprocessorDefinitions>
> +      <PrecompiledHeader>NotUsing</PrecompiledHeader>
>      </ClCompile>
>    </ItemGroup>
>  </Project>
> \ No newline at end of file
> ```

I'm just creating this issue to follow up on this. The nuget package is really useful, I'd love if we could sort out some proper coordination and responsibility around it, and make it possible for people to contribute changes to it.

Thanks!

**Comment by tmilnthorp** [comment]
I just spent some time to finally figure out those weren't official packages also. A NuGet package would be great.

**Comment by vslashg** [comment]
We would welcome efforts to improve the NuGet Google Test package, but we can't maintain unofficial Google Test packages in the many package managers that exist in the wild.

**Comment by Aralox** [comment]
Just to clarify your first point, do you mean you do want people to help contribute to any 'google test' nuget package, but not here, so it stays unofficial? 

As for your second point, that's exactly what I've opened this issue for. What's the reasoning behind that decision? I.e why not maintain official packages for the most popular and heavily used package managers like nuget? Sure, there are many package managers in the wild, but just like build systems, there are still a few that are well established and are relied upon by many businesses.
