### ISSUE TITLE
googletest doesn't build cleanly with warning 

### ISSUE THREAD

**Issue by zhangxy988** [google/googletest#2806]
According to https://github.com/google/googletest/pull/2772, googletest doesn't build cleanly with warning -Wgnu-zero-variadic-macro-arguments. We should probably fixes our code to compile cleanly with the warning and re-enable the travis config.

**Comment by Kangz** [comment]
Fixed (at least the gmock part) by https://github.com/google/googletest/commit/a09ea700d32bab83325aff9ff34d0582e50e3997, can you close the issue?
