### ISSUE TITLE
eclipse cdt code analyser issue with assert_eq / expect_eq

### ISSUE THREAD

**Issue by clauderobi** [google/googletest#2811]
Hi,

the eclipse code analyser (showing errors in the editor using the red underline, not sure about the name of this function in eclipse) is giving me an error for every single ASSERT_EQ and EXEPECT_EQ statements I put in my tests. Every other ASSERT_xxx or EXPECT_xxx are Ok. Even these simple (naive) statements are not Ok:
ASSERT_EQ((std::size_t)1, (std::size_t)0);
ASSERT_EQ(true, false);

The error wording says "Invalid arguments", which is not very helpful

I am using eclipse 20.03, with CDT 9.11, updated as of today.

**Comment by vslashg** [comment]
This sounds like an Eclipse bug which we are not equipped to handle.  If you can provide reproduction steps that demonstrate this is an issue on multiple editors, we can take a look.
