### ISSUE TITLE
Proto messages from open source protobufs are printed as bytes.

### ISSUE THREAD

**Issue by inazarenko** [google/googletest#2817]
Open source protobuf messages derive from `google::protobuf::MessageLite`.

GTest enables ProtbufPrinter based on:

```
template <typename T>
struct IsAProtocolMessage
   : public std::is_convertible<const T*, const ::proto2::MessageLite*> {};
```

So open-source protobufs are printed as bytes.

This was previously closed as "inactive": #1102

The issue still occurs at current master.

**Comment by inazarenko** [comment]
Somehow there are two merge commits in the log, and the final result is that the changes from #2818 are not actually present in master at the moment.

Is that intentional? @rogeeff

**Comment by asoffer** [comment]
This was rolled back as it caused conflicts internally. Rather than explicitly forward declaring these things, I think we need an approach that duck-types the messages.

**Comment by asoffer** [comment]
This should be fixed at head.
