### ISSUE TITLE
GTEST_SUPPRESS_UNREACHABLE_CODE_WARNING_BELOW_ doesn't seem work well with Clang's Wextra-semi-stmt

### ISSUE THREAD

**Issue by morlovich** [google/googletest#2823]
... This showed up for me since I am doing an unusual thing of building Chrome with RTTI, but it feels like other cases might hit it:

In file included from ../../third_party/dawn/src/tests/unittests/wire/WireTest.h:15:
In file included from gen/third_party/dawn/src/dawn/mock_webgpu.h:7:
In file included from ../../third_party/googletest/src/googlemock/include/gmock/gmock.h:61:
In file included from ../../third_party/googletest/src/googlemock/include/gmock/gmock-function-mocker.h:42:
In file included from ../../third_party/googletest/src/googlemock/include/gmock/gmock-spec-builders.h:75:
../../third_party/googletest/src/googlemock/include/gmock/gmock-matchers.h:3615:43: error: empty expression statement has no effect; remove unnecessary ';' to silence this warning [-Werror,-Wextra-semi-stmt]
        return internal::GetTypeName<T>());
                                          ^
../../third_party/googletest/src/googlemock/include/gmock/gmock-matchers.h:3676:43: error: empty expression statement has no effect; remove unnecessary ';' to silence this warning [-Werror,-Wextra-semi-stmt]
        return internal::GetTypeName<T>());
                                          ^
Where:
  static std::string GetTypeName() {
#if GTEST_HAS_RTTI
    GTEST_SUPPRESS_UNREACHABLE_CODE_WARNING_BELOW_(
        return internal::GetTypeName<T>());
#endif
    return "the element type";
  }

**Comment by hotwinter** [comment]
I encountered this issue as well when building chrome on Linux with `is_debug=true, is_asan=true, use_libfuzzer=true`, it looks like just simply removing the semicolon on `gmock-matchers.h:3615` works, since the macro itself does not need to be ended by an extra semicolon
