### ISSUE TITLE
A lot of erros on compilation in Windows

### ISSUE THREAD

**Issue by TiagoFunkUdescCeavi** [google/googletest#2833]
Hello Everyone.

I am trying to add Google Test Framework on my projectl, but i am a lot of erros on compilation.

Errors can be see on image:
![image](https://user-images.githubusercontent.com/19240101/80935176-d6ba3500-8da1-11ea-9483-925924ca0b39.png)

I am using MinGW as compiler, Eclipse as IDE. The operational system is Windows 7. I am adding files in project and import when using.

The command of compilation, for example (this is eclipse default): g++ -O0 -g3 -Wall -c -fmessage-length=0 -o "src\\example\\GeneratePopulationWithHeuristic.o" "..\\src\\example\\GeneratePopulationWithHeuristic.cpp".

Thanks in advance.

**Comment by diaa3007** [comment]
Try adding the -std=c++11 flag to the compiler.

Check this link explains how to do that in eclipse

https://stackoverflow.com/questions/9131763/how-to-enable-c11-c0x-support-in-eclipse-cdt

**Comment by asoffer** [comment]
The errors all look like they come from std::unique_ptr, so I believe the C++11 flag should resolve this issue.

Also, please consider usig bazel or cmake for your build system. GoogleTest supports these build systems and are, in general, unable to help in debugging raw command-line interfaces

**Comment by TiagoFunkUdescCeavi** [comment]
Hello again.
I added the flag -std=c++11 to the compiler and was unsuccessful.

I took advantage and tested the following flags: c++14, gnu++11 and gnu++14. In all of them I was not successful.

**Comment by diaa3007** [comment]
Try adding -Wno-deprecated-declarations flag

**Comment by TiagoFunkUdescCeavi** [comment]
The -Wno-deprecated-declarations flag didn't work either.
