### ISSUE TITLE
Capital-W Windows.h inclusion breaks MinGW cross compilation on GNU/Linux

### ISSUE THREAD

**Issue by hyd-dev** [google/googletest#2840]
Commit a9f6c1e adds capital-W `Windows.h` inclusion. However, MinGW only provides lowercased-W `windows.h`. The file system used on Linux is typically case-sensitive, so the compiler can't find `Windows.h` and aborts.

**Comment by mstorsjo** [comment]
This issue seems to have come from #2838, where an `#include <Windows.h>` was added next to an existing `#include <windows.h>`, in a misguided attempt to fix #2822. See #2838 for more commentary trying to clarify the misunderstanding that lead to this failed fix.

**Comment by asoffer** [comment]
Thanks. The fix for this is in our internal repository and will be upstreamed this week.

**Comment by hyd-dev** [comment]
Fixed by #2844.
