### ISSUE TITLE
ASSERT_EQ fails with **stack smashing detected**

### ISSUE THREAD

**Issue by lmiklosko** [google/googletest#2841]
Code  to reproduce:
```
STATIC uint8_t decode_uint8(const uint8_t *& data)
{
    return *(data++);
}
TEST(Decode, Uint8)
{
    const uint8_t stream[] = { 0xAA, 0xBB };
    const uint8_t* data = &stream[0];

    ASSERT_EQ(0xAA, decode_uint8(data));
    ASSERT_EQ(0xBB, decode_uint8(data));
}
```

removing ASSERT_EQ and replacing it with if (0xAA != decode_uint8_t(data)) {...} works without any problems. Code also works outside GTEST environment.

Env:
Ubuntu 18.04 LTS, g++ 8.3.0
GOOGLETEST_VERSION 1.10.0

**Comment by hyukmyeong** [comment]
Hello?

I checked in my environment (ubuntu 18.04 / g++ 7.5.0)
and both of them `ASSERT_EQ` and `if (0xAA != decode_uint8_t(data)) {...}` works well

I just modified like below because of tiny compile error

* `STATIC --> static`
* `decode_uint8_t --> decode_uint8`

**Comment by asoffer** [comment]
Similarly to @hyukmyeong, I am unable to reproduce this issue. Could you provide
* Exact reproduction instruction (compilation command)
* A stack trace
* Information about what happens when this is run with ASAN?

**Comment by asoffer** [comment]
@lmiklosko, I'm closing this as it is not reproducible with the current information. Please reopen if you have a reproducer for us. We'll be happy to look at.
