### ISSUE TITLE
Strange behavior if mock name is defined twice

### ISSUE THREAD

**Issue by dynaxo** [google/googletest#2847]
If you have two test files where each file defines a mock class with identical names and maybe even with same base class google test shows strange behavior (tests crash, ON_CALL & EXPECT_CALL not working, behavior can change when comments are added and removed again):
Example for setup:
Test file 1: `class MockDM : public DM {...`
Test file 2: `class MockDM : public DM {...`

The compiler did not warn about this doubly defined classes. I had to invest several days to find the cause for my problems. I'm not sure if this is even a googlemock bug or if this is just a follow up error caused by my error to give both mocks the same name. I'm curious to hear your opinion. 

IDE & compiler: Visual Studio 2017.

**Comment by sbenzaquen** [comment]
On Mon, May 11, 2020 at 1:54 PM dynaxo <notifications@github.com> wrote:

> If you have two test files where each file defines a mock class with
> identical names and maybe even with same base class google test shows
> strange behavior (tests crash, ON_CALL & EXPECT_CALL not working, behavior
> can change when comments are added and removed again):
> Example for setup:
> Test file 1: class MockDM : public DM {...
> Test file 2: class MockDM : public DM {...
>
> The compiler did not warn about this doubly defined classes. I had to
> invest several days to find the cause for my problems. I'm not sure if this
> is even a googlemock bug or if this is just a follow up error caused by my
> error to give both mocks the same name. I'm curious to hear your opinion.
>
> IDE & compiler: Visual Studio 2017.
>
If they are both in the same namespace with external linkage (ie they were
not in an anonymous namespace), you have an ODR violation
no-diagnostics-required.
This has undefined behavior in your code that is unrelated to googlemock.
A solution is to put pretty much all the symbols you define in a .cc test
file in an anonymous namespace.

**Comment by dynaxo** [comment]
I obviously underestimated the usefulness of anonymous namespace. Thank you very much for your explanation, it helped me a lot.
