### ISSUE TITLE
Premature Exit File causes a crash on Windows

### ISSUE THREAD

**Issue by ozio85** [google/googletest#2848]
If the premature_exit_filepath fails to open (e.g. if the file is created on a path longer than 260 chars on Windows), there is no check that the file was opened OK.

```
      # Line 4871 in googletest/src/gtest.cc:
      FILE* pfile = posix::FOpen(premature_exit_filepath, "w");
      fwrite("0", 1, 1, pfile);
      fclose(pfile);

```
The program will simply crash with the error code c0000409 (STATUS_FAIL_FAST_EXCEPTION)

**Comment by CJ-Johnson** [comment]
Would adding `assert(pfile != nullptr);` before the call to `fwrite(...);` be a sufficient fix?

**Comment by ozio85** [comment]
Well no.. since there is no real way of avoiding the long path (triggered by Bazel on Windows).

I added if (pfile != nullptr) around the fwrite call, and simply skipped writing the file in these cases.. but that would lead to a undeterministic behavior. I guess the real fix would be to use _wfopen on Windows, so the file is possible to open.

**Comment by CJ-Johnson** [comment]
Got it. Thanks! I've switched this to use `_wfopen` when run on Windows. This will be upstreamed in the next push.
