### ISSUE TITLE
static CMAKE_EXE_LINKER_FLAGS causes problem with gtest

### ISSUE THREAD

**Issue by Youssef1313** [google/googletest#2856]
Hi !
I'm working locally on a project (in CLion IDE) and have a CI pipeline on GitLab.
Here is my CMakeLists.txt and the gitlab yml config

![image](https://user-images.githubusercontent.com/31348972/82530053-ad88fb00-9b3c-11ea-8be2-8d0659db8a33.png)

Locally, the project works, and the unit tests works. However, At GitLab, I get the following warning:

>  /builds/USER/simple-interpreter/lib/gtest/googletest/src/gtest.cc:4758: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

What is the problem?
When I remove the CMAKE_EXE_LINKER_FLAGS line from the yml file, the unit tests work as expected. But I need to use CMAKE_EXE_LINKER_FLAGS.

**Comment by derekmauro** [comment]
We don't have expertise with this particular build configuration issue. You may want to try asking your question on a more general forum.
