### ISSUE TITLE
Crashpad fail to compile in Fedora Linux 32 

### ISSUE THREAD

**Issue by rvvillal** [google/googletest#2861]
Hi.

I'm compiling RStudio from source on Linux, but it fails compiling crashpad:

Your branch is up to date with 'rstudio/rstudio'.
Already up to date.
Done. Made 62 targets from 25 files in 7ms
ninja: Entering directory `out/Default'
ninja: error: '../../third_party/gtest/gtest/googletest/src/gtest-death-test.cc', needed by 'obj/third_party/gtest/gtest/googletest/src/gtest.gtest-death-test.o', missing and no known rule to make it

The issue is in the path of the source files, the file gtest-death-test.cc is searched at:
/opt/rstudio-tools/crashpad/crashpad/third_party/gtest/gtest/googletest/src/gtest-death-test.cc

but is here:
/opt/rstudio-tools/crashpad/crashpad/third_party/googletest/googletest/googletest/src/gtest-death-test.cc

I tried to modify the BUILD.ng files, but I haven't any success changing "gtest" for "googletest" in them.

Any suggestions?

Regards

**Comment by derekmauro** [comment]
Can you please ask this question on an RStudio forum? We don't support the RStudio build.
