### ISSUE TITLE
What is the compiling process of Google unit test?

### ISSUE THREAD

**Issue by Marvinmw** [google/googletest#2863]
Dear All,
I am curious if it is possible to compile the Google unit test to LLVM bitcode? I want to change the code that are tested and then run the test ( mutation)
Best 
Wei

**Comment by asoffer** [comment]
Googletest is typically compiled with either Bazel or CMake. Targetting LLVM bit-code is likely possible, but not something we currently support. If you look into the Bazel and CMake files, you may be able to find a way to get this to work.
