### ISSUE TITLE
googlemock depends on internal functions of googletest (ParseInt32).

### ISSUE THREAD

**Issue by devcooch** [google/googletest#2864]
We are compiling googlemock/googletest as shared libraries. Starting from version 1.10 we noticed that googlemock started to use ParseInt32 internal function from googletest which is not exported properly.
This unfortunately causes linker errors, e.g. on Linux with hidden symbols:
```
preinstall-image/lib/here/libGMock.so: error: undefined reference to 'testing::internal::ParseInt32(testing::Message const&, char const*, int*)'
```
or similar message on Windows (where symbols are always hidden anyway).

Is there recommended way to fix that?

**Comment by derekmauro** [comment]
Fixed by 9f287b46d1b103010748899ddd47250176565179.
