### ISSUE TITLE
Using ON_CALL and EXPECT_CALL together on the same mock function will usually result in unexpected mock function calls

### ISSUE THREAD

**Issue by kkaja123** [google/googletest#2865]
From what I can tell (by reading the documentation), this may be a design issue.

If I use ON_CALL to create a default action and use an EXPECT_CALL for different tests, the EXPECT_CALL will generate an unexpected mock function call if the call doesn't match (even though it matches the ON_CALL).

Example:
```
class ExampleTestFixture : public ::testing::Test
{
protected:
  ::testing::NiceMock<ExampleMockClass> exampleMock;

  void SetUp(void) override
  {
    ON_CALL(exampleMock, ExampleFunction(::testing::_))
      .WillByDefault(::testing::Return(0));
  }
}

TEST_F(ExampleTestFixture, ExampleTestCase)
{
  EXPECT_CALL(exampleMock, ExampleFunction(::testing::Ge(10))
    .WillRepeatedly(::testing::Return(5));

  ExampleClientClass clientUnderTest(&exampleMock);

  clientUnderTest.FunctionUnderTest(15);  // Calls ExampleMockClass::ExampleFunction(15)
  clientUnderTest.FunctionUnderTest(3);  // Calls ExampleMockClass::ExampleFunction(3)
}
```

In the above example, `clientUnderTest.FunctionUnderTest(15);` will satisfy the `EXPECT_CALL`. The following call will not match `EXPECT_CALL`, but it will match ON_CALL and performs the default action. Since there was an `EXPECT_CALL` that was not matched, GoogleMock declares that this is an "unexpected" mock function call, which is an error (not a warning, which the NiceMock would otherwise ignore).

In this case, it seems more logical to test that an EXPECT_CALL of any number of times was matched at least once. Instead, GoogleMock is testing that **every** call matches the expectation. The case where an error *would* be expected is if the EXPECT_CALL of Times(any) is *never* called.

The documentation recommends using ON_CALL like this, but using it like this tends to generate errors instead of robust tests. That's why I think this is more of a design issue.

**Comment by derekmauro** [comment]
This is a known shortcoming of the library that we probably aren't going to fix. I'd recommend not using `ON_CALL` in your `SetUp()` function in this case.

**Comment by artek-koltun** [comment]
Could you please provide an explanation why it won't be fixed? Is it just a way of how it is implemented, and it would require too much effort to change? Or any scenarios when the current behavior is useful?
