### ISSUE TITLE
Building gmock and gtest libraries for visual studio 2019

### ISSUE THREAD

**Issue by ben2289** [google/googletest#2871]
I am fairly new to building libraries and using cmake 3.16.7 and 3.17.3. I have been attempting to build the necessary libraries for gmock and gtest to use in VS studio 2019. I am using googletest 1.10

_C:\Users\Ben's PC\Desktop\googletest-master\build>cmake -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX=c:\\opt .._

I have been at this for a while and can't seem to find a solution. I keep getting the following error

-- The C compiler identification is MSVC 19.26.28805.0
-- The CXX compiler identification is MSVC 19.26.28805.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/Ben's PC/Desktop/googletest-master/build/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_b0077.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.

    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(5669,7): error MSB4023: Cannot evaluate the item metadata "%(FullPath)". The item metadata "%(FullPath)" cannot be applied to the path "@(_DebugSymbolsIntermediatePath->'C:\Users\Ben's PC\Desktop\googletest-master\build\CMakeFiles\CMakeTmp\Debug\%(Filename)%(Extension)')". Illegal characters in path. [C:\Users\Ben's PC\Desktop\googletest-master\build\CMakeFiles\CMakeTmp\cmTC_b0077.vcxproj]

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:10 (project)

-- Configuring incomplete, errors occurred!
See also "C:/Users/Ben's PC/Desktop/googletest-master/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Ben's PC/Desktop/googletest-master/build/CMakeFiles/CMakeError.log".

I can see that there might be a broken path, but I am not sure what to do. Am I on the right track to building these libraries? Is this even the best way to use gmock and gtest in VS 2019?

Any advice, thoughts would be greatly appreciated.

**Comment by derekmauro** [comment]
The error message seems to be complaining about an illegal character in your path. The single quote in `Ben's PC` seems suspicious. Can you try it in another directory? Otherwise I suspect is has something to do with your computer's configuration.
