### ISSUE TITLE
Make EXPECT_THROW and EXPECT_NO_THROW macros more informative

### ISSUE THREAD

**Issue by AmatanHead** [google/googletest#2878]
This is a continuation of #2071.

We could add catch case for `std::exception` to `EXPECT_THROW` to improve case when thrown exception is of an incompatible type.

If RTTI is available, we can also report the exact exception type by means of [`GetTypeName`](https://github.com/google/googletest/blob/fff8dabbf6c5641e97a646d710862508746183a2/googletest/include/gtest/internal/gtest-type-util.h#L71). This would further improve `EXPECT_THROW` and `EXPECT_NO_THROW` macros.

**Comment by CJ-Johnson** [comment]
Thank you for the Issue report. Unfortunately, this is not an area of expertise for us. Could you provide a PR for this change?

**Comment by CJ-Johnson** [comment]
The PR review is ongoing :)

**Comment by AmatanHead** [comment]
@CJ-Johnson I think it's merged: https://github.com/google/googletest/blob/master/googletest/include/gtest/internal/gtest-internal.h#L1320

**Comment by CJ-Johnson** [comment]
My apologies. I mistook it for this one: https://github.com/google/googletest/pull/2904
