### ISSUE TITLE
Build error with latest commit

### ISSUE THREAD

**Issue by Holt59** [google/googletest#2881]
Since the commit 4fe018038f87675c083d0cfb6a6b57c274fb1753, I get the following error when trying to build my project using `googletest` in VS 16.6.1:

> gtest/gtest-printers.h(190,11): error C2280: 'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const char32_t *)': attempting to reference a deleted function

I get similar error for all `charXX_t *` types.

Checking out 07d4a6e93de43ab47f5a5a3994009f53360e06c8 instead of 4fe018038f87675c083d0cfb6a6b57c274fb1753 fixes the issue.

**Comment by dpriedel** [comment]
I get a similar error trying to build with GCC 10 and -std=c++2a

`/usr/local/include/gtest/gtest-printers.h:190:11: error: use of deleted function ‘std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, const char32_t*) [with _Traits = std::char_traits<char>]’
  190 |       *os << p;
      |       ~~~~^~~~
In file included from /extra/gcc/gcc-10/include/c++/10.1.0/istream:39,
                 from /extra/gcc/gcc-10/include/c++/10.1.0/sstream:38,
                 from /extra/gcc/gcc-10/include/c++/10.1.0/bits/quoted_string.h:38,
                 from /extra/gcc/gcc-10/include/c++/10.1.0/iomanip:45,
                 from /extra/gcc/gcc-10/include/c++/10.1.0/bits/fs_path.h:39,
                 from /extra/gcc/gcc-10/include/c++/10.1.0/filesystem:45,
                 from Unit_Test.cpp:42:
/extra/gcc/gcc-10/include/c++/10.1.0/ostream:649:5: note: declared here
  649 |     operator<<(basic_ostream<char, _Traits>&, const char32_t*) = delete;
      |     ^~~~~~~~
`

**Comment by erthink** [comment]
Seems testing under GCC 10.x and MSVC-2019 should be added to CI.

**Comment by erthink** [comment]
There is a some workaround for this bug. Briefly: 
   - it is the [cmake-module](https://github.com/erthink/erthink/blob/master/cmake/testing.cmake) which able to download and checkout last **release** (or other specified branch/tag/commit) of GoogleTest.
   - and it is simple to use ([step 1](include("${CMAKE_CURRENT_SOURCE_DIR}/cmake/testing.cmake")), [step 2](https://github.com/erthink/erthink/blob/master/test/CMakeLists.txt)).

**Comment by CJ-Johnson** [comment]
@erthink Thank you for posting a workaround. Is this a sufficient solution? If not, are you able to provide a PR that would address this issue?

**Comment by derekmauro** [comment]
Is this still an issue with the latest commit? I think it is fixed.

**Comment by Holt59** [comment]
Seems to be fixed, at least for my projects.

**Comment by CJ-Johnson** [comment]
Thank you!
