### ISSUE TITLE
googlemock ‘NS_MICRO_THREAD’ not define

### ISSUE THREAD

**Issue by Jacklibobo** [google/googletest#2888]
googletest version:release 1.8.0

when i use 1.8.0 version make unittest. there was some error:
[ 80%] Building CXX object googletest/googlemock/CMakeFiles/gmock_main.dir/__/googletest/src/gtest-all.cc.o
[ 86%] Building CXX object googletest/googlemock/CMakeFiles/gmock_main.dir/src/gmock-all.cc.o
[ 93%] Building CXX object googletest/googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
/data/xxx/googletest/googlemock/src/gmock_main.cc: In function ‘int main(int, char**)’:
/data/xxx/googletest/googlemock/src/gmock_main.cc:48: 错误：‘NS_MICRO_THREAD’未声明

**Comment by CJ-Johnson** [comment]
Thank you for the Issue report. Are you able to provide full platform information and reproduction instructions?
