### ISSUE TITLE
Override missing on MATCHER Macro

### ISSUE THREAD

**Issue by ericriff** [google/googletest#2897]
Hi guys, 
I'm refactoring old code on a linux project. Since one of the requirements was to build with `Wsuggest-override`, we upgraded the gtest version to `1.10.0` to be able to specify override at the end of every `MOCK_METHOD` macro. This worked flawlessly.
In a piece of code we're using a custom `MATCHER` macro to check the extension of a file. Since the string is a QString, we can't use the built in EndsWith matcher.

`MATCHER(QStringEndsWithTxt, "") { return arg.endsWith(".txt"); }`

`EXPECT_CALL(mockFileHelper, doSomething(QStringEndsWithTxt());`

The matcher works but when we build with `Wsuggest-override` we get errors saying that we're missing an "override" on the method created by the matcher. 

`error: ‘bool QStringEndsWithTxtMatcher::gmock_Impl<arg_type>::MatchAndExplain(typename testing::internal::ConstRef<arg_type>::type, testing::MatchResultListener*) const [with arg_type = const QString&; typename testing::internal::ConstRef<arg_type>::type = const QString&]’ can be marked override [-Werror=suggest-override]`

Is there a way to instruct the macro to add overrides when needed? Like we do with the `MOCK_METHOD` macro.
Thanks,
Eric.

**Comment by zhangxy988** [comment]
This seems to be working fine on master branch.
I traced it back to
- 3cddd56e195b516f449bea6dcd3edd4494195631 which adds keyword `override`.
- 41b5f149ab306e96b5b2faf523505d75acffd98a which refactors the code to remove the ".pump" files.
My suggestion would be to use the master branch for now and wait for the next release.
Alternatively, you could patch your copy of the googletest 1.10.0 to add `override` just like 3cddd56e195b516f449bea6dcd3edd4494195631 did.
