### ISSUE TITLE
provide binary packages for googletest in Ubuntu/Debian

### ISSUE THREAD

**Issue by ericoporto** [google/googletest#2905]
The packages provided in Ubuntu come without any binaries. [There used to be a recommendation here that googletest should be provided directly in the project repository](https://web.archive.org/web/20150801115151/https://code.google.com/p/googletest/wiki/FAQ#Why_is_it_not_recommended_to_install_a_pre-compiled_copy_of_Goog). Since it's gone and the package is not included or picked in [other projects,](https://github.com/google/shaderc) it would be recommended the libary shipped in Debian/Ubuntu not be a header only and provide the required binaries so gmock and other useful tools could be used without building from source.

**Comment by derekmauro** [comment]
We have nothing to do with distro provided packages. Please request this from the distro.

**Comment by ericoporto** [comment]
It would be good if there was something in the README for maintainers know it's alright to ship binaries now since it was asked not to in the past.

**Comment by ericoporto** [comment]
See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802587

**Comment by ericoporto** [comment]
Saying "We have nothing to do with distro provided packages" won't fix things when there's a clear communication issue somewhere.
