### ISSUE TITLE
Unresolved symbol when using parameterized test

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#292]
```
I'm using WXP, MSVC 2008 with gtest 1.5 built as DLL.

I have a parameterized testcase (TEST_P) cpp file which is also linked into 
DLL. When building the testcase, I get the following linker error:


Error   1   error LNK2001: unresolved external symbol "class 
testing::internal::Mutex testing::internal::g_linked_ptr_mutex" 
(?g_linked_ptr_mutex@internal@testing@@3VMutex@12@A)    test_Mechanic.obj

```

Original issue reported on code.google.com by `constant...@gmail.com` on 11 Jun 2010 at 7:56

**Comment by louis-langholtz** [comment]
I've been seeing this crop up when building static libraries on Windows 10 with MSVC 2017. Any specific details you want on this? It may also be a problem when I'm building dynamic libraries but I'm running into other problems then that may be occluding seeing this as a problem for dynamic builds.

**Comment by NauticalMile64** [comment]
@louis-langholtz I think @GoogleCodeExporter is a bot or something. I don't know if anyone else is watching this issue...

**Comment by NauticalMile64** [comment]
@sgraham @gennadiycivil Can this issue be reopened?

**Comment by gennadiycivil** [comment]
The original issue is for MSVC 2008. This is a very old version of Visual Studio. 
Does this still happen with more modern compiler?

**Comment by NauticalMile64** [comment]
Yes. I am seeing it as of VS 15.3.3 2017. The full error in my case is:

> LNK2019	unresolved external symbol "class testing::internal::Mutex testing::internal::g_linked_ptr_mutex" (?g_linked_ptr_mutex@internal@testing@@3VMutex@12@A) referenced in function "public: virtual void __cdecl testing::internal::ParameterizedTestCaseInfo<class VerticalStackTest>::RegisterTests(void)" (?RegisterTests@?$ParameterizedTestCaseInfo@VVerticalStackTest@@@internal@testing@@UEAAXXZ)	UnitTests	C:\path\to\PlayRho\Build\cmake-build\UnitTests\World.obj	1

**Comment by emptyVoid** [comment]
I've just stumbled upon this issue while implementing value-parameterized tests (beforehand we had no issues with linking against dynamic ```gtest``` library). And I've managed to fix it by building my tests with a preprocessor definition ```GTEST_LINKED_AS_SHARED_LIBRARY```.

**Comment by Knitschi** [comment]
Is `GTEST_LINKED_AS_SHARED_LIBRARY` something that you use in your code, or an official cmake switch for **GTest**?

**Comment by emptyVoid** [comment]
It's a preprocessor definition that should be set while building the code that uses *GTest* as shared library. I've personally set it in my project's properties.

**Comment by Knitschi** [comment]
using `target_compile_definitions( GMockConsumer PRIVATE -DGTEST_LINKED_AS_SHARED_LIBRARY )` fixes the compiler error, but causes a lot of 
````
warning C4251: 'identifier' : class 'type' needs to have dll-interface to be used by clients of class 'type2' 
````
warnings for me.

**Comment by Knitschi** [comment]
Maybe it is also worth mentioning that the problem only occurs for me when using the generator option `-G"Visual Studio 14 2015"` for **x86** builds. When building with `-G"Visual Studio 14 2015 Win64"`, it builds and links fine.

**Comment by emptyVoid** [comment]
If those C4251 warnings mention standard library components (such as std::basic_string), you can ignore/disable them as long as you build **GTest** and your own code using the same compiler and the same 'Runtime Library' settings.

**Comment by Gil-Mor** [comment]
I'm trying to build gtest 1.8 with CMake and VS2017 with Value Parameterized Tests and I get this error:

Error LNK2001 unresolved external symbol "class testing::internal::Mutex testing::internal::g_linked_ptr_mutex" (?g_linked_ptr_mutex@internal@testing@@3vmutex@12@A)

I don't want to apply the solution of setting GTEST_LINKED_AS_SHARED_LIBRARY=1 because I don't want to compile my code into a shared lib (I'm building gtest 1.8 as a shared lib). Is there a solution in this case?

My code compiles if I remove this code:

TEST_P(DerivedTests, SomeTest)
{
    ...
}

INSTANTIATE_TEST_CASE_P(JustSomeTestCaseNamePrefix,
    DerivedTests,
    ::testing::Values( custom_value_a, custom_value_b) );
Complete Code:

Class TestsBase : public Base, public ::testing::WithParamInterface< CustomType_t >
{
public:
    virtual void SetUp()
    {
        val_ = GetParam();
    }
protected:
    CustomType_t val_;

};
and Class Base is:

Class Base : public ::testing::Test 
{
    ...
};
I am building with set(BUILD_SHARED_LIBS on) and also
set(BUILD_SHARED_LIBS ON CACHE BOOL "Build shared libraries (DLLs)." FORCE)
set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)

I'm using CMake and VS 2017.

Any help would be appreciated. Thanks

**Comment by bolbol2night** [comment]
I've this issue with VS2019 (16.9). I'm using "Microsoft.googletest.v140.windesktop.msvcstl.dyn.rt-dyn" version="1.8.1.3".
The LNK2001 error (external symbol not resolved: "class testing::internal::Mutex testing::internal::g_linked_ptr_mutex" (?g_linked_ptr_mutex@internal@testing@@3VMutex@12@A)) is preceeded by some warning related to critical sections and mutex.

**Comment by JarekParal** [comment]
I have VS2019 (16.11.7 v142), Windows SDK 10.0.18362.0 and ISO C++17 Standard (/std:c++17). I tried the advice from a comment above to fix this error message which I got after adding a parametrized test:
```bash
error LNK2001: unresolved external symbol "class testing::internal::Mutex testing::internal::g_linked_ptr_mutex" (?g_linked_ptr_mutex@internal@testing@@3VMutex@12@A)
```

When I added this:
```cpp
testing::internal::Mutex testing::internal::g_linked_ptr_mutex;
```
before the `INSTANTIATE_TEST_CASE_P(...` the compilation starts to work but there is a problem with the Exit code after the GTest finish the execution -> breaking the CI build:
```bash
[----------] Global test environment tear-down
[==========] 14 tests from 3 test cases ran. (1742 ms total)
[  PASSED  ] 14 tests.

D:\sandbox\LX\Libraries\lx_circle_detection\Release>echo Exit Code is %errorlevel%
Exit Code is -1073741819
```

I'm using the GTest 1.8.1.4 Nuget package from Microsoft: [Microsoft.googletest.v140.windesktop.msvcstl.dyn.rt-dyn](https://www.nuget.org/packages/Microsoft.googletest.v140.windesktop.msvcstl.dyn.rt-dyn/1.8.1.4)

Any suggestion on how to fix this error? @louis-langholtz @emptyVoid @Knitschi @Gil-Mor

**Comment by Shawn1874** [comment]
This article does suggest that the preprocessor definition should be added when linking to google test built as a shared library.
https://github.com/google/googletest/blob/main/googletest/README.md

The documentation does state that using that preprocessor definition will become necessary at some point for some compilers and recommends that we always define it when linking google test as a shared library.

**Comment by JarekParal** [comment]
Thank you, @Shawn1874. After adding the preprocessor definition `GTEST_LINKED_AS_SHARED_LIBRARY` for all the build configurations, the build passed.
