### ISSUE TITLE
user friendly CMakeLists.txt missing

### ISSUE THREAD

**Issue by oneptr** [google/googletest#2924]
For some reason I get a lot of compile errors when trying to compile google test. There are many 1000's of lines of error output.
The gcc compile flag -Wfatal-errors is meant to stop after encountering the first error. Looking into CMakeLists.txt it is completely unclear to me how to add this flag!

1. Please describe how additional compile time flags can be added.
2. change the CMakeFile.txt in such a way that it is obvious how to do this.

**Comment by vacing** [comment]
try this 
```
cmake ../ -DCMAKE_CXX_FLAGS="-std=c++11"
```

**Comment by asoffer** [comment]
This is primarily a CMake issue rather than a GoogleTest issue. Unfortunately we are not CMake experts and cannot provide guidance here.
