### ISSUE TITLE
-std=c++11 missing

### ISSUE THREAD

**Issue by oneptr** [google/googletest#2925]
I'm using an old compiler (gcc 4.9.2) which has C++11 support, but it needs to be enabled with the compiler flag -std=c++11. The CMakefile.txt does not use this compiler flag; it defaults to c++98, which leads to many compile errors.

1. Please add -std=c++11 compiler flag
2. check for compiler supported language level, and if it doesn't meet requirements, issue ONE simple error message, like C++11 or whatever not supported by installed compiler, instead of spitting out 10,000's of non-sense error messages.

**Comment by vacing** [comment]
try this
```sh
cmake ../ -DCMAKE_CXX_FLAGS="-std=c++11"
```

**Comment by derekmauro** [comment]
I believe this has been fixed at head.
