### ISSUE TITLE
Question : Death tests for capturing cout

### ISSUE THREAD

**Issue by nayakche** [google/googletest#2929]
I would like to write death tests for an application where exit code is 0 and there is some message displayed on cout instead of cerr. 

`
void display_help(){
  //std::cerr.set_rdbuf(std::cout.rdbuf());
  //std::cerr << "From display_help" << std::endl;
  std::cout << "From display_help"<< std::endl;
  std::exit(0);
}

TEST_F(CommandlineTest, help_function_test)
{
  std::string exectedHelpMessage{ "" };
  exectedHelpMessage += std::string("From display_help");
  
  EXPECT_EXIT(display_help(),
              ::testing::ExitedWithCode(0),
              ::testing::ContainsRegex(exectedHelpMessage));
}
` 
The above code fails because, its unable to match the message. My observation is, when the display_help function displays a message in cerr death test is able to capture. But, when the some thing is printed on cout its not able to capture.  
Is there any suggestion on how such testing can be enabled ?

**Comment by zhangxy988** [comment]
Currently, `EXPECT_EXIT|DEATH` only checks for stderr, not stdout. And I don't think we would consider a design change for this particular use case.
Does `CaptureStdout` work for you, as mentioned in https://stackoverflow.com/a/33186201? However, be wary that you are reaching into internal APIs here.

**Comment by nayakche** [comment]
IThanks for the hint. I will check and get back to you on this. 

However, what is gtest recommendation for testing these kind of cases without reaching out to internal API. Because, I am pretty sure that application would not prefer to write help message to r while exiting. 
Meanwhile, when we can capture even ೦ as exit code with ExitedWithExitCode , will it be a big expectation for providing this flexibility ? :blush:

**Comment by derekmauro** [comment]
I would recommend just using some form of dependency injection that allows you to write to a sink that you can capture from, and use a sink the writes to stdout when not testing.
