### ISSUE TITLE
Shifting arguments breaks ABI assumption about environment

### ISSUE THREAD

**Issue by josephcsible** [google/googletest#2933]
https://github.com/google/googletest/blob/78fdd6c00b8fa5dd67066fbb796affc87ba0e075/googletest/src/gtest.cc#L6043-L6052

Shifting the arguments following the removed one to the left breaks the ABI assumption that `envp` starts immediately after the null pointer in `argv`, which caused [LLVM issue #46598](https://bugs.llvm.org/show_bug.cgi?id=46598). Shouldn't this instead increment the caller's `argv` by 1, and then shift the arguments preceding the removed one to the right instead?

**Comment by CJ-Johnson** [comment]
Thank you for this issue report! Googletest reserves the right to modify the command line flags, so fixing this is not feasible.

**Comment by josephcsible** [comment]
Couldn't they still be modified by shifting from the other end?
