### ISSUE TITLE
None of the links in gMock documentation work

### ISSUE THREAD

**Issue by drczuckerman** [google/googletest#2938]
Every link that I click on in the following pages does not take me to the referenced section:
- [For Dummies](https://github.com/google/googletest/blob/master/googlemock/docs/for_dummies.md)
- [FAQ](https://github.com/google/googletest/blob/master/googlemock/docs/gmock_faq.md)
- [Cook Book](https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md)
- [Cheat Sheet](https://github.com/google/googletest/blob/master/googlemock/docs/cheat_sheet.md)

Instead, it either goes to the top of the page (if linked to an external document) or stays on the same page (if linked to an anchor on this document). I'm assuming that having `{#link}` in the header is supposed to create that anchor tag. If that is the intent, it is not working. For example, in the cook book, this header, `Combining Matchers {#CombiningMatchers}`, has [this link](https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md#combining-matchers-combiningmatchers).

**Comment by vslashg** [comment]
There is a tension here between the markdown library we use internally and the one used in github.  We want to have a single source of truth for the documentation, but there is no easy way for us to write these links so that they work in both environments.

We will try to find a solution to this that we can maintain.

**Comment by ericschmidtatwork** [comment]
I'm going to close this since these links now work on our [GitHub Pages site](https://google.github.io/googletest/) and we recommend browsing the documentation there instead of in the GitHub repo browser.

Example: https://google.github.io/googletest/gmock_cook_book.html#CombiningMatchers
