### ISSUE TITLE
Two the same values are not equal in multithreaded code

### ISSUE THREAD

**Issue by Chukak** [google/googletest#2951]
I get the following situation: 
There are some threads in my code, `gtest 1.8.0`. One of this threads modifies some variable. This variable is compared with another using a macro `EXPECT_EQ`. I was a little confused, when i got the output:
```
...: Failure
      Expected: callsCount
      Which is: 2
To be equal to: 2
```
Also, i could reproduce this situation outside of my code, using `master` branch:
```cpp
#include <thread>
#include <atomic>
#include <gtest/gtest.h>

int main(int argc, char** argv)
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}

TEST(Test, CompareTwoBoolean)
{
    bool a = 1, b = 1;
    std::atomic_bool run(true);
    auto thread1 = std::thread([&b, &run]() { while(run) b = !b; });
    std::this_thread::sleep_for(std::chrono::microseconds(1));
    for(int i = 0; i < 100; i++) EXPECT_EQ(a, b);
    run = false;
    thread1.join();
}
```
Output:
```
...: Failure
Expected equality of these values:
  a
    Which is: true
  b
    Which is: true
...: Failure
Expected equality of these values:
  a
    Which is: true
  b
    Which is: true
```

**Comment by sbenzaquen** [comment]
Your code has a race condition while accessing `b` and that has undefined
behavior in C++.
The output you get does not have to make sense because it violates the
contract of the language.

**Comment by Chukak** [comment]
Okay, i knew about race condition, but i didn't think, that a value which passed by `const ref` also has UB in this case. Anyway, i understand how to fix this situation. Thanks for your reply, phrase `because it violates the contract of the language` got me thinking. 
Ways to fix this situation:
1) use a `std::atomic<T>` and load values in macro: `EXPECT_EQ(a.load(), a.load())`. This will make a copy that will be passed to the printer function.
2) use mutex.

Also, can make a copy before [this code](https://github.com/google/googletest/blob/master/googletest/include/gtest/gtest.h#L1544), or pass a copy to macro. But, it doesn't guarantee, that value doesn't modify in copy constructor.

**Comment by sbenzaquen** [comment]
On Fri, Jul 17, 2020 at 5:36 PM Sergey Fedorov <notifications@github.com>
wrote:

> Okay, i knew about race condition, but i didn't think, that a value which
> passed by const ref also has UB in this case. Anyway, i understand how to
> fix this situation. Thanks for your reply, phrase because it violates the
> contract of the language got me thinking.
> Ways to fix this situation:
>
>    1. use a std::atomic<T> and load values in macro: EXPECT_EQ(a.load(),
>    a.load()). This will make a copy that will be passed to the printer
>    function.
>    2. use mutex.
>
> Both of these would remove the race condition.

>
>
> Also, can make a copy before this code
> <https://github.com/google/googletest/blob/master/googletest/include/gtest/gtest.h#L1544>,
> or pass a copy to macro. But, it doesn't guarantee, that value doesn't
> modify in copy constructor.
>
We can't make a copy, because the object might not be copyable.
But the race condition and undefined behavior is there anyway.

The compiler can assume that UB doesn't happen and can optimize based on
this assumption.
It could, for example, unroll that loop and do the comparison once since it
can see that nothing changes the values. Because if something did that
would have been UB so it doesn't matter.
Or you could see partial writes.
Or any number of other invalid results.

Hitting UB means that your program is not a valid C++ program and the
compiler has no requirement to give you a valid output.

**Comment by Chukak** [comment]
Thanks for the explanation. I am closing this issue because it is not a Googletest problem.
