### ISSUE TITLE
Mock does not fail despite error on call count

### ISSUE THREAD

**Issue by csorvagep** [google/googletest#2974]
The test below succeeds even though it shows an error on call count. This bug is probably related to #2890, but I'm not sure, so I created a new issue.

```c++
#include "gmock/gmock.h"
#include "gtest/gtest.h"

using namespace ::testing;
using ::testing::Return;

class Interf {
public:
    virtual void f() = 0;
};

class MockInterf final : public Interf {
public:
    MOCK_METHOD(void, f, (), (override));
};

TEST(GMockTests, expectCallTest)
{
    MockInterf mi;
    EXPECT_CALL(mi, f)
        .Times(1);
}
```
GoogleTest version 1.10.0 (vcpkg)

ps: I also created a stackoverflow [question](https://stackoverflow.com/questions/63220849/gmock-expect-call-failed-but-test-returns-ok-while-mocking-c-functions) yesterday, because I thought it is related to C free function testing.

**Comment by asoffer** [comment]
I've built this with GoogleTest version 1.10.0 on Linux Mint with Bazel and the test fails as expected. Can you verify that this is not due to a patch from vcpkg?

**Comment by hyukmyeong** [comment]
I can see the correct result with linux(ubuntu) + g++ + googletest v1.10.0
even though I can reproduce https://github.com/google/googletest/issues/2890 in my envrionment

and so I think these two issues are different

**Comment by csorvagep** [comment]
@asoffer You were right, I tried as a submodule and it worked as it should.

I disabled the patches in vcpkg and the issue still persists. I have no idea what else could it be, but I guess, this is now a vcpkg issue.

**Comment by asoffer** [comment]
Thanks for checking. I'm going to close is... please feel free to reopen it if this turns out to be an issue we can help with.
