### ISSUE TITLE
Disabling a test from a test suite is not reflected properly in documentation

### ISSUE THREAD

**Issue by lkotsonis** [google/googletest#2986]
The documentation states that disabling a test from a test suite is done with:
```
TEST_F(DISABLED_BarTest, Doesxyz)
```

but this does not compile. This works though:

```
TEST_F(BarTest, DISABLED_Doesxyz)
```

with gtest version 1.10.0

**Comment by vslashg** [comment]
Both of these work, and they have different meaning.  The section of [docs/advanced.md](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md) you are referencing says this:

> If you need to disable all tests in a test suite, you can either add DISABLED_ to the front of the name of each test, or alternatively add it to the front of the test suite name.

And it gives two examples.  The first is:

```
// Tests that Foo does Abc.
TEST(FooTest, DISABLED_DoesAbc) { ... }
```

This pattern disables the `DoesAbc` test from the `FooTest` suite, but other tests from the `FooTest` suite will be run.

The second is:

```
class DISABLED_BarTest : public ::testing::Test { ... };

// Tests that Bar does Xyz.
TEST_F(DISABLED_BarTest, DoesXyz) { ... }
```

This disables the entire test suite, but it requires you to rename the test suite class as well.  (Essentially you would need to search-and-replace `BarTest` with `DISABLED_BarTest` in your entire foo_test.cc file.)

**Comment by lkotsonis** [comment]
I somehow misread the documentation. Thanks for replying @vslashg. It would be nice to have the explanation for the second case though.
