### ISSUE TITLE
Printing std::pair and std::tuple of const types selects wrong printer

### ISSUE THREAD

**Issue by gregwb** [google/googletest#2987]
I noticed when googletest prints e.g. a `map<variant<...>, int>` object, the keys wrongly printed as bytes.  

This looks like it is because the [`PrintTo()`](https://github.com/google/googletest/blob/adeef192947fbc0f68fa14a6c494c8df32177508/googletest/include/gtest/gtest-printers.h#L610) overload for `pair` delegates to `UniversalPrinter<T1>` but T1 is const qualified.  This means `UniversalPrinter<>` specializations are not used.

I see this issue affects both `pair<>` and `tuple<>` if the inner types are a `const` `variant`/`optional`/`any`

**Comment by alex-weej** [comment]
Are variant/optional/any special here, somehow? Why does a map<variant, ...> have this problem but not a map<string, ...>? What about vector?

Seems reasonable that we should strip cv qualifiers (and maybe references too?) when delegating. `std::decay_t` may be the best approach?

**Comment by alex-weej** [comment]
It looks like the tuple printer has the same problem:

https://github.com/google/googletest/blob/adeef192947fbc0f68fa14a6c494c8df32177508/googletest/include/gtest/gtest-printers.h#L593

The comment in the pair printer is interesting:

```c++
  // We cannot use UniversalPrint(value.first, os) here, as T1 may be
  // a reference type.  The same for printing value.second.
```

If T1 is a reference type then `std::remove_reference_t` would also be fine. I guess these type traits didn't exist prior to C++11 so someone tried to avoid writing them for C++98 and unwittingly introduced this 'bug'?

(Aside, seems like the pair printer should just defer to the tuple printer anyway...)

**Comment by gregwb** [comment]
The comment  in the pair printer 
https://github.com/google/googletest/blob/adeef192947fbc0f68fa14a6c494c8df32177508/googletest/include/gtest/gtest-printers.h#L608 suggests to me that it is intentional to delegate to the `class UniversalPrinter<T&>` specialisation (and not strip the reference)

As to why this issue affects variant/optional/any in particular, it's because these types have specialisations for class `class UniversalPrinter<T>` whereas other types customise printing with other mechanisms (such as overloading `PrintTo()`).  I'm not sure if there's any particular reason for one method over the other.

**Comment by alex-weej** [comment]
But std::string doesn't get printed via `PrintTo` either... Or are we accidentally deferring to `ostream<<string` (thus missing the quotes, etc.) in this context?
