### ISSUE TITLE
EXPECT_DEATH test passes but leaves a dumped core

### ISSUE THREAD

**Issue by lavigne958** [google/googletest#2990]
In a test I run I make the test trigger, in purpose, a call to `assert(0)`.

I use the macro `EXPECT_DEATH` to check the assert is triggered, the test runs fine, but it still generates a core dump.

This is a issue for the CI environment I use, if any core dump is generated the CI fails (which is a fairly descent behavior).

Here is an example of the code snippet I use:
```
TEST_F(Module, TestCase!
{
  int *foo = new_foo();
  ASSERT_NE(foo, nullptr);
  foo.bar = 42;
  destroy_foo(foo);
  foo = nullptr;
  EXPECT_DEATH(destroy_foo(foo), "memory error");  /* triggers: assert(0) */
}
```

I found the following issue that is related and provides a workaround but I am interested in any solution or the reason why it still generates the core dump. #237 

both systems I use:
OS: ubuntu bionic / centos 8
glibc: (ubuntu) GLIBC 2.27-3ubuntu1.2 / (centos) (GNU libc) 2.28

**Comment by lavigne958** [comment]
Someone around me told me that the Gtest framework starts a clone process to run the statement checked by `ASSERT_DEATH` .

Therefore we can not prevent it from creating a core-dump, not via the Gtest framework.

**Comment by jmundack** [comment]
Can we clean up corefiles at the end of the test then?
