### ISSUE TITLE
Mocking std::function with a reference parameter

### ISSUE THREAD

**Issue by bodnarpolina** [google/googletest#2996]
I want to mock my std::function taking int as a reference. So I have a mock like this:
`using MyFunc = testing::MockFunction<std::string(int&)>;`

And in the body of my test I have the next code:
`  MyFunc f;`
 ` f.AsStdFunction();`

But during compilation I get an error:
'std::basic_string<char,std::char_traits<char>,std::allocator<char>> testing::MockFunction<std::string (int &)>::Call(int &)': cannot convert argument 1 from 'int' to 'int &'

**Comment by sbenzaquen** [comment]
Can you provide more complete repro instructions?
This quick test seems to work: https://gcc.godbolt.org/z/KvbTGr

**Comment by bodnarpolina** [comment]
Thanxs for the answer. I see that it works for u. Is it possible that the problem is with GMock library version? We use version 1.8.1.

**Comment by hyukmyeong** [comment]
@bodnarpolina 

I can reproduce the same problem with 1.8.x
but It is OK with 1.10.x

**Comment by derekmauro** [comment]
Closing this as it is fixed in 1.10.0.
