### ISSUE TITLE
Error: static assertion failed: throw() cannot be recognized as a valid specification modifier.

### ISSUE THREAD

**Issue by adcicnx** [google/googletest#3002]
Configuration:
centos 8 on wsl2 with gcc 9.2.1
gtest and gmock builded with c++11

/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:163:43: error: static assertion failed: throw() cannot be recognized as a valid specification modifier.
  159 |       (GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_CONST(_i, _, _elem)) +    \
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  160 |        GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_OVERRIDE(_i, _, _elem)) + \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  161 |        GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_FINAL(_i, _, _elem)) +    \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  162 |        GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_NOEXCEPT(_i, _, _elem)) + \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  163 |        GMOCK_INTERNAL_IS_CALLTYPE(_elem)) == 1,                           \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:163:43: note: in definition of macro ‘GMOCK_INTERNAL_ASSERT_VALID_SPEC_ELEMENT’
  163 |        GMOCK_INTERNAL_IS_CALLTYPE(_elem)) == 1,                           \
      |                                           ^~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:259:3: note: in expansion of macro ‘GMOCK_PP_INTERNAL_CALL_MACRO’
  259 |   GMOCK_PP_INTERNAL_CALL_MACRO(_Macro, _i, _Data, GMOCK_PP_HEAD _Tuple)
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:262:3: note: in expansion of macro ‘GMOCK_PP_INTERNAL_FOR_EACH_IMPL_1’
  262 |   GMOCK_PP_INTERNAL_FOR_EACH_IMPL_1(GMOCK_PP_INC(_i), _Macro, _Data,    \
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:180:39: note: in expansion of macro ‘GMOCK_PP_INTERNAL_FOR_EACH_IMPL_2’
  180 | #define GMOCK_PP_INTERNAL_CAT(_1, _2) _1##_2
      |                                       ^~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:100:3: note: in expansion of macro ‘GMOCK_PP_FOR_EACH’
  100 |   GMOCK_PP_FOR_EACH(GMOCK_INTERNAL_ASSERT_VALID_SPEC_ELEMENT, ~, _Spec)
      |   ^~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:59:3: note: in expansion of macro ‘GMOCK_INTERNAL_ASSERT_VALID_SPEC’
   59 |   GMOCK_INTERNAL_ASSERT_VALID_SPEC(_Spec)                                     \
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:180:39: note: in expansion of macro ‘GMOCK_INTERNAL_MOCK_METHOD_ARG_4’
  180 | #define GMOCK_PP_INTERNAL_CAT(_1, _2) _1##_2
      |                                       ^~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:18:30: note: in expansion of macro ‘GMOCK_PP_INTERNAL_CAT’
   18 | #define GMOCK_PP_CAT(_1, _2) GMOCK_PP_INTERNAL_CAT(_1, _2)
      |                              ^~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:82:3: note: in expansion of macro ‘GMOCK_PP_CAT’
   82 |   GMOCK_PP_CAT(_Macro, GMOCK_PP_NARG(__VA_ARGS__))(__VA_ARGS__)
      |   ^~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:43:3: note: in expansion of macro ‘GMOCK_PP_VARIADIC_CALL’
   43 |   GMOCK_PP_VARIADIC_CALL(GMOCK_INTERNAL_MOCK_METHOD_ARG_, __VA_ARGS__)
      |   ^~~~~~~~~~~~~~~~~~~~~~
mock_jsondict_mapping.h:8:2: note: in expansion of macro ‘MOCK_METHOD’
    8 |  MOCK_METHOD(bool, AlreadyInitialized, (), (const, NOEXCEPT));
      |  ^~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:163:43: error: static assertion failed: throw() cannot be recognized as a valid specification modifier.
  159 |       (GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_CONST(_i, _, _elem)) +    \
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  160 |        GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_OVERRIDE(_i, _, _elem)) + \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  161 |        GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_FINAL(_i, _, _elem)) +    \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  162 |        GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_NOEXCEPT(_i, _, _elem)) + \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  163 |        GMOCK_INTERNAL_IS_CALLTYPE(_elem)) == 1,                           \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:163:43: note: in definition of macro ‘GMOCK_INTERNAL_ASSERT_VALID_SPEC_ELEMENT’
  163 |        GMOCK_INTERNAL_IS_CALLTYPE(_elem)) == 1,                           \
      |                                           ^~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:259:3: note: in expansion of macro ‘GMOCK_PP_INTERNAL_CALL_MACRO’
  259 |   GMOCK_PP_INTERNAL_CALL_MACRO(_Macro, _i, _Data, GMOCK_PP_HEAD _Tuple)
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:180:39: note: in expansion of macro ‘GMOCK_PP_INTERNAL_FOR_EACH_IMPL_1’
  180 | #define GMOCK_PP_INTERNAL_CAT(_1, _2) _1##_2
      |                                       ^~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:100:3: note: in expansion of macro ‘GMOCK_PP_FOR_EACH’
  100 |   GMOCK_PP_FOR_EACH(GMOCK_INTERNAL_ASSERT_VALID_SPEC_ELEMENT, ~, _Spec)
      |   ^~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:59:3: note: in expansion of macro ‘GMOCK_INTERNAL_ASSERT_VALID_SPEC’
   59 |   GMOCK_INTERNAL_ASSERT_VALID_SPEC(_Spec)                                     \
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:180:39: note: in expansion of macro ‘GMOCK_INTERNAL_MOCK_METHOD_ARG_4’
  180 | #define GMOCK_PP_INTERNAL_CAT(_1, _2) _1##_2
      |                                       ^~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:18:30: note: in expansion of macro ‘GMOCK_PP_INTERNAL_CAT’
   18 | #define GMOCK_PP_CAT(_1, _2) GMOCK_PP_INTERNAL_CAT(_1, _2)
      |                              ^~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:82:3: note: in expansion of macro ‘GMOCK_PP_CAT’
   82 |   GMOCK_PP_CAT(_Macro, GMOCK_PP_NARG(__VA_ARGS__))(__VA_ARGS__)
      |   ^~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:43:3: note: in expansion of macro ‘GMOCK_PP_VARIADIC_CALL’
   43 |   GMOCK_PP_VARIADIC_CALL(GMOCK_INTERNAL_MOCK_METHOD_ARG_, __VA_ARGS__)
      |   ^~~~~~~~~~~~~~~~~~~~~~
mock_jsondict_mapping.h:9:2: note: in expansion of macro ‘MOCK_METHOD’
    9 |  MOCK_METHOD(void, SetUseLocking, (const bool), (NOEXCEPT));
      |  ^~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:163:43: error: static assertion failed: throw() cannot be recognized as a valid specification modifier.
  159 |       (GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_CONST(_i, _, _elem)) +    \
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  160 |        GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_OVERRIDE(_i, _, _elem)) + \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  161 |        GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_FINAL(_i, _, _elem)) +    \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  162 |        GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_NOEXCEPT(_i, _, _elem)) + \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  163 |        GMOCK_INTERNAL_IS_CALLTYPE(_elem)) == 1,                           \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:163:43: note: in definition of macro ‘GMOCK_INTERNAL_ASSERT_VALID_SPEC_ELEMENT’
  163 |        GMOCK_INTERNAL_IS_CALLTYPE(_elem)) == 1,                           \
      |                                           ^~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:259:3: note: in expansion of macro ‘GMOCK_PP_INTERNAL_CALL_MACRO’
  259 |   GMOCK_PP_INTERNAL_CALL_MACRO(_Macro, _i, _Data, GMOCK_PP_HEAD _Tuple)
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:180:39: note: in expansion of macro ‘GMOCK_PP_INTERNAL_FOR_EACH_IMPL_1’
  180 | #define GMOCK_PP_INTERNAL_CAT(_1, _2) _1##_2
      |                                       ^~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:100:3: note: in expansion of macro ‘GMOCK_PP_FOR_EACH’
  100 |   GMOCK_PP_FOR_EACH(GMOCK_INTERNAL_ASSERT_VALID_SPEC_ELEMENT, ~, _Spec)
      |   ^~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:59:3: note: in expansion of macro ‘GMOCK_INTERNAL_ASSERT_VALID_SPEC’
   59 |   GMOCK_INTERNAL_ASSERT_VALID_SPEC(_Spec)                                     \
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:180:39: note: in expansion of macro ‘GMOCK_INTERNAL_MOCK_METHOD_ARG_4’
  180 | #define GMOCK_PP_INTERNAL_CAT(_1, _2) _1##_2
      |                                       ^~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:18:30: note: in expansion of macro ‘GMOCK_PP_INTERNAL_CAT’
   18 | #define GMOCK_PP_CAT(_1, _2) GMOCK_PP_INTERNAL_CAT(_1, _2)
      |                              ^~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:82:3: note: in expansion of macro ‘GMOCK_PP_CAT’
   82 |   GMOCK_PP_CAT(_Macro, GMOCK_PP_NARG(__VA_ARGS__))(__VA_ARGS__)
      |   ^~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:43:3: note: in expansion of macro ‘GMOCK_PP_VARIADIC_CALL’
   43 |   GMOCK_PP_VARIADIC_CALL(GMOCK_INTERNAL_MOCK_METHOD_ARG_, __VA_ARGS__)
      |   ^~~~~~~~~~~~~~~~~~~~~~
mock_jsondict_mapping.h:10:2: note: in expansion of macro ‘MOCK_METHOD’
   10 |  MOCK_METHOD(bool, AddTag, (const DICT_TAG_TYPE, const CCoreTag &), (NOEXCEPT));
      |  ^~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:163:43: error: static assertion failed: throw() cannot be recognized as a valid specification modifier.
  159 |       (GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_CONST(_i, _, _elem)) +    \
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  160 |        GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_OVERRIDE(_i, _, _elem)) + \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  161 |        GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_FINAL(_i, _, _elem)) +    \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  162 |        GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_NOEXCEPT(_i, _, _elem)) + \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  163 |        GMOCK_INTERNAL_IS_CALLTYPE(_elem)) == 1,                           \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:163:43: note: in definition of macro ‘GMOCK_INTERNAL_ASSERT_VALID_SPEC_ELEMENT’
  163 |        GMOCK_INTERNAL_IS_CALLTYPE(_elem)) == 1,                           \
      |                                           ^~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:259:3: note: in expansion of macro ‘GMOCK_PP_INTERNAL_CALL_MACRO’
  259 |   GMOCK_PP_INTERNAL_CALL_MACRO(_Macro, _i, _Data, GMOCK_PP_HEAD _Tuple)
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:180:39: note: in expansion of macro ‘GMOCK_PP_INTERNAL_FOR_EACH_IMPL_1’
  180 | #define GMOCK_PP_INTERNAL_CAT(_1, _2) _1##_2
      |                                       ^~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:100:3: note: in expansion of macro ‘GMOCK_PP_FOR_EACH’
  100 |   GMOCK_PP_FOR_EACH(GMOCK_INTERNAL_ASSERT_VALID_SPEC_ELEMENT, ~, _Spec)
      |   ^~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:59:3: note: in expansion of macro ‘GMOCK_INTERNAL_ASSERT_VALID_SPEC’
   59 |   GMOCK_INTERNAL_ASSERT_VALID_SPEC(_Spec)                                     \
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:180:39: note: in expansion of macro ‘GMOCK_INTERNAL_MOCK_METHOD_ARG_4’
  180 | #define GMOCK_PP_INTERNAL_CAT(_1, _2) _1##_2
      |                                       ^~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:18:30: note: in expansion of macro ‘GMOCK_PP_INTERNAL_CAT’
   18 | #define GMOCK_PP_CAT(_1, _2) GMOCK_PP_INTERNAL_CAT(_1, _2)
      |                              ^~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:82:3: note: in expansion of macro ‘GMOCK_PP_CAT’
   82 |   GMOCK_PP_CAT(_Macro, GMOCK_PP_NARG(__VA_ARGS__))(__VA_ARGS__)
      |   ^~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:43:3: note: in expansion of macro ‘GMOCK_PP_VARIADIC_CALL’
   43 |   GMOCK_PP_VARIADIC_CALL(GMOCK_INTERNAL_MOCK_METHOD_ARG_, __VA_ARGS__)
      |   ^~~~~~~~~~~~~~~~~~~~~~
mock_jsondict_mapping.h:11:2: note: in expansion of macro ‘MOCK_METHOD’
   11 |  MOCK_METHOD(void, AddJsonToDictTag, (const std::string &, const DICT_TAG_TYPE), (NOEXCEPT));
      |  ^~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:163:43: error: static assertion failed: throw() cannot be recognized as a valid specification modifier.
  159 |       (GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_CONST(_i, _, _elem)) +    \
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  160 |        GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_OVERRIDE(_i, _, _elem)) + \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  161 |        GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_FINAL(_i, _, _elem)) +    \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  162 |        GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_NOEXCEPT(_i, _, _elem)) + \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  163 |        GMOCK_INTERNAL_IS_CALLTYPE(_elem)) == 1,                           \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:163:43: note: in definition of macro ‘GMOCK_INTERNAL_ASSERT_VALID_SPEC_ELEMENT’
  163 |        GMOCK_INTERNAL_IS_CALLTYPE(_elem)) == 1,                           \
      |                                           ^~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:259:3: note: in expansion of macro ‘GMOCK_PP_INTERNAL_CALL_MACRO’
  259 |   GMOCK_PP_INTERNAL_CALL_MACRO(_Macro, _i, _Data, GMOCK_PP_HEAD _Tuple)
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:262:3: note: in expansion of macro ‘GMOCK_PP_INTERNAL_FOR_EACH_IMPL_1’
  262 |   GMOCK_PP_INTERNAL_FOR_EACH_IMPL_1(GMOCK_PP_INC(_i), _Macro, _Data,    \
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:180:39: note: in expansion of macro ‘GMOCK_PP_INTERNAL_FOR_EACH_IMPL_2’
  180 | #define GMOCK_PP_INTERNAL_CAT(_1, _2) _1##_2
      |                                       ^~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:100:3: note: in expansion of macro ‘GMOCK_PP_FOR_EACH’
  100 |   GMOCK_PP_FOR_EACH(GMOCK_INTERNAL_ASSERT_VALID_SPEC_ELEMENT, ~, _Spec)
      |   ^~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:59:3: note: in expansion of macro ‘GMOCK_INTERNAL_ASSERT_VALID_SPEC’
   59 |   GMOCK_INTERNAL_ASSERT_VALID_SPEC(_Spec)                                     \
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:180:39: note: in expansion of macro ‘GMOCK_INTERNAL_MOCK_METHOD_ARG_4’
  180 | #define GMOCK_PP_INTERNAL_CAT(_1, _2) _1##_2
      |                                       ^~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:18:30: note: in expansion of macro ‘GMOCK_PP_INTERNAL_CAT’
   18 | #define GMOCK_PP_CAT(_1, _2) GMOCK_PP_INTERNAL_CAT(_1, _2)
      |                              ^~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:82:3: note: in expansion of macro ‘GMOCK_PP_CAT’
   82 |   GMOCK_PP_CAT(_Macro, GMOCK_PP_NARG(__VA_ARGS__))(__VA_ARGS__)
      |   ^~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:43:3: note: in expansion of macro ‘GMOCK_PP_VARIADIC_CALL’
   43 |   GMOCK_PP_VARIADIC_CALL(GMOCK_INTERNAL_MOCK_METHOD_ARG_, __VA_ARGS__)
      |   ^~~~~~~~~~~~~~~~~~~~~~
mock_jsondict_mapping.h:12:2: note: in expansion of macro ‘MOCK_METHOD’
   12 |  MOCK_METHOD(bool, GetJsonNameByTagId, (const DICT_TAG_TYPE, std::string &), (const, NOEXCEPT));
      |  ^~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:163:43: error: static assertion failed: throw() cannot be recognized as a valid specification modifier.
  159 |       (GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_CONST(_i, _, _elem)) +    \
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  160 |        GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_OVERRIDE(_i, _, _elem)) + \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  161 |        GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_FINAL(_i, _, _elem)) +    \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  162 |        GMOCK_PP_HAS_COMMA(GMOCK_INTERNAL_DETECT_NOEXCEPT(_i, _, _elem)) + \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  163 |        GMOCK_INTERNAL_IS_CALLTYPE(_elem)) == 1,                           \
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:163:43: note: in definition of macro ‘GMOCK_INTERNAL_ASSERT_VALID_SPEC_ELEMENT’
  163 |        GMOCK_INTERNAL_IS_CALLTYPE(_elem)) == 1,                           \
      |                                           ^~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:259:3: note: in expansion of macro ‘GMOCK_PP_INTERNAL_CALL_MACRO’
  259 |   GMOCK_PP_INTERNAL_CALL_MACRO(_Macro, _i, _Data, GMOCK_PP_HEAD _Tuple)
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:262:3: note: in expansion of macro ‘GMOCK_PP_INTERNAL_FOR_EACH_IMPL_1’
  262 |   GMOCK_PP_INTERNAL_FOR_EACH_IMPL_1(GMOCK_PP_INC(_i), _Macro, _Data,    \
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:180:39: note: in expansion of macro ‘GMOCK_PP_INTERNAL_FOR_EACH_IMPL_2’
  180 | #define GMOCK_PP_INTERNAL_CAT(_1, _2) _1##_2
      |                                       ^~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:100:3: note: in expansion of macro ‘GMOCK_PP_FOR_EACH’
  100 |   GMOCK_PP_FOR_EACH(GMOCK_INTERNAL_ASSERT_VALID_SPEC_ELEMENT, ~, _Spec)
      |   ^~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:59:3: note: in expansion of macro ‘GMOCK_INTERNAL_ASSERT_VALID_SPEC’
   59 |   GMOCK_INTERNAL_ASSERT_VALID_SPEC(_Spec)                                     \
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:180:39: note: in expansion of macro ‘GMOCK_INTERNAL_MOCK_METHOD_ARG_4’
  180 | #define GMOCK_PP_INTERNAL_CAT(_1, _2) _1##_2
      |                                       ^~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:18:30: note: in expansion of macro ‘GMOCK_PP_INTERNAL_CAT’
   18 | #define GMOCK_PP_CAT(_1, _2) GMOCK_PP_INTERNAL_CAT(_1, _2)
      |                              ^~~~~~~~~~~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/internal/gmock-pp.h:82:3: note: in expansion of macro ‘GMOCK_PP_CAT’
   82 |   GMOCK_PP_CAT(_Macro, GMOCK_PP_NARG(__VA_ARGS__))(__VA_ARGS__)
      |   ^~~~~~~~~~~~
/Pro/3rdparty/src/googletest/googlemock/include/gmock/gmock-function-mocker.h:43:3: note: in expansion of macro ‘GMOCK_PP_VARIADIC_CALL’
   43 |   GMOCK_PP_VARIADIC_CALL(GMOCK_INTERNAL_MOCK_METHOD_ARG_, __VA_ARGS__)
      |   ^~~~~~~~~~~~~~~~~~~~~~
mock_jsondict_mapping.h:13:2: note: in expansion of macro ‘MOCK_METHOD’
   13 |  MOCK_METHOD(bool, GetTagIdByJsonName, (const std::string &, DICT_TAG_TYPE &), (const, NOEXCEPT));

**Comment by sbenzaquen** [comment]
I'm guessing the NOEXCEPT macro you are passing has `throw()` in it?
That is not a supported argument on the MOCK_METHOD macro.

**Comment by adcicnx** [comment]
Thanks. I wiil check it. It is really strange behavior, because on Windows the build of app is succeeded.

**Comment by derekmauro** [comment]
Dynamic exception specifications were deprecated in C++11. We don't intend to add support for this today.
