### ISSUE TITLE
SetArrayArgument action has incorrect documentation for WillOnce and WillRepeatedly

### ISSUE THREAD

**Issue by kobaj** [google/googletest#3005]
From the issue here
https://github.com/google/googletest/issues/2874

The following documentation needs to be updated (ctrl-f for `.WillOnce(SetArrayArgument` and similar)
https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md

Which has multiple instances of code like
```
  EXPECT_CALL(mutator, Mutate(NotNull(), 5))
      .WillOnce(SetArrayArgument<0>(values, values + 5));
```

Which should be modified, for example
```
  EXPECT_CALL(mutator, Mutate(NotNull(), 5))
      .WillOnce(DoAll(SetArrayArgument<0>(values, values + 5), Return(...));
```

**Comment by asoffer** [comment]
Hi @kobaj. `Return()` is only needed for methods that do not return void. I believe this all works as expected.
https://godbolt.org/z/8TWbz9
