### ISSUE TITLE
undefined symbol: _ZN7testing8internal23MakeAndRegisterTestInfo

### ISSUE THREAD

**Issue by wreck2002** [google/googletest#3013]
When I use gtest, sometimes it give a running error in some machines.
It complains something like follows,

./adecu_hmi: symbol lookup error: ./adecu_hmi: undefined symbol: _ZN7testing8internal23MakeAndRegisterTestInfoEPKcS2_S2_S2_PKvPFvvES6_PNS0_15TestFactoryBaseE

gtest version is 1.7.0
operating system is Ubuntu 16.04.4 LTS
use dynamic library libgtest.so

Thanks for your attention.

**Comment by sbenzaquen** [comment]
On Thu, Sep 17, 2020 at 5:38 AM Bo Chen <notifications@github.com> wrote:

> When I use gtest, sometimes it give a running error in some machines.
> It complains something like follows,
>
> ./adecu_hmi: symbol lookup error: ./adecu_hmi: undefined symbol:
> _ZN7testing8internal23MakeAndRegisterTestInfoEPKcS2_S2_S2_PKvPFvvES6_PNS0_15TestFactoryBaseE
>
Seems like you are not linking the gtest library into your binary, or you
might have a mismatch between headers and precompiled library.

**Comment by wreck2002** [comment]
Thanks for the response, that hint me it is possible that I use different gtest version from the executable binary.

After investigate, I verified this reason.
The library I use is different from the binary want to use.
The libgtest.so the binary want to use 's size is 869,200 Bytes;
The libgtest.so in my computer 's size is 1,085,896 Bytes.
I replace my computer's libgtest.so(1,085,896 Bytes) to libgtest.so(869,200 Bytes), 
and then the executable binary could run successfully.

Then another two problems appear in my mind.
1. Is there any method to found the version of libgtest.so?
2. Why don't the command sudo make install only copy one file (libgtest.so) to /usr/local/lib?
It seems like three files (libgtest.so libgtest.so libgtest.so.1.7 libgtest.so.1.7.0) created at /usr/local/lib better than just one.
