### ISSUE TITLE
Feature request: Use yellow instead of red for tests failing due to EXPECT_*

### ISSUE THREAD

**Issue by denniskb** [google/googletest#3035]
I would prefer if test cases that exclusively fail due to a failed `EXPECT_*(...)` (i.e. not a single `ASSERT_(...)` failed) were highlighted in yellow instead of red.

Is this already expressible using the public API?, i.e. via `ADD_FAILURE`? If not, how would I go about modifying my own fork to achieve this?

Many thanks!

**Comment by derekmauro** [comment]
From GoogleTest's perspective, `EXPECT_*` and `ASSERT_*` are both failures, so we display them in the same way.

For colors, start here https://github.com/google/googletest/blob/fe4d5f10840c5f62b984364a4d41719f1bc079a2/googletest/src/gtest.cc#L3130 and dig your way around from there.
