### ISSUE TITLE
Test Failure on Uncaught Exception

### ISSUE THREAD

**Issue by sclel016** [google/googletest#3048]
Hi,

Default behavior of a testcase seems to be termination on uncaught exception. However this doesn't fail the testcase and also prevents all subsequent tests from running. This can cause unexpected coverage holes in regressions. I understand that I could wrap all my tests with EXPECT_NO_THROW but that seems like it should be unnecessary. An uncaught exception should always be a failure.

Is there a reason why the above is the default behavior?

Stew

**Comment by asoffer** [comment]
Likely the answer to "Why" is that Google does not use exceptions and so this wasn't a particularly important case. I don't see any immediate issues with this (the performance impact of exceptions is ~1% on the happy path, and we don't care much if the test was about to fail anyway). So I suspect this is a change we'd be okay with. That being said, this is not something we, the GoogleTest maintainers, are able to prioritize. If you'd like to send us a PR, we'd be more than happy to discuss there.

**Comment by sclel016** [comment]
I unfortunately don't have time nor the expertise to properly implement this feature. I've put together a work-around by wrapping the suspect code with NO_THROW(). If you don't see this issue being something that the googletest team can prioritize, I completely understand. I'm okay with closing the issue, unless you would like it open for reference purposes.

**Comment by gqqnbig** [comment]
I face a similar issue that somewhere deep in my code or the libraries I used throws C-style literal string. When the error occurs, the test proecess terminates with no conclusion, or in Visual Studio it says "Unknown C++ exception thrown in the test body".
