### ISSUE TITLE
Unresolved external symbol when building gtest

### ISSUE THREAD

**Issue by MrDejan995** [google/googletest#3052]
I'm getting this linker error when building google test 32bit version. I can see that similar issue was open before, so it might be related- https://github.com/google/googletest/issues/304
![image](https://user-images.githubusercontent.com/23005111/95861681-18440880-0d62-11eb-940b-4cef6d1b4b38.png)

**Comment by derekmauro** [comment]
Please provide **complete** instructions on how to reproduce this issue.

**Comment by MrDejan995** [comment]
After downloading project, I went to download folder
mkdir build
cd build
cmake .. -G "Visual Studio 16 2019" -A Win32 -Dgtest_force_shared_crt=ON
cmake --build .
cmake --build . --config Release
After that I intergrated it in my project, and when i tried building my project, i got that error (as you can see im using Visual Studio compiler and Windows 32bit build)

**Comment by derekmauro** [comment]
Yes, we need to see exactly what you did, or at least a minimal reproduction.

> After that I intergrated it in my project, and when i tried building my project, i got that error

Without knowing exactly what you did in this step, we can't help.

**Comment by MrDejan995** [comment]
Well in my project I included property file that contains path to the .lib and .pdb files that I have built with CMake. After that I included gtest.h in my project and that's basically it. One note only- it works with 64bit project nicely, it just fails with 32bit project.

**Comment by derekmauro** [comment]
Sorry, we are not able to reproduce this problem with the information provided. If you can provide us with more detailed information, for example, a GitHub repo that we can pull and run, feel free to reopen.
