### ISSUE TITLE
Regression: operator<< defined outside the namespace is not considered

### ISSUE THREAD

**Issue by ReneOschmann** [google/googletest#3066]
Hi, 

since https://github.com/google/googletest/commit/0555b0eacbc56df1fd762c6aa87bb84be9e4ce7e the following code does not compile anymore:

```C++
#include "gtest.h"
#include <ostream>

namespace NS {
class MyClass{};
} // namespace NS

std::ostream& operator<<(std::ostream& os, const NS::MyClass&)
{
    return os;
}

TEST(MyTest, test) {
    NS::MyClass object;
    ASSERT_TRUE(true) << object;
}
```

As workaround you can define the streaming operator in the same namespace as `MyClass`

```C++
#include "gtest.h"
#include <ostream>

namespace NS {
class MyClass{};
} // namespace NS

namespace NS {
std::ostream& operator<<(std::ostream& os, const MyClass&)
{
    return os;
}
} // namespace NS

TEST(MyTest, test) {
    NS::MyClass object;
    ASSERT_TRUE(true) << object;
}
```

Kind regards
René

**Comment by ReneOschmann** [comment]
This issue does not happen with clang 10

**Comment by sbenzaquen** [comment]
This is WAI.
`operator<<` is meant to be found by ADL, just like other overloaded operators.
To do that it has to be in one of the associated namespaces of the types involved in the operation.
Putting the overload in the namespace of the object is not a workaround. It is the way it is supposed to be done.
See https://en.cppreference.com/w/cpp/language/adl

If it worked for you in the past it was by chance and was subject to breaking with subtle things like which `#include`s you had and their order of inclusion.
The PR linked makes the failure more deterministic.

**Comment by ReneOschmann** [comment]
It gets ugly if typedefs are involved as the workaround has to point to the canonical type:

```C++
#include "gtest.h"
#include <ostream>

namespace NS {
class MyClass{};
template<size_t size>
class SizedClass{};
} // namespace NS

namespace NS2 {
typedef NS::SizedClass<1> SomeClass;
} // namespace NS2

namespace NS {
std::ostream& operator<<(std::ostream& os, const SizedClass<1>&) // pretty ugly workaround for NS2::SomeClass
{
    return os;
}
} // namespace NS

TEST(MyTest, test) {
    NS2::SomeClass object;
    ASSERT_TRUE(true) << object;
}
```

**Comment by ReneOschmann** [comment]
NVM I can do:
```C++
namespace NS {
std::ostream& operator<<(std::ostream& os, const NS2::SomeClass&) // pretty ugly workaround for NS2::SomeClass
{
    return os;
}
} // namespace NS
```

**Comment by sbenzaquen** [comment]
`NS2::SomeClass` is not a type, it is just an alias.
As such, it should not be extending the API of the type. It does not own the type.
Again, having to put it in the `NS` namespace is not an "ugly workaround". It is WAI in C++.
You are extending the API of `NS::SizedClass` and the place to do it is in its namespace (and the same file where `SizedClass` is declared).

**Comment by ReneOschmann** [comment]
Thanks again :) I close the issue
