### ISSUE TITLE
More Abseil dependency questions.

### ISSUE THREAD

**Issue by fsecilia** [google/googletest#3075]
Heya, folks!

Will the Abseil dependency be transparent, considering I have it installed? Specifically, can I still use the system standard library in client code when under test?

Will the dep interfere with cmake builds?

Thanks!

**Comment by derekmauro** [comment]
While using Abseil as a dependency is still on our list of things we'd like to do, we haven't started working on it yet, so this is all still to be determined.

We strongly recommend you compile all C++ code from source. There is no reason you couldn't use the standard system library, but your code would need to be built with the same ABI-affecting compile options as the system library.
