### ISSUE TITLE
No known features for CXX compiler

### ISSUE THREAD

**Issue by GABS9718** [google/googletest#3078]
Hi,
I'm trying to build my project but I'm getting this error message:

**CMake Error at build/googletest-src/googletest/cmake/internal_utils.cmake:193 (target_compile_features):
  target_compile_features no known features for CXX compiler

  "GNU"

  version 8.3.1.**

I'm working using zephyr environment, where my CXX compiler version is 3.8.1. For getting this I followed the tutorial in the README from googletest/googletest repository, where basically I just created a new CMakeLists.txt.in file and added the rest of the code said there in my main CMakeLists.txt

Someone can help me?

**Comment by derekmauro** [comment]
We have no familiarity with the zephyr environment. You may want to ask for help on a zephyr forum.

**Comment by dschwen** [comment]
This is not specific to "zephyr". I get a similar error on mac (with `CXX=$CLANGXX CC=$CLANG cmake ..`, where clang is provided vis conda)

```
CMake Error at googletest/cmake/internal_utils.cmake:193 (target_compile_features):
  target_compile_features no known features for CXX compiler

  "Clang"

  version 9.0.1.
Call Stack (most recent call first):
  googletest/cmake/internal_utils.cmake:206 (cxx_library_with_type)
  googletest/CMakeLists.txt:128 (cxx_library)
```

**Comment by dschwen** [comment]
```
cmake .. -DCMAKE_POLICY_DEFAULT_CMP0025=NEW
```

fixed it for me!
