### ISSUE TITLE
undefined references to testing::Matcher<std::string_view>::Matcher(std::string_view)

### ISSUE THREAD

**Issue by smr99** [google/googletest#3081]
I built a zip export of googletest from 2020-10-18, and again from today (2020-10-25) on Debian linux ("unstable").  The build uses cmake.  The test code below, when built and linked using "g++ -std=c++20 test.cpp -lgmock_main -lgmock -lgtest -pthread", results in undefined reference:

> undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(std::basic_string_view<char, std::char_traits<char> >)'

The same code and build line works when using googletest release 1.10.0.

test.cpp
```
#include <gmock/gmock.h>
#include <gtest/gtest.h>

#include <string_view>

class MyMock {
public:
    MOCK_METHOD(void, testPrint, (std::string_view));
};

TEST(Test, test)
{
    constexpr std::string_view param{"test"};
    MyMock mock;
    EXPECT_CALL(mock, testPrint(param))
        .Times(1);
}
```

Original bug report from Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=972627

**Comment by sbenzaquen** [comment]
You have to build gtest with at least C++17 to get the C++17 related matchers/printers.
You are building the test code with C++20, but the library might have been built with different options.
You should always build everything with the same compiler options.

**Comment by strager** [comment]
> You have to build gtest with at least C++17 to get the C++17 related matchers/printers.
> You are building the test code with C++20, but the library might have been built with different options.
> You should always build everything with the same compiler options.

I agree that, in a perfect world, everything builds with the same compiler options.

Question 1: Does googletest support building itself as C++14  (`-std=c++14`, [currently active](https://github.com/google/googletest/blob/d9251171f5a42eaf993395e7ef127546af5814b0/googletest/cmake/internal_utils.cmake#L200)) but building client code as C++17 (`-std=c++17`)?

Question 2:Does googletest support building itself as C++17  (`-std=c++17`) but building client code as C++14 (`-std=c++14`)?

Context: Homebrew (package manager) developers are discussing how googletest should be configured in their repository. I assume they want many different googletest clients (some C++11, some C++17, some C++20) to share the same version of googletest. https://github.com/Homebrew/homebrew-core/pull/122027
