### ISSUE TITLE
can gtest use a test file to run like "-e testFile" in AndroidJunitRunner

### ISSUE THREAD

**Issue by xty-20200627** [google/googletest#3082]

**Comment by xty-20200627** [comment]
can gtest use a file which includes some testcases to run?

**Comment by derekmauro** [comment]
No. There is a flag you can use: https://github.com/google/googletest/blob/620659ed92829a88ee34134c782bf5b5aa5a0a0c/googletest/docs/advanced.md#running-a-subset-of-the-tests
