### ISSUE TITLE
Describe how to trigger test failures when there are sanitizer errors

### ISSUE THREAD

**Issue by sfc-gh-ebrossard** [google/googletest#3083]
It took a bit of digging, but I found the magic hooks for UBSAN/ASAN/TSAN errors and was successfully able to instrument them to trigger individual test failures, as opposed just to crashing at the end of executing all tests. It would be nice to have this as part of the googletest documentation in case it's useful to other projects as well:

```
extern "C" {
void __ubsan_on_report() {
  FAIL() << "Encountered an undefined behavior sanitizer error";
}
void __asan_on_error() {
  FAIL() << "Encountered an address sanitizer error";
}
void __tsan_on_report() {
  FAIL() << "Encountered a thread sanitizer error";
}
}  // extern "C"
```

**Comment by asoffer** [comment]
This looks really useful, and something you're now familiar with. None of us on the GoogleTest team have done this before. Would you mind sending a PR? Thanks!

**Comment by sfc-gh-ebrossard** [comment]
Sure, created https://github.com/google/googletest/pull/3086.

**Comment by axxel** [comment]
Found this in the official doc, very useful info. Thanks. Question: any chance/interest in having some kind of out-of-the-box support for this from inside `gtest/gtest.h`? I have whole bunch of individual cpp files with tests and would have to 'manually' provide those functions to all of them if I'm not mistaken.
