### ISSUE TITLE
error: use of undeclared identifier 'FormatIntWidthN'

### ISSUE THREAD

**Issue by seanngpack** [google/googletest#3087]
System: macOS Catalina, compiler: g++, googletest: release 1.10

Is anyone else having compiling issues with the latest release? I was previously using release 1.8.1 as a submodule, but when updating to the latest this issue happens:

```
/Users/project/extern/googletest/googletest/src/gtest.cc:2130:10: error: use of undeclared identifier 'FormatIntWidthN'
  return FormatIntWidthN(value, 2);
         ^
/Users/project/extern/googletest/googletest/src/gtest.cc:2134:21: error: out-of-line definition of 'FormatIntWidthN' does not match any declaration in 'testing::internal::String'
std::string String::FormatIntWidthN(int value, int width) {
                    ^~~~~~~~~~~~~~~
/Users/project/extern/googletest/googletest/src/gtest.cc:4102:15: error: call to non-static member function without an object argument
      String::FormatIntWidthN(static_cast<int>(ms % 1000), 3);
```

The errors immediately occur upon the ``add_subdirectory()`` command.

```
if (BUILD_TESTS)
    include(CTest)
    enable_testing()
    add_subdirectory(${PROJECT_SOURCE_DIR}/extern/googletest) // issue happens here
#    add_subdirectory(test)
endif ()

```

edit: I can get my googletest working by declaring and defining ``FormatIntWidthN()`` locally in the gtest.cc file. Not sure why the method is not implementing the signature declared in ``gtest-string.h``

**Comment by asoffer** [comment]
Could you provide full reproduction instructions? Given the error message I suspect you're mixing an old header (that doesn't have this method marked as static) with a newer release. Mixing versions is a common way to see this sort of problem and something Googletest does not support.

**Comment by seanngpack** [comment]
Thanks for the response! I think you're right with the old header, after reinstalling my project and adding the submodule again, the issue went away
