### ISSUE TITLE
TSan reports a data race for VerifyAndClearExpectations vs. UntypedInvokeWith

### ISSUE THREAD

**Issue by phu-cinemo** [google/googletest#3093]
ThreadSanitizer reports a data race on `untyped_expectations_` with v1.10.0.

A call to `VerifyAndClearExpectations()` writes `untyped_expectations_`
https://github.com/google/googletest/blob/3005672db1d05f2378f642b61faa96f85498befe/googlemock/src/gmock-spec-builders.cc#L561

But a concurrent call to the mock would issue an unprotected access here:
https://github.com/google/googletest/blob/3005672db1d05f2378f642b61faa96f85498befe/googlemock/src/gmock-spec-builders.cc#L380

I couldn't find anything in the documentation that prohibits calling `VerifyAndClearExpectations()` on an active mock object.

**Comment by asoffer** [comment]
It's not spelled out explicitly, but this is probably the best reference:
https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md#using-gmock-and-threads-usingthreads

We're working on updating a lot of this documentation and we'll make sure to spell this out explicitly.

**Comment by derekmauro** [comment]
We believe this is working as intended.
