### ISSUE TITLE
can't install googletest on linux

### ISSUE THREAD

**Issue by ertosns** [google/googletest#3112]
i have tested different methods to install googletest, but i fail to use it's API
i have this init file.
```
#include "gtest/gtest.h"

TEST( ExampleTest, First ) {
  EXPECT_TRUE(  true );
}

int main(int argc, char **argv) {
  ::testing::InitGoogleTest(&argc, argv); 
  return RUN_ALL_TESTS();
}
```

1) through apt-get install google-mock, and build it under /usr/src/googletest, then coppied lib/* to /usr/local/lib, and googlemock/include/gmock, and googletest/include/gtest under /usr/local/include.

g++ -lgmock init.cpp 
/usr/bin/ld: /tmp/cctbY6ZO.o: in function `main':
init.cpp:(.text+0x22): undefined reference to `testing::InitGoogleMock(int*, char**)'
/usr/bin/ld: /tmp/cctbY6ZO.o: in function `RUN_ALL_TESTS()':
init.cpp:(.text._Z13RUN_ALL_TESTSv[_Z13RUN_ALL_TESTSv]+0x9): undefined reference to `testing::UnitTest::GetInstance()'
/usr/bin/ld: init.cpp:(.text._Z13RUN_ALL_TESTSv[_Z13RUN_ALL_TESTSv]+0x11): undefined reference to `testing::UnitTest::Run()'
collect2: error: ld returned 1 exit status

2) i used this script https://gist.github.com/butuzov/e7df782c31171f9563057871d0ae444a
clang++ -lgtest test.cpp -o  ./test -std=c++14 && ./test
/usr/bin/ld: /tmp/test-f61c8f.o: in function `ExampleTest_First_Test::TestBody()':
test.cpp:(.text+0x5f): undefined reference to `testing::Message::Message()'
/usr/bin/ld: test.cpp:(.text+0x81): undefined reference to `testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)'
/usr/bin/ld: test.cpp:(.text+0xaa): undefined reference to `testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)'
/usr/bin/ld: test.cpp:(.text+0xbc): undefined reference to `testing::internal::AssertHelper::operator=(testing::Message const&) const'
/usr/bin/ld: test.cpp:(.text+0xca): undefined reference to `testing::internal::AssertHelper::~AssertHelper()'
/usr/bin/ld: test.cpp:(.text+0x109): undefined reference to `testing::internal::AssertHelper::~AssertHelper()'
/usr/bin/ld: /tmp/test-f61c8f.o: in function `main':
test.cpp:(.text+0x16f): undefined reference to `testing::InitGoogleTest(int*, char**)'
/usr/bin/ld: /tmp/test-f61c8f.o: in function `__cxx_global_var_init.1':
test.cpp:(.text.startup+0x8a): undefined reference to `testing::internal::GetTestTypeId()'
/usr/bin/ld: test.cpp:(.text.startup+0x138): undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
/usr/bin/ld: /tmp/test-f61c8f.o: in function `testing::internal::SuiteApiResolver<testing::Test>::GetSetUpCaseOrSuite(char const*, int)':
test.cpp:(.text._ZN7testing8internal16SuiteApiResolverINS_4TestEE19GetSetUpCaseOrSuiteEPKci[_ZN7testing8internal16SuiteApiResolverINS_4TestEE19GetSetUpCaseOrSuiteEPKci]+0x6a): undefined reference to `testing::internal::IsTrue(bool)'
/usr/bin/ld: test.cpp:(.text._ZN7testing8internal16SuiteApiResolverINS_4TestEE19GetSetUpCaseOrSuiteEPKci[_ZN7testing8internal16SuiteApiResolverINS_4TestEE19GetSetUpCaseOrSuiteEPKci]+0x9b): undefined reference to `testing::internal::GTestLog::GTestLog(testing::internal::GTestLogSeverity, char const*, int)'
/usr/bin/ld: test.cpp:(.text._ZN7testing8internal16SuiteApiResolverINS_4TestEE19GetSetUpCaseOrSuiteEPKci[_ZN7testing8internal16SuiteApiResolverINS_4TestEE19GetSetUpCaseOrSuiteEPKci]+0x122): undefined reference to `testing::internal::GTestLog::~GTestLog()'
/usr/bin/ld: test.cpp:(.text._ZN7testing8internal16SuiteApiResolverINS_4TestEE19GetSetUpCaseOrSuiteEPKci[_ZN7testing8internal16SuiteApiResolverINS_4TestEE19GetSetUpCaseOrSuiteEPKci]+0x137): undefined reference to `testing::internal::GTestLog::~GTestLog()'
/usr/bin/ld: /tmp/test-f61c8f.o: in function `testing::internal::SuiteApiResolver<testing::Test>::GetTearDownCaseOrSuite(char const*, int)':
test.cpp:(.text._ZN7testing8internal16SuiteApiResolverINS_4TestEE22GetTearDownCaseOrSuiteEPKci[_ZN7testing8internal16SuiteApiResolverINS_4TestEE22GetTearDownCaseOrSuiteEPKci]+0x6a): undefined reference to `testing::internal::IsTrue(bool)'
/usr/bin/ld: test.cpp:(.text._ZN7testing8internal16SuiteApiResolverINS_4TestEE22GetTearDownCaseOrSuiteEPKci[_ZN7testing8internal16SuiteApiResolverINS_4TestEE22GetTearDownCaseOrSuiteEPKci]+0x9b): undefined reference to `testing::internal::GTestLog::GTestLog(testing::internal::GTestLogSeverity, char const*, int)'
/usr/bin/ld: test.cpp:(.text._ZN7testing8internal16SuiteApiResolverINS_4TestEE22GetTearDownCaseOrSuiteEPKci[_ZN7testing8internal16SuiteApiResolverINS_4TestEE22GetTearDownCaseOrSuiteEPKci]+0x122): undefined reference to `testing::internal::GTestLog::~GTestLog()'
/usr/bin/ld: test.cpp:(.text._ZN7testing8internal16SuiteApiResolverINS_4TestEE22GetTearDownCaseOrSuiteEPKci[_ZN7testing8internal16SuiteApiResolverINS_4TestEE22GetTearDownCaseOrSuiteEPKci]+0x137): undefined reference to `testing::internal::GTestLog::~GTestLog()'
/usr/bin/ld: /tmp/test-f61c8f.o: in function `RUN_ALL_TESTS()':
test.cpp:(.text._Z13RUN_ALL_TESTSv[_Z13RUN_ALL_TESTSv]+0x5): undefined reference to `testing::UnitTest::GetInstance()'
/usr/bin/ld: test.cpp:(.text._Z13RUN_ALL_TESTSv[_Z13RUN_ALL_TESTSv]+0xd): undefined reference to `testing::UnitTest::Run()'
/usr/bin/ld: /tmp/test-f61c8f.o: in function `ExampleTest_First_Test::~ExampleTest_First_Test()':
test.cpp:(.text._ZN22ExampleTest_First_TestD2Ev[_ZN22ExampleTest_First_TestD2Ev]+0x14): undefined reference to `testing::Test::~Test()'
/usr/bin/ld: /tmp/test-f61c8f.o: in function `ExampleTest_First_Test::ExampleTest_First_Test()':
test.cpp:(.text._ZN22ExampleTest_First_TestC2Ev[_ZN22ExampleTest_First_TestC2Ev]+0x1b): undefined reference to `testing::Test::Test()'
/usr/bin/ld: /tmp/test-f61c8f.o:(.rodata+0x20): undefined reference to `testing::Test::SetUp()'
/usr/bin/ld: /tmp/test-f61c8f.o:(.rodata+0x28): undefined reference to `testing::Test::TearDown()'
/usr/bin/ld: /tmp/test-f61c8f.o:(.rodata+0x70): undefined reference to `typeinfo for testing::Test'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

i have tested varies methods, but nothing works, any idea which  it doesn't work?!

**Comment by hyukmyeong** [comment]
I just tested and it seems below worksplease try this

```cpp
g++ main.cpp -lgtest -lpthread
g++ main.cpp -std=c++11 -lgtest -lpthread
```
and you can follow below guide as well
https://github.com/google/googletest/blob/master/googletest/README.md

**Comment by ertosns** [comment]
thanks, worked
