### ISSUE TITLE
Cannot find gmock for windows x86 build

### ISSUE THREAD

**Issue by synacker** [google/googletest#3117]
I use conan recipe for building gtest and gmock lib from [here](https://github.com/conan-io/conan-center-index/tree/master/recipes/gtest/all)

Recipe is the same for both 1.8.1 and 1.10.0 versions.
1.8.1 compiled fine, but, 1.10.0 version is not working, because when I tried to compile my project on x86 windows platform with gtest, I got next error:
```
CMake Error at CMakeLists.txt:24 (find_package):
  By not providing "FindGMock.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "GMock", but
  CMake did not find one.

  Could not find a package configuration file provided by "GMock" with any of
  the following names:

    GMockConfig.cmake
    gmock-config.cmake

  Add the installation prefix of "GMock" to CMAKE_PREFIX_PATH or set
  "GMock_DIR" to a directory containing one of the above files.  If "GMock"
  provides a separate development package or SDK, be sure it has been
  installed.
```

What happen with cmake configuration in 1.10 version and why I cannot find gmock?

**Comment by derekmauro** [comment]
I don't think we provide this file. Are you sure you weren't getting it from some other dependency?

**Comment by synacker** [comment]
> I don't think we provide this file. Are you sure you weren't getting it from some other dependency?

Yes, I'm sure, and this file not in gtest repo, this file located in cmake modules. But, the focus of issue in version regression. The 1.8.1 building successfully, but 1.10 is not. The version of cmake is equal in both cases.

**Comment by ccvca** [comment]
gmock is part of gtest:

```
# NO_CMAKE_SYSTEM_PACKAGE_REGISTRY ensures, that the outdated findGTest of cmake is not used
find_package(GTest REQUIRED NO_CMAKE_SYSTEM_PACKAGE_REGISTRY)
target_link_libraries(Test_Target TestLib GTest::gtest_main GTest::gmock)
```

Possible targets of GTestTargets.cmake: `GTest::gtest GTest::gtest_main GTest::gmock GTest::gmock_main`

**Comment by synacker** [comment]
@ccvca yes, I used incorrect names. Now my issue is resloved, thank you!
