### ISSUE TITLE
how to run tests in testcase one by one ?

### ISSUE THREAD

**Issue by tika64208** [google/googletest#3120]
I have three test 
test_f(A a),test_f(A b),test_f(A c),

how can I configure to run these test in order of :
a.setup()-> a -> a.teardown() ->b.setup()-> b -> b.teardown() ->c.setup()-> c -> c.teardown() ?

**Comment by asoffer** [comment]
GoogleTest does not support or guarantee any particular test ordering. Tests are not intended to be interdependent. Any state needed to be set up for a particular test must be initialized in that test's SetUp (or constructor or body of the test itself).
