### ISSUE TITLE
When it will be new gtest release?

### ISSUE THREAD

**Issue by apivovarov** [google/googletest#3124]
We want to use new feature to check the exception message #2904. It was merged to master on Aug 23, 2020.  But currently this code is not included into any existing releases / tags.
Last release was more than a year ago. Oct 3, 2019
```
//   EXPECT_THAT(
//       []() { throw std::runtime_error("message"); },
//       ThrowsMessage<std::runtime_error>(HasSubstr("message")));
```

**Comment by friendlyanon** [comment]
Quote from the README:  
> Post 1.10.x googletest will follow Abseil Live at Head philosophy

You should pull directly from `master` and not from a version tag.

**Comment by Ozaq** [comment]
From: https://abseil.io/about/philosophy#if-you-choose-to-not-live-at-head
> We will periodically mark a tag as “supported” and branch it — if we discover security issues or major performance problems, we’ll update those branches. Our expectation is to do this every 6 months and support those branches for 2 years.

So my expectation is that at least some known good tags are published, and the laste one was the 1.10 release. Or if you plan to not follow the abseil policy in that regard please state so.

**Comment by derekmauro** [comment]
Although we in general follow Abseil's Live-at-Head philosophy, we haven't looked into doing an LTS release yet. Thank you for raising this, we need to clarify the policy. As far as a known-good tag goes, we don't really have such a concept - we simply try to keep all commits in a working state.

**Comment by derekmauro** [comment]
> You should pull directly from master and not from a version tag

This is NOT what we recommend. See https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#what-is-live-at-head-and-how-do-i-do-it
