### ISSUE TITLE
Provide ALIAS targets to unify usage

### ISSUE THREAD

**Issue by friendlyanon** [google/googletest#3125]
If `googletest` is made part of the dependent's build tree (via `FetchContent`), then usage is different compared to using it from an install location (via `find_package`).

Ever since `FetchContent` has been introduced, the example has been using `googletest`. See [here](https://cmake.org/cmake/help/v3.11/module/FetchContent.html).

Usage differences in code:
```cmake
# make googletest part of hte build tree
include(FetchContent)
FetchContent_Declare(googletest
        GIT_REPOSITORY https://github.com/google/googletest.git
        GIT_TAG master)
FetchContent_MakeAvailable(googletest)

# no ALIAS target, must use non-namespaced target instead
target_link_libraries(my_target PRIVATE gtest_main)

# ----

# use googletest from an install location
find_package(GTest REQUIRED CONFIG)

# the install(EXPORT) command namespaces the targets
target_link_libraries(my_target PRIVATE GTest::gtest_main)
```

I see from another issue (https://github.com/google/googletest/issues/3040#issuecomment-717300633), that due to CMake 3.19 deprecating `<2.8.12` there are also plans to set that as the minimum version and conveniently 2.8.12 is also the version that introduced the `ALIAS` form for `add_library`.

**Comment by asoffer** [comment]
We use Bazel almost exclusively internally, so most of the GoogleTest team is relatively unfamiliar with CMake. This seems like a reasonable request, but not one we are likely to prioritize. Would you be willing to send a PR suggesting these changes? Thanks!

**Comment by AlexanderStein** [comment]
Isn't this the same issue as #2429?
