### ISSUE TITLE
How to record how many times is the mocked method invoked?

### ISSUE THREAD

**Issue by wanghaiqiangk** [google/googletest#3135]
Basically, I want a counter to increment every time the mocked method is invoked. How can I do that?
```c++
// Define a mock method
class
{
  MOCK_METHOD(Return_t, DoWork, (T1, T2), (override));
}

// A test suit
TEST ()
{
  int cnt = 0;
  EXPECT_CALL(mock_object, DoWork(_,_))
    .WillRepeatedly(Action(cnt++));
}
```

**Comment by sbenzaquen** [comment]
On Mon, Nov 30, 2020 at 6:02 AM wanghaiqiangk <notifications@github.com>
wrote:

> Basically, I want a counter to increment every time the mocked method is
> invoked. How can I do that?
>
If the stock actions don't do what you want, just pass a lambda.
Eg:

EXPECT_CALL(mock_object, DoWork(_,_))
    .WillRepeatedly([&cnt] { ++cnt; });

// Define a mock methodclass

**Comment by wanghaiqiangk** [comment]
> EXPECT_CALL(mock_object, DoWork(_,_)) .WillRepeatedly([&cnt] { ++cnt; });

Thanks for your reply. I tried using lambda but ended up with this error:
```
/home/wang/workspace/gtest-learn/test.cpp: In member function ‘virtual void FooTest_Counter_Test::TestBody()’:
/home/wang/workspace/gtest-learn/test.cpp:18:39: error: no matching function for call to ‘testing::internal::TypedExpectation<bool(int)>::WillRepeatedly(FooTest_Counter_Test::TestBody()::<lambda()>)’
         .WillRepeatedly([&cnt]{++cnt;});
                                       ^
In file included from /home/wang/workspace/repos/gtest/gtest-1.10.0/include/gmock/gmock-generated-function-mockers.h:47:0,
                 from /home/wang/workspace/repos/gtest/gtest-1.10.0/include/gmock/gmock-function-mocker.h:39,
                 from /home/wang/workspace/repos/gtest/gtest-1.10.0/include/gmock/gmock.h:61,
                 from /home/wang/workspace/gtest-learn/test.cpp:1:
/home/wang/workspace/repos/gtest/gtest-1.10.0/include/gmock/gmock-spec-builders.h:1018:21: note: candidate: testing::internal::TypedExpectation<F>& testing::internal::TypedExpectation<F>::WillRepeatedly(const testing::Action<F>&) [with F = bool(int)]
   TypedExpectation& WillRepeatedly(const Action<F>& action) {
                     ^~~~~~~~~~~~~~
/home/wang/workspace/repos/gtest/gtest-1.10.0/include/gmock/gmock-spec-builders.h:1018:21: note:   no known conversion for argument 1 from ‘FooTest_Counter_Test::TestBody()::<lambda()>’ to ‘const testing::Action<bool(int)>&’
```

**Comment by sbenzaquen** [comment]
On Mon, Nov 30, 2020 at 10:16 AM wanghaiqiangk <notifications@github.com>
wrote:

> EXPECT_CALL(mock_object, DoWork(*,*)) .WillRepeatedly([&cnt] { ++cnt; });
>
> Thanks for your reply. I tried using lambda but ended up with this error:
>
> /home/wang/workspace/gtest-learn/test.cpp: In member function ‘virtual void FooTest_Counter_Test::TestBody()’:
>
> /home/wang/workspace/gtest-learn/test.cpp:18:39: error: no matching function for call to ‘testing::internal::TypedExpectation<bool(int)>::WillRepeatedly(FooTest_Counter_Test::TestBody()::<lambda()>)’
>
>          .WillRepeatedly([&cnt]{++cnt;});
>
>
You have to use one that matches the signature.
According to the error, the signature is bool(int), so you need one that
takes an int argument and returns a bool.

**Comment by wanghaiqiangk** [comment]
OK. After providing the same signature as the DoWork function, the compiler passed.

I can use `InvokeWithoutArgs` to by pass the requirement for providing arguments, but a same return type still must be provided.

I'm thinking that whether there is a way to simplify this. If not, it's fine.

A final testing code:
```c++
#include <gmock/gmock.h>
#include <gtest/gtest.h>

using ::testing::_;
using ::testing::InvokeWithoutArgs;

class FooMock
{
public:
    MOCK_METHOD(bool, FooMethod, (int));
};

TEST(FooTest, Counter)
{
    FooMock foomock;
    int cnt = 0;
    EXPECT_CALL(foomock, FooMethod(_))
        .WillRepeatedly(InvokeWithoutArgs([&cnt]{++cnt;return true;}));
    foomock.FooMethod(10);
    foomock.FooMethod(20);

    EXPECT_EQ(cnt, 1);
}

int main(int argc, char *argv[])
{
    testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
```

**Comment by sbenzaquen** [comment]
On Mon, Nov 30, 2020 at 10:18 PM wanghaiqiangk <notifications@github.com>
wrote:

> OK. After providing the same signature as the DoWork function, the
> compiler passed.
>
> I can use InvokeWithoutArgs to by pass the requirement for providing
> arguments, but a same return type still must be provided.
>
> I'm thinking that whether there is a way to simplify this. If not, it's
> fine.
>
This part is required because the return value of the lambda is what the
mock method will return. The framework can't return a value that it doesn't
have.

> A final testing code:
>
> #include <gmock/gmock.h>
> #include <gtest/gtest.h>
> using ::testing::_;using ::testing::InvokeWithoutArgs;
> class FooMock
> {public:
>     MOCK_METHOD(bool, FooMethod, (int));
> };
> TEST(FooTest, Counter)
> {
>     FooMock foomock;
>     int cnt = 0;
>     EXPECT_CALL(foomock, FooMethod(_))
>         .WillRepeatedly(InvokeWithoutArgs([&cnt]{++cnt;return true;}));
>
>
Two minor suggestions:
 - If you don't care about any of the arguments in the matcher part, you
can just drop them all and it implicitly matches them all with `_`.
 - If you don't care about any of the arguments in the action part, you can
use a no-arg callable and the framework will do the invoke-without-args
automatically.
Eg

>     EXPECT_CALL(foomock, FooMethod)
>         .WillRepeatedly([&cnt]{++cnt;return true;});
>
>  (that is, assuming you have a googletest version current enough. These
are relatively new features)

**Comment by wanghaiqiangk** [comment]
> This part is required because the return value of the lambda is what the mock method will return. The framework can't return a value that it doesn't have.

I guess it is. So in my production code, I remove `Return()` action and instead directly use the returned value from lambda.

> - If you don't care about any of the arguments in the matcher part, you can just drop them all and it implicitly matches them all with `_`.

Yes. I am aware of that actually. This is mentioned in docs as long as the method is not overloaded.

> - If you don't care about any of the arguments in the action part, you can use a no-arg callable and the framework will do the invoke-without-args automatically.

This is new to me. I thought I had to call `InvokeWithoutArgs`. With this feature, the code becomes a bit simple.

Thanks so much.
