### ISSUE TITLE
I'm a newbie can anyone give a brief explanation about this . I'll be grateful thanks :)

### ISSUE THREAD

**Issue by suryanshgupta04** [google/googletest#3142]
https://www.github.com/google/googletest/tree/master/

**Comment by MrScottAtt** [comment]
@suryanshgupta04   Issues are normally filed to request some sort of _specific_ change to the code or documentation:  report a _specific_ bug, ask for a _specific_ software or documentation enhancement, etc.  
I suggest using a Web browser to search for "google test tutorial" or similar.
