### ISSUE TITLE
cgroups and eBPF

### ISSUE THREAD

**Issue by chadbrewbaker** [google/googletest#3168]
In porting coreutils to Rust I hit the wall with a lot of things we take for granted  with libc/libstdc++, and some bizarre issues between Rust standard library system call differences in Linux and xnu. Then there was the AWS outage a few days ago because they didn't test thread counts which went past ulimits as the linear or accidentally quadratic number of threads blew past ulimits when they added capacity.  These type of tests require cgroup test runners, and possibly some eBPF expectations.

Linux containers are just cgroups and namespaces https://jvns.ca/blog/2016/10/10/what-even-is-a-container/. Using something like docker just to get test isolation or simulate a network connections between two machines is crazy when this could be a few lines of google test runner setup.  The lack of operating system call tracing is also a pain point - we should be able to write expectations about OS calls.

Does google test support cgroup runners or OS call expectations? If not what would be a good API so I could submit a PR to add either.

**Comment by chadbrewbaker** [comment]
Secondary pain point - distributed ulimits. How does Borg do it? I don't want Kubernetes hell when resource limiting jobs across kernels. Did GNU Hurd or Plan9 support this?  My minds eye has a datacenter availability zone Linux running with each machine as a device which it submits jobs to - then normal Linux on each box.

**Comment by derekmauro** [comment]
GoogleTest is OS agnostic.  If you want to test system calls using GoogleTest, you can use a method like https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md#mocking-free-functions. I suspect the answer to all of your questions is just some variant on dependency injection.
