### ISSUE TITLE
VC++ compilation time improvement for unit tests using googletest

### ISSUE THREAD

**Issue by mihaimaris** [google/googletest#3171]
Dear googletest team, 
I am working on a large project where googletest is used and the compilation time witt VC++ is really slow. As far as I have read from other threads, this has probably to do with the macros and the templates from the googletest framework. Is there a way to improve the compilation time? The version that we use is v1.8.0.
Thank you in advance for your time.

**Comment by derekmauro** [comment]
Standard solutions like build caching or remote builds may help, but you would have to set those up. We can't help you with that.
