### ISSUE TITLE
Pre-compiled `gtest_main` prints path binary was compiled on instead of the system where it's running

### ISSUE THREAD

**Issue by LeonineKing1199** [google/googletest#3180]
https://github.com/google/googletest/blob/967d8e05c2f006dc0bcebb3b0b28ecc637204b8d/googletest/src/gtest_main.cc#L50

As evidenced above, the path is baked into the final executable so that when `gtest` is consumed as a binary package, users see the path where the machine was compiled on.

Instead, this should be a runtime property to accurately reflect the system where it's running.

Example of issue:

* GTest was compiled on my machine
* Downstream user links against `libgtest.a` and `libgtest_main.a`
* User compiles test suite and runs

Output is:
```
Running main() from /home/christian/no-boost/buildtrees/gtest/src/ase-1.10.0-7231afa423.clean/googletest/src/gtest_main.cc
```

Downstream user has no `/home/christian/no-boost/...` path on their system.

**Comment by asoffer** [comment]
Yes, __FILE__ is a macro that expands to the file name of the file being compiled. This is how the macro works in C++ and is unrelated to an issue in GoogleTest.

**Comment by LeonineKing1199** [comment]
I know `__FILE__` is a macro. I'm saying, using it here is the Wrong Thing to do.

The issue is that GTest is using something it shouldn't because a user is using it in a valid way and getting silly/unexpected results.

Instead, I'd opt into removing this from the build:
https://github.com/google/googletest/blob/336fd36fee0e95a28a6f5f8ea77e36a2eb7c583e/googletest/CMakeLists.txt#L130

Or come up with some other non-macro based solution.
