### ISSUE TITLE
will run tests many times when I try to test my multi-process code. 

### ISSUE THREAD

**Issue by GitYuanQu** [google/googletest#3182]
so confused that I write the code which will fork some son process to handle other process, and try to check this parts codes with Gtest, I wrote the test body to control my code run 6 times, and mock the son process to repeat run success, final, it will run 6 times than I expect. 

for example, if I wrote only 1 case to test my code, and in this case, I will control my code to run fork 6 times, finally will have at least 6 results in screen.

by the way, if you have example about how to test multi-process code, please send to me. thanks.

**Comment by asoffer** [comment]
GoogleTest is a unit-testing framework and generally we consider multi-process to be multi-unit and therefore not something we test. I suspect the fork is executing the other test cases multiple times, but in general this is not something we support.
