### ISSUE TITLE
Gmock nuget package: Missing "pch.h" in gmock-all.cc and gtest-all.cc

### ISSUE THREAD

**Issue by Thomas1664** [google/googletest#3190]
I installed the nuget extension gmock (Version 1.10.0) for Visual Studio 2019. I got 2 errors after building the project saying that `pch.h` needs to be included in `gmock-all.cc` and `gtest-all.cc`. I tried to fix this error by adding those files to the project and disabeling precompiled headers for them but it didn't work. Including `pch.h` leads to a couple of linking errors.

Since the nuget package refers to this repo as project, I considered it to be the right place for requesting help with this problem.

**Comment by derekmauro** [comment]
We think this is an issue with nuget and/or how you are building the code. Unfortunately we can't help here, this is not a GoogleTest issue.
