### ISSUE TITLE
"threadsafe" option causes "death test" not to fail in case of normal situation.

### ISSUE THREAD

**Issue by aslanfatih** [google/googletest#3192]
- For the multithreaded test binay, when "threadsafe" option is applied according to the way proposed in v1.10.0 [Death Test Style](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#death-test-styles)

It does not fail.

However, we expect that when it runs normally (not failed one) as shown below, death test assertion should give a failure.

```
int main(int argc, char** argv) {
  testing::InitGoogleTest(&argc, argv);
  testing::FLAGS_gtest_death_test_style = "fast";
  return RUN_ALL_TESTS();
}

TEST(MyDeathTest, TestOne) {
  testing::FLAGS_gtest_death_test_style = "threadsafe";
  // This test is run in the "threadsafe" style:
  ASSERT_DEATH(**Not**Die(), "");
}

```

**Comment by asoffer** [comment]
Perhaps I'm misunderstanding, but this seems to be working:
https://godbolt.org/z/dWMYvK

Could you provide exact reproduction instructions (ideally, a godbolt link)?

**Comment by aslanfatih** [comment]
Hi Andy,

You understood the problem correctly. After opening issue, I recognized that my test cases have some dependency with DPDK  threads. After isolated my death test case from the threads which are available during test execution, then saw the failure as expected. There can be some wrong adaptation of the DPDK threads. Therefore, we can close this issue for now.
