### ISSUE TITLE
Add support for generating Code Coverage Report

### ISSUE THREAD

**Issue by Rahul-Dixit** [google/googletest#3203]
Most software have large code bases, which makes it difficult to maintain them. And many of them use unit testing frameworks so that each module that ships to the production stage is well tested.

In this scenario, it would be very helpful if GoogleTest supports computing code coverage apart from the usual unit testing it does. It should also allow us to generate a detailed code coverage report in some convenient format like HTML, XML or JSON.

This would help the software maintainers to find out how much of their code has been covered under unit testing. They will then strive to increase their code coverage, and thus their code will ship with significantly lesser bugs in the production stage.

Those of them who use code coverage currently have to rely on various third party tools, which have far lesser reputation. Moreover their results cannot be trusted completely. It would be great if this ability is directly built-in inside the GoogleTest  framework. Many other unit testing frameworks already have this.

See [this Wikipedia page](https://en.m.wikipedia.org/wiki/List_of_unit_testing_frameworks) for more information. Note that many of the unit testing frameworks have Code Coverage Integration.

**Comment by derekmauro** [comment]
We use the compiler to generate code coverage reports. I know both GCC and Clang have this ability. We don't consider this to be a job of a C++ unit testing framework.
