### ISSUE TITLE
SCOPED_TRACE removes the HasFailure() value

### ISSUE THREAD

**Issue by oesteban-vx** [google/googletest#3210]
```cpp
#include <gtest/gtest.h>

int some_function(int n)
{
    // No messages (should print both [Internal] and [External])
    return n < 0;

    // Prints [External]
    // return n >= 0;
}

TEST(aaa, bbb)
{
    for (int n = 0; n < 3; n++)
    {
        SCOPED_TRACE(n);

        EXPECT_PRED1(some_function, n); // Test 1

        if (HasFailure())
            std::cout << "[Internal] Got a failure" << std::endl;
    }

    EXPECT_TRUE(some_function(-1)); // Test 2

    if (HasFailure())
        std::cout << "[External] Got a failure" << std::endl;
}
```
When running this code we'll get the _[External]_ message if _Test 2_ fails, but it won't show if _Test 1_ does.

Removing the `SCOPED_TRACE`, it behaves as expected.

GTest release is 1.8.1. In fact, it's a fork from efecb0bfa6 (Feb 2019).

**Comment by kuzkry** [comment]
Hey. That's an interesting issue, but I don't know how to reproduce it. Perhaps I didn't understand how. What I did was to checkout efecb0b, compile your code snippet and compare it against some other slightly modified versions of it (like removing _Test2_ or `SCOPED_TRACE` lines) but every time I got the _[External]_ message.

**Comment by oesteban-vx** [comment]
Using `some_function` as it is (`n < 0`) wouldn't print anything (it should print both), while using the commented code (`n >= 0`) would print [External] as expected.

At least, that's how it would behave last friday... but neither I can't reproduce it today :-o

I'd say I know what happened. The problem is not with GTest, but with [VS's Text Explorer](https://docs.microsoft.com/en-us/visualstudio/test/run-unit-tests-with-test-explorer?view=vs-2019).
### `n < 0`:
![imagen](https://user-images.githubusercontent.com/60652318/104165868-3c16f900-53fa-11eb-9565-5a5eaeffe09c.png)
### `n >= 0`:
![imagen](https://user-images.githubusercontent.com/60652318/104165930-4df89c00-53fa-11eb-84cf-fe4ce5a2fb91.png)

**Comment by oesteban-vx** [comment]
I've tried reporting the issue to MS but I've given up. I can't make out where or how I have to sign up to just add a reference to this issue. I'd appreciate your help if you are more familiarized with those things. It looks like [this is the place to do it](https://developercommunity2.visualstudio.com/report?space=8&entry=problem), but it asks you to do it from a running Visual Studio instance.

**Comment by kuzkry** [comment]
Sorry, I can't help you with it. I don't use Visual Studio. I only tried to reproduce your problem using command line and it looked fine.

**Comment by oesteban-vx** [comment]
Feel free to close it as a non-issue, then :-)

**Comment by kuzkry** [comment]
I'm not a maintainer here so I can't. If you're think it's not a googletest issue, you can close it.

**Comment by dinor7c** [comment]
Can you reproduce the issue in the command line?
What compiler are you using?

**Comment by oesteban-vx** [comment]
@dinor7c , see above. It runs ok on the command line, the problem is one of VisualStudio Text explorer reporting. I guess it gets confused with the SCOPE lines and it discards stdout.
The only thing remaining would be reporting to MS (with a link to this issue). I tried and failed, it might be that I don't have a MS-developer account, I'm not sure.

**Comment by dinor7c** [comment]
That does sound like a VisualStudio problem; I'm closing the issue.
