### ISSUE TITLE
A bunch of links are broken 

### ISSUE THREAD

**Issue by Celthi** [google/googletest#3225]
A bunch of links such as the "gmock for dummies" in https://github.com/google/googletest/blob/master/googlemock/README.md

**Comment by saynb** [comment]
google searches for the gmock cookbook etc are also directing to these broken links

**Comment by hyukmyeong** [comment]
I think it’s because all documents moved to https://github.com/google/googletest/tree/master/docs yesterday

**Comment by ericschmidtatwork** [comment]
@hyukmyeong is correct, I'm working on fixing this and #3222
