### ISSUE TITLE
Use linear-time globbing in UnitTestOptions::MatchesFilter

### ISSUE THREAD

**Issue by dmcardle** [google/googletest#3227]
This function uses a recursive globbing algorithm that takes exponential time.

Besides a readability loss, I don't think there's any downside to using a linear-time algorithm. See https://research.swtch.com/glob.

I have a prototype that gives a noticeable boost to Chromium's net_unittests startup time. Need to clean it up before uploading a PR.

**Comment by derekmauro** [comment]
cl/351880895 is the pending internal change
