### ISSUE TITLE
assert should be pass but fail sometimes

### ISSUE THREAD

**Issue by xty-20200627** [google/googletest#3229]
hi, i use like  EXPECT_EQ(4,args) , but it failed when the args is 4 , here is the output of the  console

Expected equality of these values:
  4
  args
    Which is: 4

How cause this?

**Comment by asoffer** [comment]
We would need a small reproduction case to check this. Feel free to reopen if you can provide one. I suspect `args` prints itself as `4` but doesn't compare equal to `4` (perhaps it's not of type`int`)?
