### ISSUE TITLE
Getting Http 404 when trying to access the Google Test Primer Link

### ISSUE THREAD

**Issue by rajahks** [google/googletest#3233]
The link mentioned in the README.md is https://github.com/google/googletest/blob/master/googletest/docs/primer.md
---
![image](https://user-images.githubusercontent.com/26196414/105015966-1b891780-5a68-11eb-8b3c-a280b5e4c131.png)
---

And accessing it returns a Http 404 error.
![image](https://user-images.githubusercontent.com/26196414/105015591-b6cdbd00-5a67-11eb-962c-5b025570ae2b.png)

**Comment by frankalicious** [comment]
There are already pull requests for this issue.  
See #3231 and #3232.

**Comment by ericschmidtatwork** [comment]
Fixed by #3231
