### ISSUE TITLE
`GoogleTest Primer` documenation is broken ( 404 )

### ISSUE THREAD

**Issue by dschiller** [google/googletest#3236]
URL `GoogleTest Primer` at `https://github.com/google/googletest/blob/master/googletest/docs/primer.md` is broken and results in `404`.

![image](https://user-images.githubusercontent.com/3144986/105466101-0f819d80-5c94-11eb-87c6-3714601b3fb0.png)

**Comment by ericschmidtatwork** [comment]
Thanks! Closing as a duplicate of #3233
