### ISSUE TITLE
10: fatal error: gtest/internal/gtest-internal.h: No such file or directory  #include "gtest/internal/gtest-internal.h"

### ISSUE THREAD

**Issue by manavs396** [google/googletest#3241]
I am working on c++ project trying to use google testing I have installed google test contents in lib folder here is cmakelist: 
project(Google_tests)

# 'lib' is the folder with Google Test sources
add_subdirectory(lib)
include_directories(${gtest_SOURCE_DIR}/include ${gtest_SOURCE_DIR})

# 'Google_Tests_run' is the target name
# 'test1.cpp tests2.cpp' are source files with tests
add_executable(Google_Tests_run test1.cpp)
target_link_libraries(Google_Tests_run gtest gtest_main)

Here is my test1.cpp: 

#include <CacheSimulator.h>
//#include "gtest/gtest.h"
#include "lib/googletest/include/gtest/gtest.h"

//#include "lib/googletest/include/gtest/gtest.h"

    class test1
            : public testing::Test {

    protected:
        virtual void SetUp() {
            cacheObj = new CacheSimulator(0, 0, 0, 0);
        }

        virtual void Teardown() {
            delete cacheObj;
        }

        CacheSimulator *cacheObj;
    };

    TEST_F()

    int main(int argc, char **argv) {
        testing::InitGoogleTest(&argc, argv);
        return RUN_ALL_TESTS();
    }

Whenever I run the play button on class this error comes up : 10: fatal error: gtest/internal/gtest-internal.h: No such file or directory #include "gtest/internal/gtest-internal.h"

**Comment by derekmauro** [comment]
The only real help we can offer you is to point you to a working example: https://github.com/fowles/abseil-hello/tree/cmake
