### ISSUE TITLE
Bad Link to the Primer on the README

### ISSUE THREAD

**Issue by yth** [google/googletest#3243]
The link to the GoogleTest primer seems to contain a typo:
https://github.com/google/googletest/blob/master/googletest/docs/primer.md (current)
https://github.com/google/googletest/blob/master/docs/primer.md (actual location).

**Comment by rainerschoe** [comment]
Thanks for pointing this out :) Your issue helped me as a user, as I was struggling to find the correct location when I needed to do some quick API lookup :+1:

**Comment by ericschmidtatwork** [comment]
Thanks for raising this. This issue is covered by #3233 and the fix is pending export 👍
