### ISSUE TITLE
GTEST_IMPL_CMP_HELPER_(GT, >); in gtest.c

### ISSUE THREAD

**Issue by Oskar-H** [google/googletest#3249]
GTEST_IMPL_CMP_HELPER_(GT, >) ;  
There seem compilation errors as result of the semicolon added.

**Comment by hhatch** [comment]
Yes, and for all of these in googletest-src/googletest/include/gtest/gtest.h :

`// Implements the helper function for {ASSERT|EXPECT}_NE
GTEST_IMPL_CMP_HELPER_(NE, !=);
// Implements the helper function for {ASSERT|EXPECT}_LE
GTEST_IMPL_CMP_HELPER_(LE, <=);
// Implements the helper function for {ASSERT|EXPECT}_LT
GTEST_IMPL_CMP_HELPER_(LT, <);
// Implements the helper function for {ASSERT|EXPECT}_GE
GTEST_IMPL_CMP_HELPER_(GE, >=);
// Implements the helper function for {ASSERT|EXPECT}_GT
GTEST_IMPL_CMP_HELPER_(GT, >);
`

**Comment by sethrj** [comment]
Yep, I just saw this too. Is there an open PR yet? Can the googletest CI add `-pedantic -Werror` to one of the builds to prevent a reoccurrence?

**Comment by derekmauro** [comment]
I believe a fix is pending release.
