### ISSUE TITLE
Why using googletest PrintToStringParamName() to print test suffix not working?

### ISSUE THREAD

**Issue by sdajklfw389** [google/googletest#3255]
I wanna google test to show different suffix in parametrized test, my code is as following:

```
class CacheTestP
    : public ::testing::TestWithParam<std::string>
{

};

TEST_P(CacheTestP, NewTest)
{
}

vector<string> GetStrings()
{
    vector<string> ret;
    ret.push_back("Insert"s);
    ret.push_back("Query"s);
    return ret;
}

INSTANTIATE_TEST_SUITE_P(Preffix, CacheTestP, ::testing::ValuesIn(GetStrings()), testing::PrintToStringParamName());
```
It seems that the function PrintToStringParamName() convert the std::string Insert into '\"Insert\"', which is weird, because in the source code the author clearly wrote:

> // The last argument to INSTANTIATE_TEST_SUITE_P allows the user to specify generator and an optional function or functor that generates custom test name suffixes based on the test parameters.

>// testing::PrintToStringParamName is a builtin test suffix generator that returns the value of testing::PrintToString(GetParam()).

So why I did it wrongly? I think it supposes to work regarding to the comments.

**Comment by derekmauro** [comment]
What was the expected result and what did you actually observe?

**Comment by sdajklfw389** [comment]
I expect it to print the test name like this: "Preffix/CacheTestP/Insert" & "Preffix/CacheTestP/Query". But infact there is an exception, because the function PrintToStringParamName() does not handle std::string quite well.

**Comment by sdajklfw389** [comment]
> What was the expected result and what did you actually observe?

I expect it to print the test name like this: "Preffix/CacheTestP/Insert" & "Preffix/CacheTestP/Query". But infact there is an exception, because the function PrintToStringParamName() does not handle std::string quite well. And it actually have the test suffix like this : '\"Insert\"' and '\"Query\"', when I debug.

**Comment by sbenzaquen** [comment]
I don't think `testing::PrintToStringParamName` will do what you need here.
`testing::PrintToString` prints a std::string with quotes around it, which make the output an invalid name.
`testing::PrintToStringParamName` is mostly useful for integrals/enums.

**Comment by derekmauro** [comment]
This seems to be working as intended.

**Comment by sdajklfw389** [comment]
> I don't think `testing::PrintToStringParamName` will do what you need here.
> `testing::PrintToString` prints a std::string with quotes around it, which make the output an invalid name.
> `testing::PrintToStringParamName` is mostly useful for integrals/enums.

sorry about the late response, but I must humbly disagree with this. 

Firstly the comment in source code does not stress that this function is only for integral.
Secondly, to use string as Testname Suffix is much more common than number.
Thirdly, I do not think it is technically impossible to make this function also handle string.

**Comment by sbenzaquen** [comment]
It doesn't say it is for integral, but it does say that it uses `PrintToString`, which will put quotes on strings as well as escape non-printable characters, etc. Those things are not compatible with what `INSTANTIATE_TEST_SUITE_P` requires.
We could change the contract of `PrintToStringParamName` and special case string. That is a different proposal, though.
