### ISSUE TITLE
C++20:  gtest attempts to invoke deleted stream insertion operators

### ISSUE THREAD

**Issue by aidtopia** [google/googletest#3266]
In C++20, the `basic_ostream<T>` insertion operators for character types that are not `T` are deleted.  If you have `EXPECT_` or `ASSERT_` macros to check the values of something like a `char32_t`, you will no longer be able to compile the test after upgrading to C++20.

For example:
```
TEST(Foo, Bar) {
  char32_t code_point = GetNextCodePoint();
  EXPECT_EQ(0, code_point);  // won't compile
}
```

This won't compile because the macro generates code to format an error message if the test fails.  That formatting code tries to invoke `std::basic_ostream<char> & operator<<(std::basic_ostream<char> &, char32_t)`, but C++20-compliant standard libraries delete that function to prevent programmers from accidentally trying to print a character or string from a type that isn't compatible with the stream.

Workarounds:
* Cast the unusual character type to an integral type.
* Check your toolchain for a switch to turn of this new feature of C++20 (e.g., with MSVC, you can `#define _HAS_STREAM_INSERTION_OPERATORS_DELETED_IN_CXX20 1`).

It seems unfortunate that this standards change makes it harder for the test framework to be able to provide well-formatted messages regardless of the types in use.  It also means that previously useful tests no longer compile.

**Comment by sbenzaquen** [comment]
This seems to work with both gcc/libstdc++ and clang/libc++.
Eg: https://gcc.godbolt.org/z/h1nfoY

Can you post more information on how to reproduce this?

**Comment by svenpanne** [comment]
> This seems to work with both gcc/libstdc++ and clang/libc++.
> Eg: https://gcc.godbolt.org/z/h1nfoY
> 
> Can you post more information on how to reproduce this?

Compiler Explorer is useless for testing problems with recent googletest versions, it uses an old version of googletest, which doesn't have the bug yet: https://github.com/compiler-explorer/compiler-explorer/blob/a4ad7f2a41500bd71977c91c83e38eaa31594114/etc/config/c%2B%2B.amazon.properties#L1558

Having said that, I have tons of problems with recent googletest versions and C++17/20 myself, see e.g. https://github.com/google/googletest/issues/2881, this issue should _not_ have been closed.

**Comment by aidtopia** [comment]
Here's a repro:  https://godbolt.org/z/xczG86

Note that it's using MSVC with the `/std:c++latest` option, which is necessary to enable C++20 features.  I don't think it's an MSVC bug, because it seems to be doing exactly what the C++20 standard requires, but I haven't taken the time to try other compilers and their libraries.

In particular, the standard library for C++20 deletes some of the `operator<<` overloads on the assumption that sending something like a `char32_t` to a `basic_ostream<char>` is likely an error.  Unfortunately, this library change makes it difficult for generic code like the testing framework.

**Comment by sbenzaquen** [comment]
> Compiler Explorer is useless for testing problems with recent googletest versions

The "trunk" version should be pretty up to date.

> Here's a repro: https://godbolt.org/z/xczG86

The MSVC version of googletest there doesn't seem to have trunk. It is from 2020.04.

> see e.g. #2881

From what I can see in the code, we are not streaming `charXX_t` or `charXX_t*` directly anymore.
`charXX_t` are casted to integers before streaming.
https://github.com/google/googletest/blob/master/googletest/src/gtest-printers.cc#L256
`charXX_t*` are casted to `void*`.
https://github.com/google/googletest/blob/master/googletest/include/gtest/gtest-printers.h#L517

I believe this should work fine at head.

**Comment by aidtopia** [comment]
OK, thanks.  I had just upgraded to the 1.10.0 release when I discovered the problem.  I didn't realize I was still that far behind head.

**Comment by svenpanne** [comment]
> > Compiler Explorer is useless for testing problems with recent googletest versions
> 
> The "trunk" version should be pretty up to date.

Nope, I don't think so: If I read the Compiler Explorer config correctly, it uses https://github.com/google/googletest/releases/tag/release-1.10.0 from Oct 2019, which is hundreds of commits behind HEAD.
