### ISSUE TITLE
CMake compatibility with version 2.8

### ISSUE THREAD

**Issue by bstaletic** [google/googletest#3274]
Since cmake 3.19, the following warning is shown:

```
CMake Deprecation Warning at CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at googlemock/CMakeLists.txt:45 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```

**Comment by derekmauro** [comment]
I thought someone fixed this a few weeks ago. Are you using the latest HEAD?

**Comment by bstaletic** [comment]
Hi. I'm on the latest release - 1.10.0, but looking at master's CMakeLists.txt, the requirement for version 2.8 is still there:

1. https://github.com/google/googletest/blob/master/CMakeLists.txt#L4
2. https://github.com/google/googletest/blob/master/googlemock/CMakeLists.txt#L45
3. https://github.com/google/googletest/blob/master/googletest/CMakeLists.txt#L56

**Comment by hyukmyeong** [comment]
Hello,
https://github.com/google/googletest/pull/3094 is merged quite recently (Jan/2021)  
and so using 1.10.0 which was released 2019 can't resolve above warnings

**Comment by bstaletic** [comment]
Oh, thanks for pointing that out. I was under the impression that all of cmake 2.8.x is raising warnings, so I didn't try HEAD. Yes, HEAD doesn't raise those warnings. Apologies for the noise.
