### ISSUE TITLE
Add GTEST_DONT_DEFINE_EXPECT_{TRUE,FALSE} flags.

### ISSUE THREAD

**Issue by jacobdweightman** [google/googletest#3282]
The GoogleTest README includes a section "Avoiding Macro Name Clashes" which mentions the possibility of adding flag `-DGTEST_DONT_DEFINE_FOO=1` to prevent GoogleTest from defining a macro `FOO`. This is only possible with a select set of macros defined in GoogleTest.

I work on a project where I would like to use GoogleTest, but it already defines macros named `EXPECT_TRUE` and `EXPECT_FALSE` which we prefer not to change. I propose that GoogleTest instead define new macros `GTEST_EXPECT_TRUE`, and conditionally define `EXPECT_TRUE` when not compiling with `-DGTEST_DONT_DEFINE_EXPECT_TRUE=1`, in line with the existing precedent.

**Comment by dinord** [comment]
Merged in https://github.com/google/googletest/commit/4048829db1b29977f96f05c183a52869e6bdecbe.

**Comment by jacobdweightman** [comment]
Awesome, thanks!
