### ISSUE TITLE
Release plan for new versions

### ISSUE THREAD

**Issue by leosh64** [google/googletest#3285]
Dear developers,

is there a release plan for new versions of `googletest`? 

The latest release at the time of writing is *v1.10.0* from October 2019. Since then, some useful features have been added on master that we'd like to use in our project (e.g. the `--gtest_brief` flag is not present in `v1.10.0`).

When can we expect the next stable release that includes features from current `master`?

**Comment by derekmauro** [comment]
We recommend you use the master branch. We try to keep it stable. We are going to look at doing coordinated releases with the Abseil LTS releases soon.

**Comment by mechatheo** [comment]
what about ubuntu Debian releases? when are those updated, does anyone know?

**Comment by leosh64** [comment]
Anyone finding this issue in the future: Releases have resumed, there's [v1.11.0](https://github.com/google/googletest/releases/tag/release-1.11.0) now.
