### ISSUE TITLE
Links in docs/index.md don't work (Error 404)

### ISSUE THREAD

**Issue by leosh64** [google/googletest#3288]
**Describe the bug**

The links to subpages in `docs/index.md` don't work in the Github web interface because the `.md` extension is missing.

**Steps to reproduce the bug**

* Access https://github.com/google/googletest/blob/master/docs/index.md
* Click any of the links to subpages (e.g. **Primer** at https://github.com/google/googletest/blob/master/docs/primer)

**What version of GoogleTest are you using?**

`master`

**Additional context**

Adding `.md` to the link that shows a 404 on the Github web interface fixes the issue: https://github.com/google/googletest/blob/master/docs/primer.md should work.

**Comment by leosh64** [comment]
Potential fix: https://github.com/google/googletest/pull/3287

**Comment by ericschmidtatwork** [comment]
Thanks for reporting this. We had a fix pending export and it's now released.
