### ISSUE TITLE
Bazel Build: Use buildifier formatting for BUILD.bazel and WORKSPACE.bazel

### ISSUE THREAD

**Issue by robbie-vanderzee** [google/googletest#3295]
**Describe the bug**

The provided workspace and build files for the gtest suite do not have the buildifier formatting applied. For bazel projects including gtest as a submodule or otherwise, this results in dirty commits when running buildifier recursively without specifying directory ignores. However, these files probably should be formatted according to that tool for consistency.

**Steps to reproduce the bug**

N/A

**What version of GoogleTest are you using?** 

Latest master-(e8b478a7356f21efbada1aae15b49b332cc54e3f)

**What operating system and version are you using**

N/A 

**What compiler and version are you using?**

N/A 

**What build system are you using?**

`bazel --version` bazel 4.0.0

**Additional context**

[Results from Buildifer](https://github.com/google/googletest/compare/master...robbie-vanderzee:master#diff-92d130d91bf45e219931148cd6eb6a33e996a2cc6759605556a93cb962ccacce)

**Comment by SaaadSaadAl** [comment]
Gg

**Comment by dinord** [comment]
Fixed in [e7e5917](https://github.com/google/googletest/commit/e7e591764baba0a0c3c9ad0014430e7a27331d16).

**Comment by robbie-vanderzee** [comment]
Reopening: Seems to have resurfaced.
