### ISSUE TITLE
Do I need a main function to test C lang?

### ISSUE THREAD

**Issue by RanX12** [google/googletest#3296]
hi @bgianfo , I am using gtest to test Clang, but I encountered a problem. I wrote the following code:

```c
#include <stdio.h>

int solution(const int i1, const int i2)
{
  return i1 + i2;
}

int main() {}
```

My test code is as follows:

```c
#include "gtest/gtest.h"
#include "testcase.c"

TEST(testcase, solution)
{
  int sum;
  sum = solution(1, 2);
  EXPECT_EQ(sum, 3);
}
```

You should be able to see that I wrote an ```int main() { }``` in the code, but I did not use it in the test code. If I don't write ```int main() { }```, an error will be reported when running```cmake .. && make```, the following is a screenshot of the error:

![image](https://user-images.githubusercontent.com/46048444/109468722-f85e7880-7aa7-11eb-816b-e46d825826d5.png)

I think that when I test Clang code, I don't want to write ```int main() {}```, but running `cmake .. && make`` will not report errors. what should I do? Please advise, thank you

**Comment by RanX12** [comment]
@bgianfo

**Comment by jayuambekar** [comment]
Hi,

You can link your program with "libgtest_main.a" and completely omit main() function from your source code.
`target_link_libraries(<targetName> ${GTEST_MAIN_LIBRARY} ${GTEST_LIBRARY} pthread) `

**Comment by derekmauro** [comment]
@jayuambekar is correct and that is what I would advise as well.
