### ISSUE TITLE
Does google test support test suites like CUnit ?

### ISSUE THREAD

**Issue by prithvitewatia** [google/googletest#3297]
Does gtest support test suites because I could not find any documentation related to that. Also, is gtest documentation hosted on readthedocs?

**Comment by jayuambekar** [comment]
I haven't used CUnit, but there is a concept of Test Suite(a single test suite contains one or more tests). You can find the documentation https://github.com/google/googletest/blob/master/docs/primer.md

**Comment by prithvitewatia** [comment]
@jayuambekar Found it. Thanks.
