### ISSUE TITLE
CMake Deprecation Warning when compiling with Visual Studio 2019 16.10 Preview 1

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [google/googletest#3298]
I get the following warning when compiling with Visual Studio 2019 16.10 Preview 1:
```shell
CMake Deprecation Warning at CMakeLists.txt:4 (cmake_minimum_required):                                                   
Compatibility with CMake < 2.8.12 will be removed from a future version of CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```
It's caused because of the entry in the CMakeLists.txt file:
```shell
cmake_minimum_required(VERSION 2.8.8)
```

**Steps to reproduce the bug**

```shell
mkdir build
cd build
cmake ..
```

**What version of GoogleTest are you using?**

1.10.0

**What operating system and version are you using**

Windows 10 2004

**What compiler and version are you using?**

Visual Studio 2019 16.10 Preview 1

**What build system are you using?**

cmake version 3.19.20122902-MSVC_2

**Comment by SaaadSaadAl** [comment]
Gh

**Comment by lizzby** [comment]
whatever hacker/Cheaters! why dont you cheat yourselves huh!

**Comment by lizzby** [comment]
or hack yourself?

**Comment by lizzby** [comment]
-➡️➡️➡️ WIFE!!!!!!

**Comment by lizzby** [comment]
dont really get it! any deeper? lol
 here's your task: READ THIS www.verywellmind.com/how-to-be-a-better-person-4167628

**Comment by mustafa19951787** [comment]
Yük

**Comment by lizzby** [comment]
> Yük

in a tech dominated world, are you losing your grip on reality?

**Comment by derekmauro** [comment]
This issue should be fixed in the latest commit. We recommend [living at head](https://abseil.io/about/philosophy#we-recommend-that-you-choose-to-live-at-head) (use the latest commit in the master branch) and don't recommend using the old "release" versions anymore.
