### ISSUE TITLE
--gtest_output generate a empty xml output sporadic

### ISSUE THREAD

**Issue by YW82** [google/googletest#3338]
I have some testcase and want to generate the xml report from gtest, the testcase was ran sucessfully 
[==========] Running 50 tests from 22 test cases.
[==========] 50 tests from 22 test cases ran. (87 ms total)
[  PASSED  ] 50 tests.

but the xml report was empty. The issues was  spradic, it was happend in about 25 cycles only 1 time.
i am using the belowing commant
Unittest.exe --gtest_output=xml:../reports/gtestresults.xml

**Comment by anushkagupta417** [comment]
I am interested on working on it .please assign it to me.

**Comment by derekmauro** [comment]
There isn't enough information provided to understand why this is happening. We recommend filling out the bug template when filing issues because requests important information to help us understand what is happening.

**Comment by YW82** [comment]
@derekmauro pls tell me which information you need
