### ISSUE TITLE
"--gtest_list_tests" outputs much more than just test names

### ISSUE THREAD

**Issue by mloeser21** [google/googletest#3349]
**Describe the bug**

If I try to retrieve the test names via './build/data/data_tests --gtest_list_tests' the output includes warnings, errors, basically a bunch of stdout messages that are not actual tests.

Example (only first two lines are what I would expect to see):
```
StatusRequesterTests. <<< Expected
  TestGetName <<< Expected
CacheControllerTests/CacheControllerTestFixture.
  ApplyCapturePolicy/0  # GetParam() = 1-byte object <00>
  ApplyCapturePolicy/1  # GetParam() = 1-byte object <01>
  ApplyCapturePolicy/2  # GetParam() = 1-byte object <02>
[...]
InvalidSchemaTriggerConditionWithSignalTests/InvalidSchemaTriggerConditionWithSignalTest.
  InvalidTriggerConditions/0  # GetParam() = "SIG_FOR_UNIT_TEST1 == 0xjklm"
  InvalidTriggerConditions/1  # GetParam() = "SIG_FOR_UNIT_TEST1 == 0xJKLM"
[...]
RequiredTopLevelFieldTests/MissingRequiredTypeFieldByPolicyTypeFixture.
  typesAreRequiredOnAllPolicyTypes/0  # GetParam() = 1-byte object <01>
  typesAreRequiredOnAllPolicyTypes/1  # GetParam() = 1-byte object <00>
[...]
FileStorageRangeTests/FileStorePolicyFieldsByPolicyTypeFixture.
  fileStorageRangeCheck/0  # GetParam() = (1-byte object <00>, 2, 1, true)
  fileStorageRangeCheck/1  # GetParam() = (1-byte object <00>, 3, 1, true)
  fileStorageRangeCheck/2  # GetParam() = (1-byte object <00>, 2, 460800, true)
[...]
[2021-04-06 14:16:54.243] [data_logger] [info] Logging halted
[2021-04-06 14:16:54.243] [data_logger] [info] Halting Transmission
[2021-04-06 14:16:54.243] [data_logger] [info] No in progress transmission to halt
```

**Steps to reproduce the bug**

Run the test binaries against '--gtest_list_tests', i.e. `./build/data/data_tests --gtest_list_tests`.
We are using version 3.10.2.

**Does the bug persist in the most recent commit?**

N/A -- upgrading will need to be carefully planned

**What operating system and version are you using?**

Linux 18.04.1-Ubuntu

**What compiler and version are you using?**

gcc version 6.5.0 20181026 (Ubuntu 6.5.0-2ubuntu1~18.04)
clang version 9.0.0-2~ubuntu18.04.2 (tags/RELEASE_900/final)

**What build system are you using?**

cmake version 3.10.2

**Additional context**

N/A

**Comment by derekmauro** [comment]
This looks correct to me. It looks like you have parameterized tests and we are dumping the instantiations of the parameterized tests. Do you agree?

The final log lines do not appear to be coming from GoogleTest.

**Comment by mloeser21** [comment]
Yes, looks like you are correct - sorry I was not aware of that. Please go ahead and close this ticket then. Thanks!
