### ISSUE TITLE
google mock DoAll(SaveArg()) fails, if mocked method takes an R-Value reference

### ISSUE THREAD

**Issue by Mario-Klebsch** [google/googletest#3352]
**Describe the bug**

I have to mock a method, that takes an R-value reference:

    MOCK_METHOD(bool, bug3, (const char*, std::string&&), ());

I can instruct the mock to return a value:

    EXPECT_CALL(*this, bug3).Times(1).WillOnce(Return(true));

But when I try to capture an argument, the code fails to compile:

    EXPECT_CALL(*this, bug3).Times(1).WillOnce(DoAll(SaveArg<0>(&actualArg), Return(true)));

The same code works without problems, when the mocked method takes an l-value reference instead:

    MOCK_METHOD(bool, bug2, (const char*, std::string&), ());
    ...
    EXPECT_CALL(*this, bug2).Times(1).WillOnce(DoAll(SaveArg<0>(&actualArg), Return(true)));

Include a clear and concise description of what the problem is, including what
you expected to happen, and what actually happened.

**Steps to reproduce the bug**
   
    #include "gtest/gtest.h"
    #include "gmock/gmock.h"
    
    class test : public ::testing::Test
    {
    public:
    	MOCK_METHOD(bool, bug1, (const char*), ());
    	MOCK_METHOD(bool, bug2, (const char*, std::string&), ());
    	MOCK_METHOD(bool, bug3, (const char*, std::string&&), ());
    };
    
    using ::testing::Return;
    using ::testing::SaveArg;
    using ::testing::DoAll;
    
    TEST_F(test, test1_return_ok)
    {
    	const char *actualArg = nullptr;
    
    	EXPECT_CALL(*this, bug1).Times(1).WillOnce(Return(true));
    	const char *arg = __FUNCTION__;
    	EXPECT_TRUE(bug1(arg));
    	::testing::Mock::VerifyAndClearExpectations(this);
    }
    
    TEST_F(test, test1_return_and_safe_ok)
    {
    	const char *actualArg = nullptr;
    
    	EXPECT_CALL(*this, bug1).Times(1).WillOnce(DoAll(SaveArg<0>(&actualArg), Return(true)));
    	const char *arg = __FUNCTION__;
    	EXPECT_TRUE(bug1(arg));
    	EXPECT_EQ(actualArg, arg);
    	::testing::Mock::VerifyAndClearExpectations(this);
    }
    
    TEST_F(test, test2_return_and_safe_ok)
    {
    	const char *actualArg = nullptr;
    	EXPECT_CALL(*this, bug2).Times(1).WillOnce(DoAll(SaveArg<0>(&actualArg), Return(true)));
    	const char *arg = __FUNCTION__;
    	std::string s;
    	EXPECT_TRUE(bug2(arg, s));
    	EXPECT_EQ(actualArg, arg);
    	::testing::Mock::VerifyAndClearExpectations(this);
    }
    
    
    TEST_F(test, test3_return_ok)
    {
    	EXPECT_CALL(*this, bug3).Times(1).WillOnce(Return(true));
    	const char *arg = __FUNCTION__;
    	std::string s;
    	EXPECT_TRUE(bug3(arg, std::move(s)));
    	::testing::Mock::VerifyAndClearExpectations(this);
    }
    
    
    TEST_F(test, test3_return_and_safe_dont_compile)
    {
    	const char *actualArg = nullptr;
   	// does not compile in VS2017
    	EXPECT_CALL(*this, bug3).Times(1).WillOnce(DoAll(SaveArg<0>(&actualArg), Return(true)));
    	const char *arg = __FUNCTION__;
    	std::string s;
    	EXPECT_TRUE(bug3(arg, std::move(s)));
    	EXPECT_EQ(actualArg, arg);
    	::testing::Mock::VerifyAndClearExpectations(this);
    }

I am using the NuGet-provided google test:

      <package id="gmock" version="1.10.0" targetFramework="native" />

**Does the bug persist in the most recent commit?**

We recommend using the latest commit in the master branch in your projects.

**What operating system and version are you using?**

Windows 10

**What compiler and version are you using?**

VS2017
Microsoft Visual Studio Professional 2017 
Version 15.9.17
VisualStudio.15.Release/15.9.17+28307.905
Microsoft .NET Framework
Version 4.8.04084

Visual C++ 2017   00370-20003-82190-AA474
Microsoft Visual C++ 2017

**What build system are you using?**

VS2017

**Comment by Mario-Klebsch** [comment]
The code also fauils to compile on linux using g++ (Gentoo 10.2.0-r5 p6) 10.2.0 and clang version 11.1.0

**Comment by sbenzaquen** [comment]
This seemed to be working at head, at least for the g++/clang versions listed above. I don't have access right now to run the code at head with that version of MSVC.

gtest 1.10 fails: https://gcc.godbolt.org/z/WYe9x9615
gtest works: https://gcc.godbolt.org/z/cezaWrT63

Can you test the code with a head version of GoogleTest?

**Comment by Mario-Klebsch** [comment]
Yes, the code compile fine, when I use code from the current git repository (git clone https://github.com/google/googletest.git)

**Comment by derekmauro** [comment]
Closing because this is fixed at HEAD.
