### ISSUE TITLE
Where are the elusive samples?

### ISSUE THREAD

**Issue by Eutics** [google/googletest#3368]
**Describe the bug**
The doc directory of the download has a samples.md file which only describes the tests.
The web link goes to a page which has broken links to the actual samples.

**Comment by ericschmidtatwork** [comment]
Thanks for reporting this! The samples are located at https://github.com/google/googletest/tree/master/googletest/samples.

The links from the docs appear to work on my end - which links are you finding broken?

**Comment by Bitney-0806** [comment]
More information

**Comment by ericschmidtatwork** [comment]
Closing this - feel free to reopen if you have more information.
