### ISSUE TITLE
Example with concept and C++20 for gmock

### ISSUE THREAD

**Issue by bansan85** [google/googletest#3375]
**Describe the bug**

I know there is [Mocking Non-virtual Methods](https://github.com/google/googletest/blob/master/docs/gmock_cook_book.md#mocking-non-virtual-methods-mockingnonvirtualmethods) but it would be nice to have an explicit example with concept.

**Steps to reproduce the bug**

In [gmock for dummies](https://github.com/google/googletest/blob/master/docs/gmock_for_dummies.md#writing-the-mock-class), there is an example with Turtle. Please find below the same example using concept.

```
#include <gmock/gmock.h>

template <typename T>
concept TurtleC = requires(const T t, T u) {
  { u.PenUp() } -> std::same_as<void>;
  { u.PenDown() } -> std::same_as<void>;
};

class MockTurtle {
 public:
  MOCK_METHOD0(PenUp, void());
  MOCK_METHOD0(PenDown, void());
};

template <typename T>
requires TurtleC<T>
class Painter {
  T* turtle;

 public:
  Painter(T* turtle) : turtle(turtle) {}

  bool DrawCircle(int, int, int) {
    turtle->PenDown();
    return true;
  }
};

using ::testing::AtLeast;
TEST(PainterTest, CanDrawSomething) {
  MockTurtle turtle;
  EXPECT_CALL(turtle, PenDown()).Times(AtLeast(1));

  Painter painter(&turtle);

  EXPECT_TRUE(painter.DrawCircle(0, 0, 10));
}

int main(int argc, char** argv) {
  // The following line must be executed to initialize Google Mock
  // (and Google Test) before running the tests.
  ::testing::InitGoogleMock(&argc, argv);
  return RUN_ALL_TESTS();
}
```

**What compiler and version are you using?**

gcc 10.1

Run it with [godbolt](https://godbolt.org/z/Koscjx67G)

**Comment by derekmauro** [comment]
We actually don't have much experience with concepts at this point. I think we will have to wait until we have a better understanding of concepts.

If you feel like writing something unofficial, we would consider linking to it.

**Comment by bansan85** [comment]
Thanks, Unfortunately, I do not have lots of experience neither. I just try replacing pure virtual class by concept and it worked :) That's why I suggested an example. I don't know if it could create some side effects.

**Comment by asoffer** [comment]
I don't think this is appropriate for GMock For Dummies for two primary reasons. First, that guide is intended primarily for beginners; while I do hope that concepts become a beginner-friendly part of the C++ language, I don't think we can call them that yet.

Second, GMock's mocking mechanism is based on dynamic dispatch, whereas concepts provide constraint system for static dispatch. You don't need MOCK_METHOD here and using it doesn't interact in any special way with concepts. In other words, this example, while illustrative, shows two tools (GMock and concepts) being used together but doesn't provide anything beyond would could be provided by separate guides for GMock and concepts.
