### ISSUE TITLE
Compilation error when running cmake3 --build build (CentOS 7.9 & cmake 3.17)

### ISSUE THREAD

**Issue by ryanr08** [google/googletest#3387]
**Describe the bug**

I am attempting to follow the steps from this tutorial: https://google.github.io/googletest/quickstart-cmake.html

I followed the exact steps and ran into trouble running "cmake3 --build build":

Scanning dependencies of target gtest
[ 10%] Building CXX object _deps/googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
In file included from /home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/internal/gtest-death-test-internal.h:39:0,
                 from /home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-death-test.h:41,
                 from /home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest.h:64,
                 from /home/centos/my_project/build/_deps/googletest-src/googletest/src/gtest-all.cc:38:
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h: In static member function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined()’:
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:414:12: error: ‘is_trivially_copy_constructible’ is not a member of ‘std’
            std::is_trivially_copy_constructible<M>::value &&
            ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:414:50: error: expected primary-expression before ‘>’ token
            std::is_trivially_copy_constructible<M>::value &&
                                                  ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:414:51: error: ‘::value’ has not been declared
            std::is_trivially_copy_constructible<M>::value &&
                                                   ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = const std::basic_string<char>&]’:
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:418:58:   required from ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = const testing::MatcherInterface<const std::basic_string<char>&>*&; T = const std::basic_string<char>&]’
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:292:14:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U>*) [with U = const std::basic_string<char>&; T = const std::basic_string<char>&]’
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:516:55:   required from here
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:416:3: error: body of constexpr function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = const std::basic_string<char>&]’ not a return-statement
   }
   ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = const testing::MatcherInterface<const std::basic_string<char>&>*&; T = const std::basic_string<char>&]’:
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:292:14:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U>*) [with U = const std::basic_string<char>&; T = const std::basic_string<char>&]’
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:516:55:   required from here
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:418:58: error: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = const std::basic_string<char>&]’ called in a constant expression
   template <typename M, bool = MatcherBase::IsInlined<M>()>
                                                          ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:412:25: note: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = const std::basic_string<char>&]’ is not usable as a constexpr function because:
   static constexpr bool IsInlined() {
                         ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:463:35: note: in template argument for type ‘bool’
     using Policy = ValuePolicy<MM>;
                                   ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = std::basic_string<char>]’:
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:418:58:   required from ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = const testing::MatcherInterface<const std::basic_string<char>&>*&; T = std::basic_string<char>]’
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:292:14:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U>*) [with U = const std::basic_string<char>&; T = std::basic_string<char>]’
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:538:48:   required from here
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:416:3: error: body of constexpr function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = std::basic_string<char>]’ not a return-statement
   }
   ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = const testing::MatcherInterface<const std::basic_string<char>&>*&; T = std::basic_string<char>]’:
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:292:14:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U>*) [with U = const std::basic_string<char>&; T = std::basic_string<char>]’
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:538:48:   required from here
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:418:58: error: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = std::basic_string<char>]’ called in a constant expression
   template <typename M, bool = MatcherBase::IsInlined<M>()>
                                                          ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:412:25: note: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = std::basic_string<char>]’ is not usable as a constexpr function because:
   static constexpr bool IsInlined() {
                         ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:463:35: note: in template argument for type ‘bool’
     using Policy = ValuePolicy<MM>;
                                   ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<std::basic_string<char> >*; T = std::basic_string<char>]’:
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:418:58:   required from ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = const testing::MatcherInterface<std::basic_string<char> >*&; T = std::basic_string<char>]’
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:292:14:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U>*) [with U = std::basic_string<char>; T = std::basic_string<char>]’
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:540:48:   required from here
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:416:3: error: body of constexpr function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<std::basic_string<char> >*; T = std::basic_string<char>]’ not a return-statement
   }
   ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = const testing::MatcherInterface<std::basic_string<char> >*&; T = std::basic_string<char>]’:
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:292:14:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U>*) [with U = std::basic_string<char>; T = std::basic_string<char>]’
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:540:48:   required from here
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:418:58: error: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<std::basic_string<char> >*; T = std::basic_string<char>]’ called in a constant expression
   template <typename M, bool = MatcherBase::IsInlined<M>()>
                                                          ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:412:25: note: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<std::basic_string<char> >*; T = std::basic_string<char>]’ is not usable as a constexpr function because:
   static constexpr bool IsInlined() {
                         ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:463:35: note: in template argument for type ‘bool’
     using Policy = ValuePolicy<MM>;
                                   ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = const std::basic_string<char>&]’:
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:418:58:   required from ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = const std::basic_string<char>&]’
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:298:28:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-2-2> = void; T = const std::basic_string<char>&]’
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:521:69:   required from ‘testing::Matcher<const std::basic_string<char>&>::Matcher(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-1-2> = void]’
/home/centos/my_project/build/_deps/googletest-src/googletest/src/gtest-matchers.cc:45:68:   required from here
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:416:3: error: body of constexpr function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = const std::basic_string<char>&]’ not a return-statement
   }
   ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = const std::basic_string<char>&]’:
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:298:28:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-2-2> = void; T = const std::basic_string<char>&]’
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:521:69:   required from ‘testing::Matcher<const std::basic_string<char>&>::Matcher(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-1-2> = void]’
/home/centos/my_project/build/_deps/googletest-src/googletest/src/gtest-matchers.cc:45:68:   required from here
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:418:58: error: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = const std::basic_string<char>&]’ called in a constant expression
   template <typename M, bool = MatcherBase::IsInlined<M>()>
                                                          ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:412:25: note: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = const std::basic_string<char>&]’ is not usable as a constexpr function because:
   static constexpr bool IsInlined() {
                         ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:463:35: note: in template argument for type ‘bool’
     using Policy = ValuePolicy<MM>;
                                   ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’:
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:418:58:   required from ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:298:28:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-2-2> = void; T = std::basic_string<char>]’
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:545:62:   required from ‘testing::Matcher<std::basic_string<char> >::Matcher(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-1-2> = void]’
/home/centos/my_project/build/_deps/googletest-src/googletest/src/gtest-matchers.cc:55:61:   required from here
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:416:3: error: body of constexpr function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’ not a return-statement
   }
   ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’:
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:298:28:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-2-2> = void; T = std::basic_string<char>]’
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:545:62:   required from ‘testing::Matcher<std::basic_string<char> >::Matcher(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-1-2> = void]’
/home/centos/my_project/build/_deps/googletest-src/googletest/src/gtest-matchers.cc:55:61:   required from here
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:418:58: error: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’ called in a constant expression
   template <typename M, bool = MatcherBase::IsInlined<M>()>
                                                          ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:412:25: note: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’ is not usable as a constexpr function because:
   static constexpr bool IsInlined() {
                         ^
/home/centos/my_project/build/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:463:35: note: in template argument for type ‘bool’
     using Policy = ValuePolicy<MM>;
                                   ^
gmake[2]: *** [_deps/googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
gmake[1]: *** [_deps/googletest-build/googletest/CMakeFiles/gtest.dir/all] Error 2
gmake: *** [all] Error 2

My CMakeLists.txt and other files are exactly the same as in the tutorial. 

I have attached my CMakeError.log file as well.
[CMakeError.log](https://github.com/google/googletest/files/6379738/CMakeError.log)

Versions:
CentOS Linux release 7.9.2009 (Core)
cmake3 version 3.17.5
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

Any help would be greatly appreciated, thank you in advance!

**Comment by derekmauro** [comment]
> g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

GoogleTest requires GCC >= 5.1.

**Comment by ericoporto** [comment]
is there a version that was compatible with g++ (GCC) 4.8.5 20150623 ?

**Comment by nmoinvaz** [comment]
We were able to get it working with tag `release-1.10.0`.
