### ISSUE TITLE
A new "release" in the sense of Live at Head

### ISSUE THREAD

**Issue by marehr** [google/googletest#3388]
**Describe the bug**

I know that the first line in the README says:

> GoogleTest now follows the [Abseil Live at Head philosophy](https://abseil.io/about/philosophy#upgrade-support).
We recommend using the latest commit in the `master` branch in your projects.

The linked document also states in the same section

> If You Choose to Not Live at Head:
> 
>     You are of course free to fork Abseil, include it in your project and manage dependencies any way that is convenient for your development practices.
>     We will periodically mark a tag as “supported” and branch it — if we discover security issues or major performance problems, we’ll update those branches. Our expectation is to do this every 6 months and support those branches for 2 years.

I'm aware of https://github.com/google/googletest/issues/3124#issuecomment-736032073, but that issue was closed without any resolution.

So I want to propose:

As googletest aims to be fully functional in every commit, for me, it would suffice if you would just release every x months a snapshot (maybe in form of a (new) release branch) of the current master branch. That itself could be automated by e.g. github actions. If anything broke at that time frame, the community can fix that by suggesting pull requests and/or cherry-picking commits from the master and/or reverting commits.

**Comment by derekmauro** [comment]
Thank you for the feedback. What problem would this be solving for you?

**Comment by puetzk** [comment]
It would be a Schelling point for packaging systems like [conan-center-index](https://github.com/conan-io/conan-center-index/blob/master/recipes/gtest/config.yml), [vcpkg](https://github.com/microsoft/vcpkg/blob/master/ports/gtest/portfile.cmake), etc to make something newer than 1.10 available.

**Comment by marehr** [comment]
I personally had problems with debian and fedora that packaged different versions of googletest, and it was a bit difficult to find out what the subtle difference was, because we couldn't easily name a reference point.

As @puetzk already pointed out, it makes it easier for the community to have a name for a known good point in time and helps to have an easier accessible, common language to pinpoint to a certain state. I mean in math you always name certain values in a contiguous function that are special. This is done to keep the complexity low.

As I suggested, it would suffice to add an automatic tagging / branch system and if you green light this, we, as the community, can establish and maintain that. (similar as cmake is maintained by the community)

**Comment by NorbertNemec** [comment]
I already wanted to recommend the same: our project consumes googletest via vcpkg and updating it manually would be quite a bit of overhead. I'm mostly annoyed & concerned by the CMake < 2.8.12 warning that has been fixed in googletest master for months and would be trivial by a release flowing through the official channel but could become an urgent problem for many projects when CMake suddenly decides to make true of their warning and drop compatibility.

**Comment by NorbertNemec** [comment]
I guess, with 1.11.0 out of the door, this can be resolved?
