### ISSUE TITLE
can't build on mac m1 

### ISSUE THREAD

**Issue by picturetxl** [google/googletest#3396]
I followed the steps in the readme file under the googletest folder to execute the compilation command, but it prompted me to make an error。
![image](https://user-images.githubusercontent.com/34642821/117274520-b7138c00-ae8f-11eb-8180-97acaa217575.png)

**Comment by derekmauro** [comment]
Please fill out the bug report form so we have all the information that we need: https://github.com/google/googletest/blob/master/.github/ISSUE_TEMPLATE/00-bug_report.md
