### ISSUE TITLE
Unecessary warnings : Comparison of integer expressions of different signedness 

### ISSUE THREAD

**Issue by AxelVE** [google/googletest#3401]
It's a moment now that a new version brought unnecessary warnings during C++ compiling.
 
warning: comparison of integer expressions of different signedness: 'const long unsigned int' and 'const int'

EXPECT_EQ(ErrorCount(), 1);

In the function ErrorCount returns a size_t value.

Gtest version : release-1.10.0
gcc version : 8.3.0

**Comment by derekmauro** [comment]
This is how compilers warn on signedness comparison. There isn't anything we can do about this.

Try `EXPECT_EQ(ErrorCount(), 1u);` or `EXPECT_EQ(ErrorCount(), size_t{1});`
