### ISSUE TITLE
[Question]Is there a way to force quit during test execution?

### ISSUE THREAD

**Issue by hyukjae-yoo** [google/googletest#3402]
I am developing a tool that can run GTEST from a GUI program. A function to stop or forcefully terminate during execution of numerous test cases is required. However, I can't see any document related functions. Is there a way to stop/terminate?

**Comment by derekmauro** [comment]
I think the answer to this is just to kill the process running the test. You can run individual processes with tests using `--gtest_filter`. If you have more questions about this, feel free to ask.

**Comment by hyukjae-yoo** [comment]
Thank you for answer. I'll check it in an individual process method.
