### ISSUE TITLE
support ranges with Container Matchers 

### ISSUE THREAD

**Issue by slymz** [google/googletest#3403]
See https://godbolt.org/z/KWb3bT16c

```
using testing::ElementsAre;
EXPECT_THAT( ranges::views::iota(0,3),  ElementsAre(0,1,2)); // currently a compilation error
```
where `ranges` is either C++20 ranges (`std::ranges`) or the emulation in C++14+ via range-v3.  

Inadvertently or not (despite the name) [Container Matchers](https://google.github.io/googletest/reference/matchers.html#container-matchers) seems to support the now legacy Boost.Range2 (which are not technically containers).  E.g. https://godbolt.org/z/3fdx43Mcq

It would make sense to support the up-and-coming and/or modern ranges with the so called Container Matchers, or perhaps rename them as Range Matchers.

**Comment by derekmauro** [comment]
We don't have much experience with ranges yet, but when we get more experience we will probably add this support.

**Comment by asoffer** [comment]
This is a similar request to #3564, we would welcome a pull-request, but at this time we are not able to promise support for C++20 ranges ourselves.
