### ISSUE TITLE
I don't understand why my test case took 11.22 sec.Would you please tell me where the extra 10s came from？

### ISSUE THREAD

**Issue by Russellqiu** [google/googletest#3418]
Running main() from D:\Code\win_rtc_dll_test\test_main.cpp
Note: Google Test filter = MediaSDKTest.TestScreenSharing
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from MediaSDKTest
[ RUN      ] MediaSDKTest.TestScreenSharing
[       OK ] MediaSDKTest.TestScreenSharing (265 ms)
[----------] 1 test from MediaSDKTest (265 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (855 ms total)
[  PASSED  ] 1 test.
----------------neither WEBRTC_ARCH_ARM_NEON nor WEBRTC_DETECT_ARM_NEON defined-------------------------------Init SPL to C---------------
<end of output>
Test time =  11.22 sec

**Comment by sebkraemer** [comment]
My guess is that was in the global test setup or teardown.

What is the bug here? The issue I see is that, for clarity, the setup and teardown could maybe log their execution times. That could be tagges as _improvement_.

**Comment by derekmauro** [comment]
We can't look into this without complete reproduction instructions.
