### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by richardtop** [google/googletest#3426]
**Describe the bug**

Does the Googletest support Swift Package Manager? As of right now, I've been able to find the only reference to it in this firebase ticket: https://github.com/firebase/firebase-ios-sdk/projects/1#card-43223176

**What operating system and version are you using?**

macOS 11

**What compiler and version are you using?**

```
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**What build system are you using?**

Swift Package Manager, Xcode 12

**Comment by derekmauro** [comment]
The GoogleTest owners do not manage 3rd-party packages or package managers. Others are free to package GoogleTest.
