### ISSUE TITLE
The test has only the beginning, not the end

### ISSUE THREAD

**Issue by yangaynjie** [google/googletest#3430]
My source code is embedded code based on ARM 48x, because GTEST can not be compiled with armcl, I will be able to use GCC, G + + to compile the code for unit testing. The compiler passed, but the test could not run completely. What is the reason?

compile output：
-------------------
C:\Users\yyj\workspace_v8\RM48x_loop2\RM48x\demo-app>scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
gcc -o source\led.o -c -fprofile-arcs -ftest-coverage -ggdb -Wall -fprofile-arcs -ftest-coverage -fmessage-length=0 -I .\include -I ..\HALCOGen\include -I C:\Users\yyj\Desktop\CCS_CI2021\googletest-master\googletest\include source\led.c
g++ -o test\ledtest.o -c -ggdb -Wall -fprofile-arcs -ftest-coverage -fmessage-length=0 -I .\include -I ..\HALCOGen\include -I C:\Users\yyj\Desktop\CCS_CI2021\googletest-master\googletest\include test\ledtest.cpp
gcc -o C:\Users\yyj\workspace_v8\RM48x_loop2\RM48x\HALCOGen\source\het.o -c -fprofile-arcs -ftest-coverage -ggdb -Wall -fprofile-arcs -ftest-coverage -fmessage-length=0 -I .\include -I ..\HALCOGen\include -I C:\Users\yyj\Desktop\CCS_CI2021\googletest-master\googletest\include C:\Users\yyj\workspace_v8\RM48x_loop2\RM48x\HALCOGen\source\het.c
g++ -o arm48.exe -fprofile-arcs -ftest-coverage source\led.o test\ledtest.o C:\Users\yyj\workspace_v8\RM48x_loop2\RM48x\HALCOGen\source\het.o -LC:\Users\yyj\Desktop\CCS_CI2021\googletest-master\googletest -lgtest -lpthread
scons: done building targets.

C:\Users\yyj\workspace_v8\RM48x_loop2\RM48x\demo-app>arm48.exe
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from SuiteTestSampl
TestCase event0 : start
[ RUN      ] SuiteTestSampl.LedTurnOff
[       OK ] SuiteTestSampl.LedTurnOff (0 ms)
[ RUN      ] SuiteTestSampl.LedTurnOn        /*Where is the issues，Because the test did not end, the export of the XML report also failed */
C:\Users\yyj\workspace_v8\RM48x_loop2\RM48x\demo-app>

My Test:

TEST_F(SuiteTestSampl, LedTurnOn)
{
    EXPECT_EQ(17,LedTurnOn(17));
    //EXPECT_NE(6,LedTurnOn(6));
}

My source: //Open Led 

enum LED_NUM{

    D3=17,
    D4=31,
    D5=00,
    D6=25,
    D7=18,
    D8=29,
    LED1=27,
    LED2=05
};
int LedTurnOn(int port){

    switch(port){

    case D3:
         hetREG1->DOUT      = 0 | (1 << D3);
         return port;
    case D4:
         hetREG1->DOUT      = 0 | (1 << D4);
        return port;
    case D5:
         hetREG1->DOUT      = 0 | (1 << D5);
        return port;
    case D6:
         hetREG1->DOUT      = 0 | (1 << D6);
        return port;
    case D7:
         hetREG1->DOUT      = 0 | (1 << D7);
         return port;
    case D8:
         hetREG1->DOUT      = 0 | (1 << D8);
        return port;
    case LED1:
         hetREG1->DOUT      = 0 | (1 << LED1);
        return port;
    case LED2:
         hetREG1->DOUT      = 0 | (1 << LED2);
        return port;

    default:
        return 0;
    }

}

**Comment by derekmauro** [comment]
Did your program crash? We can't look into this without complete reproduction instructions.

**Comment by yangaynjie** [comment]
My program can be compiled normally by using scons. I only compile the source code files related to the test code

**Comment by derekmauro** [comment]
It is not clear from the instructions exactly how to reproduce this issue. Please provide *all* code, OS and compiler information, etc.
