### ISSUE TITLE
googletest/generated no added to gitignore

### ISSUE THREAD

**Issue by fgr-17** [google/googletest#3431]
**Describe the bug**

Every time I run cmake on the parent folder, there's a new untracked folder inside the /googletest folder called "googletest/generated".
I think this folder should be ignored by the googletest .gitignore file

**Steps to reproduce the bug**

Add googletest as a submodule of the parent repository.
Add googletest as a CMake subdirectory like this:
`add_subdirectory(googletest)
`
Run cmake on the parent folder 
Then run git status on the parent folder. You should see something like this:

`modified:     googletest (untracked content)`

Enter into googletest folder and run git status. You should see something like this:
```

Untracked files:
           googletest/generated/
```

**Does the bug persist in the most recent commit?**

Yes

**What operating system and version are you using?**

Linux Mint 19
```

 uname -a
Linux froux 4.15.0-143-generic #147-Ubuntu SMP Wed Apr 14 16:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**What compiler and version are you using?**

I'm using CMake and g++

**What build system are you using?**
```

cmake --version
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Additional context**

-

**Comment by derekmauro** [comment]
CMake recommends using out-of-source builds instead so this doesn't happen: https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#cmake-does-not-generate-a-make-distclean-target-why

For example:
```
mkdir googletest build && cd googletest-build
cmake /path/to/googletest
make
```

If you really want to use in-source builds, you can set your own global gitignore
https://docs.github.com/en/github/getting-started-with-github/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer

**Comment by fgr-17** [comment]
ok, so cmake should always run from a separated folder to keep the repo clean.
thanks
