### ISSUE TITLE
This project is abandoned?

### ISSUE THREAD

**Issue by paulo-coutinho** [google/googletest#3432]
Hi,

This project is abandoned?

We will have a new version?

Thanks.

**Comment by derekmauro** [comment]
A new version is coming soon, but we recommend just using the latest commit if possible.

**Comment by paulo-coutinho** [comment]
Ok, thanks @derekmauro for the answer.

**Comment by paulo-coutinho** [comment]
Im using it here:
https://github.com/ezored/ezored

For auto tests. Nice library.

**Comment by paulo-coutinho** [comment]
I made a pull request to conan with the new version:
https://github.com/conan-io/conan-center-index/pull/5892

Thanks.
