### ISSUE TITLE
Google death tests without message

### ISSUE THREAD

**Issue by Silicomancer** [google/googletest#3435]
**Describe the bug**

AFAIK death test macros like EXPECT_DEBUG_DEATH have a second parameter ("matcher") which is a regex string that is compared to whatever has been printed to stderr before the test finishes by death of the process. However I do not get any message, "Actual msg" in the test output is always empty.

**Steps to reproduce the bug**

Please run the following snippet:

```
TEST(MyDeathTests, MyDeathTest)
{
   EXPECT_DEBUG_DEATH({ assert(false); }, "");
   EXPECT_DEBUG_DEATH({ fprintf(stderr, "Bye\n"); fflush(stderr); exit(1); }, "");
   EXPECT_DEBUG_DEATH({ std::cerr << "Darn" << std::endl << std::flush; std::abort(); }, "");
}

```
All tests succeed for me. But they should fail due to empty matchers. When using non-empty matchers, I can see the prints (e.g. "[  DEATH   ] Bye") but "Actual msg" is empty according to the results printed to the console.

**Does the bug persist in the most recent commit?**

Yes.

**What operating system and version are you using?**

Kubuntu 20.04.

**What compiler and version are you using?**

GCC 10.2

**What build system are you using?**

qmake

**Comment by sbenzaquen** [comment]
The second parameter is a partial regex. The empty string is a regex that matches everything.

**Comment by Silicomancer** [comment]
Ok, I see. I guess I skipped this in the documentation. (can't check if it is actually written there since the website is down for me currently).

Probably I just understood another problem of mine. When replacing the matchers by something random (like "x") it thought it displays an empty "Actual msg" line like this:

```
[----------] 1 test from MyDeathTest
[ RUN      ] MyDeathTest.MyDeathTest
../Tests.hpp:62: Failure
Death test: { fprintf(stderr, "Bye"); fflush(stderr); exit(999); }
    Result: died but not with expected error.
  Expected: contains regular expression "x"
Actual msg:
[  DEATH   ] Bye
[  FAILED  ] MyDeathTest.MyDeathTest (224 ms)
[----------] 1 test from MyDeathTest (224 ms total)
```
But now I guess it doesn't. I suppose it just adds a line break after "Actual msg:" followed by a "[ DEATH   ]" which made me think there is no text after "Actual msg:" and the "Bye" line would be the un-cought error output on the console.

Is it just me or could it be that this formatting is a bit mistakable?

Anyway, I guess the error(s) where on my side. Thanks a lot for helping!
