### ISSUE TITLE
Not able to open documentation google.github.io/googletest/

### ISSUE THREAD

**Issue by atulmangat** [google/googletest#3436]
I'm not able to access the documentation page for the google test 
<img width="759" alt="Screenshot 2021-06-09 at 10 59 02 AM" src="https://user-images.githubusercontent.com/23705245/121298557-b730fc80-c911-11eb-8488-0b072f007ce3.png">

**Comment by ericschmidtatwork** [comment]
We're investigating - in the meantime, as a workaround, you can view the docs in the repository at https://github.com/google/googletest/tree/master/docs

**Comment by ericschmidtatwork** [comment]
https://google.github.io/googletest should be available again.
