### ISSUE TITLE
Is it possible to integrate mprotect into googletest to make mock non-virtual function easier?

### ISSUE THREAD

**Issue by impvd** [google/googletest#3441]
**Does the feature exist in the most recent commit?**

No

**Why do we need this feature?**

As the example I posted in [SO](https://stackoverflow.com/questions/67934510/how-to-mock-non-virtual-methods-in-concrete-classes-using-gmock), we have tons of production code which define dependencies as local variables(And basically 99% of them are non-virtual function).

That means if we want to use googletest to mock it and test, we must refractor the production code first to make them templates. And it kind of impossible to do that refractor on a 10 years+ code base.

Just extended [donsoft.io's example](http://donsoft.io/gmock-presentation/#/3/16), the minimal test case would look like:

<img src="https://user-images.githubusercontent.com/37371804/121756852-2004b880-cb4e-11eb-98b9-e617f6314a2a.png" width="300">

coinflipper.cc:

```c
#include "coinflipper.h"
#include <iostream>

CoinFlipper::CoinFlipper() {}

CoinFlipper::Result CoinFlipper::flipCoin() const {
  Rng d_rng;
  const double val = d_rng.generate(0.0, 1.0);
  return (val < 0.5) ? HEADS : TAILS;
}

int main(int argc, char** argv) {
  CoinFlipper cf;
  CoinFlipper::Result res = cf.flipCoin();
  if (res == 0) {
      std::cout << "head" << std::endl;
  } else {
      std::cout << "tail" << std::endl;
  }
  return 0;
}
```

coinflipper.h:

```c
#include "rng.h"

class CoinFlipper {
 public:
  enum Result { HEADS = 0, TAILS = 1 };

  explicit CoinFlipper();
  Result flipCoin() const;
};
```

rng.h:

```c
#ifndef RNG_H
#define RNG_H
class Rng {
 public:
  Rng() {};
  ~Rng() {};
  double generate(double min, double max);
};
#endif
```

rng.cc:

```c
#include "rng.h"

double Rng::generate(double min, double max) {    
    return 0.75; //Just for test
}
```

**Describe the proposal**

There're existing solutions like [typemock](https://www.typemock.com/) and [vesavlad/easymock](https://github.com/vesavlad/easymock) (not the easymock/easymock), and easymock is open source.

According to its source code, it use [mprotect](https://github.com/vesavlad/easymock/blob/c81ab881fc1831afb0511dba2dfe391b5bdcc4fa/posix/runtime_patch_impl.h) to hook the system API.

**Is the feature specific to an operating system, compiler, or build system version?**
No

**Comment by derekmauro** [comment]
We don't have any plans to implement this.
