### ISSUE TITLE
Issue with fused version of googletest v.1.11.0

### ISSUE THREAD

**Issue by bindhi06** [google/googletest#3444]
**Unit_test compilation issue with googletest v.1.11.0**

This issue was not seen with v.1.10.0

**Steps to reproduce the bug**

Used fused version of googletest with 3 files in OUTPUT_DIR.
make unit_test is throwing build errors

**Does the bug persist in the most recent commit?**

yes

**What operating system and version are you using?**

CentOS Linux release 7.8.2003 (Core)

**What compiler and version are you using?**

gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

**What build system are you using?**

cmake version 3.12.3

**Additional context**

Please find the build errors-
In file included from googletest/gmock-gtest-all.cpp:38:0:
googletest/gtest/gtest.h: In static member function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined()’:
googletest/gtest/gtest.h:6495:12: error: ‘is_trivially_copy_constructible’ is not a member of ‘std’
            std::is_trivially_copy_constructible<M>::value &&
            ^
googletest/gtest/gtest.h:6495:50: error: expected primary-expression before ‘>’ token
            std::is_trivially_copy_constructible<M>::value &&
                                                  ^
googletest/gtest/gtest.h:6495:51: error: ‘::value’ has not been declared
            std::is_trivially_copy_constructible<M>::value &&
                                                   ^
googletest/gmock-gtest-all.cpp: In member function ‘bool testing::internal::FilePath::FileOrDirectoryExists() const’:
googletest/gmock-gtest-all.cpp:10084:31: error: missing initializer for member ‘stat::st_dev’ [-Werror=missing-field-initializers]
   posix::StatStruct file_stat{};
                               ^
googletest/gmock-gtest-all.cpp:10084:31: error: missing initializer for member ‘stat::st_ino’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10084:31: error: missing initializer for member ‘stat::st_nlink’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10084:31: error: missing initializer for member ‘stat::st_mode’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10084:31: error: missing initializer for member ‘stat::st_uid’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10084:31: error: missing initializer for member ‘stat::st_gid’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10084:31: error: missing initializer for member ‘stat::__pad0’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10084:31: error: missing initializer for member ‘stat::st_rdev’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10084:31: error: missing initializer for member ‘stat::st_size’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10084:31: error: missing initializer for member ‘stat::st_blksize’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10084:31: error: missing initializer for member ‘stat::st_blocks’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10084:31: error: missing initializer for member ‘stat::st_atim’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10084:31: error: missing initializer for member ‘stat::st_mtim’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10084:31: error: missing initializer for member ‘stat::st_ctim’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10084:31: error: missing initializer for member ‘stat::__unused’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp: In member function ‘bool testing::internal::FilePath::DirectoryExists() const’:
googletest/gmock-gtest-all.cpp:10111:31: error: missing initializer for member ‘stat::st_dev’ [-Werror=missing-field-initializers]
   posix::StatStruct file_stat{};
                               ^
googletest/gmock-gtest-all.cpp:10111:31: error: missing initializer for member ‘stat::st_ino’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10111:31: error: missing initializer for member ‘stat::st_nlink’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10111:31: error: missing initializer for member ‘stat::st_mode’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10111:31: error: missing initializer for member ‘stat::st_uid’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10111:31: error: missing initializer for member ‘stat::st_gid’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10111:31: error: missing initializer for member ‘stat::__pad0’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10111:31: error: missing initializer for member ‘stat::st_rdev’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10111:31: error: missing initializer for member ‘stat::st_size’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10111:31: error: missing initializer for member ‘stat::st_blksize’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10111:31: error: missing initializer for member ‘stat::st_blocks’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10111:31: error: missing initializer for member ‘stat::st_atim’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10111:31: error: missing initializer for member ‘stat::st_mtim’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10111:31: error: missing initializer for member ‘stat::st_ctim’ [-Werror=missing-field-initializers]
googletest/gmock-gtest-all.cpp:10111:31: error: missing initializer for member ‘stat::__unused’ [-Werror=missing-field-initializers]
In file included from googletest/gmock-gtest-all.cpp:38:0:
googletest/gtest/gtest.h: In instantiation of ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = const std::basic_string<char>&]’:
googletest/gtest/gtest.h:6499:58:   required from ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = const testing::MatcherInterface<const std::basic_string<char>&>*&; T = const std::basic_string<char>&]’
googletest/gtest/gtest.h:6373:14:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U>*) [with U = const std::basic_string<char>&; T = const std::basic_string<char>&]’
googletest/gtest/gtest.h:6597:55:   required from here
googletest/gtest/gtest.h:6497:3: error: body of constexpr function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = const std::basic_string<char>&]’ not a return-statement
   }
   ^
googletest/gtest/gtest.h: In instantiation of ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = const testing::MatcherInterface<const std::basic_string<char>&>*&; T = const std::basic_string<char>&]’:
googletest/gtest/gtest.h:6373:14:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U>*) [with U = const std::basic_string<char>&; T = const std::basic_string<char>&]’
googletest/gtest/gtest.h:6597:55:   required from here
googletest/gtest/gtest.h:6499:58: error: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = const std::basic_string<char>&]’ called in a constant expression
   template <typename M, bool = MatcherBase::IsInlined<M>()>
                                                          ^
googletest/gtest/gtest.h:6493:25: note: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = const std::basic_string<char>&]’ is not usable as a constexpr function because:
   static constexpr bool IsInlined() {
                         ^
googletest/gtest/gtest.h:6544:35: note: in template argument for type ‘bool’
     using Policy = ValuePolicy<MM>;
                                   ^
googletest/gtest/gtest.h: In instantiation of ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = std::basic_string<char>]’:
googletest/gtest/gtest.h:6499:58:   required from ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = const testing::MatcherInterface<const std::basic_string<char>&>*&; T = std::basic_string<char>]’
googletest/gtest/gtest.h:6373:14:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U>*) [with U = const std::basic_string<char>&; T = std::basic_string<char>]’
googletest/gtest/gtest.h:6619:48:   required from here
googletest/gtest/gtest.h:6497:3: error: body of constexpr function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = std::basic_string<char>]’ not a return-statement
   }
   ^
googletest/gtest/gtest.h: In instantiation of ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = const testing::MatcherInterface<const std::basic_string<char>&>*&; T = std::basic_string<char>]’:
googletest/gtest/gtest.h:6373:14:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U>*) [with U = const std::basic_string<char>&; T = std::basic_string<char>]’
googletest/gtest/gtest.h:6619:48:   required from here
googletest/gtest/gtest.h:6499:58: error: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = std::basic_string<char>]’ called in a constant expression
   template <typename M, bool = MatcherBase::IsInlined<M>()>
                                                          ^
googletest/gtest/gtest.h:6493:25: note: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<const std::basic_string<char>&>*; T = std::basic_string<char>]’ is not usable as a constexpr function because:
   static constexpr bool IsInlined() {
                         ^
googletest/gtest/gtest.h:6544:35: note: in template argument for type ‘bool’
     using Policy = ValuePolicy<MM>;
                                   ^
googletest/gtest/gtest.h: In instantiation of ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<std::basic_string<char> >*; T = std::basic_string<char>]’:
googletest/gtest/gtest.h:6499:58:   required from ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = const testing::MatcherInterface<std::basic_string<char> >*&; T = std::basic_string<char>]’
googletest/gtest/gtest.h:6373:14:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U>*) [with U = std::basic_string<char>; T = std::basic_string<char>]’
googletest/gtest/gtest.h:6621:48:   required from here
googletest/gtest/gtest.h:6497:3: error: body of constexpr function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<std::basic_string<char> >*; T = std::basic_string<char>]’ not a return-statement
   }
   ^
googletest/gtest/gtest.h: In instantiation of ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = const testing::MatcherInterface<std::basic_string<char> >*&; T = std::basic_string<char>]’:
googletest/gtest/gtest.h:6373:14:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(const testing::MatcherInterface<U>*) [with U = std::basic_string<char>; T = std::basic_string<char>]’
googletest/gtest/gtest.h:6621:48:   required from here
googletest/gtest/gtest.h:6499:58: error: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<std::basic_string<char> >*; T = std::basic_string<char>]’ called in a constant expression
   template <typename M, bool = MatcherBase::IsInlined<M>()>
                                                          ^
googletest/gtest/gtest.h:6493:25: note: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = const testing::MatcherInterface<std::basic_string<char> >*; T = std::basic_string<char>]’ is not usable as a constexpr function because:
   static constexpr bool IsInlined() {
                         ^
googletest/gtest/gtest.h:6544:35: note: in template argument for type ‘bool’
     using Policy = ValuePolicy<MM>;
                                   ^
googletest/gtest/gtest.h: In instantiation of ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = const std::basic_string<char>&]’:
googletest/gtest/gtest.h:6499:58:   required from ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = const std::basic_string<char>&]’
googletest/gtest/gtest.h:6379:28:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-2-2> = void; T = const std::basic_string<char>&]’
googletest/gtest/gtest.h:6602:69:   required from ‘testing::Matcher<const std::basic_string<char>&>::Matcher(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-1-2> = void]’
googletest/gmock-gtest-all.cpp:10282:68:   required from here
googletest/gtest/gtest.h:6497:3: error: body of constexpr function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = const std::basic_string<char>&]’ not a return-statement
   }
   ^
googletest/gtest/gtest.h: In instantiation of ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = const std::basic_string<char>&]’:
googletest/gtest/gtest.h:6379:28:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-2-2> = void; T = const std::basic_string<char>&]’
googletest/gtest/gtest.h:6602:69:   required from ‘testing::Matcher<const std::basic_string<char>&>::Matcher(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-1-2> = void]’
googletest/gmock-gtest-all.cpp:10282:68:   required from here
googletest/gtest/gtest.h:6499:58: error: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = const std::basic_string<char>&]’ called in a constant expression
   template <typename M, bool = MatcherBase::IsInlined<M>()>
                                                          ^
googletest/gtest/gtest.h:6493:25: note: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = const std::basic_string<char>&]’ is not usable as a constexpr function because:
   static constexpr bool IsInlined() {
                         ^
googletest/gtest/gtest.h:6544:35: note: in template argument for type ‘bool’
     using Policy = ValuePolicy<MM>;
                                   ^
googletest/gtest/gtest.h: In instantiation of ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’:
googletest/gtest/gtest.h:6499:58:   required from ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’
googletest/gtest/gtest.h:6379:28:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-2-2> = void; T = std::basic_string<char>]’
googletest/gtest/gtest.h:6626:62:   required from ‘testing::Matcher<std::basic_string<char> >::Matcher(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-1-2> = void]’
googletest/gmock-gtest-all.cpp:10292:61:   required from here
googletest/gtest/gtest.h:6497:3: error: body of constexpr function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’ not a return-statement
   }
   ^
googletest/gtest/gtest.h: In instantiation of ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’:
googletest/gtest/gtest.h:6379:28:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-2-2> = void; T = std::basic_string<char>]’
googletest/gtest/gtest.h:6626:62:   required from ‘testing::Matcher<std::basic_string<char> >::Matcher(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-1-2> = void]’
googletest/gmock-gtest-all.cpp:10292:61:   required from here
googletest/gtest/gtest.h:6499:58: error: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’ called in a constant expression
   template <typename M, bool = MatcherBase::IsInlined<M>()>
                                                          ^
googletest/gtest/gtest.h:6493:25: note: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’ is not usable as a constexpr function because:
   static constexpr bool IsInlined() {
                         ^
googletest/gtest/gtest.h:6544:35: note: in template argument for type ‘bool’
     using Policy = ValuePolicy<MM>;
                                   ^

**Comment by dinord** [comment]
GoogleTest only [supports gcc >= 5.0](https://google.github.io/googletest/platforms.html#compilers) -- `std:: is_trivially_copy_constructible` is only available with newer versions of gcc.

Please upgrade your compiler or continue using the previous version of GoogleTest.
