### ISSUE TITLE
Gtest's output has no color when running in kitty

### ISSUE THREAD

**Issue by ItsNilDev** [google/googletest#3455]
**Describe the bug**
when I compiled the test.cpp file with `g++ test.cpp -lgtest`, the output of that has no color when I ran it with `./a.out` (on kitty) but it does have color when running in konsole. Kitty itself can show colors in the terminal. I tested with `-fdiagnostics-color=always` too but I had no luck.

**Steps to reproduce the bug**
compile the program.
run it in kitty.

**What operating system and version are you using?**
Latest Arch linux with `Linux 5.10.43-1-lts`

**What compiler and version are you using?**
```Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.1.0 (GCC) 
```

**Comment by derekmauro** [comment]
Thank you for reporting this. This isn't something we are likely to fix ourselves, but it can probably fixed with a simple PR. We would accept such a request.

**Comment by ItsNilDev** [comment]
You're basically asking me to fix this myself, I have no idea what's going on, on this repo.

**Comment by logan-lieou** [comment]
Interesting, this probably has to do with the way kitty handles the output, because other terminals work fine, I tested on kitty and it's bugged for some reason.

How to solve this is probably
1. determine the terminal is kitty
2. output the test differently because kitty doesn't handle the colors correctly?

idk seems mostly like kitty is probably bugged here.

**Comment by lekcyjna123** [comment]
Hi,
kitty work fine with coloring output, after change TERM variable or using `--gtest_color=yes`. By default kitty use:
```
TERM=xterm-kitty
```
And in such case to have colored output from gtest we have to use `--gtest_color=yes`. 

To have it working with `--gtest_color=auto` tests should be run with different TERM variable:
```
TERM=xterm-256color ./gtestTest
```

**Comment by vmiheer** [comment]
Similar issue with Alacritty. I wonder if better (non-standard) option is to depend on `COLORTERM` environment variable similar to how [emacs does](https://www.gnu.org/software/emacs/manual/html_node/efaq/Colors-on-a-TTY.html)? There is long thread about pros/cons of `COLORTERM` in [windows terminal discussion](https://github.com/microsoft/terminal/issues/11057) but the argument is on same line as why cmake is defacto build system for c++ (loads of projects use it).
