### ISSUE TITLE
Weird timeout looking for tests at linking

### ISSUE THREAD

**Issue by ericoporto** [google/googletest#3475]
Building a project on MacOS Catalina, using CMake, I occasionally get an error while linking

https://cirrus-ci.com/task/4940341838086144?logs=build#L3755
```
[ 43%] Linking CXX executable common_test
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.20/Modules/GoogleTestAddTests.cmake:77 (message):
  Error running test executable.
    Path: '/private/var/folders/wh/z5_y2cv53sg24tzvtw_f_y1m0000gn/T/cirrus-ci-build/build_12.2_release/Common/common_test'
    Result: Process terminated due to timeout
    Output:
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.20/Modules/GoogleTestAddTests.cmake:173 (gtest_discover_tests_impl)

```

I am using this googletest: https://github.com/google/googletest/archive/4ec4cd23f486bf70efcc5d2caa40f24368f752e3.tar.gz
Googletest commit: 4ec4cd23f486bf70efcc5d2caa40f24368f752e3
CMake: 3.20.5

Any idea why it's trying to runs tests there? And sometimes I don't get this error, I can't yet understand why. 

I build everything in a step and will only call ctest later, so it's a weird error.

My guess is it's something related to LTO (when it happens it's on release builds, I do have release builds where it doesn't happen but it didn't happen in my non-LTO debug builds)

Edit: I used a flag to avoid LTO when building test runners and it seems to work.

**Comment by hyukmyeong** [comment]
Hello,

I'm not sure but error log come from cmake module below
As you know the log in question was from B, not A
https://github.com/Kitware/CMake/blob/master/Modules/GoogleTestAddTests.cmake#L75

How about using `add_test()` or `gtest_add_tests()` to see if the same issue occurs?

**Comment by ericoporto** [comment]
I gave up using this and went back to the old `gtest_add_tests(TARGET my_test)`, it really wasn't reliable in MacOS.

**Comment by derekmauro** [comment]
It sounds like you resolved the issue. If not, please re-open.

**Comment by ahsonkhan** [comment]
We see this error on Mac and other OSes as well (like Windows), from time to time.

Is there a workaround for it? I am not sure if it will help, but is there a way we can increase `TEST_DISCOVERY_TIMEOUT`?

https://github.com/Azure/azure-sdk-for-cpp/issues/1607#issuecomment-961458426

**Comment by MichaelGoulding** [comment]
I'm still seeing this happen.  It doesn't look like the issue was every resolved. @derekmauro

**Comment by ericoporto** [comment]
I resolved by going back to `gtest_add_tests`, like this:
- https://github.com/adventuregamestudio/ags/blob/538e9072b03b0441853ac0022d17f8990065f8de/Engine/CMakeLists.txt#L655
- https://github.com/adventuregamestudio/ags/blob/538e9072b03b0441853ac0022d17f8990065f8de/Compiler/CMakeLists.txt#L104
- https://github.com/adventuregamestudio/ags/blob/538e9072b03b0441853ac0022d17f8990065f8de/Common/CMakeLists.txt#L248

**Comment by ahsonkhan** [comment]
This doc seems to suggest using the newer `gtest_discover_tests` instead of `gtest_add_tests` has benefits: https://cmake.org/cmake/help/latest/module/GoogleTest.html

I can try the same workaround as you, @ericoporto, to see if that resolves the issue. However, I am hoping the issue with `gtest_discover_tests` itself can be fixed (unless I am using it wrong, and need to explicitly pass-in a longer timeout somehow).

https://github.com/Azure/azure-sdk-for-cpp/issues/1607#issuecomment-1252630726

**Comment by Kirchesch** [comment]
This problem is still happening btw

**Comment by geoff-m** [comment]
This Cmake failure appeared for me when I added C++ code that threw an uncaught exception during static initialization. Although it is reported as a timeout, it seems to have nothing to do with time, as the "timeout" is reported pretty much instantly (after maybe 1 second?) regardless of the value of `DISCOVERY_TIMEOUT`. Replacing `gtest_discover_tests` with `gtest_add_tests` allowed the build to succeed again, allowing me to debug my app.

**Comment by Youw** [comment]
Seeing the same issue.
But I believe that is a CMake/CTest issue.
A workaround that works for me is to set `DISCOVERY_MODE PRE_TEST` parameter for `gtest_discover_tests`. It changes the default behavior a bit, but it is more convenient anyway.
