### ISSUE TITLE
Found it's OK with `underscores (_)` in the TestSuiteName and TestName.

### ISSUE THREAD

**Issue by SunChenAtGitHub** [google/googletest#3488]
**Describe the bug**

There's a description in the `Testing Reference`
`Both arguments TestSuiteName and TestName must be valid C++ identifiers and must not contain underscores (_).`
But I have tried several time and found it's OK with `underscores (_)` in the TestSuiteName and TestName.
Is that something wrong?

**Steps to reproduce the bug**

Any test case.

**Does the bug persist in the most recent commit?**

Yes

**What operating system and version are you using?**

Mac Os Big Sur

**What compiler and version are you using?**

clang --version
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**What build system are you using?**

cmd line

**Additional context**

No

**Comment by apcountryman** [comment]
https://github.com/google/googletest/blob/master/docs/faq.md#why-should-test-suite-names-and-test-names-not-contain-underscore explains why `TestSuiteName` and `TestName` shouldn't contain underscores.

**Comment by derekmauro** [comment]
There is no enforcement that underscores should not be used, but the docs provide the rationale.
