### ISSUE TITLE
extra semi-colons on flag declarations

### ISSUE THREAD

**Issue by dominichamon** [google/googletest#3491]
**Describe the bug**

build against googletest with `-pedantic`.

**Steps to reproduce the bug**

https://github.com/google/benchmark/issues/1202

when the flag declaration was put into the `testing` namespace, all the callsites should have been updated to remove the extra semi-colon.

**Does the bug persist in the most recent commit?**
yes

**What operating system and version are you using?**

https://github.com/google/benchmark/actions/runs/1044548579

ubuntu (various)

**What compiler and version are you using?**

g++ (default for ubuntu)

**What build system are you using?**

cmake 3.18.4 but that's irrelevant :)

**Additional context**

**Comment by marehr** [comment]
Fixed by 2d924d7a971e9667d76ad09727fb2402b4f8a1e3
