### ISSUE TITLE
AddressSanitizer:DEADLYSIGNAL

### ISSUE THREAD

**Issue by uniontech-hj** [google/googletest#3495]
**Describe the bug**

********* Start testing of QTestMain *********
Config: Using QtTest library 5.11.3, Qt 5.11.3 (arm64-little_endian-lp64 shared (dynamic) release build; by GCC 8.3.0)
PASS   : QTestMain::initTestCase()
[==========] Running 83 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 83 tests from Application

AddressSanitizer:DEADLYSIGNAL
=================================================================
==14818==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0xffffcf94cfe0 sp 0xffffcf94cfe0 T0)
==14818==Hint: pc points to the zero page.                                                                                                                                                                           
==14818==The signal is caused by a READ memory access.
==14818==Hint: address points to the zero page.

**Steps to reproduce the bug**
I just run test case.

**Does the bug persist in the most recent commit?**
libgtest-dev version:1.8.1-3

**What operating system and version are you using?**
deepin  linux kernel:4.19.0

**What compiler and version are you using?**
gcc version:8.3.0

**What build system are you using?**
cmake

**Comment by derekmauro** [comment]
Please provide the code so we can reproduce this ourselves.
