### ISSUE TITLE
Failures detected with clang static analyzer

### ISSUE THREAD

**Issue by mcottrell1** [google/googletest#3498]
**Describe the bug**

googletest 1.11+ (I tried up to 96f4ce02a3a78d63981c67acbd368945d11d7d70) fail static analysis when ASSERT/EXPECT_THAT are used with certain matchers. I'm unsure if this is an issue with googletest or an issue with false positives in clang static analyzer.

**Steps to reproduce the bug**

CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.20)

project(googletest-static-analysis-failure)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_subdirectory(googletest)

add_executable(test test.cpp)

target_link_libraries(test
  PRIVATE
    gtest
    gmock
    gmock_main
)
```

test.cpp:
```
#include <gmock/gmock.h>

#include <cstdint>
#include <system_error>
#include <vector>

TEST(StaticAnalysis, uninitializedObjectPointer)
{
    ASSERT_THAT((std::vector<uint8_t>{0, 1, 2, 3}), testing::ElementsAreArray({0, 1, 2, 3}));
}

TEST(StaticAnalysis, potentialMemoryLeak)
{
    testing::internal::MakePredicateFormatterFromMatcher(testing::Eq(std::error_code{}))("test", std::error_code{});
}
```

Reproduction steps:
1. ensure googletest is present in the same dir as CMakeLists.txt
2. `mkdir build && cd build`
3. `scan-build-8 --use-cc=clang-8 --use-c++=clang++-8 cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..`
4. `scan-build-8 --use-cc=clang-8 --use-c++=clang++-8 -o static-analysis ninja`
5. 2 static analysis errors are reported, when zero would be expected.

**Does the bug persist in the most recent commit?**

Yes. I tried release-1.11.0 but it also happens with 96f4ce02a3a78d63981c67acbd368945d11d7d70 (latest at time of writing).

**What operating system and version are you using?**

Ubuntu 18.04.5

**What compiler and version are you using?**

```
Ubuntu clang version 12.0.0-++20210126063813+7c03f7d7d04c-1~exp1~20210126174541.2187
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
```
and
```
clang version 8.0.0-3~ubuntu18.04.2 (tags/RELEASE_800/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
```

**What build system are you using?**

```
cmake version 3.21.0
```

**Additional context**

As mentioned above I don't know if this is actually an issue with googletest or a false positive in the static analyzer.
The generated static analysis report can be found here: [report.tar.gz](https://github.com/google/googletest/files/6870614/report.tar.gz).

**Comment by derekmauro** [comment]
I doubt those are real issues, but that is tricky code that could confuse static analysis. We run this code under sanitizers which are more accurate that static analyzers in our experience.
