### ISSUE TITLE
Init-Statement in if interferes with clang diagnostic pragma.

### ISSUE THREAD

**Issue by drew-gross** [google/googletest#3518]
**Describe the bug**

Due to what appears to be a bug in clang, the following code does not compile with `-Werror -Wshadow -Wshadow-uncaptured-local -std=c++17`:

```
#include <gtest/gtest.h>

#define MACRO(object) \
    _Pragma("clang diagnostic push") \
    _Pragma("clang diagnostic ignored \"-Wshadow\"") \
    _Pragma("clang diagnostic ignored \"-Wshadow-uncaptured-local\"") \
    [&](auto&& object) { return 1; }(object) \
    _Pragma("clang diagnostic pop")

TEST(Shadow, Tests) {
    int a = 1;
    // This one generates an unexpected error
    ASSERT_EQ(MACRO(a), 1);
    // This one doesn't
    int x = MACRO(a);
}
```

**Steps to reproduce the bug**

https://godbolt.org/z/fj35e19ez

**Does the bug persist in the most recent commit?**

Yes

**What operating system and version are you using?**

Linux

**What compiler and version are you using?**

Clang 11

**What build system are you using?**

Bazel (internal fork)

**Additional context**

This appears to be caused by some interaction between macros and the init-statement in `GTEST_ASSERT_`. This patch appears to fix the issue in our codebase:

```
diff --git a/third_party/googletest/googletest/include/gtest/gtest_pred_impl.h b/third_party/googletest/googletest/include/gtest/gtest_pred_impl.h
index d514255c733b..3c8868f3b852 100644
--- a/third_party/googletest/googletest/include/gtest/gtest_pred_impl.h
+++ b/third_party/googletest/googletest/include/gtest/gtest_pred_impl.h
@@ -74,10 +74,13 @@ namespace testing {

 #define GTEST_ASSERT_(expression, on_failure) \
   GTEST_AMBIGUOUS_ELSE_BLOCKER_ \
-  if (const ::testing::AssertionResult gtest_ar = (expression)) \
-    ; \
-  else \
-    on_failure(gtest_ar.failure_message())
+  do { \
+    const ::testing::AssertionResult gtest_ar = (expression); \
+    if (gtest_ar) \
+      ; \
+    else \
+      on_failure(gtest_ar.failure_message()); \
+  } while (0)


 // Helper function for implementing {EXPECT|ASSERT}_PRED1.  Don't use
```

Would you accept this patch if I added a test?

**Comment by derekmauro** [comment]
Hi - yes, we would accept that patch. Thanks.

**Comment by drew-gross** [comment]
Turns out there is a feature I didn't know about where you can do `<<` after an assertion, it doesn't work with this implementation. I wasn't able to find one that does work.
