### ISSUE TITLE
`fuse_gmock_files.py` is broken because of removed dependency

### ISSUE THREAD

**Issue by cz4rs** [google/googletest#3522]
**Describe the bug**

`googlemock/scripts/fuse_gmock_files.py` script is broken because of removed dependency. This was introduced with the commit 47f819c3ca54fb602f432904443e00a0a1fe2f42 (which removes `googletest/scripts/fuse_gtest_files.py`).

Please revert that commit partially or explicitly remove the support for fusing.

**Steps to reproduce the bug**
```
googletest  googlemock  scripts  ./fuse_gmock_files.py
Traceback (most recent call last):
  File "./fuse_gmock_files.py", line 77, in <module>
    import fuse_gtest_files as gtest  # pylint:disable=g-import-not-at-top
ImportError: No module named fuse_gtest_files
```

**Comment by ReneOschmann** [comment]
This got removed with https://github.com/google/googletest/commit/47f819c3ca54fb602f432904443e00a0a1fe2f42

As far as I can see the fusing is also not mentioned in the docu anymore

@derekmauro: Was it intended that also the fuse script got deleted? If so it would make sense to also delete `googlemock/scripts/*`

**Comment by derekmauro** [comment]
Unsupported scripts are being removed. We just haven't gotten around to removing all of them. `fuse_gmock_files.py` will be removed in a followup.

**Comment by derekmauro** [comment]
This is now removed.
