### ISSUE TITLE
Get coverage reports on death tests

### ISSUE THREAD

**Issue by antonromanov1** [google/googletest#3526]
I can't get coverage data using **lcov** and **gcovr** tools on tests which contain `EXPECT_DEATH`. Please provide me a solution for this. Thank you in advance.

**Comment by derekmauro** [comment]
This is going to be tricky. `EXPECT_DEATH` uses `fork()`. https://stackoverflow.com/questions/28408811/how-do-i-generate-coverage-reports-for-forkd-children-using-gcov-lcov suggests that it should be possible to use after `fork()`, but your program is going to have to exit in a controlled way. `EXPECT_DEATH` usually means your program dies in an expected way.

That's just my 5 minute investigation. I don't think we are going to prioritize working on this.
