### ISSUE TITLE
Template Test ,  Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by Zrealshadow** [google/googletest#3540]
**Describe the bug**

I want to test a my own template class, and divide the declaration and definition
 But got some link errors.

> [build] Undefined symbols for architecture x86_64:
[build]   "Ownheap<int>::Ownheap(std::__1::vector<int, std::__1::allocator<int> >&)", referenced from:
[build]       HeapTest_BasicAssertions_Test::TestBody() in heap_test.cc.o
[build]   "Ownheap<int>::~Ownheap()", referenced from:
[build]       HeapTest_BasicAssertions_Test::TestBody() in heap_test.cc.o
[build]   "Ownheap<int>::size() const", referenced from:
[build]       HeapTest_BasicAssertions_Test::TestBody() in heap_test.cc.o

**Steps to reproduce the bug**

Ownheap.cpp
```c++
#ifndef OWNHEAP_H
#define OWNHEAP_H
#pragma once
#include<vector>
#include<string>
template<class T>
class Ownheap  
{	

	public:
		typedef typename std::vector<T>::iterator iterator;
		void display();
		bool empty() const {return c.empty();};
		size_t capacity() const {return c.capacity();};
		size_t size() const { return c.size();};
		void clear() {c.clear();};
		Ownheap(std::vector<T> &);
		
		T pop();
		void push(const T &);
		
		Ownheap();
		~Ownheap();
	
	private:
		std::vector<T> c;
		void __pop_heap(iterator first, iterator last);
		void __init_heap(iterator first, iterator last);
		void __push_heap(iterator first, iterator last);

};

extern template class Ownheap<int>;
extern template class Ownheap<float>;
#endif
```
Ownheap.cpp
I delete some unrelated code
```c++
#include "Ownheap.hpp" 
#include "math.h"
#include "iostream"
template<typename T>
Ownheap<T>::Ownheap()
{
	
}

template<typename T>	
Ownheap<T>::~Ownheap()
{
	c.clear();
}

template<typename T>
Ownheap<T>::Ownheap(std::vector<T> &cc){
    c = cc;
    if(c.size() > 1) {
        __init_heap(c.begin(), c.end());
    }
}
template class Ownheap<int>;
template class Ownheap<float>;

```
CMakeLists.txt under test directory
```cmake
cmake_minimum_required(VERSION 3.0.0)
include_directories(../src/include)
include(FetchContent)
FetchContent_Declare(
  googletest
  URL https://github.com/google/googletest/archive/609281088cfefc76f9d0ce82e1ff6c30cc3591e5.zip
)
# For Windows: Prevent overriding the parent project's compiler/linker settings
set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(googletest)

# message(${CommonSourceCode})
enable_testing()

add_executable(
  heap_test
  heap_test.cc
)

add_executable(
    all_test
    heap_test.cc
)


target_link_libraries(
  heap_test
  gtest_main
)
target_link_libraries(
    all_test
    gtest_main
)

include(GoogleTest)
gtest_discover_tests(
    heap_test
    all_test
)
```
testunit.cc
```c++
#include <gtest/gtest.h>
#include "Ownheap.hpp"
#include "vector"
using OwnheapInt = Ownheap<int>;
TEST(HeapTest, BasicAssertions) {

    std::vector<int> s = {0, 10, 20, 30, 40, 50, 60, 70, 80, 90};
    OwnheapInt v = OwnheapInt(s);

    EXPECT_EQ(v.size(), s.size());
    EXPECT_EQ(0, 0);
}
```

**What operating system and version are you using?**
MacOS  Catelina 10,15,7

**What compiler and version are you using?**

GCC 10,2,0 x86_64-apple-darwin19

**What build system are you using?**

cmake version 3.14.1

**Additional context**

I think I have instantiate the int Ownheap at the end of Ownheap.cpp file.
So if I include Ownheap.hpp, this bug should not happen.
If i include it in main.cpp and run main, there is no error.
However, build error when I run gtest unit

**Comment by asoffer** [comment]
I don't think this is a bug in googletest. Definitions of template functions and member functions of class templates need to be defined in the header file so that any instantiation of the template knows how to instantiate it. This is in general required when working with templates in C++.

**Comment by davidmerwin** [comment]
= )
