### ISSUE TITLE
Add a command line flag to log test start/end markers in both stderr and stdout

### ISSUE THREAD

**Issue by mohitmv** [google/googletest#3547]
**Does the feature exist in the most recent commit?**
No.

**Why do we need this feature?**

The problem: When we run the test in our infra, we pipe the stdout and stderr in 2 different files, so that we can use stdout file for the test summary (how many tests failed, which all passed etc.), and stderr contains the internal logs, printed by main utility, unit test etc.. However the problem with this is, test boundaries are lost in stdout file.  i.e. that `[ RUN      ]`, `[       OK ]` info is not there, because that info is piped in stdout..

Hence, we need a command line option to instruct gtest to log `[ RUN      ]` info in stdout as well as stderr. So that we can read the stdout file for quick history and stderr file for details with clear test boundaries.

**Comment by derekmauro** [comment]
We don't recommend parsing either of these two outputs. The formats may change without notice. GoogleTest can output an XML file that would be much better to use for this purpose.

**Comment by mohitmv** [comment]
we don't parse those test-start / test-end identifier. I was saying, these identifier helps us in knowing the test boundary when a developer is reading a large test output file which contains logs from many tests and many utilities which are being tested. So It helps them identify which tests they are looking. At best, while they are reading the test-output file in a text-editor, they can do Ctrl+F a test name to jump to the place they need to read logs from.
Well, If this sounds ok to you, I'm open to implement it and make a pull request.
