### ISSUE TITLE
Clang-tidy failure on Matcher under c++17

### ISSUE THREAD

**Issue by dfreese** [google/googletest#3553]
Commit c13c27a513ecd1cbf5700a45fe590e85e8ae6770 for googletest (cl/350580998),
started causing issues for us under clang-tidy.  The problem only appears under
C++17, and with a struct that has non-trivial copy-construction.

The following example is the simplest I could come up with:
```cpp
#include "gmock/gmock.h"
#include "gtest/gtest.h"

namespace {

class Value {
 public:
  // Basic constructor to get something with dummy values.
  Value() : value_(42) {}

  // Fails with the non-default constructor, which makes Value
  // non-trivially-copy-constructible
  Value(const Value& sz) : value_(sz.value_) {}
  // Passes if we use the default constructor
  // Value(const Value& sz) = default;

  // Matcher needs a comparison.
  friend bool operator==(const Value& a, const Value& b) {
    return a.value_ == b.value_;
  }

 private:
  int value_;
};

class TestInterface {
 public:
  virtual ~TestInterface() = default;
  virtual void open(Value value) = 0;
};

class MockTestInterface : public TestInterface {
 public:
  MOCK_METHOD(void, open, (Value value), (override));
};

TEST(GtestClangTidyTest, ShowsErrorsUnderCpp17) {
  MockTestInterface mock;

  // Same result with both
  // EXPECT_CALL(mock, open(Value())).Times(0);
  EXPECT_CALL(mock, open(::testing::Eq(Value()))).Times(0);
}

}  // namespace
```

When running:
```bash
clang-tidy-12 '--warnings-as-errors=*' gtest_clangtidy_test.cc -- \
  -std=c++17 \
  -isystem googletest/googlemock/include \
  -isystem googletest/googletest/include
```
The failure that I see is:
> googletest/googlemock/include/gmock/gmock-spec-builders.h:1489:18: error: Potential leak of memory pointed to by field 'shared' [clang-analyzer-cplusplus.NewDeleteLeaks,-warnings-as-errors]
>     MutexLock l(&g_gmock_mutex);
>                  ^
> /home/viz/replicate/gtest_clangtidy_test.cc:41:26: note: Calling constructor for 'Matcher<(anonymous namespace)::Value>'
>   EXPECT_CALL(mock, open(::testing::Eq(Value()))).Times(0);
>                          ^
> googletest/googlemock/include/gmock/gmock-spec-builders.h:2034:48: note: expanded from macro 'EXPECT_CALL'
>   GMOCK_ON_CALL_IMPL_(obj, InternalExpectedAt, call)
>                                                ^
> googletest/googlemock/include/gmock/gmock-spec-builders.h:2026:24: note: expanded from macro 'GMOCK_ON_CALL_IMPL_'
>   ((mock_expr).gmock_##call)(::testing::internal::GetWithoutMatchers(), \
>                        ^
> Suppressed 1 warnings (1 NOLINT).
> 1 warning treated as error

Clang-tidy-12 is used here just to try and grab a modern-ish version of clang-tidy. I was also seeing that on clang-tidy-9.  I was running this on ubuntu 20.04.  I've put the cc file, a script to run this, and a dockerfile to replicate my environment at https://github.com/dfreese/gtest_clangtidy

**Comment by davidmerwin** [comment]
________________________________
From: David Freese ***@***.***>
Sent: Sunday, September 5, 2021 12:18:02 AM
To: google/googletest ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [google/googletest] Clang-tidy failure on Matcher under c++17 (#3553)


Commit c13c27a<https://github.com/google/googletest/commit/c13c27a513ecd1cbf5700a45fe590e85e8ae6770> for googletest (cl/350580998),
started causing issues for us under clang-tidy. The problem only appears under
C++17, and with a struct that has non-trivial copy-construction.

The following example is the simplest I could come up with:

#include "gmock/gmock.h"
#include "gtest/gtest.h"

namespace {

class Value {
 public:
  // Basic constructor to get something with dummy values.
  Value() : value_(42) {}

  // Fails with the non-default constructor, which makes Value
  // non-trivially-copy-constructible
  Value(const Value& sz) : value_(sz.value_) {}
  // Passes if we use the default constructor
  // Value(const Value& sz) = default;

  // Matcher needs a comparison.
  friend bool operator==(const Value& a, const Value& b) {
    return a.value_ == b.value_;
  }

 private:
  int value_;
};

class TestInterface {
 public:
  virtual ~TestInterface() = default;
  virtual void open(Value value) = 0;
};

class MockTestInterface : public TestInterface {
 public:
  MOCK_METHOD(void, open, (Value value), (override));
};

TEST(GtestClangTidyTest, ShowsErrorsUnderCpp17) {
  MockTestInterface mock;

  // Same result with both
  // EXPECT_CALL(mock, open(Value())).Times(0);
  EXPECT_CALL(mock, open(::testing::Eq(Value()))).Times(0);
}

}  // namespace

When running:

clang-tidy-12 '--warnings-as-errors=*' gtest_clangtidy_test.cc -- \
  -std=c++17 \
  -isystem googletest/googlemock/include \
  -isystem googletest/googletest/include

The failure that I see is:

googletest/googlemock/include/gmock/gmock-spec-builders.h:1489:18: error: Potential leak of memory pointed to by field 'shared' [clang-analyzer-cplusplus.NewDeleteLeaks,-warnings-as-errors]
MutexLock l(&g_gmock_mutex);
^
/home/viz/replicate/gtest_clangtidy_test.cc:41:26: note: Calling constructor for 'Matcher<(anonymous namespace)::Value>'
EXPECT_CALL(mock, open(::testing::Eq(Value()))).Times(0);
^
googletest/googlemock/include/gmock/gmock-spec-builders.h:2034:48: note: expanded from macro 'EXPECT_CALL'
GMOCK_ON_CALL_IMPL_(obj, InternalExpectedAt, call)
^
googletest/googlemock/include/gmock/gmock-spec-builders.h:2026:24: note: expanded from macro 'GMOCK_ON_CALL_IMPL_'
((mock_expr).gmock_##call)(::testing::internal::GetWithoutMatchers(),
^
Suppressed 1 warnings (1 NOLINT).
1 warning treated as error

Clang-tidy-12 is used here just to try and grab a modern-ish version of clang-tidy. I was also seeing that on clang-tidy-9. I was running this on ubuntu 20.04. I've put the cc file, a script to run this, and a dockerfile to replicate my environment at https://github.com/dfreese/gtest_clangtidy

**Comment by derekmauro** [comment]
Thank you for reporting this. At the present time I don't think we can prioritize fixing this. Clang-tidy is probably wrong here. The code is complex enough that I can imagine a static checker getting this wrong.

**Comment by ahojnnes** [comment]
Just wanted to call out that we hit the same issue on our end. I already see tons of `NOLINT`s in this file, so I am wondering whether @derekmauro would consider adding a few dedicated NOLINTs to this end as well? I could fix some of these issues and could submit a patch as a PR.

**Comment by dinord** [comment]
Doesn't seem to trigger at head with ClangTidy 14:
```bash
clang-tidy-14 '--warnings-as-errors=*' gtest_clangtidy_test.cc -- \
  -std=c++17 \
  -isystem googletest/googlemock/include \
  -isystem googletest/googletest/include
```

**Comment by dinord** [comment]
We recommend upgrading to newer versions of ClangTidy and googletest instead of patching code. Please re-open if I'm missing something.

**Comment by Maxxus220** [comment]
I run into this same issue using clang-tidy at 18.1.4
