### ISSUE TITLE
ElementsAre not working with C++20 views

### ISSUE THREAD

**Issue by libbooze** [google/googletest#3564]
**Describe the bug**
I know google is still at C++17, but eventually you will move to C++20 so GTest should work with C++20 views. 
Currently ElementsAre does not work with C++20 views.
https://godbolt.org/z/73McMYrG9

**Steps to reproduce the bug**
Uncomment commented line on:
https://godbolt.org/z/73McMYrG9

It's important that we are able to reproduce the problem that you are
experiencing. Please provide all code and relevant steps to reproduce the
problem, including your `BUILD`/`CMakeLists.txt` file and build commands. Links
to a GitHub branch or [godbolt.org](https://godbolt.org/) that demonstrate the
problem are also helpful.

**Does the bug persist in the most recent commit?**

I guess, IDK what godbolt considers trunk

We recommend using the latest commit in the master branch in your projects.

**What operating system and version are you using?**

linux(godbolt)

**What compiler and version are you using?**

not relevant, since I presume bug is in missing support for views, but gcc trunk from godbolt

**What build system are you using?**
commandline(godbolt)

Please include the output of `bazel --version` or `cmake --version`, or the
equivalent for your build system.

**Additional context**

**Comment by asoffer** [comment]
Thanks. Currently, `ElementsAre` requires a `value_type` alias which ranges do not provide. I think we would be open to a PR to remove this constraint, provided it did not change behavior for existing containers.
