### ISSUE TITLE
GoogleTestAddTests.cmake:173 (gtest_discover_tests_impl) when using gmock

### ISSUE THREAD

**Issue by ziccardi** [google/googletest#3565]
**GoogleTestAddTests.cmake:173 (gtest_discover_tests_impl) when using gmock**

My tests were working pretty well until I started using gmock.
Now the test works on Mac and on Linux, but I get a `GoogleTestAddTests.cmake:173 (gtest_discover_tests_impl) when using gmock` when building on windows (Visual Studio 2019)

Complete error:
```
Make Error at C:/Program Files/CMake/share/cmake-3.21/Modules/GoogleTestAddTests.cmake:77 (message):
  Error running test executable.

    Path: 'C:/myproject/build/FlexDBLayerTests/FlexDBLayer_test.exe'
    Result: Exit code 0xc0000135

    Output:


Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/GoogleTestAddTests.cmake:173 (gtest_discover_tests_impl)


NMAKE : fatal error U1077: 'echo' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
```

**Steps to reproduce the bug**

There are my CMakeLists.txt files:

**TOP ONE**
```
cmake_minimum_required(VERSION 3.2.2)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
project(SQLServerClient)

if (${APPLE})
    include_directories("/usr/local/include")
endif ()

enable_testing()

add_subdirectory(FlexDBLayer)
add_subdirectory(FlexDBLayerTests)

```

FlexDBLayer
```
SET(LIBNAME FlexDBLayer)

find_library(
        ODBC
        NAMES odbc32 odbc
)

add_compile_definitions(FLEXDBLAYER_EXPORTS)

include_directories("${CMAKE_SOURCE_DIR}/FlexDBLayer")

add_library(
        ${LIBNAME} SHARED
        ... all the sources
)

target_link_libraries(
        FlexDBLayer PUBLIC ${ODBC}
)
```

FlexDBLayerTests
```
include(FetchContent)
FetchContent_Declare(
        googletest
        URL https://github.com/google/googletest/archive/refs/tags/release-1.11.0.zip
)
# For Windows: Prevent overriding the parent project's compiler/linker settings
set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(googletest)

add_executable(
        FlexDBLayer_test
        ... all the tests sources        
)


target_link_libraries(
        FlexDBLayer_test
        FlexDBLayer
        ${ODBC}
        gtest_main
        gmock_main
)

include(GoogleTest)
gtest_discover_tests(
        FlexDBLayer_test
        MYTEST1_test
        MYTEST2_test
        .... all the tests
)

include_directories("${CMAKE_SOURCE_DIR}/FlexDBLayer")
```

**Does the bug persist in the most recent commit?**

Yes

**What operating system and version are you using?**

* Linux Ubuntu: works
* Linux Alpine: works
* MacOS: works
* Windows 10 + VisualStudio 2019: I get the error described

**What compiler and version are you using?**

Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30040 for x86

**What build system are you using?**

cmake version 3.21.1

**Additional context**

Error happens only on windows and *only since I started using gmock*.

**Comment by hyukmyeong** [comment]
Hello,

From https://github.com/Kitware/CMake/blob/v3.21.0/Modules/GoogleTestAddTests.cmake#L68 ,
`gtest_discover_tests` runs the test binary once to get a list of test cases, and the error seems to have occurred when running it.

I'm not sure but how about checking if it works normally when only the test binary is executed?
`C:/myproject/build/FlexDBLayerTests/FlexDBLayer_test.exe`

It seems that exit code `0xc0000135` should be solved first

**Comment by ziccardi** [comment]
> If I google the exit code `0xc0000135`,
> it says that the required `.dll` is missing or it needs access right to use it
> or the appropriate version of .NET framework is missing in some cases.

In the end the issue was a missing DLL, thank you VERY MUCH!

**Comment by zonmen** [comment]
I have similar problem with gtest_discover_tests function in CMake, Windows OS. You can solve it by set DISCOVERY_MODE option to PRE_TEST.
https://discourse.cmake.org/t/cmake-build-and-test-with-qt-and-google-test/4729
