### ISSUE TITLE
Quiet output

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#358]
```
There is no flag to pass to InitGoogleTest that results in minimal console 
output. Such a flag would tell gtest to only output errors from failed tests, 
the number of tests passed, and the total time elapsed. This flag is necessary 
if one wants to compile all tests into a executable to be run as a post-build 
step.
```

Original issue reported on code.google.com by `mahsm...@gmail.com` on 4 Mar 2011 at 8:41

**Comment by joshkel** [comment]
A couple of semi-standard solutions that have come out since this issue was first raised:

* [This gist](https://gist.github.com/elliotchance/8215283) contains a sample `ConfigurableEventListener` decorator that allows selectively enabling or disabling output types.
* My [Google Test Pretty Printer](https://github.com/joshkel/gtpp) significantly shortens GTest's output.

**Comment by metal4people** [comment]
Still believe this feature should be available out of the box, because there are a lot of tests already written and to achieve the behavior you would need to add listener to all of them.
Instead having commandline option --quite or something like that would be very useful in my opinion.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by metal4people** [comment]
No problem. You know I've found better way to reach my aim.
I think most of people needs the same is to use: --gtest_repeat and --gtest_break_on_failure.
For example: --gtest_repeat=100 --gtest_break_on_failure will run tests 100 times, but once something fails it stop tests execution.
Very convenient.
Thank you guys!

**Comment by gennadiycivil** [comment]
Great to hear. I suggest submitting a patch to the documentation so others
can benefit.
Thanks
G

**Comment by moof2k** [comment]
+1 for this being an out-of-the-box feature
