### ISSUE TITLE
Compilation issue when using class with default constructor with random ranlux on MSVC

### ISSUE THREAD

**Issue by yhmtsai** [google/googletest#3631]
**Describe the bug**

When creating a class with default constructor (not printable with <<), using gtest with creating ranlux throws compliation error.
If the test file does not contain ranlux or use a different random generator, all compilation is passed.

**Steps to reproduce the bug**

I put those codes in https://github.com/yhmtsai/gtest_with_random_on_msvc (failed) with github action
pass without ranlux in https://github.com/yhmtsai/gtest_with_random_on_msvc/commit/7fa86132e09f0cd72e202e7e1d00cfde5e699cda

A dummy class with default constructor and ranlux give the error.

**Does the bug persist in the most recent commit?**

Yes

**What operating system and version are you using?**

Windows 10

**What compiler and version are you using?**

(Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29112 for x64)
or the MSVC compiler in github action

**What build system are you using?**

cmake version 3.16.5

**Additional context**
It may be related to #3311 
Quick workaround for others facing this issue: do not use ranlux48/ranlux24 might help

**Comment by asoffer** [comment]
Thanks so much for bringing this to our attention. This does seem to be the same as #3311 as you mentioned. I'm going to close this bug and continue the discussion there.
