### ISSUE TITLE
Display Disabled Test Names In Verbose Output

### ISSUE THREAD

**Issue by limitedAtonement** [google/googletest#3637]
https://github.com/google/googletest/issues/452 is related, but the current proposal does not include the unrelated "Display test fixture" functionality.

**Does the feature exist in the most recent commit?** no.

Ideally, explain why a combination of existing features cannot be used instead.

We recommend using the latest commit from GitHub in your projects.

:heavy_check_mark: living at HEAD as requested

**Why do we need this feature?**

This feature has shown itself to be desired by the community over the years: 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=497892

https://groups.google.com/g/googletestframework/c/jYGXVcrqsX8

It will help testing quality by, instead of hiding disabled tests behind a message like "YOU HAVE 1527 DISABLED TESTS", a larger list showing which tests exactly are disabled. According to the docs (https://github.com/google/googletest/blob/master/docs/advanced.md):

> This feature should only be used for temporary pain-relief. You still have to fix the disabled tests at a later date. As a reminder, googletest will print a banner warning you if a test program contains any disabled tests.

This "reminder" is more effective when it's harder to ignore.

To my knowledge, there is no existing feature or combination of features to show disabled test names.

**Describe the proposal**

Include a detailed description of the feature, with usage examples.

if `./test` has output like this:

```
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from activateBuildings
[ RUN      ] activateBuildings.pinkMarket
[       OK ] activateBuildings.pinkMarket (0 ms)
[----------] 1 test from activateBuildings (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 1 test.

  YOU HAVE 2 DISABLED TESTS
```

    ./test --gtest_print_disabled_test_names;

would display output like this:

```
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from activateBuildings
[ RUN      ] activateBuildings.pinkMarket
[       OK ] activateBuildings.pinkMarket (0 ms)
[----------] 1 test from activateBuildings (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 1 test.

  YOU HAVE 2 DISABLED TESTS
[ DISABLED ] activateBuildings.DISABLED_fixedPedlar
[ DISABLED ] activateBuildings.DISABLED_marketActsAutomaticallyWithOnlyOneGood
```

(the word `DISABLED` would be the same color as `YOU HAVE ...`) I chose the wording, `--gtest_print_disabled_test_names`, to coordinate with the existing feature flag: `--gtest_print_time=0`.

There are several other conceivable ways to design this functionality, but this seems the simplest to me although I do not have familiarity with the code base. It may be easier to put the `[ DISABLED  ]` test names in line with the `[ RUN   ]` and `[     OK ]` messages.

**Is the feature specific to an operating system, compiler, or build system version?**

no.

If it is, please specify which versions.

**Comment by limitedAtonement** [comment]
@googlebot I signed it!

**Comment by CJ-Johnson** [comment]
Thank you for the feature request. We agree that this would be a reasonable change. We would accept a pull request but cannot prioritize development of the feature ourselves.

**Comment by limitedAtonement** [comment]
Pull request is visible at #3638

**Comment by limitedAtonement** [comment]
Merge request merged.
