### ISSUE TITLE
linux make[1]: *** [googletest/CMakeFiles/gtest.dir/all] Error 2

### ISSUE THREAD

**Issue by ZJolin** [google/googletest#3639]
**Describe the bug**
I'm trying to build gtest and gmock (1.11.0) in linux.
git clone https://github.com/google/googletest.git -b release-1.11.0

**Steps to reproduce the bug**

root/source/googletest/googletest/include/gtest/gtest-matchers.h:412:25: note: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = const std::basic_string<char>&]’ is not usable as a constexpr function because:
   static constexpr bool IsInlined() {
                         ^
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:463:35: note: in template argument for type ‘bool’ 
     using Policy = ValuePolicy<MM>;
                                   ^
/root/source/googletest/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’:
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:418:58:   required from ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:298:28:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-2-2> = void; T = std::basic_string<char>]’
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:545:62:   required from ‘testing::Matcher<std::basic_string<char> >::Matcher(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-1-2> = void]’
/root/source/googletest/googletest/src/gtest-matchers.cc:55:61:   required from here
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:416:3: error: body of constexpr function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’ not a return-statement
   }
   ^
/root/source/googletest/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’:
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:298:28:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-2-2> = void; T = std::basic_string<char>]’
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:545:62:   required from ‘testing::Matcher<std::basic_string<char> >::Matcher(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-1-2> = void]’
/root/source/googletest/googletest/src/gtest-matchers.cc:55:61:   required from here
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:418:58: error: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’ called in a constant expression
   template <typename M, bool = MatcherBase::IsInlined<M>()>
                                                          ^
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:412:25: note: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’ is not usable as a constexpr function because:
   static constexpr bool IsInlined() {
                         ^
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:463:35: note: in template argument for type ‘bool’ 
     using Policy = ValuePolicy<MM>;
                                   ^
make[2]: *** [googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
make[1]: *** [googletest/CMakeFiles/gtest.dir/all] Error 2
make: *** [all] Error 2

**What operating system and version are you using?**
Linux VM-155-224-centos 5.4.119-1-tlinux4-0005 #1 SMP Thu Jul 8 11:20:55 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

**What compiler and version are you using?**
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 

**What build system are you using?**
cmake version 2.8.12.2

**Comment by CJ-Johnson** [comment]
Thank you for the issue report. Unfortunately, GCC 4.8 is not a supported compiler. We suggest upgrading to a newer compiler.

**Comment by ZJolin** [comment]
I have upgraded GCC to 11.2.0, and the problem still occurred.
/root/source/googletest/googletest/src/gtest-matchers.cc:55:61:   required from here
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:416:3: error: body of constexpr function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’ not a return-statement
   }
   ^
/root/source/googletest/googletest/include/gtest/gtest-matchers.h: In instantiation of ‘void testing::internal::MatcherBase<T>::Init(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’:
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:298:28:   required from ‘testing::internal::MatcherBase<T>::MatcherBase(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-2-2> = void; T = std::basic_string<char>]’
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:545:62:   required from ‘testing::Matcher<std::basic_string<char> >::Matcher(M&&) [with M = testing::internal::EqMatcher<std::basic_string<char> >; <template-parameter-1-2> = void]’
/root/source/googletest/googletest/src/gtest-matchers.cc:55:61:   required from here
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:418:58: error: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’ called in a constant expression
   template <typename M, bool = MatcherBase::IsInlined<M>()>
                                                          ^
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:412:25: note: ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined() [with M = testing::internal::EqMatcher<std::basic_string<char> >; T = std::basic_string<char>]’ is not usable as a constexpr function because:
   static constexpr bool IsInlined() {
                         ^
/root/source/googletest/googletest/include/gtest/gtest-matchers.h:463:35: note: in template argument for type ‘bool’ 
     using Policy = ValuePolicy<MM>;
                                   ^
make[2]: *** [googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
make[1]: *** [googletest/CMakeFiles/gtest.dir/all] Error 2
make: *** [all] Error 2
[root@VM-155-224-centos ~/source/googletest/build]# gcc --version
gcc (GCC) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by erot1211** [comment]
Maybe you should specify the compiler in CMakeLists.txt, like this：
set(CMAKE_C_COMPILER “/home/hhb/gcc-5.2.0/bin/gcc”)
set(CMAKE_CXX_COMPILER “/home/hhb/gcc-5.2.0/bin/g++”)
