### ISSUE TITLE
clang++ msan may be flagging an issue

### ISSUE THREAD

**Issue by tbonza** [google/googletest#3647]
**Describe the bug**

Running msan on my CMake project with only a sanity check of one test:

```cpp
TEST(BombyxTest, SanityCheck) {
    EXPECT_EQ(2,2);
}
```

It looks like a destructor may be missing for https://github.com/google/googletest/blob/bf0701daa9f5b30e5882e2f8f9a5280bcba87e77/googletest/include/gtest/internal/gtest-internal.h#L490

**Steps to reproduce the bug**

Here's my msan log: [2_build (Debug, msan, clang).txt](https://github.com/google/googletest/files/7471642/2_build.Debug.msan.clang.txt)
and the relevant commit https://github.com/mothWings/bombyx/commit/db9b90bd0e58e2bc626f38281bc2b66294f86b36

**Does the bug persist in the most recent commit?**

Yes, I'm building from head https://github.com/mothWings/bombyx/blob/e30fd34b6b5f4a954fca2ff4da4d32bd30557798/cmake/FindGoogleTest.cmake#L7

**What operating system and version are you using?**

Ubuntu
20.04.3
LTS

**What compiler and version are you using?**

clang, referenced in attached msan log file. Using `grep -rn clang amd64`:

`./build (Debug, msan, clang)/3_prerequisite dependencies.txt:53:2021-11-04T00:57:18.0877737Z Get:1 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 clang amd64 1:10.0-50~exp1`

**What build system are you using?**

`./build (Debug, msan, clang)/3_prerequisite dependencies.txt:57:2021-11-04T00:57:18.9671900Z Get:5 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 cmake amd64 3.16.3-1ubuntu1`

**Additional context**

Let me know if you'd prefer a pull request with the destructor added to the struct. I'm trying to raise the possibility of a memory issue here first because of my unfamiliarity with this project.

**Comment by sbenzaquen** [comment]
I think that you are linking against an uninstrumented standard library.
For MSan to work correctly, all the code has to be instrumented. Otherwise you get false positives like these.
See https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo

**Comment by tbonza** [comment]
It's certainly possible that I made a mistake and that would be a likely culprit. I did add the instrumentation for Libcxx before filing this ticket: https://github.com/mothWings/bombyx/blob/db9b90bd0e58e2bc626f38281bc2b66294f86b36/.github/.libcxx-setup.sh

Thoughts?

**Comment by derekmauro** [comment]
From the error message I agree with @sbenzaquen's assessment.
