### ISSUE TITLE
Contains(e).Times(n) doesn't compile

### ISSUE THREAD

**Issue by ourarash** [google/googletest#3651]
**Describe the bug**

`Contains(e).Times(n)` doesn't compile for me.

**Steps to reproduce the bug**
Using release release-1.11.0, this code fails to compile:

```

TEST(ContainsTimes, ListMatchesWhenElementQuantityMatches) {
  std::list<int> some_list;
  some_list.push_back(3);
  some_list.push_back(1);
  some_list.push_back(2);
  some_list.push_back(3);
  EXPECT_THAT(some_list, Contains(3).Times(2));
  EXPECT_THAT(some_list, Contains(2).Times(1));
  EXPECT_THAT(some_list, Contains(Ge(2)).Times(3));
  EXPECT_THAT(some_list, Contains(Ge(2)).Times(Gt(2)));
  EXPECT_THAT(some_list, Contains(4).Times(0));
  EXPECT_THAT(some_list, Contains(_).Times(4));
  EXPECT_THAT(some_list, Not(Contains(5).Times(1)));
  EXPECT_THAT(some_list, Contains(5).Times(_));  // Times(_) always matches
  EXPECT_THAT(some_list, Not(Contains(3).Times(1)));
  EXPECT_THAT(some_list, Contains(3).Times(Not(1)));
  EXPECT_THAT(list<int>{}, Not(Contains(_)));
}
```
Error that I'm getting:

```
no member named 'Times' in 'testing::internal::ContainsMatcher<int>'
  EXPECT_THAT(some_list, Contains(3).Times(2));
```
**Does the bug persist in the most recent commit?**

It fails in the latest release: release-1.11.0

**What operating system and version are you using?**
Mac OS

**What compiler and version are you using?**

Please include the output of `gcc -v` or `clang -v`, or the equivalent for your
compiler.
```
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
```
**What build system are you using?**
```
bazel 4.2.0-homebrew
```
**Additional context**

**Comment by derekmauro** [comment]
https://godbolt.org/z/dzz4K3xx5 - This works for me.

The above code sample is incomplete (no headers, using statements etc). Please share the full reproduction. Godbolt links are helpful.

**Comment by derekmauro** [comment]
`Times()` was added in https://github.com/google/googletest/commit/4ec4cd23f486bf70efcc5d2caa40f24368f752e3, which is after 1.11.0 was released. If you want to use `Times()`, you need to use the latest commit.
