### ISSUE TITLE
Valgrind reports Syscall param write(buf) points to uninitialised byte(s)

### ISSUE THREAD

**Issue by emmenlau** [google/googletest#3656]
**Describe the bug**

I've recently run a number of our tests through valgrind to identify memory problems. On all occasions, I've seen the following valgrind message early in the log:

```
==1550443== Syscall param write(buf) points to uninitialised byte(s)
==1550443==    at 0x14CBC89D: syscall (syscall.S:38)
==1550443==    by 0x14815A70: write_validate (Ginit.c:141)
==1550443==    by 0x14815A70: mincore_validate (Ginit.c:171)
==1550443==    by 0x1481646A: validate_mem (Ginit.c:308)
==1550443==    by 0x14815DA7: access_mem (Ginit.c:330)
==1550443==    by 0x148172E3: dwarf_get (libunwind_i.h:169)
==1550443==    by 0x1481717E: _ULx86_64_access_reg (Gregs.c:130)
==1550443==    by 0x148151F1: _ULx86_64_get_reg (Gget_reg.c:40)
==1550443==    by 0x14823A22: apply_reg_state (Gparser.c:802)
==1550443==    by 0x148235DC: _ULx86_64_dwarf_step (Gparser.c:974)
==1550443==    by 0x14817EB9: _ULx86_64_step (Gstep.c:71)
==1550443==    by 0x1882CF7: testing::internal::OsStackTraceGetter::UnwindGetStackTrace(std::vector<testing::internal::OsStackTraceGetter::StackFrame, std::allocator<testing::internal::OsStackTraceGetter::StackFrame> >&, int, int, void*) (gtest.cc:4978)
==1550443==    by 0x18836E4: testing::internal::OsStackTraceGetter::UponLeavingGTest() (gtest.cc:5180)
==1550443==  Address 0x1ffeffe000 is on thread 1's stack
==1550443==  in frame #9, created by _ULx86_64_step (Gstep.c:57)
==1550443== 
```

I don't really know what that means and if this is even related to google test. But since there is namespace `testing::internal::` in the name I assumed it may be relevant and wanted to report it.

This was observed with a patched build of `release 1.11.0`. I assume (and hope) my patches are unrelated to this problem.

**Steps to reproduce the bug**

Run tests through Valgrind-3.17.0 with standard options.

**Does the bug persist in the most recent commit?**

I have not checked, sorry.

**What operating system and version are you using?**
```
Ubuntu 20.04 x86_64.
```

**What compiler and version are you using?**
```
Ubuntu clang version 13.0.1-++20211108052949+d5159b99105d-1~exp1~20211108173542.20
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**What build system are you using?**
```
cmake version 3.21.4-g5ec345f
```

**Comment by derekmauro** [comment]
The stacktrace functions by their nature manipulate arbitrary memory. I don't think this is an issue on our end.
