### ISSUE TITLE
Shouldn't it say to check the main branch instead of the master branch on the recommendation?

### ISSUE THREAD

**Issue by FahimFBA** [google/googletest#3673]
**Describe the bug**

In the `README`, it recommends using the latest commit in the `master` branch in our projects, but as the project has the `main` branch instead of a `master` branch, then shouldn't we replace that `master` branch with the `main` branch?

**Steps to reproduce the bug**

It's not that type of bug at all.

**Does the bug persist in the most recent commit?**

No, nothing like that.

**What operating system and version are you using?**

I am currently checking it from my Windows 11 machine.

**What compiler and version are you using?**

It's not necessary for the `README` file.

**What build system are you using?**

It's not necessary for the `README` file.

**Additional context**

No.

**Comment by FahimFBA** [comment]
That clears the confusion. Thanks a lot.

**Comment by dinord** [comment]
Fixed in ca2952c5efa4f8227a3c47f9d719e36442daa2ad.
