### ISSUE TITLE
Confusing description in Googletest Primer.

### ISSUE THREAD

**Issue by panzhongxian** [google/googletest#3704]
In Googletest Primer, there is a sentence making me misunderstand that data could be shared between tests in the same test suite:

> When multiple tests in a test suite need to share common objects and subroutines, you can put them into a test fixture class.

The later expression "reuse the same configuration of objects for several different tests" may be more clear.

**Comment by joshiayush** [comment]
> When multiple tests in a test suite need to share common objects and subroutines, you can put them into a test fixture class.

@panzhongxian See the __test fixture__ written at the end it makes everything clear. You can create a __test fixture__ class and declare and define several objects and subroutines inside of it which then later be used by several test suites of this particular fixture.

For more information see the Wiki [Sharing Resources Between Tests in the Same Test Suite](https://github.com/google/googletest/blob/main/docs/advanced.md#sharing-resources-between-tests-in-the-same-test-suite).

**Comment by panzhongxian** [comment]
@joshiayush Thanks. In short, we can share data and other resources between tests by defining static members in fixture class.
