### ISSUE TITLE
Stop testing if fatal failure occured

### ISSUE THREAD

**Issue by BMBurstein** [google/googletest#3705]
Today when a test fails with a fatal failure, it stops running the rest of the function that the failure occurred in, but if it was not in the main test body, it will not prevent the rest of the test from running. For example:

```
TEST(suite, Ex1) { // this will only report 1 failure, at #1
  FAIL(); // #1
  FAIL(); // this will not be called
}

TEST(suite, Ex2) { // this will report 2 failures
  []{ FAIL(); }(); // #1
  []{ FAIL(); }(); // #2
}
```

I understand that without using exceptions, there is no way to prevent the rest of the code from running, but I am suggesting that at least the gtest macros will first check if a fatal failure already happened before  doing their own test, or if that is not possible, at least not report any failures after a fatal failure.

For example, I am suggesting that the `ASSERT_TRUE()` macro expand into something like this:

```
#define ASSERT_TRUE(x) \
  if (not_yet_fatal_failure) { \
    ... do current ASSERT_TRUE(x) handling ... \
  }
```

and the same for all other assertions of all types.

**Comment by derekmauro** [comment]
We probably won't be making a change like this. For our supported solution, please see:

https://google.github.io/googletest/advanced.html#asserting-on-subroutines

```
TEST(suite, Ex2) {
  ASSERT_NO_FATAL_FAILURE([]{ FAIL(); }(););
  ASSERT_NO_FATAL_FAILURE([]{ FAIL(); }(););
}
```
