### ISSUE TITLE
Regular expression match against a std::wstring?

### ISSUE THREAD

**Issue by drauch** [google/googletest#3711]
Maybe this is already supported, but I can't figure it out. I have a std::wstring and want to match a regular expression against it. I tried:

```
// 1
EXPECT_THAT(L"Test", testing::MatchesRegex(L"T.*")); // C2664, C2672, C2737

// 2
EXPECT_THAT(L"Test", testing::MatchesRegex("T.*")); // C2440, C2672
```

How to do that properly?

Best regards,
D.R.

**Comment by bolshoytoster** [comment]
[This stackoverflow answer](https://stackoverflow.com/a/33601356) suggests casting `std::wstring` to `std::wregex`:
```cpp
EXPECT_THAT(std::wregex(L"Test"), testing::MatchesRegex("T.*")))
```

**Comment by asoffer** [comment]
We don't use wstring internally, so we are not likely to add support for wstring regex. I'd recommend adding your own matcher, possibly with RE2 or std::wregex, or any other regex engine you see fit.
