### ISSUE TITLE
Missing link to regex when building with cmake for qnx

### ISSUE THREAD

**Issue by PhilipMourdjis** [google/googletest#3714]
**Describe the bug**

Similar to https://github.com/google/googletest/pull/3484 but when building with cmake. QNX requires linking against regex. 

**Steps to reproduce the bug**

Impossible to reproduce without a valid QNX licence but simply trying to build this normally via cmake (using a suitably configured qnx toolchain file) will fail at build time.

**Does the bug persist in the most recent commit?**

Yes

**What operating system and version are you using?**

Host OS is Ubuntu 20.04, target is QNX 7.1

**What compiler and version are you using?**

qcc 8.3

**What build system are you using?**

cmake version 3.20.5

**Additional context**

I have a fix here: https://github.com/google/googletest/pull/3713 that works for me, would it be possible to get this merged?

**Comment by derekmauro** [comment]
Fix has been merged.
