### ISSUE TITLE
It is pronounced kemie and not schemie

### ISSUE THREAD

**Issue by TESAFACEborgir** [google/googletest#3716]
The google translator pronouncea it wrong

Include a clear and concise description of what the problem is, including what
you expected to happen, and what actually happened.

Open google translator and get google to say the german version of chemistry

It's important that we are able to reproduce the problem that you are
experiencing. Please provide all code and relevant steps to reproduce the
problem, including your `BUILD`/`CMakeLists.txt` file and build commands. Links
to a GitHub branch or [godbolt.org](https://godbolt.org/) that demonstrate the
problem are also helpful.

Yes

We recommend using the latest commit in the master branch in your projects.

Google translator web version

If you are using a Linux distribution please include the name and version of the
distribution as well.

Newest

Please include the output of `gcc -v` or `clang -v`, or the equivalent for your
compiler.

Idek

Please include the output of `bazel --version` or `cmake --version`, or the
equivalent for your build system.

In germany we pronounce it kemie not schemie please fix the google translator and its voice

**Comment by joshiayush** [comment]
> The google translator pronouncea it wrong

@TESAFACEborgir Sir/Mam this is a unit testing framework.
