### ISSUE TITLE
Compare section is not working

### ISSUE THREAD

**Issue by LayRami** [google/googletest#3718]
**Describe the bug**

In Google Chrome stock compare section is not working.

**Steps to reproduce the bug**

1 open Google (tested on both Chrome and   Google)
2. Search "infty 50"
3. Click on "compare"
4. Select and other index (not working)
5. Click on "compare to another index"
**Does the bug persist in the most recent commit?**
Idk

**What operating system and version are you using?**

Android, iOS and web

**What compiler and version are you using?**

Android Google version :12.48.23.23.arm64

iOS Google version : 190.1

**What build system are you using?**

**Additional context**

![Screenshot_20211231-230520.jpg](https://user-images.githubusercontent.com/78353660/147834180-6f1094c4-0a59-4d63-b192-a1ba8e7a0469.jpg)

**Comment by sbenzaquen** [comment]
Thanks for the report. Note that this github repository is for GoogleTest/GoogleMock.
I forwarded this report to the Google Search.
