### ISSUE TITLE
[FR] Project Examples for PlatformIO Registry

### ISSUE THREAD

**Issue by gdimauro** [google/googletest#3729]
Hi,

Currently, the [library page](https://registry.platformio.org/packages/libraries/google/googletest) in the PlatformIO Registry doesn't contain any quick start projects for developers. Such examples serve both to highlight widespread use cases and to help newcomers to get up and running much more quickly.

Please consider adding a few comprehensive project examples to the PlatformIO Registry.

Useful links:
- https://registry.platformio.org/packages/libraries/google/googletest
- https://docs.platformio.org/en/latest/librarymanager/config.html#examples

**Comment by derekmauro** [comment]
Please consider asking this of the PlatformIO project. The maintainers of GoogleTest do not know anything about PlatformIO.
