### ISSUE TITLE
DEATH_TEST segfaults in gtest.h:6332: Condition vtable_->match_and_explain != nullptr with NVHPC

### ISSUE THREAD

**Issue by janciesko** [google/googletest#3760]
We unfortunately have a threaded environment which comes from running unit tests with gtest in our parallel programming model[1]. For some reason, DEATH_TEST and its forked process cause the segfault as shown below. I have set `::testing::FLAGS_gtest_death_test_style = "threadsafe";`.

```(gdb) where
#0  0x0000000000000000 in ?? ()
#1  0x0000000001acc03e in testing::internal::MatcherBase<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&> (x=0x7fffffff64c0, listener=0x7fffffff6170)
    at /ascldap/users/jciesko/Kokkos/kokkos_viewctr_fix/kokkos3/tpls/gtest/gtest/gtest.h:6332
#2  0x0000000001acc0a9 in testing::internal::MatcherBase<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&> (x=0x7fffffff64c0)
    at /ascldap/users/jciesko/Kokkos/kokkos_viewctr_fix/kokkos3/tpls/gtest/gtest/gtest.h:6338
#3  0x0000000001ae5dde in testing::internal::DeathTestImpl::Passed (status_ok=1 '\001') at /ascldap/users/jciesko/Kokkos/kokkos_viewctr_fix/kokkos3/tpls/gtest/gtest/gtest-all.cc:8831
#4  0x00000000009c618a in Test::cuda_DeathTest_view_construction_with_wrong_params_dyn_Test::TestBody ()
```

Adding `GTEST_CHECK(vtable_->match_and_explain != nullptr);` in gtest.h at L6332 throws in that check. Any idea why match_and_explain is nullptr? It would be cool to have this working. I am seeing this only in our CI with the NVHPC compiler (PGI)[2]. 

```  bool MatchAndExplain(const T& x, MatchResultListener* listener) const {
    GTEST_CHECK_(vtable_ != nullptr);
    GTEST_CHECK(vtable_->match_and_explain != nullptr);
    return vtable_->match_and_explain(*this, x, listener);
  }
```

[1] https://github.com/kokkos/kokkos
[2] https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/Kokkos/detail/Kokkos/7980/pipeline

**Comment by derekmauro** [comment]
Thank you for reporting this issue. This platform is unsupported. If you can reproduce it on a supported platform we can take a look.

**Comment by CJ-Johnson** [comment]
Please reopen once the requested information is provided.
