### ISSUE TITLE
add override to mock macros that override virtual functions

### ISSUE THREAD

**Issue by janwilmans** [google/googletest#3767]
`-Werror=suggest-override` cannot be enabled in using projects right now, because GMock macros do not contain override.

* if we need to remain c++11 compatible, we can add a macro OVERRIDE that is normally empty but can be set to 'override' 
* if there is support for this idea, I'm willing to create a pull request, just let me know

**Comment by apcountryman** [comment]
If you are using a new enough version of googletest (not sure which version/commit introduced this), the `MOCK_METHOD()` macro is available and you can use specifiers such as `override` with it. See https://github.com/google/googletest/blob/main/docs/gmock_for_dummies.md#how-to-define-it for examples.

**Comment by janwilmans** [comment]
thanks, I'm going to test that and report back !

**Comment by derekmauro** [comment]
@apcountryman's answer is correct.
