### ISSUE TITLE
cmake find_package can not find gmock on manual compile

### ISSUE THREAD

**Issue by Meigumikato** [google/googletest#3771]
on my mac, when i use brew install googletest cmake can correctly find gtest and gmock , but when i manu
al compile googletest and install it，my cmake only can find gtest not correctly find gmock 

my cmakelists.txt
set(GTEST_ROOT ${CMAKE_SOURCE_DIR}/third_party/googletest/output)
find_package(GTest REQUIRED)
target_link_libraries(xxx PRIVATE
  GTest::gmock_main
  GTest::gtest_main)

**Comment by Meigumikato** [comment]
my install lib dir 
--------------------
cmake
libgmock.1.11.0.dylib
libgmock.a
libgmock.1.11.0.dylib
libgmock_main.1.11.0.dylib
libgmock_main.a
libgmock_main.1.11.0.dylib
libgtest.1.11.0.dylib
libgtest.a
libgtest.1.11.0.dylib
libgtest_main.1.11.0.dylib
libgtest_main.a
libgtest_main.1.11.0.dylib
pkgconfig
------------------------

**Comment by bqhuyy** [comment]
use **find_package(GTest CONFIG REQUIRED)** instead

**Comment by Meigumikato** [comment]
ok, thanks
