### ISSUE TITLE
Save source file and line number in xml and json outputs for easier autmated operations

### ISSUE THREAD

**Issue by sobczyk** [google/googletest#3772]
**Does the feature exist in the most recent commit?**

No, only in test listing

**Why do we need this feature?**

Easier machine matching of failed tests to their location.

**Describe the proposal**

Few changes are needed, specifically moving the conditional few lines down,
and adjusting output line termination properly
```
GTEST_FLAG_GET(list_tests)
```
thus it'd be possible to get
```
 <testcase name="name" file="example.cpp" line="1" status="run" time="0" classname="cls"  />
```
Instead of
```
<testcase name="name" status="run" time="0" classname="cls"  />
```

**Is the feature specific to an operating system, compiler, or build system version?**

Not specific

**Comment by derekmauro** [comment]
Sounds like a reasonable feature request, but we are unable to prioritize it at this time. If you send us a pull request, we will consider it.

**Comment by sobczyk** [comment]
PR ready for review

**Comment by asoffer** [comment]
Thanks so much for doing this!
