### ISSUE TITLE
InSequence 'scope'

### ISSUE THREAD

**Issue by EvanTheB** [google/googletest#3782]
// An object of this type causes all EXPECT_CALL() statements
// encountered in its scope to be put in an anonymous sequence.  The
// work is done in the constructor and destructor.  You should only
// create an InSequence object on the stack.

https://github.com/google/googletest/blob/0affd45b62371c1de44064a5a5f8817242208442/googlemock/include/gmock/gmock-spec-builders.h#L649

Hello, I read the above and thought that InSequence would only apply to objects in the same scope, but it seems maybe it applies to all objects created after the constructor for InSequence runs and before the destructor runs. Is that called scope in c++ ? Is there a better term, something like 'while the object is on the stack'? I'm not sure on the words for c++, but scope seems wrong.

**Comment by dinord** [comment]
Scope is a well-defined term in C++: https://en.cppreference.com/w/cpp/language/scope

Most rules in C++ come with an asterisk or two. While we could technically provide more accurate documentation using terms such as "object lifetime", we felt that "scope" was appropriate choice given the intended use case of `InSequence`.
