### ISSUE TITLE
Output is broken if run unit tests in Xcode

### ISSUE THREAD

**Issue by rokoDev** [google/googletest#3788]
**Describe the bug**
After I have updated Mac OS to Monterey Version 12.3 (21E230) and Xcode to Version 13.3 (13E113) Google Test unable to recognise that it is run from Xcode and therefore uses colour codes to output text.

For example if I run unit tests for [strong_type](https://github.com/rokoDev/strong_type) I expect that first line of output should be:
`[==========] Running 11 tests from 1 test suite.`

but it turns out that Google Test output this:
`[0;32m[==========] [mRunning 11 tests from 1 test suite.`

**Steps to reproduce the bug**

1. Update your Mac OS to Monterey Version 12.3 (21E230)
2. Update your Xcode to Version 13.3 (13E113)
3. Clone [strong_type](https://github.com/rokoDev/strong_type) (or any C++ project which use Google Test) and run unit tests in Xcode(instructions how to run unit tests in Xcode provided in **README.md** in **strong_type** project).

**Does the bug persist in the most recent commit?**

- Yes. af29db7ec28d6df1c7f0f745186884091e602e07

**What operating system and version are you using?**

- Mac OS Monterey Version 12.3 (21E230)

**What compiler and version are you using?**

- Apple clang version 13.1.6 (clang-1316.0.21.2)

**What build system are you using?**

- cmake version 3.23.0-rc4

**Additional context**

If I understand right the reason of this bug lie in file `googletest/googletest/src/gtest.cc` in line **3241**:
`const char* const term = posix::GetEnv("TERM");`
If unit tests run from Xcode `term` expected to be `NULL` but it is equal to `"xterm-256color"`
I do not know how to fix this and currently as workaround I just disable colours by running unit tests with command line argument `--gtest_color=no`.

**Comment by derekmauro** [comment]
This sounds like an xcode bug. It seems to be asking for color but not handling it correctly.

**Comment by rokoDev** [comment]
I have submitted this issue to Apple via feedbackassistant: https://feedbackassistant.apple.com/feedback/9975209

**Comment by derekmauro** [comment]
Please re-open if this turns out not to be an Xcode bug.

**Comment by rokoDev** [comment]
Ok. Btw after updating Xcode command-line tools the bug is gone. Now `term` after this expression `const char* const term = posix::GetEnv("TERM");` is NULL as it is expected to be.
