### ISSUE TITLE
ASSERT_NE with nullptr confuses clang --analyze

### ISSUE THREAD

**Issue by josephcsible** [google/googletest#3800]
**Describe the bug**

When using `ASSERT_NE` to abort if a variable is null, the macro calling `CmpHelperNE` to do the comparison prevents `clang --analyze` from realizing what's actually being checked, causing false positives.

**Steps to reproduce the bug**

Run `clang --analyze` on this file:
```cpp
#include <new>
#include <gtest/gtest.h>

TEST(Foo, Bar) {
  int *ptr = new (std::nothrow) int;
  ASSERT_NE(ptr, nullptr);
  delete ptr;
}
```

The result:
```
warning: Potential leak of memory pointed to by 'ptr' [cplusplus.NewDeleteLeaks]
  ASSERT_NE(ptr, nullptr);
  ^~~~~~~~~~~~~~~~~~~~~~~
build/_deps/googletest-src/googletest/include/gtest/gtest.h:1873:31: note: expanded from macro 'ASSERT_NE'
#define ASSERT_NE(val1, val2) GTEST_ASSERT_NE(val1, val2)
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
build/_deps/googletest-src/googletest/include/gtest/gtest.h:1855:3: note: expanded from macro 'GTEST_ASSERT_NE'
  ASSERT_PRED_FORMAT2(::testing::internal::CmpHelperNE, val1, val2)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
build/_deps/googletest-src/googletest/include/gtest/gtest_pred_impl.h:148:44: note: expanded from macro 'ASSERT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_FATAL_FAILURE_)
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
note: (skipping 2 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
build/_deps/googletest-src/googletest/include/gtest/internal/gtest-internal.h:1353:10: note: expanded from macro 'GTEST_FATAL_FAILURE_'
  return GTEST_MESSAGE_(message, ::testing::TestPartResult::kFatalFailure)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
build/_deps/googletest-src/googletest/include/gtest/internal/gtest-internal.h:1350:3: note: expanded from macro 'GTEST_MESSAGE_'
  GTEST_MESSAGE_AT_(__FILE__, __LINE__, message, result_type)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
build/_deps/googletest-src/googletest/include/gtest/internal/gtest-internal.h:1346:71: note: expanded from macro 'GTEST_MESSAGE_AT_'
  ::testing::internal::AssertHelper(result_type, file, line, message) = \
                                                                      ^
```

**Does the bug persist in the most recent commit?**

Yes, 8ccdb9d

**What operating system and version are you using?**

Ubuntu 20.04

**What compiler and version are you using?**

```
clang version 14.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/joe/clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

**What build system are you using?**

```
cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
Although the problem happens just by running `clang --analyze` directly, outside of the build system.

**Additional context**

Here's what it expands to (formatted):
```cpp
  switch (0)
  case 0:
  default:
    if (const ::testing::AssertionResult gtest_ar =
            (::testing::internal::CmpHelperNE("ptr", "nullptr", ptr, nullptr)))
      ;
    else
      return ::testing::internal::AssertHelper(
                 ::testing::TestPartResult::kFatalFailure, "hello_test.cc", 6,
                 gtest_ar.failure_message()) = ::testing::Message();
```

**Comment by derekmauro** [comment]
I would consider this to be an issue with Clang's static analysis rather than GoogleTest code.

**Comment by josephcsible** [comment]
But isn't `::testing::internal::CmpHelperNE("ptr", "nullptr", ptr, nullptr)` an opaque function call? How should Clang's static analyzer be expected to know that that means `ptr != nullptr`?

**Comment by josephcsible** [comment]
In particular, after expanding `GTEST_IMPL_CMP_HELPER_(NE, !=)`, you get this:

```c++
template <typename T1, typename T2>
AssertionResult CmpHelperNE(const char* expr1, const char* expr2,
                            const T1& val1, const T2& val2) {
  if (val1 != val2) {
    return AssertionSuccess();
  } else {
    return CmpHelperOpFailure(expr1, expr2, val1, val2, "!=");
  }
}
```
And `AssertionSuccess` is defined in `googletest/src/gtest-assertion-result.cc`, not in a header file, so static analyzers looking at any other source file have no way of knowing that the `AssertionResult` it returns will always have `success_` being true.

**Comment by josephcsible** [comment]
It turns out that just moving the definitions of `AssertionSuccess` and `AssertionFailure` to the header wasn't sufficient to make the false positive go away. I also had to swap the order that `message_` and `success_` are declared inside of `AssertionResult`. I'm not sure why, though. I asked https://stackoverflow.com/q/72007867/7509065 about that.

**Comment by josephcsible** [comment]
I opened PR #3823 which will fix this.

**Comment by dinord** [comment]
We might consider non-invasive changes (e.g. something strictly limited to a .cc file and behind macros), but not non-trivial API changes like the one proposed in PR #3823. Feel free to re-open if you can come up with an alternative proposal.
