### ISSUE TITLE
Gtest doesn't use TMPDIR if it's set

### ISSUE THREAD

**Issue by ZijunZhaoCCK** [google/googletest#3810]
**Describe the bug**

TMPDIR isn't used if it is set.

https://github.com/google/googletest/blob/bf66935e07825318ae519675d73d0f3e313b3ec6/googletest/src/gtest-port.cc#L1078 is not this one: https://github.com/google/googletest/blob/bf66935e07825318ae519675d73d0f3e313b3ec6/googletest/src/gtest.cc#L6765

TMPDIR is not set on most versions of Android.
The only way for apps to find their temp dir pre S (or maybe even T) is with a Java API.
Gtest doesn't read TMPDIR. It's hard coded to use /data/local/tmp, which is not accessible to apps.

https://github.com/google/googletest/blob/bf66935e07825318ae519675d73d0f3e313b3ec6/googletest/src/gtest-port.cc#L1135-L1139. The path it's trying to read is /data/local/tmp/gtest_captured_stream.9HGG34. Apps haven't been allowed to access /data/local/tmp for a while . For new OSs (S and newer maybe?), TMPDIR is set for apps. 

**Does the bug persist in the most recent commit?**

Yes.

**What operating system and version are you using?**

Debian GNU/Linux rodete

**Comment by dinord** [comment]
On Android, the environment variable is called `TEST_TMPDIR`, not `TMPDIR`: https://github.com/google/googletest/blob/bf66935e07825318ae519675d73d0f3e313b3ec6/googletest/src/gtest.cc#L6763

**Comment by mgood7123** [comment]
this must also be changed in gtest-ports.cc

name_template = TempDir();
