### ISSUE TITLE
Set default message for tests based on type

### ISSUE THREAD

**Issue by GasimGasimzada** [google/googletest#3826]
**Does the feature exist in the most recent commit?**

Not sure. Could not find it in docs

**Why do we need this feature?**

To make sure that the human readable content is displayed for all tests that assert a specific type

**Problem**

There are certain complex data types that show up as binary data when assertions fail. Example output:

```
camera.projectionViewMatrix
    Which is: 64-byte object <28-24 65-BF 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 28-24 65-BF 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 08-00 80-BF 00-00 80-BF 28-24 65-3F 28-24 E5-3E A8-EF 1F-40 00-00 20-40>
camera.projectionMatrix
    Which is: 64-byte object <28-24 65-BF 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 28-24 65-BF 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 08-00 80-BF 00-00 80-BF 00-00 00-00 00-00 00-00 77-12 83-BA 00-00 00-00>
```

This information is not really useful and requires cognitive effort to understand that the values are the same. Currently, in order to mitigate this problem, we can set a custom message **per assertion:**

```cpp
EXPECT_EQ(camera.projectionViewMatrix, camera.projectionMatrix)
  << glm::to_string(camera.projectionViewMatrix) << "\n" << glm::to_string(camera.projectionMatrix);
```

Output:

```
mat4x4((-0.895083, 0.000000, 0.000000, 0.000000), (0.000000, -0.895083, 0.000000, 0.000000), (0.000000, 0.000000, -1.000001, -1.000000), (0.895083, 0.447541, 2.499002, 2.500000))
mat4x4((-0.895083, 0.000000, 0.000000, 0.000000), (0.000000, -0.895083, 0.000000, 0.000000), (0.000000, 0.000000, -1.000001, -1.000000), (0.000000, 0.000000, -0.001000, 0.000000))
```

This is one assertion for one type of object. There are lots of types like this that can benefit from having a user readable text and adding them to every assertion adds a lot of noise to the test codes.

**Proposal:**

It would be nice if we can have a function that allows overriding these fields in a really easy way. For example:

```cpp
// OutStream is what gets printed into the console from the assertion
template<> ::testing::OutStream &operator<<(::testing::OutStream &out, glm::mat4 &value) {
  out << glm::to_string(value);
  return out;
}
struct CameraLens {
  float fov, near, far;
};

template<> ::testing::OutStream &operator<<(::testing::OutStream &out, CameraLens &value) {
  out << "FOV: " << value.fov << "; Near: " << value.near << "; Far: " << value.far;
  return out;
}

// No need to set custom message anymore
EXPECT_EQ(camera.projectionViewMatrix, camera.projectionMatrix);
```

**Is the feature specific to an operating system, compiler, or build system version?**

No

**Comment by asoffer** [comment]
This exists, but the documentation is a bit difficult to find:

https://github.com/google/googletest/blob/main/googletest/include/gtest/gtest-printers.h#L37-L45

**Comment by GasimGasimzada** [comment]
How does that work exactly? I added the overloads in the same file as the test but nothing changes:

```
#include <gtest/gtest.h>

namespace glm {
  void PrintTo(const vec3 &value, std::ostream *out) {
    *out << to_string(value);
  }
}

TEST(MyTest, TestingOutput) {
  EXPECT_EQ(glm::vec3{1.0f}, glm::vec3{2.5f}));
}
```

Assertion fails and the error gets displayed as binary values.

**Comment by GasimGasimzada** [comment]
@ignatyevm Did you add your logic inside a the `glm` namespace? I tried it both ways but I still get the binary output instead of the actual stringified glm vector or matrix.

**Comment by GasimGasimzada** [comment]
I found the problem and it is related to the `glm` math library that I am trying to extend with testing functions. I will close this ticket since this goes beyond the scope of google test printers (gtest printers do work in different namespaces but not with `glm` math library)
