### ISSUE TITLE
matcher(err.what(), expect_msg) evaluates to false, even though err.what() and expect_msg seem identical.

### ISSUE THREAD

**Issue by mitiguy** [google/googletest#3842]
I encountered the following "bug" (more precisely a defect) when testing code.
matcher() reports the following message which (on its surface) is difficult to comprehend.
It appears these two strings are identical (this causes confusion).
```
mitiguy_test.cc:: Failure
matcher(err.what(), expect_msg) evaluates to false, where
err.what() evaluates to "A length argument to CheckSolidBox() is negative."
expect_msg evaluates to "A length argument to CheckSolidBox() is negative."
```

There is no mention that under the hood, regular expressions are being used.  It would have saved me _hours_ had the use of regular expressions been mentioned in the actual on-screen message (particularly since the on-screen text is _exactly_ the same for both err.what() and expect_msg).  Although the error is my user mis-expectation, I have checked this with my group of post PhD CS folks and all of the ones I queried wasted time investigating their mistaken expectation (string vs. regular expression).

I greatly simplified my C++ code to provide an example.
The code below throws the message.
```
  /// @throws std::exception if any of Lx, Ly, Lz are negative.
  static void  CheckSolidBox(const double& Lx, const double& Ly, const double& Lz) {
    if (Lx < 0 || Ly < 0 || Lz < 0) {
      const std::string msg = "A length argument to CheckSolidBox() is negative.";
      throw std::logic_error(msg);
    }
}
```

Here is the code that catches the exception and checks the message.
```
  // Ensure an exception is thrown if a length is negative.
  const std::string msg = "A length argument to CheckSolidBox() is negative.";
  DRAKE_EXPECT_THROWS_MESSAGE(CheckSolidBox(1, 2, -3), expect_msg);
```

Here is the code that fixes the problem (which is that regular expressions, not strings are being used).
```
  // Ensure an exception is thrown if a length is negative.
  const std::string msg = "A length argument to CheckSolidBox\\(\\) is negative.";
  DRAKE_EXPECT_THROWS_MESSAGE(CheckSolidBox(1, 2, -3), expect_msg);
```

**Comment by tallua** [comment]
I tried to find DRAKE_EXPECT_THROWS_MESSAGE macro and found its implementation [here](
https://github.com/RobotLocomotion/drake/blob/master/common/test_utilities/expect_throws_message.h
).

It says
`
 Unit test helper macro for "expecting" an exception to be thrown but also
testing the error message against a provided regular expression.
`

```cpp
#define DRAKE_EXPECT_THROWS_MESSAGE(expression, regexp)
```
So I think it is not a bug, nor the bug or googletest itself.

**Comment by dinord** [comment]
This does not look like a GoogleTest bug. If you think it is, please re-open and make sure to use the GitHub issue template to provide instructions for reproducing the issue.
