### ISSUE TITLE
using structured bindings inside INSTANTIATE_TEST_SUITE_P results in failed compilation

### ISSUE THREAD

**Issue by krzysiek6d** [google/googletest#3848]
**Describe the bug**

Using structured bindings inside lambda desired for giving names of parametrized tests inside INSTANTIATE_TEST_SUITE_P results in failed compilation.
According to document [Specifying Names for Value-Parameterized Test Parameters](https://github.com/google/googletest/blob/main/docs/advanced.md#specifying-names-for-value-parameterized-test-parameters) you can pass a lambda function to specify the test cases of parametrized tests.
Unfortunately you cannot use structured bindings inside it - it results in failed compilation
If you specify exactly the same lambda outside the INSTANTIATE_TEST_SUITE_P then everything works fine.
I'd like to use structured bindings instead of std::get for having code more readable

**Steps to reproduce the bug**

```c++
#include <gtest/gtest.h>
#include <tuple>
#include <string>

struct Issue : public ::testing::TestWithParam<std::tuple<int, int>>
{
};

TEST_P(Issue, my_test)
{
}

auto lambda_defined_out_of_instantiate_test_suite_p_macro = [](const auto& info)
{
    auto [val1, val2] = info.param;
    return std::to_string(std::get<0>(info.param)) + std::to_string(std::get<1>(info.param));
};

// switch SHOW_ISSUE to 1 to see that using structured bindings inside INSTANTIATE_TEST_SUITE_P is impossible
// switch SHOW_ISSUE to 0 to see that when the same lambda is defined out of INSTANTIATE_TEST_SUITE_P
//                   then everything works ok
#define SHOW_ISSUE 1

INSTANTIATE_TEST_SUITE_P(
        tests,
        Issue,
        ::testing::Values(
            std::make_tuple(2, 3)
        ),
#if SHOW_ISSUE == 1
        [](const auto& info)
        {
            auto [val1, val2] = info.param;  // if you comment this line then everything works fine, here binding is from info.param but for others, like std::pair it does not work as well
            return std::to_string(std::get<0>(info.param)) + std::to_string(std::get<1>(info.param));
        }
#else
        lambda_defined_out_of_instantiate_test_suite_p_macro
#endif
);
```

**Does the bug persist in the most recent commit?**

Yes
main branch of googletest (https://github.com/google/googletest.git): commit 8d51dc50eb7e7698427fed81b85edad0e032112e

**What operating system and version are you using?**

5.10.114-1-MANJARO

If you are using a Linux distribution please include the name and version of the
distribution as well.

**What compiler and version are you using?**

c++20
gcc (GCC) 11.2.0

**What build system are you using?**

cmake --version  
cmake version 3.23.1

**Additional context**

cmakelists fyi:
```
cmake_minimum_required(VERSION 3.0)
project(named_parametrized_test_issue)

set(CMAKE_CXX_STANDARD 20)

include(FetchContent)
Set(FETCHCONTENT_QUIET FALSE)
FetchContent_Declare(googletest
        GIT_REPOSITORY https://github.com/google/googletest.git
        GIT_TAG main
        GIT_PROGRESS TRUE)
FetchContent_MakeAvailable(googletest)
enable_testing()

add_executable(named_parametrized_test_issue
        reproduction.cpp)
target_link_libraries(named_parametrized_test_issue gtest_main gmock)
add_test(named_parametrized_test_issue named_parametrized_test_issue)
```

**Comment by dinord** [comment]
The problem lies in the `,` in structured bindings. Unfortunately, the C++ preprocessor will misinterpret that as a separator between two macro arguments.  

A common trick to avoid this issue is to put parentheses around the expression (in this case, the entire lambda): https://godbolt.org/z/o1ahP3e88
