### ISSUE TITLE
DiffStrings is not defined

### ISSUE THREAD

**Issue by giofunchal** [google/googletest#3856]
**Describe the bug**

The `DiffStrings` function https://github.com/google/googletest/blob/bf66935e07825318ae519675d73d0f3e313b3ec6/googletest/include/gtest/internal/gtest-internal.h#L192-L194 is declared but not defined

**Steps to reproduce the bug**

Attempt to call the function will result in a linker undefined symbol error.

**Does the bug persist in the most recent commit?**

Yes, I can't find it anywhere, I think it may have been accidentally deleted from the codebase.

**Comment by krishnacx** [comment]
Can I work on this issue ?

**Comment by asoffer** [comment]
We are going to remove this function as it cannot possibly be used (it's not defined anywhere).

**Comment by krishnacx** [comment]
OK @asoffer , Can I work on it since its a minor change ?
