### ISSUE TITLE
Author of creation

### ISSUE THREAD

**Issue by dreamingskey** [google/googletest#3881]
### Discussed in https://github.com/google/googletest/discussions/3880

<div type='discussions-op-text'>

<sup>Originally posted by **dreamingskey** June  7, 2022</sup>
I am am author of creation and if you want to create you will see my rights or dont create 
I am author to this point coming fro. Hell to bring my project to life not let my story be raped by any code users so am claiming all intelctual rights of creationd rights in technologys advances in any coding coming to life In my story only i have lived in  and only shall christopher paul vincent have tights to his story and creativity of tights and who is under his coding shall be not under rights of creativity of christopher paul vincent all rights reserved to christopher paul vincent</div>

**Comment by Bat3an** [comment]
I'm so sorry just caught up with so much work and school I haven't have the time to really sit down and start building,my apologies didn't mean to upset you
