### ISSUE TITLE
Seed for --gtest_shuffle should be reported at the end of the test runs

### ISSUE THREAD

**Issue by Matthdonau** [google/googletest#3882]
**Why do we need this feature?**
My use case: In order to check a unittest target for good health i run the target with --gtest_repeat=-1 --gtest_shuffle --gtest_break_on_failure for a certain amount of time. This will give me a good idea if certain tests change some global state on which other tests subsequently depend on and catch such bugs which otherwise are very tedious to find.
However if i hit such a problem it is very likely that the target i run this command on holds very many unittests. If i was lucky enough and the buffer of my console window is large enough to get to the top where the seed is printed i am able to reproduce the problem. However it is sometimes very annoying to find the correct seed when scrolling up.

**Describe the proposal**
If unittests fail with the gtest_shuffle option (or break with gtest_shuffle and gtest_break_on_failure) the last line written to the console should be at least the seed with which the run can be reproduced. Optionally the whole command to reproduce the last failing run could be printed

**Comment by derekmauro** [comment]
There are a lot of things we could reorder in our output, but they would all displace something as well. I would recommend either redirecting the output to a file (`./mytest > output.txt`) or using something like `./mytest | less`.
