### ISSUE TITLE
Version 1.12.0 still has version 1.11.0 in the CMakeLists.txt file

### ISSUE THREAD

**Issue by a16bitsysop** [google/googletest#3911]
**Describe the bug**

Compiling version 1.12.0 on alpine linux the libraries are created as 1.11.0

**Steps to reproduce the bug**

Build from 1.12.0 release tarball

**Does the bug persist in the most recent commit?**

It is still that in main branch

**What operating system and version are you using?**

Alpine linux edge

**What compiler and version are you using?**

gcc 11.2.1

**What build system are you using?**

cmake (3.23.2-r0)

**Additional context**

**Comment by derekmauro** [comment]
Ouch, that's a slightly embarrassing mistake. I will patch the release branch and create a patch release early this week.

**Comment by derekmauro** [comment]
https://github.com/google/googletest/releases/tag/release-1.12.1 has been release to patch this issue.
