### ISSUE TITLE
UBSanitizer error under macOS (Apple Silicon/Apple clang) if Google Test is compiled as a shared library

### ISSUE THREAD

**Issue by dgazzoni** [google/googletest#3913]
**Describe the bug**

UBSanitizer from Apple clang 13.1.6, on an Apple Silicon machine with macOS Monterey reports an error on the simplest possible test case, but only when Google Test is compiled as a shared library.

I have attempted to reproduce the bug on a number of different environments as follows:

**Static library**: When compiled as a static library (e.g. by adding `-DBUILD_SHARED_LIBS=OFF` as an argument to CMake in the repro steps below), **the problem does not occur**.

**macOS Big Sur with Apple's clang 12**: Testing under macOS Big Sur on Apple Silicon with "Apple clang version 12.0.5 (clang-1205.0.22.11)", **the same problem occurs**.

**Apple Silicon Mac with gcc 11**: I was unable to test this with Homebrew's gcc under macOS with an Apple Silicon CPU, since it doesn't appear to include a necessary library for UBSanitizer, and thus **doesn't compile**.

**Intel Mac with clang 13**: I tested this with an Intel Mac, running macOS Monterey and the same version of Apple's clang as mentioned below, and **the problem does not occur**.

**Intel Mac with gcc 11**: On the same Intel Mac as above, and using "gcc-11 (Homebrew GCC 11.3.0) 11.3.0", **the problem does not occur**.

**Linux/aarch64 with clang 13**: I tested this under Linux/aarch64 on a Raspberry Pi 4 board (running 64-bit Ubuntu Linux 21.10, Ubuntu clang 13.0.0-2) and **the problem does not occur**.

**Linux/aarch64 with gcc 11**: On the same Raspberry Pi 4 board, replacing the compiler with "gcc-11 (Ubuntu 11.2.0-7ubuntu2) 11.2.0", **the problem does not occur**.

**Steps to reproduce the bug**

We assume the repro steps will be performed in the `~/test` directory.

1. Create the following CMakeLists.txt file in `~/test`:

```
cmake_minimum_required(VERSION 3.0)
project(test CXX)
option(BUILD_SHARED_LIBS "" ON)

add_compile_options(-fsanitize=undefined)
add_link_options(-fsanitize=undefined)

add_subdirectory(googletest)

add_executable(test test.cpp)
target_link_libraries(test gtest gtest_main)
```

2. Create the following test.cpp file in `~/test`:

```
#include <gtest/gtest.h>

TEST(test, test) {
    EXPECT_EQ(0, 0);
}
```

3. Configure, build and run by running the following commands starting from the `~/test` directory:

```
mkdir build
cd build
cmake ..
make
./test
```

Note: in my system this automatically picks up Apple's clang compiler. Should it pick up a different compiler, please add the appropriate flags to CMake (e.g. `-DCMAKE_CXX_COMPILER=...`) to ensure Apple's clang compiler is used.

4. The result is the following output, indicating an error:5. 

```
Running main() from /Users/dgazzoni/test/googletest/googletest/src/gtest_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from test
[ RUN      ] test.test
/Users/dgazzoni/test/googletest/googletest/src/gtest.cc:2599:10: runtime error: member call on address 0x600002930020 which does not point to an object of type 'testing::internal::TestFactoryBase'
0x600002930020: note: object is of type 'testing::internal::TestFactoryImpl<test_test_Test>'
 00 00 00 00  10 c3 eb 04 01 00 00 00  00 00 00 00 00 00 00 00  d8 65 5b 05 01 00 00 00  e8 43 e0 1d
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'testing::internal::TestFactoryImpl<test_test_Test>'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/decio/test/googletest/googletest/src/gtest.cc:2599:10 in 
[       OK ] test.test (2 ms)
[----------] 1 test from test (2 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (2 ms total)
[  PASSED  ] 1 test.
/Users/dgazzoni/test/googletest/googletest/src/gtest.cc:2727:25: runtime error: member call on address 0x600002930020 which does not point to an object of type 'internal::TestFactoryBase'
0x600002930020: note: object is of type 'testing::internal::TestFactoryImpl<test_test_Test>'
 00 00 00 00  10 c3 eb 04 01 00 00 00  00 00 00 00 00 00 00 00  d8 65 5b 05 01 00 00 00  e8 43 e0 1d
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'testing::internal::TestFactoryImpl<test_test_Test>'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/decio/test/googletest/googletest/src/gtest.cc:2727:25 in 
```

**Does the bug persist in the most recent commit?**

Yes. We had a very old (circa 2019) version of Google Test that already exhibited the bug, then we updated to the most recent commit and the problem persists.

**What operating system and version are you using?**

If you are using a Linux distribution please include the name and version of the
distribution as well.

**What compiler and version are you using?**

```
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**What build system are you using?**

```
cmake version 3.22.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Note: installed with Homebrew.

**Comment by dgazzoni** [comment]
> I didn't try to reproduce this, but the problem might be that you need a standard library that is also compiled with the sanitizer that you are using. I'm guessing this isn't the case, especially if you have a shared library.
> 
> Let us know if this makes sense.

I don't think that's the issue, seeing as the bug doesn't manifest under many other circumstances (static library, Intel Mac, Linux ARM, etc.)

**Comment by anthonygraca** [comment]
I was unable to replicate this issue. UBSanitizer doesn't report any issues with my executable.

Apple Silicon - MacOS Monterey 12.6
Compiler: clang 14.0.0
cmake 3.24.2

**Comment by dgazzoni** [comment]
> I was unable to replicate this issue. UBSanitizer doesn't report any issues with my executable.
> 
> Apple Silicon - MacOS Monterey 12.6 Compiler: clang 14.0.0 cmake 3.24.2

I can confirm that, after updating to clang 14.0.0, the issue went away (although I just checked prior to upgrading, and it still happened with clang 13.1.6).

For my part, this is no longer an issue given that I've upgraded. Thus, I'm closing it.
