### ISSUE TITLE
Add support for move only parameters in mocked methods

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#395]
```
The new C++11 standard allows for rvalue references in method parameters. Using 
those for move semantics is very useful. We need to suppor them, e.g.:

MOCK_METHOD1(mock, foo(int&& i));
```

Original issue reported on code.google.com by `vladlosev` on 19 Dec 2011 at 12:45

**Comment by timdave13** [comment]
Is there any progress on this issue?  I am forced to either change my API or not test this part of my code, which both to me are very undesirable.

**Comment by lacombar** [comment]
@timdave13 the patch in https://github.com/google/googletest/issues/395#issuecomment-125645954 worked fine for me.

**Comment by timdave13** [comment]
Thanks @lacombar.  I was hoping to stay with master so as to not have to manage another vendor branch.  It is a bit more complicated for us since we use svn, but not terrible.

**Comment by Hippocrates** [comment]
Is there anything preventing this from being integrated as a pull request (or maybe it already is and just isn't linked)? This seems like a fairly useful feature to have, and from experience I can say its extremely annoying to have to work around, especially when it gets in the way of being able to use auto-generated mocks. If nobody else has something in the works, I'd be happy to try and bring it together (though maybe the original authour of the patch might want to have a go?).

**Comment by jupp0r** [comment]
@BillyDonahue: anything we can do to get this merged?

**Comment by BillyDonahue** [comment]
There's not a PR here. We do have to be careful about adding C++11 features.

**Comment by hethi** [comment]
related to #1155 - maybe fix provided #914

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by jupp0r** [comment]
For people finding this issue through search engines: There is support for rvalue references for a limited subset of gmocks actions along those lines:

``` EXPECT_CALL(mock, MakeUnique()).WillOnce(Return(ByMove(std::move(i))));```

**Comment by daravi** [comment]
Is `MOCK_METHOD1(mock, foo(int&& i));` supported yet?
