### ISSUE TITLE
The issue of using custom comparators on new library releases.

### ISSUE THREAD

**Issue by kdator** [google/googletest#3969]
I had some problems migrating from version 1.8.1 to 1.12.1.

The fact is that I have my custom macro for comparing entities with each other. Inside it, I used the macro `EXPECT_PRED_FORMAT#(arg1...argN)`, where I passed a personal comparator and arguments as parameters. For my macro to work successfully, I needed to create my own .h is the file where I included the `gtest/gtest_pred_impl.h` file and implemented its behavior there. With migration to version 1.12.1 (I haven't tried other release versions) my project stopped assembling, giving me a compilation error, which can be seen below:

<details>
<summary>Console output</summary>
<pre><code>...: error: incomplete type 'testing::TestPartResult' named in nested name specifier
...
...\googletest\googletest\include\gtest/internal/gtest-internal.h(1350,38): note: expanded from macro 'GTEST_NONFATAL_FAILURE_'
  GTEST_MESSAGE_(message, ::testing::TestPartResult::kNonFatalFailure)
...\googletest\googletest\include\gtest/internal/gtest-internal.h(1344,50): note: expanded from macro 'GTEST_MESSAGE_'
  GTEST_MESSAGE_AT_(__FILE__, __LINE__, message, result_type)
                                                 ^~~~~~~~~~~
...\googletest\googletest\include\gtest/internal/gtest-internal.h(1340,37): note: expanded from macro 'GTEST_MESSAGE_AT_'
  ::testing::internal::AssertHelper(result_type, file, line, message) = \
                                    ^~~~~~~~~~~
...\googletest\googletest\include\gtest/internal/gtest-internal.h(108,7): note: forward declaration of 'testing::TestPartResult'
class TestPartResult;   // Result of a test part.
<br/>
...: error: no member named 'AssertHelper' in namespace 'testing::internal''
...
...\googletest\googletest\include\gtest/gtest_pred_impl.h(224,52): note: expanded from macro 'EXPECT_PRED_FORMAT4'
  GTEST_PRED_FORMAT4_(pred_format, v1, v2, v3, v4, GTEST_NONFATAL_FAILURE_)
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
...\googletest\googletest\include\gtest/gtest_pred_impl.h(213,66): note: expanded from macro 'GTEST_PRED_FORMAT4_'
  GTEST_ASSERT_(pred_format(#v1, #v2, #v3, #v4, v1, v2, v3, v4), on_failure)
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
...\googletest\googletest\include\gtest/internal/gtest-internal.h(1350,3): note: expanded from macro 'GTEST_NONFATAL_FAILURE_'
  GTEST_MESSAGE_(message, ::testing::TestPartResult::kNonFatalFailure)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...\googletest\googletest\include\gtest/internal/gtest-internal.h(1344,3): note: expanded from macro 'GTEST_MESSAGE_'
  GTEST_MESSAGE_AT_(__FILE__, __LINE__, message, result_type)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...\googletest\googletest\include\gtest/internal/gtest-internal.h(1340,24): note: expanded from macro 'GTEST_MESSAGE_AT_'
  ::testing::internal::AssertHelper(result_type, file, line, message) = \
<br/>
"path-to-my-macro-file": error: no member named 'FormatForComparisonFailureMessage' in namespace 'testing::internal'
                                            testing::internal::FormatForComparisonFailureMessage(strExp, strAct),
                                            ~~~~~~~~~~~~~~~~~~~^
</pre></code>
</details>

My custom comparator looks like this:
```
template<typename T1, typename T2>
static testing::AssertionResult cmpHelperRt(const char*, const char*, const char*, const char*, const T1& expected,
                                            const T2& actual, const std::string& expectedExpr,
                                            const std::string& actualExpr) {
    if (expected == actual) {
        return testing::AssertionSuccess();
    }

    return cmpEqFail(expected, actual, expectedExpr, actualExpr);
}

#define EXPECT_RV_EQ(first, second) EXPECT_PRED_FORMAT4(cmpHelperRt, (first), (second), #first, #second)
```

However, connecting the "core" library file ("gtest/gtest.h") now solves this problem. Is this part of the library design that requires the user to explicitly connect the main library file, even in places where it is not particularly necessary, or have I encountered a bug?

**Comment by derekmauro** [comment]
`gtest/gtest_pred_impl.h` is an internal header, to be used only by the implementation. Directly including it is not supported. You are correct that `gtest/gtest.h` needs to be included.
