### ISSUE TITLE
Maintain "master" as an alternative name to "main" to avoid breaking build systems

### ISSUE THREAD

**Issue by greenfoo** [google/googletest#3976]
Hi.

I noticed "master" was recently renamed to "main". Would it be possible to add "master" back (at least for a few weeks) so that our build system doesn't break?

I will start working as soon as possible in the renaming process on my side and these extra weeks will give me some time.

My proposal:
1. Keep "main"
2. Create a new branch named "master" that points to where "main" is currently pointing
3. Only advance "main". Leave "master" pointing to the place "main" is currently pointing *now* but do not update it ever again.
4. (Optional) In a few weeks delete "main" (or don't ever delete it and keep it there for old build systems)

Thanks!

PS: The same proposal was accepted in other repos we depend on which also changed "master" to "main" and the transition period turned out to be a good solution.

**Comment by derekmauro** [comment]
Master was deleted nearly 9 months ago. If you really need a branch named master, and it is going to take weeks to do a rename, I would suggest just cloning this repository and creating a master branch to point at.
