### ISSUE TITLE
Does Not Compile With GCC < 6.1.0

### ISSUE THREAD

**Issue by andrej** [google/googletest#3979]
**Describe the bug**

GCC < 6.1.0 uses C++98 as default C++ mode. Googletest requires C++11. Trying to compile with GCC < 6.1.0 causes a lot of errors/warnings. Adding the `--std=c++11` or `--std=c++14` flag fixes the issue. I suggest the latter, since that is the default behavior of more recent GCC versions.

**Steps to reproduce the bug**

Attempt to build googletest from the most recent commit using an ancient GCC:

    mkdir build
    cd build
    cmake ..
    make VERBOSE=1

**Does the bug persist in the most recent commit?**

Yes.

**What operating system and version are you using?**

    Linux ubuntu 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:47 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

**What compiler and version are you using?**

    gcc (Ubuntu/Linaro 5.5.0-12ubuntu1~16.04) 5.5.0 20171010

I know it's old, but it's what I'm working with.

**What build system are you using?**

    cmake version 3.5.1

**Comment by derekmauro** [comment]
Please see my response to https://github.com/google/googletest/pull/3980.
