### ISSUE TITLE
Append multiple xml test reports of google test

### ISSUE THREAD

**Issue by GhassenJamoussi99** [google/googletest#3985]
I'm not sure if this is already possible. But here's the problem that I have:

I'm trying to generate an XML test report for multiple tests created with google tests.

Suppose I have 2 executable files: `test1.out` and `test2.out`.

To run both of them together, I used a shellscript:

    #!/bin/sh

    /test1.out --gtest_output="xml:testreport.xml"
    /test2.out --gtest_output="xml:testreport.xml"

I want to append both test reports together but in this case I'll just overwrite the `testreport.xml` of test1 with test2.

Is there a way on how to do this ?

**Comment by derekmauro** [comment]
Sorry, this is not supported by GoogleTest. You could try making one big test, or you could try standard unix file manipulation tools.
