### ISSUE TITLE
Need an Eclipse plug-in

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#40]
```
It would be nice to have an Eclipse plug-in for Google Test.

Josha at industrial logic has done some work here.
```

Original issue reported on code.google.com by `shiq...@gmail.com` on 29 Sep 2008 at 3:17

**Comment by anb0s** [comment]
Just tried Eclipse Neon with CDT 9.0 included:

1. Create a C++ project with gtest library linked
2. Include samples folder from gtest release (1.7.0) and compile it with own main() or one from samples
3. Install the plugin "C/C++ Unit Testing Support":
![unittestingsupport](https://cloud.githubusercontent.com/assets/95811/14509406/6162c58e-01cc-11e6-9719-7e4e7c193851.png)
4. Create a launch config and execute:
![unittestingsupport-runner](https://cloud.githubusercontent.com/assets/95811/14509459/b878b0d6-01cc-11e6-90fd-1f535642da96.png)
5. You should see the results in view:
![unittestingsupport-runner-view](https://cloud.githubusercontent.com/assets/95811/14509476/cdaface8-01cc-11e6-885f-048f5fa8a076.png)

**Comment by quicknir** [comment]
Can you check whether this works with type parameterized tests? I filed a bug about this in CDT 8.7 or 8.8: https://bugs.eclipse.org/bugs/show_bug.cgi?id=479289 (text reproduced here for simplicity).

When you use type parametrized tests in gtest, you get output of the following form:


[----------] 2 tests from TestCaseName/0, where TypeParam = TypeStruct<float, true>
[ RUN      ] TestCaseName/0.TestName
[       OK ] TestCaseName/0.TestName (0 ms)
[ RUN      ] TestCaseName/0.AnotherTestName
[       OK ] TestCaseName/0.AnotherTestName (1 ms)
[----------] 2 tests from TestCaseName/0 (1 ms total)

[----------] 2 tests from TestCaseName/1, where TypeParam = TypeStruct<float, false>
[ RUN      ] TestCaseName/1.TestName
[       OK ] TestCaseName/1.TestName (1 ms)
[ RUN      ] TestCaseName/1.AnotherTestName
[       OK ] TestCaseName/1.AnotherTestName (0 ms)
[----------] 2 tests from TestCaseName/1 (1 ms total)


When Eclipse sees this, it complains:

"Unknown error during parsing Google Test module output: A test case "TestName" belongs to test suite "TestCaseName/1", but the last started suite is "TestCaseName/0".

**Comment by gennadiycivil** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
