### ISSUE TITLE
CI tests for "live at head" not passing

### ISSUE THREAD

**Issue by cmdremily** [google/googletest#4004]
**Describe the bug**

CI tests for windows do not pass at HEAD since commit aa2e91fd6918519dafa3bee4aa706d04857e7d06.

**Steps to reproduce the bug**

Open commit history in GitHub and look at red crosses in CI builds.

**Does the bug persist in the most recent commit?**

Yes.

**Additional context**

The recommendation from GoogleTest is to "Live at Head", if this is the recommendation then HEAD must pass CI tests for all platforms at all commits on the `main` branch. Otherwise users could be broken.

**Comment by derekmauro** [comment]
The github-actions workflows are unofficial. The tests generated by kokoro-team are the ones we look at.

**Comment by cmdremily** [comment]
What tests? I'm an end user, I can't see these tests you're referring to? How am I supposed to see if I can pin to a specific committish if I can't see if the CI passed?
