### ISSUE TITLE
Alignment when using "EXPECT_THAT" and Eq matcher

### ISSUE THREAD

**Issue by shreyasbharath** [google/googletest#4018]
Alignment of text output when a test fails makes the failure hard to read. Can we get rid of the "is equal to" so you can easily spot the differences between actual and expected?

![image](https://user-images.githubusercontent.com/1886010/191874985-63b7dad3-d5c9-4b65-afc0-12bee8ef5858.png)

**Comment by asoffer** [comment]
This turns out to be surprisingly difficult to address, because it's part of the `Eq` matcher. We can't strip it generally, because it's necessary when `Eq` is used inside other matchers.

I believe `EXPECT_EQ(x, y)` should print more clearly.
