### ISSUE TITLE
Issues with installing google tests on macOS Monterey M1

### ISSUE THREAD

**Issue by Kr1eg3** [google/googletest#4026]
**Describe the bug**
I am trying to install Google tests, but I get an error. Tried to find a solution on the stackoverflow, but nothing from there worked for me.

I'm using macOS Version 12.6 Monterey on M1 Max chip.

❯ cmake --version
cmake version 3.24.2

❯ gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

❯ clang -v
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

❯ mkdir build && cd build
❯ cmake ..
CMake Deprecation Warning at CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at googlemock/CMakeLists.txt:45 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Found PythonInterp: /opt/homebrew/bin/python3.10 (found version "3.10.6")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/build
❯ make -j4
[ 12%] Building CXX object googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 25%] Linking CXX static library ../lib/libgtest.a
[ 25%] Built target gtest
[ 50%] Building CXX object googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
[ 50%] Building CXX object googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
In file included from /Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/src/gmock-all.cc:39:
In file included from /Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock.h:59:
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-actions.h:455:3: error: definition of implicit copy constructor for 'PolymorphicAction<testing::internal::ReturnNullAction>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(PolymorphicAction);
  ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/internal/gtest-port.h:682:8: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  void operator=(type const &) = delete
       ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-actions.h:1011:10: note: in implicit copy constructor for 'testing::PolymorphicAction<testing::internal::ReturnNullAction>' first required here
  return MakePolymorphicAction(internal::ReturnNullAction());
         ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-actions.h:455:3: error: definition of implicit copy constructor for 'PolymorphicAction<testing::internal::ReturnVoidAction>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(PolymorphicAction);
  ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/internal/gtest-port.h:682:8: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  void operator=(type const &) = delete
       ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-actions.h:1016:10: note: in implicit copy constructor for 'testing::PolymorphicAction<testing::internal::ReturnVoidAction>' first required here
  return MakePolymorphicAction(internal::ReturnVoidAction());
         ^
In file included from /Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/src/gmock-all.cc:39:
In file included from /Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock.h:61:
In file included from /Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-function-mocker.h:39:
In file included from /Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:47:
In file included from /Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-spec-builders.h:75:
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:1506:3: error: definition of implicit copy constructor for 'FloatingEqMatcher<double>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(FloatingEqMatcher);
  ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/internal/gtest-port.h:682:8: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  void operator=(type const &) = delete
       ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:3632:10: note: in implicit copy constructor for 'testing::internal::FloatingEqMatcher<double>' first required here
  return internal::FloatingEqMatcher<double>(rhs, false);
         ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:1506:3: error: definition of implicit copy constructor for 'FloatingEqMatcher<float>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(FloatingEqMatcher);
  ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/internal/gtest-port.h:682:8: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  void operator=(type const &) = delete
       ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:3660:10: note: in implicit copy constructor for 'testing::internal::FloatingEqMatcher<float>' first required here
  return internal::FloatingEqMatcher<float>(rhs, false);
         ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:721:3: error: definition of implicit copy constructor for 'StrEqualityMatcher<std::string>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(StrEqualityMatcher);
  ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/internal/gtest-port.h:682:8: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  void operator=(type const &) = delete
       ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/gtest-matchers.h:454:7: note: in implicit copy constructor for 'testing::internal::StrEqualityMatcher<std::string>' first required here
class PolymorphicMatcher {
      ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:3813:10: note: in implicit move constructor for 'testing::PolymorphicMatcher<testing::internal::StrEqualityMatcher<std::string>>' first required here
  return MakePolymorphicMatcher(
         ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:778:3: error: definition of implicit copy constructor for 'HasSubstrMatcher<std::string>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(HasSubstrMatcher);
  ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/internal/gtest-port.h:682:8: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  void operator=(type const &) = delete
       ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/gtest-matchers.h:454:7: note: in implicit copy constructor for 'testing::internal::HasSubstrMatcher<std::string>' first required here
class PolymorphicMatcher {
      ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:3842:10: note: in implicit move constructor for 'testing::PolymorphicMatcher<testing::internal::HasSubstrMatcher<std::string>>' first required here
  return MakePolymorphicMatcher(
         ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:835:3: error: definition of implicit copy constructor for 'StartsWithMatcher<std::string>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(StartsWithMatcher);
  ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/internal/gtest-port.h:682:8: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  void operator=(type const &) = delete
       ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/gtest-matchers.h:454:7: note: in implicit copy constructor for 'testing::internal::StartsWithMatcher<std::string>' first required here
class PolymorphicMatcher {
      ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:3849:10: note: in implicit move constructor for 'testing::PolymorphicMatcher<testing::internal::StartsWithMatcher<std::string>>' first required here
  return MakePolymorphicMatcher(
         ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:891:3: error: definition of implicit copy constructor for 'EndsWithMatcher<std::string>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(EndsWithMatcher);
  ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/internal/gtest-port.h:682:8: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  void operator=(type const &) = delete
       ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/gtest-matchers.h:454:7: note: in implicit copy constructor for 'testing::internal::EndsWithMatcher<std::string>' first required here
class PolymorphicMatcher {
      ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:3856:10: note: in implicit move constructor for 'testing::PolymorphicMatcher<testing::internal::EndsWithMatcher<std::string>>' first required here
  return MakePolymorphicMatcher(internal::EndsWithMatcher<std::string>(suffix));
         ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:721:3: error: definition of implicit copy constructor for 'StrEqualityMatcher<std::wstring>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(StrEqualityMatcher);
  ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/internal/gtest-port.h:682:8: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  void operator=(type const &) = delete
       ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/gtest-matchers.h:454:7: note: in implicit copy constructor for 'testing::internal::StrEqualityMatcher<std::wstring>' first required here
class PolymorphicMatcher {
      ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:3865:10: note: in implicit move constructor for 'testing::PolymorphicMatcher<testing::internal::StrEqualityMatcher<std::wstring>>' first required here
  return MakePolymorphicMatcher(
         ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:778:3: error: definition of implicit copy constructor for 'HasSubstrMatcher<std::wstring>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(HasSubstrMatcher);
  ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/internal/gtest-port.h:682:8: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  void operator=(type const &) = delete
       ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/gtest-matchers.h:454:7: note: in implicit copy constructor for 'testing::internal::HasSubstrMatcher<std::wstring>' first required here
class PolymorphicMatcher {
      ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:3894:10: note: in implicit move constructor for 'testing::PolymorphicMatcher<testing::internal::HasSubstrMatcher<std::wstring>>' first required here
  return MakePolymorphicMatcher(
         ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:835:3: error: definition of implicit copy constructor for 'StartsWithMatcher<std::wstring>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(StartsWithMatcher);
  ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/internal/gtest-port.h:682:8: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  void operator=(type const &) = delete
       ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/gtest-matchers.h:454:7: note: in implicit copy constructor for 'testing::internal::StartsWithMatcher<std::wstring>' first required here
class PolymorphicMatcher {
      ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:3901:10: note: in implicit move constructor for 'testing::PolymorphicMatcher<testing::internal::StartsWithMatcher<std::wstring>>' first required here
  return MakePolymorphicMatcher(
         ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:891:3: error: definition of implicit copy constructor for 'EndsWithMatcher<std::wstring>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(EndsWithMatcher);
  ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/internal/gtest-port.h:682:8: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  void operator=(type const &) = delete
       ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googletest/include/gtest/gtest-matchers.h:454:7: note: in implicit copy constructor for 'testing::internal::EndsWithMatcher<std::wstring>' first required here
class PolymorphicMatcher {
      ^
/Users/arkadiypozharskiy/Work/halcon_open_source/3rd_party/googletest/googlemock/include/gmock/gmock-matchers.h:3908:10: note: in implicit move constructor for 'testing::PolymorphicMatcher<testing::internal::EndsWithMatcher<std::wstring>>' first required here
  return MakePolymorphicMatcher(
         ^
[ 62%] Linking CXX static library ../lib/libgtest_main.a
[ 62%] Built target gtest_main
12 errors generated.
make[2]: *** [googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o] Error 1
make[1]: *** [googlemock/CMakeFiles/gmock.dir/all] Error 2
make: *** [all] Error 2

[CMakeLists.txt](https://github.com/google/googletest/files/9691408/CMakeLists.txt)

**Comment by derekmauro** [comment]
You appear to be using GoogleTest 1.10.0. Please upgrade to the latest version and let us know if you still have this issue.

**Comment by Kr1eg3** [comment]
Thank you! Indeed, the new version has solved this problem. Thank you for your reply.
