### ISSUE TITLE
Enforce printability of all types (optionally)

### ISSUE THREAD

**Issue by stefanhaller** [google/googletest#4027]
**Why do we need this feature?**

For failed assertions, GoogleTest tries to print the arguments if it can, falling back to printing raw bytes if not. This is convenient for writing tests, but if you have a policy that requires all types to be printable, it's very hard to ensure this. You basically have to manually make each assertion fail, inspecting the test output to see whether raw bytes are printed.

Furthermore, even if you manually ensured this once, it can easily break thereafter, for example when code is moved around in refactorings. Nobody will notice until the next time a test fails, and only prints raw bytes.

And finally, this can lead to ODR issues that are extremely hard to figure out. For example, if you have your printers in separate header files (because you don't want them to be visible to production code), then forgetting to include this header in one test file can break printing for other test files too, even if those do include the printer header.

For all these reasons it may be desirable to configure gtest to not have a raw bytes fallback printer, so that compilation fails if a type used in an assertion is not printable. This must be optional of course.
 
**Describe the proposal**

One way to implement the feature is to provide an optional define, say GTEST_FALLBACK_PRINTER; it can be defined to a function that will be called when no other printer could be found. Defining this to a function that doesn't exist achieves the desired effect of causing a compilation error.

The Catch2 test framework has a [very similar feature](https://github.com/catchorg/Catch2/blob/devel/src/catch2/catch_tostring.hpp#L131) that can be used in exactly the same way.

**Is the feature specific to an operating system, compiler, or build system version?**

No.

**Comment by asoffer** [comment]
Thanks for the proposal. We are not going to accept this for two reasons:
1. Adding extra configuration knobs makes testing and support twice as expensive, so we want to make sure we're really getting the value out of this.
2. We do not believe this is a good way to enforce printability. In particular, our printing mechanism already does a bunch of strange things for enums and other types, so we already won't be able to catch non-printability for those. I'd suggest writing an IsPrintable type-trait and asserting on that.

**Comment by stefanhaller** [comment]
Thanks for having a look. I accept 1. as a valid reason to reject this. Looks like we'll have to maintain our own fork then.

I don't agree with 2. as a reason though: I suppose the "strange things for enums and other types" is referring to how you print enums as ints in a generic way. I don't see how that contradicts the proposal; I consider printing enums as ints "good enough", and the enforcement of printability only applies to types that don't have such a generic "good enough" fallback, i.e. those that would otherwise fall back to the raw bytes printer. This is exactly what we want. (In catch2, which doesn't have a raw bytes printer, it's those types that would otherwise print as question marks.)

Anyway, if this doesn't change your mind, I have two more questions:
1. Would you mind elaborating a little bit on your suggestion of "writing an IsPrintable type-trait and asserting on that"? I don't understand what exactly you have in mind here.
2. I still think that the first commit ("[Add ScopedEnumPrinter](https://github.com/google/googletest/pull/4028/commits/760c4bda98f20732cddc12d6c641196d12cf553e)) is useful on its own, would you accept a PR for just that one?
