### ISSUE TITLE
::testing::InSequence marked as unused, triggers -Wused-but-marked-unused Clang warning

### ISSUE THREAD

**Issue by carlosgalvezp** [google/googletest#4048]
Hi,

The following code triggers the `-Wused-but-marked-unused` Clang warning:

```cpp
#include <gmock/gmock.h>

int main()
{
    ::testing::InSequence dummy;
}
```

```
<source>:5:16: warning: 'InSequence' was marked unused but was used [-Wused-but-marked-unused]
    ::testing::InSequence dummy;
               ^
```

Repro: https://godbolt.org/z/d1KdM59he

This is because the `InSequence` class is marked as unused. I can imagine the goal is to prevent `-Wall` from complaining about unused variables, but Clang is complaining that the **class** itself (not the variable) is used while marked unused.

Would it make sense to wrap this inside a macro instead? Something like:

`#define GTEST_IN_SEQUENCE (::testing::InSequence dummy __attribute__((unused)))`

Then the `unused` attribute is applied to the **variable** (`dummy`), not to the **class** (`InSequence`).

**Comment by derekmauro** [comment]
It looks like the marking InSequence as unused is incorrect since it has a constructor and destructor that do things.
