### ISSUE TITLE
How to do death test for a limit time?

### ISSUE THREAD

**Issue by LLsmile** [google/googletest#4049]
I need to check whether my code will crash or not. So I add a death test for my code. But some codes run for a long time which is also needed to be recorded. I found [the timeout checker](https://github.com/doleron/basic-googletest-example/blob/master/test/timeout_check.cpp). But how can I do the death test with timeout checker? 
Such as `  TEST_TIMEOUT_BEGIN
  ExpectDeath(function());
  TEST_TIMEOUT_FAIL_END(1000)` ?

**Comment by derekmauro** [comment]
There are many ways of doing this. You could rely on the test runner to terminate your test if it doesn't finish in an expected amount of time, for example both Bazel and CTest provide test timeouts. Something similar to the timeout checker code you linked to is also possible. We have no plans to add this functionality.
