### ISSUE TITLE
How to do death test as EXPECT_NOT_DEATH?

### ISSUE THREAD

**Issue by LLsmile** [google/googletest#4051]
When testing all modules of a project, I need to test the modules with different inputs. In some cases, the module may crash but most of them will not. So I need a EXPECT_NOT_DEATH function to get all crashed modules. How can I achieve this ? Is there any help?

**Comment by derekmauro** [comment]
I'm not sure I understand. Can you provide an example of what you are trying to do?

**Comment by LLsmile** [comment]
I need to test some Fuctions. Some of them may stuck in endless loop or crash, such as FunctionA and FunctionB.
`void FunctionA() {
sleep(9999999);
}
void FuctionB() {
int a[2] = {0, 1};
a[100] = 10;
}`
I want to record those abnormal status.
