### ISSUE TITLE
Generate gtest_output on sigkill

### ISSUE THREAD

**Issue by GuyMalinovitch** [google/googletest#4056]
When killing a long test suite mid-run, we should generate xml output.
example - I have a long test suite (over 24 hours) running on a shared resource. sometimes it gets killed by another user, and i lose track of which tests ran, and which dont. to avoid that - i need to parsed the logs which is highly inefficient.

**Comment by derekmauro** [comment]
We have no plans to do this. It is unlikely to even be reliable. Consider splitting up the test into smaller pieces.
