### ISSUE TITLE
ASSERT_THAT and wildcard matcher not compiling with multiparameter template

### ISSUE THREAD

**Issue by manquat-lo** [google/googletest#4057]
**Describe the bug**

When trying to use ASSERT_THAT (or EXPECT_THAT) with the wildcard matcher A<type>() if the type is a template with multiple parameters (map or pair...) cannot compile the code. Error log:
- "warning C4002: too many actual parameters for macro 'ASSERT_THAT'"
and then a bunch of syntax error:  
- "error C2059: syntax error: ')'"
- "error C2143: syntax error: missing ';' before '}'"

Should behave normally as there is nothing specific to this king of template. The error can be workaround by simply declaring a typedef or using before (see example code below). Based on the errors I would say that there is a bug in the parsing of the macro *_THAT.

`
#include <gtest/gtest.h>
#include <gmock/gmock.h>
#include <map>

TEST(TempsTest, AssertMap)
{
	int i;
	std::map<int, int> m;

	using pp = std::pair<int, int>;
	pp p;
	

	ASSERT_THAT(i, testing::A<int>());
	ASSERT_THAT(p, testing::A<pp>()); // this will compile correctly (and work)
	ASSERT_THAT(m, testing::A<std::map<int, int>>()); // this won't compile
}
`

I'm on windows 10 enterprise 21H2, using gtest/cci.20210126 compiled with MSVC 19.0.24245.0.

**Comment by apcountryman** [comment]
This is expected preprocessor behavior. Wrapping the macro argument in parenthesis should fix this:
```c++
ASSERT_THAT(m, (testing::A<std::map<int, int>>()));
```

**Comment by derekmauro** [comment]
The answer from @apcountryman is correct.
