### ISSUE TITLE
How to set GTEST_FAIL_FAST in C++ code?

### ISSUE THREAD

**Issue by LLsmile** [google/googletest#4077]
Sorry to ask so stupid question, but I found nothing in google test documents about how to do it. The only solution is to add "--gtest_fail_fast" in command. But I want to do it just in code.

**Comment by derekmauro** [comment]
http://google.github.io/googletest/advanced.html#death-test-styles shows some ways to do this for `death_test_style`, so in your case replace `death_test_style` with `fail_fast` (leave off the `gtest_` part).
