### ISSUE TITLE
Support enum values as type parameters in ::testing::Types

### ISSUE THREAD

**Issue by nemeshnorbert** [google/googletest#4078]
For the gtest of version 1.10 the follwing code does not compile
```
#include <gtest/gtest.h>

enum class E { e1, e2 };

using MyTypes = ::testing::Types<E::e1, E::e2>;


int main() {
    return 0;
}
```
I believe the problem could be solved if one replaces `class` with `typename` in the definition of `::testing::Types`.

**Comment by nemeshnorbert** [comment]
Additional context. Please do the following
1. Paste this code into the editor window on godbolt.org
2. Click `Add new` in the editor window, click `Compiler`, in the opened `Compiler` window click `Libraries` and add `Google Test 1.10.0`.

You will see that code does not compile. 

I want to use this feature because I want to use a Fixture template parametrized by values of my Enum class.

**Comment by shtanko-sv** [comment]
@nemeshnorbert I don't know if it still actual for you but you can use simple wrapper class to solve this:
```cpp
enum class E { e1, e2 };

template <E e> struct EnumWrapper { static constexpr E value = e; };

using MyTypes = ::testing::Types<EnumWrapper<E::e1>, EnumWrapper<E::e2>>;

template <typename T>
struct FooTest : public testing::Test {
    static constexpr E e = T::value;
};
```

**Comment by nemeshnorbert** [comment]
@shtanko-sv Thank you for this suggestion! I thought of such workaround but in the end completely redesigned my test suite.
