### ISSUE TITLE
Mocking Cookbook: Capter "Mocking Non-virtual Methods" is incomplete

### ISSUE THREAD

**Issue by mschmidtesd** [google/googletest#4081]
In chapter "Mocking Non-virtual Methods" of the Mocking Cookbook the paragraph before the last starts with "One way to do it is ..." and explains the first way. Then the chapter ends without mentioning any other way.

**Comment by asoffer** [comment]
"One way to do this" was not intended to indicate that the documentation would include all possible (or even multiple ways). There are multiple ways to do everything in C++, and we're only offering an explanation of the one, but want to indicate that there are indeed others.
