### ISSUE TITLE
Please fix failing tests (last passing commit was from 15 Oct 2022)

### ISSUE THREAD

**Issue by tellypresence** [google/googletest#4114]
### Describe the issue

Last revision showing green checkmark is from 15 Oct 2022

### Steps to reproduce the problem

Simply open the commits and look at the red "X"'s
![red_xs_Screenshot 2023-01-03 184441](https://user-images.githubusercontent.com/26958898/210475337-35df60c9-5e87-4559-a5c5-bd3d7b03e174.png)

### What version of GoogleTest are you using?

N/A: this is about "live at head" when tests are failing

### What operating system and version are you using?

N/A: this is about "live at head" when tests are failing

### What compiler and version are you using?

N/A: this is about "live at head" when tests are failing

### What build system are you using?

N/A: this is about "live at head" when tests are failing

**Comment by dinord** [comment]
We updated documentation to point out that the maintainers do not consider GitHub Actions as the official CI: https://github.com/google/googletest/commit/bba28fa8b2ef2d9725302ab8da0ca7c1a4a81715

We have no plans to fix them. Community contributions are welcome.
