### ISSUE TITLE
Multiple warnings during compilation

### ISSUE THREAD

**Issue by GaryElshaw** [google/googletest#4141]
### Describe the issue

Initially we thought this might be a gcc variation issue, but is there potentially something else going on with the number of warnings? Compilation isn't a problem, but the number of warnings is striking.

### Steps to reproduce the problem

Using build directory and 'cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..'

### What version of GoogleTest are you using?

1.13.0

### What operating system and version are you using?

Manjaro 43.2/Wayland

### What compiler and version are you using?

GCC 12.2.1
clang version 15.0.7

### What build system are you using?

cmake version 3.25.2

### Additional context

Warnings

[googletest-warnings.txt](https://github.com/google/googletest/files/10561582/googletest-warnings.txt)

**Comment by asoffer** [comment]
Most of these warnings look incorrect. For example this one appears repeatedly
```
warning: potential null pointer dereference [-Wnull-dereference]
  588 |   bool should_run() const { return should_run_; }
```
but `should_run_` is a bool. It is likely referring to the `this` pointer. Because the `this` pointer can never be null (it's UB in the same way references must not be null), at best this warning is flagging issues at the wrong point in the code.

This looks like a particularly bad bug in GCCs warning generator. I would suggest turning off this warning entirely, since it's not generating valuable findings and perhaps also filing a bug with GCC.

I'm going to close this issue because these warnings don't look actionable. Please reopen if you believe there's more to discuss.

**Comment by GaryElshaw** [comment]
Thanks for the help and info.

**Comment by asoffer** [comment]
Another example:

```
warning: potential null pointer dereference [-Wnull-dereference]
  357 |             return nullptr;
      |                    ^~~~~~~
```

I'm not sure what's going on here... this one seems very clearly to be just a bug in the warning. No dereferences are taking place on this line.

**Comment by mikedld** [comment]
These seem correct to me. For the first one with `should_run_`, the complete message is:
```
In file included from .../googletest/src/gtest-all.cc:38:
In member function `bool testing::TestSuite::should_run() const`,
    inlined from `static void testing::internal::PrettyUnitTestResultPrinter::PrintFailedTestSuites(const testing::UnitTest&)` at .../googletest/src/gtest.cc:3565:31:
.../googletest/include/gtest/gtest.h:703:36: warning: potential null pointer dereference [-Wnull-dereference]
  703 |   bool should_run() const { return should_run_; }
      |                                    ^~~~~~~~~~~
```

Last reported location (gtest.h:703:36) is where access to null is taking place (you're correct, it's `this` that is null), next to last location (gtest.cc:3565:31) is the calling site:
```cpp
    const TestSuite& test_suite = *unit_test.GetTestSuite(i);
    if (!test_suite.should_run()) {
      continue;
    }
```

Looking at `UnitTest::GetTestSuite()`:
```cpp
const TestSuite* UnitTest::GetTestSuite(int i) const {
  return impl()->GetTestSuite(i);
}
```

Looking at `UnitTestImpl::GetTestSuite()`:
```cpp
  const TestSuite* GetTestSuite(int i) const {
    const int index = GetElementOr(test_suite_indices_, i, -1);
    return index < 0 ? nullptr : test_suites_[static_cast<size_t>(i)];
  }
```

So you're creating a reference from a potentially null pointer.

Not going to explain the one in announcer.cc (second one you quite) but it's correct as well, just not relevant here as it's in libtransmission's code.

**Comment by mikedld** [comment]
@asoffer, any thoughts on the above?
