### ISSUE TITLE
Implement testing::internal::GetTypeName in terms of a class template

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#415]
```
I needed a way to customize the printing of a type name to accomodate my needs.

Currently, testing::internal::GetTypeName is a plain old template function.
However, you can't partially specialize function templates.

The solution is to implement testing::internal::GetTypeName in terms of a class 
template.

This is necessary to allow people to customize output, by partially 
specializing that implementation class template.

See the patch attached.

Gregory
```

Original issue reported on code.google.com by `gregory....@gmail.com` on 19 Jun 2012 at 10:09

Attachments:
- [GetTypeNameImpl.patch](https://storage.googleapis.com/google-code-attachments/googletest/issue-415/comment-0/GetTypeNameImpl.patch)

**Comment by thirtytwobits** [comment]
I'd like to request this is reopened, that is that a solution outside of the internal namespace is pursued. Embedded projects often disable rtti across the board. Providing a way to manually provide GetTypeName overrides would allow such projects to print types in parameterized tests.
