### ISSUE TITLE
[Bug]: bazel build doesn't generate libgmock_main.so libgmock.so

### ISSUE THREAD

**Issue by wssbygone** [google/googletest#4154]
### Describe the issue

cmake build, it'll generate libgmock_main.so  libgmock.so  libgtest_main.so  and  libgtest.so.
bazel build, there will be no generated file libgmock_main.so  & libgmock.so.

### Steps to reproduce the problem

linux cmd line : bazel build -c opt --strip=always  --linkopt=-Wl,--strip-all :all

### What version of GoogleTest are you using?

googletest_1.8.1

### What operating system and version are you using?

ubuntu 18.04

### What compiler and version are you using?

gcc 9.4

### What build system are you using?

bazel 6.0.0

**Comment by derekmauro** [comment]
Please see the build file: https://github.com/google/googletest/blob/main/BUILD.bazel

Under Bazel the target name is `gtest_main`. Bazel users should depend on target names, not individual files.

```
$ ls bazel-bin
external    libgtest_main.so           libgtest.so           _objs
googlemock  libgtest_main.so-2.params  libgtest.so-2.params  _solib_k8
```

**Comment by wssbygone** [comment]
> Please see the build file: https://github.com/google/googletest/blob/main/BUILD.bazel
> 
> Under Bazel the target name is `gtest_main`. Bazel users should depend on target names, not individual files.
> 
> ```
> $ ls bazel-bin
> external    libgtest_main.so           libgtest.so           _objs
> googlemock  libgtest_main.so-2.params  libgtest.so-2.params  _solib_k8
> ```
I see,  but it seems that there is no target will generate the libraries libgmock_main.so & libgmock.so.
