### ISSUE TITLE
[FR]: Make ColoredPrintf available for external use

### ISSUE THREAD

**Issue by Anton-V-K** [google/googletest#4185]
### Does the feature exist in the most recent commit?

`ColoredPrintf` was made externally inaccessible by commits:
* https://github.com/google/googletest/commit/482ac6ee63429af2aa9c44f4e6427873fb68fb1f (`enum class GTestColor` was moved into anonymous namespace)
* https://github.com/google/googletest/commit/7b1cf6dd5fbe0c22c5e638fce8caf7f0f5c1abbf (`static` modified added to `ColoredPrintf`)

### Why do we need this feature?

`ColoredPrintf` used to be available for external use to have custom output like [explained here](https://stackoverflow.com/a/29155677/536172).
See also https://github.com/google/googletest/issues/1487

### Describe the proposal.

The usage approach is explained here https://stackoverflow.com/a/29155677/536172 (it can't be used as is with the current sources because enum values were renamed).
The minimal changes to apply to `googletest\googletest\src\gtest.cc`:
1. Move the declaration of `enum class GTestColor` out of anonymouse namespace
2. Remove `static` modified from definition of `ColoredPrintf`
Ideally the color printing support should be available through a public API.

### Is the feature specific to an operating system, compiler, or build system version?

The feature is generic

**Comment by asoffer** [comment]
Thanks for the proposal. GoogleTest is generally not a printing library (though we cannot avoid publicizing some printing utilities). So we'd prefer not to add support/compatibility promises for these utilities.
