### ISSUE TITLE
[FR]: Add Compile-Time/Meta-Programming Tests

### ISSUE THREAD

**Issue by thirtytwobits** [google/googletest#4191]
### Does the feature exist in the most recent commit?

no

### Why do we need this feature?

Since C++11, more and more of modern C++ programs are written as compiler-time meta-programs. With the proliferation of `static_assert`, `constexpr`, `std::enable_if`, `noexcept()`, and `explicit()` (etc) there are a lot of branches taken at compile time that are not available at runtime. While parameterized tests provide an easy way to generate tests to cover the output of these meta-programs they cannot test the meta-program itself.

### Describe the proposal.

Over at the [OpenCyphal](https://github.com/OpenCyphal) CETL project we use a brittle technique of ["negative CTests"](https://github.com/OpenCyphal-Garage/CETL/blob/main/cetlvast/cmake/suites/compile.cmake) to try to cover this which are similar in concept to googletest deathtests but lack the key feature of pattern matching the resulting output to ensure the compiler failure was the required/expected failure. They also require individual files with c `main` functions for each test case which is cumbersome.

Googletest could reuse the death-test pattern to automate generation of such tests and unlock coverage of a whole class of invariants that are enforced by meta-programming.

### Is the feature specific to an operating system, compiler, or build system version?

not operating system nor compiler specific.

**Comment by asoffer** [comment]
I don't think this is something we're likely to add support for, though we certainly understand the value of it. As a workaround, if your behavior is detectable, `static_assert` can be useful. If it's not detectable (a hard compilation error), we don't have much of a suggestion here, unfortunately... We're unlikely to add negative-compilation testing facilities.
