### ISSUE TITLE
[Bug]: gtest 1.12.1 crashes on shutdown

### ISSUE THREAD

**Issue by kzhdev** [google/googletest#4193]
### Describe the issue

gtest 1.12.1 segmentation fault on shutdown after all unit tests successfully passed

![image](https://user-images.githubusercontent.com/1855243/226033546-ece32154-bd29-4d96-b321-c9a88970d3c8.png)

![image](https://user-images.githubusercontent.com/1855243/226033992-1962ad31-53e2-47fb-a9db-8ae2294d7b4a.png)

### Steps to reproduce the problem

After upgrading to 1.12.1, the unit test app crashes.

### What version of GoogleTest are you using?

1.12.1

### What operating system and version are you using?

centos 7

### What compiler and version are you using?

clang

### What build system are you using?

cmake 3.24.2

**Comment by derekmauro** [comment]
We cannot reproduce this issue. Please supply all code and commands to build and run the code.

**Comment by kzhdev** [comment]
Sorry, I can't supply all codes. That is a big project, and it is private. It happens when we build with D_GLIBCXX_DEBUG (when using debug version of containers). I hope that helps.

**Comment by derekmauro** [comment]
There is a good chance `-D_GLIBCXX_DEBUG` has introduced an ODR violation, but we can't investigate it without a reproducer. Feel free to reopen if you can provide a simplified test case and ALL build commands (telling us that  `-D_GLIBCXX_DEBUG` is used doesn't tell us if it was used safely - we need all commands for that).

**Comment by kzhdev** [comment]
simply run --gtest_list_tests command will see the crash
