### ISSUE TITLE
[FR]: Remove warnings with the NVIDIA C++ Compiler

### ISSUE THREAD

**Issue by gonzalobg** [google/googletest#4196]
### Does the feature exist in the most recent commit?

No.

### Why do we need this feature?

To be able to compile tests that use the C++ parallel algorithms on GPUs  with -Werror without spurious warnings triggering errors.

### Describe the proposal.

Ensure google test compiles with the NVIDIA C++ compiler. 
The changes needed are available in this PR #4103 .

### Is the feature specific to an operating system, compiler, or build system version?

Yes, it is specific to the NVIDIA C++ compiler.

**Comment by tobbi** [comment]
@derekmauro @gonzalobg This can be closed as the mentioned PR was already merged, right?

**Comment by gonzalobg** [comment]
Yes!
