### ISSUE TITLE
[FR]: Jupyter-book docs with xeus-cling and JupyterLite

### ISSUE THREAD

**Issue by westurner** [google/googletest#4209]
### Does the feature exist in the most recent commit?

- No (2023-04-01)

### Why do we need this feature?

- generate a per-page TOC Table of Contents with subheadings
- https://google.github.io/googletest/samples.html
  - inline these
  - dynamic code examples with the xeus-lite Jupyter kernel
    - https://blog.jupyter.org/xeus-lite-379e96bb199d?gi=4577402d6287 @DerThorsten
- index terms
- glossary terms
- https://jupyterbook.org/en/stable/intro.html

### Describe the proposal.

- Generate a jupyter-book skeleton
- Copy the docs into it
- Update the `_toc.yml`
- Reformat them
- Update the `_config.yml`
- https://jupyterbook.org/en/stable/start/create.html#anatomy-of-a-jupyter-book
- https://jupyterbook.org/en/stable/interactive/launchbuttons.html
  - https://github.com/executablebooks/jupyter-book/issues/1661
  - https://jupyterlite.readthedocs.io/en/latest/
  - https://jupyterlite.readthedocs.io/en/latest/quickstart/embed-repl.html
- ( https://jupyterbook.org/en/stable/explain/sphinx.html#how-to-replicate-jupyter-books-functionality-in-sphinx
  - PERF: read gohugoio/hugo and rewrite docutils+sphinx in Go/Rust @bep @spf13 (Linux docs, Python docs, ReadTheDocs,) )
- https://jupyterbook.org/en/stable/publish/gh-pages.html#automatically-host-your-book-with-github-actions
  > Here is a simple YAML configuration for a Github Action that will publish your book to a `gh-pages` branch.

### Is the feature specific to an operating system, compiler, or build system version?

No. https://github.com/nektos/act will run GitHub Actions locally. (e.g. Gitea Actions also builds with nektos/act and can also be installed locally (https://gitea.com/gitea/homebrew-gitea#gitea-homebrew https://docs.gitea.io/en-us/install-with-docker-rootless/ https://docs.gitea.io/en-us/install-on-kubernetes/ ) if GitHub service dependency is ever inadvisable)

**Comment by dinord** [comment]
Thanks for the suggestion. Dynamic code examples could be nice, but we have no plans to add them right now. We would not accept open source contributions in that direction either, as they would make maintenance of internal docs more complicated.
