### ISSUE TITLE
CMAKE_CXX_FLAGS are duplicated

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#421]
```
I found a problem with the code in internal_utils.cmake when including the 
CMakeLists for GMock in a larger project  that already defines CMAKE_CXX_FLAGS 
to include flags that are not repeatable.

Things crash and burn because calling set_target_properties() to set the flags 
for a target actually appends them to the existing flags[1] (resulting in 
duplicates because of the code on line 113).

Seems like when you initialize ${cxx_no_exception} you could just remove 
${CMAKE_CXX_FLAGS} like you have for ${cxx_exception}.

[1]: 
http://stackoverflow.com/questions/5096881/does-set-target-properties-in-cmake-o
verride-cmake-cxx-flags
```

Original issue reported on code.google.com by `j...@kirkconsulting.co.uk` on 18 Oct 2012 at 7:36

**Comment by dholladay00** [comment]
I am working on a project that has CUDA code and thus requires the use of the nvcc compiler. Repeated flags results in a compile time error (`nvcc fatal   : redefinition of argument 'std'`), specifically with the debug compiler flags (`-gdwarf-2` etc.). I would like to compile googletest with the same flags as the rest of my project.

I see that this issue has been open for a while, is there a time-line on its resolution?
