### ISSUE TITLE
[FR]: Publish this dependency to Maven

### ISSUE THREAD

**Issue by jaredsburrows** [google/googletest#4217]
### Does the feature exist in the most recent commit?

No

### Why do we need this feature?

Make this easily accessible for Gradle developers.

### Describe the proposal.

See example published here:
https://mvnrepository.com/artifact/org.gradle/googletest/1.8.0

See local build example here:
https://github.com/gradle/native-samples/blob/49caeb5c31ba0b412239eb77564755c0eabeab82/cpp/library-with-tests/build.gradle#L13

See local gradle prebuilt here:
https://github.com/gradle/native-samples/blob/49caeb5c31ba0b412239eb77564755c0eabeab82/cpp/simple-library/build.gradle#L20

Similar to:
https://android.googlesource.com/platform/tools/ndkports

Potential live example:
https://sourceforge.net/p/gtest-gradle/wiki/Home/

Can we help maintain a version from Google and publish this to Maven or the https://maven.google.com repo?

Question originally asked here but with no context: https://github.com/google/googletest/issues/1179. We can use the Gradle examples to package and publish this to Maven.

### Is the feature specific to an operating system, compiler, or build system version?

macOS
Linux
Windows

**Comment by dinord** [comment]
In terms of build systems, we only support Bazel and CMake: http://google.github.io/googletest/platforms.html  
We do not plan to support Gradle at this time.

**Comment by jaredsburrows** [comment]
Id be more than happy to help write the support we need for this. Why close this so quickly?

**Comment by dinord** [comment]
What would we need to change in this repo in order to support Gradle?

**Comment by dinord** [comment]
I'm closing because it's been 2 weeks since I asked the question, because there doesn't seem to be anything actionable within the googletest repo, and because we have no plans to support Maven for our own needs.
