### ISSUE TITLE
Does googletest support C++0x/11?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#422]
```
Does googletest support C++0x/11?
If not so, do you intend to support it later?

Using this library with -std=C++11 (-std=C++0x) for gcc is not possible due to 
a list of errors. I did not check it on VC++.

As far as using syntax sugar of new standards is very attractive, I think, it 
is good idea to support them.

Compliling several different binaries with different flags is not an option for 
it is not "easy to use". 

Thanks

```

Original issue reported on code.google.com by `dmit...@interlink-ua.com` on 23 Oct 2012 at 9:44

**Comment by KindDragon** [comment]
Can be closed

**Comment by charterchap** [comment]
gcc w/ c++14 on cygwin cmake
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -DGTEST_OS_CYGWIN=1 -DGTEST_USE_OWN_TR1_TUPLE=1 -DGTEST_HAS_TR1_TUPLE=1 -std=gnu++14  -Wno-narrowing")

**Comment by michab66** [comment]
chartercap's comment uses -std=gnu++14.  Actually the question was whether -std=c++11 is working.

I am working with Google Test 1.8.0 and gcc. This cannot be compiled using -std=c++11.

So the issue should not be closed.

**Comment by michab66** [comment]
It took some time, but I found a workaround.  My concrete problem was that gcc did exclude some POSIX/XOPEN symbols when compiling with -std=c++11
This can be solved by defining the following symbols:

#define _POSIX_SOURCE 1
#define _XOPEN_SOURCE 500

This can also be done from the command line using the -D option.

**Comment by zawhh** [comment]
Having trouble building gmock with c++11 and found this thread, so I thought I should post workaround I found (found here too but the following posts after that seems ppl are still confused). 
Basically, need this 2 flags (-DGTEST_USE_OWN_TR1_TUPLE=1 -DGTEST_HAS_TR1_TUPLE=1).

E.g.
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DGTEST_USE_OWN_TR1_TUPLE=1 -DGTEST_HAS_TR1_TUPLE=1 -std=c++11")

Tested with:
g++ (MacPorts gcc47 4.7.4_8) 4.7.4
cmake version 3.10.2
