### ISSUE TITLE
[FR]: New container matcher that allows circular shifts (e.g. CircularlyShiftedElements

### ISSUE THREAD

**Issue by tom-anders** [google/googletest#4229]
### Does the feature exist in the most recent commit?

No

### Why do we need this feature?

For containers there are currently two types of matchers:

- ElementsAre -> Matches two containers, including exact order
- UnorderedElementsAre -> Matches two containers, regardless of order

However, sometimes I want to match containers where the elements have a certain order, but allow a [circular shift](https://en.wikipedia.org/wiki/Circular_shift) of the elements. For example we want `{0, 1, 2}` to match `{1, 2, 0}`, but not `{0, 2, 1}`

### Describe the proposal.

Add a new matcher (of course the name is open for discussion, but let's call it `CircularlyShiftedElementsAre`) with the following usage:

```
const std::vector<int> container = {0, 1, 2};
ASSERT_THAT(container, CircularlyShiftedElementsAre(1, 2, 0);
ASSERT_THAT(container, CircularlyShiftedElementsAre(2, 0, 1);
ASSERT_THAT(container, CircularlyShiftedElementsAre(0, 1, 2);

ASSERT_THAT(container, Not(CircularlyShiftedElementsAre(0, 2, 1));
ASSERT_THAT(container, Not(CircularlyShiftedElementsAre(2, 1, 0));
ASSERT_THAT(container, Not(CircularlyShiftedElementsAre(0, 1));
ASSERT_THAT(container, Not(CircularlyShiftedElementsAre(0, 1, 2, 3));
```

We probably also want the analogous `CircularlyShiftedElementsAreArray` and `CircularlyShiftedPointWise` matchers

### Is the feature specific to an operating system, compiler, or build system version?

No

**Comment by dinord** [comment]
We don't have many uses for `CircularlyShiftedElementsAre` in our own codebase, and this is probably the first time anyone requested it. We'd recommend implementing a utility in your own library, using `MATCHER` macros: http://google3/base/tracer.h;l=904;rcl=522386433
