### ISSUE TITLE
[FR]: Periodic and frequent semantic versions

### ISSUE THREAD

**Issue by bebuch** [google/googletest#4259]
### Does the feature exist in the most recent commit?

No

### Why do we need this feature?

I think the rooling releases approach makes sense in principle. However, there are environments, especially in companies, where this is difficult to integrate. (E.g. offline systems or complex and old build systems).

### Describe the proposal.

I suggest to release new major versions periodically. Ideally with a relatively high frequency. (Maybe once a month?)

Other projects, for example web browsers, do the same.

### Is the feature specific to an operating system, compiler, or build system version?

No

**Comment by dinord** [comment]
We do not have plans to commit to a more frequent release cadence at the moment.
