### ISSUE TITLE
[FR]: Add to the documentation a quickstart for GNU Make

### ISSUE THREAD

**Issue by jolopezl** [google/googletest#4272]
### Does the feature exist in the most recent commit?

No. The documentation in the form of an example Makefile existed up to release 1.8.1:
https://github.com/google/googletest/blob/release-1.8.1/googletest/make/Makefile

### Why do we need this feature?

Instead of doing some archeology, having a quick starting point to set things up working with GNU Make is helpful. Yes, some people still use GNU Make.

### Describe the proposal.

Start with https://github.com/google/googletest/blob/release-1.8.1/googletest/make/Makefile, and build a document equivalent to [quickstart-bazel.md](https://github.com/google/googletest/blob/main/docs/quickstart-bazel.md) or [quickstart-cmake.md](https://github.com/google/googletest/blob/main/docs/quickstart-cmake.md).

### Is the feature specific to an operating system, compiler, or build system version?

Not really, but it should be easy to follow so that it works on Linux and MacOS at least.

**Comment by derekmauro** [comment]
We don't officially support using GNU Make directly. Our supported build systems are Bazel and CMake.
