### ISSUE TITLE
[FR]: Add an EXPECT_DEATH_IN_DEBUG macro

### ISSUE THREAD

**Issue by krzikalla** [google/googletest#4275]
### Does the feature exist in the most recent commit?

No.

### Why do we need this feature?

There is the `EXPECT_DEBUG_DEATH` macro. But I fail to see its general usability. Usually you use it to test if an assertion fires in debug mode, that is, if some intended inconsistency is detected by your assertions. However, `EXPECT_DEBUG_DEATH` executes the statement also in release mode - with the same intended inconsistency. In that case you can't be sure what happens.
The example below is not possible with `EXPECT_DEBUG_DEATH`.

### Describe the proposal.

I propose another macro `EXPECT_DEATH_IN_DEBUG`, which executes its statement in debug mode only and does nothing in release mode. Example:

```
void TestFunc(int n)
{
  assert(n > 0);
  std::vector<int> v(n);
  v[0] = 1;
} 

EXPECT_DEATH_IN_DEBUG(TestFunc(0), "");
```

### Is the feature specific to an operating system, compiler, or build system version?

No.

**Comment by dinord** [comment]
> However, `EXPECT_DEBUG_DEATH` executes the statement also in release mode - with the same intended inconsistency. In that case you can't be sure what happens.

We typically want to crash when some invariant is violated. Sometimes crashing a production server is unacceptable, and we'd rather log and e.g. return some default value and keep serving other requests.  
This is where `EXPECT_DEBUG_DEATH` can be used to test that code crashes in debug mode, but *does not* crash outside of debug mode.

We'd recommend implementing your example using a combination of `NDEBUG` and `EXPECT_DEATH`, like so:

```c++
void TestFunc(int n)
{
  assert(n > 0);
  std::vector<int> v(n);
  v[0] = 1;
} 

#ifndef NDEBUG
EXPECT_DEATH(TestFunc(0), "");
#endif
```

**Comment by dinord** [comment]
We only have `EXPECT_DEBUG_DEATH` because it is more difficult to express in terms of readable building blocks, unlike the proposed `EXPECT_DEATH_IN_DEBUG`.

**Comment by dinord** [comment]
Feel free to re-open the issue if you'd like to add more clarification to your proposal.
