### ISSUE TITLE
[FR]: Support for xfail tests

### ISSUE THREAD

**Issue by LecrisUT** [google/googletest#4280]
### Why do we need this feature?

Use-case:
Tests that check if an error is thrown in an unstable regime.

### Describe the proposal.

In pytest, xfail(strict=false) (default xfail) the tests are run, but the test_suite does not fail if the individual test fails. This is different from skipping tests or negating them in that in most cases it should pass, but due to architecture, floating point errors or other kind of noises, the tests can fail.

And related to that, having a parametrized/generator tests that we expect at least one test to pass, e.g. in the above situation we can add some random noise so that the tests eventually pass.

**Comment by dinord** [comment]
We don't have any plans to implement xfail. In general we strongly discourage writing tests of any kind that expect at least one of x to pass, as that encourages writing flaky tests that are easy to sweep under the rug and hard to debug.
