### ISSUE TITLE
[FR]: Allowing for inline update of test results to reduce number of lines printed to stdout

### ISSUE THREAD

**Issue by shaurya-chandhoke** [google/googletest#4283]
### Does the feature exist in the most recent commit?

Not that I'm aware of

### Why do we need this feature?

It would be a great way to reduce the output for large test suites into succinct lines describing which ones have passed or failed.

### Describe the proposal.

Currently every passing test will receive at least 2 lines as follows:

```
[ RUN      ]  SuiteA.Test1
[       OK ]  SuiteA.Test1 (0 ms)
```

It would be great if this instead happened with a carriage return so it updates within 1 line as follows

***

**Test is executed**
```
[ RUN      ]  SuiteA.Test1
```

**Test result is passed and updates the current line it's on instead of writing to new line**
```
[       OK ]  SuiteA.Test1 (0 ms)
```

***
Of course for failed tests this wouldn't apply as we would need to see the failure message.

Perhaps this feature could be a flag (i.e `--gtest_succinct=true`)

### Is the feature specific to an operating system, compiler, or build system version?

No

**Comment by derekmauro** [comment]
We have no plans to change our output format.
