### ISSUE TITLE
[Bug]: GCC Warnings with -Wuseless-cast

### ISSUE THREAD

**Issue by jonathanmcdermid** [google/googletest#4306]
### Describe the issue

When building for GCC with -Wuseless-cast, there are some warnings in \googletest\include\gtest\internal\gtest-port.h

`return static_cast<int>(read(fd, buf, count));`

### Steps to reproduce the problem

1. Enable -Wuseless-cast flag on a GCC build
2. Do the build

### What version of GoogleTest are you using?

v1.13

### What operating system and version are you using?

Windows 11

### What compiler and version are you using?

GCC

### What build system are you using?

minGW64

**Comment by pgawro** [comment]
Hi @jonathanmcdermid 
I could reproduce that problem also on Linux can you check if proposed changes by me works also under windows?

**Comment by jonathanmcdermid** [comment]
Hi @pgawro I am still getting warnings for useless casts using your changes. I had to remove these two casts.
https://github.com/pgawro/googletest/blob/abe672c483bd1bd26b28977f1a00e2a758db5677/googletest/include/gtest/internal/gtest-port.h#L2160C6-L2160C6
https://github.com/pgawro/googletest/blob/abe672c483bd1bd26b28977f1a00e2a758db5677/googletest/include/gtest/internal/gtest-port.h#L2163

**Comment by pgawro** [comment]
Hi @jonathanmcdermid Thanks for pointing that out. I looks like I skipped that unintentionally. I will be obliged if you could check if that works for you. I have updated commit.

**Comment by jonathanmcdermid** [comment]
The new version works as expected, thanks.

**Comment by jonathanmcdermid** [comment]
I've tried using your version on linux though and am still having issues. According to the existing comment, this const cast is redundant on C++17 and onward. https://github.com/pgawro/googletest/blob/63d67622ea58dd5b9f5529ae9d7a8737419b0fe2/googletest/src/gtest-port.cc#L1100C61-L1100C61

**Comment by jonathanmcdermid** [comment]
The latest version works!

**Comment by pgawro** [comment]
Now the question is if that is suitable to merge. @derekmauro Can you take a look to PR #4306

**Comment by derekmauro** [comment]
https://github.com/google/googletest/pull/4307#issuecomment-1640275519
