### ISSUE TITLE
[Bug]: Linking error seen in Visual Studio 2022

### ISSUE THREAD

**Issue by khteh** [google/googletest#4316]
### Describe the issue

https://developercommunity.visualstudio.com/t/INSTANTIATE_TEST_SUITE_P-function-defini/10409205#T-ND10411176

<img width="1123" alt="Screenshot 2023-07-13 095853" src="https://github.com/google/googletest/assets/3871483/3e91b007-afdd-4c40-84b2-b6456dd5b05a">

### Steps to reproduce the problem

https://developercommunity.visualstudio.com/t/INSTANTIATE_TEST_SUITE_P-function-defini/10409205#T-ND10411176

### What version of GoogleTest are you using?

4a1a299b206ba250a4318f74938ea67c75c3c0c9

### What operating system and version are you using?

Windows 11

### What compiler and version are you using?

Visual Studio 2022 17.6.4

### What build system are you using?

Visual Studio 2022

**Comment by jmpostmes** [comment]
I have also seen this issue on Windows Server 2022, with MSBuild 17.4.1 (curiously, issue does not occur in 17.5.1) and GoogleTest 1.11.0
![image](https://github.com/google/googletest/assets/12891555/d061d88d-eff8-48e6-8539-33a0fadc1e14)

**Comment by derekmauro** [comment]
This report does not contain the information needed for us to reproduce this issue.
