### ISSUE TITLE
[Bug]: Mismatched std::span elements are not printed

### ISSUE THREAD

**Issue by milesfrain** [google/googletest#4318]
### Describe the issue

When comparing arrays, both expected and actual values are printed if there is a mismatch.

For spans, the actual value is omitted.

It's also potentially confusing that details are displayed about the contents of the span object wrapper. These bytes could be misinterpreted as the span element contents.

### Steps to reproduce the problem

```cpp
uint8_t u8_arr_1[] = {0x01};
uint8_t u8_arr_2[] = {0x02};

std::span<uint8_t> u8_span_1(u8_arr_1);

EXPECT_THAT(u8_arr_1, testing::ElementsAreArray(u8_arr_2));
/*
Value of: u8_arr_1
Expected: has 1 element that is equal to '\x2' (2)
  Actual: { '\x1' (1) }, whose element #0 doesn't match
*/

EXPECT_THAT(u8_span_1, testing::ElementsAreArray(u8_arr_2));
/*
Value of: u8_span_1
Expected: has 1 element that is equal to '\x2' (2)
  Actual: 16-byte object <16-E1 0B-6C FE-7F 00-00 01-00 00-00 00-00 00-00>,
whose element #0 doesn't match
*/
```

### What version of GoogleTest are you using?

https://github.com/google/googletest/commit/dea0484e4d3b6a2c50055c24c5617cd662a50c5f

### What operating system and version are you using?

Ubuntu 22.04

### What compiler and version are you using?

clang 17

### What build system are you using?

ninja 1.11.1

**Comment by NextThread** [comment]
hey, I'd like to work on this issue
