### ISSUE TITLE
[Bug]: Compile gtest-all.cc comes with error

### ISSUE THREAD

**Issue by lygstate** [google/googletest#4321]
### Describe the issue

```
In file included from ../src/gtest/src/gtest-all.cc:49:
../src/gtest/src/gtest.cc: In function 'void testing::internal::ColoredPrintf({anonymous}::GTestColor, const char*, ...)':
../src/gtest/src/gtest.cc:3308:19: error: '%s' directive argument is null [-Werror=format-overflow=]
 3308 |   printf("\033[0;3%sm", GetAnsiColorCode(color));
      |                   ^~
```

### Steps to reproduce the problem

https://gitlab.freedesktop.org/mesa/mesa/-/issues/9404

### What version of GoogleTest are you using?

[gtest tip](https://github.com/google/googletest/commit/40412d85124f7c6f3d88454583c4633e5e10fc8c)

### What operating system and version are you using?

GCC on Debian 12.

### What compiler and version are you using?

GCC on Debian 12.

### What build system are you using?

GCC on Debian 12.

**Comment by pgawro** [comment]
I added small tweak. Can you check if that is helpful for you?

**Comment by okias** [comment]
@pgawro thank you, fixed the issue for us!

**Comment by pgawro** [comment]
Since PR is merged I think we can close this ticket
