### ISSUE TITLE
[FR]: Remove public `#include <iomanip>` include directives for build speed

### ISSUE THREAD

**Issue by IncludeGuardian** [google/googletest#4329]
### Does the feature exist in the most recent commit?

No.

### Why do we need this feature?

As `<iomanip>` is not a common included file, its content is unlikely to be included in translation units other than through GoogleTest includes.

By reducing the number of include directives public headers in GoogleTest, this may reduce the time taken to compile tests as it would reduce the amount of work that the preprocessor and compiler front-end need to do.

The [C++ Compile Health Watchdog](https://artificial-mind.net/projects/compile-health/) puts `<iomanip>` at ~100ms-200ms extra compilation cost.

~0.45% of all preprocessing tokens in translation units in LLVM come from this `<iomanip>` include directive in GoogleTest. https://gist.github.com/IncludeGuardian/7e560c26783d5f11d7645c96db6b81d4#file-after-yaml-L4066-L4069

### Describe the proposal.

Move the includes of `<iomanip>` in public headers:

  * https://github.com/google/googletest/blob/455fcb7773dedc70ab489109fb12d8abc7fd59b6/googletest/include/gtest/gtest.h#L54
  * https://github.com/google/googletest/blob/455fcb7773dedc70ab489109fb12d8abc7fd59b6/googletest/include/gtest/internal/gtest-internal.h#L61

and call the [`precision`](https://en.cppreference.com/w/cpp/io/ios_base/precision) method instead of using `std::setprecision`.

### Is the feature specific to an operating system, compiler, or build system version?

No.

**Comment by IncludeGuardian** [comment]
Initial PR: https://github.com/google/googletest/pull/4330

**Comment by Ankit-Jaipuriar** [comment]
Hey! I'd like to start working on this issue.

**Comment by IncludeGuardian** [comment]
https://github.com/google/googletest/pull/4330
