### ISSUE TITLE
Unencrypted HTTP Links to external websites

### ISSUE THREAD

**Issue by sthd** [google/googletest#4341]
### Does the feature exist in the most recent commit?

no

### Why do we need this feature?

Multiple markdown files (*.md) across the project contain public labeled links that hold unencrypted HTTP links, e.g. [Link Label](http://)

Hence, when a user clicks such a link, an unencrypted HTTP request is made.

A passive eavesdropper with the ability to monitor the network traffic of the target could potentially intercept and peruse these unencrypted requests and track the target's browsing activity on these websites.

Among the links one can find: code.google.com, groups.google.com,  github.com and wikipedia.org.

### Describe the proposal.

Change public links so that they use HTTPS
For example edit line 103 on googletest-main/README.md 
so that (**http://www.chromium.org/**) will change into (**https://www.chromium.org/**)

### Is the feature specific to an operating system, compiler, or build system version?

no

**Comment by sthd** [comment]
I sent a pull request

**Comment by dinord** [comment]
Fixed by #4343.

**Comment by dinord** [comment]
...or not. We still have a bunch of http:// in our repo.

**Comment by sthd** [comment]
Thanks for bringing to my attention, changed all the current urls in PR #4349
