### ISSUE TITLE
Unexpected behavior with ASSERT_NO_THROW() and throw; without arguments.  

### ISSUE THREAD

**Issue by WillemvJ** [google/googletest#4348]
### Describe the issue

ASSERT_NO_THROW{
  throw;
};

passes. 

I expected it to fail. (I know empty throw; is bad practice.)

### Steps to reproduce the problem

Suppose somebody writes something horrible like

f(){
 throw; // should implement later
}

On c++20 (MSVC), with googletest 1.14.0, the following test does not fail:

TEST(StrangBehavior, emptythrow)
	{
		ASSERT_NO_THROW(
			f();
		);
	}

Subsequent tests in the same cpp file seem not to run at all. But at first glance, everything is going well. 

### What version of GoogleTest are you using?

1.14.0

### What operating system and version are you using?

Windows.

### What compiler and version are you using?

MSVC 19.35.32216.1

### What build system are you using?

cmake version 3.25.1-msvc1

**Comment by WillemvJ** [comment]
ps throw; outside catch block is undefined behavior in c++, so maybe this is hard to fix. But I was surprised to find that no red light starts flashing, so I wanted to report it.

**Comment by derekmauro** [comment]
Thanks for reporting this. Since this is undefined behavior, we have no plans to address this. However, there is a great tool called UBSAN that you can use to catch cases of undefined behavior.
