### ISSUE TITLE
[Bug] Gtest's output has no color when running in alacritty

### ISSUE THREAD

**Issue by vmiheer** [google/googletest#4355]
### Describe the issue

Same as #3455 but for [alacritty](https://github.com/alacritty/alacritty).

### Steps to reproduce the problem

See #3455

### What version of GoogleTest are you using?

8a6feabf04bec8fb125e0df0ad1195c42350725f

### What operating system and version are you using?

Ubuntu 22.04

### What compiler and version are you using?

Ubuntu clang version 14.0.0-1ubuntu1.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

### What build system are you using?

cmake version 3.26.4

### Additional context

https://github.com/google/googletest/issues/3455#issuecomment-1696434251

**Comment by Srivastava-Kaushal** [comment]
Hi, I am Kaushal Kumar Srivastava.
I am working on this issue.

**Comment by vmiheer** [comment]
@memdo, did you consider the option of relying on $COLORTERM? https://github.com/google/googletest/issues/3455#issuecomment-1696434251
