### ISSUE TITLE
[FR]: Offer ASSERT/EXPECT_COMPILATION_ERROR macros

### ISSUE THREAD

**Issue by rsarrazin2** [google/googletest#4379]
### Does the feature exist in the most recent commit?

No

### Why do we need this feature?

Various test use cases would then be supported (non-exhaustive list):
- Test failing static assertions
- Test invalid template instantiation
- Test private or protected methods are actually inaccessible

### Describe the proposal.

Usage examples:
- `EXPECT_COMPILATION_ERROR("int main() {", "at end of input");`
- `ASSERT_COMPILATION_ERROR("static_assert(false, \"failed\");", "failed");`

Notes:
- The compiler and its options/definitions to use shall be identical to those used to compile the test itself. It is unclear to me whether there's a use case for differing compiler/options/definitions.
- The second argument states the expected error message similarly to `ASSERT_DEATH`.
- The facility could be extended to also test against compiler warnings.
- Passing the code by string is not a must. If another interface makes more sense or the implementation easier, this is fine as well.
- If it makes an initial implementation easier (for example by having the invalid code as a generic lambda that gracefully fails in a specific SFINAE context instead of a string that is bluntly passed to the compiler in a separate process), restricting the use cases to testing failing static assertions would already help a lot.

Additional reference:
- [Is it possible to ASSERT_DOES_NOT_COMPILE with GTest?](https://stackoverflow.com/questions/31607928/is-it-possible-to-assert-does-not-compile-with-gtest)

### Is the feature specific to an operating system, compiler, or build system version?

No

**Comment by derekmauro** [comment]
We have no plans to support this. GoogleTest is designed to test runtime bugs.

Some ways you could do this:
1) Invoke the compiler from a script on a test program, capture the return value, and fail if the compile command succeeds.
2) If you are using clang, you can use `-verify` to check that the compile emits a certain error: https://clang.llvm.org/doxygen/classclang_1_1VerifyDiagnosticConsumer.html#details
