### ISSUE TITLE
[Bug]: Death tests are not supported in rust

### ISSUE THREAD

**Issue by cathaysia** [google/googletest#4396]
### Describe the issue

I'm currently writing a rust library for cpp. And test its api via gtest. There are some asserts in the rust code. When I used gtest for death testing, I found that gtest recognized rust's panic as an exception (the process return value after Rust panic is ABRT) and therefore does not support it.
But the worst thing is that using EXPECT_ANY_EXCEPTION will directly cause the process to crash, and the result is not even as good as EXPECT_DEATH.

The method I currently use is to change the panic of rs to abort. In this way, gtest can be executed correctly.

### Steps to reproduce the problem

1. write a rs ffi and add any assert
2. compile rs library.
3. run ASSERT_DEATH for the ffi function
4. then gtest cannot capture death

### What version of GoogleTest are you using?

1.14.0

### What operating system and version are you using?

macos aarch64

### What compiler and version are you using?

rustc 1.73.0-nightly (500647fd8 2023-07-27)

clang version 16.0.6
Target: arm64-apple-darwin
Thread model: posix
InstalledDir: /nix/store/b07a65s9w90rx4vsqgjzvg3r4qnq3l0p-clang-16.0.6/bin

### What build system are you using?

cmake version 3.26.4

**Comment by cathaysia** [comment]
the test message is:

```console
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from SomeTest
[ RUN      ] SomeTest.Death
/Users/xxx/tests/test_some_test.cpp:27: Failure
Death test: some_ffi_function_with_assert()
    Result: threw an exception.
 Error msg:
[  DEATH   ] thread '<unnamed>' panicked at 'assertion failed: id < 600', /Users/xxx/rs/src/lib.rs:230:9
[  DEATH   ] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[  DEATH   ]

[  FAILED  ] SomeTest.Death (600 ms)
[ RUN      ] SomeTest.Create
[       OK ] SomeTest.Create (0 ms)
[ RUN      ] SomeTest.CreateComplex
[       OK ] SomeTest.CreateComplex (0 ms)
[----------] 3 tests from SomeTest (602 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test suite ran. (602 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SomeTest.Death

 1 FAILED TEST
```

using ASSERT_ANY_THROW:

```console
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from SomeTest
[ RUN      ] SomeTest.Death
thread '<unnamed>' panicked at 'assertion failed: id < 600', /Users/xxx/rs/src/rtps/lib.rs:230:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: Rust panics must be rethrown
zsh: abort      ./build/bin/test_some_test
```

**Comment by derekmauro** [comment]
Please provide all code necessary to reproduce the problem. We have a lot of expertise in C++ but no expertise in Rust.

**Comment by cathaysia** [comment]
I add a repo to reproduce this issue: https://github.com/cathaysia/gtest_4396

**Comment by pgawro** [comment]
@cathaysia I think trying to handle rust panic in c++ will be undefined behaviour why not to refine that rust function to throw proper rust error with rust's Result and write C++ wrapper to handle that error? 
I'm also not an expert in rust i know only basics. So please correct me If that is not possible or wrong from Rust perspective

**Comment by cathaysia** [comment]
The reason for this is because I want to end the program as early as possible when the user passes in wrong initialization values.

Errors caused by the program itself will generate a return value and handle it internally as much as possible, but values provided by the user are considered logical errors, so the program will panic directly.

**Comment by cathaysia** [comment]
I close this because I thinks rust shoud be tested by rust ;)
