### ISSUE TITLE
[FR]: --gtest_filter needs the ability to filter in a case insensitive manner

### ISSUE THREAD

**Issue by towel42-com** [google/googletest#4404]
### Does the feature exist in the most recent commit?

No.

### Why do we need this feature?

Often times, as a test suite grows, case may change, either intentionally or by accident.

Being able to filter in a case insensitive manner would greatly improve the usability of the filter

### Describe the proposal.

for positive or negative filters, using a suffix of '^' to search in a case insensitive manner
--gtest_filter=*foo^ will find all variants of tests that end with foo, Foo, FOO, fOo etc.
--gtest_filter=*foo will work as before.

### Is the feature specific to an operating system, compiler, or build system version?

No

**Comment by derekmauro** [comment]
We don't plan to do this.

**Comment by towel42-com** [comment]
I have a patch to support it.  Is it that you dont want it? or have no desire to publicize it?  I havent created fork yet, but could if warranted.  it was a very trivial change, with no changes to the current usage model since ^ is not valid in a function name
