### ISSUE TITLE
[FR]: Request for googletest to support non-compile tests in C++

### ISSUE THREAD

**Issue by phaedon** [google/googletest#4430]
### Does the feature exist in the most recent commit?

No

### Why do we need this feature?

Modern idioms for C++ library design often rely on compile-time invariants (static_assert, constexpr, enable_if, etc)
It is useful to be able to write unit tests which can run and successfully verify compilation failures.

### Describe the proposal.

I don't have a detailed design, however I have previously seen (and personally used) something along these lines.

```
// Code
template <int Dim>
struct Polygon {
  Polygon() { static_assert(Dim >= 3); }
};

// Test
TEST_NON_COMPILE(PolygonTest, OneDimension) {
  Polygon<1> not_a_polygon;
}

// Build
cc_test_non_compile(
  name = "polygon_test",
  // etc.
)
```

And then test output would be successful on the basis of the compilation failure triggered by the static assert.

### Is the feature specific to an operating system, compiler, or build system version?

No

**Comment by derekmauro** [comment]
To figure out if code successfully compiles, we would have to implement a compiler. We are not going to do that. That job is best left to an actual compiler. GoogleTest is designed to test runtime bugs.

Some ways you could do this:

* Invoke the compiler from a script on a test program, capture the return value, and fail if the compile command succeeds.
* If you are using clang, you can use -verify to check that the compile emits a certain error: https://clang.llvm.org/doxygen/classclang_1_1VerifyDiagnosticConsumer.html#details
