### ISSUE TITLE
[Bug]: --gtest_filter appears to cause some libraries not to load.

### ISSUE THREAD

**Issue by bgbsww** [google/googletest#4451]
### Describe the issue

When a cmake generated test runner is executed with a --gtest_filter it appears to fail to load some libraries.

In this case, executing ./Part_tests_run from within a FreeCAD build works, as does ./Part_tests_run "--gtest_filter=-TopoShapeExpansionTest.makeElementFaceNull" but ./Part_tests_run "--gtest_filter=TopoShapeExpansionTest.makeElementFaceNull" fails with evidence deep in the code that a library didn't load.

### Steps to reproduce the problem

Unfortunately, the build takes much time and some expertise to set up, and the broken tests aren't quite yet committed to the repo.    I don't have a small reproducer for this right now.

### What version of GoogleTest are you using?

googletest/jammy,jammy 1.11.0-3 all

### What operating system and version are you using?

Ubuntu 11.4.0

### What compiler and version are you using?

gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 

### What build system are you using?

cmake version 3.22.1

**Comment by derekmauro** [comment]
There isn't enough information here to debug this issue. Re-open if you have a minimal reproduction.
