### ISSUE TITLE
[Bug]: Please title this bug report

### ISSUE THREAD

**Issue by eugeneo** [google/googletest#4472]
### Describe the issue

Post-update, Bazel build requires Fuchsia SDK.

```
$ bazel query "deps(set(//test:layers_test))"
ERROR: Evaluation of query "deps(set(//test:layers_test))" failed: preloading transitive closure failed: no such package '@@fuchsia_sdk//pkg/zx': The repository '@@fuchsia_sdk' could not be resolved: Repository '@@fuchsia_sdk' is not defined
```

### Steps to reproduce the problem

Update project to use post 9756ee7cbaef1b6652065616ab832810a6032bbf GTest

### What version of GoogleTest are you using?

top of tree

### What operating system and version are you using?

Ubuntu 20 (inside Windows WSL2)

### What compiler and version are you using?

```
Ubuntu clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

### What build system are you using?

Bazel

**Comment by baryluk** [comment]
Hi.

It looks like this is still broken, there was a fix, but then it was reverted.

googletest-1.15.2

Bazel 7.4.1:

bazel query 'somepath(//core/engine/core:engine_test , //utl/engine/utl:compression)'
`bazel query 'somepath(//core/fig:gg_test, //foo:bar)'`

`ERROR: Evaluation of query "somepath((//core/fig:zib, //foo:bar)" failed: preloading transitive closure failed: no such package '@@fuchsia_sdk//pkg/syslog': The repository '@@fuchsia_sdk' could not be resolved: Repository '@@fuchsia_sdk' is not defined`

`bazel query 'allpaths(//core/fig:gg_test, //foo:bar)'`
`ERROR: Evaluation of query "allpaths(//core/fig:zib, //foo:bar)" failed: preloading transitive closure failed: no such package '@@com_google_absl//absl/container': The repository '@@com_google_absl' could not be resolved: Repository '@@com_google_absl' is not defined`
