### ISSUE TITLE
[FR]: Expose SetUpTestSuite and TearDownTestSuite getters and setters.

### ISSUE THREAD

**Issue by mbhaskar98** [google/googletest#4482]
### Does the feature exist in the most recent commit?

Don't think so. 

### Why do we need this feature?

To give flexibility while integrating Gtest with other testing frameworks.

### Describe the proposal.

Expose getters and setters for `SetUpTestSuite` and `TearDownTestSuite` so that while integrating Gtest with other testing frameworks, these methods can be called during the setup and teardown  phase of the framework. 

### Is the feature specific to an operating system, compiler, or build system version?

Probably yes, `Xcode's XCTest`

**Comment by derekmauro** [comment]
We are not interested in supporting this use case.
