### ISSUE TITLE
[FR]: Add support for building GoogleTest on Xbox platforms

### ISSUE THREAD

**Issue by to01z** [google/googletest#4500]
### Does the feature exist in the most recent commit?

No

### Why do we need this feature?

It would be great to be able to use the same testing framework on PC and Xbox platforms. 

### Describe the proposal.

In order to use GoogleTest on Xbox platforms, the code must compile with `WINAPI_FAMILY` set to `WINAPI_FAMILY_GAMES` (see [here](https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/getstarted/overviews/developing-new-titles-on-gamecore#games-for-xbox)).

I have done the work to make GoogleTest compile/ link and some basic testing on Xbox platforms to make sure it runs. You can see the necessary changes [here](https://github.com/to01z/googletest/compare/main...add-winapi-partition-games-support). I would be happy to file a pull request, if you think the changes are acceptable.

### Is the feature specific to an operating system, compiler, or build system version?

This feature is specific to the Windows OS. By compiling with `WINAPI_FAMILY` set to `WINAPI_FAMILY_GAMES`, the Win32 API is limited to a stricter subset which can successfully link and run on Xbox platforms. The feature as propose, does not alter behavior on existing platforms.

**Comment by derekmauro** [comment]
https://github.com/to01z/googletest/compare/main...add-winapi-partition-games-support is simple enough that if it passes our tests I would accept it.
