### ISSUE TITLE
EXPECT_EXIT、ASSERT_EXITにてstderrの取得のため以下を実行するとシグナル6で異常終了する。

### ISSUE THREAD

**Issue by ikis-ikis** [google/googletest#4506]
### Describe the issue

1.8.x(1.1.0)で、EXPECT_EXIT、ASSERT_EXITにてstderrの取得のため以下を実行するとシグナル6で異常終了する。

### Steps to reproduce the problem

testing::internal::CaptureStderr();
EXPECT_EXIT(Function(...), ::testing::ExitedWithCode(0), "");     // signal 6
EXPECT_STREQ("", testing::internal::GetCapturedStderr().c_str());

### What version of GoogleTest are you using?

1.10.0

### What operating system and version are you using?

ScientificLinux  7.8

### What compiler and version are you using?

gcc 4.8.5

### What build system are you using?

make

**Comment by derekmauro** [comment]
Unintelligible report with an unsupported compiler and GoogleTest version.
