### ISSUE TITLE
[FR]: Add z/OS platform for death test support

### ISSUE THREAD

**Issue by abhina-sree** [google/googletest#4526]
### Does the feature exist in the most recent commit?

No

### Why do we need this feature?

We would like to support death tests on z/OS as well

### Describe the proposal.

Add GTEST_OS_ZOS here https://github.com/google/googletest/blob/main/googletest/include/gtest/internal/gtest-port.h#L672

### Is the feature specific to an operating system, compiler, or build system version?

z/OS system

**Comment by derekmauro** [comment]
PR was merged.
