### ISSUE TITLE
[Bug]: std::length_error from cmake function "generate_testname_guards()"

### ISSUE THREAD

**Issue by hunjmes** [google/googletest#4537]
### Describe the issue

Symptoms seem related to earlier issue https://github.com/google/googletest/issues/2849 .

When building a package that has lots of Google Tests, we get an unhandled `std::length_error` exception, from file `GoogleTestAddTests.cmake` , function `generate_testname_guards()`:
```
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
CMake Error at .../Modules/GoogleTestAddTests.cmake:40 (message):
  Error running test executable.

    Path: '.../TestSuites'
    Result: Child aborted
    Output:
      SingleThreadUtils default stack size from system 8388608
```

### Steps to reproduce the problem

Our build system currently reproduces this privately, but I do not yet have a public repro.

### What version of GoogleTest are you using?

3.9.

### What operating system and version are you using?

Amazon Linux.

### What compiler and version are you using?

gcc 11.x

### What build system are you using?

cmake 3.9.6.

**Comment by derekmauro** [comment]
Sorry, but we don't look at issues that are this vague and have no reproducer.
