### ISSUE TITLE
Patching adding support for FreeBSD 10

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#463]
```
Please find attached a patch adding build support for FreeBSD 10. It basically 
turns on Linux build with clone disabled, with the addition of a few headers 
POSIX requires and Linux is sloppy about.
```

Original issue reported on code.google.com by `niall.do...@maidsafe.net` on 29 May 2014 at 4:14

Attachments:
- [freebsd_support.patch](https://storage.googleapis.com/google-code-attachments/googletest/issue-463/comment-0/freebsd_support.patch)

**Comment by emaste** [comment]
This issue should be closed. FreeBSD support was added in b215e30cadd11db7c9f378b57ffecce92aacce37
