### ISSUE TITLE
GTEST_AMBIGUOUS_ELSE_BLOCKER_ causes code analysis warning

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#471]
```
What steps will reproduce the problem?
1. Write a test that uses EXPECT_TRUE
2. Use Visual Studio 2013 to run CodeAnalysis
Now you'll get message:
"error C6326: Potential comparison of a constant with another constant."

It seems to be due to the GTEST_AMBIGUOUS_ELSE_BLOCKER_ macro which is expanded 
to "switch (0) case 0: default:".

What is the expected output? What do you see instead?
I would like no error/warning messages.

What version of Google Test are you using? On what operating system?
1.7.0

```

Original issue reported on code.google.com by `mikko...@gmail.com` on 12 Aug 2014 at 3:40

**Comment by thomthom** [comment]
Ran into the same myself after enabling code analysis on my project. All ASSERT/EXPECT triggers a warning.

**Comment by Bu11etmagnet** [comment]
C6326 will need to get suppressed.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
@Bu11etmagnet is this still an issue? VS2013 is not even supported

**Comment by kiwixz** [comment]
It was still an issue on VS2017.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by MichaelGoulding** [comment]
This is still an issue
