### ISSUE TITLE
Add the ability to specify parameterized test names

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#488]
```
When using parameterized tests, names come out as

"Fixture/0.Case/0"
"Fixture/0.Case/1"
"Fixture/1.Case/1"

Sometimes in the logs it's not as visible what the 0's and 1's represent, even 
if you also print out a test name (or other identifying information) in the 
body of the test. It would be very nice to be able to specify this along with 
other test parameters. This would also give better access to command line 
filters.

```

Original issue reported on code.google.com by `jmad...@chromium.org` on 24 Apr 2015 at 7:22

**Comment by mwoehlke-kitware** [comment]
This might not help you, but if you're using CMake, the new [dynamic discovery](https://blog.kitware.com/dynamic-google-test-discovery-in-cmake-3-10/) mechanism maps these to much more informative (read: uses the actual type name or value string instead of indices) CTest test names...

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
