### ISSUE TITLE
Merge googlemock into googletest

### ISSUE THREAD

**Issue by BillyDonahue** [google/googletest#510]
Googlemock and Googletest will be merged into one repository to make release management easier. The first step toward this will be a unified 'googletest' project, containing 3 top-level objects:
    googletest/
    googlemock/
    README.md

Eventually, we'd make the googlemock/ directory disappear as its files will be folded into the googletest/ directory.

**Comment by mazong1123** [comment]
Any progress on this? googlemock/ is still there and the code failed to compile with current Makefile and vs project props. 

In case of anyone wants to compile the project without modifying the makefile/vs project props, I've just sent a pull request #773 to address the compile issue with current folder structure. This would be a temporary solution before the folder structure being changed.

**Comment by BillyDonahue** [comment]
I'll take #773 thanks.
I don't have an MSVC handy right now to check on the build problems.
