### ISSUE TITLE
Make thread-safe on Windows

### ISSUE THREAD

**Issue by BillyDonahue** [google/googletest#534]
_From @GoogleCodeExporter on August 24, 2015 22:40_

```
As the CookBook states, gmock currently is not thread-safe on Windows.

It would be great for Chrome if this feature could be added. Chrome is highly 
multi-threaded and it is sometimes not possible to avoid spinning up a helper 
thread in unit tests.

As things stand right now, it is easy to write a multi-threaded test under 
Linux only to have it flake in weird ways under Windows.
```

Original issue reported on code.google.com by `bartfab@chromium.org` on 11 May 2012 at 2:10

_Copied from original issue: google/googlemock#156_

**Comment by BillyDonahue** [comment]
_From @GoogleCodeExporter on August 24, 2015 22:40_

```
Makes sense.

However, this is not a trivial change, and gmock is maintained by volunteers 
only, so please consider contributing a patch yourself. :)
```

Original comment by `w...@google.com` on 8 Mar 2013 at 5:40
* Added labels: **Type-Enhancement**
* Removed labels: **Type-Defect**

**Comment by BillyDonahue** [comment]
_From @GoogleCodeExporter on August 24, 2015 22:40_



Original comment by `w...@google.com` on 8 Mar 2013 at 5:41
* Changed state: **Accepted**

**Comment by janwilmans** [comment]
I'm willing to give it a try, can you educate me on what the non trivial change involves?

**Comment by janwilmans** [comment]
Whoa! it looks like its already fixed  in this changeset a6340420b9cee27f77c5b91bea807121914a5831!

**Comment by janwilmans** [comment]
Jokr did some testen on linux and windows, it seems that is works fine.
https://stackoverflow.com/questions/44750012/is-googlemock-not-thread-safe-on-linux

**Comment by gennadiycivil** [comment]
Look stale
