### ISSUE TITLE
googletest 1.8 release

### ISSUE THREAD

**Issue by samkellett** [google/googletest#586]
There hasn't been an official release of gtest since 2013. Since then support for movable objects has been added (ByMove, etc.) as well as other stuff I'm sure.

Is there any plan for an official release?

**Comment by BillyDonahue** [comment]
Soon!

**Comment by samkellett** [comment]
How soon we talking?! :smile:

**Comment by BillyDonahue** [comment]
It's a Q4 goal, so before 2016.

**Comment by samkellett** [comment]
That's awesome! Cheers for all the hard work

**Comment by jupp0r** [comment]
Cool, do you have any update on the roadmap? I understand 1.8 will support C++11/14 ?

**Comment by BillyDonahue** [comment]
v1.8 will not be C++11/14 capable.
It will just be a snapshot of what's basically trunk right now.

When we have v1.8.0, we will have something relatively modern that people
can use even if they are stuck without a C++11 compiler. So they'll be
happy for a while while we go off into the future.

After v1.8.0 is tagged and released, we'll start breaking some
backward-compatibility with pre-11 compilers in head.
This applies to user support as well as the internals. If you look at the
implementation internals for googletest and googlemock, you'll see a lot of
places where C++11 would have saved us a lot of complexity and workarounds.

**Comment by jupp0r** [comment]
Thanks for the clarification.

**Comment by xor-gate** [comment]
2015-Q4 has passed :_)

**Comment by BillyDonahue** [comment]
Working on it!

**Comment by anatol** [comment]
Any update? I would like to bring this package to Arch Linux but the last release is too old. Any chance to see a new release (well at least -rc release) in the nearest future?

**Comment by dcow** [comment]
What's blocking this?

**Comment by BillyDonahue** [comment]
There's no blocker, just need the time to work on it.

**Comment by eelstork** [comment]
The lack of a recent release does have minor downsides.

**Comment by liav-teichner** [comment]
The googlemock cockbook says that googlemock supports move-constructible return types, but this (as far as I can see) is not supported in the latest official release. Maybe the cookbook should be made clearer, denoting the experimental\non-release features, and giving workarounds for current official releases.

**Comment by Gordon-Mc** [comment]
Looks like gtest v 1.8.0 _does_ now exist - but I see no information on what is new in this release. Unless I'm hallucinating (always possible :-)) the CHANGES file in the 1.8.0 download lists what is new in 1.7.0, not what is new in 1.8.0.
Can anyone point me to details of the 1.7.0 -> 1.8.0 changes ? 
Thanks.

**Comment by KindDragon** [comment]
Related to #855

**Comment by KindDragon** [comment]
> Can anyone point me to details of the 1.7.0 -> 1.8.0 changes ?

https://github.com/google/googletest/compare/release-1.7.0...release-1.8.0
548 commits

**Comment by matthauck** [comment]
548 commits is a bit much to consume... :cry:  Perhaps you could produce some bullet point release notes to help point out what is new / improved / changed in 1.8?

**Comment by abozkurt** [comment]
When are you planning to update 1.8 changelog? Thanks.

**Comment by Croydon** [comment]
Is there seriously still no changelog for 1.8?

**Comment by KindDragon** [comment]
Related to #1079
