### ISSUE TITLE
project page mentioned but not linked to

### ISSUE THREAD

**Issue by djerius** [google/googletest#587]
The top level README.md  indicates there's a project page:

>  Please see the project page above for more information as well as the mailing list for questions, discussions, and development. 

But there's no link to it that I can find.  Could you please remedy that?

Thanks,
Diab

**Comment by refaelsh** [comment]
+1

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by djerius** [comment]
As a user of this project, I really don't know what the proper links should be. That's a project level decision and should be done be a maintainer.

This issue should be re-opened.  It's still a problem, and closing the issue doesn't solve it.
