### ISSUE TITLE
googlemock autotools are broken

### ISSUE THREAD

**Issue by nomis52** [google/googletest#588]
I'm trying to switch our CI tools from https://github.com/google/googlemock to the new github version, but the build is broken when using autotools.

googletest works correctly, but googlemock fails with 

    aclocal: error: configure.ac:1: file 'gtest/m4/acx_pthread.m4' does not exist

If I fix that, there are more failures caused by the gtest directory not existing. Symlinking googlemock/gtest to googletest allows the build to succeed.

I'm happy to send patches, I just need to know what the desired layout is.

**Comment by BillyDonahue** [comment]
Googlemock has been merged into the google/googletest project.
So let's continue discussion there. I'm sure autotools are just as broken there as well, but that's the right place to talk about a fix.

**Comment by nomis52** [comment]
This issue is filed under the google/googletest project, or is there a different once I'm missing?

**Comment by BillyDonahue** [comment]
you're quite right. I don't know what I was looking at.

**Comment by BillyDonahue** [comment]
Any references to gtest should become references to ../googletest if that's possible.

**Comment by nomis52** [comment]
Alright, I'll work on a patch.

**Comment by philarnaud** [comment]
Hello nomis52,
I am looking for www.nomis52.net/data/debian ola installation and I don't find it anymore (failed to download
Could you help

**Comment by nomis52** [comment]
https://packages.debian.org/search?keywords=googletest&searchon=names&suite=stable&section=all
