### ISSUE TITLE
Broken links in googlemock readme

### ISSUE THREAD

**Issue by jyasskin** [google/googletest#590]
https://github.com/google/googletest/blob/master/googlemock/README.md has links labeled CheatSheet and CookBook, but they go to 
https://github.com/google/googletest/blob/master/googlemock/googlemock/docs/CheatSheet.md and https://github.com/google/googletest/blob/master/googlemock/googlemock/docs/CookBook.md which don't exist.

**Comment by BillyDonahue** [comment]
Thanks. I got an email about this, but an Issue# allows better tracking. Fixed.
