### ISSUE TITLE
'EINTR' not declared error

### ISSUE THREAD

**Issue by crypto750** [google/googletest#598]
I had to put #include < asm-generic/errno-base.h >
in gtest-death-test.cc to compile.

**Comment by sbenzaquen** [comment]
Can you give a little more details about your build environment?

**Comment by crypto750** [comment]
I was building it on http://tinycorelinux.net/ linux 32-bit, I think it's tinycorelinux specific though.

**Comment by sbenzaquen** [comment]
I guess it is missing an include for <errno.h>.
Can you try with just that one (instead of the very specific header you used)?
