### ISSUE TITLE
Add "filename" field to XML output

### ISSUE THREAD

**Issue by curtpm** [google/googletest#613]
currently when saving results as xml the there is no indication of what file the test was located in

```
<testsuite name="NAME" tests="3" failures="0" disabled="0" errors="0" time="0.328">
```

adding a "filename" attribute would be extremely helpful with some automated reporting tools.

```
<testsuite name="NAME" tests="3" failures="0" disabled="0" errors="0" time="0.328" filename="/home/user/project/test/file.cpp">
```

**Comment by sbenzaquen** [comment]
On Thu, Oct 15, 2015 at 6:19 PM, Curtis Mahieu <notifications@github.com>
wrote:

> currently when saving results as xml the there is no indication of what
> file the test was located in
>
> <testsuite name="NAME" tests="3" failures="0" disabled="0" errors="0" time="0.328">
>
> adding a "filename" attribute would be extremely helpful with some
> automated reporting tools.
>
> <testsuite name="NAME" tests="3" failures="0" disabled="0" errors="0" time="0.328" filename="/home/user/project/test/file.cpp">
>
>
Tests can come from many files that are all linked in into the same binary.
Maybe it would work in the <testcase> nodes, but I fear it will be too
verbose and give a lot of duplicated attributes.

_Sam

**Comment by curtpm** [comment]
<testcase> would also be fine. This can be accomplished now by using

````
  RecordProperty("fileName", __FILE__);
```` 

There is no way to globally add this to every test.  It has to be added to every Fixture or TEST by hand, and is very error prone.

Maybe if there could be a global flag that would call RecordProperty in the macro code for TEST or for every Fixture?

**Comment by phipse** [comment]
By now, is there a way to write the file name to the XML output in an automated way? Besides adding a RecordProperty statement to each test?

**Comment by em2er** [comment]
Is any progress here?

**Comment by tegoo** [comment]
I'm joining request

**Comment by Gruntfuggly** [comment]
I would also love to be able to automatically record the test location in the xml output.

**Comment by gennadiycivil** [comment]
https://github.com/google/googletest/pull/1658 seems to do just this

**Comment by curtpm** [comment]
#1658 is almost what i was looking for, but that only seems to print the file information when using "--gtest_list_tests" I was looking for that same information but in addition to the actual test result information as well.

**Comment by jkokorian** [comment]
Is there a way to do this already? (6 years later:-))
