### ISSUE TITLE
Some links on the main README.md are broken.

### ISSUE THREAD

**Issue by lvaz** [google/googletest#615]
this link (on CMakeLists.txt):
... Google Test comes with a CMake build script ( CMakeLists.txt) ...

and this link (on include/gtest/internal/gtest-port.h):
... For a complete list, see file include/gtest/internal/gtest-port.h. ...

are broken on the README.md located in googletest folder.

**Comment by anuragsoni** [comment]
I made a PR to update the broken links

**Comment by BillyDonahue** [comment]
thanks
