### ISSUE TITLE
Add ASSERT_NOT_NEAR

### ISSUE THREAD

**Issue by javanegmond** [google/googletest#623]
The ASSERT_NEAR macro exists and for good reason of being able to compare floating punt numbers. For my project, it is also very important to know in certain cases that floating point values will not be equal. I propose to have an ASSERT_NOT_NEAR be implemented similar to ASSERT_NEAR but with opposite functionality: this ASSERT should fail if the input and check target are near (with respect to the given threshold) each other.

For now I'll be using a work around with ASSERT_FALSE, but that doesn't give as nice an output as ASSERT_NEAR.

**Comment by BillyDonahue** [comment]
On Thursday, November 5, 2015, javanegmond <notifications@github.com> wrote:

> The ASSERT_NEAR macro exists and for good reason of being able to compare
> floating punt numbers. For my project, it is also very important to know in
> certain cases that floating point values will not be equal. I propose to
> have an ASSERT_NOT_NEAR be implemented similar to ASSERT_NEAR but with
> opposite functionality: this ASSERT should fail if the input and check
> target are near (with respect to the given threshold) each other.
>
> For now I'll be using a work around with ASSERT_FALSE, but that doesn't
> give as nice an output as ASSERT_NEAR.
>

How about ASSERT_THAT(x, Not(DoubleIsNear(y)))


Marchers compose better than macros

**Comment by javanegmond** [comment]
Are you proposing me to use marchers (never heard of the term to be honest) or to (have someone) implement my request using marchers? I'm by no means an expert in using googletest, but I quickly tried to adapt your ASSERT_THAT suggestion and my compiler just complains about it not existing: `‘ASSERT_THAT’ was not declared in this scope`.

For now I will just make do with a workaround using ASSERT_FALSE, I just found it unsettling that there is no ASSERT_NOT_NEAR function dual to ASSERT_NEAR, while there are ASSERT_EQ and ASSERT_NE macros.

**Comment by brandon-kohn** [comment]
He most likely meant a **matcher**. As for ASSERT_NOT_NEAR, I'm sure a patch with tests would be welcome. ;)

**Comment by BillyDonahue** [comment]
I wouldn't be excited about a patch introducing ASSERT_NOT_NEAR.
Macros tend to proliferate. Once you have a few, lots of wiggledy fiddledy
variants appear soon after.
I'd prefer to stick to composable primitives.

Sorry about "Marcher". Yes, I meant Matcher. They're unfortunately still
part of Googlemock.

#include ".../googlemock.h"

I think we should move the matchers down into Googletest. They are useful
outside of mocking.
The most likely way to do that is to just unify the two libraries into one
thing.

**Comment by brandon-kohn** [comment]
Hehe, yeah after I went back and read your response about composition.. 
I deleted my reply. That composition with ASSERT_THAT is all you need.
