### ISSUE TITLE
Off Network install

### ISSUE THREAD

**Issue by wegunterjr-Dematic** [google/googletest#630]
What if you are making a project on a system that may not have access to the internet. What are the reasons for not building/installing outside of your project build process?  Or am I misunderstanding the meaning behind this FAQ:

> Why is it not recommended to install a pre-compiled copy of Google Test (for example, into /usr/local)?
> In the early days, we said that you could install compiled Google Test libraries on *nix systems using make install. Then every user of your machine can write tests without recompiling Google Test.
> 
> This seemed like a good idea, but it has a got-cha: every user needs to compile his tests using the same compiler flags used to compile the installed Google Test libraries; otherwise he may run into undefined behaviors (i.e. the tests can behave strangely and may even crash for no obvious reasons).
> 
> Why? Because C++ has this thing called the One-Definition Rule: if two C++ source files contain different definitions of the same class/function/variable, and you link them together, you violate the rule. The linker may or may not catch the error (in many cases it's not required by the C++ standard to catch the violation). If it doesn't, you get strange run-time behaviors that are unexpected and hard to debug.
> 
> If you compile Google Test and your test code using different compiler flags, they may see different definitions of the same class/function/variable (e.g. due to the use of #if in Google Test). Therefore, for your sanity, we recommend to avoid installing pre-compiled Google Test libraries. Instead, each project should compile Google Test itself such that it can be sure that the same flags are used for both Google Test and the tests.

**Comment by wegunterjr-Dematic** [comment]
I think after reading the reason again, it doesn't violate anything by downloading the zip, installing it on the machine, and then building it as suggested.   I just need to look into how to use CMake to build it in the configure portion of the project setup.

**Comment by johnbeard** [comment]
@wegunterjr-Dematic, yes that's what I do if I want offline builds - I download it and just provide the path to the .zip on the machine in the CMake file rather than a URL.
