### ISSUE TITLE
Latest commits on Nov 10 cause infinite build

### ISSUE THREAD

**Issue by andrewsomesyoung** [google/googletest#631]
I have Google test and mock integrated with my codebase using CMake and ExternalProject with the following snippet. This worked great up until the commits on Nov 10. Now when I rebuild from clean the Google test part seems to loop infinitely creating configure scripts. Setting the Git hash to cf517375efb5581dc0f187275ebce964c34e4a3f using GIT_TAG resets me to the last commit before Nov 10 and works again.
## Google Test

set(GTEST_PREFIX ${CMAKE_CURRENT_BINARY_DIR}/external/gtest)
ExternalProject_Add(
    gtest
    PREFIX ${GTEST_PREFIX}
    GIT_REPOSITORY https://github.com/google/googletest.git
    UPDATE_COMMAND cd ${GTEST_PREFIX}/src/gtest/googlemock && autoreconf -fvi
    CONFIGURE_COMMAND cd ${GTEST_PREFIX}/src/gtest/googlemock && ./configure
    BUILD_COMMAND cd ${GTEST_PREFIX}/src/gtest/googlemock && make
    INSTALL_COMMAND ""
)

**Comment by BillyDonahue** [comment]
If you can send a PR that fixes you that would be easiest.
