### ISSUE TITLE
Fix links to samples in docs

### ISSUE THREAD

**Issue by ip** [google/googletest#635]
https://github.com/google/googletest/blob/master/googletest/docs/Samples.md
The page points to old repository

**Comment by metaflow** [comment]
@ip as I see all links are `github...` Which one is broken?

**Comment by ip** [comment]
@metaflow Sorry, it's https://github.com/google/googletest/blob/master/googletest/docs/V1_7_Samples.md

**Comment by ip** [comment]
By the way there are a lot of links to http://code.google.com/p/googletest if you try to search in whole repository

**Comment by jasjuang** [comment]
+1

**Comment by ip** [comment]
Also here: https://github.com/google/googletest/blob/master/googlemock/docs/v1_7/Documentation.md
