### ISSUE TITLE
EXPECT_EQ with integer literal gives "Comparison of integers of different signs" with clang

### ISSUE THREAD

**Issue by jtbandes** [google/googletest#644]
When building with clang, something as simple as

```
EXPECT_EQ(0, someVector.size());
```

throws warnings like "Comparison of integers of different signs" at [this comparison](https://github.com/google/googletest/blob/2f93e2d8085eac507c065c081f356afecc7ed1b5/googletest/include/gtest/gtest.h#L1392).

It can be worked around by specifying `0U` instead of `0`, but it's pretty annoying to do that everywhere.

It looks like the equivalent warnings in Visual Studio are disabled on the previous line, so it might make sense to disable these for clang also, e.g.

```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wsign-compare"
...
#pragma clang diagnostic pop
```

But to me, it seems like a bad idea to disable this warning here. Perhaps instead the macros/templates can be rejiggered to allow the compiler to infer the correct type for the literal.

**Comment by nickma82** [comment]
+1

**Comment by BillyDonahue** [comment]
That's a sophisticated request and  would necessitate treating the arguments asymmetrically.
The "correct type for the literal" isn't obvious. We take the user at his word and just use the type of the expression provided. The type actually seen by the == operator will be subject to implicit conversions and promotions depending on what's on the right.  A 0 might be an int, a void*, a size_t, or an R(T::*)(A...).

**Comment by BillyDonahue** [comment]
For your needs, you might be better served by training yourself to write this instead:

`    EXPECT_THAT(someVector.size(), Eq(0)).`

**Comment by jtbandes** [comment]
Why does `EXPECT_EQ` allow arguments of different types? I think if the function being called were a template requiring its arguments to be of the same type, the compiler would be able to implicitly convert the literal to the same type as the other expression.

**Comment by BillyDonahue** [comment]
EXPECT_EQ allows arguments of different types because operator== allows arguments of different types.
