### ISSUE TITLE
Minimum CMake version should be 2.6.4, not 2.6.2

### ISSUE THREAD

**Issue by audiofanatic** [google/googletest#656]
I'm just doing some testing of a change I'm working on for issue 655 and noticed that the CMakeLists.txt files list 2.6.2 as the minimum CMake version. My testing shows, however, that these do not build with 2.6.2 (chokes on the `include(cmake/internal_utils.cmake)` line in googletest/CMakeLists.txt), they only seem to build successfully with 2.6.4 or later. I'm using a pretty standard OS X 10.10.5 machine for testing. I think the `cmake_minimum_required()` lines need to be updated to 2.6.4, which is what the developer guidelines list as the minimum anyway.

**Comment by BillyDonahue** [comment]
Sounds right

**Comment by thedrow** [comment]
Should be closed no?

**Comment by audiofanatic** [comment]
The CMakeLists.txt files have not actually been updated yet, they still specify 2.6.2 as the minimum version. I'll try to put together a pull request later today to address this.

**Comment by BillyDonahue** [comment]
Ok thanks
