### ISSUE TITLE
Where did the gtest primer/manual go? 

### ISSUE THREAD

**Issue by perkj** [google/googletest#662]
I have been trying to find a manual for how to use gtest. Every search I do I end up in the readme .md file in this repo but I can not find the documentation for how to write a gtest that existed before the merge (?)  

In particular I am looking for how to write a squence of tests. Ie, I want to write tests that are dependent on each other.

**Comment by BillyDonahue** [comment]
Check the docs/ directory?
I'm not sure what you're looking for, but nothing should have been lost.

**Comment by perkj** [comment]
eh, thanks, there it is.... I think this issue can be closed.

What made me confused was the line "More detailed documentation for
googletest (including build instructions) are in its interior
googletest/README.md file." that did not do me any good.
The links I found on for example
http://stackoverflow.com/questions/17079702/gtest-testing-template-class
redirects me to the github repo.

**Comment by JMVOLLE** [comment]
Hello,
Where did the original Google test documentation (wiki page?) go?
This was a really good documentation with example usage advance technics,...
Could you at least provide a link to the new one (provided it's not been lost when going from google hosting to github).
I'm thinking of the following link tipically (now redirect to github :-() 
http://code.google.com/p/googletest/wiki/GoogleTestAdvancedGuide
http://code.google.com/p/googletest/wiki/GoogleTestPrimer

**Comment by hethi** [comment]
Similar to #609 - The top level [README](https://github.com/google/googletest) is linking directly to the Google Test Primer and to the Google Mock documentation, IMHO this issue can be closed.
