### ISSUE TITLE
small documentation error or am I confused?

### ISSUE THREAD

**Issue by xaxxon** [google/googletest#664]
in: https://github.com/google/googletest/blob/master/googlemock/docs/ForDummies.md

using ::testing::_;...
EXPECT_CALL(turtle, Forward(__));  // #1
EXPECT_CALL(turtle, Forward(10))  // #2
    .Times(2);
If Forward(10) is called three times in a row, the third time it will be an error, as the last matching expectation (#2) has been saturated. If, however, the third Forward(10) call is replaced by Forward(20), then it would be OK, as now #1 will be the matching expectation.

Am I missing something?  Wouldn't 10 three times be fine?  It would hit the second one twice then the wildcard.   Why would the wildcard accept the 20 but not the 10?  If the first one were Forward(20) then the description would make sense.

**Comment by JMVOLLE** [comment]
Hello,
Where did the original Google test documentation (wiki page?) go?
This was a really good documentation with example usage advance technics,...
Could you at least provide a link to the new one (provided it's not been lost when going from google hosting to github).
I'm thinking of the following link tipically (now redirect to github :-() 
http://code.google.com/p/googletest/wiki/GoogleTestAdvancedGuide
http://code.google.com/p/googletest/wiki/GoogleTestPrimer

**Comment by BillyDonahue** [comment]
On Mon, Dec 14, 2015 at 4:54 AM, JMVOLLE <notifications@github.com> wrote:

> Hello,
> Where did the original Google test documentation (wiki page?) go?
> This was a really good documentation with example usage advance
> technics,...
> Could you at least provide a link to the new one (provided it's not been
> lost when going from google hosting to github).
> I'm thinking of the following link tipically (now redirect to github :-()
> http://code.google.com/p/googletest/wiki/GoogleTestAdvancedGuide
>


https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md


>
> http://code.google.com/p/googletest/wiki/GoogleTestPrimer
>


https://github.com/google/googletest/blob/master/googletest/docs/Primer.md

**Comment by JMVOLLE** [comment]
Thanks!
