### ISSUE TITLE
Support "noexcept" function specifiers

### ISSUE THREAD

**Issue by goofacz** [google/googletest#667]
I'm looking forward to see "noexcept" function specifier support in Google Mock. At the moment I deal with number of virtual methods annotated with "noexcept" specifier and I cannot mock them using Google Mock.

**Comment by pepe82sh** [comment]
@gennadiycivil Is this closed because there is a solution to work with? I followed the "trail" to #1532, but that one is still open.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
