### ISSUE TITLE
gtest_main-config.cmake not found while building libqi for ros nao.

### ISSUE THREAD

**Issue by rsshruti** [google/googletest#672]
hi,
I am trying to install libqi for nao-ros using ccmake and it gives me error given below. I already have gtest package,  Although its able to find the gtest_main library but gtest_main_dir is missing.

error:
........................................................................
CMake Error at /home/shruti/d-prefix/share/cmake/qibuild/internal/uselib.cmake:80 (find_package): By not providing "FindGTEST_MAIN.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "GTEST_MAIN", but CMake did not find one.

Could not find a package configuration file provided by "GTEST_MAIN" with any of the following names:

GTEST_MAINConfig.cmake gtest_main-config.cmake

Add the installation prefix of "GTEST_MAIN" to CMAKE_PREFIX_PATH or set "GTEST_MAIN_DIR" to a directory containing one of the above files. If "GTEST_MAIN" provides a separate development package or SDK, be sure it has been installed.
..........................................................................
Any one knows about it? Thanks in advance!

**Comment by jMartich** [comment]
@ years later, did anyone ever figure this out?

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
