### ISSUE TITLE
Is there reason why GTEST_FATAL_FAILURE_ macro contains the return statement but GTEST_NONFATAL_FAILURE_ no?

### ISSUE THREAD

**Issue by Gluttton** [google/googletest#680]
Why macro ```GTEST_FATAL_FAILURE_``` and ```GTEST_NONFATAL_FAILURE_``` which defined in file [include/gtest/internal/gtest-internal.h](https://github.com/google/googletest/blob/master/googletest/include/gtest/internal/gtest-internal.h) have similar meaning but different behaviour? Or more specific: is ```return``` statement in the ```GTEST_FATAL_FAILURE_``` is redundant?

P.S. My question is expired by other question from [SO](http://stackoverflow.com/questions/34696483/assert-throw-error-void-value-not-ignored-as-it-ought-to-be).

**Comment by sbenzaquen** [comment]
On Sat, Jan 9, 2016 at 6:05 PM, Gluttton <notifications@github.com> wrote:

> Why macro GTEST_FATAL_FAILURE_ and GTEST_NONFATAL_FAILURE_ which defined
> in file include/gtest/internal/gtest-internalh
> <https://githubcom/google/googletest/blob/master/googletest/include/gtest/internal/gtest-internalh>
> have similar meaning but different behaviour? Or more specific: is return
> statement in the GTEST_FATAL_FAILURE_ is redundant?
>
These macros are internal and implementation details of gTest.
Their implementation should not be relevant to you.

The macros you care about are EXPECT_XXX and ASSERT_XXX.
ASSERT_XXX is used as a poor man's exception to allow it to work in
environments where exceptions are disabled. It does a return; instead.
It is meant to be used from within the TEST() methods, which return void.

**Comment by Gluttton** [comment]
@sbenzaquen , thanks for your answer!
> It is meant to be used from within the TEST() methods, which return void.

This is exactly what I wanted to know!

**Comment by goldsteinn** [comment]
@sbenzaquen is there a reason you guys don't implement it with `setjmp`/`longjmp`?

**Comment by maryfranharper** [comment]
I don't know.

**Comment by goldsteinn** [comment]
@maryfranharper 
open to a patch to change the behavior?

**Comment by apcountryman** [comment]
`longjmp()` is not guaranteed to properly unwind the stack (it looks like some implementations do but this is not required) which results in non-trivial destructors for stack allocated objects not being called. Therefore you must be extremely careful when using `setjmp()`/`longjmp()` with C++ and some standards explicitly ban their use.

https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=88046492
