### ISSUE TITLE
Name the download link googletest-release-1.7.0 instead of release-1.7.0

### ISSUE THREAD

**Issue by emmenlau** [google/googletest#693]
The download link for the latest release is for example
https://github.com/google/googletest/archive/release-1.7.0.tar.gz
However when downloading the file, its actually named googletest-release-1.7.0.tar.gz, which is a better
and more descriptive name. Could the download link (url) also be named the same, so:
https://github.com/google/googletest/archive/googletest-release-1.7.0.tar.gz ?
Otherwise the current name behaves differently when downloading from the browser
versus automatic downloaders like wget, and it breaks our build system.

**Comment by vapier** [comment]
this behavior is built in to github.  it's not something projects can control.  using a tag name as you suggest would mean "googletest-" would get inserted more than once.

if you're using wget, you can just use the -O option to rename it.

**Comment by rleigh-codelibre** [comment]
Not all infrastructure allows renaming though.  I have to put up with the same poor naming since the option to rename the downloaded file doesn't exist using the build infrastructure I use.

If you named the release tags `googletest-${version}` it would be quite clear what was being downloaded and there would be no need for renaming.

**Comment by vapier** [comment]
as i said, this is how the majority of github projects work.  if your infra is so bad as to not handle this common case, fix your infra.  github already provides a header explicitly with the preferred download name and that's how browsers rename, and what `wget --content-disposition` supports:
```
$ HEAD https://github.com/google/googletest/archive/release-1.8.0.tar.gz | grep filename
Content-Disposition: attachment; filename=googletest-release-1.8.0.tar.gz

$ wget -nv --content-disposition https://github.com/google/googletest/archive/release-1.8.0.tar.gz
2016-09-13 13:47:40 URL:https://codeload.github.com/google/googletest/tar.gz/release-1.8.0 [1281617/1281617] -> "googletest-release-1.8.0.tar.gz" [1]
```

also as i said, that tag naming convention is bad: it messes up the contents of the tarball.  it wouldn't be `googletest-release-1.8.0/travis.sh`, it'd be `googletest-googletest-release-1.8.0/travis.sh`.

are you going to go to every single github project out there and ask them to change their tag naming conventions just to workaround your broken infra ?  while simultaneously making it worse for people who have sane infra ?  don't you think that's unreasonable ?

**Comment by emmenlau** [comment]
Hi Vapier, do I understand correctly that when you create a tag "xxx", then github creates the download archive as "xxx.tar.gz" with content directory "googletest-xxx"? This seems completely broken! That is not a question of broken user infrastructure, that is broken github functionality.
In any case if this is true, then we should complain to github, not the individual projects.

**Comment by KindDragon** [comment]
Why it's broken? Directory "googletest-xxx" contain all source code including googlemock

**Comment by emmenlau** [comment]
The naming is broken.

**Comment by vapier** [comment]
as i showed, github names the tarball `googletest-xxx.tar.gz`, but the URI is `.../xxx.tar.gz`.

yes, this is entirely something github provides and no individual project has control over.

**Comment by emmenlau** [comment]
Dear @vapier , I do not feel too passionate about this, so I'll close the issue. But just to mention, several other projects somehow managed to get this fixed. I assume they use a release style that creates matching names for the tar archives. From the 20 or 30 projects I follow on github releases, there are only two or three where the tar archives are named differently than the contained source directory, so there must be some way around this github limitation.
But in any case, its not a big issue...

**Comment by vapier** [comment]
projects can manually create tarballs and upload them, but it's a waste of resources in scenarios like this where the tarball is a copy of the git tag

**Comment by emmenlau** [comment]
I think that github has a simpler solution, and after some googling I found a suggestion here: https://stackoverflow.com/questions/20774727/how-does-github-releases-generate-archive-filenames

When the link to the tarball is modified to contain the full name after the tag name, then all download tools are happy and everything is consistent. As an example, the current googletest release download link is https://github.com/google/googletest/archive/release-1.8.0.tar.gz but instructs the web browser to expect a file named `googletest-release-1.8.0.tar.gz`. This works in most browsers but requires extra settings on automatic download tools and continuous integration services. If you modify the above link, and add the full tarball name after the tag name (like so https://github.com/google/googletest/archive/release-1.8.0/googletest-release-1.8.0.tar.gz) then all downloaders will be happy! :-)

In any case, its not such a big issue for me anymore, so feel free to ignore the request. And thanks for the good work on googletest!
