### ISSUE TITLE
Unsupported flag in cmake for gcc 3.4

### ISSUE THREAD

**Issue by ihsandemir** [google/googletest#695]
-Wno-missing-field-initializers flag in file 
googletest/googletest/cmake/internal_utils.cmake is not supported for gcc version 3.4 . This should be handled.

**Comment by punkkeks** [comment]
Your Compiler is over 10 years old. How about updating it?!

**Comment by ihsandemir** [comment]
Hello,

Due to backward compatibility, we can not upgrade the compiler. I don't see in your documentation what is the minimum supported version of gcc and i assumed that it needs to support gcc 3.4 since it claims to support CPP98 standard.
