### ISSUE TITLE
testing::internal::CaptureStdout();

### ISSUE THREAD

**Issue by mknafl** [google/googletest#696]
This function is not working in an MFC app.  I am trying to use it to capture the test output and send to a CStatic control on a window.  

testing::internal::CaptureStdout();
std::cout << "My test";
std::cout.flush();
std::string output = testing::internal::GetCapturedStdout();

results in a blank string.  Any help is appreciated!

**Comment by kdawgwilk** [comment]
I am also trying to use this to test `operator<<` overloads to make sure the right text is outputted but haven't been able to find a good way to do so

**Comment by sbenzaquen** [comment]
On Wed, Mar 22, 2017 at 8:31 PM, Kaden Wilkinson <notifications@github.com>
wrote:

> I am also trying to use this to test operator<< overloads to make sure
> the right text is outputted but haven't been able to find a good way to do
> so
>
Using cout for this is unnecessary and undesired.
You can use a locally defined stream object, like a std::stringstream,
which is much simpler than trying to capture cout.
It is also better because you can't control what other threads might be
pushing into cout, but the local object is under your control.
_Sam

**Comment by Dekken** [comment]
@sbenzaquen regardless of your suggestion (which I agree with BTW)

Cross platform consistency should be desired, or the feature reconsidered entirely

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by Dekken** [comment]
This is still an issue

**Comment by Dekken** [comment]
Closing older issues don't stop the issue existing.

**Comment by gennadiycivil** [comment]
In any case if this is an issue you are welcome to provide actual details with completely reproducible unit test.
However please be aware that testing::internal is an internal only namespace. None of these functions are to be used directly by the client code.

**Comment by Dekken** [comment]
The details are in the ticket above - cross platform consistency is desirable.

A unit test won't be reproducible across platforms and that's the point
