### ISSUE TITLE
Add tmux / tmux-256color to the list of TERMs with color

### ISSUE THREAD

**Issue by achimnol** [google/googletest#698]
https://github.com/google/googletest/blob/82b11b8/googletest/src/gtest.cc#L2927-L2936
The above lines of code are defining the list of known-good terminals for colored output.

I would suggest to add "tmux" and "tmux-256color", as tmux v2.1 (latest at the time of writing) now enforces screen-compatible behavior (e.g., altering italics) and suggests to use "tmux" and "tmux-256color" terminals for those who want such extra customizations. Moreover, some Linux distros such as ArchLinux contain these terminals by default, and I see no reason why there is only screen but tmux. ;)

**Comment by BillyDonahue** [comment]
Sounds good. Can you send a PR for that?
