### ISSUE TITLE
Segfault in gtest-linked_ptr.h

### ISSUE THREAD

**Issue by jensBrunel** [google/googletest#712]
I wrote a simple testcase which ran without any problems under linux. I used the same testcase under cygwin (Version 1.7.19-1, gcc 4.5.3) but the testcase threw a segfault in  gtest-linked_ptr.h:113
[gtest_seg_fault_gdb_bt.txt](https://github.com/google/googletest/files/130477/gtest_seg_fault_gdb_bt.txt)

Testcase code:
`TEST(SuiteSplitTest, split_long_string)
    {
        //Create mock object
        StringReturnMock mockString;
        //Tell mock to return value
        EXPECT_CALL(mockString, getStringAsChar()).WillOnce(::testing::Return("Dieter"));
        std::vector<std::string> returnString = split(mockString.getStringAsChar(), "i");
        std::string expectedString = "D";
        ASSERT_STREQ("D", returnString[0].c_str());
    }`

**Comment by jhbe** [comment]
I'm looking at a segmentation fault on the same line. Windows 10, MinGW x86_64-5.3.0-posix-seh-rt_v4-rev0. I use no optimization (-O0). To eliminate differences in compiler flags I use a fused gmock generated with googletest/googlemock/scripts/fuse_gmock_files.py; obviously that didn't help.

[This](https://bugs.chromium.org/p/google-breakpad/issues/detail?id=269) post looks applicable.
