### ISSUE TITLE
Multiple test projects could be run in parallel rather than sequentially.

### ISSUE THREAD

**Issue by TimYorke** [google/googletest#720]
It would be great if, in the case of solutions with multiple test projects, the test executables could be run in parallel instead of running the 'exe's one at time.

**Comment by Bu11etmagnet** [comment]
There's nothing preventing this. 

```
##### Makefile start
TEST_PROGRAMS := test1 test2 ...
%-run: %
        ./$<

checks: $(addsuffix -run, $(TEST_PROGAMS))
##### Makefile end

```
$ make -j8 checks
