### ISSUE TITLE
ASSERT_NO_THROW does not accept any valid C++ statement

### ISSUE THREAD

**Issue by skypjack** [google/googletest#733]
As from the title, `ASSERT_NO_THROW` does not accept any valid C++ statement.
I suspect that the same problem affects almost all the available macros, even though the documentation does not state anything about what _statement_ really means.

As an example, consider the following code that compiles fine, being `f` valid C++ code:

```
#include <gtest/gtest.h>

void f() {
    int i;
    i = 0, 0;
}

TEST(Foo, Bar) {
    ASSERT_NO_THROW(f());
}
```

Anyway, if I move the body of `f` to the `ASSERT_NO_THROW` macro, it doesn't work anymore:

```
#include <gtest/gtest.h>

TEST(Foo, Bar) {
    ASSERT_NO_THROW({
        int i;
        i = 0, 0;
    });
}
```

This time, I get the error:

> error: macro "ASSERT_NO_THROW" passed 2 arguments, but takes just 1

I suggest either to fix the issue (if it can be considered an issue) or update the documentation in order to better define what _statement_ really means.

**Comment by BillyDonahue** [comment]
Dup of #219. I think we are okay assuming common knowledge of the limitations of macros here. You need more parens here because you have a comma in the argument.

**Comment by skypjack** [comment]
Oh, sorry, haven't seen the #219. My fault.
Well, fair enough, but saying in the documentation that *statement is any C++ valid statement* could lead to quite annoying errors (of course, easy to solve once one find that he's using commas when he should not).
Maybe a hint in the documentation about extra parentheses would help.

**Comment by BillyDonahue** [comment]
Can you send a PR to fix the docs?

**Comment by skypjack** [comment]
Sure, if you find it a good idea to add a note like that one, I'd be glad to send a PR.
Anyway, in Italy is almost midnight, I guess I'll send it tomorrow.
Can it be a note at the top or the end of the page, saying to mind the limitation of the macros when one defines his *statement*s?

**Comment by BillyDonahue** [comment]
On Sun, Mar 6, 2016 at 5:27 PM, Michele Caini <notifications@github.com>
wrote:

> Sure, if you find it a good idea to add a note like that one, I'd be glad
> to send a PR.
> Anyway, in Italy is almost midnight, I guess I'll send it tomorrow.
> Can it be a note at the top or the end of the page, saying to mind the
> limitation of the macros when one defines his *statement*s?
>
I guess if it works in the doc. I'd have to see it.
