### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by daviddoria** [google/googletest#746]
I noticed that 1.7.0 is the latest release and is more than 2 years old even though the project seems to still be actively developed. Should the repository after 1.7.0 be considered unstable? Are there plans for a release anytime soon?

**Comment by kkm000** [comment]
Yes, please make a release! The last release 1.7.0 contains gtest only, without gmock.

While GitHub provides URLs for downloading source at any commit or tag, there is not even a tag. Even simply tagging a version considered a stable release would be awesome!

**Comment by onyb** [comment]
Any updates on this?

**Comment by skyscribe** [comment]
A brand official new release is definitely needed, otherwise we have to ship the fused headers and cc files everywhere - considering the fused API is not so trivial (**1~2 MB**), new release would allow system level stuffs be pre-installed, even by ppa on Ubuntu.

**Comment by izaid** [comment]
A new release would be great. I don't understand why there isn't one.

**Comment by schwaerz** [comment]
Is there at least some rough planning available at what time or implemented scope the next release is going to happen?

**Comment by BillyDonahue** [comment]
I want to stamp a v1.8.0, but let's make sure it builds everywhere. I accepted a PR to fix MSVC15 issues as recently as last week.

**Comment by jakirkham** [comment]
Happy to help test. Should we try tip or is there some other commit you recommend?
