### ISSUE TITLE
can't use braced initialization in EXPECT_THROW

### ISSUE THREAD

**Issue by nholthaus** [google/googletest#747]
this compiles:

```
EXPECT_THROW(std::vector<int> test{1}, std::bad_alloc);
```

but this does not:

```
EXPECT_THROW(std::vector<int> test{1, 2, 3, 4, 5}, std::bad_alloc);
```

> main.cpp(2077): warning C4002: too many actual parameters for macro 'EXPECT_THROW'
> main.cpp(2077): error C2143: syntax error : missing '}' before ';'
> main.cpp(2077): error C2059: syntax error : 'constant'
> main.cpp(2077): error C2310: catch handlers must specify one type

Obviously this `vector<int>` wont throw, but it is difficult in general to use gtest to check for exception safety due to this limitation.

**Comment by sbenzaquen** [comment]
On Tue, Mar 22, 2016 at 8:16 AM, Nic Holthaus <notifications@github.com>
wrote:

> this compiles:
>
> EXPECT_THROW(std::vector<int> test{1}, std::bad_alloc);
>
> but this does not:
>
> EXPECT_THROW(std::vector<int> test{1, 2, 3, 4, 5}, std::bad_alloc);
>
>
This is a limitation of the macro.
The preprocessor doesn't understand the braces so it thinks you are passing
6 arguments to a macro that takes 2.
The solution is to add parens around the expression to let the preprocessor
know it is a single argument:

EXPECT_THROW((std::vector<int>{1, 2, 3, 4, 5}), std::bad_alloc);

You have the same problems in other macros.

Eg:

You can't say: EXPECT_FALSE(std::is_same<int, long>::value);

You have to add extra parens: EXPECT_FALSE((std::is_same<int, long>::value));

_Sam
