### ISSUE TITLE
How to configure  google test to provide "Actual vs Expected values in log" information for even success cases

### ISSUE THREAD

**Issue by gkr898** [google/googletest#751]
Ex) in my test if am using EXPECT_EQ(14, Get_Status()) then even in success case i need some thing like
Actual:14
Expected:14
Success

This information is currently provided only for failures,but i need for success cases too..

**Comment by Bu11etmagnet** [comment]
Gmock and Gtest adhere to the "no news is good news" philosophy. Success is indicated by the lack of error messages. You really, really want them to work this way. When you have hundreds of EXPECT_... checks and one of them fails, you want just the one failure message, not one failure message buried amongst hundreds of success messages.

**Comment by gkr898** [comment]
I agree,but for Peer Review process,and as per out project need  we need more details.Simple log is not acceptable.So is there any way to achieve that??

**Comment by fallenworld1** [comment]
auto myLoggingEQ = [](auto actual, auto expected){
(actual  == expected ? cout: FAIL())<<"Actual: "<< actual<< "\nExpected: "<< expected<<'\n';
}
myLoggingEQ (Get_Status(),14);

something like that
