### ISSUE TITLE
Documentation does not specify where to find / how to install gmock.

### ISSUE THREAD

**Issue by nathan-at-least** [google/googletest#763]
I'm new to this project, and I checked out the release-1.7.0 only to discover it does not contain gmock. A quick search finds many people running into a similar issue: #746, #717, and #684 for example.

The [github googlemock README](https://github.com/google/googlemock#googlemock) says it has been "absorbed into" googletest, but there are no clear instructions for how to use the integrated codebase, and there's no clear release with both.

**Comment by mazong1123** [comment]
Just download the source code from master branch. And you will be able to find the googlemock folder and corresponding make files.

As our project using gtest/gmock heavily, I just forked this project and may publish newer releases for our needs (as google does not publish newer release for nearly 3 years!)

**Comment by casantos** [comment]
This issue probably became irrelevant, like #717, considering that gtest 1.8.0 was released and already contains gmock.

**Comment by gennadiycivil** [comment]
Looks stale/irrelevant
