### ISSUE TITLE
rookie mistake! googletest: make test -> Help!

### ISSUE THREAD

**Issue by PAFlores** [google/googletest#767]
What am I doing wrong!

I run make test and this is what I see which appears to be wrong!
Running tests...
Start processing tests
Test project /home/pflores/shop/googletest/build02
No tests were found!!!

Any help is appreciated!

**Comment by mazong1123** [comment]
If you success to build the gtest/gmock code, you'd better check the code of your own project.
Gtest may fail to find test cases if:
1. Lack of testing::InitGoogleMock(&argc, argv) or RUN_ALL_TESTS() in your test runner.
2. No TEST or TEST_F marco found in your test case source files.
