### ISSUE TITLE
let users inherit from PrettyUnitTestResultPrinter

### ISSUE THREAD

**Issue by jwuttke** [google/googletest#771]
The Advanced Guide describes how a user can write his own Listener, inheriting from EmptyTestEventListener. In many cases, users would be better served if they could inherit from the default listener (PrettyUnitTestResultPrinter) and overwrite just those methods they would like to change. Why not expose PrettyUnitTestResultPrinter in gtest.h ?

**Comment by Irubataru** [comment]
This is a fairly old issue but I am very much in favour of this. I am currently looking at making a pretty-listener for MPI codes, and I would very much prefer not having to copy paste all of the PrettyUnitTestResultPrinter code to extend its behaviour.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
