### ISSUE TITLE
Error C2440 'return': cannot convert from 'const testing::internal::EqMatcher<testing::gmock_matchers_test::ConvertibleFromAny>' to 'testing::Matcher<testing::gmock_matchers_test::ConvertibleFromAny>'	gmock_test

### ISSUE THREAD

**Issue by mazong1123** [google/googletest#775]
I've got following error message when building gmock_test in visual studio 2015:

>D:\Workspace\github\googletest\googlemock\include\gmock/gmock-matchers.h(555): error C2440: 'return': cannot convert from 'const testing::internal::EqMatcher<testing::gmock_matchers_test::ConvertibleFromAny>' to 'testing::Matcher<testing::gmock_matchers_test::ConvertibleFromAny>'
2>  D:\Workspace\github\googletest\googlemock\include\gmock/gmock-matchers.h(555): note: No constructor could take the source type, or constructor overload resolution was ambiguous
2>  D:\Workspace\github\googletest\googlemock\include\gmock/gmock-matchers.h(546): note: while compiling class template member function 'testing::Matcher<testing::gmock_matchers_test::ConvertibleFromAny> testing::internal::MatcherCastImpl<T,M>::CastImpl(const M &,testing::internal::BooleanConstant<true>)'
2>          with
2>          [
2>              T=testing::gmock_matchers_test::ConvertibleFromAny,
2>              M=testing::internal::EqMatcher<testing::gmock_matchers_test::ConvertibleFromAny>
2>          ]
2>  D:\Workspace\github\googletest\googlemock\include\gmock/gmock-matchers.h(531): note: see reference to function template instantiation 'testing::Matcher<testing::gmock_matchers_test::ConvertibleFromAny> testing::internal::MatcherCastImpl<T,M>::CastImpl(const M &,testing::internal::BooleanConstant<true>)' being compiled
2>          with
2>          [
2>              T=testing::gmock_matchers_test::ConvertibleFromAny,
2>              M=testing::internal::EqMatcher<testing::gmock_matchers_test::ConvertibleFromAny>
2>          ]
2>  D:\Workspace\github\googletest\googlemock\include\gmock/gmock-matchers.h(611): note: see reference to class template instantiation 'testing::internal::MatcherCastImpl<T,M>' being compiled
2>          with
2>          [
2>              T=testing::gmock_matchers_test::ConvertibleFromAny,
2>              M=testing::internal::EqMatcher<testing::gmock_matchers_test::ConvertibleFromAny>
2>          ]
2>  D:\Workspace\github\googletest\googlemock\test/gmock-matchers_test.cc(638): note: see reference to function template instantiation 'testing::Matcher<testing::gmock_matchers_test::ConvertibleFromAny> testing::MatcherCast<testing::gmock_matchers_test::ConvertibleFromAny,testing::internal::EqMatcher<testing::gmock_matchers_test::ConvertibleFromAny>>(const M &)' being compiled
2>          with
2>          [
2>              M=testing::internal::EqMatcher<testing::gmock_matchers_test::ConvertibleFromAny>
2>          ]

**Comment by xmclark** [comment]
I also have this issue

**Comment by ashwinrs** [comment]
I do too.

**Comment by kiydev** [comment]
I experienced the same issue. Somewhat of a workaround - #661

**Comment by BillyDonahue** [comment]
I don't think #661 fixed this. There's no fix yet.

**Comment by kiydev** [comment]
Right, #661 is still Open. But, I got it building (in December) by using cmake:  https://github.com/google/googletest/issues/661#issuecomment-169212423

**Comment by BillyDonahue** [comment]
So we could get a PR generated by running cmake to produce MSVC's project files.
But you mentioned some difficulty with x64 support?

**Comment by kiydev** [comment]
I'm rather new to CMake, so, it's quite possible that it is a simple option to set so that it makes the x64 VS project configurations. I manually (hopefully out of ignorance) added all the x64 configurations after running cmake (and it was quite annoying because of how the x86 configurations were produced).

**Comment by mazong1123** [comment]
Just send PR #821 to address this issue. @BillyDonahue please check. As stated in the PR description, I've seen the fix somewhere a couple of weeks ago, but I can't to find the author now. So I just send the PR by myself.

**Comment by mazong1123** [comment]
Close this issue as #821 fixed it.
