### ISSUE TITLE
Missing don't define macros for EXPECT_XY() macros

### ISSUE THREAD

**Issue by justy989** [google/googletest#777]
Don't define macros, which allow naming conflict resolution with client code, are available for ASSERT_XY() macros, but not available for EXPECT_XY() macros.

**Comment by BillyDonahue** [comment]
I imagine this is because ASSERT_ pops up in the wild frequently and
EXPECT_ doesn't.

**Comment by justy989** [comment]
In the current project I'm working on, which uses googletest to unittest, we have EXPECT_TRUE() and EXPECT_FALSE() macros build around gcc's __builtin_expect() branch prediction function. It would be useful for us to have GTEST_EXPECT_XY() macros in the same form as the GTEST_ASSERT_XY() macros. I've made these change locally for our project, so I've submitted pull request #770.
