### ISSUE TITLE
Error google test when build a project with Eclipse and MinGW

### ISSUE THREAD

**Issue by p4535992** [google/googletest#784]
Hi , i just started to use google test so maybe this is already a solved issue, but i haven't find anything similar to mi issue online. I have followed the documentation on the link [https://github.com/google/googletest/blob/master/googletest/docs/Primer.md#writing-the-main-function](https://github.com/google/googletest/blob/master/googletest/docs/Primer.md#writing-the-main-function) .
I'm using Windows with MinGW and i have build it google test with the file 'fuse_gtest_files.py' and i generate 'gtest.h' and  'gtest-all.c' , i copied the 'gtest/include' files to 'C:/MinGW/include' folder, here my example code:

``` c++
#include <gtest/gtest.h>
#include "Rectangle.h"
#include "Shape.h"
#include "Point.h"

class TestRectangleGoogle: public ::testing::Test {
protected:
  TestRectangleGoogle() {}
  virtual ~TestRectangleGoogle() {}
  virtual void SetUp() {}
  virtual void TearDown() {}
};

TEST(TestRectangleGoogle,testRectangle){
    Point p1(2, 3);
    Point p2(4, 8);
    Rectangle r1(p1, p2);
    ASSERT_TRUE(r1.getTopLeft() == p1);
    ASSERT_TRUE(r1.getBottomRight() == p2);
    Shape* pS = new Rectangle();
    delete pS;
    pS = new Rectangle(p1, p2);
    delete pS;
}

TEST(TestRectangleGoogle,testDraw) {
    Point p1(2, 3);
    Point p2(4, 8);
    Rectangle r1(p1, p2);
    bool result = r1.draw();
    ASSERT_EQ(result, true);
}
```

Now i try with two ways:
1.  first i just include the dependecy 'gtest.h' i copied before on the folder 'C:/MinGW/include' so i expected that is enough for work with google test, but when i run the build i got the following error on the 'TEST' function: "undefined reference to xxx", i put a screenshot of the problem on eclipse:

Out of the class: [image1](http://s6.postimg.org/5vb8e34pt/eclipse_error1.png)
In the class: [image2](http://s6.postimg.org/xwp9rsa01/eclipse_error2.png)
1. Second i try to use directly the generated file  'gtest.h' and  'gtest-all.c' by included them on my project, but i get another error "cannot define member function..." here the screenshot [image3](http://s6.postimg.org/5l3puqq3l/eclipse_error3.png).

For anyone want to help i put a online copy of the test to this [link](https://github.com/p4535992/test_googletest)
Ty in advance for any help.

**Comment by Bu11etmagnet** [comment]
1. You shouldn't use TEST() inside a class. The TEST() macro defines a class.
2. If you want to use a test fixture, you need to use TEST_F(), not TEST().

So don't do this

```
class MyTest : public ::testing::Test {
  // ...
   TEST(MyTest, testRectangle) { ... }
};

```
Do this

```
class MyTest : public ::testing::Test {
  // ...
};

TEST_F(MyTest, testRectangle) { ... }
```

The class defined by TEST_F() is derived from MyTest, so all the (public and protected) members are available.

**Comment by p4535992** [comment]
Hi ty for the fast reply, i've solved the previous issue, but now i have this build error:
```text
Info: Internal Builder is used for build
g++ "-IC:\\Users\\tenti\\eclipse\\workspace-lab-c\\TestHelloWith6Polymorphism" "-includeC:\\MinGW\\include\\gmock-gtest-all.cc" -O0 -g3 -Wall -c -fmessage-length=0 -o Shape.o "..\\Shape.cpp" 
In file included from <command-line>:0:0:
C:\MinGW\include\gmock-gtest-all.cc: In constructor 'testing::internal::Mutex::Mutex()':
C:\MinGW\include\gmock-gtest-all.cc:8791:45: error: cannot convert 'CRITICAL_SECTION* {aka _CRITICAL_SECTION*}' to '_RTL_CRITICAL_SECTION*' in initialization
       critical_section_(new CRITICAL_SECTION) {
                                             ^
C:\MinGW\include\gmock-gtest-all.cc:8792:48: error: cannot convert '_RTL_CRITICAL_SECTION*' to 'LPCRITICAL_SECTION {aka _CRITICAL_SECTION*}' for argument '1' to 'void InitializeCriticalSection(LPCRITICAL_SECTION)'
   ::InitializeCriticalSection(critical_section_);
                                                ^
C:\MinGW\include\gmock-gtest-all.cc: In destructor 'testing::internal::Mutex::~Mutex()':
C:\MinGW\include\gmock-gtest-all.cc:8802:46: error: cannot convert '_RTL_CRITICAL_SECTION*' to 'PCRITICAL_SECTION {aka _CRITICAL_SECTION*}' for argument '1' to 'void DeleteCriticalSection(PCRITICAL_SECTION)'
     ::DeleteCriticalSection(critical_section_);
                                              ^
C:\MinGW\include\gmock-gtest-all.cc: In member function 'void testing::internal::Mutex::Lock()':
C:\MinGW\include\gmock-gtest-all.cc:8810:43: error: cannot convert '_RTL_CRITICAL_SECTION*' to 'LPCRITICAL_SECTION {aka _CRITICAL_SECTION*}' for argument '1' to 'void EnterCriticalSection(LPCRITICAL_SECTION)'
   ::EnterCriticalSection(critical_section_);
                                           ^
C:\MinGW\include\gmock-gtest-all.cc: In member function 'void testing::internal::Mutex::Unlock()':
C:\MinGW\include\gmock-gtest-all.cc:8820:43: error: cannot convert '_RTL_CRITICAL_SECTION*' to 'LPCRITICAL_SECTION {aka _CRITICAL_SECTION*}' for argument '1' to 'void LeaveCriticalSection(LPCRITICAL_SECTION)'
   ::LeaveCriticalSection(critical_section_);
                                           ^
C:\MinGW\include\gmock-gtest-all.cc: In member function 'void testing::internal::Mutex::ThreadSafeLazyInit()':
C:\MinGW\include\gmock-gtest-all.cc:8841:27: error: cannot convert 'CRITICAL_SECTION* {aka _CRITICAL_SECTION*}' to '_RTL_CRITICAL_SECTION*' in assignment
         critical_section_ = new CRITICAL_SECTION;
                           ^
C:\MinGW\include\gmock-gtest-all.cc:8842:54: error: cannot convert '_RTL_CRITICAL_SECTION*' to 'LPCRITICAL_SECTION {aka _CRITICAL_SECTION*}' for argument '1' to 'void InitializeCriticalSection(LPCRITICAL_SECTION)'
         ::InitializeCriticalSection(critical_section_);
                                                      ^
C:\MinGW\include\gmock-gtest-all.cc: In static member function 'static void testing::internal::ThreadLocalRegistryImpl::StartWatcherThreadFor(DWORD)':
C:\MinGW\include\gmock-gtest-all.cc:9044:21: error: '::OpenThread' has not been declared
     HANDLE thread = ::OpenThread(SYNCHRONIZE | THREAD_QUERY_INFORMATION,
                     ^

20:23:59 Build Finished (took 6s.234ms)
```
This is a problem already question so i just put the reference to the previous issue and close the this ticket. 
**#708 [GTest not compiling](https://github.com/google/googletest/issues/708)**

**Comment by gennadiycivil** [comment]
This should be solved by now. we have MinGW in CI as part of AppVeyor

**Comment by Sissroh** [comment]
Hello all,

Firts time with Gmock framework, I am trying to use simple example of google mock.
Is someone can tell me what I am doing wrong here ?

Thanks.

Here is my code in one file Test.h

class myInterface
{
public:
virtual ~myInterface(){}

virtual bool isReady(void) = 0;
};

class ConcreteImpl : public myInterface
{
public:
bool isReady(){return true;};
};

class MockInterface : public myInterface
{
public:
MOCK_METHOD0(isReady, bool());
};

Here my Test.cpp file using BOOST LIB

class TestDriver
{
public:
TestDriver()
{
BOOST_TEST_MESSAGE("execute TestSetup constructor");
};

~TestDriver()
{
BOOST_TEST_MESSAGE("execute TestSetup destructor");
};

MockInterface mxDriver; // if I comment out this line, it is compiling.
};

when I compile, I am getting an error :
tests\test_src\build/googletest-src/googletest/src/gtest-port.cc:275: multiple definition of `testing::internal::Mutex::Lock()'

CMakeFiles/Test.dir/test_src/DriverTest.cpp.obj:C:tests\test_src\build/googletest-src/googletest/include/gtest/internal/gtest-port.h:2262: first defined here

collect2.exe: error: ld returned 1 exit status
