### ISSUE TITLE
Link Error in VC14

### ISSUE THREAD

**Issue by daB0bby** [google/googletest#787]
`LNK2019	unresolved external symbol "public: __cdecl Settings::~Settings(void)" (??1Settings@@QEAA@XZ) referenced in function "void __cdecl public: static class getInstance & __cdecl Settings::getInstance(void)'::`2'::`dynamic atexit destructor for 'instance''(void)" (??__Finstance@?1??getInstance@Settings@@SAAEAV1@XZ@YAXXZ)`

`LNK2019	Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "private: __cdecl Settings::Settings(void)" (??0Settings@@AEAA@XZ) referenced in function "public: static class Settings & __cdecl Settings::getInstance(void)" (?getInstance@Settings@@SAAEAV1@XZ)`

`LNK1120	2 unresolved externals`

this is what my code looks like:

    #include "gtest/gtest.h"
    #include "src/Core/Settings.hpp"

    class SettingsTest : public ::testing::Test
    {
        protected:
            Settings& settings = Settings::getInstance();

            void SetUp() override
            {

            }

        // virtual void TearDown() {}
    };

    TEST_F(SettingsTest, test)
    {
        // Dummy test
        EXPECT_EQ(4, 2 * 2);
    }`

This fails building. If i remove the `Setinngs.hpp` include it works fine.

I'm using Visual Studio 2015.

**Comment by mazong1123** [comment]
The unresolved external symbol error means the linker failed to find the some definitions of your Settings class, which declared in Settings.hpp, used in SettingsTest class. Please ensure you implemented the Settings::~Settings(void) method. 

This error is probably not related to gtest.
