### ISSUE TITLE
CMake build names Release and Build binaries identically

### ISSUE THREAD

**Issue by planetmarshall** [google/googletest#798]
Both Release and Debug configurations for Google Test DLL build in Visual Studio create libraries called 'gtest.dll', etc. This is causing problems with downstream CMake scripts using FindGTest, which expect the Debug Dll to be named 'gtestd.dll'.

Linking a Debug test project with a Release dll crashes the test executable.

Platform:
Windows 10
Visual Studio 2015

**Comment by eldruin** [comment]
As a workaround, you can use the standard CMAKE_DEBUG_POSTFIX variable to set the postfix to "d" when building GoogleTest. PR #685 also contains a fix for this, although it is off by default.
