### ISSUE TITLE
Retro fitting Google Mock/Test

### ISSUE THREAD

**Issue by prasdeva** [google/googletest#800]
Apologies for submitting question as issue.

I am familiar with gtest/mock and using it for some time now, working good. However I have to a new requirement to retro fit gtest/mock to legacy code which has opened up some questions. Current issue I am facing is at dependency injection for concreate class.

I have some classes which use concrete class ie not interface. Obviously gmock doesn't like it. 

Will throw some code to make my self clear.

```
class ClassUnderTest
{
ClassUnderTest(ConcreateClassA *A, ConcreateClassB *B)
...
}
```

Now for mocking objects A and B

```
class MockA : public ConcreateClassA{}
class MockB : publci ConcreateClassB{}
```

This compiles fine but my mock methods never get executed. Bisecting MockA and MockB in IDE I see gmockX_XX method points to base (ie ConcreateClass) rather than my derived mocked class (MockA and MockB)

Is there any way I can work around this ie be able to mock concreate class as well ?

Any input would be highly appreciated!

Thanks in advance
prasdeva

**Comment by mazong1123** [comment]
Is there any virtual method in ConcreateClassA and B? You need to specify MOCK_METHODX to actually mock or stub the methods. 

If there's no virtual methods in your concreate classes, you have 2 options:
1. Change your existing code with C++ template http://stackoverflow.com/questions/5777733/mock-non-virtual-method-c-gmock
2. Leveraging inline asm to change the method's behavior at runtime. The implementation depends on your compiler. For Visual C++, here is a good starting point: https://github.com/mazong1123/injectorpp (Stll in development). For gcc, by leveraging __cyg_profile_func_enter and __cyg_profile_func_exit, it's able to inject opcode to any custom class method, to change the method's behavior.

**Comment by prasdeva** [comment]
Thanks for your message mazong1123.

I had virtual methods in ConcreateClassA and B ie destructor however method being mocked was not virtual. On making them virtual test program worked.

Do you expect to mock a concreate class with just virtual destructor successfully ?
prasdeva

**Comment by mazong1123** [comment]
No. To clarify, the method to be tested must be virtual, gmock just override virtual method to add internal test code. No magic :) . So if you can change the legacy code to make the methods virtual, it's good to go.

However, the legacy code could not be changed at sometime, then you may consider my 2 options aforementioned.
