### ISSUE TITLE
Googlemocks - Test Authoring and Execution crash in Visual Studio 2015 when run all selected

### ISSUE THREAD

**Issue by SimonReaddie** [google/googletest#812]
Hi
Just started using googlemocks 1.7.0,  with Visual Studio 2015 update 2 and I am getting a crash in the 'Test authoring and execution framework' when I attempt to run all my tests. (See attached screen shot)
I can run the tests individually it’s just the 'run all' that seems to cause problems.
I have attached a very simple unit test that shows this problem.
Seems to be a access violation (0xc0000005) as the test method exits
Is this a problem in googlemocks, VS2015 test framework or have I done something silly!

![screen shot](https://cloud.githubusercontent.com/assets/20164456/16375968/0137a444-3c56-11e6-88a4-07807f7a73e8.png)

[UnitTestAndMocks.zip](https://github.com/google/googletest/files/334559/UnitTestAndMocks.zip)

**Comment by mazong1123** [comment]
I'm not able to reproduce the problem with the latest source code of gtest in the master branch. Please try again with the latest gtest code. 

Note, I changed the code generation/runtime library to Multi-threaded Debug (/MTd) as my gtest/gmock was compiled as a static library. I don't know if it impacts the result.

**Comment by SimonReaddie** [comment]
Hi
Since by original post we have update to VS2015 update 3.
I tried the latest code from the branch as suggested and had the same problems.

However I have now found a fix / workaround for my problem.
Its to  unckeck the 'Keep test execution engine running between test runs' option found in the menu Test -> Test Settings in visual studio 2015.  - 'Run all' now works.
