### ISSUE TITLE
Coloured output under MinGW/MSYS2/MinTTY is broken

### ISSUE THREAD

**Issue by jtanx** [google/googletest#826]
Even if `--gtest_color=yes` is specified, no colour is displayed when running under msys2 (MinTTY; `$TERM==xterm`).

Correct me if I'm wrong, but a brief search indicates that gtest always assumes that on Windows (but not cygwin?), it's running under a standard Windows console (i.e. cmd.exe) and hence uses WinAPI functions (`SetConsoleTextAttribute`) to change text colours.

However, this won't work if it's run under a terminal emulator such as mintty, which expects ANSI escape codes.

**Comment by Bu11etmagnet** [comment]
[Works fine for me ](http://imgur.com/a/PIrri)

**Comment by jtanx** [comment]
Yes... But is that MinTTY? Either your shell interpreter is running in a native Windows console or because it's Cygwin gtest's outputting ansi escape codes. Try doing the same thing under MinGW/msys2.

**Comment by Bu11etmagnet** [comment]
That is (Cygwin's) mintty.

**Comment by jtanx** [comment]
Looking at #826, the reason why it probably works on Cygwin but not mingw/msys2 mintty is that cygwin builds aren't considered windows builds (GTEST_OS_WINDOWS vs GTEST_OS_CYGWIN)
