### ISSUE TITLE
make install does not work for releases 1.7, 1.6 etc.

### ISSUE THREAD

**Issue by fastrizwaan** [google/googletest#828]
could you please let "make install" work for releases of googletest like it work with git. It's need for packaging for distros. Thank you.

**Comment by mazong1123** [comment]
Can you try the latest code in the master branch? 1.7 was released 3 years ago. There's a bunch of bug fixes since then.

**Comment by fastrizwaan** [comment]
but master branch can't be packaged for distros, see fedora, opensuse, debian all of them use "release" version 1.7.0 or 1.6.0 and not the master version. The master works fine with  make install, 

I want to package it for solus. All the distro packagers have to manually specify the install paths and method, this is not fair to pacakgers. Please consider a new point release from master which has  a working make install script.  Thank you.

**Comment by mazong1123** [comment]
This may relate to #746 . Actually, I'm also expecting a brand new release from the master branch. We probably can hear from @BillyDonahue about the release schedule. :)

**Comment by BillyDonahue** [comment]
Very sorry about the delay.
A v1.8.0 release tag is in the works.
