### ISSUE TITLE
link error on my project of some environment

### ISSUE THREAD

**Issue by taozhijiang** [google/googletest#835]
I used on my gentoo desktop, all went well, but my other Fedora, Ubuntu machine, failed at the last link procedure.

failed with:
(1) gcc version 4.9.3 (Ubuntu 4.9.3-13ubuntu2) 
(2) gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2.1) 
(3) gcc version 6.1.1 20160621 (Red Hat 6.1.1-3) (GCC) 

failed message:
obj/table_name_test.o: In function `testing::AssertionResult testing::internal::CmpHelperEQ<RET_TYPE, RET_TYPE>(char const*, char const*, RET_TYPE const&, RET_TYPE const&)':
/usr/include/gtest/gtest.h:1460: undefined reference to`testing::internal::EqFailure(char const_, char const_, std::string const&, std::string const&, bool)'
collect2: error: ld returned 1 exit status
Makefile:35: recipe for target 'airobot_unit_test' failed

/home/user/BitBucket/airobot/unit_test/table_name_test.cpp:7: undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
obj/table_name_test.o: In function`testing::AssertionResult testing::internal::CmpHelperEQ<RET_TYPE, RET_TYPE>(char const_, char const_, RET_TYPE const&, RET_TYPE const&)':
/usr/include/gtest/gtest.h:1460: undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
obj/rbtree_test.o: In function`__static_initialization_and_destruction_0(int, int)':
/home/user/BitBucket/airobot/unit_test/rbtree_test.cpp:69: undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const_, char const_, char const_, char const_, void const_, void (_)(), void (_)(), testing::internal::TestFactoryBase_)'
collect2: error: ld returned 1 exit status
Makefile:35: recipe for target 'airobot_unit_test' failed
make: **\* [airobot_unit_test] Error 1

I do not know how to handle or debug this issue, if you need more test or debug info, please info me at your convience.
attached my code.
[unit_test.zip](https://github.com/google/googletest/files/375071/unit_test.zip)

Thanks in advance!

**Comment by raquya** [comment]
I'm having the same problem, any news?

**Comment by Ayymoose** [comment]
I'm also having a similar problem where I can't get rid of this linker error

`include/gtest/gtest.h:1412: undefined reference to `testing::internal::EqFailure(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'

It's driving me crazy. 
Did you manage to solve it?

**Comment by sparkleholic** [comment]
Is there any update of this?

**Comment by gennadiycivil** [comment]
Thank you very much for this report. Unfortunately there appears to be no actionable information here.
