### ISSUE TITLE
gtest_filter not working on  Windows7

### ISSUE THREAD

**Issue by tekale2** [google/googletest#837]
I have Two test cases  in my test program FooTestCase and BarTestCase, if I just want to run tests under
 FooTestCase, i use --gtest_filter=FooTestCase*
And I get the following output:
Note: Google Test filter = footestcase*
[=====] Running 0 tests from 0 test cases.
[=====] 0 tests from 0 test cases ran. (0 ms total)
[=====] 0 tests.

On the other hand if set the filter as  --gtest_filter=\*oo\*
It will successfully run all the tests under FooTestCase. It seems that the regex is only matching lower character in strings.

**Comment by janwilmans** [comment]
The filter argument is case-sensitive and the test name must be preceded by the classname  (FooClass.FooTest) so -gtest_filter=*FooTestCase* will work

**Comment by tekale2** [comment]
Using the filter option within the program works without any issues. Closing the issue.
