### ISSUE TITLE
Please git tag 1.7.0

### ISSUE THREAD

**Issue by xnox** [google/googletest#844]
Hello,

release-1.7.0 tag is not part of master. Could you please tag the master branch revision 2d3543f as 1.7.0 that way git describe would work and a stable version number could be determined for packaging snapshot releases. At this point there are bugfixes on master, and 1.7.0 release no longer builds with default compiler on Debian and Ubuntu (g++-6).

After doing `$ git tag 1.7.0 2d3543f` locally the current master head can now be identified as `1.7.0-548-gec44c6c`.

Please make a new release... Even if just a beta1 or rc1 tag, then github would generate tarballs for that source code snapshot.

**Comment by mazong1123** [comment]
Just made a release on my own version of Google Test [here](https://github.com/mazong1123/googletest/releases)

Actually it's tagged from current master branch of Google Test ( 3 commits ahead the original repository though).
