### ISSUE TITLE
Python tests are misconfigured when CMAKE_BUILD_TYPE is defined

### ISSUE THREAD

**Issue by jmacfarlane** [google/googletest#848]
In the function `py_test` from internal_utils.cmake, the path passed to the `--build-dir` option includes the configuration, which is not correct for CMake generators like Makefiles and Ninja that only support a single configuration at a time.  The current value is correct for CMake generators that support multiple configurations at a time like Visual Studio.

This problem was not caught by Travis CI because the current script does not set a configuration.  In this case, the configuration is reported as an empty string and the path is the same as if it was not included.

Merge request #846 addresses this issue and adjusts the Travis CI script to catch the regression.  A more sophisticated solution may also be possible.

**Comment by codetackler** [comment]
I ran into this problem and created a patch as a work around.  Not sure if this is the correct fix but it works for me. Note that I am using CMake 3.7

```
--- googletest/googletest/cmake/internal_utils.cmake	2016-12-20 09:21:56.000000000 -0800
+++ googletest/googletest/cmake/internal_utils.cmake.new	2016-12-20 09:43:53.000000000 -0800
@@ -243,7 +243,7 @@
       add_test(
         NAME ${name}
         COMMAND ${PYTHON_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/test/${name}.py
-            --build_dir=${CMAKE_CURRENT_BINARY_DIR}/$<CONFIGURATION>)
+            --build_dir=${CMAKE_CURRENT_BINARY_DIR})
     else (${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION} GREATER 3.1)
       add_test(
         ${name}
```
