### ISSUE TITLE
runtime error?

### ISSUE THREAD

**Issue by zhengwx11** [google/googletest#849]
I wrote a standard main.cpp (two key statements), and some testcase (test*.cpp).
If I compile them in this way :

```
g++ -c main.cpp
g++ -c test*.cpp
g++ *.o -o test
```

everything is ok.

However, if I compile them in this way:

```
g++ -c main.cpp
g++ -c test*.cpp
ar rv libtest.a test*.o
g++ main.o libtest.a -o test
```
then gtest cannot find the test case and pass quickly.

I believe that these two ways are the same in term of linking. So is this a bug? or I have wrong idea about the .a and .o?

**Comment by zhengwx11** [comment]
The compiler is g++ 4.9.2 under Ubuntu 15.04. 
Gtest is the compiled from the current master brach.

**Comment by sbenzaquen** [comment]
On Wed, Aug 10, 2016 at 11:59 AM, zhengwx11 <notifications@github.com>
wrote:

> I wrote a standard main.cpp (two key statements), and some testcase
> (test*.cpp).
> If I compile them in this way :
>
> g++ -c main.cpp
> g++ -c test*.cpp
> g++ *.o -o test
>
> everything is ok.
>
> However, if I compile them in this way:
>
> g++ -c main.cpp
> g++ -c test*.cpp
> ar rv libtest.a test*.o
> g++ main.o libtest.a -o test
>
> then gtest cannot find the test case and pass quickly.
>
> I believe that these two ways are the same in term of linking. So is this
> a bug? or I have wrong idea about the .a and .o?
>
It is not the same.
afaik, in the .a case the linker will drop unrefereced symbols which causes
what you see. Try --whole-archive, like this:

g++ main.o -o test -Wl,--whole-archive libtest.a

**Comment by zhengwx11** [comment]
Got it! Thank you ↑
