### ISSUE TITLE
Release 1.8 Changes missing

### ISSUE THREAD

**Issue by drivehappy** [google/googletest#855]
I've noticed that the 1.8.0 release has been posted. Unfortunately there doesn't seem to be any list of changes/features that are provided in this release (both on the download description and within the CHANGES file)

**Comment by KindDragon** [comment]
I thought that they wanted to fix VS2015 before the release (#811) :cry:

**Comment by Croydon** [comment]
#855

**Comment by KindDragon** [comment]
Related to #1079

**Comment by Klaim** [comment]
This ticket have been created in 2016, a year ago. Why still no change log? Are they too massive?

**Comment by gennadiycivil** [comment]
We are not maintaining CHANGE log
