### ISSUE TITLE
NuGet package "gtest" and Microsoft Visual Studio 2015 (toolset version 1900)

### ISSUE THREAD

**Issue by efistokl** [google/googletest#861]
I have tried to use google test framework as NuGet package.  

When I try to build it I get an error message.
I would like to stress this line: 

```
error LNK2038: mismatch detected for '_MSC_VER': value '1800' doesn't match value '1900' in Source.obj
```

Where Source.obj - is Source.cpp:  

```
#include "gtest/gtest.h"

TEST(test1, case1) {
  EXPECT_EQ(0, 0);
}

int main(int argc, char **argv) {
  ::testing::InitGoogleTest(&argc, argv);
  RUN_ALL_TESTS();
  system("pause");
  return 0;
}
```

I consider it's not good to change toolset in my project configuration because after that I will not be able to install any other package compiled with other toolset versions, won't I?

Also, I've tried to fix a problem using packages called "fix8.dependencies.gtest" and "fix8.dependencies.gtest.symbols" but it didn't help.

I have also tried [this](http://stackoverflow.com/a/36082663/5801858) and [this](http://stackoverflow.com/questions/28886725/how-to-compile-and-link-google-tests-in-c-project-in-visual-studio-2013-but-wi)

**Comment by KindDragon** [comment]
Try this unofficial package https://www.nuget.org/packages/googletest.v140.windesktop.static.rt-dyn/

**Comment by efistokl** [comment]
@KindDragon Thank You, I will try.
But I hope that official plugin will be fixed.

**Comment by efistokl** [comment]
@KindDragon Thank You!  
The unofficial package proposed by you works well.  
I think the issue should remain opened, shouldn't it? (Problem with official package still remains)

**Comment by Eternal21** [comment]
I am confirming the issue with the official package.  The unofficial package fixed it for me as well.

**Comment by jking777** [comment]
I'm also having this problem with the official package.

**Comment by vikhik** [comment]
I am also having the same problem with the official package.

**Comment by convexbytes** [comment]
I have the same problem, which is solved as well by using unofficial package "googletest.v140.windesktop.static.rt-dyn".
Visual C++ 2017

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
