### ISSUE TITLE
ASSERT_NO_THROW(…) should give more information when a std::exception is thrown

### ISSUE THREAD

**Issue by dpelle** [google/googletest#875]
ASSERT_NO_THROW(…) should give more information when an exception is thrown.
At least, when it's a std::exception (or a class that derives from it), it should report the exception#what() string. otherwise when a test fails, it can be difficult to know what exception was thrown.

I saw the same request here with a patch:
http://stackoverflow.com/questions/11439525/googlemock-display-more-detailed-debug-info

Patch at that link was not good enough for my purpose as it requires c++11 and I need to
stick to c++03. So I ended up with this patch. Probably it can be done better (I'm not familiar with internal of Google test):

```
--- gtest/internal/gtest-internal.h 2016-08-23 14:20:55.000000000 0000
+++ gtest/internal/gtest-internal.h 2016-08-23 14:20:55.000000000 0000
@@ -1150,12 +1150,17 @@
 #define GTEST_TEST_NO_THROW_(statement, fail) \
   GTEST_AMBIGUOUS_ELSE_BLOCKER_ \
   if (::testing::internal::AlwaysTrue()) { \
     try { \
       GTEST_SUPPRESS_UNREACHABLE_CODE_WARNING_BELOW_(statement); \
     } \
+    catch (const std::exception& e) { \
+      /* Log the what() string of std::exception to help debugging why test failed. */ \
+      fprintf(stderr, "Warning: GTest caught std::exception [%s]\n", e.what()); \
+      goto GTEST_CONCAT_TOKEN_(gtest_label_testnothrow_, __LINE__); \
+    } \
     catch (...) { \
       goto GTEST_CONCAT_TOKEN_(gtest_label_testnothrow_, __LINE__); \
     } \
   } else \
     GTEST_CONCAT_TOKEN_(gtest_label_testnothrow_, __LINE__): \
       fail("Expected: " #statement " doesn't throw an exception.\n" \
```

**Comment by gennadiycivil** [comment]
@andrei-ng I don't remember, sorry. This was in 2018

**Comment by andrei-ng** [comment]
No worries. Thanks for your reply.
