### ISSUE TITLE
TAP support

### ISSUE THREAD

**Issue by bnoordhuis** [google/googletest#887]
Is the project open to adding TAP output, the [Test Anything Protocol](https://testanything.org/)?

Our CI is built around TAP.  It's probably possible to transform the output of the XML generator into TAP but it seems all around easier to make gtest write it natively.

Refs: https://github.com/nodejs/node/pull/8034

**Comment by adminspotter** [comment]
There exists a TAP listener, https://github.com/kinow/gtest-tap-listener

**Comment by bnoordhuis** [comment]
Yes, I've seen it.  My preference would be for native gtest support, however.

**Comment by kinow** [comment]
On a native gtest support, happy to merge that library with googletest, maybe moving some of its files to the main project. License should be compatible too.
