### ISSUE TITLE
Conflicting export decorations on Windows

### ISSUE THREAD

**Issue by mwoehlke-kitware** [google/googletest#891]
I'm trying to build gtest for [another project](https://github.com/lcm-proj/lcm). Since I don't want to import a special CMake macro for all my tests, I am doing the obvious thing and defining the necessary symbols for correct export decoration on the libraries themselves:

``` cmake
add_library(gtest src/gtest-all.cc)
target_link_libraries(gtest ${CMAKE_THREAD_LIBS_INIT})
target_include_directories(gtest SYSTEM PUBLIC ${PROJECT_SOURCE_DIR}/include)
if(BUILD_SHARED_LIBS)
  target_compile_definitions(gtest
    PRIVATE GTEST_CREATE_SHARED_LIBRARY
    INTERFACE GTEST_LINKED_AS_SHARED_LIBRARY)
endif()

add_library(gtest_main src/gtest_main.cc)
target_link_libraries(gtest_main gtest ${CMAKE_THREAD_LIBS_INIT})
if(BUILD_SHARED_LIBS)
  target_compile_definitions(gtest_main
    PRIVATE GTEST_CREATE_SHARED_LIBRARY)
endif()
```

Unfortunately, due to the way `GTEST_API_` is defined, this results in `main()` having `__declspec(dllimport)` decoration.

(TBH, It's not obvious to me how this ever works; when building `gtest_main.cc`, `main()` needs to be decorated with `__declspec(dllexport)`, while everything else needs to be decorated with `__declspec(dllimport)`, but both are decorated with `GTEST_API_`.)

AFAICT, `gtest_main.cc` needs to define its own ABI decoration symbol based only on if `GTEST_CREATE_SHARED_LIBRARY` is defined, ignoring `GTEST_LINKED_AS_SHARED_LIBRARY`.

**Comment by petersteneteg** [comment]
Aldo having this issue, anyone working on this?

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by petersteneteg** [comment]
This is still an issue!
