### ISSUE TITLE
better std::experimental::string_view support

### ISSUE THREAD

**Issue by VestniK** [google/googletest#907]
std::experimental::string_view has operator<< overload for std::ostream but still printed as collection of chars. The only way to make gtest print string_view value as string is add PrintTo into std::experimental::fundamentals_v1 namespace which is not really great practice.

**Comment by dermojo** [comment]
Quick update:
This has become more annoying since string_view is now in the std namespace (C++ 17).
It's possible to provide an overload of PrintTo in the testing::internal namespace. It would be possible to add this conditionally (by checking __cplusplus for the C++ 17 standard).

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by dermojo** [comment]
I referenced the pull request above.
