### ISSUE TITLE
Does GTest support having child nodes under `<testcase>`? 

### ISSUE THREAD

**Issue by carun** [google/googletest#908]
From [0] I understand that `RecordProperty` can be used, but it is not enough for some use cases. Does GTest support having child nodes under `<testcase>` other than `<failure>`? 

[0] https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md

**Comment by carun** [comment]
@gennadiycivil No comments?

**Comment by gennadiycivil** [comment]
Hello:
NOTE: I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it happens to be inactive since 2017 or so. 

Thank you
