### ISSUE TITLE
Doesn't compile with Clang/C2

### ISSUE THREAD

**Issue by gpakosz** [google/googletest#934]
GoogleTest doesn't compile with Visual Studio's new Clang/C2 giving lots of errors like:

```
error : use of undeclared identifier 'chdir'; did you mean '_chdir'?
```

See https://msdn.microsoft.com/en-us/library/ms235420.aspx

**Comment by gpakosz** [comment]
What's the resolution?

**Comment by gennadiycivil** [comment]
I have been closing old issues. There is no information here to try to do anything. " Visual Studio's new Clang/C2 giving lots of errors like:" What "new Clang"? What version? This has been open since 2016, if still relevant please provide actual details

**Comment by gpakosz** [comment]
Fair enough. Sometimes issues or PRs remain open for a long time also because you maintainers vanish 😉

**Comment by gennadiycivil** [comment]
@gpakosz absolutely. Sorry for any disconnects.
