### ISSUE TITLE
FreeBSD support for death tests

### ISSUE THREAD

**Issue by michelangelo** [google/googletest#938]
Death tests via `(ASSERT | EXPECT)_DEATH` should be supported on FreeBSD.

**Comment by emaste** [comment]
@gennadiycivil Do death tests work on FreeBSD now?

**Comment by gennadiycivil** [comment]
@emaste I dont know, sorry.

**Comment by emaste** [comment]
Death tests were enabled on FreeBSD in b215e30cadd11db7c9f378b57ffecce92aacce37.

**Comment by jbeich** [comment]
On FreeBSD death tests will warn about lack of `GetThreadCount`. I have a [fix](https://github.com/freebsd/freebsd-ports/blob/master/devel/googletest/files/patch-bsd-defines) but cannot upstream as CLA requires Google Account.

https://github.com/google/googletest/blob/2fe3bd994b3189899d93f1d5a881e725e046fdc2/googletest/src/gtest-death-test.cc#L235-L236

**Comment by emaste** [comment]
@jbeich I take it you're unable or unwilling to create a Google account to accept the CLA?

I wonder if there is a way to upstream small patches like this without the CLA?
