### ISSUE TITLE
Compiler error in ASSERT_TRUE with function call 

### ISSUE THREAD

**Issue by alextreib** [google/googletest#940]
Hi,
I have the problem that ASSERT_TRUE(false) doesn't compile due to the following error:

> void value not ignored as it ought to be
>      = ::testing::Message()
> 

Code is the following:
```
int func()
{
	int returnvalue=3;
	if(false)
	{
		return returnvalue;
	}
	else
	{
		ASSERT_TRUE(false);
	}
}
```

Best regards
Alexander Treib

**Comment by Bu11etmagnet** [comment]
`ASSERT_anything` can only be used in functions that return `void` (for example, the `TestBody` methods created by the `TEST`, `TEST_F`, `TEST_P` macros).

**Comment by alextreib** [comment]
Why?
Does it make sense to implement it like that? For EXPECT_anything it doesn't end in an error, although the program continues.

**Comment by Bu11etmagnet** [comment]
`ASSERT_` stops the execution of the test by doing a return:

`ASSERT_TRUE(foo) << "Should be true"` is expanded to

    if ( ... foo ) ; else return AssertHelper(...) = Message() << "Should be true";"

where `AssertHelper::operator=(Message)` returns void.

**Comment by technic** [comment]
So what is a suggested workaround?!

**Comment by ni4** [comment]
Got to this issue as well. Given that `assert()` inside of test's helper functions doesn't bring much of a value (at least in my case), replaced it with throwing an exception.
