### ISSUE TITLE
Comma operator with ASSERT_* family of macros in functions with return value

### ISSUE THREAD

**Issue by stianval** [google/googletest#947]
It seems to be possible to use the ASSERT_* family of macros in functions with return value, provided that a return value of a failing case is specified after a comma operator. For instance
``` C++
bool foo(int x, int y) {
    ASSERT_EQ(x, y), false;  // return false if the assertion fails
    return true;  
}
```
This is because the comma operator has a lower precedence than the bitshift operator and the assignment operator. My guess is that this feature is not easy to hinder, and I guess it can in some cases be desirable, so I think it could be considered to document this instead of stating that the ASSERT_* family of macros can't be used in functions with return value.

**Comment by Bu11etmagnet** [comment]
> Doctor, doctor, it hurts when I do this!
> Don't do it, then.


This is what you get when you use macros :)

ASSERT_XX expands to

    return AssertHelper(__FILE__, __LINE__, ...) = Message()

where Message acts like an ostream, so

    ASSERT_XX << "Howdy";

expands to 

    return AssertHelper(__FILE__, __LINE__, ...) = Message() << "Howdy";

and the `AssertHelper::operator=(Message)` returns void (because it's meant to be used from the `TestBody()` methods which return `void`).

It's up to the user not to use it in a context for which it wasn't designed.

**Comment by stianval** [comment]
I wouldn't say the feature itself is an issue, I actually think it is quite beautiful, and my impression is that many people want to use ASSERT_* family of macros in functions with return values. If they are informed that they can do that, provided that they provide a return value after a comma, they will even be more informed about the workings of the ASSERT_* family of macros, i.e. the macros will only return from the current function. In particular, these users will not end up believing that the macros automagically terminates the test case. :) In that regard, people who try to use ASSERT_* family of macros in functions that are void are actually worse off, since they can actually miss this point.

Nonetheless, in my opinion there is still another important issue here, and that is whether users can rely that this feature is going to stay or not. I deem it likely that it is going to stay, since breaking it is very likely to involve redesigning the whole system, if possible at all. So the feature is there, I think it would be sad if it is denied and shut off. There are so many clever programmers out there, that some of them might actually do right use of it if it was only documented.

**Comment by Bu11etmagnet** [comment]
When I wrote "ASSERT_XX expands to...", that was an implementation detail, and those can change. Documenting implementation details would mean that the implementation can't be changed, even if somebody comes up with an implementation twice as clever.

**Comment by stianval** [comment]
Ah, I see your concern. I have to say I kind of agree, but kind of disagree as well. I agree that the expansion of the macro is an implementation detail, but I disagree in that this particular one can be changed. That is, I suspect it indeed can not be changed to hinder the comma feature without violating the already documented features of the macro.

You see, I suspected the comma feature just by reading the documentation, the clues are:

1. They must be macros, and they must return from the current function. (It is explicitly stated that this is what will happen when they are used in void-functions).
2. They must admit a "tail" of << operators.

If any macro at all permits these two features without also permitting this use of the comma operator, I believe that it must be particularly constructed for that sole purpose, and I think that would be a counterproductive effort.

So I believe that documenting the feature would _not_ be a sacrifice of future liberty. (And I do agree that sacrifices of future liberties should be avoided).
