### ISSUE TITLE
Allow MOCK_METHOD without specifying the argument count

### ISSUE THREAD

**Issue by ugoren** [google/googletest#948]
Currently, you must use the correct MOCK_METHODn macro:
```
MOCK_METHOD2(foo, void(int, int));
MOCK_METHOD3(bar, void(int, int, int));
```
I suggest a variation that works without the number:
```
MOCK_METHOD(foo, void, (int, int));
MOCK_METHOD(bar, void, (int, int, int));
```
Note that the return type is now separate from the argument types.

Implementing this isn't complicated. It's basically this:
```
#define MOCK_METHOD(name, ret, args) MOCK_METHOD##PP_NARG(args)(name, ret args)
```
Where `PP_NARG` is define as in [this StackOverflow answer](http://stackoverflow.com/a/2124385/1111371).
It will be limited to a maximum number of arguments - but so are existing `MOCK_METHODn` macros.
Perhaps there's a more elegant implementation, instead of reducing it to existing macros.

I'm willing to do the development (if I think there's a chance that it will be accepted).

**Comment by sbenzaquen** [comment]
On Tue, Nov 29, 2016 at 10:32 AM, ugoren <notifications@github.com> wrote:

> Currently, you must use the correct MOCK_METHODn macro:
>
> MOCK_METHOD2(foo, void(int, int));
> MOCK_METHOD3(bar, void(int, int, int));
>
> I suggest a variation that works without the number:
>
> MOCK_METHOD(foo, void, (int, int));
> MOCK_METHOD(bar, void, (int, int, int));
>
> Note that the return type is now separate from the argument types.
>
> Implementing this isn't complicated. It's basically this:
>
> #define MOCK_METHOD(name, ret, args) MOCK_METHOD##PP_NARG(args)(name, ret args)
>
> Where PP_NARG is define as in this StackOverflow answer
> <http://stackoverflow.com/a/2124385/1111371>.
> It will be limited to a maximum number of arguments - but so are existing
> MOCK_METHODn macros.
> Perhaps there's a more elegant implementation, instead of reducing it to
> existing macros.
>
> I'm willing to do the development (if I think there's a chance that it
> will be accepted).
>

We have been toying with the idea of one macro to rule them all.
Right now we have a combinatoric explosion of arity * const * template *
calltype.
This is one of the reasons we have not added C++11 support here for
override, final, reference qualification, etc.
Supporting all those combinations would give us hundreds of macros and make
the problem worse.

We discussed a few different approaches last time we talked about this
problem.
The option that was winning is to emulate the order of a regular function
declaration.
eg:

MOCK_METHOD(void, MethodName, (int, double, (map<int,int>)), (const,
override))

iirc, this has a problem with telling apart () from (x) for the argument
list in a portable way.
We could find a workaround for this problem, though.

We have only one shot at making a new macro named "MOCK_METHOD". We want to
use it for the super-macro and not just a small incremental improvement.

If the extended scope didn't scare you away, let me know =)

Thanks, Sam

**Comment by ugoren** [comment]
Not scared (yet).
I'll take a deeper look to see if it can be done as a replacement for the
Tom of macros, not on top of them.

The preprocessor ##, when used with __VA_ARGS__ has a strange and useful
behavior that can help distinguish () from (x).
In x,##_VA_ARGS__, the comma disappears for empty ARGS.

**Comment by sbenzaquen** [comment]
On Tue, Nov 29, 2016 at 2:03 PM, ugoren <notifications@github.com> wrote:

> Not scared (yet).
> I'll take a deeper look to see if it can be done as a replacement for the
> Tom of macros, not on top of them.
>

Ideally, it would be the other way around. The old macros would be aliases
to the new macro.


>
> The preprocessor ##, when used with __VA_ARGS__ has a strange and useful
> behavior that can help distinguish () from (x).
> In x,##_VA_ARGS__, the comma disappears for empty ARGS.
>

That is not portable behavior, as it is explained in that thread you linked.
In particular, it will not work on MSVC.

**Comment by ugoren** [comment]
Of course.
I think we may need GMOCK_METHODn_ macros to still be repeated 11 times.
The new macros will invoke them using the argument count macro, and old
macros will use the new ones, for compatibility.,

**Comment by ugoren** [comment]
Regarding the argument count solution - [this StackOverflow answer](http://stackoverflow.com/a/26685339/1111371)  provides a solution for MSVC.

So if we give up theoretical portability and limit support to MSVC, gcc and Clang, we're fine.

**Comment by ugoren** [comment]
I hit a problem with unprotected commas. I see no way to support them.
I knew all along that they're trouble, but I assumed that they break the existing macros too. 
I see no way around it.

When considering new code, I don't think it's a big deal. A simple typedef lets you avoid it.
But if we want to redefine existing macros to use the new ones, then existing code will break.

The best I can suggest is:
1. Existing macros will stay as they are, and keep supporting unprotected commas.
2. The new generic macros will not support unprotected commas.
3. When introducing new options (e.g. override methods), implement them over the generic macros, and don't support unprotected commas.

**Comment by ugoren** [comment]
I just realized another problem with making existing macros use the new ones - separating return value from arguments.
It's impossible for the preprocessor to convert `MOCK_METHOD1(foo, int(char))` to `MOCK_METHOD(int, foo, (char))`.

Along with the unprotected commas issues, it means that we the old macros can't be aliases for the new macros. They'll have to stay as they are, more or less.

**Comment by sbenzaquen** [comment]
On Wed, Nov 30, 2016 at 4:51 AM, ugoren <notifications@github.com> wrote:

> I just realized another problem with making existing macros use the new
> ones - separating return value from arguments.
> It's impossible for the preprocessor to convert MOCK_METHOD1(foo,
> int(char)) to MOCK_METHOD(int, foo, (char)).
>
It is not impossible.
The old macro has a function signature there. We can extract a type from a
function signature with a trait.

MOCK_METHOD1(name, sig...) would map to
MOCK_METHOD(typename GetReturnType<void(sig...)>::type, name, (typename
GetArg<1, void(sig...)>::type)

That void(x) trick is a simple way to put parens around the type.

> Along with the unprotected commas issues, it means that we the old macros
> can't be aliases for the new macros. They'll have to stay as they are, more
> or less.
>
We can't allow unprotected commas in the new macro if we want to be able to
count.
Users would have to wrap each argument or return type with parens.
Eg: https://godbolt.org/g/K3cpkR

**Comment by ugoren** [comment]
Thanks.
I'll consider this and try to come up with an orderly suggestion of what I
can implement.

I'm not 100% sure if we can do this in a way that supports unprotected
commas in old macros (your suggestion seems to fail if they're in the
return type) - I believe it would be possible.

**Comment by ugoren** [comment]
Updated suggestion:

New internal "Mother of all macros"
---
replacing the `GMOCK_METHODn` family:
```
MOCK_METHOD_BASE(modifiers, nargs, rtype, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10);
```
`modifiers` is a list, a subset of `(CONST, TYPENAME, CALLTYPE(x))`. Concatenation will be used to generate correctly placed `const`, `typename` and call type.
The return and argument types are passed one by one, to help avoid breaking and rebuilding function signatures more than necessary.
I believe it can be implemented as one macro, rather than 11 today, using helper macros such as `IF_AT_LEAST_3(n, x)` (x if n>=3, else nothing). If I missed a pitfall, we might need to duplicate it.

New generic macros
---
Can be used without specifying the argument count.
```
MOCK_METHOD(rtype, method, (arglist));
MOCK_CONST_METHOD(rtype, method, (arglist));
// etc...
```
Question - how do we want to expose the different modifiers? We can either provide create a variety of macros, as today, or a single macro which accepts a modifier list (more generic, but the syntax may look awkward).

Implementing BC macros
---
100% backward compatibility is required.
```
MOCK_METHODn(method, signature);   // Same as today
```
Will use `GetReturnType` and `GetArg` templates to break the signature.
Will be implemented over `MOCK_METHOD_BASE`, not `MOCK_METHOD`.

Unprotected Commas
---
BC macros will support unprotected commas, in the return type and/or arguments, as today.
New macros will not support them in either case.
Documentation should include a suggested workaround, something like this:
```
using map_int_float = map<int, float>;
class MyMock {
public:
    MOCK_METHOD(float, lookup, (map_int_float, int));
};
```
If a user mistakenly uses them, compilation errors may be nasty.

Compiler Support
---
Argument counting will be implemented differently on MSVC and other compilers (i.e. gcc/Clang), following [this StackOverflow answer](http://stackoverflow.com/a/26685339/1111371).
I tested the counting macros on gcc, clang and icc (using [compiler explorer](https://godbolt.org/)) and MS Visual Studio 2012.

**Comment by sbenzaquen** [comment]
Thanks for this work.

On Tue, Dec 6, 2016 at 5:14 AM, ugoren <notifications@github.com> wrote:

> Updated suggestion:
> New internal "Mother of all macros"
>
> replacing the GMOCK_METHODn family:
>
> MOCK_METHOD_BASE(modifiers, nargs, rtype, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10);
>
> modifiers is a list, a subset of (CONST, TYPENAME, CALLTYPE(x)).
> Concatenation will be used to generate correctly placed const, typename
> and call type.
>
We should not ask for uppercase here. They have a higher chance of
conflicting with macros. They could be lowercase.
We would still concatenate them.

> The return and argument types are passed one by one, to help avoid
> breaking and rebuilding function signatures more than necessary.
> I believe it can be implemented as one macro, rather than 11 today, using
> helper macros such as IF_AT_LEAST_3(n, x) (x if n>=3, else nothing). If I
> missed a pitfall, we might need to duplicate it.
>
We should try to avoid variadic at the macro argument level, because it
makes it hard/impossible to add more arguments later.
That is why modifiers and args where proposed initially to be a
parenthesized tuple.

> New generic macros
>
> Can be used without specifying the argument count.
>
> MOCK_METHOD(rtype, method, (arglist));
> MOCK_CONST_METHOD(rtype, method, (arglist));
>
> There should be a single overload.
Otherwise we would still have the combinatoric explosion for const *
override * final * ...

>
> // etc...
>
> Question - how do we want to expose the different modifiers? We can either
> provide create a variety of macros, as today, or a single macro which
> accepts a modifier list (more generic, but the syntax may look awkward).
>
Single macro, with a tuple for modifiers.
The syntax will look close to the regular signature syntax, except we add
some extra commas and parens.

> Implementing BC macros
>
> 100% backward compatibility is required.
>
> MOCK_METHODn(method, signature);   // Same as today
>
> Will use GetReturnType and GetArg templates to break the signature.
> Will be implemented over MOCK_METHOD_BASE, not MOCK_METHOD.
> Unprotected Commas
>
> BC macros will support unprotected commas, in the return type and/or
> arguments, as today.
> New macros will not support them in either case.
> Documentation should include a suggested workaround, something like this:
>
> using map_int_float = map<int, float>;
> class MyMock {
> public:
>     MOCK_METHOD(float, lookup, (map_int_float, int));
> };
>
> If a user mistakenly uses them, compilation errors may be nasty.
>
We can support protected commas. Eg:

class MyMock {
public:
    MOCK_METHOD(float, lookup, ((map<int, float>), int));
};

Compiler Support
>
> Argument counting will be implemented differently on MSVC and other
> compilers (i.e. gcc/Clang), following this StackOverflow answer
> <http://stackoverflow.com/a/26685339/1111371>.
> I tested the counting macros on gcc, clang and icc (using compiler
> explorer <https://godbolt.org/>) and MS Visual Studio 2012.
>
I think we could provide 2 macros. One that does argument counting and one
that doesn't.
The latter can be used in environments where counting is not supported.

**Comment by ugoren** [comment]
I had some difficulties implementing the extraction of types from a signature. I did manage to overcome it, but I'm not sure how good my solution is.

You suggested `typename GetReturnType<void(sig...)>::type`, which I translated to Google Mock's macros as `GMOCK_RESULT_(, GMOCK_ARG_(typename, 1, void(__VA_ARGS__)))`.

The trouble was that, if the method signature is `int()`, the expression `GMOCK_ARG_(typename, 1, void(__VA_ARGS__))` evaluates to `int(*)()`, not `int()`, and then `GMOCK_RESULT_` fails to match the template.

I solved it by adding a bunch of these - `struct Function<R(*)(A1)> : Function<R(A1)> {};`
If I understand correctly, it treats function pointers the same as functions. I hope it doesn't break antything.

**Comment by ugoren** [comment]
Work in progress in my fork - https://github.com/ugoren/googletest

**Comment by ugoren** [comment]
I ran into a trouble regarding compiler support - gcc and Clang work, but `gcc -std=c++11` doesn't.
In this case, counting the arguments fails if there are none.

When using `c++11` (rather than `gnu++11`) gcc extensions are disabled, the argument counting macro returns 1 when there are no arguments.
Then `MOCK_METHOD(int, foo, ())` becomes (sort-of) `MOCK_METHOD1(foo, int())` which is wrong.
Travis-CI uses `-std=c++11` which brought it up.

The best I can do is:
1. Legacy macros would work in all cases.
2. New macros will work in all cases, except functions with no arguments where GNU extensions are disabled.
3. Some self-tests will have to be put under `#ifdef`.

**Comment by sbenzaquen** [comment]
On Tue, Dec 20, 2016 at 8:33 AM, ugoren <notifications@github.com> wrote:

> I ran into a trouble regarding compiler support - gcc and Clang work, but gcc
> -std=c++11 doesn't.
> In this case, counting the arguments fails if there are none.
>
> When using c++11 (rather than gnu++11) gcc extensions are disabled, the
> argument counting macro returns 1 when there are no arguments.
> Then MOCK_METHOD(int, foo, ()) becomes (sort-of) MOCK_METHOD1(foo, int())
> which is wrong.
> Travis-CI uses -std=c++11 which brought it up.
>
> The best I can do is:
>
>    1. Legacy macros would work in all cases.
>    2. New macros will work in all cases, except functions with no
>    arguments where GNU extensions are disabled.
>    3. Some self-tests will have to be put under #ifdef.
>
>
There are some other ways that are also not bulletproof, but work well for
this.
Eg: https://gustedt.wordpress.com/2010/06/08/detect-empty-macro-arguments/

This one works fine, as long as the token passed is not a macro function
itself.

**Comment by ugoren** [comment]
Thanks,  this should work.
I noticed another annoying case - (void)  instead of (). Naturally it will
be treated as 1 arg.
Maybe I can deal with it with some concatenation tricks.
Anyway,  if I can't do it the workaround is trivial.

**Comment by ugoren** [comment]
My fork - https://github.com/ugoren/googletest - now has a working implementation of the feature.

One problem we have is licensing for P99 macros - I created the file gmock-generated-p99.h.pump with content copied from P99 (with P99's license on the top).
P99's authoer, Jens Gustedt, sees this usage positively, but I'm not sure how to do it while complying to the license.

**Comment by fsecilia** [comment]
As far as I can tell, this is the gmock team's preferred solution. What is holding this up? P99's author seems to approve.

**Comment by ugoren** [comment]
I'm glad to see interest.
I don't know how to write a license that gives proper credit to Jens
Gustedt and suits Google Test. Not a big problem but I'm not a license
expert and I ran out of steam trying to figure it out.

On Sep 7, 2017 2:53 AM, "Frank Secilia" <notifications@github.com> wrote:

As far as I can tell, this is the gmock team's preferred solution. What is
holding this up? P99's author seems to approve.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/googletest/issues/948#issuecomment-327643262>,
or mute the thread

**Comment by fsecilia** [comment]
Is the only thing holding this up a license?

**Comment by ugoren** [comment]
Indeed.
The thing works, including self tests, and passes CI on both Linux and
Windows.
Sources which are not original are either from StackOverflow (Windows
macros) or P99 (the author, Jens Gustedt, agrees to use it).

But maybe I should say "almost", because:
1. I didn't update documentation.
2. I didn't update gmock_doctor (not sure it's relevant).

**Comment by Nurdok** [comment]
@ugoren perhaps Jens Gustedt or you, on his behalf, can put the P99 code on GitHub with the MIT License?

**Comment by ugoren** [comment]
Hi Amir,

Here's what Jens wrote to me about the license:

I have no problem to grant a specific license for that code extraction
from P99. So could you just produce a header for
gmock-generated-p99.h.pump that

 - keeps the copyrights as they are
 - adds a copyright for yourself for the work that you have done here
 - states this is an extract of P99
 - applies license terms that are compatible with the rest of google mock?


I suggested using the same license as in all Google Test files, with Jens's
name added in addition to Google.
Jens's reply was:

Instead I would go for something like

// Copyright 2017, Jens Gustedt
//                 Uri Goren
//
// This code has originally been published as part of the P99 project,
// http://p99.gforge.inria.fr, and is reproduced here with explicit
// permission by its author granting a modification of its
// license to the text as stated below.

And then go on with the license blabla.


If this is good enough, then I'll update my fork (
https://github.com/ugoren/googletest) with it.
If not, I can mail both Jens and you and we can iron this out.

This whole thing doesn't look like a serious problem. The trouble is that I
don't know much about licensing, what's important and what isn't.

**Comment by Nurdok** [comment]
@ugoren just to clarify - I work at Google, but I'm not a Google Test _owner_, so I can't accept your changes on my own, etc. I'm just trying to help as I think this change is for the best.

In general, Google will need open source projects to have an appropriate license. The MIT license is good for that.

**Comment by ugoren** [comment]
Hi,

If I understand Jens Gustedt's requirements correctly, it's OK to use a BSD
license, identical to other Google Test files, but put him and me as
authors, instead of Google.
This makes sense, because the file doesn't contain anything developed by
Google.

So we get this license text:

// Copyright 2018, Jens Gustedt,
//                 Uri Goren
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Does this seem OK?
I'm also sending the same to Jens, hopefully it's OK with him.

**Comment by ugoren** [comment]
I just updated my clone - https://github.com/ugoren/googletest - with the new license string.
I also renamed all macros to have a __GMOCK prefix.

Should I submit a pull request?

Thanks.

**Comment by fsecilia** [comment]
What do we need to do to get movement on this? Working around noexcept methods is getting really old.

**Comment by fsecilia** [comment]
I certainly do, but I know there's a history of ignoring them in this project. Maybe that's changing with all of the activity of late.

**Comment by ugoren** [comment]
I'll try and hope for the best.
I did get some encouraging feedback from the maintainers when I started.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
