### ISSUE TITLE
Testsuite fails on many targets in Debian

### ISSUE THREAD

**Issue by glaubitz** [google/googletest#949]
Hello!

Just as of recently, Debian's APT maintainers decided to use the new googletest C++ framework to do perform build time unit tests. Unfortunately, this means that APT now became unusable on several on at least eight of Debian targets because googletest has just too many issues to be portable enough to work on all these targets.

For example, the testsuite fails completely on sparc64 (which is a current CPU architecture developed by Oracle) [1]:

0% tests passed, 60 tests failed out of 60

Total Test time (real) =   4.38 sec

The following tests FAILED:
	  1 - gmock-actions_test (SEGFAULT)
	  2 - gmock-cardinalities_test (SEGFAULT)
	  3 - gmock_ex_test (SEGFAULT)
	  4 - gmock-generated-actions_test (ILLEGAL)
	  5 - gmock-generated-function-mockers_test (SEGFAULT)
	  6 - gmock-generated-internal-utils_test (SEGFAULT)
	  7 - gmock-generated-matchers_test (SEGFAULT)
	  8 - gmock-internal-utils_test (ILLEGAL)
	  9 - gmock-matchers_test (ILLEGAL)
	 10 - gmock-more-actions_test (SEGFAULT)
	 11 - gmock-nice-strict_test (SEGFAULT)
	 12 - gmock-port_test (SEGFAULT)
	 13 - gmock-spec-builders_test (SEGFAULT)
	 14 - gmock_link_test (SEGFAULT)
	 15 - gmock_test (SEGFAULT)
	 16 - gmock_stress_test (SEGFAULT)
	 17 - gmock_use_own_tuple_test (SEGFAULT)
	 18 - gmock-more-actions_no_exception_test (SEGFAULT)
	 19 - gmock_no_rtti_test (SEGFAULT)
	 20 - gtest-death-test_test (SEGFAULT)
	 21 - gtest_environment_test (SEGFAULT)
	 22 - gtest-filepath_test (SEGFAULT)
	 23 - gtest-linked_ptr_test (SEGFAULT)
	 24 - gtest-listener_test (SEGFAULT)
	 25 - gtest_main_unittest (SEGFAULT)
	 26 - gtest-message_test (SEGFAULT)
	 27 - gtest_no_test_unittest (SEGFAULT)
	 28 - gtest-options_test (SEGFAULT)
	 29 - gtest-param-test_test (SEGFAULT)
	 30 - gtest-port_test (SEGFAULT)
	 31 - gtest_pred_impl_unittest (ILLEGAL)
	 32 - gtest_premature_exit_test (SEGFAULT)
	 33 - gtest-printers_test (SEGFAULT)
	 34 - gtest_prod_test (SEGFAULT)
	 35 - gtest_repeat_test (SEGFAULT)
	 36 - gtest_sole_header_test (SEGFAULT)
	 37 - gtest_stress_test (SEGFAULT)
	 38 - gtest-test-part_test (SEGFAULT)
	 39 - gtest_throw_on_failure_ex_test (SEGFAULT)
	 40 - gtest-typed-test_test (SEGFAULT)
	 41 - gtest_unittest (SEGFAULT)
	 42 - gtest-unittest-api_test (SEGFAULT)
	 43 - gtest-death-test_ex_nocatch_test (SEGFAULT)
	 44 - gtest-death-test_ex_catch_test (SEGFAULT)
	 45 - gtest_no_rtti_unittest (ILLEGAL)
	 46 - gtest-tuple_test (SEGFAULT)
	 47 - gtest_use_own_tuple_test (SEGFAULT)
	 48 - gtest_break_on_failure_unittest (Failed)
	 49 - gtest_catch_exceptions_test (Failed)
	 50 - gtest_color_test (Failed)
	 51 - gtest_env_var_test (Failed)
	 52 - gtest_filter_unittest (Failed)
	 53 - gtest_help_test (Failed)
	 54 - gtest_list_tests_unittest (Failed)
	 55 - gtest_output_test (Failed)
	 56 - gtest_shuffle_test (Failed)
	 57 - gtest_throw_on_failure_test (Failed)
	 58 - gtest_uninitialized_test (Failed)
	 59 - gtest_xml_outfiles_test (Failed)
	 60 - gtest_xml_output_unittest (Failed)

I have no idea how googletest managed to do that, but it just means the software is currently highly unportable "as is", despite being written in C++.

Adrian

> [1] https://buildd.debian.org/status/fetch.php?pkg=googletest&arch=sparc64&ver=1.8.0-3&stamp=1480450609

**Comment by glaubitz** [comment]
Additional comment: You can use qemu to test the framework on various platforms like m68k, sh4, sparc64 and so on.

**Comment by smr99** [comment]
Oddly: the vast majority of these failures only appear when optimisation is disabled -- which I did due to issue #845.  The most recent Debian upload uses optimization and only one issue remains: gtest-port_test fails on Debian/m68k, specifically GetThreadCountTest.ReturnsCorrectValue.  It looks like the kernel is reporting always 0 threads.

The issue is being tracked in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=846464 for details.
