### ISSUE TITLE
gmock_gen.py cannot find class after a forward declared enum

### ISSUE THREAD

**Issue by hugoholgersson** [google/googletest#950]
**Steps to reproduce:**
chromium/src/testing/gmock/scripts/generator$ ./gmock_gen.py ../../../../third_party/WebKit/public/platform/WebMediaPlayerClient.h

**Actual:** `No class found in ../../../../third_party/WebKit/public/platform/WebMediaPlayerClient.h`
**Expected:** MockWebMediaPlayerClient is outputed.

This bug surfaced after https://codereview.chromium.org/2480003002/patch/160001/170027 .

**Comment by hugoholgersson** [comment]
Still reproducible on chromium ToT:

```
/bepo/trunk/src/third_party/googletest/src/googlemock/scripts/generator$ ./gmock_gen.py /bepo/trunk/src/third_party/WebKit/public/platform/WebMediaPlayerClient.h
No class found in /bepo/trunk/src/third_party/WebKit/public/platform/WebMediaPlayerClient.h
```

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
