### ISSUE TITLE
'gtest/internal/gtest-port-arch.h' not found building Xcode project after including gtest.h

### ISSUE THREAD

**Issue by FlashSheridan** [google/googletest#953]
After adding #include "gtest/gtest.h" to main.cpp as instructed in Primer.md, in an Xcode project set up as in XcodeGuide.md (with corrections, e.g., as in bug #951), compilation fails with 

> error: 'gtest/internal/gtest-port-arch.h' file not found.  

This seems to be because gtest-port-arch.h is missing from https://github.com/google/googletest/blob/master/googletest/xcode/gtest.xcodeproj/project.pbxproj, though, e.g., gtest-port.h is present. The entire directory Headers/internal/custom seems to be missing as well.
    After correcting both the above omissions by manually copying the files into the framework, compilation succeeds, though linking fails for  testing::internal::StringStreamToString(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >*).

Here’s more of the compilation error message:

> In file included from /Volumes/Norlamin/Users/flash/Documents/git/New_Code/Programming_Exercises/Other learning projects/String Play/GooTests/main.cpp:11:

> In file included from /Volumes/Norlamin/Users/flash/Documents/git/New_Code/Programming_Exercises/Other learning projects/String Play/GooTests/gtest.framework/Headers/gtest.h:58:

> In file included from /Volumes/Norlamin/Users/flash/Documents/git/New_Code/Programming_Exercises/Other learning projects/String Play/GooTests/gtest.framework/Headers/internal/gtest-internal.h:40:

> /Volumes/Norlamin/Users/flash/Documents/git/New_Code/Programming_Exercises/Other learning projects/String Play/GooTests/gtest.framework/Headers/internal/gtest-port.h:281:10: fatal error: 'gtest/internal/gtest-port-arch.h' file not found

> #include "gtest/internal/gtest-port-arch.h"

**Comment by skeid21** [comment]
I'm wondering if there are long term plans to support macOS.  Could a maintainer of the project speak to that?

**Comment by imadsco** [comment]
did you get a fix to that ?

**Comment by skeid21** [comment]
FlashSheridan mentioned this is an issue with header copy phases for the generated framework.  You can adjust the header copy phases to pull in the missing headers.

**Comment by kdawgwilk** [comment]
I also think you can re-run CMake to generate the Xcode project as well.

**Comment by 4brunu** [comment]
https://github.com/google/googletest/pull/725 got merged yesterday to master, maybe this fix the issue.
Can anyone confirm this?

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
