### ISSUE TITLE
Windows background colour

### ISSUE THREAD

**Issue by gvanem** [google/googletest#956]
Currently the `googletest/src/gtest.cc` assumes the Windows console has a black background colour giving IMHO this ugly output:
![google-test-color](https://cloud.githubusercontent.com/assets/945271/21012220/3f14bef2-bd55-11e6-9336-98b461a5cf63.png)

I think this would be nicer:
![google-test-color2](https://cloud.githubusercontent.com/assets/945271/21012251/6b6e0f62-bd55-11e6-8f4e-ff6eb93ea23e.png)

with this simple patch:
```
--- a/googletest/src/gtest.cc 2016-12-08 12:54:10
+++ b/googletest/src/gtest.cc 2016-12-08 14:39:52
@@ -2986,8 +2986,8 @@
   // SetConsoleTextAttribute call lest it affect the text that is already
   // printed but has not yet reached the console.
   fflush(stdout);
-  SetConsoleTextAttribute(stdout_handle,
-                          GetColorAttribute(color) | FOREGROUND_INTENSITY);
+  const WORD new_color_attrs = (old_color_attrs & ~7) + (GetColorAttribute(color) | FOREGROUND_INTENSITY);
+  SetConsoleTextAttribute(stdout_handle, new_color_attrs);
   vprintf(fmt, args);

   fflush(stdout);
```

**Comment by gvanem** [comment]
Close and bye!

**Comment by tanzislam** [comment]
Good suggestion; raise a PR! :slightly_smiling_face:
