### ISSUE TITLE
Qualifier gets removed when header is using default value

### ISSUE THREAD

**Issue by Lorac** [google/googletest#961]
When auto-generating mocks, if you use default value with `const` or `&` in your header files. The mock generator will remove `const` and `&` thereby calling the real object and not the mock.

method header :
`void action(const std::string& x, const int y = 5);`

after mocking : 
`MOCK_METHOD2(action, void(std::string, int));`

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
