### ISSUE TITLE
Google Mock documentation contains broken link

### ISSUE THREAD

**Issue by VermillionAzure** [google/googletest#972]
> Using Google Mock Without Google Test
>
>Google Mock is not a testing framework itself. Instead, it needs a testing framework for writing tests. Google Mock works seamlessly with Google Test, but you can also use it with any C++ testing framework.

The **any C++ testing framework** part has a broken link. Can someone fix it?

**Comment by sejr** [comment]
I've had a [pull request](https://github.com/google/googletest/pull/874) open to solve this issue for quite some time now.

**Comment by VermillionAzure** [comment]
Great! Let's see if this gets noticed.

**Comment by hethi** [comment]
As the PR is merged, can somebody close the issue?
