### ISSUE TITLE
More strict floating point comparison.

### ISSUE THREAD

**Issue by kkimdev** [google/googletest#973]
I'm writing a floating point util library and I need to distinguish positive zero and negative zero.

```C++
EXPECT_NE(0.0f, -0.0f);
```

Can we add a macro for more strict floating point comparison?  If adding directly to GTest not desired, what would be a recommended way of achieving this with GTest?

**Comment by sbenzaquen** [comment]
On Thu, Dec 29, 2016 at 6:23 PM, Kibeom Kim <notifications@github.com>
wrote:

> I'm writing a floating point util library and I need to distinguish
> positive zero and negative zero.
>
> EXPECT_NE(0.0f, -0.0f);
>
> Can we add a macro for more strict floating point comparison?
>
We don't intend to add more macros for expectations.

> If adding directly to GTest not desired, what would be a recommended way
> of achieving this with GTest?
>
Use gMock's matchers. They are superior to new macros, as they are
composable and work in other contexts.

Eg:

MATCHER_P(MyFloatEq, v, "") {
  return arg == v && std::signbit(arg) == std::signbit(v);
}
...

EXPECT_THAT(0.0f, Not(MyFloatEq(-0.0f)));

**Comment by kkimdev** [comment]
Thanks!
