### ISSUE TITLE
Compile failure test support.

### ISSUE THREAD

**Issue by kkimdev** [google/googletest#974]
Sometimes we want ensure certain code doesn't compile, for example,

```C++
struct B
{
    explicit B(int) { }
};
 
int main()
{
    // The following is a compiler error, and should be a compile failure.
    B b1 = 1;
}
```

It would be nice if GTest can test compile failures.

**Comment by gennadiycivil** [comment]
Non-Compile checking is usually responsibility of the build tools, not libraries
