### ISSUE TITLE
Buggy markdown in CookBook.md

### ISSUE THREAD

**Issue by jlebar** [google/googletest#979]
See:

https://github.com/google/googletest/blob/master/googlemock/docs/CookBook.md#1-to-0-and-returns-argument-0

This shouldn't be a heading.  It also looks like the table in this section is not being picked up by github's markdown parser.

**Comment by jlebar** [comment]
Another broken table: https://github.com/google/googletest/blob/master/googlemock/docs/CookBook.md#using-the-action-objects-type

**Comment by hethi** [comment]
Seems to be fixed in PR #1137 - can somebody close the issue?

**Comment by jlebar** [comment]
Yes, both seem to be fixed.
