### ISSUE TITLE
Visual Studio 2015 Build Issues

### ISSUE THREAD

**Issue by badbadc0ffee** [google/googletest#987]
The Visual Studio 2015 build fails because an excetion is thrown from the destructor `~CxxExceptionInDestructorTest()`.
In C++11, a user defined destructor is noexcept(true) by default unless it is explicitly declared `noexcept(false)`.
The test case in `gtest_catch_exceptions_test_.cc` is already guarded and excluded if `__GXX_EXPERIMENTAL_CXX0X__` is set or `__cplusplus` greater than 201103. MSVC 2015 still does not set the latter symbol such that it would claim to comply with recent C++ standards. Instead, a check for the symbol `_MSC_VER` could be added.

Moreover `hash_map` and `has_set` are now deprecated. One can silence the warnings for use of these deprecated containers by defining the preprocessor symbol `_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS`. Alternatively, `GTEST_HAS_HASH_MAP_` could remain undefined when compiling with MSVC 2015 or later.

**Comment by KindDragon** [comment]
Should be fixed by PR #811

**Comment by KindDragon** [comment]
Can be closed. PR #1218 fixed this
