### ISSUE TITLE
Incorrect Shared Library Flag

### ISSUE THREAD

**Issue by kdatta** [google/googletest#992]
The README.md says to compile gtest as a shared library use -DGTEST_CREATE_SHARED_LIBRARY=1. However, cmake does not recognize this flag, it recognizes -DBUILD_SHARED_LIBS=ON flag. The command which works is:
$ mkdir build
$ cd build
$ cmake  -DBUILD_SHARED_LIBS=ON ${GTEST_DIR}

I believe the documentation is wrong!

**Comment by concatime** [comment]
I can confirm, same issue here. `Manually-specified variables were not used by the project: GTEST_CREATE_SHARED_LIBRARY`.

**Comment by gennadiycivil** [comment]
I believe this issue is "old" , see code http://go/gh/google/googletest/blob/29b47e45cfd0b30f8e7efd93e7ea34c8343012b3/googletest/include/gtest/internal/gtest-port.h#L101

**Comment by dinord** [comment]
Feel free to re-open as a new issue, using the bug report template.
