### ISSUE TITLE
Mocking factory methods that return a std::unique_ptr to inject a mock object with expectations

### ISSUE THREAD

**Issue by noizefloor** [google/googletest#994]
I find myself using lots of factories lately to inject mock objects. The factories are usually implementing an interface and are injected thru the constructor. In my tests I usually create an instance of my mock object, managed as a std::unique_ptr, set my expectation on this mock object and set expectations on my mocked factory to return the unique_ptr by move. If I need to set different expectations on the mock object at a later point and usually also hold a raw pointer on the mock object.
This works great, as long as the factory method is only called once. If the factory method is called a second time, the unique_ptr is already moved and cannot be used anymore. In such a case I usually let the factory method invoke a lambda that creates the unique_ptr, sets the expectations on the new instance of the mock object and returns it by move. This also works pretty good as long as you don't have to set different expectations on the already injected mock objects. Yeah I know this is usually the point at which you should realize that the structure of the code you're testing might not be that great, but things happen ;)

As both solutions were not really satisfying I implemented a proxy class that implements the same interface as the mock object. The proxy class simply delegates all calls to the given instance of the mock object. Now I was able to let the factory method return a new unique_ptr with an instance of the proxy class and the expectations could be set on the main mock object. So far so good. The only problem is that now you've got to create a mock and a proxy class implementation every time an mock object needs to be returned as a unique_ptr.

I thought maybe it would be possible to teach a mock class to create a clone/proxy of itself. This is a rough implementation of what I came up with:

```
#include <gtest/gtest.h>
#include <gmock/gmock.h>
#include <memory>

using namespace testing;


//////////////////////////////////////////////////////////////////////////

template <typename InterfaceType, typename MockType>
class CloneableMock : public InterfaceType
{
public:
    std::unique_ptr<InterfaceType> clone()
    {
        auto clone = std::make_unique<MockType>();
        clone->_delegate = this;
        return std::unique_ptr<InterfaceType>(clone.release());
    }

protected:
    InterfaceType* _delegate = nullptr;
};

#define CLONEABLE_GMOCK_METHOD0_(tn, constness, ct, Method, ...) \
  GMOCK_RESULT_(tn, __VA_ARGS__) ct Method( \
      ) constness { \
    if (_delegate) return _delegate->Method();\
    GTEST_COMPILE_ASSERT_((::testing::tuple_size<                          \
        tn ::testing::internal::Function<__VA_ARGS__>::ArgumentTuple>::value \
            == 0), \
        this_method_does_not_take_0_arguments); \
    GMOCK_MOCKER_(0, constness, Method).SetOwnerAndName(this, #Method); \
    return GMOCK_MOCKER_(0, constness, Method).Invoke(); \
  } \
  ::testing::MockSpec<__VA_ARGS__>& \
      gmock_##Method() constness { \
    GMOCK_MOCKER_(0, constness, Method).RegisterOwner(this); \
    return GMOCK_MOCKER_(0, constness, Method).With(); \
  } \
  mutable ::testing::FunctionMocker<__VA_ARGS__> GMOCK_MOCKER_(0, constness, \
      Method)

#define CLONEABLE_MOCK_CONST_METHOD0(m, ...) CLONEABLE_GMOCK_METHOD0_(, const, , m, __VA_ARGS__)

//////////////////////////////////////////////////////////////////////////
// Test Interface
//////////////////////////////////////////////////////////////////////////
class ITestMock
{
public:
    virtual ~ITestMock() {}

    virtual std::string toString() const = 0;
};

//////////////////////////////////////////////////////////////////////////
// A test implementation of ITestMock, which is cloneable
//////////////////////////////////////////////////////////////////////////
class TestMock : public CloneableMock<ITestMock, TestMock>
{
public:
    TestMock() {}
    virtual ~TestMock() {}

    CLONEABLE_MOCK_CONST_METHOD0(toString, std::string());
};

//////////////////////////////////////////////////////////////////////////
// Tests
//////////////////////////////////////////////////////////////////////////

class CloneableMock_UnitTest : public testing::Test
{
protected:
    void SetUp() override
    {
        _testMock = std::make_unique<TestMock>();
    }

    void TearDown() override
    {
        _testMock.reset();
    }

    std::unique_ptr<TestMock> _testMock;
};

TEST_F(CloneableMock_UnitTest, functionCall)
{
    EXPECT_CALL(*_testMock, toString()).WillOnce(Return("Test"));

    EXPECT_EQ("Test", _testMock->toString());
}

TEST_F(CloneableMock_UnitTest, clone)
{
    EXPECT_CALL(*_testMock, toString()).WillOnce(Return("Test"));

    auto clone = _testMock->clone();

    EXPECT_EQ("Test", clone->toString());
}
```

Basically the idea is that a cloneable mock inherits from the template class CloneableMock. The template parameters are the interface type and the mock class type. Instead of the normal MOCK_METHODE macros you would use the CLONEABLE_MOCK_ macros. The CloneableMock class would hold a pointer to the original mock object. This pointer gets set when the mock object is cloned. If the pointer is not nullptr the object acts as a proxy and delegates all calls to mocked methods to the original mock object.

I've got to admit I feel a bit lost when I look inside the google mock code. That why I would like to get your input.

- Is this idea usable at all or should we be more focused to avoid situations in which we would need something like that?
- Would it be better, to maybe not inherit from CloneableMock, but instead use a macro to add the delegation pointer and the clone() method to the mock class?

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
