### ISSUE TITLE
CaptureTest is guarded by too-specific platform test

### ISSUE THREAD

**Issue by gareth-rees** [google/googletest#999]
In gtest-port_test.cc, four test cases are guarded like this:
```
#if !GTEST_OS_WINDOWS_MOBILE

TEST(CaptureTest, CapturesStdout) { //...
TEST(CaptureTest, CapturesStderr) { //...
TEST(CaptureTest, CapturesStdoutAndStderr) { //...
TEST(CaptureDeathTest, CannotReenterStdoutCapture) { //...

#endif  // !GTEST_OS_WINDOWS_MOBILE
```
But this platform test is too specific: GTEST_OS_WINDOWS_MOBILE is not the only platform that lacks stream redirection: the platforms GTEST_OS_WINDOWS_PHONE and GTEST_OS_WINDOWS_RT also lack this feature. This means that the test cases do not compile on these platforms.

The guard on !GTEST_OS_WINDOWS_MOBILE should be replaced with a guard on the appropriate feature test, that is, GTEST_HAS_STREAM_REDIRECTION.

**Comment by gennadiycivil** [comment]
Stale, closing
